### ISSUE TITLE
HTTP does not support UpnEndpointIdentity

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#10]
The ctor currently throws PlatformNotSupportedException

**Comment by zhenlan** [comment]
With [this](https://github.com/dotnet/wcf/commit/4a9fe667bbe2eeb035306378bb9c3b09ba22db60), this should only be an issue for UWP.

**Comment by iamjasonp** [comment]
This is a little bit more nuanced: 

* **On UWP,** the class can not be constructed 

* On other platforms, UpnEndpointIdentity can be constructed, and: 
  * In HTTP scenarios, the UPN is not passed on due to dotnet/ corefx#4502
  * In Windows TCP scenarios, the credential will be passed along on supported platforms.
  * In non-Windows TCP scenarios, #946, #1262 prevents cases from working at the moment.

**Comment by roncain** [comment]
Tests disabled with Issue(10) now pass for me on Windows when run manually.

**Comment by roncain** [comment]
Closing because #1502 appears to have fixed this.  I will open a new PR that re-enables the tests previously disabled by issue #10.

**Comment by roncain** [comment]
Reopening -- this issue exists only in UWP, even after PR #1502.

**Comment by roncain** [comment]
Retesting in UWP showed these tests pass now, so PR #1560 has been opened to re-enable them.

**Comment by roncain** [comment]
Closing now that #1560 has been merged.  I manually tested this against NET Native running against a self-hosted service running on a 2nd machine, and passing explicit credential in TestProperties.
