### ISSUE TITLE
Create a suite of stress tests for WCF client

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#100]
These stress scenarios would cover wide functional areas in System.ServiceModel.* (e.g. simple repetition of various API calls) and also cover "interesting" stress scenarios such as concurrent usage of shared resources and validation of thread safety claims of certain APIs. 

The stress tests should be open sourced and should have not dependencies on any internal harness code.

**Comment by SajayAntony** [comment]
You should also update them to be unit testable. 
We do not want the stress test to be skipped during compile or outerloop. 
/cc @dmetzgar

**Comment by zhenlan** [comment]
@KKhurin can you please update this issue and close if appropriate.

**Comment by KKhurin** [comment]
After discussing it with the WCF team we decided to not pursue running stress tests in the outer loop.
The stress tests rely on very stable contracts and did not get broken a single time in the past so making them part of unit tests does not seem to bring much benefits. 

However corefx team might decide to use unit tests to run stress. In this case we'll reevaluate this work item and create specific unit tests for them.
