### ISSUE TITLE
Code cleanup of IISHostedWcfService initial checkin

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1005]
This issue tracks the code review comments from PR #995 that were not done in the initial checkin.
1. Move types shared by clients and server into folder under App_code ("servicetypes"? "sharedtypes"?) so they can be included by client projects.  Avoid code duplication.
2. Consider moving all service implementations from App_code into a new folder ("App_code\testservices"?) the same way the hosts have their own folder "testhosts"
3. Rename Util.cs to be more specific about what it does, and move the service interfaces to the new shared folder in (1) above
4. Run CodeFormatter to fix up a lot of little formatting issues
5. Remove old Bridge-specific names from files and classes (ex: "Resources")

**Comment by hongdai** [comment]
The server code has been cleaned up along the way.
