### ISSUE TITLE
use the standard IIS ports for self hosted test service

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1016]
Investigate if it's feasible to use the standard IIS ports for self hosted test service. Thus we don't need to open so many ports.

**Comment by zhenlan** [comment]
IIS uses these 3 ports for all our tests

- 80 for HTTP
- 443 for HTTPS
- 808 for NetTcp

For 80 (HTTP) and 443 (HTTPS), there are no concerns to have self hosted service using these same ports by default as long as people have a way to change to something else when they need to.

For nettcp working on IIS, it requires TCP Port Sharing feature enabled on the machine. If we want to use the same port (808) as IIS, we need to make sure TCP Port Sharing is available to self hosted service as we don't want to add extra setup need to developers. @hongdai, maybe this is a scenario you can take a further look?

cc: @mconnew

**Comment by Lxiamail** [comment]
Low priority. Close it for now.
