### ISSUE TITLE
Create end-to-end Duplex scenario test

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#104]
Task is to update the standalone test service to expose a duplex service and to add basic end-to-end tests to verify it works properly.

**Comment by iamjasonp** [comment]
I'm actually working on something like this to verify #90 / #91...

**Comment by StephenBonikowsky** [comment]
@iamjasonp  I used what you started as the basis for the pull request I just made. Opened Issue111 for product bug.

**Comment by StephenBonikowsky** [comment]
Also, there are a few little things in this PR that I really should clean-up before it gets merged but after you and I spending the last couple of days on this I wanted to get something out there before I left today that can be used to reproduce the product issue.
