### ISSUE TITLE
Modify PRService return HTTP error codes 

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#1059]
Suggested improvement per: https://github.com/dotnet/wcf/pull/1054/files#r60516164

Currently, the PRService uses 400 and 500 to distinguish the difference between a likely issue with server setup, and a likely issue with client parameters passed in. @zhenlan discovered in testing that, in practice, it was incredibly hard to distinguish what errors were coming from IIS and what errors were coming from the PRService. 

We should consider distinguishing the 4xx and 5xx error codes that we emit from the normal 400/500 error codes. Possible solutions: 
1.  ~~Use an extension code to the status such as 400.xxx~~ (unfortunately, this doesn't seem to show up when inspecting the responses
2. Modify the reason phrase (e.g., modify "Bad Request" to "Bad Request - PRService error" 
3. Modify the status code (e.g., define 48x and 58x as our own errors)

Each has its merits, and it's probably worth a little bit of discussion before changing this. I am leaning towards option 2 above as it allows us to both use well-known status codes and provides a good description that can be inspected in the F12 developer tools. 

I tend not to like option 3 as this is, for better or for worse, going to be "public API" even though it's a test tool - I would prefer not having anyone have depend on it at the moment, but am certainly open to this if we decide that consumers of the PRService would need this type of API definition

**Comment by iamjasonp** [comment]
Aside: usually you can use the browser F12 developer tools to see the output that PRService gave. If you see no output, typically this is an IIS problem

**Comment by zhenlan** [comment]
PRService became stable. Normally we need to use browser F12 for debugging anyway. The change is not necessary.
