### ISSUE TITLE
Add scenario test coverage of ClientBase and ClientBase<T>

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1073]
ClientBase and ClientBase<T> have very low code coverage numbers, and needs to be improved.  These correspond to the wrapper classes that SvcUtil generates, so it is vital all its public entry points are tested.  Notably lacking:
- most property getters
- any of the events (OnClosing, etc.)
- any asynchronous handling (async open and close)
- checking that the State property is correct (ex: 'Closing' when the Closing event fires, 'Closed' after it is closed, etc.)

**Comment by zhenlan** [comment]
@hongdai, a potentially interesting idea to deal with this is to 1. expose mex of all our endpoints 2. generate proxy code by using .Net Core version of svcutil.exe and then test it.

**Comment by roncain** [comment]
@zhenlan and @hongdai -- this issue as written can be closed due to PR's #1666 and #1685.
But I didn't want to close it because of the conversation of mex and svcutil above.
Feel free to close this or tell me to.

**Comment by zhenlan** [comment]
@hongdai I think you've done 1. and is in progress of doing 2?

> 1. expose mex of all our endpoints 2. generate proxy code by using .Net Core version of svcutil.exe and then test it
