### ISSUE TITLE
[rc2] Running outerloop build causes error 

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#1079]
When running an outerloop build in OSX RC2 branch, this issue manifests. From an initial look, it's not apparent to me why this is an issue, as `delimiterIndex` is defined on the line immediately above the line referencing this variable. 

This seems to manifest itself only when building outerloop, OSX, in RC2. No such issue on Ubuntu - see http://dotnet-ci.cloudapp.net/job/dotnet_wcf/job/master/job/outerloop_osx_release_rc2/4/consoleFull

```
System/IdentityModel/Claims/X509CertificateClaimSet.cs(455,63): error CS0103: The name 'delimiterIndex' does not exist in the current context [/Users/dotnet-bot/j/workspace/dotnet_wcf/master/outerloop_osx_release_rc2/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
15:59:38 System/IdentityModel/Claims/X509CertificateClaimSet.cs(459,77): error CS0103: The name 'delimiterIndex' does not exist in the current context [/Users/dotnet-bot/j/workspace/dotnet_wcf/master/outerloop_osx_release_rc2/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
15:59:38 System/IdentityModel/Claims/X509CertificateClaimSet.cs(461,46): error CS0103: The name 'delimiterIndex' does not exist in the current context [/Users/dotnet-bot/j/workspace/dotnet_wcf/master/outerloop_osx_release_rc2/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
```

**Comment by iamjasonp** [comment]
(edit the title because it doesn't look like a #if condition issue anymore)

**Comment by zhenlan** [comment]
@iamjasonp please take a look what went wrong. We do have supported feature table to fill out and we would like to know what works and what not on OSX for RC2.

**Comment by iamjasonp** [comment]
This no longer repros, though no changes were made to the code. Might have been a machine issue. 

A build was run against the rc2 bits against OSX and only failures related to Bridge were reported. http://dotnet-ci.cloudapp.net/job/dotnet_wcf/job/master/job/outerloop_osx_release_rc2/2/console

Closing.
