### ISSUE TITLE
CustomTextMessageEncoder_Http_RequestReply_Streamed test fails due to stream length

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1080]
The recently added test CustomTextMessageEncoder_Http_RequestReply_Streamed assert fails due to mismatching stream length.  It expects 86016 bytes but finds 86019.  

This test appears to have worked at one point when it was using the Bridge resources but has ceased to work since moving to the new test infrastructure.  During that time we also advanced to more recent version of the CoreFx packages and might have inadvertently caught a behavioral change in lower levels of code.

**Comment by mconnew** [comment]
This is caused by a change in the service I made which was reverted. The service is adding a BOM when copying the input stream to a string and back to a stream again. A different overload of the method for fetching the encoding for UTF8 needs to be used to specify not to emit the BOM.

**Comment by roncain** [comment]
Thanks @mconnew -- could you provide that overload for me to incorporate.  I'm in the process of porting those tests onto the new infrastructure, and it would be great to check-in clean.

**Comment by mconnew** [comment]
I can do it when get in the office or you could look at the commit where the test was introduced to see the change that has been reverted. It's super obvious once you see it, it's in the service implementation class.

**Comment by roncain** [comment]
I found the BOM change, and it works.  It will be checked in with PR #1081. Closing this issue now.
