### ISSUE TITLE
Add async scenario tests to Client.ChannelLayer

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1082]
Scenarios\Client\ChannelLayer needs to be enhanced to include async versions of each of its tests.  This includes:
- async open and close of factory
- using channel.BeginRequest for the service operation calls

Examples can be found from the typed channel equivalents in PR #1071.

**Comment by zhenlan** [comment]
Duplicate the existing tests but provide async versions of them, like BeginXxx, EndXXX.

Related to #1087
