### ISSUE TITLE
CI should provide IIS logs for failing runs

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#1092]
When running CI, we have found that sometimes it's hard for us to obtain logs from CI machine when something goes wrong. Unfortunately, what's provided by the test runs themselves is not necessarily useful as the error is often on the server side and we get no data on (say) a 500 error that happens. 

We need to: 
- Decide what types of logs we want to gather
- Find a good way to surface them/attach them to Jenkins runs

**Comment by roncain** [comment]
I'd like to add to this list having the PRService invoke a ping endpoint (assuming it has gotten that far) and capture errors if possible.  As I found yesterday, a PR that causes IISHostedWebService to fail to build captures no information at all in the CI logs, yet it is a nonstarter that should fail the tests outright.
