### ISSUE TITLE
Create temp.crl out of the normal enlistment root path

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1099]
Currently, doing an OuterLoop build that self-starts the SelfHostedWcfService causes a temp.crl file to be created at the root of the enlistment.  A 'git status' shows there is a new file.  Simply running a build on a clean enlistment should not automatically show there is a new file in the workspace.  Someone could easily do 'git add --all' while working on a PR and inadvertently pull in the crl file.

Proposed solutions: produce this file under bin\WCF, and add *.crl to the .gitignore.

**Comment by roncain** [comment]
I believe this issue can be closed once #1089 is resolved.  temp.crl is just a throw-away file used by the current ping script.

**Comment by hongdai** [comment]
This issue will be resolved once the ping service(tracked by issue#1089).
