### ISSUE TITLE
NetTcp TransportSecurity tests fail cross-machine

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1108]
The NetTcp tests using TransportSecurity pass when self-hosted and run locally but fail in cross-machine use, including CI.   This is a manual Windows-to-Windows Self-hosted cross machine test involving domain-joined machines.  It does not occur yet in CI because the ConditionalFact detectors skip these tests.  By setting environment variables, we force them to run.

Repro steps:

1. Start the self-hosted WCF services on machine A (domain-joined)

2. On machine B running Windows and domain-joined, do these steps
 - Set these environment variables:
```
    set Server_Accepts_Certificates=true
    set Domain_Joined=true
    set NTLM_Available=true
    set Basic_Authentication_Available=true
    set Digest_Authentication_Available=true
    set Windows_Authentication_Available=true
    set ExplicitUserName=valid-domain-user-name
    set ExplicitPassword=valid-domain-user-password
```
 - Run the OuterLoops on machine B

The failing tests are:
```
Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString
Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_EchoString
StreamingTests.NetTcp_TransportSecurity_StreamedRequest_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String_WithSingleThreadedSyncContext
StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedRequest_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedResponse_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedResponse_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation
StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String_WithSingleThreadedSyncContext
```

Failure usually looks like this on the CI machines:
```
     Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString [FAIL]
        System.ServiceModel.Security.SecurityNegotiationException : Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
        ---- System.Security.Authentication.AuthenticationException : Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
        -------- System.ComponentModel.Win32Exception : The logon attempt failed
```

When run cross-machine self-hosted, failure looks like this:
```
            Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString [FAIL]
               System.ServiceModel.Security.SecurityNegotiationException : A call to SSPI failed, see inner exception.
               ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
               -------- System.ComponentModel.Win32Exception : The target principal name is incorrect

```

**Comment by roncain** [comment]
These tests have never passed on CI using the new test infrastructure.  They were initially marked with [ConditionalFact] to allow CI OuterLoops to run, and the [ConditionalFact] only evaluated to true when run self-hosted.  Attempting PR #1096 revealed that when these test are run cross-machine, they fail.

**Comment by zhenlan** [comment]
If these tests could pass with Bridge on CI in the past, they _should_ be able to pass with new infrastructure on Windows selfhost CI job.

It is expected these tests do not pass on *nix due to #700 where we need to automate root cert install on *nix.

I do expect these tests to pass on Windows outerloop cross machine CI job. @hongdai, are you aware of any specific reason this is not the case? If not, it's probably time for us to take a further look.

**Comment by zhenlan** [comment]
> The NetTcp tests using TransportSecurity pass when self-hosted but fail in cross-machine use

Just to clarify... when you say self-hosted, do you actually mean client/server on the same (Windows) machine because self-hosted can be on cross-machine too? In the repo steps, you showed tests will fail even if the service is self-hosted.

**Comment by zhenlan** [comment]
Just to add more data points. I triggered a Windows self-host CI run (using localhost) on PR #1096. The result shows

These 2 tests passed (as expected)
```
Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString
Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_EchoString
```

The rest of tests were skipped due to _Condition(s) not met: "Client_Certificate_Installed"_
```
StreamingTests.NetTcp_TransportSecurity_StreamedRequest_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String_WithSingleThreadedSyncContext
StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedRequest_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedResponse_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedResponse_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation
StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String_WithSingleThreadedSyncContext
```
Do all these tests need client cert? If yes, this sounds like a setup issue.

**Comment by roncain** [comment]
To clarify, the cross-machine aspect of this issue is the important one.  Running self-host where client and server are on the same machine will pass.  Running the server self-host but the client on another machine will fail.  The CI failures indicate IIS-hosted cross-machine also fails the same way.

The fact the self-host CI run skipped those tests indicates the client cert is not installed on that machine (or my detector is wrong :grinning:).

@zhenlan -- the repro steps in the issue description are the only known way to demonstrate the failure.  I've tried them Win10 + Win10 as well as Win10 + Windows Server 2012, and both give the same results.  I have not tried this on *nix -- only Windows.  I have not tried same-machine-IIS-hosted.

I agree we should investigate asap, as these tests are the only end-to-end test for NegotiateStream (as well as tcp async streaming over TransportSecurity).

**Comment by zhenlan** [comment]
Yes, it does sound like a client setup issue at this point. @hongdai, can you confirm?

**Comment by zhenlan** [comment]
@hongdai has confirmed the failure is because the client setup is not done.

@roncain will look into hoop up client cert setup through condition detector.

**Comment by roncain** [comment]
Latest results (6/1/16) -- failures are now just these:

```
Binding_Tcp_NetTcpBindingTests.DefaultSettings_Echo_RoundTrips_String
Binding_Tcp_NetTcpBindingTests.SecurityModeTransport_Echo_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedRequest_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String_WithSingleThreadedSyncContext
StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedRequest_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedResponse_Async_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_StreamedResponse_RoundTrips_String
StreamingTests.NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation
StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String_WithSingleThreadedSyncContext
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_AmbientCredentials
```
The majority of failures look like this:
```
            Binding_Tcp_NetTcpBindingTests.DefaultSettings_Echo_RoundTrips_String [FAIL]
               System.ServiceModel.Security.SecurityNegotiationException : A call to SSPI failed, see inner exception.
               ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
               -------- System.ComponentModel.Win32Exception : The target principal name is incorrect
               Stack Trace:
                  e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WindowsStreamSecurityUpgradeProvider.cs(282,0): at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__12.MoveNext()
                  --- End of stack trace from previous location where exception was thrown ---
```
The AmbientCredentials test fails like this:
```
            NegotiateStream_Http_Tests.NegotiateStream_Http_AmbientCredentials [FAIL]
               System.ServiceModel.Security.MessageSecurityException : The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'Negotiate oXsweaADCgEBonIEcGBuBgkqhkiG9xIBAgIDAH5fMF2gAwIBBaEDAgEepBEYDzIwMTYwNjAxMTQzODIzWqUFAgMIbP6mAwIBKakcGxpSRURNT05ELkNPUlAuTUlDUk9TT0ZULkNPTaoUMBKgAwIBAaELMAkbB3JvbmNhaW4='.
               Stack Trace:
                  e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs(364,0): at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
                  e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs(39,0): at System.ServiceModel.Channels.HttpResponseMessageHelper.<ParseIncomingResponse>d__7.MoveNext()
                  --- End of stack trace from previous location where exception was thrown ---
```

**Comment by roncain** [comment]
PR #1236 allows all these tests to pass if PSEXEC_PATH is set to point to psexec.exe and let the self-host services run as Local System.

**Comment by roncain** [comment]
I'm closing this issue now that we know these tests pass when self-host runs as local system.  Issue #1271 is responsible for making changes to CI and lab runs to allow these to pass.
