### ISSUE TITLE
The callback from the service back to the client fails.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#111]
The duplex service receives the initial call from the client, processes the message and sends a response back via the callback channel but times out when it fails to connect with the client thread which should be waiting for it.

**Comment by mconnew** [comment]
@StephenBonikowsky, I think this got fixed with PR 165. You don't mention which test is failing, can you verify this is fixed?

**Comment by mconnew** [comment]
Just saw when this was opened. This is a dupe of Issue #1
