### ISSUE TITLE
Make it possible to stop self-hosted exe when not running non-elevated

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1114]
The script to start the self-hosted WCF service is able to run in a non-elevated window.  It self-elevates and starts the service successfully.  However, the script to stop the service fails with "access denied" when run from a non-elevated window.  The net effect is attempting to do an OuterLoop run self-hosted from a non-elevated CMD window will leave the service running, making it impossible to clean the enlistment without manual intervention.

PR #1113 attempts to solve this by using RunElevated.vbs, but the TaskKill.exe still fails to stop the exe.  The task here is to investigate and make it succeed.  It is currently expected we will run selfhost tests in the lab elevated.  This change is protection so we don't render an enlistment uncleanable if we accidentally run non-elevated.

**Comment by roncain** [comment]
Alternately, we may choose to *not* start the self-host service unless we are elevated, rather than attempting to self-elevate.  Investigate both options.

**Comment by zhenlan** [comment]
This affects Windows self-host CI job.

**Comment by roncain** [comment]
This will be fixed by PR #1113.  Part of getting logging to work involved making it work non-elevated too

**Comment by roncain** [comment]
Fixed by PR #1113
