### ISSUE TITLE
Https tests fail on *nix from CI

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1123]
The following Https tests fail when run from CI against *nix platforms:

```
CustomBindingTests.DefaultSettings_Https_Text_Echo_RoundTrips_String
HttpsTests.SameBinding_Soap12_EchoString
HttpsTests.CrossBinding_Soap11_EchoString
HttpsTests.SameBinding_Soap11_EchoString
```
Failure in all cases looks the same and is probably related to the fact we need to do manual setup on the *nix machines before they work properly.

```
     CustomBindingTests.DefaultSettings_Https_Text_Echo_RoundTrips_String [FAIL]
Test case FAILED with errors : warning : Unexpected exception was caught while doing the basic echo test for variation... [/mnt/j/workspace/dotnet_wcf/master/outerloop_ubuntu14.04_debug_prtest/src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.Tests.csproj]
        'Client:: CustomBinding/DefaultValues
        Server:: CustomBinding/DefaultValues'
        Exception: System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK

```

**Comment by zhenlan** [comment]
If the root cause is cert install on *nix, this is a dup of #700.

**Comment by roncain** [comment]
I wouldn't mark it a dupe just yet.  This issue captures the fact the tests fail, and how.  #700 is the work item to automate setup on *nix machines.  I think it is better to say #700 represents the infrastructure work necessary to fix this issue.  This issue is the "why" for the need for #700.  If you still want to mark it a dupe, let's propagate the information contained in this issue back to #700.

**Comment by zhenlan** [comment]
related to #1129

**Comment by roncain** [comment]
Closing for this reason: #1305 replaced the ActiveIssue(1123) with a new ConditionalFact -- SSL_Available.  It appears all these errors were related to OpenSSL not being correctly installed on the machines where the tests ran.  Any issues discovered with these tests after we get OpenSSL setup properly will open new issues.
