### ISSUE TITLE
We should use independent detection logic in ConditionalFact detectors, separated from installation logic

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1130]
Please find the details of the discussion [here](https://github.com/dotnet/wcf/pull/1096/files#r62286169).

**Comment by roncain** [comment]
The logic is now
1. Call server to get cert
2. Check if cert is already installed with matching thumbprint
3. If not, attempt to install the cert
4. Whether succeed or fail in install, ask for cert in store by thumbprint
5. If fail, lookup cert by IssuedBy and SubjectName
I believe step 5 should be removed and opened #1172 for it
Closing this issue now and using #1172 for finalizing this detection logic
