### ISSUE TITLE
PR service and CI PR synching appears mismatched for tests vs WCF services

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1168]
PR service and the Jenkins PR syncing scripts for Outerloops appear to use different approaches, sometimes resulting in a situation where the tests that run are not in sync with the WCF services they execute against.

For example, after PR #1103 was merged, no PR submitted after that point would succeed until it was rebased onto master to incorporate changes in #1103, even PR's that had absolutely nothing to do with changes from #1103.

This does not affect self-hosted tests -- only those where there server and test client are on separate machines and synced independently.

**Comment by zhenlan** [comment]
@iamjasonp while we can workaround this issue for now (by rebasing other PRs), it will be great if we can fix this sooner.

**Comment by iamjasonp** [comment]
Next time someone changes the service is going to be validation for this :smile:

**Comment by iamjasonp** [comment]
@roncain and I think that this is sufficiently tested after PR #1346 - we find that the PeerTrust tests are running successfully with both a server side and a client side change. 

Closing this issue - please reopen if there are additional issues that are found
