### ISSUE TITLE
Obsolete PeerTrust

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1179]
PeerTrust depends on a Windows component that no longer exists.
It has been obsoleted on the full framework.
Obsolete this in .NetCore as well.

**Comment by StephenBonikowsky** [comment]
Using the "ContractUpdate" label to help find this and all other Issues that will require updates to the public contract.

**Comment by mconnew** [comment]
Are you confusing PeerTrust with PeerChannel? I couldn't find anything about PeerTrust being deprecated? PeerTrust only relies on the "Trusted People" certificate store and doesn't need any windows components.

**Comment by StephenBonikowsky** [comment]
@iamjasonp can you comment?

**Comment by iamjasonp** [comment]
I was commenting on PeerChannel when we were talking about this f2f - PeerTrust is still supported as far as I know. I must have misheard when we were chatting earlier.

**Comment by iamjasonp** [comment]
That said, I am not sure what level of support we would be providing for this on non-Windows platforms; as for this work item - there's no need to obsolete any PeerTrust-related APIs. However, we need to understand the level of support we're providing today.

**Comment by zhenlan** [comment]
Let's close this one and use #480 to verify the PeerTrust manually.

**Comment by StephenBonikowsky** [comment]
Closing.
