### ISSUE TITLE
Validation of WCF RTM packages on UWP

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1187]
This is to have a sanity validation of ServiceModel packages from RTM branch (when they are available) with last .NET Native release (VSU2).

**Comment by shmao** [comment]
RC3 + Update 2 is being blocked by https://github.com/dotnet/corefx/issues/8798.

**Comment by shmao** [comment]
My test UWP app built successfully using the latest RC3 packages (5.2.0-rc3-24126-01) + VS Update 2.

I tried referencing RC3 packages in two different ways,

1)	Add `"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0-rc3-24126-01"` in project.json.
2)	Add the following packages in project.json,
```
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Microsoft.NETCore.Platforms": "1.0.1-rc3-24126-01",
    "NETStandard.Library": "1.5.0-rc3-24126-01",
    "System.ServiceModel.Primitives": "4.1.0-rc3-24126-01",
    "System.ServiceModel.Duplex": "4.0.1-rc3-24126-01",
    "System.ServiceModel.Http": "4.1.0-rc3-24126-01",
    "System.ServiceModel.NetTcp": "4.1.0-rc3-24126-01",
    "System.ServiceModel.Security": "4.0.1-rc3-24126-01",
```
In both cases the app built fine in both debug & release mode.

**Comment by shmao** [comment]
I just verified the latest build (version *-24214). My test app built successfully in both debug and release modes. I tried referencing RC3 packages in two different ways,
1) Referencing the 5.2.0 `Microsoft.NETCore.UniversalWindowsPlatform` package.
```
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
```
2) Referencing the 5.1.0  `Microsoft.NETCore.UniversalWindowsPlatform` package and the RC3 WCF packages.
```
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Microsoft.NETCore.Platforms": "1.0.1",
    "NETStandard.Library": "1.5.0",
    "System.ServiceModel.Primitives": "4.1.0",
    "System.ServiceModel.Duplex": "4.0.1",
    "System.ServiceModel.Http": "4.1.0",
    "System.ServiceModel.NetTcp": "4.1.0",
    "System.ServiceModel.Security": "4.0.1",
    "System.Private.Uri": "4.0.1",
```

Closing the issue.
