### ISSUE TITLE
Cannot set X509CertificateValidationMode.PeerTrust on http.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1192]
I was unable to do this but don't see any reason why it shouldn't be possible.
Investigate and determine...

- [x] Is it possible?
- [x] Is it worth having a test?

**Comment by StephenBonikowsky** [comment]
After additional investigation with @mconnew this works...

var binding = new BasicHttpsBinding();
var factory = new ChannelFactory<IVerifyWebSockets>(binding);
factory.Credentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication();
factory.Credentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = X509CertificateValidationMode.PeerTrust;

**Comment by StephenBonikowsky** [comment]
This issue is for adding the http variations of the PeerTrust tests.
The tcp tests were added with PR #1194

**Comment by zhenlan** [comment]
This is done.
