### ISSUE TITLE
Is this usable from desktop apps?

### ISSUE THREAD

**Issue by fgreinacher** [dotnet/wcf#1199]
Is it possible to use this implementation from a regular desktop app, targeting .NET Framework 4.6?

**Comment by zhenlan** [comment]
Hi @fgreinacher you can create .NET Core apps that target full .NET Framework, but under the cover, it will still be implementation from full .NET Framework that will be used.

**Comment by fgreinacher** [comment]
Thanks @zhenlan - that's what I observed too...

To be more specific - we'd need the ClientBase / ChannelFactory implementations from .NET Core because they set HttpWebRequest.PreAuthenticate to true when using Windows authentication - the desktop implementation does not do it in this case. 

We are observing severe performance problems with big payloads (because each HTTP request is sent twice) and are trying to find a solution for this.

https://github.com/fgreinacher/wcf-auth shows the problem and how the .NET Core implementation is better.
