### ISSUE TITLE
Add test coverage for LayerChannel

### ISSUE THREAD

**Issue by khdang** [dotnet/wcf#1204]
From #623, I've added a test to verify that the channel extensibility model works but that doesn't cover LayerChannel. This issue is to track that part.

**Comment by hongdai** [comment]
I have clarified with khdang. This is because the code coverage report still shows no coverage for LayerChannel related classes after this test is checked in. It is not a high priority to investigate missing code coverage unless there is a known missing scenario. I'd suggest we move it to post RTM.

**Comment by hongdai** [comment]
Ron has made a fix to the test. We should have coverage now.
