### ISSUE TITLE
Enable ETW Channel events

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1217]
This is a tracking bug for the investigations we're doing with CLR folks on reducing the impact of ETW events on perf.

**Comment by zhenlan** [comment]
@mconnew do we have an issue opened in corefx so we can track?

**Comment by zhenlan** [comment]
Opened dotnet/corefx#8901

**Comment by KKhurin** [comment]
Assigning to Matt to enforce the event ids alignment.

**Comment by mconnew** [comment]
ETW channel events were disabled in PR #1246 due to issue with EventLog. Once the change in dotnet/coreclr#5477 is available, we can revert the change in PR #1246 and apply the change in PR #1238.

**Comment by zhenlan** [comment]
Close out this one for the perf fix and track the post rtm work item to enable ETW channel events in #1254.
