### ISSUE TITLE
Implement workaround in NETNative for ConditionalFact not being understood.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1221]
All tests being attributed with a ConditionalFact will not get run in NETNative as ToF uses a "toy" version of xunit that doesn't understand ConditionalFact, therefore since it doesn't recognize ConditionalFact its as if the test doesn't even have the 'Fact' attribute and ToF doesn't even think it is a test.

Test using an IF/DEF based on if(ToF) to add the 'Fact' attribute. Then the first step in the test case would do an Assert(<call the conditional fact method>).

If this works we would add this logic to all tests we "expect" to work in NETNative/ToF environment if certain setup/environment conditions are met.

The difference between these and other runs would be that whereas in other runs the tests would show as skipped if they failed the condition, these tests would show as failures, albeit with a good error message to know why.

**Comment by roncain** [comment]
Thanks @StephenBonikowsky .  And I think the #if expression should be based on a DefineConstant we put in the ToF wrapper project wcfopen.settings.targets  -- maybe called something like "Pseudo_Xunit" or "ConditionalFact_Unsupported".   That way only the TFS wrapper code would have the constant, not GitHub.

**Comment by StephenBonikowsky** [comment]
Yeah, that is exactly what I was going to do. @zhenlan wants me to use the existing FEATURE_NETNATIVE constant that we already define there that we use for the ActiveIssues. I pushed back a little but... maybe you will have better luck 😃

**Comment by roncain** [comment]
I'm afraid FEATURE_NETNATIVE would be incorrect.  That value is set for NET Native specific code both in GitHub and in TFS and affects product code.  Our issue is related only to ToF-built test and is not NET Native related.  The code we need to execute conditionally includes tests run under both CoreCLR and NET Native.  We can debate name to call it, but its meaning is "this test is being run by the pseudo-xunit used by ToF in TFS".

**Comment by StephenBonikowsky** [comment]
I can confirm that the logic works in "N on K" and "K on K".

Discussed this a little further with @zhenlan and we are leaning towards renaming the existing constant in wcfopen.settings.targets to something more appropriate which we can use for both the ActiveIssue if/defs as well as this new purpose.

**Comment by roncain** [comment]
@StephenBonikowsky -- Please include me in these discussions. Attempting to make a single constant seems wrong to me.  There are 2 orthogonal concepts that deserve separate constants:
1) This test is running against the NET Native version of the product
2) This test is being run by ToF

The fact we can run against NET Native using only ToF is probably what is adding confusion here. But even when we move to Helix, there will still be concept (1).  And concept (2) will no longer apply.

If the existing FEATURE_NETNATIVE is true in "K on K" we have a problem. It should be true only in "N on K". I'm not opposed to renaming FEATURE_NETNATIVE (though I don't understand why we would) but I am opposed to attempting to merge these 2 orthogonal concepts.
