### ISSUE TITLE
Are there plans to port svcutil.exe to .NET Core?

### ISSUE THREAD

**Issue by epignosisx** [dotnet/wcf#1222]
Currently there is no way to generate a proxy from a Mac or Linux computer. Are there plans to port SvcUtil.exe to .NET Core?

**Comment by zhenlan** [comment]
@epignosisx - yes, this is something we are looking into. Stay tuned.

For now, you can generate proxy in VS 2015 by using [WCF Connected Service](https://blogs.msdn.microsoft.com/webdev/2016/05/25/announcing-wcf-connected-service-for-net-core-rc2-and-asp-net-core-rc2/) and copy the file/project to Mac or Linux.

**Comment by Coruscate5** [comment]
Is it possible to just manually extract dotnet-svcutil for the time being? On Windows, I've used svcutil in various occasions when the WCF/SOAP service I'm consuming was built incorrectly - this way I can at least generate scaffolded code that works with methods that aren't broken (as opposed to the current WCF connected service plugin, which is by-and-large all or nothing - if there's an error I can't move forward)

**Comment by zhenlan** [comment]
The current dotnet-svcutil shipped in the VS extension is not tested on Mac or Linux, so no guarantees it works... 😄 With that being said, the standalone release of dotnet-svcutil will be our next priority. We were busy with including the WCF connected services tool in-box VS lately and now it's part of VS 2017 starting v15.5.


> I can at least generate scaffolded code that works with methods that aren't broken (as opposed to the current WCF connected service plugin, which is by-and-large all or nothing - if there's an error I can't move forward)

@Coruscate5, we are improving the WCF connected services tool in our latest release in VS 15.5 so that it will continue for non-fatal errors (eg. some schema validation errors). Please give it a try if you get a chance. If you still see issues, please open a separate issue and I would like to follow up for that.

**Comment by Coruscate5** [comment]
@zhenlan - thanks for the response! For the most part, the WCF connected service works, except when it doesn't. One particular case appears to be an old MSFT bug in WSDL generation - complex custom types sometimes get assigned to a conflicted namespace (e.g. complex type is in "s1" when it should be "s", which can't be easily corrected even with full access to the service code), and the connected service plugin chokes. This is probably in the scope of a schema validation error, and in my case I didn't need the complex type. 

That being said, there shouldn't be anything wrong with just using the scaffolded code as a reference to building a custom Service model for a given endpoint myself, right? I.e. if the tool completely fails, I can at least try to hack together a manual service model together to at least allow me to call *some* methods from the old service.

**Comment by zhenlan** [comment]
@Coruscate5 thanks for the information.

Yes, even if the tool fails due to an ill WSDL or whatever reason, you can still write code and call your service (as long as the bindings/features that the service uses are supported by the WCF on .NET Core runtime).

**Comment by mlacouture** [comment]
dotnet-svcutil is now available, see #2894
