### ISSUE TITLE
Suppress ConditionalFact detectors when not running OuterLoops

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1224]
The ConditionalFact detectors are attempting to run when only InnerLoops are run.  And they attempt to contact ServiceUri, which usually fails.  They do this because the Fact discoverer comes before the Trait discoverer, and xunit doesn't know to eliminate the OuterLoop-marked tests until they have already executed their [ConditionalFact].

Task: find a way to return false from all ConditionalFact detectors without contacting the server when we are running only InnerLoops.

**Comment by zhenlan** [comment]
@roncain - question only, is this something we can open against buildtools?

**Comment by roncain** [comment]
I don't think we can @zhenlan though one of our oldest requests of buildtools was to allow an entire project to be marked OuterLoop so it would not even compile or be visited by xunit discoverers.  And by the time xunit runs its trait discovers, it's too late -- the ConditionalFact's have run.
I see a couple solutions though.  My preferred would be to alter the list of projects to compile based on whether OuterLoop was set.  If set, exclude everything under unit.  If not set, exclude everything under scenarios.  I think that would also shorten build times.   I will investigate that approach when we choose to work on this issue.
