### ISSUE TITLE
Replace Mahjong tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#123]
The Mahjong tests originally written before WCF went OSS were not ported to OSS.  This task is to add test coverage to OSS to replace what the Mahjong tests did, such as message inspector, request headers, etc.  We should also drop references to Mahjong from both client and self-host service code.

**Comment by roncain** [comment]
Not required for beta7

**Comment by zhenlan** [comment]
@hongdai will identify if we need to add any coverage to our existing test bed.

**Comment by hongdai** [comment]
The additional coverage needed.
