### ISSUE TITLE
How to update to the new version of Microsoft.NETCore.UniversalWindowsPlatform for the use and test current WCF?

### ISSUE THREAD

**Issue by huangjinshe** [dotnet/wcf#1231]
Currently my UWP application project use Microsoft.NETCore.UniversalWindowsPlatform v5.1.0 from Nuget.  I hope someone could tell me which is the new version of .NetCore.UniversalWindowsPlatform which I could replace it?  Thank you.

I search but Microsoft.NETCore.UniversalWindowsPlatform not newest version in Nuget, then I think maybe it change the name, but I don't know which one is it.

**Comment by zhenlan** [comment]
Hi @huangjinshe, the v5.1.0 of Microsoft.NETCore.UniversalWindowsPlatform _is_ the latest version and its name is not changed to something else.

The v5.1.0, however, does not contain any updates from WCF. To use the prerelease of WCF packages in UWP, please follow the instructions in the known issues section of the [WCF RC1 release notes](https://github.com/dotnet/wcf/releases/tag/v1.0.0-rc1), which was tested using v5.0.0 of Microsoft.NETCore.UniversalWindowsPlatform.

**Comment by huangjinshe** [comment]
@zhenlan Thank you, but I want to try and use Duplex channel on the UWP.  I think it's available on RC2. as like roncain said :https://github.com/dotnet/wcf/issues/1#issuecomment-220971464

Do you know when it would release a version which supported UWP?

**Comment by zhenlan** [comment]
@huangjinshe Duplex feature is available for UWP on RC1 already. Did you get a chance to give it a try or did you run into any issues? The RC2 bits, however, do not work on UWP (as noted in the RC2 release notes).

**Comment by huangjinshe** [comment]
Hi @zhenlan I thought it release to RC2, Because I'm new for GitHub,  could you tell me more about using the RC1 version?  could I just go back to Microsoft.NETCore.UniversalWindowsPlatform v5.0 and add `dependencies` to the  `project.json` then I could use it? Or I should download something or replace someting?  Thank you.

**Comment by zhenlan** [comment]
@huangjinshe, sure, please update the `project.json` of your UWP project with packages (and versions) listed in the known issues section for UWP in the [RC1 release notes](https://github.com/dotnet/wcf/releases/tag/v1.0.0-rc1) (yes, which include v5.0.0 `Microsoft.NETCore.UniversalWindowsPlatform`). Rebuilding your project in VS will download those packages automatically and then you should be good to go.

**Comment by huangjinshe** [comment]
@zhenlan Thank you. It worked.  but I must go to visual studio setting-->Nuget---> and select "auto download missing package"  and "download package when build"  that two option. and then it will auto download all pre version packages.

It works fine. Only the problem is Looks like this version couldn't use `SecurityMode`(only could use `SecurityMode.None`). I'm using TCP duplex.  So basically it's just let every one see all data when server and client communication.

I'm look forward to the next release. Thank you. :-)
