### ISSUE TITLE
Include outerloop testing in CI by default

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1233]
We have been discussing to include outerloop testing in CI by default since that's most PRs doing manually anyway. With PR #1225, we don't even build outerloop tests as part of default building process anymore. I am leaning towards including all outerloop CI jobs by default but this can be discussed.

**Comment by zhenlan** [comment]
Triage recommendation: Windows and Ubuntu outerloop

**Comment by iamjasonp** [comment]
Fixed - #1335
