### ISSUE TITLE
NegotiateStream in Tcp is not supported for UWP.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1235]
I found two issues in corefx that might be what fixes this issue, @iamjasonp @mconnew could one of you confirm?

dotnet/corefx#2928
dotnet/corefx#4721

Using this issue as the ActiveIssue for the tests in...
\Scenarios\Security\TransportSecurity\Negotiate\NegotiateStream_Tcp_Tests.cs

**Comment by roncain** [comment]
Tests that fail for me run on NET Native are:
* NegotiateStream_Tcp_AmbientCredentials
* NegotiateStream_Tcp_With_ExplicitSpn
* NegotiateStream_Tcp_With_SPN
* NetTcp_TransportSecurity_StreamedRequest_RoundTrips_String
* NetTcp_TransportSecurity_Streamed_RoundTrips_String_WithSingleThreadedSyncContext
* NetTcp_TransportSecurity_Streamed_RoundTrips_String
* NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String
* NetTcp_TransportSecurity_StreamedResponse_Async_RoundTrips_String
* NetTcp_TransportSecurity_StreamedResponse_RoundTrips_String
* NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation
* NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String_WithSingleThreadedSyncContext

**Comment by iamjasonp** [comment]
> NegotiateStream_Tcp_AmbientCredentials
NegotiateStream_Tcp_With_ExplicitSpn
NegotiateStream_Tcp_With_SPN

These I think will require a domain-joined server - is that the case?

**Comment by zhenlan** [comment]
@DavidGoll will networking have NegotiateStream support in UWP/NS2.0 timeframe?

**Comment by CIPop** [comment]
@zhenlan Yes. This is tracked by https://github.com/dotnet/corefx/issues/20033, in particular https://github.com/dotnet/corefx/issues/14560.

**Comment by zhenlan** [comment]
Great, I see dotnet/corefx#14560 is in UWP6.0 milestone. Thanks @CIPop!

cc: @mconnew

**Comment by mconnew** [comment]
Resovled by #2043
