### ISSUE TITLE
Support for WCF tracing in non-windows OS

### ISSUE THREAD

**Issue by PurnaChandraPanda** [dotnet/wcf#1243]
Currently - only ETW tracing is supported for WCF client applications. It is well documented how to collect and analyze ETW traces - awesome work. It seems traditional WCF tracing mean <system.diagnostics .. /> is out of the picture now with the evolution of .NET Core. It is OK. As is documented, ETW tracing (logman) can be performed in Windows OS only. Just in case we have challenges for a .NET core web application (running on Mac/ Linux machine) have specific challenges in communicating with a backend WCF service, do we have any set of diagnostic (alike ETW) in non-Windows OS?

**Comment by zhenlan** [comment]
In general, this depends on what .NET core can support in the future.

For WCF, however, you can write your own event listener to collect events. Please check out our test code below:
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs#L26
