### ISSUE TITLE
Need new ConditionalFact "Is_Manual_Test".

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1244]
To clearly distinguish tests that are only expected to pass after some manual work has been done, this Issue should include adding this new ConditionalFact to the tests.

The tests that need this are...
NegotiateStream_Http_Tests.NegotiateStream_Http_With_ExplicitUserNameAndPassword
NegotiateStream_Http_Tests.NegotiateStream_Http_With_ExplicitSpn
NegotiateStream_Http_Tests.NegotiateStream_Http_With_ExplicitUserNameAndPassword_With_Spn
NegotiateStream_Http_Tests.NegotiateStream_Http_With_ExplicitUserNameAndPassword_With_Upn
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitSpn
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword_With_Spn
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword_With_Upn
Https_ClientCredentialTypeTests.DigestAuthentication_RoundTrips_Echo

Possibly these as well...
NegotiateStream_Http_Tests.NegotiateStream_Http_With_Upn
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_Upn

**Comment by roncain** [comment]
It's probably worth discussing the best way to do this. Ideally, these tests "light up" as soon as their required ConditionalFact's are satisfied, but our problem today is that we don't know what they need.  Each test can have different setup requirements, so we wouldn't want them to start executing just by setting Is_Manual_Test true. It might make sense that when I do the prototype to merge ConditionalFact/ActiveIssue that we can have ConditionalFact that return false also can show in the console log what setup is necessary to make them run.

**Comment by roncain** [comment]
Closing for these reasons:
1. We now have scenario-specific conditions that can be set to enable tests requiring manual setup
2. We have integrated [WcfFact] and [Condition] to log why a test has been skipped
