### ISSUE TITLE
ProjectK RTM VS experience needs to explicitly include "System.Private.DataContractSerialization" in project.json

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1245]
"System.ServiceModel.Http" depends on  "System.Runtime.Serialization.Xml", it should have included 
System.Private.DataContractSerialization automatically.

The package restore shows it has included System.Private.DataContractSerialization, but the runtime fails to find it.

**Comment by zhenlan** [comment]
This is the exception
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.ServiceModel.Channels.MessageVersion' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.ServiceModel.EnvelopeVersion' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Xml, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at System.ServiceModel.EnvelopeVersion..cctor()
   --- End of inner exception stack trace ---
   at System.ServiceModel.EnvelopeVersion.get_None()
   at System.ServiceModel.Channels.MessageVersion..cctor()
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.TextMessageEncodingBindingElement..ctor()
   at System.ServiceModel.HttpBindingBase..ctor()
   at System.ServiceModel.BasicHttpBinding..ctor(BasicHttpSecurityMode securityMode)
   at ConsoleApp3.Program.Main(String[] args)
```
After including `System.Runtime.Serialization.Xml` package in project.json the exception goes away although the app does not use anything directly from S.R.S.Xml. This is updated project.json:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc3-004338"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "System.ServiceModel.Http": "4.1.0-rc3-24128-00",
        "System.Runtime.Serialization.Xml": "4.1.1-rc3-24128-00"
      }
    }
   }
}
```
One possible reason is `System.Private.ServiceModel` is not updated to use `4.1.1-*` version of `System.Runtime.Serialization.Xml` (it is still referencing `4.1.0` version). @weshaggard @ericstj, can I get your thoughts on this issue?

**Comment by ericstj** [comment]
Can you share the lock file as a gist?

**Comment by zhenlan** [comment]
Here is it
https://gist.github.com/zhenlan/82a2b8e77b6d3586b5dcb244267980b1

**Comment by ericstj** [comment]
Got a repro:
```
warn : Detected package downgrade: System.Runtime.Serialization.Xml from 4.1.0-rc3-24128-00 to 4.0.0-rc3-24128-00
warn :  p.dcs (>= 1.0.0) -> System.ServiceModel.Http (>= 4.1.0-rc3-24128-00) -> System.Private.ServiceModel (>= 4.1.0-rc3-24128-00) -> System.Runtime.Serialization.Xml (>= 4.1.0-rc3-24128-00)
warn :  p.dcs (>= 1.0.0) -> System.ServiceModel.Http (>= 4.1.0-rc3-24128-00) -> System.Runtime.Serialization.Xml (>= 4.0.0-rc3-24128-00)
warn : Detected package downgrade: System.Collections.NonGeneric from 4.0.0 to 4.0.0-rc3-24128-00
warn :  p.dcs (>= 1.0.0) -> System.ServiceModel.Http (>= 4.1.0-rc3-24128-00) -> System.Private.ServiceModel (>= 4.1.0-rc3-24128-00) -> System.Collections.Specialized (>= 4.0.0-rc3-24128-00) -> System.Collections.NonGeneric (>= 4.0.0)
warn :  p.dcs (>= 1.0.0) -> System.ServiceModel.Http (>= 4.1.0-rc3-24128-00) -> System.Private.ServiceModel (>= 4.1.0-rc3-24128-00) -> System.Collections.NonGeneric (>= 4.0.0-rc3-24128-00)
```
This is an odd warning but it is highlighting the problem.  S.P.SM is depending on non-existent package versions, nuget is silently finding the closest one, which ends up downgrading other dependencies.

It looks like package base-lining is broken so you're getting invalid package versions written as your dependencies of the System.Private.ServiceModel package.  The dependency on System.Private.ServiceModel's version is correct, but all of its dependencies are wrong.  My theory is that baselining is broken for the WCF branch entirely.  Trying to chase down when that happened.

**Comment by ericstj** [comment]
OK, found the root cause.  https://github.com/dotnet/wcf/blob/master/pkg/baseline/project.json is not being updated with new versions.  /cc @dagood
