### ISSUE TITLE
Negative test times-out.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1250]
ExpectedExceptionTests.SendTimeout_For_Long_Running_Operation_Throws_TimeoutException

This test times-out for around 6 minutes when running manually on NetNative, possibly other platforms as well.

**Comment by roncain** [comment]
This fails for me in K-on-K too.  I believe I have seen it very rarely in GitHub from time to time.

**Comment by zhenlan** [comment]
Will see if this still repos.

**Comment by StephenBonikowsky** [comment]
Looks like it no longer occurs.
