### ISSUE TITLE
Enable ETW channel events

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1254]
ETW channel events were disabled to reduce impact on performance for RTM release. See comments below from @mconnew for details:

> ETW channel events were disabled in PR #1246 due to issue with EventLog. Once the change in dotnet/coreclr#5477 is available, we can revert the change in PR #1246 and apply the change in PR #1238.

**Comment by roncain** [comment]
@mconnew -- what is the status of this issue?  Is there any remaining work on our end to close this?

**Comment by roncain** [comment]
@mconnew -- now that we are using later package versions and https://github.com/dotnet/coreclr/pull/5477 was merged, it seems like we should be able to enable the events as described in the description above.
