### ISSUE TITLE
SSL CustomCertificateValidator

### ISSUE THREAD

**Issue by YZahringer** [dotnet/wcf#126]
Hello,

How to configure allowed SSL certificates?

System.Net.ServicePointManager is unavailable, CustomCertificateValidator also not available in vNext.

There is a new way for this?

Best regards,
Yann

**Comment by atanasa** [comment]
Hello,
I'd like to know this too.
Is there a way to provide a delegate similar to ServicePointManager.ServerCertificateValidationCallback ideally per client and not an app-domain-wide.
I tried to change the HttpClientHandler used by the https transport by hooking in a DelegatingHandler through a HttpMessageHandlerFactory but that produces a "HttpPipelineNotSupportedOnClientSide" exception in the HttpsTransportBindingElement.

**Comment by roncain** [comment]
PR https://github.com/dotnet/wcf/pull/411 expanded the API to include CustomCertificateValidator.  You can see an example of usage in a functional test at https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

@YZahringer and @atanasa Will this provide what you need?

**Comment by YZahringer** [comment]
Yes, thank's @roncain

**Comment by atanasa** [comment]
Would this validator be called for all certificates or only for the ones that are not valid according to the Windows Certificate Store?

**Comment by hongdai** [comment]
It is for all certificates.
