### ISSUE TITLE
NegotiateStream_Tcp_With_Upn test throw platform not supported exception

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1260]
It throws as we currently do not support UpnObjectComparer:Equals in ClaimComparer.cs

#if SUPPORTS_WINDOWSIDENTITY
        private class UpnObjectComparer : IEqualityComparer
        {
            bool IEqualityComparer.Equals(object obj1, object obj2)
            {
                throw ExceptionHelper.PlatformNotSupported();
            }

**Comment by roncain** [comment]
@hongdai -- can you provide instructions how you ran this and the stack trace?  I see from code inspection what you mean, but it would be good to have repro steps to know when it is fixed.  Also, is this related to #1235?

**Comment by roncain** [comment]
I believe PR #1502 may fix this issue at the same time it fixes #1454.

**Comment by hongdai** [comment]
I have verified this issue is fixed by PR #1502 and enable the test disabled by this issue.
