### ISSUE TITLE
All TCP ExplicitUserNameAndPassword tests are failing

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1262]
They are failing because of  https://github.com/dotnet/corefx/issues/9160.

**Comment by hongdai** [comment]
Tests failed:
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword failed.
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword_With_Spn failed.
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword_With_Upn failed.

The client will throw below exception from NCL:
System.Net.Security.dll!System.Net.Security.NegoState.ThrowCredentialException(long error) Line 842 C#
 System.Net.Security.dll!System.Net.Security.NegoState.ProcessReceivedBlob(byte[] message, System.Net.LazyAsyncResult lazyResult) Line 608 C#
 System.Net.Security.dll!System.Net.Security.NegoState.ReadCallback(System.IAsyncResult transportResult) Line 758 C#
 System.Net.Security.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken) Line 481 C#
 System.Net.Security.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken) Line 431 C#
 System.Net.Security.dll!System.Net.StreamFramer.ReadFrameComplete(System.IAsyncResult transportResult) Line 292 C#
 System.Net.Security.dll!System.Net.StreamFramer.ReadFrameCallback(System.IAsyncResult transportResult) Line 171 C#
 System.Net.Security.dll!System.Threading.Tasks.TaskToApm.InvokeCallbackWhenTaskCompletes.AnonymousMethod__0() Line 137 C#
 System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Unknown
 System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Unknown
 System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask) Unknown
 System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations() Unknown
 System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.TrySetResult(int result) Unknown
 System.Private.CoreLib.ni.dll!System.Threading.Tasks.TaskFactory.FromAsyncCoreLogic(System.IAsyncResult iar, System.Func endFunction, System.Action endAction, System.Threading.Tasks.Task promise, bool requiresSynchronization) Unknown
 System.Private.CoreLib.ni.dll!System.Threading.Tasks.TaskFactory.FromAsyncImpl.AnonymousMethod__1(System.IAsyncResult iar) Unknown
 System.Net.Sockets.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken) Line 481 C#
 System.Net.Sockets.dll!System.Net.ContextAwareResult.CompleteCallback() Line 461 C#
 System.Net.Sockets.dll!System.Net.ContextAwareResult.Complete.AnonymousMethod__15_0(object s) Line 450 C#
 System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Unknown
 System.Net.Sockets.dll!System.Net.ContextAwareResult.Complete(System.IntPtr userToken) Line 451 C#
 System.Net.Sockets.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken) Line 431 C#

**Comment by iamjasonp** [comment]
A little more detail, as this is tagged as a known issue in 1.0.0-rtm: 

Clients which need to authenticate to the server via NTLM/Kerberos will not be able to provide alternate credentials to connect to a server. This is due to corefx#9160, explicit credentials provided by WCF are not honoured by NegotiateStream.

**Comment by zhenlan** [comment]
@hongdai, now that dotnet/corefx#9160 is closed, do you know if this scenario works now?

**Comment by hongdai** [comment]
This is a manual test. I will manually verify it.

**Comment by roncain** [comment]
This issue has been marked closed, but one of these tests still fails for me -- #1499.
The other explicit username/password tests appear to have passed for me run manually self-hosted.
I reopened that issue but will leave this issue closed.

/cc: @hongdai @zhenlan
