### ISSUE TITLE
Update CoreFX dependencies to rc3-24206-00

### ISSUE THREAD

**Issue by joshfree** [dotnet/wcf#1268]
As part of testing, WCF should update /release/1.0.0 to the latest packages available

It looks like this isn't automated yet, and the last manual update was 2 weeks ago https://github.com/dotnet/wcf/pull/1214

**Comment by joshfree** [comment]
Also the corefx build that WCF is referencing is 3+ weeks old

**Comment by zhenlan** [comment]
@StephenBonikowsky - can you please make this change?

**Comment by StephenBonikowsky** [comment]
Opened PR #1272

**Comment by StephenBonikowsky** [comment]
Merged PR #1272
