### ISSUE TITLE
Stackoverflow with certain WSDL

### ISSUE THREAD

**Issue by Ravenheart** [dotnet/wcf#1269]
https://gist.github.com/Ravenheart/128eaee4a3937a313377102023bcdcb1

The above WSDL will cause the tool generating the C# client class to crash with a stackoverflow exception, the WSDL supports querying for data with the possibility of an endlessly deep WHERE clause which in turn the tool can't process and hence the stackoverflow exception.

**Comment by roncain** [comment]
Thanks for reporting this @Ravenheart.  Was the tool you were using to create the C# client the [WCF Connected Services in VS](https://blogs.msdn.microsoft.com/webdev/2016/05/25/announcing-wcf-connected-service-for-net-core-rc2-and-asp-net-core-rc2/)?  Were you able to process this same WSDL successfully using other tools previously (like SvcUtil or Add Service Reference in VS)?

/cc @mlacouture @zhenlan

**Comment by Ravenheart** [comment]
I've only used svcutil and the classic services one (wsdl.exe I believe), but I was able to generate proxy client classes i other languages with their respective tooling (java and php).

**Comment by Ravenheart** [comment]
Tried the new WCF Connected Services, same error:

```
Scaffolding Code ...
Attempting to download metadata from 'https://gist.githubusercontent.com/Ravenheart/128eaee4a3937a313377102023bcdcb1/raw/d838ec6035c138beeaaba0d2832618862bd86dfc/PISService.wsdl' using WS-Metadata Exchange and HttpGet.

Error:Error: Process is terminated due to StackOverflowException.
An error occurred in the tool.

Failed to generate service reference.```

**Comment by mlacouture** [comment]
this is a problem in one of the lower level libraries (XML Schema if I remember correctly) affecting all web services tools (wsdl.exe, svcutil.exe, and add service reference tools). not specific to WCF Connected Service.
