### ISSUE TITLE
Reenable Fiddler-based URL's for Bridge using TestProperties

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#129]
The Bridge feature #115 will undo the UseFiddler conditional code. After that feature is merged, we need to update the point at which URL's are returned (Endpoints.cs?) to check TestProperties (#120) and conditionally substitute Fiddler URL's

**Comment by roncain** [comment]
Not strictly required for beta7, but when we move to the Bridge we will lose the ability to use Fiddler to debug unless we fix this.  Fix needs to work with Bridge's returned URL's.

**Comment by zhenlan** [comment]
@roncain is this already done?

**Comment by iamjasonp** [comment]
Hmm, is this item strictly necessary? I guess i typically go and attempt to test cross-machine when I need Fiddler, and so if I allow Fiddler to take over my default HTTP(S) proxy, this problem goes away. 

A while back (I forget how long) I had luck passing build.cmd /p:BridgeHost=<my local machne's fqdn name> and was able to have Fiddler intercept traffic.

**Comment by roncain** [comment]
@mconnew I think you were the main user of this before we moved to the Bridge and killed the old code.  Are you able to do what you want without this feature just by setting BridgeHost to another machine and run the tests cross-machine?  I wonder if we should close this issue and remove the Bridge and TestProperties that refer to this setting (no code does anything with it).

**Comment by roncain** [comment]
@mconnew -- do you still need this feature?  If not, we should remove UseFiddlerUrl from TestProperties and the BridgeConfiguration.  They currently are inoperative anyway.

**Comment by mconnew** [comment]
No we have cross machine working, it's less useful. I'm okay to remove them. If I find a need again in the future, I'll put them back.

**Comment by roncain** [comment]
Closing issue because the old Bridge infrastructure has been removed, and we can easily use cross-machine testing when we want to use Fiddler, without the need for special URL handling.
