### ISSUE TITLE
Provide better way to re-generate root cert or report expiration on CI machines

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1290]
When the root cert expires on the CI machine, there is no outward appearance of failure.  The ConditionalFact that tries to install the root cert fails (NullRefException in Util.GetRootCert).  Subsequently, all cert-based tests are SKIPPED, and the CI jobs report PASS.

I recommend we find a better way for the CI machines to detect and regenerate the required certificates.  And at the very least, we need better error reporting when a certificate has expired.

**Comment by zhenlan** [comment]
We can have a scheduled task to regenerate certificate once a while.

**Comment by zhenlan** [comment]
We have a scheduled task to refresh certs once a while.
