### ISSUE TITLE
 A libcurl built with OpenSSL is required on OSX to test client certificate tests

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1296]
Currently the following tests failed:
HttpsTests.ClientCertificate_EchoString 
HttpsTests.ServerCertificateValidation_EchoString

**System.PlatformNotSupportedException: The libcurl library in use (7.43.0) and its SSL backend ("SecureTransport") do not support custom handling of certificates. A libcurl built with OpenSSL is required.**

We need to figure out a way to meet this setup requirement manually at minimum to test client certificate on OSX.

**Comment by zhenlan** [comment]
This is a dup of #1295
