### ISSUE TITLE
Move test case out of 4.0.0 file.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1298]
Test case "DuplexChannelShapeTests.IRequestChannel_Https_NetHttpsBinding" was incorrectly added to  ...Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

It needs to be moved to "...System.Private.ServiceModel\tests\Scenarios\Client\ChannelLayer\DuplexChannelShapeTests.cs"

The test uses a new API that was added as mentioned in #507 so it cannot work on 4.0.0.

**Comment by zhenlan** [comment]
@StephenBonikowsky - please go ahead and move this test.

**Comment by StephenBonikowsky** [comment]
After looking at this more carefully the test uses the RequestReply channel shape so it should be moved into the RequestReplyChannelShapeTests class and not the DuplexChannelShapeTests class.
