### ISSUE TITLE
Is there any new version for Release ?

### ISSUE THREAD

**Issue by huangjinshe** [dotnet/wcf#1299]
Currently I'm using RC1.

But for this, we must use .Net core 5.0.  Also there are other dependencies limitation on it.

It will cause some `System.Reflection.MissingMetadataException` on UWP(Xamarin).

My project need to release now. But I really hope you guys could give us a new stable version.  Or tell us date of the next release.  Thank you.

**Comment by zhenlan** [comment]
Hi @huangjinshe - as [announced in dotnetConf](https://blogs.msdn.microsoft.com/dotnet/2016/06/09/thank-you-for-watching-dotnetconf-2016/), .NET Core will be released on Jun 27th.

**Comment by huangjinshe** [comment]
@zhenlan Is the new version stable wcf include in it?  Thank you.

**Comment by zhenlan** [comment]
Yes, stable version of WCF packages will be part of the .NET Core release on Jun 27th.

You can actually give it a try if you add `https://dotnet.myget.org/F/dotnet-core` to your NuGet feed and reference packages like what @shmao listed in his [comment](https://github.com/dotnet/wcf/issues/1187#issuecomment-226036484) in #1187.

Thank you for any feedback @huangjinshe.

**Comment by huangjinshe** [comment]
@zhenlan Ok. and Thank you very much.
