### ISSUE TITLE
Enforce expected test sets are included in CI and nightly lab runs

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1304]
For each testing environment (eg. Windows, OS X, etc.), we will have expected set of tests to be included. We should enforce this by setting the specific conditions to true so those tests attributed with corresponding ConditionFact will always be included.

- [x] CI is updated - @iamjasonp 
- [x] Lab run is updated - @hongdai

**Comment by roncain** [comment]
At the moment, the following conditions are used in ConditionalFact and will be auto-detected  if left unspecified.
```
Root_Certificate_Installed
Client_Certificate_Installed
Server_Domain_Joined
Domain_Joined
Windows_Authentication_Available
Basic_Authentication_Available
Digest_Authentication_Available
NTLM_Available
SPN_Available
UPN_Available
Ambient_Credentials_Available
Explicit_Credentials_Available
```
Auto-detection can be avoided by explicitly setting these values 'true' or 'false' when build.cmd is called.  Example:
```
    build.cmd /p:Root_Certificate_Installed=true
```
ConditionalFact tests for each value obey these rules:
1. If unspecified, auto-detect and either run or skip the test based on the result
2. If 'true', always run the test
3. If 'false', always skip the test

The complete set of ConditionalFact conditions can be found [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs)

**Comment by hongdai** [comment]
Update on Helix lab: I'm researching on options to enable cert tests on non window machines.

**Comment by hongdai** [comment]
Updates:
1) Have made changes to VSO build to enable certs for Windows OS.
2) We have identified 2 possible solutions for Linux cert installation.
a. install it via process API in the test run time.
b. install it via a set up script.

b) is preferable if it's not very complicate to implement. Investigating it with Helix owner.

**Comment by iamjasonp** [comment]
Done! Closing
