### ISSUE TITLE
ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_StreamedRequest is flaky in ToF

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#1307]
This test is timing out in ToF and causing 45 other tests in the same project to fall over and not report results. 

I have disabled this test only in ToF to prevent this flakiness from impeding our ability to get good test results from Contract.Service.Tests.csproj

**Comment by roncain** [comment]
Does this test ever fail in "K on K"?  If so, it might indicate a test issue.  But if it happens only in "N on K" I am concerned we have an intermittent *product* issue in NET Native.

**Comment by iamjasonp** [comment]
I think we'll have to look out for this test... marking as test issue, and self-assigning so that I can keep an eye on it

**Comment by iamjasonp** [comment]
Also marking as "bug" since we don't know if it's a product issue or not

**Comment by roncain** [comment]
We're suddenly seeing intermittent failures in Ubuntu for this family of tests.
```
ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed
ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed_Async_WithSingleThreadedSyncContext
```

We may need to ActiveIssue this for AnyUnix till we understand the issue

**Comment by iamjasonp** [comment]
Data point: Not reproing when I run this in Ubuntu on my dev boxes

**Comment by zhenlan** [comment]
This is now observed not just in TOF. It is observed in CI and Helix as well.

**Comment by hongdai** [comment]
This is caused by race conditions in ProducerConsumerStream class. It affects both Linux and .Net Native. It can be consistently repro'ed by running below tests in a loop for 50 times.

ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed
ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed_Async_WithSingleThreadedSyncContext
