### ISSUE TITLE
is there any example or tutorial that show howto add server-side wcf in aspnet core rc2?

### ISSUE THREAD

**Issue by vincentshow** [dotnet/wcf#1310]
hello guys, i cannot find the wcf template in my vs2015 updte2, and no tuturials found in internet, can someone give me a clue? much thanks

**Comment by vincentshow** [comment]
i dont know which repo is suitable for getting help between dotnet/wcf and dotnet/core, so i create this issue both here and core  #https://github.com/dotnet/core/issues/130

**Comment by zhenlan** [comment]
Thank you for your query @vincentshow. As I replied in dotnet/core#130, the only way to build a WCF service is by using WCF in full .NET Framework at this point, but we are very interested to hear more about your scenarios/features if WCF server side on .NET Core is important to you. Please share more details on #1200.

Thank you for your feedback!
