### ISSUE TITLE
Websockets Http tests timed out on Helix

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1315]
These tests run on Windows timed out on the 6/20 Helix run, and one of them timed out on 6/19.  Given the other sporadic Http streaming test timeouts we have been seeing CI, indications are that Http streaming has regressed and now sporadically times out.  They may be unrelated, but we've seen timeouts in Net Native and CI for Ubuntu.

```
FunctionalTest.Extensibility.WebSockets.Tests#WebSocketTests.WebSocket_Http_Duplex_BinaryStreamed	
FunctionalTest.Extensibility.WebSockets.Tests#WebSocketTests.WebSocket_Http_Duplex_TextStreamed	
FunctionalTest.Extensibility.WebSockets.Tests#WebSocketTests.WebSocket_Https_Duplex_BinaryStreamed	
```
Error is:  Test case timeout was reached while waiting for the stream response from the Service to be completed. Timeout was: 00:01:00\r\nExpected: True\r\nActual:   False

**Comment by StephenBonikowsky** [comment]
Nothing in the history of this file indicates that there was any kind of test change that could have anything to do with these failures.
Also, all of these websocket tests are ActiveIssued on AnyUnix.

**Comment by zhenlan** [comment]
The tests are still failing in the most recent Helix runs. @mconnew can you please look into this?

**Comment by mconnew** [comment]
This isn't a product issue, it's a test issue. The tests depend on static state, but the nightly Helix tests run the test suites on multiple platforms at once, which means multiple clients are hitting the service concurrently. The WebSockets tests aren't currently safe for concurrent calls and that's what's causing the failures.
