### ISSUE TITLE
Add scenario tests for WindowsStreamSecurityUpgradeProvider

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1329]
WindowsStreamSecurityUpgradeProvider is not covered by any scenario tests.  We need scenario tests that exercise both sync and async paths.

**Comment by iamjasonp** [comment]
This should be done upon automation of domain-based security tests

**Comment by hongdai** [comment]
I have verified this class is covered in the manual domain-based security tests. After running the manual tests, the class line coverage is 58.7%. Given it's an internal class that customers do not have direct access, it should be sufficient.

I'm closing this issue as automation for domain-base security tests is not a near term goal and also are tracked elsewhere.
