### ISSUE TITLE
Can't generate scaffold code from SVC which works with svcutil.exe (incorrect handling of KeyValuePair`2 type)

### ISSUE THREAD

**Issue by duizendnegen** [dotnet/wcf#1340]
Generating from http://services.carsolize.com/BookingServices/DynamicDataService.svc fails

Workaround: http://tattoocoder.com/asp-net-core-getting-clean-with-soap/

Trace:
```
Scaffolding Code ...

Error:Error: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: Referenced type 'System.Collections.Generic.KeyValuePair`2, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' with data contract name 'KeyValuePairOf_x007B_0_x007D__x007B_1_x007D_BsJfAo7l' in namespace 'http://schemas.datacontract.org/2004/07/System.Collections.Generic' cannot be used since it does not match imported DataContract. Need to exclude this type from referenced types.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IDynamicDataService']
Error: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IDynamicDataService']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='BasicHttpBinding_IDynamicDataService']
Error: Cannot import wsdl:port
Detail: Value cannot be null.
Parameter name: format
XPath to Error Source: //wsdl:definitions[@targetNamespace='']/wsdl:service[@name='DynamicDataService']/wsdl:port[@name='BasicHttpBinding_IDynamicDataService']
Error: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IDynamicDataService']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='BasicHttpBinding_IDynamicDataService1']
Error: Cannot import wsdl:port
Detail: Value cannot be null.
Parameter name: format
XPath to Error Source: //wsdl:definitions[@targetNamespace='']/wsdl:service[@name='DynamicDataService']/wsdl:port[@name='BasicHttpBinding_IDynamicDataService1']
Error: No endpoints compatible with .Net Core apps were found.
An error occurred in the tool.

Failed to generate service reference.
```

**Comment by roncain** [comment]
Sorry you're having issues @duizendnegen .  Just yesterday we publically released our RTM stable packages for the whole .NET Core stack, including WCF, as well as an updated Connected Services extension for VS.  Are you in a position to try those to see if the problem continues?

[Announcing NET Core 1.0](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/)
[WCF Release notes](https://github.com/dotnet/wcf/releases)
[Connected Services blog](https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/)
[Connected Services download](https://visualstudiogallery.msdn.microsoft.com/c3b3666e-a928-4136-9346-22e30c949c08)

**Comment by duizendnegen** [comment]
I did try those - at least, I downloaded every package just a few hours ago. Is there a way I can dump my version stack of .NET Core & Connectec Services in here?

**Comment by davidlottavalara** [comment]
I'm seeing a similar error trying to import `https://avatax.avalara.net/account/AccountSvc.wsdl` using Visual Studio WCF Connected Service `0.3.20624.0`

```
Scaffolding Code ...
Error:Error: Cannot import wsdl:binding
Detail: The WSDL binding named AccountSvcSoap12 is not valid because no match for operation ServiceSettingSave was found in the corresponding portType definition.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://avatax.avalara.com/services']/wsdl:binding[@name='AccountSvcSoap12']
Error: Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://avatax.avalara.com/services']/wsdl:binding[@name='AccountSvcSoap12']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://avatax.avalara.com/services']/wsdl:service[@name='AccountSvc']/wsdl:port[@name='AccountSvcSoap12']
An error occurred in the tool.

Failed to generate service reference.
```

**Comment by roncain** [comment]
Hi @duizendnegen and @davidlottavalara .  I can confirm I see the identical error message trying to build an ASP.NET Core app and using Connected Services to the address you provided.  Thanks for reporting this issue -- we will investigate.  I believe you are using the right version of WCF Connected Service, which is still a preview version.

/cc @mlacouture @zhenlan

**Comment by duizendnegen** [comment]
Will you be welcoming community PRs for this issue? If so, what would be a good place to start? I tried to browse through the repo, Ctrl+F for the specific error messages, but I couldn't get much further - however I'm interested in making a contribution here.

**Comment by zhenlan** [comment]
Thank you @duizendnegen for offering the help and sorry for the confusion. The source code of WCF Connected Service is not yet put up on GitHub, but that is certainly in our plan. We currently have a few higher priority items to do and we need to go through a few processes to get code OSS. Once the code is made available, we absolutely will welcome community contributions.

**Comment by mlacouture** [comment]
this issue has been fixed for dotnet-svcutil.exe (WCF Connected Service). We need to port the fix over .net core ...

**Comment by mlacouture** [comment]
BTW: an update with the fix is now available: https://visualstudiogallery.msdn.microsoft.com/c3b3666e-a928-4136-9346-22e30c949c08

**Comment by duizendnegen** [comment]
Just wanted to confirm: for me, the update solved the problem. Feel free to keep this issue open to track other integration, or close it if also considered completed from your side.

**Comment by mlacouture** [comment]
thank you for confirming.

**Comment by mlacouture** [comment]
BTW: this is a serialization issue and the fix needs to go into the corefx repo ...

**Comment by mlacouture** [comment]
fixed with pull request https://github.com/dotnet/corefx/pull/10870
