### ISSUE TITLE
Root certificate is not considered valid on *nix

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1347]
The Infrastructure test that verifies the validity of the root certificate fails on *nix. It fails when we use FindBy on the X509Certificate2Collection and ask for only a valid cert.

Exception is:
```
MESSAGE:
Did not find valid certificate with thumbprint 737B995D0F2829DC37EEC32C01559F5EDEA6E94B in StoreName 'Root', StoreLocation 'CurrentUser'\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at SetupValidationTests.ValidateCertificate(X509Certificate2 certificate, StoreName storeName, StoreLocation storeLocation) at SetupValidationTests.Root_Certificate_Correctly_Installed()
```

**Comment by roncain** [comment]
I'm closing this because it no longer repro's since we moved forward to latest package dependencies.  The Infrastructure.Tests project has been verified to run properly on Ubuntu.

**Comment by roncain** [comment]
Re-opening because this is still failing in both VSO and CI.

**Comment by iamjasonp** [comment]
See https://github.com/dotnet/corefx/issues/10801

**Comment by iamjasonp** [comment]
We're still waiting for a package versions update

**Comment by iamjasonp** [comment]
The package versions are up to date - #1475 needs to be rebased and I think it should pass now. If it doesn't, it means that something in corefx is still not quite fixed...

**Comment by iamjasonp** [comment]
Woot. fixed :)
