### ISSUE TITLE
Root_Certificate_Installed ConditonalFact always evaluating to false for selfhosted Windows tests

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#1353]
As of this build: http://dotnet-ci.cloudapp.net/job/dotnet_wcf/job/master/job/outerloop_selfhost_windows_nt_debug/52/, Root_Certificate_Installed is always evaluating to false on selfhost Windows. 

The root cause seems to be the following exception: 

```
  System.IO.FileLoadException: Could not load file or assembly 'System.Security.Cryptography.X509Certificates, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

  File name: 'System.Security.Cryptography.X509Certificates, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at ServiceUtilHelper.EnsureRootCertificateInstalled()
     at Infrastructure.Common.ConditionalTestDetectors.IsRootCertificateInstalled() in C:\git\wcf1\src\System.Private.ServiceModel\tests\Common\Infrastructure\ConditionalTestDetectors.cs:line 28
```

which can be see when we output the exception that's caught and swallowed in `ServiceUtilHelper.IsRootCertificateInstalled`

We are not seeing CI failures because [Root_Certificate_Installed] is always evaluated as false, and hence these tests are skipped

**Comment by iamjasonp** [comment]
Client_Certificate_Installed is also evaluating to false for the same reason

**Comment by iamjasonp** [comment]
Note that the certificates are successfully installed on the machine.

**Comment by roncain** [comment]
Investigation shows we have dependency resolution issues in most scenario test projects.  For example, Security\TransportSecurity works, but many others do not.  In the projects that don't work, the binary folders contain different versions of DLL's than projects that do work (ex: System.Runtime.dll).  By adding explicit dependencies to project.json's for S.Net.Primitives, S.SM.NetTcp and S.SM.Security, those projects can be made to work.  Needs investigation, but this isn't an issue with ConditionalFact. per se.
