### ISSUE TITLE
Scaffolding code fails (MessageSecurity issue)

### ISSUE THREAD

**Issue by mmbetzel** [dotnet/wcf#1354]
Generating from https://mm2nq.morgenundmorgen.com/v210/Service.svc

Scaffolding Code ...
Error:Error: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='BasicHttpBinding_IVersicherungsService']
Error: Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='BasicHttpBinding_IVersicherungsService']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:service[@name='WebVersicherungsService']/wsdl:port[@name='BasicHttpBinding_IVersicherungsService']
Error: No endpoints compatible with .Net Core apps were found.
An error occurred in the tool.

Failed to generate service reference.

**Comment by mlacouture** [comment]
This problem happens because message security is not yet fully supported in .net core and the service implements message security.  Now, the error message is misleading and not very helpful, we need to improve it ...

**Comment by lburkovsky** [comment]
Do you have any plans to support this functionality?

**Comment by mlacouture** [comment]
Yes, that's in our radar.

**Comment by zhenlan** [comment]
Hi @lburkovsky, the support of message security is tracked by issues #3, #4, #8. We are still working on the plan of how to support it in .NET Core. We will update those issues when we have an update.

cc: @EricaMo

**Comment by ammar-haider** [comment]
Hi @zhenlan , any progress on this? I have a WCF service with TransportWithMessageSecurity that is being used by many many clients. Now there is a need to develop a new client and I want to use asp.net core but unfortunately getting stuck because of this issue. Is there any workaround?
thanks

**Comment by zhenlan** [comment]
Hi @ammar-haider I don't see the support of message security can be added in anytime soon. Will it be a viable solution for you to use transport security with client cert auth or Kerberos auth?

**Comment by Jelle87** [comment]
Any news wether this is on the short term roadmap?

**Comment by mlacouture** [comment]
Hi @Jelle87 

Support for message security in the .Net Core framework is going to take a while as it requires several other APIs not yet in the framework.  We will update this issue when we have a clearer roadmap for this feature.

thanks again for your interest in the .Net Core platform and the WCF Web Service Reference tool.

cc @zhenlan

**Comment by hemabhushanr** [comment]
I would like to know when will .Net Core platform support message security

**Comment by mlacouture** [comment]
Please track message security support with issues #3, #4 and #8 as @zhenlan  mentioned.  thanks,

**Comment by ckrandhir** [comment]
Any update on MessageSecurity issue ?
