### ISSUE TITLE
Issues regarding using System.Web.Services.Configuration.XmlFormatExtensionAttribute

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1363]
Issue reported from [blog post](https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/) when using WCF Connected Service. 

> I am getting this issue while trying to add a reference:
> “Error: Cannot import wsdl:binding
> Detail: Unable to cast object of type ‘System.Attribute[]’ to type ‘System.Web.Services.Configuration.XmlFormatExtensionAttribute[]’.”

The type `System.Web.Services.Configuration.XmlFormatExtensionAttribute` is not supported on core.

**Comment by mlacouture** [comment]
Looking for WSDL or service address for repro ...

**Comment by RLaptev** [comment]
http://ws.cdyne.com/ip2geo/ip2geo.asmx?wsdl

**Comment by mlacouture** [comment]
thank you!

**Comment by mlacouture** [comment]
this issues has been fixed for dotnet-svcutil (WCF Connected Service), need to port the fix to .net core ...

**Comment by mlacouture** [comment]
BTW: an update with the fix is now available: https://visualstudiogallery.msdn.microsoft.com/c3b3666e-a928-4136-9346-22e30c949c08

**Comment by RLaptev** [comment]
Thanks!

**Comment by mlacouture** [comment]
This fix needs to be applied once the affected API has been ported to corefx.

**Comment by zhenlan** [comment]
This API won't be ported to corefx.
