### ISSUE TITLE
CRL server offline is causing multiple tests to fail

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1365]
Immediately after changing the CRL endpoint to use the REST TestHost, we started seeing multiple tests fail in different environments.  The error is:
```
Caught Unexpected exception:System.ServiceModel.Security.SecurityNegotiationException: X509ChainBuildFail, CN=not-real-subject-name, O=DO_NOT_TRUST, OU=Created by https://github.com/dotnet/wcf; 4A5FAEC4A0337250DF6B66D24CF2FAEB04ED70B7, The revocation function was unable to check revocation for the certificate.
 The revocation function was unable to check revocation because the revocation server was offline.
  ---> System.IdentityModel.Tokens.SecurityTokenValidationException: X509ChainBuildFail, CN=not-real-subject-name, O=DO_NOT_TRUST, OU=Created by https://github.com/dotnet/wcf; 4A5FAEC4A0337250DF6B66D24CF2FAEB04ED70B7, The revocation function was unable to check revocation for the certificate.
 The revocation function was unable to check revocation because the revocation server was offline.
```

The failing tests are:

- CustomBindingTests.DefaultSettings_Tcp_Binary_Echo_RoundTrips_String
- Tcp_ClientCredentialTypeCertificateCanonicalNameTests.Certificate_With_CanonicalName_Fqdn_Address_EchoString
- Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_With_ServerAltName_EchoString	Chunk149
- IdentityTests.VerifyServiceIdentityMatchDnsEndpointIdentity
- IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException

Failing environments include:

- N on K nightly run
- WCF selfhost nightly run
- WCF IIS host nightly run
- Helix nightly run

**Comment by iamjasonp** [comment]
Failures not seen anymore after regenerating certificates. Please reopen this issue or open a new issue if this is seen again, as this should be fixed for good by #1379
