### ISSUE TITLE
MessageInterceptorTest is failing on NetNative

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1374]
It is throwing from...
C:\OSS\WCF\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs
line 155
ChannelFactoryCannotBeUsedToCreateChannels

For some reason ChannelFactoryBase.ValidateCreateChannel is evaluating the CommunicationState as not Opened and throwing.

@mconnew took enough of a look at this to agree that there is something strange going on. This should fail on any normal N on K runs.

**Comment by roncain** [comment]
Is this after the rename? Remember there was a product fix post Rtm, and this test was altered to reflect it. This test cannot be run against shipped packages.

**Comment by StephenBonikowsky** [comment]
Agree that this issue is no longer valid, it has been fixed in current pre-release development.
