### ISSUE TITLE
Root_Certificate_Installed [CondtionalFact] is not aware of Linux nuances

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#1380]
Root_Certificate_Installed will check whether or not a certificate is installed on the box, but only by using the X509 APIs available to .NET. 

In Linux/OS X, we must also install the certificate to the system's root store for HTTP scenarios to work; merely installing it to the user root store will not work - which is what Root_Certificate_Installed does. 

We either need to: 
* Split up the ConditionalFact to be aware of this nuance, or 
* (Preferred) Have the ConditonalFact also check for installation in the machine root store, and return false if not available. This might reduce some coverage we get in Helix, but we can rely on CI to give us coverage in that area

**Comment by roncain** [comment]
@iamjasonp -- the other option is to not make the ConditionalFact detector smarter but to insist the CI and VSO scripts set Root_Certificate_Installed=true. Of course we need to find a way to install to the right stores on Linux in our VSO runs (#1304).  We need to make a call on how much we expect to rely on the detectors.

**Comment by zhenlan** [comment]
@iamjasonp will open corefx bug for consistent cert install behavior on all platforms
We will fix the infrastructure test to make sure certs are installed in system root store as well.
All tests on CI should pass once Jason's cert install script are hooked up.
Http tests will fail on Helix lab run until we figure out a way to install cert in system root store.

**Comment by iamjasonp** [comment]
All these items are complete, so closing off this bug. There is a PR out to fix install on OpenSUSE. 

> All tests on CI should pass once Jason's cert install script are hooked up.
Note that this statement isn't true :smile: it means that tests requiring the Root_Certificate_Installed condition will pass
