### ISSUE TITLE
Create test directory for test common code.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#139]
Test common code is now located: ...\System.Private.ServiceModel\tests\Common\src

Need to create the directory: ...\System.Private.ServiceModel\tests\Common\test and put the file, "...\System.Private.ServiceModel\tests\Common\TestPropertiesTest.cs" in it, these are tests that validate certain test infrastructure features.

**Comment by zhenlan** [comment]
Done by @StephenBonikowsky already.
