### ISSUE TITLE
Support NetTcpBinding default ctor

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#14]
The default ctor for NetTcpBinding cannot be used yet because it relies on NegotiateStream which is not yet available.

Current workaround is to construct it like this:
NetTcpBinding binding = new NetTcpBinding(SecurityMode.None);

**Comment by roncain** [comment]
This issue depends on resolving https://github.com/dotnet/corefx/issues/1844 first.
Once NegotiateStream is available, this current issue involves enabling its support in NetTcpBinding.

**Comment by zhenlan** [comment]
I think this can be closed now given that we've had NegotiateStream support on both Windows and *nix. @iamjasonp can you please confirm?

**Comment by zhenlan** [comment]
This is not supported on UWP due to lack of NegotiateStream support in Networking layer on UWP.

**Comment by zhenlan** [comment]
Close this as the NegotiateStream support for UWP is tracked by #1235.
