### ISSUE TITLE
Add message attribute APIs

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1410]
- [ ] `T:System.ServiceModel.MessageHeaderArrayAttribute`
- [ ] `T:System.ServiceModel.MessagePropertyAttribute`

**Comment by roncain** [comment]
Tasks are:
- [ ] Add implementation [in progress]
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by roncain** [comment]
PR waiting for feedback
