### ISSUE TITLE
Add APIs to support reliable messaging

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1411]
`T:System.ServiceModel.Channels.IBindingDeliveryCapabilities`

**Comment by pankajbhagra** [comment]
Hi Zhenlan,

I am wondering if its possible to make the WS-Reliable messaging work with the dotnet 1.0 release (with patch) ? if not, do u have any suggestion of how to make it work before 1.2 release is available. thanks.

later,
pankaj

**Comment by zhenlan** [comment]
This is a large work item. We will have to put it in future backlog and prioritize among other things.

**Comment by HongGit** [comment]
Duplicate #1655.
