### ISSUE TITLE
Add API T:System.ServiceModel.Channels.XmlSerializerImportOptions

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1414]
This API has dependency on CodeDom

**Comment by roncain** [comment]
This class contains public API's for CodeDOM and System.Web.Services.WebReferenceOptions.  It is likely to be larger in scope than originally thought.

**Comment by zhenlan** [comment]
Part of the CodeDOM was made available recently in corefx.

@mlacouture @hongdai is this something dotnet svcutil is/will be using?

**Comment by hongdai** [comment]
Yes, dotnet svcutil is using this API: XmlSerializerImportOptions

**Comment by zhenlan** [comment]
@StephenBonikowsky can you see if it is feasible to bring this type to Core because only part of CodeDom is available?

**Comment by StephenBonikowsky** [comment]
At a high level the necessary pieces of CodeDom have been added to CoreFx.

However, WsdlNS.WebReferenceOptions does not yet exist. It lives in the namespace 'System.Web.Services.Description', I'm not sure who owns this namespace. In full framework it is located under NetFx2.0. @zhenlan any ideas?

**Comment by zhenlan** [comment]
We will revisit this if we find dotnet-svcutil is going to need this API in the future.
