### ISSUE TITLE
Add API T:System.ServiceModel.Channels.ChannelPoolSettings

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1416]

**Comment by roncain** [comment]
Tasks are:
- [ ] Add implementation [in progress]
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by StephenBonikowsky** [comment]
Need to finish this next Monday. Going to complete it for this milestone.
