### ISSUE TITLE
Add API T:System.ServiceModel.Channels.UnderstoodHeaders

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1419]

**Comment by roncain** [comment]
Tasks are:
- [x] Add implementation [already in code base]
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by StephenBonikowsky** [comment]
Created Issue #1773 for adding the scenario test.
