### ISSUE TITLE
Add API T:System.ServiceModel.Dispatcher.IChannelInitializer

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1422]

**Comment by roncain** [comment]
Interface is already in our code and just needs to be exposed.
Recommend System.ServiceModel.Primitives.
Although it is used by server-side code, it is also used on client-side for Dispatch.

**Comment by roncain** [comment]
Tasks are:
- [X] Add implementation [already in code base]
- [ ] Add to contract [waiting till update to latest dependencies and issues around adding API's]

**Comment by roncain** [comment]
[Scenario enabled by this API]
The addition of this API permits a client application (including mid-tier) to register an IChannelInitializer that will be called every time a channel is opened.  This extensibility point can be used to perform some additional initialization required for all channels or to do things like registering event listeners to track the channel's state.

This [WCF Extensibility Blog](https://blogs.msdn.microsoft.com/carlosfigueira/2012/02/13/wcf-extensibility-initializers-instance-context-channel-call-context/) provides a real-world scenario that uses an IChannelInitializer implementation to track the number of open channels as well as when they are closed.
