### ISSUE TITLE
Add API T:System.ServiceModel.Dispatcher.IDispatchMessageFormatter

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1423]

**Comment by roncain** [comment]
Tasks are:
- [x] Add implementation [already in product]
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by roncain** [comment]
I recommend *not* adding IDispatchMessageFormatter to the public API at this time.
Its intended use is server-side, not client.  And we do support IClientMessageFormatter for the client-side.  If/when server-side support becomes available, it would make sense to add both IDispatchMessageFormatter and IDispatchMessageInspector to the public API for the server.

**Comment by zhenlan** [comment]
Design discussion agrees not to add this API at this point. Please close this issue.

**Comment by roncain** [comment]
Closing as agreed.
