### ISSUE TITLE
Add API T:System.ServiceModel.PeerHopCountAttribute

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1426]
The API is not used internally.

**Comment by roncain** [comment]
Tasks are:
- [ ] Add implementation
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by roncain** [comment]
[Design Discussion]
We should discuss whether exposing this in the public API is necessary.  In the full framework, [PeerHopCount] could really appear in any [MessageContract] class to mark which fields are to be treated as the hop count.  But it is really intended just for peer-to-peer programming, and I can't find any special handling of it in WCF product code.  It is possible some [MessageContract] type containing this attribute might be used on the server, possibly leading to a compilation error if it is propagated to the client via Connected Services.  But I think that usage scenario is likely very rare and recommend we don't add this API until we know it is needed.

**Comment by zhenlan** [comment]
Design discussion agrees to not add these APIs at this point. We will wait for customer feedback to see if there is a need. As a workaround, user can just use [MessageHeader] with explicitly specified XML namespace and name.

**Comment by roncain** [comment]
Closing as agreed
