### ISSUE TITLE
MessageSecurityOverTcp.ClientCredentialType not supported

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1434]
The MessageSecurityOverTcp.ClientCredentialType property throws PlatformNotSupportedException for any security type but None.

**Comment by zhenlan** [comment]
We will change this test to a negative test (verifying PNSE). The test will not pass on full framework, we will do another pass in the future to fix all relevant tests when we get there.

**Comment by roncain** [comment]
PR #1435 has the modified test.  I will close this issue as soon as that PR is signed off and merged.

**Comment by roncain** [comment]
Closing because PR #1435 was merged.
