### ISSUE TITLE
Add API T:System.ServiceModel.Channels.IBindingRuntimePreferences

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1444]

**Comment by roncain** [comment]
Tasks are:
- [ ] Add implementation
- [ ] Add to contract 
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by roncain** [comment]
[Design Discussion]
I believe the only place this interface is checked in in building the server-side dispatch stack.  That code path is never executed by any of our scenario tests, not even duplex.  Therefore I propose that we do *not* add this interface to the public API unless @mconnew sees a use for it in future development.

If we decide to add it, I have a local branch that adds it to the API and unit tests it.

/cc: @zhenlan @StephenBonikowsky @hongdai @mconnew

**Comment by zhenlan** [comment]
Design discussion agrees Ron's recommendation. Please close this.

**Comment by roncain** [comment]
Closing as agreed
