### ISSUE TITLE
Scaffolding fails with .NETCoreApp with errors "unable to resolve x"

### ISSUE THREAD

**Issue by hanssens** [dotnet/wcf#1445]
When using the Visual Studio WCF Connected Service extension (v0.3.20722.0) for VS2015 and attempt to add a service reference to a .NET Core Library, I get the following error:

	Scaffolding Code ...
	Error:Error: Errors in C:\Users\...\AppData\Local\Temp\WCFConnectedService\2016_aug_03_11_39_43\svcutil_bootstrap\dotnet-svcutil\project.json
	    Unable to resolve 'System.ComponentModel.EventBasedAsync (>= 4.0.11)' for '.NETCoreApp,Version=v1.0'.
	    Unable to resolve 'System.Net.WebSockets.Client (>= 4.0.0)' for '.NETCoreApp,Version=v1.0'.
	    Unable to resolve 'System.Private.ServiceModel (>= 4.1.0)' for '.NETCoreApp,Version=v1.0'.
	    Unable to resolve 'System.ServiceModel.Primitives (>= 4.1.0)' for '.NETCoreApp,Version=v1.0'.
	An error occurred while bootstrapping svcutil. This usually happens when processing references.  You might be able to work around this problem by not providing reference parameters, and manually removing any types redefined in the generated proxy code.

	Failed to generate service reference.

![wcf](https://cloud.githubusercontent.com/assets/493382/17366469/ba84a468-598b-11e6-931b-d156c5e1fab7.png)

**Steps to reproduce**  
1. Create a new **Class Library (.NET Core)**
2. Select project > Add connected service
3. Attempt to generate the code, using the following address http://ws.cdyne.com/ip2geo/ip2geo.asmx?wsdl 

I'm using VS2015 with Update 3, patched/updated with everything up until today. The problem is not limited to the service mentioned above, but with all other SOAP/WCF services I've tried so far.

**Comment by mlacouture** [comment]
This seems more like a problem with the solution, nuget packages cannot be resolved.
@hanssens, can you try rebuilding the project and resolving any package restore failures before trying to add the service reference again? thanks,

**Comment by hanssens** [comment]
@mlacouture thanks for the feedback. Unfortunately, this happens on **all** new and existing .NET Core class library projects I attempt to add a service reference to. 

I can reproduce the error on two different machines (Win10), with all latest updates of Visual Studio (v14.0.25431.01 Update 3, with all extensions up-to-date). I have asked a colleague with pretty much the same setup and he confirms the same behaviour as well.

Please, have a look at the steps to reproduce from the originally posted issue.

**Comment by hongdai** [comment]
@hanssens I have tried the original steps and could NOT reproduce the issue on Windows 10.

I agree with @mlacouture this looks like a problem with your machine set up.

Could you check 
1) The NuGet package sources. It should has both https://api.nuget.org/v3/index.json and C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
2) Make your project.json like below, and check if all references have been resolved correctly.
{
  "version": "1.0.0-*",
  "dependencies": {
    "NETStandard.Library": "1.6.0"
  },
  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50",
      "dependencies": {
        "System.ServiceModel.Duplex": "4.0.1",
        "System.ServiceModel.Http": "4.1.0",
        "System.ServiceModel.NetTcp": "4.1.0",
        "System.ServiceModel.Security": "4.0.1",
        "System.Xml.XmlSerializer": "4.0.11"
      }
    }
  }
}

**Comment by hanssens** [comment]
Thanks for the response, @hongdai. I feel almost ashamed, but indeed: we were running the NuGet v2 instead of v3 url. Changing this worked immediately! What a triviality...

Peculiar that dotnet core worked with the older feed, but I'm happy it works now. 👍
