### ISSUE TITLE
Tcp_ClientCredentialTypeTests/TcpClientCredentialType_Certificate_EchoString fail due to found multiple X.509 certificate on OSX in Helix

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1478]
**Failed cases**
Tcp_ClientCredentialTypeTests/TcpClientCredentialType_Certificate_CustomValidator_EchoString
Tcp_ClientCredentialTypeTests/TcpClientCredentialType_Certificate_EchoString 

**Message**
    System.InvalidOperationException : Found multiple X.509 certificates using the following search criteria: StoreName 'My', StoreLocation 'CurrentUser', FindType 'FindByThumbprint', FindValue 'C7979286A20741AE49436142E9D9CD72BA2F59F4'. Provide a more specific find value.

**Stack Trace**
       at System.ServiceModel.Security.SecurityUtils.GetCertificateFromStoreCore(StoreName storeName, StoreLocation storeLocation, X509FindType findType, Object findValue, EndpointAddress target, Boolean throwIfMultipleOrNoMatch)
       at System.ServiceModel.Security.SecurityUtils.GetCertificateFromStore(StoreName storeName, StoreLocation storeLocation, X509FindType findType, Object findValue, EndpointAddress target)
       at System.ServiceModel.Security.X509CertificateInitiatorClientCredential.SetCertificate(StoreLocation storeLocation, StoreName storeName, X509FindType findType, Object findValue)
       at Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString()

**Failing configurations**
- OSX.1011.Amd64

**Comment by iamjasonp** [comment]
Generally speaking, when adding the same cert to the same store, no duplicates will exist as it's de-duplicated. 

This issue has the potential to happen on all *nix platforms. The reason behind this is a race condition around the X509Store PAL when certificates are added to the store - when one process. What you will observe is (thumbprint).pfx and (thumbprint).1.pfx in the same directory on the file system. 

This error does not happen in Windows as there's deduplication that happens in the certificate store

Note that technically, it's possible for two certificates to have the same thumbprint, as a thumbprint is a SHA-1 hash. It's exceedingly rare for a collision to happen though

We haven't seen this happen often - if there is a further issue we should open an issue in corefx to get it looked at

**Comment by imcarolwang** [comment]
Same issue occurred in build [20160818.01](https://mc.dot.net/#/product/netcore/master/source/official~2Fwcf~2Fmaster/type/test~2Fscenario~2Fselfhosted~2F/build/20160818.01/workItem/Security.TransportSecurity.Tests/analysis/xunit/Tcp_ClientCredentialTypeTests~2FTcpClientCredentialType_Certificate_CustomValidator_EchoString/log/93802614-e016-4292-86df-cc14ea6f7d6d)

**Comment by iamjasonp** [comment]
@imcarolwang - thanks, I will investigate further

**Comment by iamjasonp** [comment]
dotnet/corefx#11016 opened; However I think there is additional work for us to try to make sure multiple certs aren't added at the same time to prevent this from happening

**Comment by iamjasonp** [comment]
Closing - this one shouldn't repro after some manual intervention (or at least has a very low chance of reproing).
