### ISSUE TITLE
Solve issue of nightly Helix runs using CoreFx packages that don't exist

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1486]
Today our nightly VSO build frequently fail in sync.cmd looking for CoreFx packages that don't exist.  There is a flaw in the package dependency calculation that assumes the version being built for *WCF* is the version of CoreFx packages to use.  But if CoreFx has not yet built those versions, it will fail.  

Each triggered build in VSO for CoreFx or WCF is given a trailing build number (ex: .01, .02, ...).  If CoreFx fails to publish during a nightly build, there is no .01 for WCF to consume, and we fail.  Or, even if CoreFx succeeds in publishing a .01, we cannot launch a .02 build of WCF because it won't find CoreFx packages to match.

**Comment by zhenlan** [comment]
@StephenBonikowsky can you please close this if this is solved already?
