### ISSUE TITLE
Hook up auto-update PR infrastructure

### ISSUE THREAD

**Issue by dagood** [dotnet/wcf#1489]
I'm planning on porting over changes that will start auto-updates like https://github.com/dotnet/corefx/pull/10986 for wcf, based on the dotnet/versions repo. I expect the changes here will be like https://github.com/dotnet/corefx/pull/10868, plus wcf dependency info, a buildtools upgrade, and a PR on dotnet/versions to add wcf subscriptions to Maestro.

Before I do that, do the auto-updates sound useful for wcf?

A few more details: the automation updates the same PR when there's an open one, so it won't cause a PR flood. This also changes the way dependency validation works so it's based on the full list of packages produced in each build, so no more regexes.

/cc @roncain @StephenBonikowsky

**Comment by roncain** [comment]
Thanks @dagood .  Stephen should be back today, and he probably has some insights into other stuff we need to do.  I know whenever we have manually updated, we've generally spent the next couple days repairing things -- due partly to the fact we take more package dependencies on just about everything in CoreFx.  Occasionally we find issues with random CoreFx packages that can break the build.

We're also now significantly behind the CoreFx shared scripts that were put in a couple weeks ago for the new dev workflow and VSO integration.  We were waiting for CoreFx to stabilize them before porting (they were massively unstable for several days).  Probably this week. I'll let Stephen comment more.

/cc: @StephenBonikowsky

**Comment by StephenBonikowsky** [comment]
@dagood I think PR #1531 will take care of the Wcf dependency info side of things, and I think the buildtools update has been done. I also think Wcf subscriptions has been added to Maestro in dotnet/versions?

I spoke with @zhenlan and we do want to take advantage of the auto-updates for wcf.

I plan on getting the VSTS pieces done tomorrow, once PR #1531 is in.

**Comment by StephenBonikowsky** [comment]
All the pieces should now be complete and functional.
