### ISSUE TITLE
Exceptions in Streaming over Http on Ubuntu 16.04

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1503]
We're consistently seeing exceptions in both sync and async streaming over http on Ubuntu 16.04 on corefx build 24403. More details to come after the investigation.

**Comment by zhenlan** [comment]
@KKhurin is trying with a more recent build and did not see this repros yet.

**Comment by KKhurin** [comment]
Not repro on recent 1.1 builds.
