### ISSUE TITLE
Investigate port exhaustion issue on Net.Tcp in stress

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1504]
When running stress against IIS over Net.Tcp transport we see port exhaustion. So far it does not look like any of the known issues. Need more investigation to figure out the cause.

**Comment by zhenlan** [comment]
This still repros often.

@mconnew suggested to set a break point at socket closing for further investigation.

**Comment by zhenlan** [comment]
@KKhurin made fix #1752 for this issue.
