### ISSUE TITLE
Update netci.groovy

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1506]
Whith the changes to support the new Dev Workflow netci.groovi needs to be updated in particular the [Jenkins jobs definition](https://github.com/StephenBonikowsky/wcf/blob/master/netci.groovy#L112).

**Comment by iamjasonp** [comment]
We should use this opportunity to also turn on the "@dotnet-bot help" functionality

**Comment by iamjasonp** [comment]
> We should use this opportunity to also turn on the "@dotnet-bot help" functionality

Actually scratch that. Let's take the help functionality netci.groovy changes separately; the change to netci.groovy -> dev workflow needs to happen when the dev workflow goes in

**Comment by iamjasonp** [comment]
Done, #1508, #1516
