### ISSUE TITLE
Manual tests NegotiateStream With ExplicitUserNameAndPassword tests failed

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1518]
NegotiateStream_Http_Tests.NegotiateStream_Http_With_ExplicitUserNameAndPassword_With_Spn
NegotiateStream_Http_Tests.NegotiateStream_Http_With_ExplicitUserNameAndPassword
NegotiateStream_Tcp_Tests.NegotiateStream_Tcp_With_ExplicitUserNameAndPassword

This is a test issue. ExplictUserName is set to domainName\username format for Digest test to work. We assume ExplictUserName is set without domain prefix in the NegotiateStream tests. Hence the failures. We need to have a solution works for both Digest and NegotiateStream Tests.

**Comment by roncain** [comment]
Thanks @hongdai .  Looking at these tests, I see they are already using test helpers for GetDomain() and GetExplicitUserName.  Is the right fix merely combining those in 2 strings when setting ClientCredential.UserName in these tests?

**Comment by hongdai** [comment]
GetExplicitUserName returns domain\username currently as Digest test needs it.

Thus the right fix is to remove setting Domain in these tests as Domain is already part of the user name.

**Comment by hongdai** [comment]
The latest test pass result shows set ExplicitUserName without prefix with Domain worked for Digest test. Thus there is no code change to fix this issue. Just ensure to set ExplicitUserName without prefix with Domain in the manual test pass process.

**Comment by roncain** [comment]
@hongdai -- be aware that one of these tests still fails when run self-hosted on the same machine.  It is being tracked with issue #1499
