### ISSUE TITLE
dotnet-svcutil does not generate any operations or data contracts

### ISSUE THREAD

**Issue by sklose** [dotnet/wcf#1524]
I am trying to add a connected service based on this WSDL https://ws.tradetracker.com/soap/affiliate?wsdl from within Visual Studio as follows

![image](https://cloud.githubusercontent.com/assets/546088/18496846/85182200-79f7-11e6-87f8-c162ed5edba9.png)

![image](https://cloud.githubusercontent.com/assets/546088/18496856/911c4266-79f7-11e6-84da-d8c16e1ba068.png)

![image](https://cloud.githubusercontent.com/assets/546088/18496859/95dcf20a-79f7-11e6-9d94-690fde5197ac.png)

![image](https://cloud.githubusercontent.com/assets/546088/18496860/9a2d24ce-79f7-11e6-9a6a-5ff3c8d3512e.png)

Everything runs fine (no error message). And in the end this code was generated:

![image](https://cloud.githubusercontent.com/assets/546088/18496886/dd357154-79f7-11e6-9192-57ed7827db4b.png)

It doesn't contain any of the operations the remote service provides or any of the data contracts. Anything I can do to make it generate those?

Another service I tried with the same result is: http://ws.webgains.com/aws.php?wsdl

**Comment by sklose** [comment]
I just tried it from the command line, the issue seems to be

```
WSDL is not compatible with .Net Core apps because it contains one or more operations with SOAP Encoding (use='encoded'). Only the non-encoded operations will be generated.
```

Is this something that will be supported in the near future?

**Comment by hongdai** [comment]
@sklose Thanks for reporting it! 

I confirm the issue is because we do NOT currently support Soap encoded operations. We are considering to support it in the future. The feature request is tracked by #1549
