### ISSUE TITLE
Move ContractCallbackType unit tests to System.ServiceModel.Primitives

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#154]
The current unit test for ContractCallbackType lives in System.Private.ServiceModel but belongs in System.ServiceModel.Primitives.  Unless it is moved, it cannot be tested in NET Native.  I  believe it will fail in NET Native and block duplex

**Comment by roncain** [comment]
Not strictly required for beta7

**Comment by zhenlan** [comment]
@roncain do you have an update of this?

**Comment by roncain** [comment]
@StephenBonikowsky solved this issue when cleaning up our warning messages
