### ISSUE TITLE
Add OperationFormatUse to support soap encoded WSDL

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1549]
1. The Enum type OperationFormatUse  is missing from runtime.

There is a customer ask for OperationFormatUse.Encoded to be supported. See #1517 for details.

**Comment by zhenlan** [comment]
This depends on dotnet/corefx#10579.

**Comment by adamreed90** [comment]
Another request for this: https://github.com/dotnet/wcf/issues/1500 =D 
Our company would be willing to make a financial donation to see this be implemented!

**Comment by ei09026** [comment]
Any update for this issue? im facing the same problem!!

**Comment by zhenlan** [comment]
This will be unblocked when WCF is able to build on NS2.0. dotnet/corefx#10579 is already closed.

**Comment by Dereeg** [comment]
Looking forward to this feature as well.
