### ISSUE TITLE
System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by emailtowalter** [dotnet/wcf#1562]
Hi... I am migrating a existing WCF client to .net core and deploy to cloud foundry.  The security is using client certificate. 

Instead of regenerate WCF proxy, we simply reuse the existing proxy code generated using .net framework 4 and remove some attributes that gave us compilation error. 

Everything seems to work on windows, but when deploy to cloud foundry ( Ubunto underneath) , we got error "System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates". 

Here is the sample code that we use to set the client cert. 

            Binding binding;
            binding = new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly)
            {
                Security =
                {
                    Mode=BasicHttpSecurityMode.Transport,
                    Transport=new HttpTransportSecurity() {ClientCredentialType=HttpClientCredentialType.Certificate },
                }
            };

           SampleServicePortClient proxy;
            
            proxy = new SampleServicePortClient (binding, new EndpointAddress("http://test...."));
            proxy.ClientCredentials.ClientCertificate.Certificate = new X509Certificate2(CertificateFileName, CertificatePassword);
...

I guess my question is if this approach will work, and is there a workaround for this issue. 

Thanks, 

Walter

**Comment by hongdai** [comment]
Hi Walter,
We do not support using certificate file name to configure certificates in .Netcore. The supported approach is you install client certificate on the client machine, then use below API to configure client certificate:
factory.Credentials.ClientCertificate.SetCertificate(
                StoreLocation.CurrentUser,
                StoreName.My,
                X509FindType.FindByThumbprint,
                clientCertThumb);

Hope it helps,
Hong

**Comment by emailtowalter** [comment]
On cloud environment, many times we do not have the luxury to install the cert.  Isn't it one of the businesses case for .net core?

cert file approach worked in .net core. I wonder if it is just the way we reuse the old proxy code. Again, looking for ideas. 

thanks

**Comment by hongdai** [comment]
@emailtowalter just verify with my peer that cert file approach should still work in .net core.

I have edited my previous reply. Please take a look. We suspect you use https, and the error is caused by Server certificate failed to authenticate on the client side.

**Comment by emailtowalter** [comment]
@hongdai . thanks for taking the extra efforts to validate this. 

Yes, the service is https.  can you point me to the resource on the custom cert validator? 

Also, I can only use file based client cert. I am not sure what this API to do with it ? 
factory.Credentials.ClientCertificate.SetCertificate(
StoreLocation.CurrentUser,
StoreName.My,
X509FindType.FindByThumbprint,
clientCertThumb);

let me know. 

Walter

**Comment by mconnew** [comment]
@emailtowalter, the ideal thing would be to have your service use a certificate that is signed by a public CA that the client host is aware of. If this isn't possible, then you will need to validate the server certificate yourself. An example of using a custom certificate validator with https can be found [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs#L277) in one of our test methods. The implementation of the custom validator for that test can be found [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs#L1132). The only method you need to worry about is the Validate method, everything else is to do with validating our test scenario. You will need to sufficiently check that the correct certificate has been used as you will be bypassing the normal validation checks. I would expect checking that the thumbprint matches would be sufficient, although you should do your own research to decide what is sufficient validation for your purposes.

**Comment by emailtowalter** [comment]
Your recommendation resolved my problem .Thank you!
