### ISSUE TITLE
ServiceContract_TypedProxy_DuplexCallback test times out

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#157]
Remove the [ActiveIssue] attribute from the ServiceContract_TypedProxy_DuplexCallback and run the OuterLoop tests.  It times out waiting for the callback.

**Comment by roncain** [comment]
Should investigate/fix for beta7

**Comment by zhenlan** [comment]
This should been fixed by @mconnew already.

**Comment by roncain** [comment]
The test is still disabled with an [ActiveIssue].  It needs to be re-enabled and verified as fixed
