### ISSUE TITLE
How to use duplex communication and TCP binding in UWP?

### ISSUE THREAD

**Issue by leonli77** [dotnet/wcf#1606]
Stable versions of WCF as part of .NET Core 1.0 was released. Duplex and many other [WCF features](https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v1.0.0.md) can now be supported in Windows Universal Apps by referencing the 5.2.2 version of [Microsoft.NETCore.UniversalWindowsPlatform](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/5.2.2) package in the project.json file of a UWP project. So I want to create a uwp client as same as the wpf client in http://www.codeproject.com/Articles/25261/A-WCF-WPF-Chat-Application#
How to do it?

**Comment by mconnew** [comment]
I looked at the article and can comment on feature availability in .Net Core. In the article, there are two different WPF applications. The service is hosted in a WPF UI application and uses ServiceHost to host the chat service. WCF in .Net Core is the client implementation only so you will not be able to host the service in a UWP app, this will need to remain running on the full desktop framework. You could convert it to an Azure hosted service, but how to do this is out of scope for this repo.  
The second WPF application is the client app. All the features used by the article are available on the client side. The example uses no transport security with NetTcpBinding and this is supported with UWP. Are there are any specific problems you've run into with implementing the client using WCF?

**Comment by leonli77** [comment]
Hi mconnew,
>>"_The second WPF application is the client app. All the features used by the article are available on the client side. The example uses no transport security with NetTcpBinding and this is supported with UWP. Are there are any specific problems you've run into with implementing the client using WCF?_"
Yes, there are many problems. For example:
1. When adding a service reference, there is a step ("**Click Advanced to enable asynchronous operations and generic lists.**") in the article. But the "Generate asynchronous operations" option is disabled in UWP. I can't select it.  
2. In the article, there is such code:  
"**InstanceContext context = new InstanceContext(this); 
proxy = new SVC.ChatClient(context);**" 
But there is no corresponding constructor which has a System.ServiceModel.InstanceContext  parameter  in auto-generated code file in UWP.
So I can't  create an uwp client whcih uses duplex communication and TCP binding.

**Comment by mconnew** [comment]
The "Generate asynchronous operations" option is disabled in UWP as we only generate Task based operation methods for windows store apps. This is because UWP apps aren't supposed to ever block the UI thread and all IO calls should be asynchronous. There really is no reason not to use the Task based proxy.  
Duplex communication is supported with the NetTcp binding. The generated proxy client is different for UWP apps and I don't know off hand what the generated code looks like. Here is an alternative method which might work for you.
```csharp
InstanceContext context = new InstanceContext(this); 
var client = new SVC.ChatClient();
var factory = (DuplexChannelFactory<IMyService>)client.ChannelFactory;
var proxy = factory.CreateChannel(context);
```
If that doesn't work, can you provide a copy of the generated ChatClient.

**Comment by leonli77** [comment]
Hi mconnew,
The code doesn't work. The following code is the copy of the generated ChatClient :

    public partial class ChatClient : ChatClientBase {
        
        public ChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new ChatClientCallback(), binding, remoteAddress) {
        }
        
        private ChatClient(ChatClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress) {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<RefreshClientsReceivedEventArgs> RefreshClientsReceived;
        
        public event System.EventHandler<ReceiveReceivedEventArgs> ReceiveReceived;
        
        public event System.EventHandler<ReceiveWhisperReceivedEventArgs> ReceiveWhisperReceived;
        
        public event System.EventHandler<IsWritingCallbackReceivedEventArgs> IsWritingCallbackReceived;
        
        public event System.EventHandler<ReceiverFileReceivedEventArgs> ReceiverFileReceived;
        
        public event System.EventHandler<UserJoinReceivedEventArgs> UserJoinReceived;
        
        public event System.EventHandler<UserLeaveReceivedEventArgs> UserLeaveReceived;
        
        private void OnRefreshClientsReceived(object state) {
            if ((this.RefreshClientsReceived != null)) {
                object[] results = ((object[])(state));
                this.RefreshClientsReceived(this, new RefreshClientsReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnReceiveReceived(object state) {
            if ((this.ReceiveReceived != null)) {
                object[] results = ((object[])(state));
                this.ReceiveReceived(this, new ReceiveReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnReceiveWhisperReceived(object state) {
            if ((this.ReceiveWhisperReceived != null)) {
                object[] results = ((object[])(state));
                this.ReceiveWhisperReceived(this, new ReceiveWhisperReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnIsWritingCallbackReceived(object state) {
            if ((this.IsWritingCallbackReceived != null)) {
                object[] results = ((object[])(state));
                this.IsWritingCallbackReceived(this, new IsWritingCallbackReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnReceiverFileReceived(object state) {
            if ((this.ReceiverFileReceived != null)) {
                object[] results = ((object[])(state));
                this.ReceiverFileReceived(this, new ReceiverFileReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnUserJoinReceived(object state) {
            if ((this.UserJoinReceived != null)) {
                object[] results = ((object[])(state));
                this.UserJoinReceived(this, new UserJoinReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnUserLeaveReceived(object state) {
            if ((this.UserLeaveReceived != null)) {
                object[] results = ((object[])(state));
                this.UserLeaveReceived(this, new UserLeaveReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class ChatClientCallback : object, IChatCallback {
            
            private ChatClient proxy;
            
            public void Initialize(ChatClient proxy) {
                this.proxy = proxy;
            }
            
            public void RefreshClients(System.Collections.Generic.List<AppTestWCF.SVC.Client> clients) {
                this.proxy.OnRefreshClientsReceived(new object[] {
                            clients});
            }
            
            public void Receive(AppTestWCF.SVC.Message msg) {
                this.proxy.OnReceiveReceived(new object[] {
                            msg});
            }
            
            public void ReceiveWhisper(AppTestWCF.SVC.Message msg, AppTestWCF.SVC.Client receiver) {
                this.proxy.OnReceiveWhisperReceived(new object[] {
                            msg,
                            receiver});
            }
            
            public void IsWritingCallback(AppTestWCF.SVC.Client client) {
                this.proxy.OnIsWritingCallbackReceived(new object[] {
                            client});
            }
            
            public void ReceiverFile(AppTestWCF.SVC.FileMessage fileMsg, AppTestWCF.SVC.Client receiver) {
                this.proxy.OnReceiverFileReceived(new object[] {
                            fileMsg,
                            receiver});
            }
            
            public void UserJoin(AppTestWCF.SVC.Client client) {
                this.proxy.OnUserJoinReceived(new object[] {
                            client});
            }
            
            public void UserLeave(AppTestWCF.SVC.Client client) {
                this.proxy.OnUserLeaveReceived(new object[] {
                            client});
            }
        }
    }

**Comment by mconnew** [comment]
I believe you can use the base class ChatClientBase for what you want. That is similar to the class you would have been provided on the full framework using Add Service Reference. E.g.:
```csharp
InstanceContext context = new InstanceContext(this); 
var client = new SVC.ChatClientBase(context);
```
`ChatClient` is a further abstraction from `ChatClientBase` which has event handler on it to handle the callbacks. This way you don't need to provide a callback instance but instead can wire up to the events.

**Comment by mconnew** [comment]
So it just occurred to me, you are using the proxy generated by "Add Connected Service". In a UWP app, "Add Service Reference" is what you should be using and provides classes which look like what you were expecting. The connected services code generator is for .Net Core apps and not UWP and generates slightly different code as you are seeing. How did you generate the client as I believe the connected services plugin for WCF isn't available in a Universal app?

**Comment by leonli77** [comment]
Hi mconnew,
>>"_I believe you can use the base class ChatClientBase for what you want._"
There is also no corresponding constructor for ChatClientBase which has a System.ServiceModel.InstanceContext parameter in auto-generated code file in UWP.  The following is the copy of generated ChatClientBase:

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClientBase : System.ServiceModel.DuplexClientBase<AppTestWCF.SVC.IChat>, AppTestWCF.SVC.IChat {
        
        public ChatClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync(AppTestWCF.SVC.Client client) {
            return base.Channel.ConnectAsync(client);
        }
        
        public System.Threading.Tasks.Task SayAsync(AppTestWCF.SVC.Message msg) {
            return base.Channel.SayAsync(msg);
        }
        
        public System.Threading.Tasks.Task WhisperAsync(AppTestWCF.SVC.Message msg, AppTestWCF.SVC.Client receiver) {
            return base.Channel.WhisperAsync(msg, receiver);
        }
        
        public System.Threading.Tasks.Task IsWritingAsync(AppTestWCF.SVC.Client client) {
            return base.Channel.IsWritingAsync(client);
        }
        
        public System.Threading.Tasks.Task<bool> SendFileAsync(AppTestWCF.SVC.FileMessage fileMsg, AppTestWCF.SVC.Client receiver) {
            return base.Channel.SendFileAsync(fileMsg, receiver);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(AppTestWCF.SVC.Client client) {
            return base.Channel.DisconnectAsync(client);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }

**Comment by leonli77** [comment]
Hi mconnew,
>>"_How did you generate the client as I believe the connected services plugin for WCF isn't available in a Universal app?_"
What does "the connected services plugin for WCF" mean?
I generate the client code according to the article(http://www.codeproject.com/Articles/25261/A-WCF-WPF-Chat-Application#) practices.

**Comment by mconnew** [comment]
@leonli77, were you able to get this working?
