### ISSUE TITLE
Make NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation more robust

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1608]
The test NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation is too restrictive in the timeout it accepts, and in a busy system can take longer than the test allows.  Fix is to increase the acceptable amount of time allowed in the Assert.  Because this test is currently run only manually, it does not appear in lab results, so is not currently high priority to fix.

**Comment by roncain** [comment]
Note: this can be considered low priority.  I observed it manually running this test.  I predict it will be flakey if automated.

**Comment by zhenlan** [comment]
According to @KKhurin and @mconnew, we should explicitly open the channel after [it is created](NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation). Otherwise, the time for opening could affect the actual time taken for timeout.

**Comment by zhenlan** [comment]
@StephenBonikowsky made a fix by #1654
