### ISSUE TITLE
Intermittent CommunicationObjectAbortedException, OperationCanceledException, ObjectDisposedException running NetHttpStreaming on Linux

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1620]
Due to the design of the stress tests some of them are actually expected (and expected to be handled). It is the CommunicationObjectAbortedException that eventually went unhandled and crashed the process. 

This exception is raised when we try to use a channel in Aborted state.
We will experiment more with the tests (see if it happens without the scenarios where we do randomly close the channels and factories while using them) and if it does we'll try to get a good repro for coreFX team.

---
- [ ] Get a simplified repro of an issue that we see in stress - S110

**Comment by zhenlan** [comment]
- [ ] Get a simplified repro of an issue that we see in stress - S109

**Comment by KKhurin** [comment]
We don't see these particular exceptions after moving to post 1.1 master branch. In fact web sockets appear to be pretty stable in both Streaming and DuplexStreaming scenarios (both passed 15+ hours of regular stress and stress with extra frequent channel and factory recycles).
