### ISSUE TITLE
How to consume webservice (asmx) using this tool ?

### ISSUE THREAD

**Issue by udkadam** [dotnet/wcf#1623]
We have requirement of consuming webservice, .NET core/VS 2015 do not have support to add web reference. how can we achieve consuming web services from .NET core Web API project ?

**Comment by zhenlan** [comment]
Hi @udkadam 

The WCF Connected Service should be able to produce .NET Core compatible code for consuming asmx service as well. Please check it out and let us know if you run into any issues.
https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/

**Comment by zhenlan** [comment]
cc: @hongdai @mlacouture

**Comment by soraco** [comment]
How about connecting a .NET Core app to an ASP.NET (ASMX) web service?

**Comment by hongdai** [comment]
@soraco, consuming ASMX is supported. Let us know if it doesn't work for you.

**Comment by soraco** [comment]
Thanks for the response. Would you mind sharing how? 
I created a .NET Core 1.1 Console app, but there does not seem to be a way to add a reference to a web service. If I try to use the web service classes that were generated for a regular .NET client and I add these classes (Reference.cs) to a .NET Core 1.1 app, I get a ton of errors.

**Comment by soraco** [comment]
Nevermind. I did not realize that the "WCF Connected Service" extension also works with ASP.NET web services. All good. thanks.

**Comment by ganesh1984hary** [comment]
I am facing issue while adding asmx service in .NetCore Console application. I am using WCF Connected Service extension as add web reference is not available.  So i followed the same steps which was suggested in following link https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/

After completing all  step it provided auto generated reference class which contain all method as asyn method. My asmx service required username and password authentication for each method and we pass credential as first parameter of any method.

 for example GetData(Credential credential) but auto generated class shows  this method like
GetDataAsync() so i used the below mention code to pass the credentials before calling the my web service method

client.ClientCredentials.UserName.UserName = "myusername";
 client.ClientCredentials.UserName.Password = "mypassword";

Its giving **Not Authorized error**, after putting the breakpoints i found that credential was not getting at asmx service. Please suggest some solution.

**Comment by paonekumar** [comment]
@ganesh1984hary  I am also getting same error, did you find any solution?

**Comment by zhenlan** [comment]
@paonekumar, does this help?
https://blogs.msdn.microsoft.com/webdev/2017/06/28/wcf-web-service-reference-mex-authentication/

**Comment by Ranjoz** [comment]
@zhenlan , i know this may be way late but i cant find the  WCF Connected Service for 2015,any guidelines i have .netcore 1.0 app i need to add some WCF service urgenltly.Thanks in advance

**Comment by zhenlan** [comment]
The early preview of WCF Connected Service is not available to VS 2015 anymore. However, the final release of WCF Connected Service is in-box with VS 2017 v15.5 or later now (including free community edition). It works for .NET Core 1.0 apps.

You can find more details from our [release notes](https://github.com/dotnet/wcf/blob/master/release-notes/WCF-Web-Service-Reference-notes.md).

**Comment by mlacouture** [comment]
@Ranjoz, just in case you are interested, the dotnet-svcutil tool was just released, see issue #2894 for details.

**Comment by Ranjoz** [comment]
@zhenlan thank you will update to vs 2017, for now i used the dotnet-svcutil and was successful thanks to @mlacouture
