### ISSUE TITLE
Support for Legacy Services

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/wcf#1625]
Having errors when importing the following web service: https://ds.hitpromo.net/product

This had always been a pain on .NET previously, but we _could_ for legacy reasons use System.Web.Services and import it as a legacy web reference. This is no longer an option on .NET Core. As far as I know there are no workarounds (http://stackoverflow.com/questions/38309366/net-soap-client-using-array has been on StackOverflow since July with no options other than "don't use .NET Core").

Every _once in awhile_ I'll run across one of these older services (it seems like a specific PHP SOAP framework is the main culprit).

Edit: Found newer services (bleeding edge new for them) from this vendor, but still probably something to eyeball and consider.

---

Failed to generate service reference.

Scaffolding Code ... Error:Error: Cannot import wsdl:portType Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter Error: The datatype 'http://schemas.xmlsoap.org/soap/encoding/:Array' is missing. XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:ProductControllerwsdl']/wsdl:portType[@name='ProductControllerPortType'] Error: Cannot import wsdl:binding Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on. XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='urn:ProductControllerwsdl']/wsdl:portType[@name='ProductControllerPortType'] XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:ProductControllerwsdl']/wsdl:binding[@name='ProductControllerBinding'] Error: Cannot import wsdl:port

Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on. XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='urn:ProductControllerwsdl']/wsdl:binding[@name='ProductControllerBinding'] XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:ProductControllerwsdl']/wsdl:service[@name='ProductControllerService']/wsdl:port[@name='ProductControllerPort'] Error: No endpoints compatible with .Net Core apps were found. An error occurred in the tool.

**Comment by hongdai** [comment]
@StrangeWill  Thanks for your feedback!

System.Web.Services  is not currently supported in .Net Core as you know. There is not a plan to support it in the near future.
