### ISSUE TITLE
WCF client spends about 2600 milliseconds to sending the request message when on Windows Server 2008 R2

### ISSUE THREAD

**Issue by Lcng** [dotnet/wcf#1628]
The following is my client code.

    Binding binding = new BasicHttpBinding();            
    string url = "http:localhost:9999/Service";
    EndpointAddress address = new EndpointAddress(url);
    ChannelFactory<TService> channelFactory = new ChannelFactory<TService>(binding, address);
    TService service = channelFactory.CreateChannel();
    string helloWorld = service.GetHelloWorld();

I call service.GetHelloWorld() on the client, my WCF Server receive this call after about 2600 milliseconds.
Even if I open the channel by calling `((IChannel)service).Open()` manually before I call `service.GetHelloWorld()`, my WCF Server also has to wait about 2600 milliseconds to receive the message from the client.

But, when I move the client to a Windows 10 computer(my developing computer), my WCF server(still running on a remote Windows Server 2008 R2 machine) can receive the message from the client quickly.

Can any one help me? Thank you.

**Comment by Lcng** [comment]
Now I'm using NetTcpBinding instead of BasicBinding, the problem is gone..

**Comment by zhenlan** [comment]
Sorry for taking so long @Lcng. We are looking into this. Just to confirm, by Windows Server R2, you mean Windows Server **2012** R2?

**Comment by Lcng** [comment]
That's all right. My OS is Windows Server 2008 R2. Thank you.

**Comment by mconnew** [comment]
The easiest way to diagnose this is to capture some tracing. Can you run the following command in an administrative command prompt:
```
logman start WCFCORETracing -p "Microsoft-Windows-WebIO" 0xFFFFFFFF 0x5 -bs 64 -nb 120 320 -ets -ct perf -f bincirc -max 500 -o <temp folder>\wcf-winhttp.etl
```
Replace `<temp folder>` with a temporary folder name. Then run your client which is having the delay problems. Afterwards, run the following command:
```
logman stop WCFCORETracing -ets
```
This will capture the url's and headers of any outgoing http request so make sure you don't have anything running which might expose anything secret. This includes any browsers as the cookies used to persist a logged in session can be used to spoof an account. If you want to see what's in the trace, you can use [PerfView](http://www.microsoft.com/en-us/download/details.aspx?id=28567) to open the etl file and use the events view. ETL files can be big, but they compress very well so zip it first.

**Comment by zhenlan** [comment]
I am closing this for now. @Lcng please let us know if you need anything else.
