### ISSUE TITLE
Unsupported bindings

### ISSUE THREAD

**Issue by yexcoffier** [dotnet/wcf#1657]
Hi, there is some unsupported bindings.

ServiceModel.Channels.ReliableSessionBindingElement
ServiceModel.Channels.SymmetricSecurityBindingElement
ServiceModel.Channels.CompositeDuplexBindingElement
ServiceModel.Channels.OneWayBindingElement

Any plan on implementing them ? 
Thank you.

euhics

**Comment by zhenlan** [comment]
@euhics thanks for pointing this out. You are right these bindings are not supported currently. We are enabling bindings by scenarios and these bindings are not in the scenarios we currently support.

**Comment by brandonmartinez** [comment]
Is this still an open issue? Has it been covered by #8 ?

**Comment by raffaeler** [comment]
A customer of mine will never able to migrate clients + services at once to .NET Core.
The only possible path is migrating the clients first to .NET Core, and later one service by one.
The blocker is the use (on the client side) of the WCF bindings of this thread.
