### ISSUE TITLE
Feature request: Support WIF token security

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1659]
Customer ask copied from https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/

"This is a very big deal for my company, as we use WCF services + WIF token security. In practice we’ve discovered that the reliance on WS-Trust and WS-Federation features has restricted the interoperability of our SOAP API’s to only .NET clients and the major Java web frameworks such as Metro and CXF. Having a .NET core option would give us another much needed option for non-Windows clients. I tried the current tool and it is not able to generate client proxies to our endpoints. Please add support for STS token authentication and custom token parameters!"

**Comment by zhenlan** [comment]
This request needs the support of message security, which we don't have a plan to add support in the near future.

**Comment by StephenBonikowsky** [comment]
@mconnew Is this resolved with the WSFederation work we are doing?

**Comment by mconnew** [comment]
The original ask was kind of vague and broad. Technically the work we did in preparation for WSFederation fits what they are asking for but I suspect they would want to whole WSFederation feature in practice.

**Comment by StephenBonikowsky** [comment]
Ok, closing this as we are doing work in the space and will continue to do so with more specific customer asks.
