### ISSUE TITLE
Update the WCF Connected Service extension to support VS2017

### ISSUE THREAD

**Issue by hanssens** [dotnet/wcf#1664]
The Visual Studio WCF Connected Service extension is currently limited to Visual Studio 2015 editions. It would be great if an update could be provided that supports VS2017 (RC) as well.

**Comment by zhenlan** [comment]
Thanks for the feedback @hanssens. This is certainly on our radar. In VS2017, .NET Core is moving to the new [MSBuild based project system](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/), which is still in "alpha" stage. The WCF Connected Service extension has corresponding work to do to support this. I hope we can have something out by the time VS2017 is RTM'ed.

**Comment by softveda** [comment]
Yes please do. In enterprise scenario we have legacy WCF SOAP web services that I want to wrap using APIs. I am trying to convince management on .Net core and this tooling is essential even in VS2017 RC.

**Comment by MattyBoy4444** [comment]
Will this be done soon?  Thanks

**Comment by zhenlan** [comment]
@MattyBoy4444 thanks for querying. As I mentioned earlier, I hope we can have a preview release by the time VS2017 reaches its final release. By then the .NET Core tooling and the MSBuild-based project system hopefully will also reach a relative stable state, which is an important foundation for WCF Connected Service to deliver reasonable quality and functionalities that we are comfortable with.

**Comment by mchender** [comment]
@zhenlan any update on this now that Visual Studio is RTM?

**Comment by mlacouture** [comment]
The WCF Connected Service for 2017 is here: https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService

**Comment by hanssens** [comment]
As far as I'm concerned, this issue is closed for me now that VS2017 is supported and available.

**Comment by knutanderss** [comment]
Marketplace link is dead, and the extension is not showing up in Visual Studio 2017 anymore. Why is this?

**Comment by mlacouture** [comment]
Hi @knutanderss!  The extension is part of Visual Studio 2017 v15.5 and later, for more information visit the [WCF Web Service Reference tool doc](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide).

**Comment by DarkC343** [comment]
Hi, I tried to add this feature through [this link](https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService) and `404 NOT FOUND We could not find the requested page` pops up.
Also, I tried using Extensions and Updates in VS2017 and searched for `WCF Web Service Reference` but nothing were shown up related to what I've searched.
