### ISSUE TITLE
Async unit and scenario tests for DuplexClientBase / DuplexChannelFactory

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#167]
As per title. We have added tests in #161, but we do need to add async tests too.

**Comment by zhenlan** [comment]
@iamjasonp can you please update the progress of this item?

**Comment by zhenlan** [comment]
@iamjasonp can this be done by this milestone?

**Comment by iamjasonp** [comment]
For 2016.01 that's going to be tight especially since I will be on vacation shortly. 

We've constantly reprioritized other work ahead of this particular work item. Wondering if we need some kind of MQ milestone to mop up this type of work.
