### ISSUE TITLE
Define proper try/catch/finally pattern for tests to close communication objects correctly

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#168]
Our tests currently are inconsistent in whether they close channels, factories or ClientBase's.  And those that do close are inconsistent.  At the same time we choose the pattern, we want to decide whether tests are also samples and could be copy&pasted.  If so, the Close pattern should follow our public guidelines.

This issue is to serve as a discussion topic for the right way to handle this and will then be farmed out to a new set of issues to repair the tests.

**Comment by roncain** [comment]
Not required for beta7

**Comment by SajayAntony** [comment]
I believe this has always been the pattern we have recommended. Its not ideal and is not in accordance with the dispose pattern. But for those who use WCF it has always been consistent. 
Try/Catch/Abort - http://blogs.msdn.com/b/drnick/archive/2007/05/04/the-try-catch-abort-pattern.aspx

**Comment by roncain** [comment]
Thanks @SajayAntony .  Now the broader questions for everyone -- is it our intent to make all tests close the channels, channel factories, and ClientBases they open during a test?   And is it our intent that any scenario test could be copy/pasted and used as a sample?  If the answers are "yes" and "yes", then most scenario tests will need to be updated.

My personal opinion is that all tests should explicitly clean-up any resources they acquire.  I'm undecided about how copy/pastable scenario tests should be for samples.

**Comment by StephenBonikowsky** [comment]
I agree with @iamjasonp 's statement elsewhere that we should view our scenario tests as samples, therefore; we should use best practices or established/recommended patterns when writing them.

**Comment by iamjasonp** [comment]
I think the answer is "yes" we want to clean up as best as possible after a test - as a best practice. It's not such a big deal now that we've moved away from a central server for open sourced tests. 

Whether or not a test is going to be copy-and-pastable is debatable, but we've had best practice stating that we don't use `using` in WCF. I think it's best not to confuse the community that it *might* be all right in WCF-CoreFx.

**Comment by roncain** [comment]
Time to get concrete about this proposal.  I propose that every scenario test uses a try/finally pattern, and in the finally it closes all ICommunicationObjects it has acquired following the pattern described at http://blogs.msdn.com/b/drnick/archive/2007/05/04/the-try-catch-abort-pattern.aspx.  That means a Close() in a Try/Catch, and then an Abort if a TimeoutException or CommunicationException occurs.

Given the verbosity, this is one place I think a test helper would enhance readability, something like TestHelpers.CloseCommunicationObject(ICommunicationObject).  It could also check for null.  We would close channels first, then channel factories.  If anyone is going to cut and paste the "right" way to close, let's put it in one place, document it, and then call it from all our scenario finally blocks.

**Comment by StephenBonikowsky** [comment]
We will need a second pattern for negative tests that expect an exception. In that scenario I don't think we can expect to close channels and factories. We should still do aborts in the finally block.

**Comment by iamjasonp** [comment]
Keep in mind that Close() is not exposed on all ICommunication-derived objects in the contract. Do we want to always `Close()` by doing a cast, or `Dispose()` as seems to be what happens in our contracts, or just `Abort()`? 

Btw, if we do `Close()`, it should not appear inside the finally block - this should appear in the try { } block. `Close()` is graceful and can throw. `Abort()` should never throw and is a last-resort thing.

**Comment by roncain** [comment]
I'd prefer a test helper like "public static void CloseCommunicationObjects(params ICommunicationObject[] objects)" that just takes a list of ICommunicationObjects and shuts them down with the recommended pattern (null test, Close() inside a try/catch, followed by Abort() if needed).  I believe this helper should use exactly the recommended pattern, and developers could cut and paste it into production code.

A failure from the Close() should not fail the test unless the test is explicitly testing Close() semantics, so I think the Close() belongs in the test helper, called from the finally block.  The purpose of this helper is tearing down the resources used in the test, not verifying how the teardown behaves.

@StephenBonikowsky is there really a need to special case the negative tests?  You are right that depending on the test the CO may already be faulted, but the test helper would tolerate that.  I'd prefer to have one single pattern that says "here is how you close/abort a communication object **no matter what state it is in**.

**Comment by iamjasonp** [comment]
I don't know if I agree entirely with:

> A failure from the Close() should not fail the test unless the test is explicitly testing Close() semantics... [t]he purpose of this helper is tearing down the resources used in the test, not verifying how the teardown behaves.

We are Windows *Communication* Foundation after all :smile:. Graceful closing of channels is somewhat a given (like graceful opening), and we should almost never have an issue Closing gracefully unless there was a problem somewhere. 

If we get into trouble closing after a series of seemingly normal operations, I believe that in itself could be a problem that might warrant a look. It could be a channel that got caught in a bad state after a specific set of operations (yes... seen it before). 

I agree it's a scope creep in the tests, but this in my mind is acceptable here.

**Comment by roncain** [comment]
Consider in this discussion the possibility of fixing issue #26 first and simply settling on Dispose as the proper pattern.

**Comment by StephenBonikowsky** [comment]
To answer your earlier question, in the context you provided no I don't think it is necessary to special case the negative tests.

**Comment by StephenBonikowsky** [comment]
I opened PR #278 to try and close on this, I scoped it down to positive tests and I think I took into account the various views on the issue.
