### ISSUE TITLE
MessageSecurityException after setting X509CertificateInitiatorClientCredential.ClientCertificate

### ISSUE THREAD

**Issue by chlowell** [dotnet/wcf#1689]
I built a minimal service and client on Windows to learn about certificate authentication. I want the client to  load its certificate from the filesystem and set the `X509CertificateInitiatorClientCredential.ClientCertificate` property:
``` cs
var address = new EndpointAddress("https://localhost:9000/WcfService");
var binding = new BasicHttpsBinding(BasicHttpsSecurityMode.Transport);
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

var factory = new ChannelFactory<IWcfService>(binding, address);
factory.Credentials.ClientCertificate.Certificate = new X509Certificate2(@"C:\temp\ClientCert.cer");
var channel = factory.CreateChannel();
...
```
And here's the service host:
``` cs
using (var host = new ServiceHost(typeof(WcfService)))
{
    var address = new Uri("https://localhost:9000/WcfService");
    var binding = new BasicHttpsBinding(BasicHttpsSecurityMode.Transport);
    binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

    host.AddServiceEndpoint(typeof(IWcfService), binding, address);
    host.Open();
    ...
}  
```
When the client tries to communicate with the host, it throws an exception:  `System.ServiceModel.Security.MessageSecurityException: 'The HTTP request was forbidden with client authentication scheme 'Anonymous'.'`

However, the client works as expected when it retrieves the certificate from the local store:
```
factory.Credentials.ClientCertificate.SetCertificate(StoreLocation.LocalMachine, StoreName.My, X509FindType.FindByThumbprint, clientCertThumbprint);
```

What's the correct way to do this?

**Comment by mconnew** [comment]
An X509Certificate can have either just the public key (this is what you get in a server certificate validation callback) or the public and private key. You need the private key when you are going to use the certificate to authenticate against a third party. CER files only hold the public key. PFX files hold the public and private keys and will generally be either password protected (this is generally what people use) or file system protected. As you aren't providing a password along with the filename to the constructor of X509Certificate and the file has a CER extension, I suspect you only have the public key in that file. You need the PFX file with the private key.
