### ISSUE TITLE
CallbackBehaviorAttribute in parent class is ignored

### ISSUE THREAD

**Issue by farlop** [dotnet/wcf#1706]
_Edit: I'm using .NET Framework 4.6.2 and not .NET Core. So I think this is not the right place to put this issue. Could anyone tell me where?_

Given a WCF service which uses a Callback contract declared like this:
```
[ServiceContract(CallbackContract = typeof(ICommunicationServicesCallback), SessionMode = SessionMode.Required)]
    public interface ICommunicationServices
    { ... }

 public interface ICommunicationServicesCallback
    { ... }
```
And having a first implementation of the callback interface:
```
[CallbackBehavior(ConcurrencyMode = ConcurrencyMode.Multiple)]
    public class ServiceSimpleParser : ICommunicationServicesCallback
    { ... }
```
When using this class `CallbackBehavior` is recognized and `ConcurrencyMode` works as expected (Multiple).

But now, if I create a new class which inherits from `ServiceSimpleParser` like this:

```
class CustomerParser : ServiceSimpleParser
{
}

```
I've found that the `ConcurrencyMode` falls back to default (Single) behavior. I've expected that the attribute was inherit from parent class, as attributes are inherit by default and also because this is stated in MSDN: [Configuring and Extending the Runtime with Behaviors](https://msdn.microsoft.com/en-us/library/ms730137(v=vs.110).aspx):

>  Contract Behaviors
> 
>  For a given contract, all contract behavior attributes on that interface and on parents of that interface, are applied. If the same type of attribute is applied at multiple places in the inheritance hierarchy, the most-derived type is used.

**Comment by StephenBonikowsky** [comment]
Hi @farlop, yeah this GitHub repo is only for .NET Core version of WCF, the team that currently supports WCF in the full framework gets its bugs and other feedback via http://connect.microsoft.com/VisualStudio

**Comment by mconnew** [comment]
Also the CallbackBehaviorAttribute is not a contract behavior (meaning it implements `IContractBehavior`) but is an endpoint behavior (meaning it implements `IEndpointBehavior`). See the documentation for [CallbackBehaviorAttribute](https://msdn.microsoft.com/en-us/library/system.servicemodel.callbackbehaviorattribute(v=vs.110).aspx).

**Comment by zhenlan** [comment]
Closing since this is a desktop issue.
