### ISSUE TITLE
Update tests to skip DataContractResolverTest fail on UWP Runs only with konwn issue 

### ISSUE THREAD

**Issue by willaimyou** [dotnet/wcf#1709]
**adding the following attribute:** 
[Issue(1708, Framework = FrameworkID.NetNative)]
[Issue#1708](https://github.com/dotnet/wcf/issues/1708)

**case code path:**
wcf / src / System.Private.ServiceModel / tests / Scenarios / Contract / Data / DataContractTests.4.1.1.cs 

**Note:** This will skip the test on UWP runs only and give us clean runs until someone has time to investigate the test.

**Comment by StephenBonikowsky** [comment]
@huanwu Could you add the above attribute to the test case so that it gets skipped on UWP runs until you have a chance to investigate the root cause of the failure.

**Comment by zhenlan** [comment]
@huanwu can you please disable the test for now? It's failing in our nightly runs.

**Comment by huanwu** [comment]
This is because the DataContractResolver doesn't work in UWP. https://github.com/dotnet/corefx/issues/14879
