### ISSUE TITLE
Consider dropping the 3.5 Claims Model

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/wcf#1711]
This claim model:
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/IdentityModel/Claims/Claim.cs#L39

Was replaced by (in .Net 4.5):
https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/Claim.cs#L50

Any Core implementation should use System.Security.Claims OM.

**Comment by zhenlan** [comment]
Thanks for the feedback @brentschmaltz. The code we are currently using is consistent with WCF on desktop. It has special logic of handling SOAP. What will be the new value added for WCF user scenarios by switching to S.S.Claims OM?

**Comment by zhenlan** [comment]
Potentially this can be done by Message Inspector to add the support of System.Security.Claims OM. This can be a separate component that does not have to be in WCF core.
