### ISSUE TITLE
Not able add a WCF service reference Using visual studio 2017 RC

### ISSUE THREAD

**Issue by avireddy02** [dotnet/wcf#1725]
Not able add a WCF service reference Using visual studio 2017 RC

**Comment by hongdai** [comment]
@avireddy02  Assume you meant for .Net Core applications, we are currently working on making WCF connected service tool available on visual studio 2017 RC for .Net Core applications.

**Comment by zhenlan** [comment]
Thanks for the feedback @avireddy02. This work is tracked by #1664.

**Comment by RG2712** [comment]
still not able to add WCF reference in VS 2012.  I am using ASP.Net Web Application(.Net Framework) MVC application. My VS version is Enterprise 2017 version 15.4.5

The problem I am facing is while adding the service reference in web project, its not adding endpoints in web.config file. And when am trying to add the service reference in class library project it showing the error:
"url does not have valid endpoints"
I have installed Microsoft WCF Web Service Reference Provider also to get the reference in class library.
Also checked with unchecking the checkbox in advanced section of referencing other assemblies.

Please suggest.

**Comment by HarkinsDave** [comment]
@RG2712 
Open VS2017 
Tools --> Extensions and Updates --> Online 
Search for Microsoft WCF
Download and install Microsoft WCF Web Service Reference Provider
Restart VS2017
Open Solution --> Right Click Project you want to add a service reference to --> Add --> Connected Service
Select Microsoft WCF Web Service Reference Provider
Configure as required.

**Comment by zhenlan** [comment]
This is a very old thread, but in case anyone runs into this thread in the future - "WCF Web Service Reference Provider" tool ships with VS2017 since update v15.5, so it's not necessary to install it through "Tools --> Extensions and Updates" if you have VS2017 v15.5 or later.
