### ISSUE TITLE
Update System.Private.ServiceModel to Use NetStandard2.0 on UWP

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#1729]
System.Private.ServiceModel is building netcore50 assembly for UWP. To use NetStandard2.0 on UWP, it need to build assembly targeting uap101 (or uap101aot). 

This is being blocked by https://github.com/dotnet/corefx/issues/14935.

**Comment by Lxiamail** [comment]
@StephenBonikowsky can you check if the problem has been solved since the blocking corefx issue dotnet/corefx#14935 has been resolved.

**Comment by StephenBonikowsky** [comment]
Our S.P.SM package now includes separate assemblies for netcore50 and uap.

For netcore50 we currently harvest assembly version 4.1.1.1
For UAP it is the latest netstandard version (currently ns2.0)
