### ISSUE TITLE
Test didn't finish elegantly by missing some "task#:done" output after running for the scheduled 15 hours in Stress test

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1732]
Have seen in scenarios below:
Linux: 
2s_HttpStreaming.sh
5s_NetHttpDuplex.sh
7s_NetHttpStreaming.sh
Windows:
CertAuth\3s.NetTcpHello.cmd

The exception seen after test finished 15 hours' run are different for different test scenario...

**Comment by KKhurin** [comment]
#1760 should help us with this.

**Comment by imcarolwang** [comment]
- for test with netHttp binding, #1733 is mainly responsible for this issue.
- with #1760 applied, I have seen test stopped with output "WcfService1.IStreamingService requests timed out: 2" in the CertAuth netTcpStreaming scenario.

**Comment by KKhurin** [comment]
I believe these are all symptoms of lingering outstanding calls that have not been timed promptly. In a way these are similar to #1815 but with different calls being stuck. We'll likely need to update the stress harness and even instrument the product to get to the bottom of these.

**Comment by Lxiamail** [comment]
Closing the bug since a lot of things had changed. Will reactive it if we will see it again.
