### ISSUE TITLE
Error while creating the websocket with "CoreClrClientWebSocketFactory" in Stress test with NetHttp binding on Linux

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1733]
**Scenario** (running on Ubuntu):
5a_NetHttpDuplex.sh (async: true)
7s_NetHttpStreaming.sh (async: false)

Inconsistently repro during test run : 
**Exception**: error while creating the websocket with factory of type "CoreClrClientWebSocketFactory", cannot access a disposed object at System.Net.Sockets.Socket.BeginConnect

**Comment by zhenlan** [comment]
According to @KKhurin, this happens pretty frequently. Next step is to determine if this is fatal or the system can actually recover so we have better understanding of the impact of this issue.

**Comment by Lxiamail** [comment]
Close it for now. Reactive it if we see it again.
