### ISSUE TITLE
Reason behind wcf splitting user names with '@' in them.

### ISSUE THREAD

**Issue by tclev** [dotnet/wcf#1736]
I'm researching an issue we're having when trying to authenticate with a SharePoint site. Browsers and HttpClient all are able to authenticate using NTLM without issue but WCF fails. 

The user name is in the format of "user@somedomain.com". The only thing I can see that's different when capturing the requests using Fiddler is that WCF has a call [here](https://github.com/dotnet/wcf/blob/4ba5c2527bae16587c130f9a5f485f6c5109ee59/src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityUtils.cs#L925) that splits user name on the '@' character. The browsers and HttpClient do not do this split. We are using the desktop framework, but I noticed .net core does the same thing. Could someone explain to me why WCF does this?

**Comment by mconnew** [comment]
The method `FixNetworkCredential` is called when you have specified to use Windows integrated authentication (or Negotiate is another name for it). If you have provided a username in the format user@domain and have specified to use Windows credentials, then the username can unambiguously be interpreted as the username being the part before the @ and authentication domain being the part after the @. When providing a NetworkCredential to various networking classes (such as HttpClient, NegotiateStream etc), it is expected that the username and domain be provided as separate fields to NetworkCredential. If you aren't using Windows integrated authentication, then WCF leaves the credential alone. This expects the server authentication challenge to specify Negotiate as the mechanism. If the server is requesting NTLM, that's not Windows integrated authentication and is specifically NTLM. In this case, user@domain is not a valid NTLM username. If the server is requesting NTLM (which is distinct from Negotiate which does support NTLM), provide the username as DOMAIN\user. I'll give a simple example. If you have the user `bob@contoso.com`, then their active directory username is `bob` and the active directory realm is `contoso.com`. This isn't the same as a windows domain user id. The windows domain user would be user `bob`, and the domain doesn't need to match anything after the @. For example, the windows domain could be `OFFICE`, or it could be `CONTOSO`, or even `ACCOUNTING` and has nothing to do with the active directory domain. When you are communicating with a server which is asking for NTLM credentials, you have only provided `user` as the username, and the domain is `somedomain.com`, which isn't a valid NTLM username/domain pair. You need to provide the windows domain username, e.g. SOMEDOMAIN\user.

**Comment by zhenlan** [comment]
@tclev please let us know if you have any other questions. Closing.
