### ISSUE TITLE
System.ServiceModel.Http 4.3.0 doesn't work with .net framework 4.5.2

### ISSUE THREAD

**Issue by pholly** [dotnet/wcf#1746]
Steps to reproduce:
1. Create a new Asp.net core / .net framework project in Visual Studio 2015, keeping framework version 4.5.2
2. Add "System.ServiceModel.Http" 4.3.0 to project.json

When I upgrade to .net version 4.6.1 my errors go away and I can reference `System.ServiceModel` in my app.

**Comment by zhenlan** [comment]
Hi @pholly the v4.3.0 of all WCF packages including System.ServiceModel.Http supports .NET Standard 1.3. As you can see from [.NET Standard Versions](https://github.com/dotnet/standard/blob/master/docs/versions.md), .NET Standard 1.3 is supported by .NET Framework 4.6 or higher. This is why it works when you can use WCF packages in an ASP.NET Core app targeting .NET Framework 4.6.1 but it does not work when you target 4.5.2.

**Comment by pholly** [comment]
@zhenlan Thanks. Based on https://www.nuget.org/packages/System.ServiceModel.Http/ I thought it supported 4.5 as well.

**Comment by zhenlan** [comment]
@pholly when you target for full .NET Framework, you don't need to reference any of these WCF packages. Under the cover it's system.servicemodel.* DLLs from .NET Framework installed on your machine that are used. It will work when you target for 4.5.2 too.

**Comment by pholly** [comment]
@zhenlan Ahhhh, thanks! No wonder. Closing.
