### ISSUE TITLE
Enable running tests in NET Native environment

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#175]
This task is initially just to investigate feasibility of running the tests inside a NET Native environment.

**Comment by zhenlan** [comment]
CoreFx folks are working enabling package building for each component. This could be solved by that effort.

**Comment by roncain** [comment]
Adding @StephenBonikowsky who is working on the VSO scripts that should make this possible.

**Comment by StephenBonikowsky** [comment]
In Progress

**Comment by StephenBonikowsky** [comment]
Progress Report:
At this point I can successfully build and run 4 of the 5 Contract unit tests (some failures), Http has a build failure because it is missing a reference to S.N.WebHeaderCollection.

Making progress.

**Comment by StephenBonikowsky** [comment]
This is completed.
