### ISSUE TITLE
VS extention not supported on VS17rc

### ISSUE THREAD

**Issue by ArgTang** [dotnet/wcf#1750]
I tried installing this extension on VS17rc, but it wont install
https://marketplace.visualstudio.com/items?itemName=erikcai-MSFT.VisualStudioWCFConnectedService 

 -  -Found installed product - Visual Studio Community 2017 RC
 -  -VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

**Comment by hongdai** [comment]
https://marketplace.visualstudio.com/items?itemName=erikcai-MSFT.VisualStudioWCFConnectedService only applies to VS15. We are currently working on an extension for VS17. Will let you know once it's available.

**Comment by zhenlan** [comment]
@ArgTang, for your information, this work is tracked in #1664. I am closing this issue.
