### ISSUE TITLE
Update service reference?

### ISSUE THREAD

**Issue by trend900** [dotnet/wcf#1753]
Hi team! Hope everyone is doing great back there.

Im using the Visual Studio WCF Connected Service addon in my asp.net core project. the issue that i have is that every time i make any change to my service i need to delete the entire service reference and add it again for it to pick up the changes.

In full .net framework projects there is an option named "Update service reference" that does just that and its so useful.

Can you please consider porting back that functionality to the addon in .net core? 

Thanks for your great work.

**Comment by zhenlan** [comment]
Hi @trend900, thank you and hope you are doing well too!

We are currently prioritizing to bring existing functionality of WCF Connected Service to VS2017 and support the new MSBuild based .NET Core project system first. I will keep this request in the backlog for the consideration in our future planning. Thank you for the feedback!

**Comment by mlacouture** [comment]
@trend900, you can overwrite the service reference by specifying the same namespace, can you try that and provide your feedback?

thanks,

**Comment by gergo123** [comment]
In the meantime, i made a blank web project and than added a new service reference with namespace as it is in the original project. Then copied the content of the Reference.cs from the blank to my actual project where i wanted to update the web service reference. No need for deleting, and removing references from the code base.

**Comment by zhenlan** [comment]
@gergo123, just to make sure it's clear, the workaround @mlacouture suggested does not need you to manually delete the existing reference.cs - all you need is to restart the WCF Connected Services tool and input the same namespace in the bottom box of the first page of the wizard. The tool will overwrite the existing reference.cs.

**Comment by mlacouture** [comment]
I'm pleased to announce that this feature is now available with the [Visual Studio 2017 v15.6 Preview 1.0 ](https://blogs.msdn.microsoft.com/visualstudio/2017/12/07/visual-studio-2017-version-15-6-preview/) release, please give it a try and let us know what you think!  thanks,
