### ISSUE TITLE
E2E scenario for WCF client running in containers

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1757]
As the product codebase stabilizes we are going to move towards various end-to-end scenarios to catch a different kind of fish. This is the first dive for stress to come up with end-to-end container stress.

**Comment by zhenlan** [comment]
Plan
- [ ] .NET Core console app using WCF client for http and net.tcp bindings, cert auth
- [ ] ASP.NET Core app using WCF client (mid-tier scenario) for http and net.tcp bindings and cert auth
- [ ] Instructions of how to setup and run above
