### ISSUE TITLE
WCF Service Reference - ASP.NET Core 1.1 - Microsoft Dynamics NAV 2016

### ISSUE THREAD

**Issue by nicojmb** [dotnet/wcf#1762]
When try to add SOAP Service give me this error:

![image](https://cloud.githubusercontent.com/assets/5610392/22424758/3a74304a-e6f8-11e6-90be-c9eff2e05dae.png)

The web service is a codeunit published in Microsoft Dynamics NAV 2016 (https://msdn.microsoft.com/es-es/library/hh166300(v=nav.90).aspx)

if access from browser get this code:

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:microsoft-dynamics-schemas/codeunit/WebAcciones" targetNamespace="urn:microsoft-dynamics-schemas/codeunit/WebAcciones">
   <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:microsoft-dynamics-schemas/codeunit/WebAcciones" />
   </types>
   <portType name="WebAcciones_Port" />
   <binding name="WebAcciones_Binding" type="tns:WebAcciones_Port">
      <binding xmlns="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http" />
   </binding>
   <service name="WebAcciones">
      <port name="WebAcciones_Port" binding="tns:WebAcciones_Binding">
         <address xmlns="http://schemas.xmlsoap.org/wsdl/soap/" location="http://desarrollo.dynasoft.local:7047/PruebaMigracionEstel2016/WS/Estel%20Ingenieria%20y%20Obras%20S.A./Codeunit/WebAcciones" />
      </port>
   </service>
</definitions>`

**Comment by nicojmb** [comment]
The Dynamics Web service was misconfigured, now work ok without modify .net

**Comment by massimopasquali** [comment]
HI, 
I have solved this problem, and you? Now, my problem is that I don't know how to consume the webservice on NAV. Can you explain me how have you done to authenticate and using the webservices function?
