### ISSUE TITLE
Make Duplex unit tests use BaseAddress or move to scenario tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#178]
The new Duplex unit tests use the Endpoints class which is reserved for scenario tests.  This prevents the adoption of the Bridge which must be running for the new Endpoints implementation to work.

All Duplex unit tests using Endpoints have been marked [ActiveIssue] to prevent their running.

This task is to change to the use of BaseAddress or move the tests that require Endpoints to scenario tests and mark them [OuterLoop]

**Comment by SajayAntony** [comment]
@iamjasonp I'm still not sure what made these tests pass.

**Comment by iamjasonp** [comment]
This was way too confusing. Thanks for fixing, @roncain
