### ISSUE TITLE
Is WCF dead?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/wcf#1784]
Hi,

I know the title is a bit rude, but I know many users are looking for this title so they better get over here and read official stuff rather than fake news.

Anyway I'm reading non-official articles and rumors that [WCF is dead](https://blog.tonysneed.com/2016/01/06/wcf-is-dead-long-live-mvc-6/) Hi, I see you're online, can you please refer to my question on the WCF room?

I'm about to start a new LoB application that will consist of a Xamarin portable cross-plat app and a server providing mostly CRUD operations.
WCF offers a tool-set that's far better and more reliable than ASP.NET Core Web API, like client entity generation.

Is this project alive? Doomed? Is it gonna become super set of Web API or be integrated in it?

**Comment by huangjinshe** [comment]
I was waited `WCF` for support `Xamarin` for years already. I even added a request: [Could you guys let some of the team members go to update WCF of Xamarin.Android and Xamarin.iOS?](https://github.com/dotnet/wcf/issues/1688)

`Windows phone` dead for sure now (even I took so much hope before). But for other mobile platforms..... `WCF` really not take care (or they take care but some people like CEO or CTO maybe think different), and developers maybe already use another framework right now.

For your question, I think you better need to know what feature you want, If you want some simple feature such like pass some `json` and process, I think you will not need to use `WCF`.  `ASP.NET` will do it better with `Json.Net`,  But If you want some advanced feature such like: security, duplex channel...or more, you should understand some feature not support for other platforms right now, if you application only work for `Windows`, you don't need to worry, but if you want to do something for multiple platforms with advanced features and if you want to wait, I think all feature will be come in the future but maybe few years later, So Don't Wait For It.

**Comment by ByronAP** [comment]
It's not dead but I feel as though they are cutting there nose off not supporting netstandard as a server :-(

**Comment by Grauenwolf** [comment]
With .NET Framework being sunsetted, WCF is dead unless we get a server-side implementation for .NET Core.

Don't get me wrong. I think there is a lot of value in client-side WCF all by itself. But no one is going to take the time to learn it if we don't get both sides of the equation.

**Comment by yogyogi** [comment]
**Not dead, but certainly dying.** - I say this because in ASP.NET Core you cannot create WCF projects, and ASP.NET Core is the future. Do you remember how Microsoft stopped XNA game development framework in 2013 without giving any notice. Same can happen to WCF, not now, in 2 years time.

**Comment by SuperJMN** [comment]
It should be dead.

**Comment by StephenBonikowsky** [comment]
A WCF Server side solution has been announced.

https://devblogs.microsoft.com/dotnet/supporting-the-community-with-wf-and-wcf-oss-projects/
https://dotnetfoundation.org/blog/2019/06/07/welcoming-core-wcf-to-the-net-foundation

The repo can be found at https://github.com/CoreWCF/CoreWCF
