### ISSUE TITLE
How to consume credential based webservice (asmx) in Asp.net Core web application?

### ISSUE THREAD

**Issue by ganesh1984hary** [dotnet/wcf#1787]
I am facing issue while adding asmx service in .NetCore Console application. I am using WCF Connected Service extension as add web reference is not available. So,I followed the same steps which was suggested in following link
 https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/

After completing all step it provided auto-generated reference class which contains all method as async method. My asmx service required username and password authentication for each method and we pass credential as first parameter of any method.

for example, using web reference my method looks like GetData(Credential credential) but here auto generated class shows this method like
GetDataAsync() so I used the below mention code to pass the credentials before calling my web service method

client.ClientCredentials.UserName.UserName = "myusername";
client.ClientCredentials.UserName.Password = "mypassword";

It's giving me **Not Authorized error**, after putting the breakpoints I found that credential was not getting at asmx service. 

Please suggest some solution.

**Comment by zhenlan** [comment]
Hi @ganesh1984hary, can you please check out #1812 and let us know if it helps?
