### ISSUE TITLE
Expose several API for svcutil tool

### ISSUE THREAD

**Issue by huanwu** [dotnet/wcf#1793]
New expose the following API, which will be used in svcutil. 
ContractDescription.GetContract (Type contractType)
XmlSerializerOperationBehavior class and GetXmlMappings method
OperationDescription Behaviors Property and its returned type KeyedByTypeCollection

**Comment by zhenlan** [comment]
@huanwu can you please open separate issues for each API and link to this issue? It will be easier to distribute the work. Please also include full API information (namespace etc.) to avoid any ambiguity. Thanks!

**Comment by huanwu** [comment]
#1796 #1797 #1798
