### ISSUE TITLE
Adding a Java SOAP service using Add Connected Service

### ISSUE THREAD

**Issue by shr87** [dotnet/wcf#1794]
Is there a way we could add Java soap service reference in a .net core project?

I tried adding using WCF Connected Service under Add Connected Service option. I get below error.

Error: Cannot obtain metadata from https://address....wsdl
Please check that you have enabled metadata publishing at the specified address.
An error occurred while sending the request. A security error occurred.

I also tried by pointing to the locally saved wsdl and schema files, but it does not work.
Please suggest..

**Comment by zhenlan** [comment]
@shr87 are you able to download the metadata from a browser?

cc: @mlacouture @hongdai

**Comment by mlacouture** [comment]
@shr87, regarding this: _I also tried by pointing to the locally saved wsdl and schema files, but it does not work._, what errors do you get?

**Comment by zhenlan** [comment]
Closing as not much information for further investigation.
