### ISSUE TITLE
Expose XmlSerializerOperationBehavior.GetXmlMappings

### ISSUE THREAD

**Issue by huanwu** [dotnet/wcf#1797]
Need expose XmlSerializerOperationBehavior class and GetXmlMappings method to be used in svcutil

**Comment by zhenlan** [comment]
@huanwu is #1420 what you need?

**Comment by huanwu** [comment]
yes, need expose this class.

**Comment by zhenlan** [comment]
@huanwu I may not ask the question clearly. The API is already added by #1420 (that issue is already closed). Can you please check if what @1420 added is all you need by this issue?

**Comment by zhenlan** [comment]
The XmlSerializerOperationBehavior class is already exposed but not the GetXmlMappings method. @StephenBonikowsky can please you add it?

**Comment by StephenBonikowsky** [comment]
Ok
