### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by AGohel** [dotnet/wcf#1800]
Unable to find Visual Studio WCF Connected Service from Visual Studio 2017. Unable to add service reference using Connected Services in Visual Studio 2017 core project.

**Comment by zhenlan** [comment]
Hi @AGohel you can download and install WCF Connected Service for VS 2017 from VS gallery. Please let us know if you run into any issues.

https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService
