### ISSUE TITLE
Unable to configure service reference that uses windows auth.

### ISSUE THREAD

**Issue by OHjeffhudson** [dotnet/wcf#1801]
Attempting to add an reference to the Exchange webserices that use windows Auth at https://xxxxxx.com/ews/services.asmx.   The Wizard finds zero services.  Fiddler shows that the request receive a 401, unauthorized.  It appears that the wizard is not passing credentials when requested.

Visual Studio 2017 is running as user that has rights to read this data.  I can view the wsdl in Internet Explorer just fine.

**Comment by zhenlan** [comment]
Hi @OHjeffhudson, sorry for running into this and thanks for reporting the issue.

WCF Connected Service does not support service metadata secured by authentication yet. As a workaround, could you please try to download the metadata into a file from a web browser (use  [singleWsdl](http://blogs.microsoft.co.il/idof/2011/09/17/whats-new-in-wcf-45-a-single-wsdl-file/) if you have modular WSDL in multiple files), then restart the WCF Connected Service and enter the full path to the downloaded file in the URI box?

cc: @mlacouture @hongdai

**Comment by zhenlan** [comment]
Hi @OHjeffhudson with latest release of [WCF Connected Service](https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService) we've added support of downloading service metadata secured by Windows authentication (and other auth). @mlacouture also wrote a [blog post](https://blogs.msdn.microsoft.com/webdev/2017/06/28/wcf-web-service-reference-mex-authentication/) explaining how to incorporate authentication with generated client proxy code. Please let us know if this works for you.

**Comment by Shadowman4205** [comment]
@zhenlan sorry for inconvience
Is there any example how connect to wcf service with certificate auth?
Cause at the moment when i try use WCF Web Service Reference Provider, when i add uri and press go
i get 
```
An error occured while attempting to find services at ......url........
The remote server  returned  an error : (500) internal server error
(details)
Metadata contains a reference that cannot be resolved: '....url....'.
```

if i try access this url by browser i get this xml
```
SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode>SOAP-ENV:Client</faultcode>
<faultstring>Unable to parse request</faultstring>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Any suggestion?

**Comment by zhenlan** [comment]
@mlacouture any suggestions for @Shadowman4205?

**Comment by mlacouture** [comment]
@Shadowman4205, internal server error usually means the service failed to process the request, it could be an exception in the service code for instance.  This does not seem to be an authentication problem.  Do you own the service that you can attach a debugger during the request? 
Regarding cert auth, my [blog post](https://blogs.msdn.microsoft.com/webdev/2017/06/28/wcf-web-service-reference-mex-authentication/) explains how to set the certificate.
