### ISSUE TITLE
Not able to generate a service reference using connected service

### ISSUE THREAD

**Issue by RaviTejaKaruturi** [dotnet/wcf#1803]
Hi,

I am trying to generate a soap client in .net core class library project, using connected service(v 0.4.21213.0). 
It throws this error
```
Scaffolding Code ...
Error:Error: Cannot obtain Metadata from https://localhost:44302/myWcfService.svc 
If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.
WS-Metadata Exchange Error
    URI: https://localhost:44302/myWcfService.svc 

Failed to generate service reference.
```
WCF service was built on .NET Framework 4.5.2.  Currently, .net core class library project is also targeting .NET framework v4.5.2.   

I am successfully able to generate a soap client  using "add service reference" in an existing project.
I was looking at https://github.com/dotnet/wcf/issues/1741. I have tried to disable the authentication in WCF service, but then

```
Scaffolding Code ...
Error:Error: Cannot obtain Metadata from https://localhost:44302/myWcfService.svc 
If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.
WS-Metadata Exchange Error
    URI: https://localhost:44302/myWcfService.svc
Metadata contains a reference that cannot be resolved: 'https://localhost:44302/myWcfService.svc'.
One or more errors occurred. (An error occurred while sending the request. A security error occurred)

Failed to generate service reference.
```

I have finally tried to download wsdl file and load the file in the connected service to generate the code

then it throws this error

```
Scaffolding Code ...
Error:Error: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: Schema with target namespace 'http://tempuri.org/' could not be found.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IMyWcfService']
Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IMyWcfService']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='BasicHttpEndpoint']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:service[@name='IMyWcfService']/wsdl:port[@name='BasicHttpEndpoint']
Error: No endpoints compatible with .Net Core apps were found.
 
```
"No endpoints compatible with .Net Core apps were found".  Is this because I am targeting .net core app with 4.5.2?

Thanks

**Comment by mlacouture** [comment]
Hi @RaviTejaKaruturi!  Can you please provide some details about the service you are using? the security error message makes me think the service has some binding elements that are not currently supported in .net core:

_An error occurred while sending the request. A security error occurred_

if you can share somehow the wsdl so we can reproduce it the issue that would be great.

thanks,

**Comment by chris5287** [comment]
I am getting the following error:

```
Scaffolding Code ...
Error:Warning: The following Policy Assertions were not Imported:   XPath://wsdl:definitions[@targetNamespace='http://imaging.oracle/']/wsdl:binding[@name='DocumentContentServicePortBinding']
  Assertions:
    <ns1:OptimizedMimeSerialization xmlns:ns1='http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization'>..</ns1:OptimizedMimeSerialization>
Warning: Unsupported binding element type: 'System.ServiceModel.Channels.UnrecognizedAssertionsBindingElement'.
Warning: Unsupported message encoding element type: 'System.ServiceModel.Channels.MtomMessageEncodingBindingElement'. It must be one of the following types: 'System.ServiceModel.Channels.BinaryMessageEncodingBindingElement', 'System.ServiceModel.Channels.TextMessageEncodingBindingElement.'
Warning: Endpoint 'DocumentContentServicePort' at address 'http://localhost/imaging/ws/DocumentContentService' contains one or more bindings not compatible with .Net Core apps, skipping...
Error: No endpoints compatible with .Net Core apps were found.
Failed to generate service reference.
```
[DocumentContentService.wsdl.txt](https://github.com/dotnet/wcf/files/839161/DocumentContentService.wsdl.txt)
[DocumentContentService.xsd.txt](https://github.com/dotnet/wcf/files/839160/DocumentContentService.xsd.txt)

**Comment by zhenlan** [comment]
@RaviTejaKaruturi please let us know if you have more information. Closing for now.

**Comment by hackfaq** [comment]
same problem, try to generate http://dev-ticketsystem.redkassa.ru/ticketsystemservice/ticketsystemservice.svc

**Comment by mlacouture** [comment]
Hi @hackfaq, 

Thank you for taking the time to report this issue and for providing the URL.  

I downloaded the WSDL from the service (which be the way, is huge) and noticed that there's a custom policy applied to the service that requires a [SecureConversationToken ](http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/ws-securitypolicy-1.2-spec-os.html).  This implies [MessageSecurity](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/message-security-in-wcf) which is not yet supported in .NET Core.

Hope this helps clarify,
Miguel Lacouture
