### ISSUE TITLE
Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'

### ISSUE THREAD

**Issue by bobmclaren** [dotnet/wcf#1807]
With a fresh install of VS 2017, and the WCF Service - Preview tooling installed, when I attempt to add a service reference to a new dotnet core console app, I receive the following error and the scaffolding fails.

> Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'

**Comment by hongdai** [comment]
@bobmclaren Sorry to hear that you are running into the issue.

Could you collect the logs and send it to me? I'll take a look what's going wrong.
1. Find the log directory under %temp%\WCFConnectedService
2.  Zip all the files under the log directory.
3.  Zip dotnet-svcutil package folder under your local package cache, such as %systemdrive%\Users\<loginname>\.nuget\packages if it **exists**.

Thanks,
-Hong

**Comment by hongdai** [comment]
@bobmclaren Could you check if you have a package resource name "local" and it's unchecked from Tools -> Options -> NuGet Package Manager -> Package Sources?

If so, you can workaround the issue by rename local to something else, this is because the WCF connected service tool uses this name. We will fix the issue in the next release.

**Comment by bobmclaren** [comment]
I have confirmed I do not have a package source named "local" configured.  I just emailed you a zip file with the requested log files.  Please note that the dotnet-svcutil package was not found in my local package cache.
Thank you again for your time.

**Comment by bobmclaren** [comment]
Update:
I copied the project to another machine and was able to successfully scaffold a service.  After copying the dotnet-svcutil package from my working machine to my first machine, I am now able to scaffold on both machines.  I still cannot explain why my first machine was unable to resolve the package after multiple attempts, on the same network as my second machine, but all is well that ends well.

Considering that my issue is resolved, and I could not replicate it on another machine, I will go ahead and close this.  Thank you again for your help.
