### ISSUE TITLE
Move Bridge and setupFiles under the System.Private.ServiceModel tests folder

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#181]
Create a tools folder under System.Private.ServiceModel\tests.
Move all the Bridge and setupFiles files under this new folder.
Fix any scripts necessary to use the new locations

**Comment by SajayAntony** [comment]
/cc @dmetzgar 
Also would not merge this move until after some time that the bridge sat in master and we got the native build all ok as well.
