### ISSUE TITLE
Request stuck without exception thrown by WCF but was detected by test code in Stress run

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#1815]
Scenarios:
(windows) CertAuth\2a.HttpStreaming.cmd
(windows) CertAuth\8a.NetTcpStreaming.cmd
(Linux) 2s_HttpStreaming.sh

**Comment by KKhurin** [comment]
According to the latest results the main suspect is a completed task with a thread synchronously waiting for its result and not getting scheduled for some reason. Following up with CLR folks to investigate further.

**Comment by Lxiamail** [comment]
Close it for now. Reactive it if we see it again.
