### ISSUE TITLE
Is using "net.msmq" no longer support from the WCF client in .NET Core?

### ISSUE THREAD

**Issue by robertmiles3** [dotnet/wcf#1816]
We have an app (full framework) currently calling a WCF service of ours via something like this...

    new TestServiceClient("NetMsmqBinding_ITestService", "net.msmq://localhost/private/MsmqService/TestService.svc")

We are porting this full framework app over to core, and was able to successfully add the WCF reference and it builds the models. However, when trying to spin up the client similarly like...

    new TestServiceClient(TestServiceClient.EndpointConfiguration.MetadataExchangeHttpBinding_ITestService, "net.msmq://localhost/private/MsmqService/TestService.svc");

...we get a error of...

    The provided URI scheme 'net.msmq' is invalid; expected 'http'.

I'm thinking it's something simple to get this going, but not sure what I'm missing. Is this still supported?

**Comment by robertmiles3** [comment]
I see now that the new WCF client generator only generated the "MetadataExchangeHttpBinding" binding and not the "NetMsmqBinding". Any reason why?

**Comment by zhenlan** [comment]
Hi @robertmiles3, MSMQ is a Windows specific feature and not available cross platform, so it is not supported in WCF on .NET Core. You can review [this doc](https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v1.1.0.md) for the list of supported features.

**Comment by robertmiles3** [comment]
@zhenlan I have a Core app that is targeting the full framework, yet it looks like MSMQ bindings are still not available (or, at least the binding isn't created with the tool). Is that correct? It does, however, look like there are some MSMQ-related objects in the `System.ServiceModel.Channels` now.

**Comment by zhenlan** [comment]
Hi @robertmiles3, the WCF Connected Service tool (I suppose that is what you are using) targets .NET Core apps, so it only looks the API surface that is available in .NET Core. The code it generated will work when your app targets full framework but the tool won't look the APIs that are only available in full framework. Hope this helps.
