### ISSUE TITLE
Could this be used to replace the OData connected service? 

### ISSUE THREAD

**Issue by philcarbone** [dotnet/wcf#1817]
We are looking at the "Visual Studio WCF Connected Service"
https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService

...and we are currently using the "OData Connected Service" found here: http://odata.github.io/odata.net/#OData-Client-Code-Generation-Tool 

Is the "Visual Studio WCF Connected Service" something that can be used instead of the "OData Connected Service" (for a Web API OData v4 endpoint)?

**Comment by zhenlan** [comment]
Hi @philcarbone, WCF Connected Service is not a replacement for OData Connected Service. Please continue using OData Connected Service for OData or seek further suggestions from OData team.
