### ISSUE TITLE
How can i specify the endpoint address over configuration?

### ISSUE THREAD

**Issue by msgorgo** [dotnet/wcf#1832]
When i add a connected service, the created service proxy contains the endpoint address in the class hard coded. Is there a way to inject the endpoint address through configuration. I'm consuming the proxy in an MVC Core project, so i could put something in appsettings.json.

Thanks,
Georg

**Comment by zhenlan** [comment]
Hi @msgorgo, .NET Core does not support traditional config file which is why all the configuration is done programmatically in the generated proxy file, but you can certainly write code to read values from a json file. It's just that we don't have this support out of box. Hope this helps.
