### ISSUE TITLE
.NET Standard Class Library 1.6.1 + WCF Connected Service

### ISSUE THREAD

**Issue by kaushalparik27** [dotnet/wcf#1841]
When I try to use WCF Connected Service and add ASMX reference in .NET Standard Class Library 1.6.1, that gives me below reference errors: [http://imgh.us/2017-03-31_12-31-05.jpg]
I have dependencies over 1.6.1 that I cannot downgrade. Is WCF Connected support not supporting 1.6.1?

**Comment by hongdai** [comment]
@kaushalparik27 Sorry to hear that you are running into issues. 1.6.1 is supported.

Could you email me the screenshot? I can't view it here for some reasons.

Are you using VS2015 or VS2017?

Thanks,
Hong

**Comment by zhenlan** [comment]
@hongdai you can see the screen shot by navigating to the link [http://imgh.us/2017-03-31_12-31-05.jpg](http://imgh.us/2017-03-31_12-31-05.jpg) that @kaushalparik27 provided.

**Comment by hongdai** [comment]
@kaushalparik27 You were using VS2015 from the screenshot. .Net Core has made project system changes. Could you try your scenario on VS2017?  You can download the WCF connected service tool for VS2017 from https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService.

Let me know if you are still running into issues.

**Comment by kaushalparik27** [comment]
I tried same scenario in VS2017. Working as expected. Thanks @hongdai for suggestion.
