### ISSUE TITLE
SSRS authentication

### ISSUE THREAD

**Issue by popraducj** [dotnet/wcf#1847]
I have attached 3 files one with the wsdl download from my SSRS (named SSRSwsdl) and the class that was generated with the help of the command:
wsdl /language:CS /n:"Microsoft.SqlServer.ReportExecution" http://<Server Name>/reportserver/reportexecution2010.asmx?wsdl /o:"ReportExecution.cs"
The third one is the class generated by the WCF Connection Service named ReferenceCS.txt.

What I want to do is to somehow be able to integrate SSRS and .NET Core. My issues are:
1 I have read some of the posts in here and it's said that WCF does not support authentication and I should get the wsdl file and restart the WCF connected service and insert the file. My question is what's the difference? and can you give some more specific steps on how to do that?
2. If I use the  ReportExecution class that was generate with the help of wsdl.exe after I get some of the libraries that I need, it throws and error because System.Web cannot be found. I've also read that somehow the application life cycle is changed in .NET Core and is not a good practice to get the old one. And I also wasn't able to get the System.Web dll from .NET 4.5 into my project because all the exemples I have found don't look like my project structure.
3. If the WCF service class that was generated is used. I was trying to use the LogonAsync or SetExecutionCredentialsAsync but on bot ends I got the same error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'NTLM'. After some reading I feel like this is thrown because I am not able to set for IISExpress or for the service Authentication type. I have changed to this
iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
} settings for IISExpress from launchSettings.json but with no result.
Technologies used: VS 2017, .NET Core web api application, SSRS 2016, SQL Server 2016 standard 

The credentials are windows credentials.
How can I integrate SSRS with .NET Core web api application?

PS: I'm a bit new to .NET Core and SSRS web services and some concepts I may not get correctly please correct me if I'm wrong.

[ReferenceCS.txt](https://github.com/dotnet/wcf/files/900663/ReferenceCS.txt)
[ReportExecutionCS.txt](https://github.com/dotnet/wcf/files/900642/ReportExecutionCS.txt)
[SSRSwsdl.txt](https://github.com/dotnet/wcf/files/900643/SSRSwsdl.txt)

**Comment by zhenlan** [comment]
@hongdai can you please help @popraducj?

**Comment by popraducj** [comment]
I've saw [this ](https://stackoverflow.com/questions/44036903/using-ssrs-from-an-asp-net-core-site) on stackoverflow  but I could not get over the "The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'NTLM'."

I've saw that the channel that the channel value in the BeforeSendRequest method has a variable named  named LocalAddress and it's value points to anonymous. How can I change that?

**Comment by zhenlan** [comment]
cc: @mlacouture

**Comment by hongdai** [comment]
@popraducj, I will answer/clarify your questions about WCF.
1) WCF runtime support authentication. WCF connected service tool does not support generating authenticated client code. You can work around by adding authentication code to generated client code.
2) This is not WCF related.
3) You will need to enable window authentication in the generated reference.cs code.

**Comment by hongdai** [comment]
@popraducj  We have just updated the tool to support 1). 

For 3), https://blogs.msdn.microsoft.com/webdev/2017/06/28/wcf-web-service-reference-mex-authentication has detailed instructions how to configure the service endpoint to provide the client credential.

Please give the latest tool a try.
Thanks,
Hong Dai

**Comment by marchchad** [comment]
@popraducj What was your final configuration to use Windows Credentials with SSRS via .NET Core?

**Comment by tomek14** [comment]
@marchchad I do this i that way:

In method "static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials)" add this code

`  this.ChannelFactory.Credentials.Windows.ClientCredential = System.Net.CredentialCache.DefaultNetworkCredentials;
            this.ChannelFactory.Credentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Impersonation;`
and in method private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) add this:
` result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Ntlm;
                result.Security.Transport.ProxyCredentialType = System.ServiceModel.HttpProxyCredentialType.None;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;`

After that if you set ApplicationPoolIdentity on IIS correct, evrything ahoud work fine.

**Comment by DonkeyKongJr** [comment]
For me, the following settings worked in a .NET 5 application.

`      var rsBinding = new BasicHttpBinding
            {
                Security =
                {
                    Mode = BasicHttpSecurityMode.TransportCredentialOnly,
                    Transport = {ClientCredentialType = HttpClientCredentialType.Windows}
                },
                MaxBufferPoolSize = 20000000,
                MaxBufferSize = 20000000,
                MaxReceivedMessageSize = 20000000
            };`

**Comment by tomek14** [comment]
If somebody doesn't want to edit generated code you can create partial class in the same namespace with additional constructor like this:
```cs
    public partial class ReportingService2010SoapClient : System.ServiceModel.ClientBase<ReportingService2010Soap>, ReportingService2010Soap
    {
        public ReportingService2010SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress, string userName, string password) 
            : base(GetBindingForEndpointBasicAuth(), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            this.ChannelFactory.Credentials.UserName.UserName = userName;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpointBasicAuth()
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding(System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly);
            result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
    }
```
In this way you can nicely inject username, password and endpoint from appsettings.
