### ISSUE TITLE
Need to generate System.ServiceModel.dll shim

### ISSUE THREAD

**Issue by joperezr** [dotnet/wcf#1848]
cc: @joshfree @weshaggard @ericstj 

UAP Metapackage's closure for netcore50 (uap10.0) includded a System.ServiceModel.dll shim that was restored from the compatibility package. We don't build that package anymore, and in order to be compatible with netcore50 we need to build this shim again for uap10.1's closure. This shim should be built in here, similar to how in corefx we build the shims for the rest of classic assemblies. Once we add that build, we should package it somewhere (perhaps the System.Private.ServiceModel package) so that we can flatten it out in our uap10.1 MetaPackage. 

This will need to be fixed before we ship the new UAP metapackage.

**Comment by zhenlan** [comment]
@joperezr do you mind to help on this issue? We don't have much context where to start. Alternatively, if you can show us pointers how this is done in corefx, @StephenBonikowsky might be able to give it shot.

**Comment by joperezr** [comment]
Sure, if you take a look at this project: https://github.com/dotnet/corefx/blob/master/src/shims/shims.proj that is where we do the same in corefx for mscorlib, System.Core, System.Net, etc. We basically have to do the exact same thing here, just that we want to do it only for System.ServiceModel.dll. Should be pretty straight forward taking the example of corefx, so let me know if you need any help.
