### ISSUE TITLE
wsdl Uri can not contain space for local path  in WCF Connected Service for Visual Studio 2017  

### ISSUE THREAD

**Issue by jiabiao** [dotnet/wcf#1852]
if there is a space in the file path, it's invalid for WCF Connected service Tool:
The service Uri is not valid: 'D:\New folder\ShipService_v19.wsdl'.
And path D:\Newfolder\ShipService_v19.wsdl works well.

![capture](https://cloud.githubusercontent.com/assets/1818225/24945454/2708d75a-1f14-11e7-92b7-0d1ef1287a22.PNG)

**Comment by zhenlan** [comment]
Thanks for reporting the issue @jiabiao. We will look into this.

**Comment by hongdai** [comment]
Fixed checked in.
