### ISSUE TITLE
WCF Web Service Reference: Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1861]
Customer reported issue:

Scaffolding Code ...
Error:Error: Restoring packages for C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\SvcUtilBootstrapper.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
Generating MSBuild file C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.props.
Generating MSBuild file C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\obj\project.assets.json
Restore failed in 3.4 sec for C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\SvcUtilBootstrapper.csproj.

Errors in C:\Users\chpatani\AppData\Local\Temp\WCFConnectedService\2017_Apr_17_17_37_35\svcutil_bootstrap\SvcUtilBootstrapper.csproj
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
By Chintan Patani Tuesday

**Comment by hongdai** [comment]
Hi Chintan,
Thanks for reporting it!

I will investigate the issue. In the mean time, you can workaround it by either of the following ways:
1. Disable Reuse types in reference assemblies, if you don't intend to reuse data contract types. If you are not sure, you can just give it a try.
2. DeCheck Reuse types in all references assemblies, and Check Reuse types in specified referenced assemblies. Then you can select the individual assemblies references to reuse type, and ensure Microsoft.Composition is unchecked.

-Hong

**Comment by hongdai** [comment]
Hi Chintan,
To help investigation, could you send me the content of your csproj file? 

Thanks,
Hong

**Comment by genifycom** [comment]
Here is an example using DotNet Core 1.0 csproj is

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.0.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.1.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.1.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.0.1" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.0.11" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.3" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.5.0" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>

Trying to add a connected service with WCF 5/02/2017 Version 0.5.10428.1201

Gives the following:

Scaffolding Code ...
Error:Error: Restoring packages for C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\SvcUtilBootstrapper.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
  Generating MSBuild file C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\obj\project.assets.json
  Restore failed in 1.98 sec for C:\Users\DAnderson\AppData\Local\Temp\WCFConnectedService\2017_May_04_09_45_48\svcutil_bootstrap\SvcUtilBootstrapper.csproj.

Failed to generate service reference.

**Comment by hongdai** [comment]
To conclude, the root cause is corefx issue dotnet/corefx#9788, the work around is to add the PackageTargetFallback.
