### ISSUE TITLE
ASP.NET Core Support for WS-*

### ISSUE THREAD

**Issue by jmolanofer** [dotnet/wcf#1867]
Within the ASP.NET Core documentation, no reference to the WS-* specifications is found, this is vital to implement SOA correctly.
I would appreciate information regarding the use of these specifications in ASP.NET Core.

**Comment by zhenlan** [comment]
Hi @jmolanofer, if your question is in the context of WCF, WS bindings are currently not supported. #31 has more discussions about this. Please clarify if you mean something else.

**Comment by jmolanofer** [comment]
Hi @zhenlan , thanks for answering. My question is oriented towards ASP.NET Core and whether this technology supports the WS- * specifications for SOA implementations.

I'm not sure your statement about WCF does not support the ws - * specifications ....

MSDN is wrong: (https://msdn.microsoft.com/en-us/library/hh128109.aspx)

"Windows Communication Foundation (WCF) is the .NET Framework technology that is used to create versioned, secure, and reliable service-oriented applications. Applications that use WCF can communicate by using message schemas and choreographies defined in the WS- * specifications. WCF complies with many WS- * specifications. "

**Comment by zhenlan** [comment]
Hi @jmolanofer sorry for the confusion. The MSDN is not wrong, but it is about WCF for .NET Framework. This GitHub repo, however, is about WCF client for .NET Core, which does not support WS bindings. Does this clarify?

For ASP.NET Core specific question, you may like to open issues in ASP.NET Core repo at https://github.com/aspnet/home
