### ISSUE TITLE
Problem while scaffolding Service

### ISSUE THREAD

**Issue by bigjack** [dotnet/wcf#1872]
I'm trying to connect to one public API using WCF Connected Service Reference Provider.
After entering the all needed data I'm clicking "Finish" and while scaffolding I recieve an error.

Scaffolding Code ...
Error:Error: Reference cannot be loaded: "dotnet-aspnet-codegenerator-design"
Could not load file or assembly 'dotnet-aspnet-codegenerator-design, Culture=neutral, PublicKeyToken=null'.

Problem is that I have in my .csproj file all needed dependencies included:
- Microsoft.VisualStudio.Web.CodeGeneration.Design
- Microsoft.VisualStudio.Web.CodeGeneration.Tools

Resolving and mapping this service works in standard .NET ASP MVC app.

I'm doing something wrong or is it really a bug?
Public API: https://webapi.allegro.pl.webapisandbox.pl/service.php

**Comment by hongdai** [comment]
@bigjack Sorry you are running into the issue. It is a bug. We are working on a fix that will be released soon.

As a workaround, you can try deselect Reuse types to generate references.cs. You might not need to Reuse types.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
This is fixed in the latest release on https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService.
