### ISSUE TITLE
What is the suggested way , if we want to use the service url in corresponding further environments (QA/Staging)?

### ISSUE THREAD

**Issue by gsainagendraprasad** [dotnet/wcf#1873]
Lets say i am writing a new dotnet core rest service and it consumes a WCF service-A. As this endpoint is not configurable , how do i make sure to point to corresponding service (environments). When i am in Dev i will point to Dev "service-A" when i going to QA/staging i would expect to point to QA/staging version of "service-A". how do i do this. Is there any suggested way ?

**Comment by zhenlan** [comment]
Hi @gsainagendraprasad will this work for you?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration
