### ISSUE TITLE
EchoComositeType_XmlSerializerFormat_Soap Failed

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#1884]
Test `EchoComositeType_XmlSerializerFormat_Soap` failed due to a bug in serialization. The bug would be fixed by dotnet/corefx#19258. We would need to update the dependencies to take the fix.

**Comment by zhenlan** [comment]
- @StephenBonikowsky will update WCF to use a more recent corefx build that includes dotnet/corefx#19258 today.
- @shmao will verify the scenario and reenable the test case.

**Comment by zhenlan** [comment]
@shmao can you verify the fix?

**Comment by shmao** [comment]
I confirmed that the issue was fixed. I sent out a PR enabling the test.

**Comment by shmao** [comment]
I was wrong. The tests ran on my machine used the private assembly. The test still failed on CI.

**Comment by shmao** [comment]
The latest preview2 build, `2.0.0-preview2-25309-07`, doesn't include dotnet/corefx#19258 .
