### ISSUE TITLE
The latest release 0.5.10428.1201 breaks DotNet Core 1.0

### ISSUE THREAD

**Issue by genifycom** [dotnet/wcf#1889]
The latest release 0.5.10428.1201 breaks DotNet Core 1.0 with:

Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)

So I have to go back to the prior version 0.5.10406.1201 which did work for DotNet Core 1.0.

Please can someone provide a link to this prior version. Everything broken at this point.

Thanks,
Dave

**Comment by genifycom** [comment]
Current workaround is to uncheck Reuse types in references Assemblies.

I still want to point out that this BROKE the DotNet Core 1.0 LTS (Long Term Support) production version of DotNet Core! It is critically important that you test using DotNet Core 1.0

DotNet Core 1.1 is NOT an LTS version and should be considered as suitable for development ONLY.

These are the Microsoft rules not mine.

**Comment by mlacouture** [comment]
Thank you for reporting this issue!

It seems you hit the same issue tracked here: https://github.com/dotnet/corefx/issues/9788. 

This does not seem to be a problem with the tool as the Microsoft.Composition package was not authored to support netcore1.x.  It is interesting that you hit this problem with the updated version of the tool, did you make any other changes to the project? thanks,

**Comment by genifycom** [comment]
Hi thanks for responding.

No changes to the project. Just created a new ASP.NET Core 1.0 project, added the wcf tool and created a connected service.

Would this depend on the connected service?

Thanks,
Dave

**Comment by hongdai** [comment]
This happened with previous tool for 1.1 project for some customers as well, See https://github.com/dotnet/wcf/issues/1861.

**Comment by hongdai** [comment]
@genifycom Have you tried adding the PackageTargetFallback workaround in dotnet/corefx#9788 ?

**Comment by genifycom** [comment]
Thank you for this reference. I will give it a try.

**Comment by zhenlan** [comment]
@genifycom please let us know how it goes. Closing for now.
