### ISSUE TITLE
Ensure all timer callbacks handle exceptions properly

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1903]
As #1694 discovered the code could be vulnerable to unhandled exceptions on timer threads.
This work item is to follow up to see if we have other cases and to handle them properly.

**Comment by KKhurin** [comment]
More testing and moving to S120

**Comment by zhenlan** [comment]
@KKhurin will do a scoped fix first. If more issues are discovered later, will address them separately.

**Comment by zhenlan** [comment]
@KKhurin is reviewing and doing more testing of his scoped fix currently.

**Comment by zhenlan** [comment]
@KKhurin will open new issues as necessary.
