### ISSUE TITLE
remove un-needed target when upgrading to v2 BuildTools 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/wcf#1912]
We have done some change in the PR https://github.com/dotnet/wcf/pull/1911 to change the license Url for packaging. because wcf repo not using v2 of the buildtools we had to hack this by adding the temporary target OverrideLicenseUrl in the dir.targets files. This target should be removed after upgrading to v2 of the buildtools and need to ensure when removing it the license Url in the packages nuspec files is correct

**Comment by StephenBonikowsky** [comment]
Fixed in #1989
