### ISSUE TITLE
support for asmx web service

### ISSUE THREAD

**Issue by sarabu07** [dotnet/wcf#1916]
Im trying to configure http://testapi.marcone.com/b2b/orders_v7.asmx web service thru WCF connected service preview but getting below error message.

Scaffolding Code ...
Error:Error: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: Could not load file or assembly 'System.Runtime.InteropServices.PInvoke, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:portType[@name='Orders_v7Soap']
Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:portType[@name='Orders_v7Soap']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:binding[@name='Orders_v7Soap']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:service[@name='Orders_v7']/wsdl:port[@name='Orders_v7Soap']
Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:portType[@name='Orders_v7Soap']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:binding[@name='Orders_v7Soap12']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://marcone.com/websmart2008']/wsdl:service[@name='Orders_v7']/wsdl:port[@name='Orders_v7Soap12']
Error: No endpoints compatible with .Net Core apps were found.

Failed to generate service reference.

**Comment by zhenlan** [comment]
@sarabu07 thanks for reporting the issue. We tried out your service http://testapi.marcone.com/b2b/orders_v7.asmx with our recent build (not released yet) and it worked without any problems, so this should work in our next update.
