### ISSUE TITLE
Get netcore50 tests running again.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1918]
As part of all the recent changes to get WCF using NetStandard2.0 packages and running on netcoreapp2.0 we are now harvesting a prior released build of netcore50 and no longer building it live. We disabled the netcore50 tests to help reduce noise but now need to try and re-enable them.

**Comment by zhenlan** [comment]
Closing as we will move to v2 Buildtools that will be tracked separately.
