### ISSUE TITLE
Zero number of services found

### ISSUE THREAD

**Issue by fvoncina** [dotnet/wcf#1920]
Hi,
When I try to add a reference to a service the wizard says in the status textbox "Number of services found: 0"

In VS2015 Add Service Reference works fine. Here is the full WSDL:

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" name="GatewayReloadService" targetNamespace="http://tempuri.org/">
<wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
<xs:element name="SendMessageRequest">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" maxOccurs="1" name="InterfaceWrap" type="tns:InterfaceWrap"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="InterfaceWrap">
<xs:sequence>
<xs:element minOccurs="0" maxOccurs="1" name="InterfaceLoad" type="tns:InterfaceLoad"/>
<xs:element minOccurs="0" maxOccurs="1" name="Message" type="tns:Message"/>
<xs:element minOccurs="0" maxOccurs="1" name="Login" type="tns:Login"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="InterfaceLoad">
<xs:sequence>
<xs:element minOccurs="0" maxOccurs="1" name="ChannelIdentifierId" type="xs:string"/>
<xs:element minOccurs="0" maxOccurs="1" name="Version" type="xs:string"/>
<xs:element minOccurs="1" maxOccurs="1" name="Interface" type="xs:int"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="Message">
<xs:sequence>
<xs:element minOccurs="0" maxOccurs="1" name="RequestId" type="xs:string"/>
<xs:element minOccurs="0" maxOccurs="1" name="Transaction" type="xs:string"/>
<xs:element minOccurs="0" maxOccurs="1" name="XML" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="Login">
<xs:sequence>
<xs:element minOccurs="1" maxOccurs="1" name="ComponentInfo" type="tns:ComponentInfo"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="ComponentInfo">
<xs:sequence>
<xs:element minOccurs="0" maxOccurs="1" name="Id" type="xs:string"/>
<xs:element minOccurs="0" maxOccurs="1" name="user" type="xs:string"/>
<xs:element minOccurs="0" maxOccurs="1" name="password" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element name="SendMessageRequestResponse">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" maxOccurs="1" name="SendMessageRequestResult">
<xs:complexType>
<xs:sequence>
<xs:any processContents="lax"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
</wsdl:types>
<wsdl:message name="IGatewayReload_SendMessageRequest_InputMessage">
<wsdl:part name="parameters" element="tns:SendMessageRequest"/>
</wsdl:message>
<wsdl:message name="IGatewayReload_SendMessageRequest_OutputMessage">
<wsdl:part name="parameters" element="tns:SendMessageRequestResponse"/>
</wsdl:message>
<wsdl:portType name="IGatewayReload">
<wsdl:operation name="SendMessageRequest">
<wsdl:input wsaw:Action="http://tempuri.org/IGatewayReload/SendMessageRequest" message="tns:IGatewayReload_SendMessageRequest_InputMessage"/>
<wsdl:output wsaw:Action="http://tempuri.org/IGatewayReload/SendMessageRequestResponse" message="tns:IGatewayReload_SendMessageRequest_OutputMessage"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:service name="GatewayReloadService"/>
</wsdl:definitions>

**Comment by hongdai** [comment]
@fvoncina Sorry to hear that you are running into an issue. 

Do you use VS2017 or VS2015?

**Comment by fvoncina** [comment]
VS2017 thanks

**Comment by fvoncina** [comment]
Is there any workaround to create the client proxy?

**Comment by hongdai** [comment]
@fvoncina The given WSDL is in valid. I couldn't use it even via Add Service Reference. Could you send me the complete wsdl file in email?

Thanks,
Hong Dai

**Comment by zhenlan** [comment]
@fvoncina please let us know when you have an update. Closing for now.
