### ISSUE TITLE
401 unauthorized upon adding connected servce with WCF Service - Preview

### ISSUE THREAD

**Issue by khurz10** [dotnet/wcf#1921]
Hi all,

I got this error while trying to add a connected service using WCF Service - Preview.

Scaffolding Code ...
Error:Error: Cannot obtain Metadata from https://blahblah(confidential).com/webservice 
If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.
WS-Metadata Exchange Error
    URI: https://blahblah(confidential).com/webservice 
Metadata contains a reference that cannot be resolved: 'https://blahblah(confidential).com/webservice '.
One or more errors occurred. (The remote server returned an error: (401) Unauthorized.)

Failed to generate service reference.

I have used the credentials provided to us but it still giving us this error.

Can you please provided solution? I am still new to .Net. :|

Thank you very much.

**Comment by zhenlan** [comment]
@khurz10, sorry for running into this. Will [this](https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService) (quoted below) be a feasible workaround for you?

>Failure to add a reference to a WCF service secured with basic authentication. The WCF Connected Service provider currently does not allow providing user credentials in this scenario. To work around this issue, download the metadata from a web browser into a file  (use [singleWsdl](http://blogs.microsoft.co.il/idof/2011/09/17/whats-new-in-wcf-45-a-single-wsdl-file/) if you have modular WSDL in multiple files), restart the WCF Connected Service and enter the full path to the downloaded file in the URI box.

**Comment by khurz10** [comment]
hi @zhenlan, 

thank you for responding right away. :)
which metadata do I need to download? From the service we are requesting?

**Comment by zhenlan** [comment]
> which metadata do I need to download? From the service we are requesting?

Yes from the service you are requesting, and you may need to use singlewsdl so the url will be something like https://blahblah(confidential).com/webservice?singleWsdl

**Comment by eserozvataf** [comment]
unfortunately SAP webservices doesn't have anything like ?singleWsdl

**Comment by zhenlan** [comment]
@eserozvataf, right 😄, but you need it only if you cannot download all the metadata.

**Comment by zhenlan** [comment]
We are working on the support of authentication by the WCF connected service including basic/digest auth, win auth and cert auth. I am closing this issue as the work is tracked in #1801.
