### ISSUE TITLE
Warning: Transport Security with DetectReplays enabled is not supported.

### ISSUE THREAD

**Issue by JhobanyPena** [dotnet/wcf#1923]
Hi everyone! i'm trying to use this tool with VS2017... but the tool throws this error! :(

![error_wcf](https://cloud.githubusercontent.com/assets/25309407/26016785/25796d66-372c-11e7-88ab-9c1a09f0a524.PNG)

Best regards,

**Comment by hongdai** [comment]
@JhobanyPena Transport security is not supported yet. We are evaluating to support it in the future.

**Comment by hongdai** [comment]
It is not supported by the WCF Runtime.
