### ISSUE TITLE
Peer trust tests failed on OSX because recent corefx change blocks access to TrustedPeople store

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#1925]
Corefx recently(3/1) introduced a change intentionally to block access to TrustedPeople store that the Peer trust tests rely on.

**Comment by karelz** [comment]
@zhenlan Post-ZBB label is/was useful only for issues filed before 5/10.

**Comment by zhenlan** [comment]
Sounds good. Thanks @karelz.

**Comment by karelz** [comment]
BTW: You don't need the label anymore, so I will just delete it entirely.

**Comment by zhenlan** [comment]
TrustedPeople store is not supported on OSX. We will put together some sample code that shows customers how to achieve the similar functionality on OSX.

We will need to update WCF code to throw if peer trust validator is accessed on OSX.

**Comment by zhenlan** [comment]
Fixed by #1951.
