### ISSUE TITLE
Types reuse does not working in .NET Core 1.1 aplication

### ISSUE THREAD

**Issue by kant2002** [dotnet/wcf#1934]
I have assembly `App.Common` where was exists all DTO objects and some of them has been renamed using `[DataMember(Name = "NewName")]`. That assembly referenced by library where I want to add WCF client. But unfortunately instead of using types from `App.Common` new types generated for the client.

That scenario work fine for me in regular .NET application

**Comment by hongdai** [comment]
@kant2002 Sorry to hear that you are running into a issue!

It will speed up the investigation if you can provide a repro app. 

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@kant2002, Since we have not got a repro app, I'm closing this issue for now. Please reopen if you have a repro.
