### ISSUE TITLE
WCF Connected Service extension cannot be used in impersonation scenarios

### ISSUE THREAD

**Issue by Rans4ckeR** [dotnet/wcf#1935]
The extension only generates async methods which do not work reliably when called by WindowsIdentity.RunImpersonated(...).
This results in the dotnet.exe process randomly crashing with an ObjectDisposedException in the eventlog.

See also #654.

**Comment by zhenlan** [comment]
@Rans4ckeR thanks for reporting the issue. Could you please share the full call stack with us? If you call .Result on the async methods, do you have the same issue?

**Comment by Rans4ckeR** [comment]
@zhenlan I did try calling .Result and it reduced the crash occurences significantly, but there was still a 10% fail rate. I ended up modifying the generated methods to synchronous methods.

Although logging is enabled and working for the application, when this error occurs no exception/stacktrace is logged. The process crashes hard and generates the following eventlog entries:

1)
Faulting application name: dotnet.exe, version: 1.1.0.1179, time stamp: 0x5820b092
Faulting module name: System.Private.CoreLib.ni.dll, version: 4.6.25009.3, time stamp: 0x589c8615
Exception code: 0x80131623
Fault offset: 0x00000000005518b6
Faulting process id: 0x828
Faulting application start time: 0x01d2d39ceb4dba4e
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.1\System.Private.CoreLib.ni.dll
Report Id: 46553d6f-3f90-11e7-80d1-0050569a70d0
Faulting package full name: 
Faulting package-relative application ID: 

2)
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: C:\Program Files\dotnet\dotnet.exe
P2: 1.1.0.1179
P3: 5820b092
P4: System.Private.CoreLib
P5: 4.6.25009.3
P6: 589c8615
P7: 172
P8: 1f
P9: System.ObjectDisposedException
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_C__Program Files_c0604eb520bab567f5913914dd411615eb3c1f4e_66e69dae_16293f4b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 46553d6f-3f90-11e7-80d1-0050569a70d0
Report Status: 4100
Hashed bucket:

**Comment by zhenlan** [comment]
Thanks @Rans4ckeR for the information. It's still hard to tell what's going on at the time of crash. 

@mconnew do you have any other ideas? Attach WinDBG to dotnet.exe process?

**Comment by Rans4ckeR** [comment]
@zhenlan can #654 be implemented to give us a workaround?

**Comment by zhenlan** [comment]
@Rans4ckeR currently we suspect this is a runtime issue and #654 won't help (#654 is not something we can enable easily either). Do you think you can reproduce the issue with debugger attached, either WinDBG or VS, so you can get call stack when the crash happens?

**Comment by zhenlan** [comment]
@Rans4ckeR any luck with crash call stack?

**Comment by zhenlan** [comment]
@Rans4ckeR please let me know if you are able to get a call stack upon crashing. Closing for now.
