### ISSUE TITLE
FaultContractAttribute throwing CommunicationException

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#194]
Duplex test: Client.ExpectedExceptionTests.DuplexCallback_Throws_FaultException
MEP is...
Client -> ServiceOperation -> Callback on the client Throws FaultException<T> -> ServiceOperation receives FaultException returns it to client.

This works on Desktop, in our OSS implementation the ServiceOperation gets a CommunicationException instead of a FaultException from the Callback.

**Comment by mconnew** [comment]
Fixed by #216
