### ISSUE TITLE
Ubuntu Help

### ISSUE THREAD

**Issue by H492** [dotnet/wcf#1957]
Does any of this run on Ubuntu 16.04? I'm having a heck of a time solving this net45 issue. Any help is GREATLY appreciated.

Package WCF 1.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package WCF 1.0.0 supports: net45 (.NETFramework,Version=v4.5)
      Package WcfLib 1.0.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package WcfLib 1.0.1 supports: net45 (.NETFramework,Version=v4.5)
      One or more packages are incompatible with .NETCoreApp,Version=v1.1.

**Comment by ctolkien** [comment]
Which package did you install?

**Comment by H492** [comment]
I tried WCF 1.0.0, WCF * WildCard for whatever the latest version might be, WCFLIB 1.0.1 and 1.1.1. I removed each after getting the error message. I think the fact that I'm running .NETCoreApp 1.1 with this 1.1 Framework but the packages I'm retrieving through the Command Palette with the Nuget command, Add Package and typing WCF to see what selections are available to install have so far been built with a Framework setting of 4.5.  This is all under Ubuntu and I don't see a way to install the .NETCore to anything greater than 1.1. I'm thinking the 4.5 requirements is perhaps a Windows build when're that framework version has been readily available. I don't know what the 1.1 .NETCore under Ubuntu is actually compatible with from a Windows versioning perspective. Of course I could be totally off base and I just need to know what I need to change or download to get over this hump. I've got a ton of C# code I've written in Windows that uses WCF and I really want to reuse this under Ubuntu for a special project where I'd prefer to not have to reinvent the wheel :-)

**Comment by zhenlan** [comment]
Hi @H492, if what you want is to use WCF in .NET Core 1.1 (netcoreapp1.1), please use WCF packages listed  in our release notes https://github.com/dotnet/wcf/releases/tag/v1.1.0.

BTW, I did a quick search of [WCFLib](https://www.nuget.org/packages/WcfLib) on nuget.org. It is *not* released from WCF team.

**Comment by H492** [comment]
Hi zhenlan. Thank you for the help. I've built successfully (for some reason, debug only). The next gap in my understanding is how to make these available to my application. Is it through the launch.json file? If so, would you be able to provide the json I need to insert into the file for these 5 libraries? I don't see a way, as in VS under Windows, to simply add a reference to a library (DLL) from the Visual Studio Code v 1.12.2.

**Comment by zhenlan** [comment]
Hi @H492 [here](https://github.com/zhenlan/examples/blob/master/WcfReadOnlyDictionaryExample/NetCoreWcfClient/NetCoreWcfClient.csproj) is an example. Please note I created it to show an issue with serialization so it will fail at runtime but should give you an idea of how to reference S.SM.* packages. I created it with VS2017 but I believe you can also run it with dotnet CLI.
