### ISSUE TITLE
Add support for CallbackBehaviorAttribute

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#1959]
The callback defaults can be very limiting in some cases (for example there is no way to call a service from within a duplex callback).

**Comment by zhenlan** [comment]
The work involved to support this feature is not trivial. We will consider it in the future based on feedback.

**Comment by DevReportOne** [comment]
Hello,

I plan to migrate desktop applications from .net framework to .net core and the fact that CallbackBehavior doesn't own a ConcurrencyMode property blocks me into this migration.

My use case is: several client applications connect to a server windows service with WCF, make asynchronous calls possibly long to the server and in the meantime, the server can make notifications to client applications to know among other things either the progress of a long task or know that another customer blocks items being modified, in order to manage competing access to resources from multiple client applications.

Do you plan to add this property in a future version?

Regards,

**Comment by DanFTRX** [comment]
I am also blocked by the lack of the ConcurrencyMode property for migration of my applications.

**Comment by HengzheLi** [comment]
Upvote

**Comment by HengzheLi** [comment]
Can share any update about this issue? Does "Priority 1" means that it will be impletemented as early as possible?

**Comment by mattg23** [comment]
For anyone looking into this: 
This "hack" works right now for my usecase. But i'm using only very few features of WCF and i'm sure this will break with some of the more advanced features.

```
var factory = new DuplexChannelFactory<IExtendedServiceContract>(new InstanceContext(client), binding, endpoint);

foreach (var behavior in factory.Endpoint.EndpointBehaviors)
{
	if (behavior is CallbackBehaviorAttribute callbackBehavior)
	{
		callbackBehavior.UseSynchronizationContext = false;
		// CallbackBehaviorAttribute is not supported on .NET Core right now
		// we need to set the concurrency mode anyway until https://github.com/dotnet/wcf/issues/1959 is resolved
		callbackBehavior.GetType()
				?.GetField("_concurrencyMode", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)
				?.SetValue(callbackBehavior, 1); // multiple
	}
}

factory.Open();
var channel = factory.CreateChannel();
```

**Comment by HengzheLi** [comment]
> DuplexChannelFactory
Thanks for the advice.
Looks like the "hack" need to dive into the WCF source code and recomplie a homebrew version. Hope there is a simpler workaround.

**Comment by felipepessoto** [comment]
Modifying the backing field may not work as expected. The WCF libraries are probably not tested to support the ConcurrencyMode.Multiple.
@Lxiamail @HongGit is this feature in roadmap?

**Comment by mjrousos** [comment]
@mconnew @Lxiamail Any ideas on this one? I also had a customer asking about `ConcurrencyMode`. Would be good to get an update.

**Comment by CFlatWouldbeMinor** [comment]
I am looking for this as well.
We want to have a .net standard client which connects to an existing server.
There the ClientBase class throws a "Platform not Supported" exception in the constructor
dotnet-svcutil generated..
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    internal partial class InstanceManagerContractClientBase : System.ServiceModel.DuplexClientBase<xxxx>, xxx

public abstract partial class DuplexClientBase<TChannel> : System.ServiceModel.ClientBase<TChannel> where TChannel : class
The clientbase just throws platform not supported ..

If I create the duplexchannel manually the Typeloader throws the exception.

[CallbackBehaviorAttribute(UseSynchronizationContext = false)]
public sealed class MyClass: IMyInterface, Service.IMessagingContractCallback
...

System.ServiceModel.Description.TypeLoader
        internal void AddBehaviorsFromImplementationType(ServiceEndpoint serviceEndpoint, Type implementationType)
        {
            foreach (IEndpointBehavior behaviorAttribute in ServiceReflector.GetCustomAttributes(implementationType, typeof(IEndpointBehavior), false))
            {
                // 
                throw ExceptionHelper.PlatformNotSupported();
            }

**Comment by imsh** [comment]
It would be nice to get this supported

**Comment by imcarolwang** [comment]
> I am looking for this as well.
> We want to have a .net standard client which connects to an existing server.
> There the ClientBase class throws a "Platform not Supported" exception in the constructor
> dotnet-svcutil generated..
> [System.Diagnostics.DebuggerStepThroughAttribute()]
> [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
> internal partial class InstanceManagerContractClientBase : System.ServiceModel.DuplexClientBase, xxx
> 
> public abstract partial class DuplexClientBase : System.ServiceModel.ClientBase where TChannel : class
> The clientbase just throws platform not supported ..
> 
> If I create the duplexchannel manually the Typeloader throws the exception.
> 
> [CallbackBehaviorAttribute(UseSynchronizationContext = false)]
> public sealed class MyClass: IMyInterface, Service.IMessagingContractCallback
> ...
> 
> System.ServiceModel.Description.TypeLoader
> internal void AddBehaviorsFromImplementationType(ServiceEndpoint serviceEndpoint, Type implementationType)
> {
> foreach (IEndpointBehavior behaviorAttribute in ServiceReflector.GetCustomAttributes(implementationType, typeof(IEndpointBehavior), false))
> {
> //
> **throw ExceptionHelper.PlatformNotSupported();**
> }

@HongGit  @mconnew , this is a different issue than a feature support of wcf core, it's an unimplemented feature in dotnet-svcutil tool (throws **PlatformNotSupported** exception), does there exist any potential problem if we insert the IEndpointBehavior object into serviceEndpoint.Behaviors collection when generating the proxy code?

**Comment by mconnew** [comment]
@imcarolwang, that's a different issue that I had missed. There's an earlier comment about ConcurrencyMode not being supported on the attribute. So at least ConcurrencyMode is missing from CallackBehaviorAttribute, and potentially more.  
There shouldn't be an issue with IEndpointBehavior's being added as we support that feature. I don't know what that code is doing though so can't comment beyond that adding a behavior does work.

**Comment by mconnew** [comment]
I had a look at the code and there's the same code in our product code [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs#L609). The correct code that should be there can be found [here](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/Description/TypeLoader.cs#L539). I can't see any problem with including that code. It looks like the same code is needed in dotnet-svcutil as you identified.
