### ISSUE TITLE
Ensure correct package dependencies for System.Private.ServiceModel

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#196]
Following on from #172, it was discovered that System.Private.ServiceModel may be depending on incorrect versions of other Nuget packages, or not depending on the necessary packages at all. 

We have so far identified the following dependencies that need updating to the list of System.Private.ServiceModel dependencies:

````
    "System.Net.Sockets" : "4.0.10-beta-*",
    "System.Reflection.Emit.Lightweight": "4.0.0-beta-*",
````

This is important as people who write against System.ServiceModel.* may need to manually reference the above packages in their own project references - otherwise, there may be a failure when running their own projects.

**Comment by iamjasonp** [comment]
Once fixed, ensure that the `project.json` changes that explicitly add these two package references in our test code in #177 get backed out.

**Comment by iamjasonp** [comment]
#244 needs to be resolved before work can resume here...

**Comment by matsprea** [comment]
I'm trying to use *System.Private.ServiceModel * on .Net 4.6 and I've got this error message from nuget
```
The dependency System.Private.ServiceModel 4.0.0 in project XXX does not support framework .NETFramework,Version=v4.6.
```
Is this error related to this issue or am I just missing somthing?
Thanks

**Comment by iamjasonp** [comment]
Hi @matsprea, 

It looks like you're trying to reference `System.Private.ServiceModel.dll` from a desktop .NET project. If that's true, you should be referencing the desktop `System.ServiceModel.dll` instead.

**Comment by matsprea** [comment]
Hi @iamjasonp, thanks!

I'm tryng to target both *net46* and *dnxcore50* frameworks and I would like to use the `System.ServiceModel.Channels.BufferManager` [Class](https://msdn.microsoft.com/en-us/library/system.servicemodel.channels.buffermanager(v=vs.110).aspx).

For *dnxcore50* referencing  `System.ServiceModel.Primitives` solves the problem, but for *net46* it doesn't, the `BuggerManager` Class is not there.
I tried the `System.Private` following a suggestion from *Microsoft.CodeAnalysis* but I'm still have a problem for *net46*, 

Maybe I'm missing something...

**Comment by iamjasonp** [comment]
@matsprea  - That's really weird. Would you mind sticking a copy of your current project somewhere so we can take a look?

**Comment by matsprea** [comment]
@iamjasonp I create a sample project with the same issue [here] (https://github.com/matsprea/ServiceModel)

**Comment by iamjasonp** [comment]
Hi @matsprea, sorry it took so long to get back to you. I PRed a change into your branch [here] (https://github.com/matsprea/ServiceModel) - see if this works for you

For everyone's benefit, the project.json looks like this: 

```
{
    "version": "1.0.0-*",
    "description": "ServiceModel Class Library",
 
    "dependencies": {
        "Microsoft.Bcl": "1.1.10",
        "System.ServiceModel.Primitives": "4.0.0-beta-23109"
    },

    "frameworks": {
        "net46": {
            "frameworkAssemblies": {
                "mscorlib": "4.0.0",
                "System": "4.0.0",
                "System.Core": "4.0.0",
                "Microsoft.CSharp": "4.0.0",
                "System.ServiceModel": "4.0.0"
            }
        },
        "dnxcore50": {
            "dependencies": {
                "System.Collections": "4.0.0",
                "System.Collections.Concurrent": "4.0.0",
                "System.ComponentModel": "4.0.0",
                "System.Linq": "4.0.0",
                "System.Reflection": "4.0.10",
                "System.Runtime": "4.0.20",
                "System.Runtime.InteropServices": "4.0.10",
                "System.Threading": "4.0.0",
                "System.Threading.Tasks": "4.0.0",
                "System.Private.ServiceModel": "4.0.0-beta-23109"
            }
        }
    }
}
```
