### ISSUE TITLE
IOperationInvoker

### ISSUE THREAD

**Issue by smbecker** [dotnet/wcf#1961]
I see that [IOperationInvoker](https://github.com/dotnet/wcf/blob/v1.1.0/src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/IOperationInvoker.cs) appears to be available in the .NET Core builds but it does not appear to be available to use within the [assemblies](http://packagesearch.azurewebsites.net/?q=IOperationInvoker). Is there any other way to intercept/wrap WCF operations?

**Comment by zhenlan** [comment]
@mconnew what else do you think involved here other than exposing the IOperationInvoker interface in the contract?

**Comment by mconnew** [comment]
@smbecker, there are multiple ways to achieve what you want to do but I can't really answer your question without more info. What is the functionality you need to be able to do in the intercepting? IOperationInvoker is a hard one to expose as we removed the synchronous Invoke which has sizable repercussions in other parts of the code if we were to add that back. If I can't help you use an already exposed extensibility point, we might be able to find an alternative that we can add in to the public contracts more easily.

**Comment by smbecker** [comment]
I am attempting to wrap logging and metrics capture around requests and responses. I previously did that with this interface but I think that I may be able to get what I need through a message inspector.

**Comment by mconnew** [comment]
@smbecker, were you able to get all the information you need for logging from the MessageInspector?

**Comment by smbecker** [comment]
I was. This issue can be closed if this interface is too hard to expose
