### ISSUE TITLE
Unable to scaffold a service in netcoreapp1.1

### ISSUE THREAD

**Issue by xumix** [dotnet/wcf#1963]
Scaffolding Code ...
Error:Error: Restoring packages for C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\SvcUtilBootstrapper.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
  Generating MSBuild file C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\obj\project.assets.json
  Restore failed in 2,71 sec for C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\SvcUtilBootstrapper.csproj.
  
  Errors in C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\SvcUtilBootstrapper.csproj
      Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      One or more packages are incompatible with .NETCoreApp,Version=v1.1.
  
  NuGet Config files used:
      C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_05_15_10_34\svcutil_bootstrap\NuGet.Config
      C:\Users\tambovtsev\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
  
  Feeds used:
      C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\MICROSOFT\WCF METADATA CONNECTED SERVICE V0.5\svcutil
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
An error occurred while bootstrapping svcutil. This usually happens when processing references.  You might be able to work around this problem by not providing reference parameters, and manually removing any types redefined in the generated proxy code.

Failed to generate service reference.

**Comment by hongdai** [comment]
@xumix This is caused by dotnet/corefx#9788. Could you please try adding the PackageTargetFallback workaround in dotnet/corefx#9788 ?

**Comment by xumix** [comment]
@hongdai 
```
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
  <PackageTargetFallback>
    $(PackageTargetFallback);portable-net45+win8+wp8+wpa81;
  </PackageTargetFallback>
</PropertyGroup>
```
Still have this:

```
Scaffolding Code ...
Error:Error: Restoring packages for C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\SvcUtilBootstrapper.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
  Generating MSBuild file C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\obj\project.assets.json
  Restore failed in 2,61 sec for C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\SvcUtilBootstrapper.csproj.
  
  Errors in C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\SvcUtilBootstrapper.csproj
      Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      One or more packages are incompatible with .NETCoreApp,Version=v1.1.
  
  NuGet Config files used:
      C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_09_12_29_10\svcutil_bootstrap\NuGet.Config
      C:\Users\tambovtsev\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
  
  Feeds used:
      C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\MICROSOFT\WCF METADATA CONNECTED SERVICE V0.5\svcutil
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
An error occurred while bootstrapping svcutil. This usually happens when processing references.  You might be able to work around this problem by not providing reference parameters, and manually removing any types redefined in the generated proxy code.

Failed to generate service reference.
```

**Comment by hongdai** [comment]
Could you try the packageTargetFallback from the default template?
<PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81</PackageTargetFallback>

**Comment by xumix** [comment]
@hongdai Same here:
```
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81</PackageTargetFallback>
  </PropertyGroup>
```


```
Scaffolding Code ...
Error:Error: Restoring packages for C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\SvcUtilBootstrapper.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
  Generating MSBuild file C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\obj\SvcUtilBootstrapper.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\obj\project.assets.json
  Restore failed in 3,4 sec for C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\SvcUtilBootstrapper.csproj.
  
  Errors in C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\SvcUtilBootstrapper.csproj
      Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      One or more packages are incompatible with .NETCoreApp,Version=v1.1.
  
  NuGet Config files used:
      C:\Users\tambovtsev\AppData\Local\Temp\WCFConnectedService\2017_Jun_13_11_24_33\svcutil_bootstrap\NuGet.Config
      C:\Users\tambovtsev\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
  
  Feeds used:
      C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\MICROSOFT\WCF METADATA CONNECTED SERVICE V0.5\svcutil
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
An error occurred while bootstrapping svcutil. This usually happens when processing references.  You might be able to work around this problem by not providing reference parameters, and manually removing any types redefined in the generated proxy code.

Failed to generate service reference.
```

**Comment by hongdai** [comment]
@xumix  Another workaround you can try is:
1) Create a .Netcore console application.
2) Set target framework to 1.1.
3) Use the WCF connected service to generate the client(reference.cs).
4) Copy the reference.cs to your Asp.Net Core app.
5) Add the following package references to your Asp.Net Core app.
 <PackageReference Include="System.ServiceModel.Duplex" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
