### ISSUE TITLE
Datacontract Serializer should be default

### ISSUE THREAD

**Issue by NickDinges** [dotnet/wcf#1969]
currently XMLSeriazlizer is used and really, really slow on large WSDLs when creating the channel.

**Comment by zhenlan** [comment]
Hi @NickDinges, WCF does use DataContractSerializer by default.

However, there are cases a service may choose to use XmlSerializer for one reason or another. You can find more details of when XmlSerializer might be used from [here](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/using-the-xmlserializer-class). If you have control of your service and can change it to use DCS, it might help your case.

FYI, we are also looking to port pre-generated XmlSerializer tool to .NET Core (#1345) that will be helpful for large WSDLs using XmlSerializer, this work is still in progress though.
