### ISSUE TITLE
Bridge should close gracefully after configurable max idle time

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#198]
We should define a new TestProperty (BridgeMaxIdleTimeSeconds?) that defines how long the Bridge will stay alive after it has received a request.  No requests for that amount of time mean the Bridge should close gracefully.  The special value of 0 should mean it never times out.

Once #185 is resolved, this property will flow naturally to the Bridge during configuration.  So this task involves defining the property and then using that property in Bridge.exe.

**Comment by SajayAntony** [comment]
Given that bridge times out in 10 minutes if there are no put/get requests. I think all that is pending is to pass in this timeout values.

**Comment by roncain** [comment]
I'm working on passing in the name/value pairs now and can add this to TestProperties to pass to the config POST.
