### ISSUE TITLE
Create test for streamed mode

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#199]
Issue #37 requires a scenario test to verify the fix.  This will require creating a new endpoint that sets the TransferMode to streamed, meaning the Bridge code will need a new endpoint, and the Endpoints.cs class will need to expose it

**Comment by SajayAntony** [comment]
@shmao  @dmetzgar need readme to add a new endpoint.

**Comment by shmao** [comment]
Fixed with #209.
