### ISSUE TITLE
Consider changes to server startup in the build script

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#20]
Some suggestions for making the self-hosted server setup script more useful: 

* Debuggability/logging - pause after error or redirect all console output from commands like *netsh* and *certutil* 
* When *buildwcftestservice.cmd* is called, prevent two elevations
* Allow ability to prevent a server from starting up/getting killed (e.g., if someone spun up their own server for debugging purposes)

**Comment by roncain** [comment]
These features should be considered when solving https://github.com/dotnet/wcf/issues/43 rather than continuing to evolve buildwcftestservice.cmd.

**Comment by iamjasonp** [comment]
Sounds good. I'll close this issue then and we'll continue following on this issue in #43.
