### ISSUE TITLE
Clean up SUPPORTS_WINDOWSIDENTITY in S.P.SM.csproj

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#2006]
We should remove section below in [S.P.SM.csproj](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj)
```
  <PropertyGroup Condition="'$(TargetGroup)' != 'netcore50' AND '$(TargetsWindows)' == 'true'">
    <DefineConstants>$(DefineConstants);SUPPORTS_WINDOWSIDENTITY</DefineConstants>
  </PropertyGroup>
```

SUPPORTS_WINDOWSIDENTITY should be true for both Windows and Linux except UWP. We already have it defined correctly in another section in the same file, but above section is causing confusion.

cc: @mconnew

**Comment by shmao** [comment]
This was fixed by https://github.com/dotnet/wcf/pull/2043.
