### ISSUE TITLE
The service at the following URI does not have any endpoints compatible with .Net Core apps

### ISSUE THREAD

**Issue by mathysd** [dotnet/wcf#2016]
With the update of version 0.5.10620.673 I am no longer able to add services from a wsdl file that did import fine on the previous version. Any suggestions? Can I download an older version?

**Comment by zhenlan** [comment]
@mathysd sorry for running into this issue. Is it the same wsdl file that was used before? Is the wsdl file downloaded by using "?singleWsdl" parameter in URL?

I just tried a very simple service. It worked fine if the wsdl file was downloaded using "?singleWsdl" but I got the same error if the wsdl file is downloaded using "?wsdl". @hongdai, is this expected?

cc: @mlacouture

**Comment by mathysd** [comment]
I have used this file before. I have this file locally so I use browse to select the file.

**Comment by mlacouture** [comment]
Hi @mathysd, can you try specifying the wsdl directory with a wildcard? something like c:\path_to_wsdl\*.*

We changed the way wsdl files are processed and I think this is why your scenario no longer works, let me explain:

In the past, you could have multiple metadata documents (.xml, .xsd) in the same folder as the .wsdl document and you would only need to specify the full path to the .wsdl file, the tool would load all files in the same folder as the .wsdl file.  This assumption however is not always true, you can have metadata documents for different services in the same folder.

The new behavior is safer but requires specifying all the metadata documents; in the case all documents are in the same folder as the .wsdl document and all of them refer to the same service, you can use wildcards.

Currently the UI does not allow to select multiple documents and this needs to be fixed, but you can specify wildcards and it should work as before.

hope this helps,

**Comment by mathysd** [comment]
@mlacouture thank you, with the wildcard it works!

**Comment by mlacouture** [comment]
Hi @mathysd 
This is to let you know that we have made several improvements to the tool around WSDL processing, now you can browse to a wsdl file that has schema references and these will be resolved by the tool.  [The WCF Web Service Reference is not part of Visual Studio 2017 15.5](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes?ref=stackshare#WCFTools).

**Comment by mathysd** [comment]
Thanks I will have a look
