### ISSUE TITLE
[uapaot] Method 'InvalidEnumArgumentException..ctor' was not included in compilation

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#2019]
Ran tests with command `.\build.cmd -framework:uapaot -tests -outerloop`. Many tests failed due to errors like the one shown below,

> System.MissingMethodException : Method 'InvalidEnumArgumentException..ctor(string, int, Type)' was not included in compilation, but was referenced in WebSocketTransportUsageHelper.Validate(WebSocketTransportUsage). There may have been a missing assembly.

**Comment by shmao** [comment]
The issue may be related to https://github.com/dotnet/wcf/pull/2011. 

/cc: @dagood

**Comment by dagood** [comment]
Yes, I think I noticed this go away when CoreFX runtime assemblies are copied from the private package into the ILCInputFolder. (I'm working through Jose's list of corrections.)

**Comment by shmao** [comment]
@dagood sounds good. Thanks!
