### ISSUE TITLE
Should ClientBase<T> be exposed to implement IDisposable in contract

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#2022]
Here is a feedback from a customer using WCF connected service

> I noticed that connection management has changed slightly. The codegen’d webclient objects don’t implement IDisposable. We can always wrap the client object to provide this capability, but it’d be super convenient if the codegen did this for us.

It looks like `ClientBase<T>` does not implement `IDisposable` in [contract](https://github.com/dotnet/wcf/blob/release/2.0.0/src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs#L110) but its [implementation](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/ClientBase.cs#L16) does have `IDisposable`. Would like to see if there is any particular reason for this.

**Comment by zhenlan** [comment]
We will update `ClientBase<T>` to implement `IDisposable` in contract.

**Comment by christopherseeley** [comment]
Has this been released yet? Using System.ServiceModel.Primitives version 4.1.1 and ClientBase<T> doesn't implement IDisposable
