### ISSUE TITLE
Add two CI legs for uap and uapaot.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2026]
From #2021...

Other than the suggestion by @shmao of making sure that this doesn't break uap testing, this LGTM. After this is in, I would create two CI legs that build both verticals (uap, and uapaot) to make sure this doesn't get broken. You should now be able to run uap tests as part of that CI (currently we support x64, x86 and arm archs), but uapaot we don't support running the tests as part of CI yet.

**Comment by StephenBonikowsky** [comment]
After adding a job in netci.groovy for uap scenario tests got the following error...
```
17:00:31   Got manifest file appxmanifest.xml
17:00:31   
17:00:31   FAILED 0x80080204 (The Appx package's manifest is invalid.
17:00:31   
17:00:31   )
```
Disabling the job with PR #2182 until it can be investigated.

**Comment by StephenBonikowsky** [comment]
This has been on hold for a while due to higher priority issues.

**Comment by Lxiamail** [comment]
Not going to make change to Jenkins anymore since we will move away from it. Will consider this request when moving to VSTS.
