### ISSUE TITLE
(dotnet-svcutil) Generation of EndpointConfiguration enum with invalid member names

### ISSUE THREAD

**Issue by marlon-tucker** [dotnet/wcf#2031]
Hello,

I've just used the visual studio 2017 connected service plugin to generate some wcf client code. It all appeared to go smoothly apart from the EndpointConfiguration enum definitions.

The service I pointed it to appears to have been namespaced, therefore contained full stops.

This caused the enum to be generated as such:

```
        public enum EndpointConfiguration
        {
            
            Company.Something.SomethingElse,
        }

```

Wasn't really any trouble to manually fix it, but just something for the radar. 

dotnet-svcutil version 0.5.0.0

**Comment by zhenlan** [comment]
@marlon-tucker thanks for letting us know!

@hongdai can you see if you can repo the issue?

**Comment by marlon-tucker** [comment]
I'm afraid it is unlikely I can give out the wsdl as it's company property. 

But briefly scanning through it, the Enum member names appear to match the wsdl:binding elements, which in our case contain full stops, e.g. 

```
<wsdl:binding name="CompanyName.DiscoveryService" type="tns:IDiscoveryService">
	...
	...
	...
</wsdl:binding>
```

Sorry, that's the best I can do, I hope that's enough.

**Comment by hongdai** [comment]
@marlon-tucker I tried something similar and was unable to repro it. 

What version of the WCF connected service tool you are using? Is it the latest one?

**Comment by marlon-tucker** [comment]
It was installed on Tuesday, and the generated comments state the dotnet-svcutil is at version 0.5.0.0.

**Comment by hongdai** [comment]
@marlon-tucker Since we are unable to repro locally, I'm going to close this issue. Please reopen it if you find another repro wsdl that you are able to share with us.
