### ISSUE TITLE
SocketConnection.Write Throw Different Exception on uapaot

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#2035]
See https://github.com/dotnet/wcf/pull/2033.

`System.ServiceModel.Channels.SocketConnection.Write` calls different methods on different platforms: 
On NetCore it calls `CoreClrSocketConnection.WriteCore`; 
On uap/uapaot, it calls `RTSocketConnection.WriteCore`. 

The two `WriteCore` use different networking APIs. As the networking APIs throw different exceptions, we get different exceptions in error cases. Do we want to consider to make the exceptions consistent across platforms?

**Comment by zhenlan** [comment]
> Do we want to consider to make the exceptions consistent across platforms?

@KKhurin @mconnew what's your thoughts about this?

**Comment by KKhurin** [comment]
Having platform independent exceptions is one of WCF goals... 
This looks like a challenging task though and [System.ServiceModel.Channels.RTSocketConnection.WriteCore](https://github.com/dotnet/wcf/blob/a2c95ad9e5cb2fff465655ae234454cf6f1c0f83/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RTSocketConnection.cs#L405) already tries to do so but doesn't cover this particular case: IOException produced by (https://github.com/dotnet/corefx/blob/master/src/System.Runtime.WindowsRuntime/src/System/IO/StreamOperationAsyncResult.CoreRT.cs#L14).
