### ISSUE TITLE
When importing some WSDLs, not all proxy classes are created in .net core 1.1 / VS2017 Community

### ISSUE THREAD

**Issue by Adrian10988** [dotnet/wcf#2038]
As an example, I have imported a WSDL from a salesforce enterprise account and am missing certain classes and properties. For example: `SessionHeader` class is missing, which is required by the salesforce api. Interestingly enough, if I open my older VS2015 targeting .Net 4.5 and add the same wsdl, I get the required classes and properties. I have attached the problematic wsdl file so you can see the issue. 
[salesforce_wsdl.docx](https://github.com/dotnet/wcf/files/1126362/salesforce_wsdl.docx)

**Comment by zhenlan** [comment]
I am wondering if this is because .NET Core has smaller API surface than .NET 4.5 so the client proxy was not generated for all the endpoints service has. @hongdai could you please take a look?

**Comment by leilasoriano** [comment]
Same problem here. The references.cs has the "Authentication" class, however, not as a attribute to the ServiceClient, and I need that to pass the token authentication. Using .net framework I get what I need, the attribute of type authentication. What I have to to? I need to use this service in a .NET Core project, there's no other way. Please, help me! :(

**Comment by hongdai** [comment]
@leilasoriano  token authentication is not supported yet in WCF runtime and we depend on WCF runtime.

**Comment by leilasoriano** [comment]
@hongdai what can I do to work it around?

**Comment by hongdai** [comment]
@leilasoriano Sorry that I don't think there is a workaround.

**Comment by Adrian10988** [comment]
@leilasoriano this is an initial thought, and I'm not 100% sure it will work. I will test later; however, perhaps add a new project to your solution under .net 4.5-4.6, import the wsdl into there and then reference your proxy classes from your .netcore projects via the .net 4.5-4.6 project

**Comment by hongdai** [comment]
@Adrian10988 Unfortunately it most likely will not work as .netcore WCF runtime does not support it - A runtime error will occur.

For your scenario, it's most likely by some features we do not support yet. I'll need to investigate and figure what are the features.

**Comment by hongdai** [comment]
@Adrian10988 In your scenario, it's the MessageHeader isn't enabled. It looks like WCF runtime has enabled the support. Your workaround to generate reference.cs in the .net 4.5-4.6 project, then copy the generated reference.cs to your .net core projects could work for you. 

We will consider to enable this feature in the tool.

**Comment by hongdai** [comment]
@mlacouture

**Comment by leilasoriano** [comment]
@Adrian10988 I tried that, but didn't work. So sad. =(

**Comment by hongdai** [comment]
@Adrian10988 We have enabled MessageHeader in the latest release.
