### ISSUE TITLE
Clean up code for NETStandard13

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#2050]
Now that we build live code only for NS2.0 and harvest NS1.3 binary from released package, we can clean up all code under `#if NETStandard13`.

**Comment by PatrykOlejniczak** [comment]
Hello,

I will take this one

Regards

**Comment by zhenlan** [comment]
Sure. Thanks @PatrykOlejniczak.

**Comment by zhenlan** [comment]
Resolved by @PatrykOlejniczak via #2886.
