### ISSUE TITLE
Using extension does not generate List

### ISSUE THREAD

**Issue by tibmeister** [dotnet/wcf#2073]
I'm consuming a WSDL and there are specification for collections in the request XML.  When using the extension to ingest I am telling it to use Lists for collections, but I always end up with arrays.

**Comment by hongdai** [comment]
@tibmeister Thanks for reporting the issue! 
Is it possible to provide the WSDL so that we can do a local repro?

-Hong Dai

**Comment by hongdai** [comment]
Update: I can repro the issue, both on full framework ASR and the WCF connected service extension.

**Comment by tibmeister** [comment]
Sorry about the delay's, been a little hectic.  I've attached the WSDL, it's a very large one to say the least.
The RetrieveDeereIncidentListRequest class is a good example.
[SM.wsdl.zip](https://github.com/dotnet/wcf/files/1163320/SM.wsdl.zip)

**Comment by hongdai** [comment]
@tibmeister Thanks for the repro! We will triage the issue.

**Comment by mlacouture** [comment]
@tibmeister, thanks again for reporting this issue and providing the wsdl file.  Unfortunately, the wsdl have a reference that cannot be resolved, I get the following error when using the attached SM.wsld file:
`There was an error downloading 'http://lsde90sm3.sdde.deere.com:14088/SM/7/Common.xsd'
  The remote name could not be resolved: 'lsde90sm3.sdde.deere.com`.

would it be possible for you to provide a full wsdl file? if it is a WCF service, you can use the ?singlewsdl when downloading the metadata file.

thank you!

**Comment by dasetser** [comment]
@tibmeister It looks like this is happening because the WSDL you're using is not supported by DataContractSerializer, XmlSerializer is used instead. Unfortunately, the ability to specify the collection type is a DataContractSerlializer feature and isn't supported by XmlSerializer, so this is a by design limitation in the tool.
