### ISSUE TITLE
Microsoft WCF Web Service Reference Provider HRESULT:0x80131500

### ISSUE THREAD

**Issue by Elprogrammador** [dotnet/wcf#2077]
I'm getting the following error when I try to add a new Connected Service:

"Connected Services. The Connected Services component 'Microsoft WCF Web Service Reference Provider - Preview' failed: (HRESULT:0x80131500) One or more errors occurred"

**Comment by ali61n60** [comment]
I get the same error too

**Comment by chaseWillden** [comment]
I'm getting the same error, please fix

**Comment by macho0001** [comment]
Same here

**Comment by Cyrus-Sushiant** [comment]
I get the same error

**Comment by zhenlan** [comment]
Thanks for reporting the issue.

Duplicate of #2076
