### ISSUE TITLE
Discuss use of EnableDumpling in VSTS build pipeline.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2082]
The property "EnableDumpling" is used by the CoreFx pipeline in VSTS, is it needed for WCF?
Discuss with @MattGal and @dagood

**Comment by MattGal** [comment]
Dumpling is a service that uploads crash dumps to a service for later analysis.  If you're interested in it we can try it but it's a bit challenging to get running.

@DrewScoggins may be able to point to information.   All this setting does is turn on the commands to enable dumpling in the test execution scripts.

**Comment by StephenBonikowsky** [comment]
That's really interesting, I don't think its something we need initially but its really good to know that its there.
