### ISSUE TITLE
proxy.ClientCredentials.ClientCertificate.SetCertificate() does not find my certificate

### ISSUE THREAD

**Issue by kotobelo** [dotnet/wcf#2083]
Any idea why these two apparent similar methods give different results. As I am working with UWP, I need to use the first method that doesn't find my certificate, the other method does work but I can not use it in UWP.

Method1 (results in error: Cannot find the X.509 certificate using the following search criteria...)

`string CertificateSerialNumber = "EED8EE38FAB3BB5B744C360747E99ECDAB"; ClientCertificate.SetCertificate(StoreLocation.LocalMachine, StoreName.My, X509FindType.FindBySerialNumber, CertificateSerialNumber );
`

Method2 (works but I can not assign that certificate directly to a proxy in UPW as it says it is not yet supported)

`string CertificateSerialNumber = "EED8EE38FAB3BB5B744C360747E99ECDAB"; X509Store storeX = new X509Store(StoreLocation.LocalMachine, StoreName.My); storeX.Open(OpenFlags.ReadOnly); X509Certificate2Collection collection = storeX.Certificates; X509Certificate2Collection scollection = (X509Certificate2Collection)collection.Find(X509FindType.FindBySerialNumber, CertificateSerialNumber, false);`

I dont understand enough to see what is different between these two methods.

**Comment by mconnew** [comment]
The UWP HttpClient only supports certificates stored in the CurrentUser store location and not the LocalMachine. We could add some better input validation here. I'm revisiting that area today anyway so I'll see if there's something simple which makes with regards errors throwing an exception, but it won't be on this API as in the next release we can use a certificate from any store for Net.Tcp.

**Comment by mconnew** [comment]
@kotobelo, does this address your issue? I did add a better error message which will be in the next UWP release. We're limited by the UWP HttpClientHandler implementation so there's nothing we can do.

**Comment by kotobelo** [comment]
Thanks Matt, I will try the next release.

Pedro

On 24 Jul 2017 20:24, "Matt Connew" <notifications@github.com> wrote:

@kotobelo <https://github.com/kotobelo>, does this address your issue? I
did add a better error message which will be in the next UWP release. We're
limited by the UWP HttpClientHandler implementation so there's nothing we
can do.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dotnet/wcf/issues/2083#issuecomment-317511611>, or mute
the thread
