### ISSUE TITLE
Suggestion/Enhancement: Include binary in the release tags (all previous versions released)

### ISSUE THREAD

**Issue by NinnOgTonic** [dotnet/wcf#2085]
Hi,

To follow up on the rollback performed in connection to https://github.com/dotnet/wcf/issues/2076, on our project in addition to getting blocked by this unfortunate timing, we also attempted to find a previous version in vein after concluding the the root cause probably was in this new release.

Perhaps going forward, it would be a good idea to:

* Include the binary release of the previous version under releases
* Present a link to github releases (and/or the github page more clearly) in the market place description of the plugin

**Comment by zhenlan** [comment]
@NinnOgTonic good suggestion! I will look into options.

**Comment by zhenlan** [comment]
WCF CS is released with Visual Studio 2017 since version 15.5 now. This issue is not applicable anymore.
