### ISSUE TITLE
ServicePointManager.ServerCertificateValidationCallback in Asp.net Core

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/wcf#2101]
I have a WCF Service in .NET Framework, and I want to consume it from Asp.Net Core.
I want to ignore the certificate validation in Asp.net Core, but ServicePointManager.ServerCertificateValidationCallback is not exist in Asp.net Core.
Is there any way to achieve this in Asp.Net Core?
Thanks for your help.

**Comment by zhenlan** [comment]
@Edward-Zhou can you check out [this](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs#L193) as an example?

**Comment by Edward-Zhou** [comment]
I have tried my below code, but it does not work.
`            client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication =
            new X509ServiceCertificateAuthentication()
            {
                CertificateValidationMode = X509CertificateValidationMode.Custom,
                CustomCertificateValidator = new MyX509CertificateValidator("CN=servicosdev2.caixaseguros.intranet")
            };`

**Comment by mconnew** [comment]
"it does not work" has a very wide range of possibilities. Can you provide a bit more detail?

**Comment by zhenlan** [comment]
@Edward-Zhou please let us know if you have an update. Closing the issue for now.
