### ISSUE TITLE
VS2017 WCF Connected Service

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/wcf#2111]
Hi,
I have an issue related with WCF Connect Service and .NET Core. Not sure whether it is specific to WCF.

Error message:

> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

Reproduce Steps:
1. Create a simple WCF Service

2. Add a .NET Standard library project, add WCF Service reference by adding connected Service Reference

3. Add a console application(.Net framework 4.6.2), add reference to library project

4. Call from below code, it throw error.
           ```
            Console.WriteLine("Hello World!");
            ClassLibrary1.Class1 c = new ClassLibrary1.Class1();
            Console.WriteLine(c.GetData(1));   //error pop up
            Console.ReadLine();
           ```
For step 3, if I create a console application (.NET Core), there will no error.
It seems the System.ServiceModel.Primitives reference is not embed into library dll, and I need to manually install System.ServiceModel.Primitives on console application.

**Comment by Edward-Zhou** [comment]
It seems to be related with targetframework, after follow below, it works.
Right Click .Net Standard library-> Edit ProjectName.csproj-> TargetFramework node to below

  <PropertyGroup>   
    <TargetFrameworks>net462;netstandard1.4</TargetFrameworks>
  </PropertyGroup>

**Comment by zhenlan** [comment]
@Edward-Zhou would you like to try out .NET Core 2.0 preview release ([System.ServiceModel.Primitives/4.4.0-preview2-25419-01](https://www.nuget.org/packages/System.ServiceModel.Primitives/4.4.0-preview2-25419-01)) and see if it works for you?

**Comment by zhenlan** [comment]
@Edward-Zhou please let me know if you have any update. Closing for now.

**Comment by YuWarm** [comment]
Thanks a lot @Edward-Zhou !
