### ISSUE TITLE
Investigate async hangs when on 1 or 2 cores.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2126]
Workaround for affected test cases fixed, Issue #2124 PR: #2125

Test cases...
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs#L79
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.0.0.cs#L183

The issue has only been reproduced at this point on Helix machines that have 1 or 2 cores. It does not repro on local machine that have more (8) cores.

Forcing the test to not run in parallel fixes the issue on the 1 and 2 core machines.
See the fix in: PR: #2125

To reproduce, setup a 2 core VM and run the 'Client.ChannelLayer.Tests' project.

Potentially a System.Threading issue as this problem does not exist in release/2.0.0

**Comment by zhenlan** [comment]
We can try to repro the issue on dev box with 1 or 2 cores.

**Comment by zhenlan** [comment]
@KKhurin repro'ed this issue. Will have a PR today to fix the test.

**Comment by KKhurin** [comment]
fixed with https://github.com/dotnet/wcf/pull/2278
