### ISSUE TITLE
Unable to load DLLs

### ISSUE THREAD

**Issue by mbearup** [dotnet/wcf#2132]
Despite several attempts, I can't seem to reference additional DLL's or packages in this project.
- I've focused mostly on the System.Private.ServiceModel csproj, but I've tried other csproj's and even the init-tools.msbuild script with no luck.
- If I reference a DLL (by absolute path, relative path, forward slahes, backslashes, etc) the compiler always complains that the dll could not be found. With other "vanilla" projects I can load these DLL's without issue.
- if I reference a package, the package reference seems to be completely skipped. The package is not downloaded into the "packages/" folder and build errors related to the missing package remain unresolved.

Any ideas what I'm doing wrong?

**Comment by zhenlan** [comment]
Hi @mbearup, you can find our developer guide [here](https://github.com/dotnet/wcf/blob/master/Documentation/developer-guide.md).

If you can share more of what you intend to achieve, we probably can assist you better. Please also keep in mind the project is using a custom [build system](https://github.com/dotnet/buildtools), it may not work as you would expect.

**Comment by zhenlan** [comment]
Discussed offline.
