### ISSUE TITLE
Some Java SOAP cannot be imported

### ISSUE THREAD

**Issue by RomanKernSW** [dotnet/wcf#2138]
I have a problem with some Java generated WSDL. I got an error: 

Processing instructions (other than the XML declaration) and DTDs are not supported. Line 1, position 2. 

the classic .net with service reference do not have such problems. Would be nice if the generator would work verbosely. the first line looks always this way: <?xml version="1.0" encoding="UTF-8"?>

Sorry, but I cannot provide the WSDL, since the interface is closed source.
Surprisingly the other Java SOAP works fine for me.
![image](https://user-images.githubusercontent.com/19260595/28814522-3a86e07e-769e-11e7-9c68-fa9997578b60.png)

the WCF Tool Version is: 0.5.10718.1239

**Comment by mathieubouchard** [comment]
Does your contract has an UTF-8 encoding with a BOM header?

**Comment by RomanKernSW** [comment]
the java service (generated with apache CXF) have in WSDL UTF-8 Encoding on XML. Means, header should be encoded in UTF-8 too.

I have a simple request here, that may help a little bit.


[test.txt](https://github.com/dotnet/wcf/files/1193214/test.txt)

**Comment by RomanKernSW** [comment]
OK, my college that do the java service have a server side solution.

on processing the xsd file the tool found one xml declaration that is not belong to the soap standard(?)
<?xml-stylesheet ... ?> removing that will solve the problem!
