### ISSUE TITLE
Visual Studio WCF Connected Service - 

### ISSUE THREAD

**Issue by schris403** [dotnet/wcf#2144]
When trying to add a service via the WCF Web Service Reference Provider tool in VS2017, we get the following error:

"The maximum read depth (32) has been exceeded because XML data being read has more levels of nesting than is allowed by the quota. This quota may be increased by changing the MaxDepth property on the XmlDictionaryReaderQuotas object used when creating the XML reader. Line 37, position 368."

For testing purposes, below is the wsdl that is causing this error:
https://services.bicgraphic.com/soa-infra/services/external/OrderShipmentNotificationService/OrderShipmentNotificationService?WSDL

From a bit of research, it seems that this may be a setting that may need be increased in the tool itself. Any help would be greatly appreciated!

**Comment by hongdai** [comment]
@schris403  Sorry for running into the issue. You are right that we can increase the maximum read depth in the tool. We will increase it for the next release.

To workaround in the mean time, you can download the wsdl file locally and give the local path to the tool. That should work.

**Comment by spankepabs** [comment]
The local wsdl is not working.  Is there anyway for us to set a larger value until you update the tool?

**Comment by hongdai** [comment]
This is fixed in the latest release.
