### ISSUE TITLE
System.InvalidOperationException: System.Xml.Linq.XElement cannot be used as: 'xml text'

### ISSUE THREAD

**Issue by RomanKernSW** [dotnet/wcf#2150]
Hi,
i have some problem with generated client proxy. Could be an issue that code generator produce.
[Stacktrace.txt](https://github.com/dotnet/wcf/files/1196925/Stacktrace.txt)
The types are comming from this xsd file
[W3C-XMLDSig.txt](https://github.com/dotnet/wcf/files/1196929/W3C-XMLDSig.txt)

I dont get, where exactly is the problem! I've tried to use ClientMessageInterceptor, but the problem seems to appear before the Interceptor is getting called.

`[TestMethod]
        public void Test()
        {
            
            var client = new ServiceClient();
            var result = client.GetSomething(new GetRequest {...}).Result; //here the exception
            Assert.IsNotNull(result);
        }`

it something about <any namespace="##other" processContents="lax"/> of type any that client proxy generator cannot handle?

Thanks

**Comment by hongdai** [comment]
@RomanKernSW Sorry to hear that you are running into a issue.

We will try to repro it locally.

**Comment by hongdai** [comment]
@RomanKernSW Is it possible to share the generated reference.cs? We cannot get a repro by just using the xsd file.

**Comment by hongdai** [comment]
@RomanKernSW How did you generated the reference.cs? The xsd file looks like Message security is needed, and it is not supported on the .Net Core yet.

**Comment by RomanKernSW** [comment]
ah Message Sec is not supported yet? But the Contracts for Message sec were successfully generated. Do you still need the wsdl or xsd files?
When will be message supported?

**Comment by hongdai** [comment]
Unfortunately we don't have a timeline yet for message security feature.

Which tool did you generate the contract?

**Comment by RomanKernSW** [comment]
with WCF Connected Service latest version. I will talk to the developer for samples. maybe its not a security feature at all

**Comment by hongdai** [comment]
@RomanKernSW Could you share me the repro wsdl file? I can attempt a repro to confirm exactly what's needed.

**Comment by hongdai** [comment]
@RomanKernSW Please reopen the issue once you have a repro wsdl file.

Thanks,
Hong Dai

**Comment by aritsa** [comment]
Hi. Im running into the same problem.

Here is the wsdl
[wsdl.zip](https://github.com/dotnet/wcf/files/1361624/wsdl.zip)

And here is the generated reference
[Reference.zip](https://github.com/dotnet/wcf/files/1361626/Reference.zip)

Seems like it does  not like the System.Xml.Linq.XElement Any properties like in:

```

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil","0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }

```
