### ISSUE TITLE
AX AIF Endpoint Can't be Discovered

### ISSUE THREAD

**Issue by madSimonJ** [dotnet/wcf#2162]
I've got an AX AIF end point, which uses the net.tcp protocol, which I'm trying to find a method of consuming in .NET Core 1.1.  I've tried using this tool, but all I get is an error message telling me that there were not discoverable services.

Is anyone aware of a solution to this issue?

**Comment by zhenlan** [comment]
@madSimonJ could you please clarify which tool you referred here? Can you please share the end point address? What are the steps you got the error?

**Comment by zhenlan** [comment]
@madSimonJ please let me know if you have an update. Closing for now.
