### ISSUE TITLE
Problem with WSDL size when fetching from URI

### ISSUE THREAD

**Issue by diazrm** [dotnet/wcf#2172]
**Steps:**

1. In a _Class Library (.NET Core)_ project, click right-button on the project, select _Add_, _Connected Service_ 
2. Select _Microsoft WCF Web Service Reference Provider - Preview_
3. In the _URI_ field, enter the URI of a webservice with a WSDL bigger than 4096 bytes
4. Press _Go_ button

**Expected result:**

Succesful service and methods discovery.

**Actual result:**

In the _Status_ field, the following error message appears and the process cannot continue:

_The 'maximum bytes per Read operation' quota (4096) has been exceeded while reading XML data. Long element start tags (consisting of the element name, attribute names and attribute values) may trigger this quota. This quota may be increased by changing the MaxBytesPerRead property on the XmlDictionaryReaderQuotas object used when creating the XML reader. Line 1, position 4097._

**Additional information:**

I'm aware that there is a setting available to allow a bigger value, but have not found which configuration file should be modified.

In the attached file are the WSDL and XSD files that can be used as example to reproduce the error steps:

[ServiceReference.zip](https://github.com/dotnet/wcf/files/1212373/ServiceReference.zip)

**Comment by dstonham** [comment]
I was hit by the same issue but, as a workaround, downloading the wsdl and loading it from the local file seems to bypass this problem.

**Comment by hongdai** [comment]
Thanks for the feedback! We will increase the quota in the next release.

**Comment by diazrm** [comment]
@hongdai isn't it possible to modify the configuration in the actual release? Some hidden .config or .json file or something like that. As a workaround, I mean.

**Comment by hongdai** [comment]
@diazrm The tool is currently code based and does not depend on any configuration file. Thus the only workaround is to download the wsdl from a browser.

**Comment by hongdai** [comment]
This is fixed in the next release.
