### ISSUE TITLE
"The service at the following URI does not have any endpoints compatible with .Net Core apps" from connected services 0.5.10718.1239

### ISSUE THREAD

**Issue by monotore** [dotnet/wcf#2180]
I have a WSDL as a local file, and try to use WCF Connected Service for Visual Studio 2017 version 0.5.10718.1239 to generate service references. I get this error messange at first step when i browse and select my WSDL:
_The service at the following URI does not have any endpoints compatible with .Net Core apps:'C:\Api\Doc\TokenCreate\TokenCreate.wsdl'_

Is it any way to get more feedback from the tool about what's not compatible with this endpoint?
Maybe a command line way of generating references?
Any log files?

**Comment by hongdai** [comment]
@monotore  you can find the log file in %temp%\WCFConnectedService. 

Could you click on the "Finish" button on the first page? The tool will continue and generate more information in the log file.

In the next release next week, we will also show more details in the UI in this case.

**Comment by hongdai** [comment]
The latest release now show more details in the UI in this case. Please reopen the issue if it's not sufficient.

**Comment by monotore** [comment]
@hongdai The lastest release does not show any valuable new information. The following redudant text is added at the beginning of the previous text:
_An error occured while browsing WSDL file 'C:\Api\Doc\TokenCreate\TokenCreate.wsdl'_

The "Finish" button is disabled, so I'm not able to click it to generate more information in the log file as suggested.

**Comment by hongdai** [comment]
@monotore Could you share the TokenCreate.wsdl file? We will try to repro it locally.
