### ISSUE TITLE
[Master] Enable UAP test variations on Windows. (VSTS)

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2183]
Currently UAP variations have been disabled due to missing resources in PRI files that is being fixed by dotnet/buildtools#1630, there the issue results in a build failure. Once the fix is merged we will need to update our Master branch to the buildtools version containing the fix and verify that our UAP tests pass.

@mconnew has more context on this issue.

Once it is verified fixed in Master update uwp6.0 branch.

**Comment by StephenBonikowsky** [comment]
@mconnew Could you keep an eye on the fix in buildtools? If it gets in it would be nice to upgrade to the new version and at least do a local run to verify results.

Adding @safern as FYI

**Comment by safern** [comment]
The PR just went in. Will update with the buildtools version whenever the package is published.

**Comment by safern** [comment]
@StephenBonikowsky The buildtools version you guys want to update to is: `2.0.0-prerelease-01918-01`

**Comment by StephenBonikowsky** [comment]
Thank you @safern !

**Comment by safern** [comment]
> Thank you @safern !

Anytime, please let me know if I can help you guys in another way or if you hit something else related to this.

**Comment by StephenBonikowsky** [comment]
UAP test configurations have been added to Master and release/2.1.0
