### ISSUE TITLE
WCF ClientBase Close method is private

### ISSUE THREAD

**Issue by stephentoub** [dotnet/wcf#2194]
_From @timClyburn on August 14, 2017 7:23_

I have an existing nuget package that contains some WCF DataContracts, ServiceContracts and proxy classes that I am now attempting to migrate for use in a dotnetcore project in VS2017 (15.2 - 26430.16 release version).
In the code there is a base proxy class that implements ClientBase and IDisposable. The dispose method calls Close() on the ClientBase. It seems now that in assembly System.ServiceModel.Primitives Version=4.1.1.0, which ins installed through the nuget package System.ServiceModel.Primatives 4.3.0 has this as a private method.
Am I missing something here? Is there something else I need to do or another package that I need?

Thanks
Tim 

Moved from [https://github.com/aspnet/Home/issues/2123](url) 

_Copied from original issue: dotnet/corefx#23206_

**Comment by mconnew** [comment]
@timClyburn, `Close()` isn't a private method on `ClientBase<TChannel>`. The `Close()` method is defined in the interface `ICommunicationObject` which `ClientBase<TChannel>` implements. The difference between the full framework and .Net Core is that in .Net Core, it is an [explicit interface implementation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation) whereas on the full framework it isn't. If you want to call the close method, you need to cast to `ICommunicationObject`. For example:
```csharp
public void Dispose()
{
    ((ICommunicationObject)this).Close();
}
```
That should work on the full framework and on .Net Core as it will cause the method to be looked up in the VTable of ICommunicationObject which will work on both. We can look into changing this to not be explicit, but I don't know what the binary backwards compatibility would be. I suspect it would be fine, but I would need to verify.

**Comment by timClyburn** [comment]
Thanks @mconnew, thats great. Next time I'll look in the source and check the implementation before posting! Thanks.
