### ISSUE TITLE
"Unable to restore NuGet packages" when adding service reference.

### ISSUE THREAD

**Issue by dstonham** [dotnet/wcf#2204]
Using version 0.5.10808.800 in a .net core 1.1 project under VS2017 v15.2 (26430.16).

I'm unable to add a service.  After completing the wizard, at the "Restoring NuGet packages..." step I see the error "Unable to restore NuGet packages, please ensure packages can be restored for the project."

The Output window shows the additional message "Failed adding Microsoft WCF Web Service Reference Provider - Preview to the project."

This error seems very similar to the one discussed in #2076 but I can't find a way to download / install previous versions of the extension in order to check.

**Comment by hongdai** [comment]
@dstonham Can you restore and build your project successfully without using the tool? The tool requires the user project can be built in order to adding service reference.

Thanks,
Hong Dai

**Comment by de12345** [comment]
have the same problem version 0.5.10808.800
we are getting this NuGet packages restore error:
Restoring NuGet packages ...
Error:Unable to restore NuGet packages, please ensure packages can be restored for the project.

tried restoring via VS menu - and this works with no problem
also rebuild is working with no problem

how can i revert to last version?

**Comment by dstonham** [comment]
@hongdai Yes, the project builds fine.  Only see a problem on trying to add the service.  Is there a nuGet package I can try to install manually?  I tried searching the standard nuget repo for "Microsoft WCF Web Service Reference Provider - Preview" but couldn't find anything.

**Comment by hongdai** [comment]
@dstonham @de12345 Could you try below workaround?
1) Open a new Dotnet Core -> Console Application.
2) Add the desired service reference.
3) Copy the generated reference.cs to your project.
4) Add below package references to your project:

    <PackageReference Include="System.ServiceModel.Duplex" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />

Could you share your .csproj file? We will try to repro the issue locally.

Thanks,
Hong Dai

**Comment by dstonham** [comment]
Thanks @hongdai.  I was able to generate the class in a fresh project and then move it across.  Took a while to find the right nuGet packages but it seems to be working.

When a run "dotnet restore" I see a number of errors that report "error NU1605: Detected package downgrade: System.Security.Claims from 4.3.0 to 4.0.1." so it seems likely that is the issue.  I've asked the dev working on that to look into it.

Thanks again.
