### ISSUE TITLE
Trying to consume a WCF service app (VS2017) using this tool, WaitingForActivation response...

### ISSUE THREAD

**Issue by kevint2017** [dotnet/wcf#2208]
Hi,

I've got a project I'm working on at the moment, WCF Service app built using .Net Framework 4.6.1 in VS 2017 that I'm trying to consume from a .Net Core 1.1 web app, the code compiles, creates the Async reference methods (note the original methods are only sync). But when I run the calls to the service  it does nothing, all I get is a response like  

> "Id = 28, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}""

And nothing happens on the service side.

What am I doing wrong here?

The service is working correctly when tested from a .Net Framework web app.

Thanks, Kevin

**Comment by hongdai** [comment]
@kevint2017 Just to confirm, Did you try copying the generated reference.cs to a .Net Framework 4.6.1 project and run the code?

Is it possible for you to give us a repro to help further investigation?
Thanks,
Hong

**Comment by hongdai** [comment]
Closing as no repro to investigate.
