### ISSUE TITLE
Issue with VS2017 Core 2.0 Consuming Net4.5.2 WCF service 

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/wcf#2209]
we are working web application on Core 2.0, VS2017 15.3.
We had few WCF services written on .Netframework 4.5.2. To consume these services in Core 2.0, We don't want to go with "VS WCF Connected Service extensions" as it uses Proxies and WSDL.

Alternative to "WCF Connected Service"  we did the following things:
1) we have created WCF service wrappers on Core 2.0 , created Agents, Clients, Contracts based on .Netframeowrk 4.5.2 actual services and added packages for "System.Private.ServiceModel", System.ServiceModel.Http/NetTcp/Primitives/Security" 4.4.0 release versions.

2) we have created web project in Core 2.0 and referred the wrapper libraries and added the following code
//var url = Environment.GetEnvironmentVariable("url");
            var helloEndpoint = new EndpointAddress("");
            var binding = new BasicHttpBinding();
            var factory = new ChannelFactory<IService>(binding, helloEndpoint);
            var client = factory.CreateChannel();
var result = client.Get();

However we are getting error "System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel"

**Comment by hongdai** [comment]
@pardhumeduri, there are a couple of possible issues:
-  It looks like you build the project in .net framework instead of Dotnet core as it attempts to load System.ServiceModel.
-  You should not directly add "System.Private.ServiceModel" package. The packages you need are:
  ```
  <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.0" />
```

Hope it helps,
Hong Dai

**Comment by hongdai** [comment]
@pardhumeduri Could you share your csproj file?

**Comment by pardhumeduri** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
	
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
	<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.0" />
	<PackageReference Include="System.Net.Requests" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
	</ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

  

</Project>

**Comment by hongdai** [comment]
Please attach the actual csproj file, if you can share.

**Comment by pardhumeduri** [comment]
CSPROJfile


<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
	
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
	<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.0" />
	<PackageReference Include="System.Net.Requests" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
	</ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

  

</Project>

**Comment by hongdai** [comment]
It seems you have difficulty to attach it, Could you send it to me by email?

**Comment by pardhumeduri** [comment]
[csproj.zip](https://github.com/dotnet/wcf/files/1232216/csproj.zip)

**Comment by hongdai** [comment]
@pardhumeduri If I understand correctly, you have a wrapper library that does the actual call. I will need to take a look your wrapper project definition.

**Comment by pardhumeduri** [comment]
but even without wrapper we are getting the same error.
following code is not using wrapper
//var url = Environment.GetEnvironmentVariable("url");
var helloEndpoint = new EndpointAddress("");
var binding = new BasicHttpBinding();
var factory = new ChannelFactory(binding, helloEndpoint);
var client = factory.CreateChannel();
var result = client.Get();

**Comment by hongdai** [comment]
Could you send me your repro Application? It seems you have a simple repro.

**Comment by hongdai** [comment]
Closing as no further action can be taken without a repro Application.
