### ISSUE TITLE
Add StreamFormatter.GetStreamAndWriteStartWrapperIfNecessaryAsync

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#221]
SerializeAsync.SerializeAsync is consuming GetStreamAndWriteStartWrapperIfNecessary. We should add an async version of this method.

**Comment by shmao** [comment]
Will be fixed by PR 209.

**Comment by shmao** [comment]
GetStreamAndWriteStartWrapperIfNecessary and WriteEndWrapperIfNecessaryAsync are using XmlDictionaryWriter's sync methods. We should switch them to use the async methods, which are not implemented yet.

**Comment by shmao** [comment]
I had the changes for this issue ready. This is pending on #341 (Change Minimum Required Version for Serialization Package to beta-8).

**Comment by roncain** [comment]
@shmao -- just to be clear, issue #341 will only *use* the beta8 version of System.Runtime.Serialization.Xml.  But version 4.0.11 does not contain any new API you can call. Were you planning to call new API's or just refactor the WCF code to use the existing API's in a different way?

**Comment by shmao** [comment]
Some async methods in System.Runtime.Serialization.Xml were existing APIs, but were not implemented. dotnet/corefx#2596 added implementations for those APIs. The fix for this issue is to change the WCF code to call those async methods.

**Comment by roncain** [comment]
We haven't yet taken a dependency on the beta8 packages because we were waiting for the packages to become available.  We are also waiting for https://github.com/dotnet/wcf/pull/383 to be checked in first to update the project.lock.json files.  Then we can apply the new dependency on 4.0.11.

**Comment by shmao** [comment]
This is fixed by https://github.com/dotnet/wcf/issues/435.
