### ISSUE TITLE
WCF Connected Service .Net 4.7

### ISSUE THREAD

**Issue by egorpavlikhin** [dotnet/wcf#2212]
Visual Studio extension still support .net framework up to 4.6.2 https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService
Although 4.7 has been out for almost 5 months.

**Comment by hongdai** [comment]
@egorpavlikhin  Thanks for your feedback! We are evaluating the support.

**Comment by zhenlan** [comment]
We will add the support in our next update.
