### ISSUE TITLE
Error installing Microsoft WCF Web Service Reference Provider - .NET Core

### ISSUE THREAD

**Issue by GSAcebal** [dotnet/wcf#2213]
Hi, how are you! ... I download Microsoft WCF Web Service Reference Provider ( https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService ). When I install it I get the following error:
![failinstaller](https://user-images.githubusercontent.com/11872837/29472990-5bd48452-842c-11e7-84f9-a82dd5eb7cf0.jpg)

I have the latest version of visual studio 2017 with its corresponding updates.

thank you very much for your help!

**Comment by hongdai** [comment]
@GSAcebal Sorry to hear that you are running into an issue!

What's your visual studio version and sku? Also could you share the Install Log?

Thanks,
Hong Dai

**Comment by GSAcebal** [comment]
Hi @hongdai ...

My version of VS2017:
![vs2017version](https://user-images.githubusercontent.com/11872837/29474866-dcf5b626-8433-11e7-9bc5-f7ab688dadf0.JPG)

The Install Log:

18/08/2017 16:40:10 - Microsoft VSIX Installer
18/08/2017 16:40:10 - -------------------------------------------
18/08/2017 16:40:10 - Initializing Install...
18/08/2017 16:40:10 - Extension Details...
18/08/2017 16:40:10 - 	Identifier         : WCFCS.C7738AB0-25C3-4220-BE27-2C3A872B57F2
18/08/2017 16:40:10 - 	Name               : Microsoft WCF Web Service Reference Provider
18/08/2017 16:40:10 - 	Author             : Microsoft
18/08/2017 16:40:10 - 	Version            : 0.5.10808.800
18/08/2017 16:40:10 - 	Description        : A Visual Studio Connected Service to add WCF Web service references to .NET Core projects in Visual Studio 2017.
18/08/2017 16:40:10 - 	Locale             : en-US
18/08/2017 16:40:10 - 	MoreInfoURL        : http://go.microsoft.com/fwlink/?LinkId=843369
18/08/2017 16:40:10 - 	InstalledByMSI     : False
18/08/2017 16:40:10 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
18/08/2017 16:40:10 - 
18/08/2017 16:40:11 - 	SignatureState     : ValidSignature
18/08/2017 16:40:11 - 	SignedBy           : Microsoft Corporation
18/08/2017 16:40:11 - 	Certificate Info   : 
18/08/2017 16:40:11 - 		-------------------------------------------------------
18/08/2017 16:40:11 - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
18/08/2017 16:40:11 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
18/08/2017 16:40:11 - 		[Serial Number] : 330000017D015E4C2BE2BCF66900000000017D
18/08/2017 16:40:11 - 		[Not Before]    : 15/02/2017 16:10:16
18/08/2017 16:40:11 - 		[Not After]     : 09/05/2018 16:10:16
18/08/2017 16:40:11 - 		[Thumbprint]    : 69713C6FF47FADFF90C9465F7783E6E08232B28F
18/08/2017 16:40:11 - 
18/08/2017 16:40:11 - 	Supported Products : 
18/08/2017 16:40:11 - 		Microsoft.VisualStudio.Community
18/08/2017 16:40:11 - 			Version : [15.0,16.0)
18/08/2017 16:40:11 - 		Microsoft.VisualStudio.Pro
18/08/2017 16:40:11 - 			Version : [15.0,16.0)
18/08/2017 16:40:11 - 
18/08/2017 16:40:11 - 	References         : 
18/08/2017 16:40:11 - 		-------------------------------------------------------
18/08/2017 16:40:11 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
18/08/2017 16:40:11 - 		Name         : Visual Studio MPF 15.0
18/08/2017 16:40:11 - 		Version      : [15.0,16.0)
18/08/2017 16:40:11 - 		MoreInfoURL  : 
18/08/2017 16:40:11 - 		Nested       : No
18/08/2017 16:40:11 - 
18/08/2017 16:40:11 - 		-------------------------------------------------------
18/08/2017 16:40:11 - 		Identifier   : ConnectedServices.897486C9-63BD-48D3-8A33-CB770FBD0723
18/08/2017 16:40:11 - 		Name         : Microsoft Connected Services
18/08/2017 16:40:11 - 		Version      : [15.0,16.0)
18/08/2017 16:40:11 - 		MoreInfoURL  : 
18/08/2017 16:40:11 - 		Nested       : No
18/08/2017 16:40:11 - 
18/08/2017 16:40:11 - 		-------------------------------------------------------
18/08/2017 16:40:11 - 		Identifier   : 1D7A611D-F1E7-4E23-91D6-C64426EBE6B5
18/08/2017 16:40:11 - 		Name         : Microsoft ASP.NET and Web Tools
18/08/2017 16:40:11 - 		Version      : [15.0,16.0)
18/08/2017 16:40:11 - 		MoreInfoURL  : 
18/08/2017 16:40:11 - 		Nested       : No
18/08/2017 16:40:11 - 
18/08/2017 16:40:11 - Signature Details...
18/08/2017 16:40:11 - 	Extension is signed with a valid signature.
18/08/2017 16:40:11 - 
18/08/2017 16:40:11 - Searching for applicable products...
18/08/2017 16:40:12 - Found installed product - Microsoft Visual Studio 2010 Premium
18/08/2017 16:40:12 - Found installed product - Microsoft Visual Studio Professional 2013
18/08/2017 16:40:12 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
18/08/2017 16:40:12 - Found installed product - Microsoft Visual Studio Professional 2015
18/08/2017 16:40:12 - Found installed product - Microsoft Visual Studio Community 2015
18/08/2017 16:40:12 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
18/08/2017 16:40:12 - Found installed product - Global Location
18/08/2017 16:40:12 - Found installed product - ssms
18/08/2017 16:40:12 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   en VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   en VSIXInstaller.App.InitializeInstall()
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()

Thanks!!!

**Comment by hongdai** [comment]
@GSAcebal The log does not show you have vs2017 installed. That's why it failed. We will try to repro it in house.

**Comment by GSAcebal** [comment]
@hongdai Thank you very much, it would be very useful to solve this problem!!

**Comment by hongdai** [comment]
@GSAcebal  We can install it successfully.

It's probably a side by side issue as there are 2013, vs2015 installed. We do not own the installer. While I will find the right team for this issue, you can work around it by using a machine without 2013 and 2015 installed.

**Comment by GSAcebal** [comment]
@hongdai  Thank you so much for everything! Try reinstalling VS.

**Comment by GSAcebal** [comment]
I could solve it, I ended up re-installing the VS
