### ISSUE TITLE
Generate proxy at runtime

### ISSUE THREAD

**Issue by ekarimi** [dotnet/wcf#2220]
Hi,
I maybe miss something in here. But I can't find a single example on how to generate a client proxy at runtime for later invoke in .Net Core.
Here is what I do in .Net Framework : 

```
            ServiceDescription serviceDescription = ServiceDescription.Read(_metadataMemoryStream);
            ServiceDescriptionImporter serviceDescriptionImporter = new ServiceDescriptionImporter
            {
                ProtocolName = "Soap12",
                Style = ServiceDescriptionImportStyle.Client,
                CodeGenerationOptions = CodeGenerationOptions.GenerateProperties
            };
            serviceDescriptionImporter.AddServiceDescription(serviceDescription, null, null);

            CodeNamespace codeNamespace = new CodeNamespace();
            CodeCompileUnit codeCompileUnit = new CodeCompileUnit();
            codeCompileUnit.Namespaces.Add(codeNamespace);

            ServiceDescriptionImportWarnings warnings = serviceDescriptionImporter.Import(codeNamespace, codeCompileUnit);
            if (warnings == 0)
            {
                using (CodeDomProvider codeDomProvider = CodeDomProvider.CreateProvider("CSharp"))
                {
                    CompilerParameters compilerParameters = new CompilerParameters(AssemblyReferences)
                    {
                        OutputAssembly = @"D:\MyTemp\Proxy\" + Guid.NewGuid()
                    };
                    CompilerResults results = codeDomProvider.CompileAssemblyFromDom(compilerParameters, codeCompileUnit);
                    _soapAssembly = results.CompiledAssembly;
                    _pathToAssembly = results.PathToAssembly;
                    return _soapAssembly;
                }
            }
```

ServiceDescription or ServiceDescriptionImporter is not supported by .Net Core.
So, how can I generate proxy at runtime?

I couldn't find the issue, sorry if it is dublicate.

**Comment by zhenlan** [comment]
Hi @ekarimi as you noticed `ServiceDescription` or `ServiceDescriptionImporter` are not available. The reason is because they require CodeDom and down the road they require Serialization that requires CodeDom too. CodeDom today is only a partial port on .NET Core and it's not part of .NET Standard while Serialization is part of .NET Standard and a component in .NET Standard cannot depend on a component that is not.

We have a [tool](https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService) for WCF client proxy generation. I understand it may not serve what you need. Can you share more details of your scenario and why runtime proxy generation is important to you?

cc: @mlacouture

**Comment by ekarimi** [comment]
Hi @zhenlan
Thanks for answering.
--
Our scenario is quite simple. We have a tool that gets the url of a web service ( for example a soap web service).
Then with the code above (first post), I can read the web methods inside it and invoke it with the right parameters ( quite easy with reflection as we all know).
Now, why I can't use the tool that you provided? Because it's up to the customer. I don't have the url, I don't know which method they're going to use or call. 
Here is a example : 
1- A client paste an url. ( yeah, pasting, they are that lazy! )
2- In the code behind, we call to the url and generate a proxy with assembly at runtime so we can use it for later invoke.
3- Then with reflection, we show the client the web methods along with their parameters.
4- Client select the method, type the right value for parameters and then click.
5- In the code behind, we invoke the method, show the client its result.

Now, Maybe I'm doing it the wrong way. But it's the only way that I'm aware of.
Can you put me in the right direction? Or I just have to wait for a real solution for .Net Core?
Thanks in advance.

**Comment by zhenlan** [comment]
Thanks for sharing the details @ekarimi. The scenario you described sounds very similar to `WcfTestClient.exe`, which is a WCF tool in Visual Studio (and is built on full .NET).

Due to the technical reason I explained earlier, this is unfortunately not easily achievable on .NET Core today.

**Comment by martinpg2001** [comment]
Hi - I have exactly the same problem. I need to support a tool that dynamically generates a client UI from a SOAP Web service WSDL. We'd like to port this to .Net Standard 2.0, but it's a non-starter if there aren't functional equivalents to the ServiceDescription and CodeDom APIs. Are these on the roadmap to be added to .Net Standard? Thanks for any feedback, Martin

**Comment by HongGit** [comment]
Thank you for the feedback, but our team was unable to prioritize it at this time as they are working on problems with broader customer impact.

**Comment by mohdali** [comment]
Hi, is there any further update on this? I'm looking for the same scenario to implement in .NET Core 3.1.

**Comment by biasc** [comment]
I'm looking for the same scenario to implement in .NET6.

**Comment by ApacheTech** [comment]
Same in .NET8. I'm writing an API reference documentation website for a backwards compatible API. I'm migrating code from .NET Framework 4.7.2 Umbraco site, to a .NET8 Blazor/OrchardCore de-coupled site.

In `net472`, we get the results of any given WSDL URL, read it into a `System.Web.Services.Description.ServiceDescription`, check if there are any warnings with a `System.Web.Services.Description.ServiceDescriptionImporter`, create an assembly in memory, with `Microsoft.CSharp.CSharpCodeProvider`, and then read the `System.Type` from the assembly via reflection.

A lot of this has been ripped out of BCL in Core. Both SOAP and WCF are both depreciated, but a lot of our clients still use the SOAP services on legacy projects; so we need to keep them up, and documented. But, we also need to move on tech-stack wise.  So, I'm wondering what the options are. Ideally, some wonderful person will have created a NuGet library that would wrap all of this up, and make it all magically work within `net8.0`. But, failing the coming of a saviour, how else would it be possible to programmatically resolve a `System.Type` from any given WSDL URL?

The services themselves are not being touched. All I'm doing is migrating the API reference docs. The reference docs have code samples, and live demos. The live demos can use REST, that's fine, but the code samples are programmatically built from the SOAP objects.
