### ISSUE TITLE
No endpoints compatible with .Net Core apps were found

### ISSUE THREAD

**Issue by mikeli11** [dotnet/wcf#2221]
Hi,

Is there anyway to get a more detailed error message to find out what the issue is? I'm not sure if this is an issue with the wsdl or the tool.

I am trying to reference this wsdl - https://github.com/mantisbt/mantisbt/blob/master/api/soap/mantisconnect.wsdl

![image](https://user-images.githubusercontent.com/1974887/29571870-55ea66e6-8752-11e7-9935-40a3c6bbe322.png)

**Comment by mikeli11** [comment]
Issue was I was targeting netcoreapp1.1, once i changed this to 2.0 it worked.

**Comment by hongdai** [comment]
@mikeli11 This is expected. We depend on Dotnet core WCF runtime, and it does not support SOAP Encoding prior to 2.0.
