### ISSUE TITLE
Error: "An error occurred in the tool. An item with the same key has already been added" when trying to add a Service Reference

### ISSUE THREAD

**Issue by diazrm** [dotnet/wcf#2226]
**Steps:**

1. In an empty _Class Library (.NET Standard)_ project, click right-button on the project, select _Add_, _Connected Service_ 
2. Select _Microsoft WCF Web Service Reference Provider - Preview_
3. In the _URI_ field, enter the path of the files included in the attached file, but replacing the name of the wsdl file with `*.*` (without quotes):
[Tarjeta.zip](https://github.com/dotnet/wcf/files/1247006/Tarjeta.zip)
4. Press _Go_ button
5. In the Services pane, a service called _integracion/tarjeta_ should appear. In the Status pane, the following message: "Number of services found: 1"
6. Press _Finish_ button

**Expected result:**

Succesful service and methods discovery.

**Actual result:**

An error message shows in the result window: "An error occurred in the tool. An item with the same key has already been added. Key: Tarjeta"
Snapshot: 

![error_message](https://user-images.githubusercontent.com/14352381/29638980-804ad6c2-882f-11e7-9879-f988b49fb59f.jpg)

And in the following path, additional logs can be found:
C:\Users\mdiaz\AppData\Local\Temp\WCFConnectedService\2017_Aug_23_18_16_10\
[2017_Aug_23_18_16_10.zip](https://github.com/dotnet/wcf/files/1247074/2017_Aug_23_18_16_10.zip)

**Additional information:**

PLEASE, THIS IS CRITICAL AND BLOCKING. **We cannot continue with development of our solution since we didn't found any workaround so far**, and there is no other tool (like svcutil) to generate the service reference.

**Comment by hongdai** [comment]
@diazrm Are you using the latest version of the tool? We have fixed the issue in the latest version.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@diazrm  I can repro the issue in the latest tool. Looks like a different issue we have fixed. We will investigate it.

Thanks,
Hong Dai

**Comment by diazrm** [comment]
For the record: I'm using the 0.5.10808.800 version.
Visual Studio: 15.3.2

**Comment by hongdai** [comment]
@diazrm  There is a problem in your web service definition. Tarjeta is defined twice, one is service interface, another one is a class. This is not supported.

`  <wsdl:portType name="Tarjeta">` in the Tarjeta.wsdl file.
and [ <xsd:complexType name="Tarjeta">](url) in Tarjeta39.xsd file.
You will need to talk to the owner of the service to rename one of them.

Hope it helps,
Hong Dai

**Comment by diazrm** [comment]
Great, thank you.
It would be very useful if the tool could raise an specific exception, instead of the generic (and mileading) one that is throwing today.

**Comment by hongdai** [comment]
@diazrm  Thanks for your feedback! We will evaluating whether the error message can be improved.

**Comment by diazrm** [comment]
Also keep in mind that the similar tool found in VS2015 does indeed support that kind of repeated definition. You can try it: add a Service Reference in that version with the same files that I've attached and you'll see.

**Comment by hongdai** [comment]
1. Were you be able to use the generated proxy from VS2015 to invoke the service successfully? I have used the svcutil tool from full framework, it generates the code, but does not even compile.

2. I tried "Add Service Reference" without success as I don't have access to 'wmbdesa'. it gives me below error:

```
"The document was understood, but it could not be processed.
  - The WSDL document contains links that could not be resolved.
  - There was an error downloading 'https://wmbdesa/integracion/tarjeta?xsd=xsd0'.
  - The remote name could not be resolved: 'wmbdesa'
```
Could you generate a single wsdl by using` ?singleWsdl ` in the browser? That probably get rid of the dependency on wmbedesa.

Thanks,
Hong Dai

**Comment by diazrm** [comment]
1. No, I've used the GUI to generate the reference:

![image](https://user-images.githubusercontent.com/14352381/29728038-b65d29f8-89ac-11e7-9334-bda098734b39.png)

After that, the project compiles successfuly.

2. No, the service doesn't support the _singleWsdl_ parameter. Do you want me to follow some steps and copy the screenshots of the process?

**Comment by hongdai** [comment]
Can you send me the source code file Add Service Reference generated? That could be helpful.

**Comment by diazrm** [comment]
This is it:

[Com.Gyf.DataProviders.ItauWebService.IntegracionTarjeta.zip](https://github.com/dotnet/wcf/files/1252954/Com.Gyf.DataProviders.ItauWebService.IntegracionTarjeta.zip)

**Comment by hongdai** [comment]
@diazrm The Tarjeta.cs in your zip file does NOT compile. It gives below compiling error message for the reason I mentioned previously(Tarjeta is defined twice):

`Error	CS0101	The namespace '<global namespace>' already contains a definition for 'Tarjeta'`
`For line 4934:  public partial class Tarjeta`

Could you please double check if it compiles for you?
Thanks,
Hong Dai

**Comment by diazrm** [comment]
Well... that's precisely the problem. The .cs file is auto-generated from the WSDL. Thus, the duplication problem that occurs in the WSDL also happens in the .cs file.

**Comment by hongdai** [comment]
Yes, that's why the only way to fix it is to fix the wsdl file.
