### ISSUE TITLE
Fix CoreFx dependency now supporting NetCoreApp2.1

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2230]
@ericstj move the Master branch in CoreFx to netcoreapp2.1
This breaks WCF when we update our dependency to a newer version of Microsoft.Private.CoreFx.NETCoreApp.

**Comment by ericstj** [comment]
Master is building as netcoreapp2.1.  You need to decide if you want WCF to do the same.  If you don't, then use the release/2.0.0 package which is still netcoreapp2.0.

This should have been done back when master stopped flowing code to 2.0.0.

**Comment by StephenBonikowsky** [comment]
We should move to netcoreapp2.1, any reason why we wouldn't?

**Comment by ericstj** [comment]
Only if you had assets targeting 2.0 that you wanted to keep there.  Looking through your repo you are only targeting netstandard and not 2.0 so its OK to move everything (tests) forward.
