### ISSUE TITLE
Offical documnetation on docs.microsoft.com says that no WCF types exist in netcore

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/wcf#2235]
Docs (https://docs.microsoft.com) says that no any WCF exists in .net core!

> The requested page is not available for .NET Core 2.0. You have been redirected to a compatible version.

Just an example: https://docs.microsoft.com/ru-ru/dotnet/api/system.servicemodel.channelfactory?view=netframework-4.7&viewFallbackFrom=netcore-2.0

I understand that server-side WCF isn't implemented on netcore. But client types does exist in `System.ServiceModel.Primitives` packages. But the doc tells nothing about that.

**Comment by zhenlan** [comment]
Thanks for bringing up this issue to my attention @evil-shrike. I am moving this to dotnet/docs repo to follow up.
