### ISSUE TITLE
Missing System.ServiceModel.Configuration.* types

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/wcf#2236]
WCF on netcore is only client-side only implementation, I see. But where are configuration types for getting access to client configuration?

Does WCF on netcore support configuration at all?

**Comment by zhenlan** [comment]
@evil-shrike System.Configuration is not supported on .NET Core so WCF does not have it on .NET Core either.

**Comment by evil-shrike** [comment]
@zhenlan No, It is supported - https://github.com/dotnet/corefx/tree/master/src/System.Configuration.ConfigurationManager
