### ISSUE TITLE
Issue in calling the agent after Referencing .Net 4.5.2 dll WCF SVC Project

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/wcf#2248]
We have referred .Net 4.5.2 dll which is WCF services project and has some SVC services
after making a call to one of classes from the refereed project we are getting the following error

wcf System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0

**Error Stacktrace**
	
![image](https://user-images.githubusercontent.com/3326148/29820939-2d26280c-8c94-11e7-9c66-1634e2fad6c4.png)

**Comment by pardhumeduri** [comment]
could any one please help us in this issue

**Comment by hongdai** [comment]
@pardhumeduri I'm not sure if referencing 4.5.2 dll from your net.core project is supported in your scenario. To verify it, are you able to reference non WCF 4.5.2 dll?

Thanks,
Hong Dai

**Comment by zhenlan** [comment]
@pardhumeduri please let us know if the issue has been solved or need anything from us.
