### ISSUE TITLE
WCF Connectivity Services issue with Registry Access

### ISSUE THREAD

**Issue by pardhumeduri** [dotnet/wcf#2249]
when we click on Connected service and Find more server we are getting the following error

"Access to the registry key 'HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\15.0_bcebb59e\ApplicationPrivateSettings\Microsoft\VisualStudio\Extensions' is denied."

we dont see this "ApplicationPrivateSettings" under 15.0_bcebb59e folder.

![wcfconnectivityissue](https://user-images.githubusercontent.com/3326148/29822578-f6b44154-8c99-11e7-8959-11320d798416.png)

**Comment by hongdai** [comment]
@pardhumeduri This is not a WCF connected service issue. Looks like the connected service framework on your machine is broken somehow. Are you using vs2017? I'd suggest to do a Visual studio Repair.

-Hong Dai

**Comment by pardhumeduri** [comment]
we are able to fix this, issue. thank you
