### ISSUE TITLE
connecting to Microsoft Dynamics NAV ERP System

### ISSUE THREAD

**Issue by ara3n** [dotnet/wcf#2252]
Hello
  When connecting to Microsoft Dynamics NAV ERP, The tool opens a box to enter credentials. After entering credentials it keeps asking for entering credentials and never is able to connect to NAV ERP

 I'm using Dynamics NAV 2017.

This is the error i get when I click cancel.

Metadata contains a reference that cannot be resolved: 'http://localhost:7057/NAV1/WS/Services'.
The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'NTLM'.

**Comment by hongdai** [comment]
@ara3n Sorry to hear that you are running into an issue!

I do not have a Dynamics NAV ERP to reproduce the issue. Could you help by using the full framework tool "Add Service Reference" and let me know your experience?

Thanks,
Hong Dai

**Comment by ara3n** [comment]
Yes i can add full framework tool add service.  It's not available in .net core project.

**Comment by hongdai** [comment]
@ara3n Did the full framework tool ask you entering credential?

**Comment by ara3n** [comment]
No, it uses windows authenication and allows you to see all classes. etc.  
I decided to go with full framework and won't be using .net core project.  You can close this ticket. Thanks.

**Comment by hongdai** [comment]
@ara3n Just a FYI: This is most likely caused by the service uses Disco protocol that Dotnet Core currently does not support. We will evaluate the support.
