### ISSUE TITLE
Deadlock / Timeout when used from Unit Test

### ISSUE THREAD

**Issue by mpetito** [dotnet/wcf#2257]
I've added a WCF service to a .NET Standard 2.0 assembly shared between an ASP.NET Core 2.0 project and an MS Unit Testing project.

I can successfully use the generated clients from an async controller action in ASP.NET Core.  However, I cannot use the generated clients from an async test method. The code is identical in both cases.

This works:

```
public async Task<IActionResult> Index()
{
    var client = new FooClient();
    var results = await client.FooMethodAsync(...);
    ...
    return View();
}
```

This results in a timeout after 20s (presumably because of a deadlock):

```
[TestMethod]
public async Task TestMethod()
{
    var client = new FooClient();
    var results = await client.FooMethodAsync(...);

    Assert.AreEqual(...);
}
```

It seems that I need to add `.ConfigureAwait(false)` to the call for this to work in the unit test.  Is this expected? Or should this call be made internally by the generated client?

**Comment by hongdai** [comment]
@mpetito Please take a look at https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

You should use .ConfigureAwait(false) to avoid deadlock, especially in UI application.

**Comment by mpetito** [comment]
@hongdai It seems like the generated client code should call `ConfigureAwait(false)` for me.

As mentioned in the link you've provided, *library code* should use `ConfigureAwait(false)` and this makes some sense for various reasons.

But I'm not writing library code.  I'm writing a unit test.  I would expect to not have to worry about `ConfigureAwait` since I'm using `async` all the way down.

**Comment by hongdai** [comment]
@mpetito Did you hit the problem if you use command line to launch the unit test(not from UI)? The problem here is the UI thread could deadlock.

As you have mentioned, use ConfigureAwait(false) does not apply for all situations. Thus we do not generate it.

**Comment by mpetito** [comment]
It seems that the deadlock no longer occurs within Unit Tests, even without `ConfigureAwait(false)`.

I wonder if this was fixed in a recent update to Visual Studio 2017?

**Comment by hongdai** [comment]
Close the issue as it no longer reproduce in the latest Visual Studio 2017.
