### ISSUE TITLE
Error while generating source for WSDL

### ISSUE THREAD

**Issue by hmdhasani** [dotnet/wcf#2258]
I am using ASP Core 1.1 and want to add a wsdl.
first I installed 'Microsoft WCF Web Service Reference Provider' Extension and then try to add a wsld from a url that works find in previous version of dot net but in asp core i get this error:

Importing web service metadata ...
Number of services found: 1
Restoring NuGet packages ...
Building solution ...
Scaffolding service reference code ...
Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://servicebus.irica.ir/GetCustomsPermit/v1/']/wsdl:binding[@name='GetCustomsPermitServiceSoapBinding']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://servicebus.irica.ir/GetCustomsPermit/v1/']/wsdl:service[@name='GetCustomsPermitService']/wsdl:port[@name='GetCustomsPermitPort']
Error:Error: No endpoints compatible with .Net Core apps were found.

Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.

I tried both 'Reuse types in references assemblies' to be checked and unchecked but no difference made:

**Comment by hongdai** [comment]
@hmdhasani From the output.config file you shared, it needs message security that dotnet core does not support yet. That's why you get:
Error: No endpoints compatible with .Net Core apps were found.

Thanks,
Hong Dai

**Comment by hmdhasani** [comment]
@hongdai Is there any workaround available?

**Comment by hongdai** [comment]
Unfortunately, there is no workaround available.
