### ISSUE TITLE
App.config '<system.serviceModel>' equivalent in ASPCore

### ISSUE THREAD

**Issue by hmdhasani** [dotnet/wcf#2259]
I want to add a wsdl service to my ASP Core 1.1 app
First I used  'Microsoft WCF Web Service Reference Provider' Extension but got an error that I described it here:
https://github.com/dotnet/wcf/issues/2258

But as a alternative solution I tried to use 'SvcUtil.exe' and successfully generated a .cs file and also a output.config file.

For simplifying the problem first I tried to use these files in a DotNetFramework Console App: after adding .cs file I got lot's of errors due to missing of nuget packages. after searching I added missing nuget packages and also added the output.config <system.serviceModel> content to the App.config and finally successfully connected to that service.

Then I tried this solution for a DotNetCore Console App: I added missing nuget packages but there is no App.config file in DotNetCore apps so was not able to use the config file. Then I run the app and got this error while calling the service:
System.PlatformNotSupportedException: 'Configuration files are not supported.'

Is there any alternative way to config service model for dot net core apps?

**Comment by hmdhasani** [comment]
This is the output.config file that is generated by SvcUtil.exe:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.serviceModel>
        <bindings>
            <customBinding>
                <binding name="GetCustomsPermitServiceSoapBinding">
                    <security defaultAlgorithmSuite="Basic256Sha256Rsa15" authenticationMode="MutualCertificate"
                        requireDerivedKeys="false" securityHeaderLayout="Lax" includeTimestamp="true"
                        messageSecurityVersion="WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10"
                        requireSignatureConfirmation="false">
                        <localClientSettings detectReplays="true" />
                        <localServiceSettings detectReplays="true" />
                    </security>
                    <textMessageEncoding />
                    <httpTransport />
                </binding>
            </customBinding>
        </bindings>
        <client>
            <endpoint address="http://servicebus.ecogif.ir/IRICA/GetCustomsPermit/4"
                binding="customBinding" bindingConfiguration="GetCustomsPermitServiceSoapBinding"
                contract="GetCustomsPermit" name="GetCustomsPermitPort">
                <identity>
                    <dns value="servicebus.ecogif.ir" />
                </identity>
            </endpoint>
        </client>
    </system.serviceModel>
</configuration>

**Comment by hongdai** [comment]
@hmdhasani Dotcore is code based currently. It's not possible to configure it via a configuration file.

**Comment by hmdhasani** [comment]
@hongdai Is there any way to turn the configuration as code?

**Comment by hongdai** [comment]
@hmdhasani Yes, there is an extension point that you can add code to configure the client behavior. Please take a look at the blog: https://blogs.msdn.microsoft.com/webdev/2017/06/28/wcf-web-service-reference-mex-authentication.

**Comment by WeihanLi** [comment]
@hongdai hi, I met the same problem.Is there any method  possible to configure it via a configuration file now?

**Comment by dgroh** [comment]
same here, any workaround? we have legacy services and we need to consume them in out .netcore application

**Comment by opejanovic** [comment]
Same problem here.
@hongdai why this thread is closed? IMHO this is important functionality.

**Comment by opejanovic** [comment]
@dgroh this looks like a workaround https://www.seeleycoder.com/blog/using-wcf-with-dotnetcore/
I did not test it, but looks promising

**Comment by mstrate** [comment]
Possibly this: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x
