### ISSUE TITLE
Microsoft.SyndicationFeed

### ISSUE THREAD

**Issue by nukec** [dotnet/wcf#2260]
Thanks for releasing this.

How do you put custom element inside of SyndicationItem? I have to put some custom element inside of Item element. Is there a way with SyndicationItem or can I only use custom element class?

As well how do you write CData? I used to use `rssFeed.WriteCData` before, how about with SyndicationFeed?

Also I tried to achieve my structure with custom syndicationContent, but I am not sure how do I nest elements?

for example SyndicationContent inside of SyndicationContent? I have to append some attributes in element inside.

**Comment by nukec** [comment]
Ok I resolved adding child with element.AddField(object of other SyndicationContent).

How about CDATA?

**Comment by drago-draganov** [comment]
ISyndicationContent has property Value

**Comment by nukec** [comment]
@drago-draganov i resolved everything I just cannot create element with colon in the name aka:

<element:encoded>, when I try to use AddField("element:encoded") it throws error that special characters are not allowed. How do I resolve this?

**Comment by drago-draganov** [comment]
@nukec 
This is effectively SyndicationContent with namespace. To add such element, you need first to add that namespace to the feed writer. It's supported by passing custom attributes to the writer.

```
//
// Element namespace definition
string elementNamespace = "http://uri_with_element_namespace_definition";

//
// Create writer with custom namespace (prefixed "element")
var writer = new Rss20FeedWriter(xmlWriter, new SyndicationAttribute[] { new SyndicationAttribute("xmlns:element", elementNamespace) };

//
// Create a standard element
var foo = SyndicationContent("foo");

//
// Add child element with namespace
foo. AddField(new SyndicationContent("encoded", elementNamespace, "my_value"));

//
// Write foo
writer.Write(foo); 

```

This will produce 
```
<foo>
   <element:encoded>my_value</element:encoded>
</foo>
```

**Comment by nukec** [comment]
@drago-draganov thanks a lot for that explanation, will sure help people after me as well.

**Comment by drago-draganov** [comment]
Glad it works for you, @nukec 
Appreciate you feedback!

**Comment by nukec** [comment]
@drago-draganov I just tried this and I get `<content xmlns="encoded">` with 
```
var contentElement = new SyndicationContent("content", "encoded", singleContentCData.ToString());
                    item.AddField(contentElement);
```
