### ISSUE TITLE
Unable to create channel when operation is using typed messages with RPC/Encoded

### ISSUE THREAD

**Issue by angeor2** [dotnet/wcf#2264]
I'm trying to consume a service that requires an operation to be attributed with RPC / Encoded. 
This is an example:
`[XmlSerializerFormatAttribute(Style=OperationFormatStyle.Rpc, SupportFaults=true, Use=OperationFormatUse.Encoded)]
PingResponse Ping(PingRequest request);`

When trying to create a channel of a service that implements the above operation I get the SFxTypedMessageCannotBeRpcLiteral error.

This may be due to the XmlSerializerOperationFormatter constructor passing isEncoded as false to the base class constructor (OperationFormatter), instead of using info from xmlSerializerFormatAttribute. 

`public XmlSerializerOperationFormatter(OperationDescription description, XmlSerializerFormatAttribute xmlSerializerFormatAttribute, MessageInfo requestMessageInfo, MessageInfo replyMessageInfo) :
            base(description, xmlSerializerFormatAttribute.Style == OperationFormatStyle.Rpc, false/*isEncoded*/)
        {
            _requestMessageInfo = requestMessageInfo;
            _replyMessageInfo = replyMessageInfo;
        }`

Is RPC/Encoded not supported?

**Comment by zhenlan** [comment]
@angeor2 which version of .NET Core are you using? Can you try out .NET Core 2.0?

**Comment by angeor2** [comment]
@zhenlan The service client is part of a multi-targeting library project (net461;net462;netstandard2.0).
I am testing the code from a netcoreapp2.0 project by referencing the library project.

**Comment by angeor2** [comment]
I created a minimum test case that reproduces the error (netcoreapp2.0):

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.ServiceModel;
using System.ServiceModel.Description;
using System.Threading.Tasks;

namespace System.ServiceModel.Test
{
    [TestClass]
    public class ServiceTest
    {
        [TestMethod]
        public void TestCreateChannel()
        {
            string baseAddress = "http://pingservice.svc";
            BasicHttpBinding binding = new BasicHttpBinding();
            ChannelFactory<IPingServer> factory = new ChannelFactory<IPingServer>(binding, new EndpointAddress(baseAddress));
            var factoryClient = factory.CreateChannel(); // throws exception
            Assert.IsNotNull(factoryClient);
        }


        [ServiceContract]
        public interface IPingServer
        {
            [OperationContract]
            [XmlSerializerFormat(Style = OperationFormatStyle.Rpc, SupportFaults = true, Use = OperationFormatUse.Encoded)]
            PingResponse Ping(PingRequest request);
        }

        public interface IPingServerChannel : IPingServer, IClientChannel { }


        [MessageContract(WrapperName = "PingResponse", IsWrapped = true)]
        public partial class PingResponse
        {
            [MessageBodyMember(Namespace = "", Order = 0)]
            public int @return;
        }

        [MessageContract(WrapperName = "Ping", IsWrapped = true)]
        public partial class PingRequest
        {

            [MessageBodyMember(Namespace = "", Order = 0)]
            public string pinginfo;

            public PingRequest() { }

            public PingRequest(string pinginfo)
            {
                this.pinginfo = pinginfo;
            }
        }

        public partial class PingClient : ClientBase<IPingServer>, IPingServer
        {

            public PingClient() { }

            public PingClient(string endpointConfigurationName) :
                        base(endpointConfigurationName)
            { }

            public PingClient(string endpointConfigurationName, string remoteAddress) :
                    base(endpointConfigurationName, remoteAddress)
            { }

            public PingClient(string endpointConfigurationName, EndpointAddress remoteAddress) :
                    base(endpointConfigurationName, remoteAddress)
            { }

            public PingClient(Channels.Binding binding, EndpointAddress remoteAddress) :
                    base(binding, remoteAddress)
            { }

            public PingResponse Ping(PingRequest request)
            {
                return base.Channel.Ping(request);
            }

        }
    }
}
```

The test fails with error: 

> Message: Test method System.ServiceModel.Test.ServiceTest.TestCreateChannel threw exception: 
System.InvalidOperationException: The operation 'Ping' could not be loaded because it specifies \"rpc-style\" in \"literal\" mode, but uses message contract types or the System.ServiceModel.Channels.Message. This combination is disallowed -- specify a different value for style or use parameters other than message contract types or System.ServiceModel.Channels.Message.

No matter what value of `Use` I enter in `XmlSerializerFormatAttribute` the factory validates against `OperationFormatUse.Literal`

I think this has to do with `XmlSerializerOperationFormatter` passing `false` to base constructor instead of getting that information from the `xmlSerializerFormatAttribute` parameter

```
public XmlSerializerOperationFormatter(OperationDescription description, XmlSerializerFormatAttribute xmlSerializerFormatAttribute, MessageInfo requestMessageInfo, MessageInfo replyMessageInfo) : 
    base(description, xmlSerializerFormatAttribute.Style == OperationFormatStyle.Rpc, false/*isEncoded*/) {
     _requestMessageInfo = requestMessageInfo; _replyMessageInfo = replyMessageInfo; 
}
```

**Comment by zhenlan** [comment]
@shmao any ideas?

**Comment by shmao** [comment]
@angeor2 Thanks for submitting the issue and sharing the repro code. You are right. This is a bug with using `false` instead of the actual `xmlSerializerFormatAttribute.IsEncoded`. I'll look into a fix for this.

**Comment by nmocruz** [comment]
Hi I was hoping that this would be solved in this release 4.4.1, but still ignoring the attribute configuration


https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/PrimitiveOperationFormatter.cs#L43

**Comment by nmocruz** [comment]
Hi, maybe the previous referred line is not the only place commented and setting fixed value for this, but I tried and stil 4.4.1 and still throw and exception about using literal when we set to encode. 
This issue should be reopen

**Comment by zhenlan** [comment]
@nmocruz, the 4.4.1 release is a servicing release to address a particular security issue. This fix of this issue will be part of WCF for .NET Core 2.1 release (package version 4.5.0).

**Comment by nielosz** [comment]
I'm afraid I'm facing this error on latest version (2.1.1, 4.5.3) too. I created the service API with svcutil 1.03 and I'm referencing

    <PackageReference Include="System.ServiceModel.Duplex" Version="4.5.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.5.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.5.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.5.*" />

**Comment by Dedrus** [comment]
I got this error on new netcoreapp2.2 project, and resolved it with update of nuget packages(System.ServiceModel.*) from 4.4.0 to 4.5.3

**Comment by SajithLakjaya** [comment]
Resolved the issue by update of System.ServiceModel.* to 4.5.3
