### ISSUE TITLE
Authentication doesn't work in Web Service Reference Provider

### ISSUE THREAD

**Issue by siberianguy** [dotnet/wcf#2266]
I'm trying to generate code for a service using Web Service Reference Provider but it requires login and password again and again. I checked credentials using the previous version of the tool in VS2015 - it works. I'm not sure what's the problem here: either a bug in the plugin or the service is not compatible with .net core 2 (it's just a guess, I don't see any error messages).

If you'd like to get access to service url and credentials for testing, please email me at alexidsa@gmail.com.

**Comment by hongdai** [comment]
@siberianguy Sorry to hear that you are running into an issue. We will try to repro it locally and investigate the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@siberianguy This is because OData API cannot be added as OData APIs are now only supported with the OData Client Code Generation Tool. Please see https://aka.ms/odatavsclientguidance.

The reason it requires login and password repeatedly is because the service returns the same error code as fail to authenticate.

Thanks,
Hong Dai

**Comment by siberianguy** [comment]
@hongdai Thanks for the feedback! The issue is closed now, does it mean now changes are considered to be necessary? Wouldn't it be nice to have a helpful error message in this not very obvious scenario?

**Comment by siberianguy** [comment]
@hongdai Did you try to access the service I provided you in email using OData Client Code Generation Tool? I get an error "Can not access /serviceurl/". Just curious if it worked for you.

**Comment by hongdai** [comment]
@siberianguy

**Comment by hongdai** [comment]
@siberianguy  Thanks for your feedback to have a helpful error message! I have reopened the issue to track the improvement.

As for access the OData Client Code Generation service, I personally have not tried it. OData team is the right place for the issue.

-Hong Dai

**Comment by siberianguy** [comment]
@hongdai Thanks for your feedback! Agree, OData team are definitely the best fit for this question but they seem to ignore the issues in their repository. If by any chance you or someone in your team have personal connections to OData team, could you please ping them about the issue?

**Comment by hongdai** [comment]
@siberianguy Sure, I will ping OData team.

**Comment by hongdai** [comment]
Close this one as we have an internal bug to track the error message improvement.

**Comment by unchase** [comment]
You can use [Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) for connecting to the OData endpoint with network credentials and proxy (with credentials) as you wish. Just check it!
