### ISSUE TITLE
The eBay Service SDK WSDL doesn't import with Connected Services

### ISSUE THREAD

**Issue by HakanL** [dotnet/wcf#2267]
I'm trying to add the eBaySvc WSDL to my .NET Core 2.0 project. I'm using the Connected Services / WCF tool (version 0.5.10808.800). As I enter the WSDL URL (http://developer.ebay.com/webservices/latest/ebaySvc.wsdl) into the UI and hit Go I'm getting this error:

An error occurred while attempting to find services at 'http://developer.ebay.com/webservices/latest/ebaySvc.wsdl'. The element was not expected in this context: <CallName xmlns='urn:ebay:apis:eBLBaseComponents'>..</CallName>. Expected elements: a couple of namespaces.

Unfortunately this textbox with the error is disabled so you can't select and copy/paste the text so I had to re-type it, there may be typos above (and I omitted all the expected namespaces).

And under the details link:
Metadata contains a reference that cannot be resolved: 'http://developer.ebay.com/webservices/latest/eBaySvc.wsdl'.
There is an error in XML document (11, 8).

This is obviously an established WSDL which imports fine (I assume) in the full frameworks.

**Comment by hongdai** [comment]
@HakanL Sorry to hear that you are running into an issue!

I have tried both full framework "Add Service Reference" and svcutil.exe. They both failed with similar reasons.

**Comment by HakanL** [comment]
I found out that there seems to be a complete syntax error in the WSDL that eBay provides, I found extra elements in the middle of the file. If I remove those extra elements then I can import it fine with svcutil (a bunch of warnings about xs:any elements, but it generates the cs files), however in the WCF Core import it aborts the import due to those warnings. So maybe that's something to address?

**Comment by hongdai** [comment]
@HakanL Yes. WCF Core aborts the import when there are schema validation errors. Ideally services should fix those validation errors. Since many customers do not own services and many of the validation errors can be successfully ignored, we have decide to ignore all validation errors. The change is in the next release.

Thanks,
Hong Dai

**Comment by HakanL** [comment]
Cool. With that clarification we can probably close this issue, or rename, as it was determined the issue is with eBay (except the validation error change)

**Comment by landlogicit** [comment]
Solution for this issue: https://stackoverflow.com/a/48025793
