### ISSUE TITLE
the service at the folowing uri does not have any valid endpoints

### ISSUE THREAD

**Issue by qinxiaowen** [dotnet/wcf#2270]
uri:https://localhost:9443/services/AuthenticationAdmin?wsdl
wsdl content:
[wsdl_text.txt](https://github.com/dotnet/wcf/files/1278192/wsdl_text.txt)
the wsdl belong to a java identityserver project .
the service is localhost https,but it dont have a valid certificate.

**Comment by hongdai** [comment]
@qinxiaowen I've got some import errors as the wsdl file depends on some other schema files that I do not have access.

Could you try to generate the full wsdl by using `?singleWsdl` ?

Thanks,
Hong Dai

**Comment by qinxiaowen** [comment]
@hongdai no singleWsdl,
the wsdl can use normal in traditional .net framwork add service reference dialog.
so i think the problem is still the tool issue.
![111](https://user-images.githubusercontent.com/8536046/30092584-4dd8f32c-92f2-11e7-9057-1767138922db.PNG)
![222](https://user-images.githubusercontent.com/8536046/30092593-613aac58-92f2-11e7-88d7-3fc7b5874167.PNG)

**Comment by hongdai** [comment]
@qinxiaowen Could you generate the .cs file and output.config using the framework svcutil.exe and share them to me? It could give me a clue why it does not find any valid endpoint.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@qinxiaowen Closing it as there is no response for 21 days. Please reactive if needed.

**Comment by timjkelly** [comment]
@qinxiaowen 
Has anyone solved this issue? I am getting this when trying to generate .Net Core compatible code.

**Comment by qinxiaowen** [comment]
@timjkelly  sorry,i didn't resolve the problem, i am using .net framework project now.

**Comment by hongdai** [comment]
@timjkelly The root cause for the "the service at the following uri does not have any valid endpoints" could be very different. If you have a different service, could you open a new issue?

Thanks,
Hong Dai
