### ISSUE TITLE
Cannot import wsdl:binding in .NET Core 2 console app

### ISSUE THREAD

**Issue by Rodske** [dotnet/wcf#2271]
I'm trying to use a WCF service in a .NET Core 2 console app. Any ideas on how to resolve the following....? The url is https://authentication.business.gov.au/R3.0/vanguard/S007v1.2/Service.svc

Warning: Cannot import wsdl:binding
Detail: An exception was thrown in a call to a policy import extension.
Extension: System.ServiceModel.Channels.SecurityBindingElementImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice']/wsdl:binding[@name='S007SecurityTokenServiceEndpoint']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice']/wsdl:service[@name='SecurityTokenService']/wsdl:port[@name='S007SecurityTokenServiceEndpoint']
Error:Error: No endpoints compatible with .Net Core apps were found.

Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.

**Comment by hongdai** [comment]
@Rodske This is because the service uses TransportWithMessageCredential binding and Dotnet core does not currently support Message security.

Thanks,
Hong Dai

**Comment by Rodske** [comment]
Are there any workarounds I could do? Is there an associated release number for when .NET Core might support this on the roadmap?

**Comment by hongdai** [comment]
Unfortunately there is no workaround available, and we do not have estimation when it will be supported in .Net Core.
