### ISSUE TITLE
Unable to copy status box contents on WCF Web Service Reference wizard's Service Endpoint tab

### ISSUE THREAD

**Issue by colinbowern** [dotnet/wcf#2272]
# Summary
I hit an error trying to create a reference for the Oracle NetSuite SOAP endpoint. In the Configure WCF Web Service Reference dialog on the Service Endpoint tab I cannot select the text in the Status box, nor can I resize it to be able to capture the entire error.

# Steps to Reproduce
1. Create a new .NET Core standard library project, add a connected service using the WCF Web Service Reference Provider
2. Use the following Uri: https://webservices.netsuite.com/wsdl/v2017_1_0/netsuite.wsdl
3. Try to click the Status text box to copy the error contents

# Actual Result
Unable to select text to copy the error or resize the box to screenshot.

# Expected Result
Ability to select the text and copy it to share with someone for help in resolution.

# Environment
Visual Studio Community 15.3.3
WCF Web Service Reference Provider - 0.5.10808.800
Windows 10 Enterprise Inside Preview (16281)

**Comment by hongdai** [comment]
@colinbowern Thanks for reporting the issue to help improve the tool! We will evaluate the fix.

-Hong Dai

**Comment by hongdai** [comment]
@colinbowern This is fixed in the next release.
