### ISSUE TITLE
Instance and dialect has Metadata property whose type does not match the dialect

### ISSUE THREAD

**Issue by colinbowern** [dotnet/wcf#2273]
# Summary
I hit an error trying to create a reference for the Oracle NetSuite SOAP endpoint using the WCF Web Service Reference Provider in a .NET Core or .NET Standard Class Library. It does work on a Windows Classic Desktop Class Library, however, using Add Service Reference. Same WSDL can also be consumed by SoapUI.

# Steps to Reproduce
1. Create a new .NET Core standard library project, add a connected service using the WCF Web Service Reference Provider
2. Use the following Uri: https://webservices.netsuite.com/wsdl/v2017_1_0/netsuite.wsdl
3. Click Go

# Actual Result
![image](https://user-images.githubusercontent.com/192707/30093398-32ed20ac-9319-11e7-885d-feff8b24b655.png)

# Expected Result
Proxy is generated.

# Environment
Visual Studio Community 15.3.3
WCF Web Service Reference Provider - 0.5.10808.800
Windows 10 Enterprise Inside Preview (16281)

**Comment by hongdai** [comment]
@colinbowern This is the same issue of #2197. Thanks for reporting the issue! It will help us evaluate the support for Disco.

-Hong Dai

**Comment by colinbowern** [comment]
@hongdai Thanks for flagging. I did search before posting, but must have used the wrong keywords. 😄  

How should we progress this issue - close as a won't fix hoping that the scenario will be kept in mind, open another Disco feature request issue to track the need, or leave it open?

**Comment by hongdai** [comment]
I will close it as a dup of issue #2197. We will keep the original one open to track the Disco feature request.
