### ISSUE TITLE
Enable Certificate related tests in CI For linux platforms

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#2275]
OSX CI is skipping certificate related tests because root certificate cannot be installed. We have discussed it long time ago and conclude that we should ensure all certificate related test get run regardless whether there are set up issues. 

We should:
1. fix the root certificate issue on CI.
2. Add flags to always run them.

**Comment by hongdai** [comment]
Since we have never enforced certificate related tests in the CI, we will do it in two stages to ensure CI PR run stability.

- [X] 1. Check in change to enable all nightly CI runs ONLY.
- [ ] 2. Discover issues with nightly runs and fix them.
- [ ] 3. Switch to PR runs only after the nightly runs are green for one week.

I have checked in the changes for step 1).

**Comment by hongdai** [comment]
Nightly runs found that some of the Linux OSes did not get detected. I have fixed it today. 
https://github.com/dotnet/wcf/pull/2344

Next step: wait for a few days. If all nightly runs are green, we can enable CI.

**Comment by zhenlan** [comment]
@hongdai has this been done for CI?

**Comment by hongdai** [comment]
@zhenlan Not yet, I've checked the nightly runs, it has been green for over a week. I will enable the CI today.

**Comment by zhenlan** [comment]
Thanks!

**Comment by hongdai** [comment]
CI is enabled now.
