### ISSUE TITLE
WCF Connected Extension fails to generate partial class from WSDL

### ISSUE THREAD

**Issue by JonahHexx** [dotnet/wcf#2279]
When I generate a proxy using the old wsdl.exe the resulting code contains a partial class which is used by our existing codebase. The new connected service generator does not include this class.
The missing class is the actual service based on the service name in the wsdl.

The section of the wsdl that defines the class is as shown (URL obfuscated):

	<wsdl:service name="CallcreditBsb7">
		<wsdl:documentation>The CallcreditBsb7 service is the fundamental gateway through which the entire functionality of the BSB api is exposed.</wsdl:documentation>
		<wsdl:port name="Soap11" binding="tns:Soap11">
			<soap:address location="https://xx.xxxx.co.uk/Services/Bsb/Bsb7.asmx"/>
		</wsdl:port>
		<wsdl:port name="Soap12" binding="tns:Soap12">
			<soap12:address location="https://xx.xxxx.co.uk/Services/Bsb/Bsb7.asmx"/>
		</wsdl:port>
	</wsdl:service>

Why is this class not being generated?

**Comment by hongdai** [comment]
@JonahHexx Sorry to hear that you are running into an issue!

The section of the wsdl file does not have enough information to identify the root cause. Could you share the full wsdl file to reproduce the issue locally?

Thanks,
Hong Dai

**Comment by JonahHexx** [comment]
Here you go
[Bsb7Full.zip](https://github.com/dotnet/wcf/files/1293877/Bsb7Full.zip)

**Comment by hongdai** [comment]
@JonahHexx wsdl.exe is a legacy technology as you might know. It does not generate WCF client that the WCF Connected extension generates. 

I can use the wsdl you provided to generate WCF client successfully. 

`public partial class SoapClient : System.ServiceModel.ClientBase<Soap>, Soap
`

SoapClient is the class you need to use to make service calls.

Hope it helps,
Hong Dai

**Comment by JonahHexx** [comment]
Thanks for the help

**Comment by hongdai** [comment]
Assume the issue is resolved. Please reopen if further help is needed.
