### ISSUE TITLE
Bridge should allow requests from only one IP

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#228]
The Bridge needs a start-up parameter to identify the single IP it will accept requests from.

**Comment by SajayAntony** [comment]
I'm curious if we just lock it down to localhost and we configure this through something like this

``` 
curl -F "allowclient=172.30.169.104" http://localhost:5050/config
```
basically configure can be called only from localhost. I personally don't want to litter code with parameter passing.

**Comment by roncain** [comment]
Closing because Bridge infrastructure no longer exists
