### ISSUE TITLE
The solution does not build

### ISSUE THREAD

**Issue by trichling** [dotnet/wcf#2280]
I am facing the problem that when I try to add a service reference to a project containig .NET Core (Target .NET Framework 4.6.1) Web Apis with full framework class library projects suddenly I get the error that the solution does not build. When I do a rebuild in VS it builds just fine. I also tried nuking bin / obj manually, closing VS, re-installing the extension but nothing worked so far.

I apologize that I am not able to produce better repro steps, but nothing indicates the kind of error. If there is some kind of diagnostics tool I would be glad to give you all the information I need. 

Currently I use a blank solution as a workaround: when I generate my reference there I can safely copy it over into my productive solution.

Thanks,
Tobias.

**Comment by hongdai** [comment]
@trichling Sorry to hear that you are running into an issue!

Could you share the repro *.csproj file? We will try to reproduce the problem locally and investigate the root cause.

Thanks,
Hong Dai

**Comment by trichling** [comment]
Hi Hong Dai,

Thanks for your immediate reply. Here is the content of the project file:

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\net461\win7-x86\apetito.FreshAndFrozen.Api.Basket.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\net461\win7-x86\apetito.FreshAndFrozen.Api.Basket.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot/Views\Baskets\basketsStylescss.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Connected Services\" />
    <Folder Include="Views\Baskets\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="1.2.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.4" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\apetito.FreshAndFrozen.Domain.Model.Basket\apetito.FreshAndFrozen.Domain.Model.Basket.csproj" />
    <ProjectReference Include="..\apetito.FreshAndFrozen.Infrastructure\apetito.FreshAndFrozen.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\PPInternetArticle.Designer.cs">
      <DependentUpon>PPInternetArticle.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\PPInternetBaskets.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PPInternetBaskets.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\PPInternetOnlineOrder.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PPInternetOnlineOrder.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\PPInternetArticle.nl.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PPInternetArticle.resx">
      <LastGenOutput>PPInternetArticle.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PPInternetBaskets.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>PPInternetBaskets.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PPInternetOnlineOrder.nl-NL.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PPInternetOnlineOrder.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PPInternetOnlineOrder.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>

I hope this gets you closer to the root caus.

Thanks,
Tobias Richling


IT | apetito AG

Bonifatiusstraße 305 | 48432 Rheine

T +495971 7999886 | M +49151 72425805 | F +495971 79979886 | E Tobias.Richling@apetito.de | I https://www.apetito.de/


apetito gehört zu den TOP 100 Unternehmen "Deutschlands BESTE Arbeitgeber" 2015
 [cid:image001.gif@01D32B94.25F12070]

 Bitte prüfen Sie, ob diese Email wirklich ausgedruckt werden muss.





Von: Hong Dai [mailto:notifications@github.com]
Gesendet: Dienstag, 12. September 2017 06:53
An: dotnet/wcf <wcf@noreply.github.com>
Cc: Tobias Richling (thinkexception) <tobias.richling@thinkexception.net>; Mention <mention@noreply.github.com>
Betreff: Re: [dotnet/wcf] The solution does not build (#2280)


@trichling<https://github.com/trichling> Sorry to hear that you are running into an issue!

Could you share the repro *.csproj file? We will try to reproduce the problem locally and investigate the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@trichling I can use a similar project to repro the issue, but only the first time do a clean build.

The build error is from "GenerateDepsFile" 
`"\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(94,5): error MSB4018: System.ArgumentException: Can not add property System.ServiceModel.Duplex to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object."`

You can remove the below package references as they no longer needed in the most recent version of the tool:
<PackageReference Include="System.ServiceModel.Duplex" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />

Your problem should go away by removing those package references.

Thanks,
Hong Dai

**Comment by trichling** [comment]
@hongdai I tried your suggestion. However when I remove the references you pointed to, I get teh following error on build:

CS0012	The type 'Claim' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	

in the references.cs:

```
  private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://services/myservice.svc"), **new System.ServiceModel.DnsEndpointIdentity("localhost"));**
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
```
The problem is the new System.ServiceModel.DnsEndpointIdentity. I can not find a Nuget package that holds the System.IdentityModel.dll, only System.IdentityModel.Tokens.Jwt - which is already referenced.

Is this because I am trying to update an existing service reference?

It seems to me that I need to keep the reference 

    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />

around. Having this I can build the project. But still I can not update my service reference (by trying to add it to the same namespace as the existing reference).

Greetings,
Tobias.

**Comment by hongdai** [comment]
@trichling For System.IdentityModel, Could you try adding the full framework reference as below:

`  <Reference Include="System.IdentityModel" />
`

Also, it seems like you are trying to **update** your existing service reference. We currently do not support this feature. We are evaluating the support and your feedback is helpful.

Thanks,
Hong Dai

**Comment by trichling** [comment]
Hi,

I read in your FAQ that One could try to Just regenerate to update. But even when I delete the service reference first it fails. Will be in the office again on Monday and try your suggestions. Will give you feedback then.

Greetings,
Tobias

Von meinem iPhone gesendet

Am 13.09.2017 um 18:42 schrieb Hong Dai <notifications@github.com<mailto:notifications@github.com>>:


@trichling<https://github.com/trichling> For System.IdentityModel, Could you try adding the full framework reference as below:

<Reference Include="System.IdentityModel" />

Also, it seems like you are trying to update your existing service reference. We currently do not support this feature. We are evaluating the support and your feedback is helpful.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
Closing it as no response for 14 days. Please reactive if there are more questions.
