### ISSUE TITLE
WSHttpBinding

### ISSUE THREAD

**Issue by dazinator** [dotnet/wcf#2288]
I am looking at upgrading an old code base on github: https://github.com/ayende/rhino-licensing to use wcf for netstandard2.0.

It uses `WSHttpBinding` - I can't find this anywhere yet - is there a migratioin path for this?
It also decorates its service with `ServiceBehavior` attribute - i can't seem to resolve this  - which package do I need for that?

**Comment by zhenlan** [comment]
Hi @dazinator WSHttpBinding is currently not supported on .NET Core.

Duplicate of #31
