### ISSUE TITLE
error when adding vimService.wsdl "The service at the following URI does not have any valid endpoints"

### ISSUE THREAD

**Issue by smartmaster** [dotnet/wcf#2294]
- download "Microsoft WCF Web Service Reference Provider" from https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService
- install the VS extension
- when adding vimService.wsdl, it reports error "The service at the following URI does not have any valid endpoints"

the wsdl files are attached.
[vimService.zip](https://github.com/dotnet/wcf/files/1313972/vimService.zip)

**Comment by hongdai** [comment]
@smartmaster Sorry to hear that you are running into an issue! We will try to repro locally and identify the root cause.

**Comment by hongdai** [comment]
@smartmaster  I confirm this is the same issue as #2269. Please use #2269 to see the workaround and tracking resolution.

Thanks,
Hong Dai
