### ISSUE TITLE
Request to port WSSecurityTokenSerializer

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#2298]
I am using the WSSecurityTokenSerializer class to serialize tokens in a WS-Trust implementation on the client side. Is there any chance that you would port that class over to .net core? I'm mainly interested in the Write* methods.

**Comment by zhenlan** [comment]
Hi @atanasa, this is blocked by #31.

**Comment by StephenBonikowsky** [comment]
track with #31
