### ISSUE TITLE
ReceiveContext Abandon method dont send the Exception to client

### ISSUE THREAD

**Issue by Pavel-Ishutin** [dotnet/wcf#2323]
Hi,

The class System.ServiceModel.Channels.ReceiveContext has 2 virtual methods Abandon with the following signatures:

public virtual void Abandon(TimeSpan timeout)
{
    Abandon(null, timeout);
}

public virtual void Abandon(Exception exception, TimeSpan timeout)
{
      // code is omitted
      // in brief

      if (exception is null)
           OnAbandon(timeout);
      else
           OnAbandon(exception, timeout);
}

and 2 protected methods with the following signatures:

protected abstract void OnAbandon(TimeSpan timeout);

protected virtual void OnAbandon(Exception exception, TimeSpan timeout)
{
    OnAbandon(timeout);  // here the exception is lost
}

All derived types, in particular System.ServiceModel.Activation.HostedAspNetEnvironment+ReceiveContextBusyCountWrapper, 
override only the abstract method OnAbandon.

We use our implementation of the class ReceiveContext. 
As we have found, the method ReceiveContext.TryGet(messageProperties, out receiveContext) returns different "receiveContext" while hosting in Console App and IIS or IIS Express. 
While it is hosting in IIS Express, it is ReceiveContextBusyCountWrapper which only contains OnAbandon(TimeSpan timeout) and the error that needs to be sent to the client is lost.

Code sample here: [https://drive.google.com/file/d/0B367m1Fw-w9rX3dFSXhyaXBhUVE/view?usp=sharing](url).

Why ReceiveContextBusyCountWrapper and all derived types from ReceiveContext does't overrides a method OnAbandon(Exception, TimeSpan)?

Best Regards,
Pavel

**Comment by zhenlan** [comment]
@Pavel-Ishutin thanks for reporting the issue. This appears to be about the full framework. As this repo is for .NET Core, I am closing this issue.

I have routed this issue internally for further investigation. In the future, please use https://connect.microsoft.com/ for any issues related to the full framework.

cc: @jcondex
