### ISSUE TITLE
System.AccessViolationException when installing extension in Visual Studio 2017

### ISSUE THREAD

**Issue by normanhuang** [dotnet/wcf#2328]
Hello, I've been experiencing issues installing the extension. Upon clicking on the vsix installer, a brief popup message shows that it is initializing but it quickly dissappears and nothing happens next. Upon loading Visual Studio and using .NET Core 2.0, I still cannot see the WCF Service option within the Connected Services Tab. Upon checking the error log, it looks like the installation failed:
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at VSIXInstaller.SettingsManager.GetRegRootFromManager(IntPtr)...

Is this a known issue and how do I solve it? Thanks.

**Comment by hongdai** [comment]
@normanhuang This is a vsix installer issue. Please open a problem in https://developercommunity.visualstudio.com/spaces/8/index.html.

Thanks,
Hong Dai
