### ISSUE TITLE
Investigate threading related test failure caused by updated dependencies.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2329]
PR #2305 is failing a test consistently. Some dependency may have broken how we expect threading to work. Needs investigation...

     TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread [FAIL]
14:40:19         System.AggregateException : One or more errors occurred. (Expected continuation to happen on thread 12 but actually continued on thread 10
14:40:19         Expected: True
14:40:19         Actual:   False)
14:40:19         ---- Expected continuation to happen on thread 12 but actually continued on thread 10
14:40:19         Expected: True
14:40:19         Actual:   False
14:40:19   ---ETW Trace for Test TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread Begins---
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: ChannelFactory created .
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: ServiceChannel asynchronous calls started.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Client request serialization started.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Client completed serialization of the request message.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: ServiceChannel Open Start.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: ServiceChannel Open Stop.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: TextMessageEncoder started encoding the message.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Created new 'TextBufferedMessageWriter'
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Pool allocating 512 Bytes.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Pool allocating 1024 Bytes.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Pool allocating 1024 Bytes.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: A message with size '564' bytes was written by the encoder.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: TextMessageEncoder started decoding the message.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Created new 'UTF8BufferedMessageData'
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: A message with size '404' bytes was read by the encoder.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Client started deserializing the reply message.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: Client completed deserializing the reply message.
14:40:19   TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread: The Client completed executing Action 'http://tempuri.org/IWcfService/Echo' associated with the 'IWcfServiceGenerated' contract. The message was sent to 'http://localhost:8081/DefaultCustomHttp.svc//default-custom-http'.
14:40:19   ---ETW Trace for Test TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread Ends---
14:40:19   
14:40:19         Stack Trace:
14:40:19               at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
14:40:19               at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
14:40:19               at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
14:40:19            D:\j\workspace\outerloop_sel---847ea45c\src\System.Private.ServiceModel\tests\Scenarios\Client\TypedClient\TypedProxyTests.4.0.0.cs(188,0): at TypedProxyTests.ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread()
14:40:19            ----- Inner Stack Trace -----
14:40:19            D:\j\workspace\outerloop_sel---847ea45c\src\System.Private.ServiceModel\tests\Scenarios\Client\TypedClient\TypedProxyTests.4.0.0.cs(195,0): at TypedProxyTests.<>c__DisplayClass13_0.<<ServiceContract_TypedProxy_Task_Call_WithSyncContext_ContinuesOnSameThread>b__1>d.MoveNext()
14:40:19            --- End of stack trace from previous location where exception was thrown ---
14:40:19               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
14:40:19               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:40:19            D:\j\workspace\outerloop_sel---847ea45c\src\System.Private.ServiceModel\tests\Common\Scenarios\ScenarioTestTypes.cs(247,0): at TestTypes.SingleThreadSynchronizationContext.Run(Func`1 asyncMethod)
14:40:19               at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
14:40:19               at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
14:40:19   Finished:    Client.TypedClient.Tests

**Comment by StephenBonikowsky** [comment]
This is really strange, it only fails on "Selfhost Windows_NT Release" not on Debug or any other variation including IIS Hosted on Windows.

@mconnew @zhenlan before I go into this.....any ideas?

**Comment by mconnew** [comment]
This isn't us, this is something broken in coreclr. I've opened dotnet/coreclr#14367 to track this. I verified that the Task we return isn't created from a TaskCompletionSource which has any options set that could cause this. We just use the default options which should honor the sync context and/or any task schedulers.

**Comment by StephenBonikowsky** [comment]
@mconnew looks like @stephentoub fixed this with dotnet/coreclr#14369 but the test still failed in the most recent update to the auto-update PR #2305

I'll double check that the fix is actually in the package version being updated in the PR.

**Comment by stephentoub** [comment]
That coreclr build is from four days ago.  My change was three days ago.

**Comment by StephenBonikowsky** [comment]
Ah, thanks Stephen, just figured out the same thing.
Seems strange, I thought each PR would trigger a new build which would update the Versions repo, I guess we'll see it come down the pike shortly.

**Comment by StephenBonikowsky** [comment]
It looks like this has been fixed.
