### ISSUE TITLE
Add connecting service fails: It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by blair55** [dotnet/wcf#2340]
I have Visual Studio Preview 15.5 installed on win10.

Steps:
New Project > Visual C# > .NET Core > ASP.NET Core Web Application
Right Click Connected Services > Add Connected Service > MS WCF Web Service Reference Provider
Enter Uri: `https://webservice.s6.exacttarget.com/etframework.wsdl`
Click Go

Output:
```
Importing web service metadata ...
Number of services found: 1
Restoring NuGet packages ...
Building solution ...
Scaffolding service reference code ...
Error:It was not possible to find any compatible framework version
Error:The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
Error:  - Check application dependencies and target a framework version installed at:
Error:      \
Error:  - Alternatively, install the framework version '1.0.4'.
Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.
```

**Comment by zhenlan** [comment]
Hi @blair55, thanks for reporting the issue. This is a known issue. As a workaround, can you please install ".NET Core 1.0-1.1 development tools" via the Visual Studio Installer? This issue has been fixed and will be available in the next update.

**Comment by blair55** [comment]
Thanks @zhenlan, I can work with that. When should I expect the new update?

**Comment by zhenlan** [comment]
It will be in next update for VS 15.5, so it won't be too long (weeks).

**Comment by zhenlan** [comment]
The fix has been released yesterday in the new preview of VS 15.5 [27019.01.d15rel].

**Comment by COLEplusTEN** [comment]
I get this error in 15.5.3.

**Comment by lenglengOMG** [comment]
I get this error in 15.7.4.  : (
