### ISSUE TITLE
Change URL address (how to configure endpoint for production).

### ISSUE THREAD

**Issue by 4gDad** [dotnet/wcf#2342]
I'm using the Visual Studio WCF Connected Service addon in my asp.net core project. I from my webapi I am calling an .asmx webservice.  I want to pull change the url address from my test system to my production code.  Based on my searching I am attempting to do this with this line of code 

            cvWebService = new PCWSSoapClient(PCWSSoapClient.EndpointConfiguration.PCWSSoap12);
            
            cvWebService .Endpoint.Address = new EndpointAddress("https://123.Production.com/PC/PCWS.asmx");

Is this the correct method because,even though I can browse to the asmx my webapi calls fail.

Thankyou

**Comment by mlacouture** [comment]
Hi @4gDad!

The recommended way to configure your endpoint from your code is to implement the partial method that is generated in the reference.cs file:

    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

You can then change the service endpoint address.

Hope this helps,
Miguel Lacouture

**Comment by mlacouture** [comment]
BTW: the generated code also offers you a constructor for your service client that receives an EndpointAddress type.

However, it seems your server requires authentication, based on the server address which uses SSL (https), in this case my previous recommendation is the way to go as you can set the credentials in the ClientCredentials parameter passed to it.

**Comment by zhenlan** [comment]
@4gDad Please let us know if you have any further questions. Closing for now.

**Comment by affableashish** [comment]
> Hi @4gDad!
> 
> The recommended way to configure your endpoint from your code is to implement the partial method that is generated in the reference.cs file:
> 
> ```
> static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
> ```
> 
> You can then change the service endpoint address.
> 
> Hope this helps, Miguel Lacouture

Hi @mlacouture ,
Can you please provide an example?

So I created this new file to call new `Your_Reference_Service_Client(uriBasedOnEnvironment)`, but I can't use non-static field `_uriBasedOnEnvironment` inside static method `ConfigureEndpoint`.
````
namespace Your_Reference_Service_Namespace
{
    public partial class Your_Reference_Service_Client
    {
        private readonly string _uriBasedOnEnvironment;

        public Your_Reference_Service_Client(string uriBasedOnEnvironment)
        {
            _uriBasedOnEnvironment = uriBasedOnEnvironment;
        }

        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials)
        {
            serviceEndpoint.Address =
                new System.ServiceModel.EndpointAddress(new System.Uri(_uriBasedOnEnvironment),
                new System.ServiceModel.DnsEndpointIdentity(""));
        }
    }
}
````

Am I even doing this right? Can you please provide a complete example?
Thanks!
