### ISSUE TITLE
Http CertValMode ChainTrust failed on some linux platform because  issue #1295 

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#2346]
Test case: HttpsTests.Https_SecModeTrans_CertValMode_ChainTrust_Succeeds_ChainTrusted 

Http CertValMode ChainTrust failed on some linux platform because issue #1295 . However, this test should not involve custom handling of certificates.

**Comment by zhenlan** [comment]
When ManagedHandler is available, it should help this issue.

**Comment by zhenlan** [comment]
ManagedHandler (renamed to socket hander) is not available in 2.1.
