### ISSUE TITLE
Need to add a service with two endpoints, but exclude one of the endpoints

### ISSUE THREAD

**Issue by jgraff26** [dotnet/wcf#2347]
I have a service that contains two endpoints.  I have a client that wants to use just the methods in one of the endpoints.  If I use Visual Studio Add Service Reference, both endpoints and all their methods are imported.  Looking at the GUI for this it appears that I can select which endpoints I would like, but both get imported regardless of what I select.  This would be my preferred method.

To get around this issue I looked into using svcutil to just import the endpoint that I would like.  It appears the /et switch should allow me to exclude the endpoint that I don't want.  None of the variations I've tried worked, a question to several forums verified my results.  Can I use either Add Service Reference or svcutil and create a service reference for just one endpoint in a multi-endpoint service?

For example

namespace a.b.c 
 { 
    public interface InterfaceToExclude
    { 
      [OperationContract] 
      bool MethodToExclude()

my service definition is

public class MyService: InterfaceToExclude, InterfaceToInclude
 {

 so would the /et switch be

1) /et:a.b.c.InterfaceToExclude   or

2) /et:a.b.c.InterfaceToExclude.MethodToExclude

sadly neither of these two options actually caused the generated .cs code to exclude the first endpoints interfaces, methods or data definitions.

my current svcutil command is

svcutil /target:code   http://machine.domain/path/MyService.svc /language:CS /et:a.b.c.InterfaceToExclude

Thanks!

**Comment by mlacouture** [comment]
Hi @jgraff26 

Thank you for reporting this issue.  What you are trying to do is currently not possible as the tool generates client code for all endpoints a service exposes.

We will evaluate adding this feature in a future release.

regards,
Miguel Lacouture

**Comment by mlacouture** [comment]
This would require significant changes in the Metadata processing API which has a high risk of introducing regressions.
