### ISSUE TITLE
WCF objects disposed but GC is not triggered

### ISSUE THREAD

**Issue by Olafski** [dotnet/wcf#2351]
I'm probably doing something wrong, but not sure what...

I have an ASP.NET Core solution which calls a few WCF Connected services through a NetTcp binding. I noticed that with every service call, the heap gains thousands of objects (XmlDictionaryString, XmlName, FaultContractInfo et cetera) which are then never released. After a few minutes, the memory usage of the process is at 3GB (from 100MB near the start). I stopped my tests at that point but I assume the usage will increase further.

When I call GC.Collect(), the memory usage goes back to 100MB. This indicates to me that the objects are in fact disposed, but not garbage collected. The debugger also does not indicate that any GC is being done.

Is this normal and should I just accept that the memory will keep going up until .NET Core considers it necessary to run a GC, or should I keep looking into this?

Here's a screenshot of the memory profiler, if that helps:
https://i.imgur.com/aBwvLri.jpg

Update 2 days later. We've managed to narrow this down a bit. When switching from the NetTcp binding to BasicHttp, the problems disappeared. I changed nothing else, and the memory remained stable around 130 MB. When changing back to NetTcp the memory usage grows with every call again.

**Comment by mconnew** [comment]
@Olafski, NetTcp binding uses the binary message encoder and BasicHttp uses the text message encoder. I believe that the text message encoder doesn't use XmlDictionaryString as it doesn't maintain a session dictionary. So 2 things have changed. The transport and the encoder. Can you try with NetHttpBinding which uses the binary message encoder and see if the problem still occurs?

**Comment by mconnew** [comment]
@Olafski, I took another look at your memory profiler screenshot and there's something very interesting. It's showing 624 instances of some types which I would only expect a single instance of per ChannelFactory. I'm going to attempt a little party trick here and guess how you wrote your code. You used the WCF Connected Services VS extension to create your client. Your coding pattern is to create a new instance of that client, maybe call Open on it, then make a call or calls, then call Close/Dispose and do the same again. The problem is the generated client doesn't cache the ChannelFactory as we don't have configuration any more and each new instance of your client will create a new ChannelFactory. If this is the case, then the solution is quite simple. Create a static instance of your client and call `mySingleClient.ChannelFactory.CreateChannel()` every time you need a new client. Don't forget to cast to ICommunicationObject and call Close when you're done with the created channel.

**Comment by Olafski** [comment]
Thanks a lot @mconnew, you were exactly right. I changed the implementation according to your suggestions, and it's a lot better now.

Just one more question though, if I may. In the snapshots, I see the amount of memory used by the heap going down. However, in task manager I still see the amount of memory used growing. I assume this is alright, but I can't explain it. Can you?

Here's a screenshot with the profiler, showing the results of using CreateChannel: https://i.imgur.com/RZFfQFs.jpg

**Comment by mconnew** [comment]
Task Manager shows your private working set. This is the amount of memory your app has asked for and hasn't been paged out. It's not the amount of memory your app is actually using. To keep things easier, I'll talk about 32-bit apps. 65-bit is the same but uses bigger numbers. Each process has it's own 4GB address space which various things can be mapped into. For example, you could map the contents of a file to a portion of the address space. The thing which is usually mapped though is RAM. So when a process needs some memory, it asks the OS to allocate some. The process then takes a contiguous portion of the process address space and marks that range as being used to map RAM. It doesn't actually map any RAM to it at this point though. Then the process will commit memory, which means "I actually need to read and write data to this allocated address space". So for example, if a process asks the OS to allocate 200MB for memory usage, it might map and return you the address at the 1GB mark. Then when the process needs to use some, it will commit a certain amount. E.g. it might need to use 10MB of it. The OS will then allocate real memory pages to the first 10MB of the address space. If the app uses the entire 10MB, it might go back and ask for the next 20MB, at which point the addresses from 1GB to 1GB + 30MB will all have real RAM mapped to them. If the process then reduces it's memory usage such that the top 10MB of the committed memory are no longer needed, it can uncommit the last 10MB of committed memory. So then only 20MB is really mapped to real memory. The reason things are done like this is it allows the application to have a contiguous range of address space and just needs to know how much has been allocated. If it did the allocation and commit at once, then the process would need to keep track of multiple addresses and abstract things like array accesses as an array might need to be split over two non-contiguous ranges of address space. The CLR heap grows and shrinks with allocation and GC compaction and will proactively uncommit unused memory pages. Without doing this, if there's any memory pressure and swapping to a swapfile occurs, you would end up writing out pages to disk which you don't need as there's nothing currently stored in them. The GC allocates memory in segments. Once a segment is full, the segment is retired and nothing else is stored there. As objects get cleaned up the segment gets emptied out and at some point any remaining objects will get compacted (i.e. moved) to a different segment. The CLR also doesn't allocate really big segments straight away, it tunes what size segments are needed as the process executes. So while the GC is warming up and is finding an equilibrium, you will size the private working set increase even though the heap size may be smaller. Also I think the GC might de-allocate some spare segments if there's memory pressure but if there's no pressure, it keeps some spare. So the short answer is that the question "how much memory is my process using" depends on what you mean by "using" and different mechanism to examine usage will mean different things. If this is a concern, then run your app for a longer period of time and make sure it does reach an equilibrium. This might take a few minutes of your app actively doing things. Also those numbers should be too far out if there is memory pressure, i.e. your system starts swapping to disk. If you have memory to spare, processes/the OS tend to be a little wasteful in allocation to improve performance, but tighten this up if memory is in short supply.

**Comment by Olafski** [comment]
Wow, case closed I would say.

Thanks again @mconnew !

**Comment by drdamour** [comment]
@mconnew  know i'm doing evil thread zombie stuff here...but is there a reason the channel factory you mentioned is ChannelFactory<IService>  and not ChannelFactory<IServiceChannel> as IService often does not implement ICommunicationObject but IServiceChannel does (from svcutil proxy generation)?
