### ISSUE TITLE
Test Case Failure: BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2353]
This is the first time running all the tests in a long time for release/1.0.0 with all the necessary infrastructure changes to get it building in VSO.

Not sure if this is a legitimate failure but it has been here all along, I don't want to block the PR https://github.com/dotnet/wcf/pull/2352 for one test failure.

ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed
     ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed [FAIL]
15:13:04         System.TimeoutException : The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
15:13:04         ---- System.TimeoutException : The HTTP request to 'http://wcfcoresrv2.cloudapp.net/WcfService104//BasicHttp.svc//Basic' has exceeded the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout.
15:13:04         Stack Trace:
15:13:04               at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__35.MoveNext()
15:13:04            --- End of stack trace from previous location where exception was thrown ---
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
15:13:04               at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__34.MoveNext()
15:13:04            --- End of stack trace from previous location where exception was thrown ---
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
15:13:04               at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
15:13:04               at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
15:13:04               at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
15:13:04               at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
15:13:04               at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
15:13:04               at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
15:13:04               at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
15:13:04            --- End of stack trace from previous location where exception was thrown ---
15:13:04               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:13:04               at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
15:13:04               at generatedProxy_5.EchoStream(Stream )
15:13:04               at ServiceContractTests.BasicHttp_DefaultSettings_Echo_RoundTrips_String_Streamed()
15:13:04            ----- Inner Stack Trace -----
15:13:04               at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
15:13:04            --- End of stack trace from previous location where exception was thrown ---
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:13:04               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
15:13:04               at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__35.MoveNext()
15:13:04   Finished:    Contract.Service.Tests

**Comment by zhenlan** [comment]
@StephenBonikowsky, which platform this test is failing on?

**Comment by StephenBonikowsky** [comment]
Only on OuterLoop Ubuntu14.04 Debug 
Not on Release, I am really close to getting VSO test builds, I would like to see results from there in order to make sure it isn't just a Jenkin's lab issue that doesn't happen in the Helix lab.

**Comment by zhenlan** [comment]
@mconnew is looking into this test.

**Comment by mconnew** [comment]
I'm not seeing this test fail. I am seeing BasicHttp_Abort_ChannelFactory_Operations_Active fail saying it's getting the wrong exception. The test is failing because it is expecting TaskCanceledException and it's getting CommuicationObjectAbortedException. This test in later branches has been modified so this isn't an issue.

**Comment by zhenlan** [comment]
@StephenBonikowsky can you please double check and close this issue if the test is not failing anymore?

**Comment by StephenBonikowsky** [comment]
branch 1.0.0 is back up and running, will check and see if this test is still an issue.

**Comment by StephenBonikowsky** [comment]
The test is not failing anymore.
