### ISSUE TITLE
Asmx support (WCF connected service)

### ISSUE THREAD

**Issue by learn9969** [dotnet/wcf#2355]
Unfortunately I need to be able to call an old asmx webservice from an asp.net core web api 2.

Is it possible to use this tool for old asmx webservices.

Any sample out there?

**Comment by mlacouture** [comment]
Hi @learn9969 
I'm assuming you are talking about the WCF Web Service Reference connected service provider tool.  This tool supports web services that follow the WSDL specification and ASMX is a technology for building this type of services, so the answer is yes, you should be able to use this tool to add a service reference to your project.
You can read more about the [tool usage here](https://github.com/dotnet/wcf/blob/master/Documentation/WCF-Web-Service-Reference-guide.md
).
Hope this helps,
Miguel Lacouture

**Comment by learn9969** [comment]
Hi thanks for your reply but the link does not show how  you call the service once generated.Can you provide an example
thanks

**Comment by mlacouture** [comment]
Hi!

The generated proxy code contains a System.ServiceModel.ClientBase derived class which is your service's client.  You can then invoke the methods on an instance of this type that will communicate with your server.

regards,
Miguel

**Comment by zhenlan** [comment]
@learn9969 below is an example of code you can write by using the `ServiceReference1.Service1Client` that is generated by the WCF Connected Service. This code is calling against a service generated from "WCF service application" VS template where it has a service operation named `GetData(int)`.

```
        static void Main(string[] args)
        {
            ServiceReference1.Service1Client client = new ServiceReference1.Service1Client(ServiceReference1.Service1Client.EndpointConfiguration.BasicHttpBinding_IService1);
            try
            {
                var result = client.GetDataAsync(5).Result;
            }
            catch (Exception ex)
            {
                Console.WriteLine("error");
            }
         }
```
