### ISSUE TITLE
WCF CS fails when Merging/Importing Multiple WSDLs into one

### ISSUE THREAD

**Issue by oruchreis** [dotnet/wcf#2357]
Hi,
We are using `<import>` definition for merging multiple wsdl locations like that:
```xml
<definitions name="XXXServices"  targetNamespace="https://xxx/schema/"  xmlns="http://schemas.xmlsoap.org/wsdl/">
  <import namespace="https://xxx/schema/Service1" location="https://service.com/Service1?wsdl" />
  <import namespace="https://xxx/schema/Service2" location="https://service.com/Service2?wsdl" />
...
</definitions>
```

When we use old "Add Service Reference" tool, everything works smoothly. But when we use WCF connected services tool, we get `The MetadataExchangeClient has resolved more than MaximumResolvedReferences.`. If I remove some of imported locations, then I got a lot of warnings like that:
`Warning:Warning: There was a validation error on a schema generated during export:
   Validation Error: The complexType 'https://xxx/schema/core/:SomeType' has already been declared.`
And this process takes very long. Updating service reference is so slow.

**Comment by mlacouture** [comment]
Hi @oruchreis 

thank you for reporting this issue.  Would it be possible for you to provide the wsdl/schema files for us to investigate? thanks,

**Comment by zhenlan** [comment]
@oruchreis please let us know if you can share more information. Closing for now.
