### ISSUE TITLE
Reading AXIS wsdl error with Microsoft WCF Web Service Reference Provider

### ISSUE THREAD

**Issue by Tecnico1** [dotnet/wcf#2360]
When I try to read wsdl from "http://www.axis.com/vapix/ws/action1/ActionService.wsdl", there is not problem with Visual Studio 2015, but with the new tool ("Microsoft WCF Web Service Reference Provider") for Visual Studio 2017 I never get a response, always with "Please wait..." message.

**Comment by mlacouture** [comment]
Hi @Tecnico1 

Thank you for reporting this issue.  This is the same problem as discussed in issue #2104. Please use issue #2104 to track progress

Miguel Lacouture

**Comment by mlacouture** [comment]
Duplicate of #2104
