### ISSUE TITLE
Performance problemn calling wcf service with BasicHttpBinding

### ISSUE THREAD

**Issue by eduardoluizm** [dotnet/wcf#2361]
Hi, 

Currently I have a web application made with asp.net core 1.1 and hosted on azure app services by net461.

This app has some classes created by svcutil.cs.

So, after the release we had some problemas with performance but after change some configs, like "ServicePointManager.DefaultConnectionLimit = 100;", no more problems.

Last week, we started to migrate it to asp.net core 2.0 compiled by netcoreapp 2.0. I created all classes from wsdl again, and our binding configuration is:

![image](https://user-images.githubusercontent.com/3385836/32064903-f7121d5e-ba59-11e7-9120-68796feb89d7.png)

Exactly the same old configuration, except by the added line "ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max".

An example for created wsdl to c# class.
![image](https://user-images.githubusercontent.com/3385836/32064617-1cd53b94-ba59-11e7-91e0-36c094df53e4.png)

Well, when I published it to production, it worked very well, but after many people trying to connect, a lot of errors happened in a period, only on WCF call's. 100 calls OK.. 20 NOK.. then.. 150 OK.. 15 NOK..

Error:
![image](https://user-images.githubusercontent.com/3385836/32065134-9dd7aa50-ba5a-11e7-8b9e-34fbd58a067d.png)

On azure I'm connecting to Application Gateway and every problem on wcf returns 502 (Bad gateway). It ocurrs only on netcoreap2.0. If compiled by net461 nothing happens.

**Comment by zhenlan** [comment]
Hi @eduardoluizm, it's a bit hard to tell what went wrong here with Application Gateway. Do you think you can troubleshoot and get a bit more details?

https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-troubleshooting-502

**Comment by zhenlan** [comment]
@eduardoluizm please let us know if you can get more details. Close for now.
