### ISSUE TITLE
System.ServiceModel.Channels.StandardBindingImporter

### ISSUE THREAD

**Issue by BrettKoenig** [dotnet/wcf#2367]
Is this method not implemented or supported yet? Any timeline to when it will be? Thanks!

**Comment by zhenlan** [comment]
@BrettKoenig this type is not available in .NET Core. Can you please share with us your use case?

**Comment by zhenlan** [comment]
@BrettKoenig Please let us know if you have further information. Closing for now.

**Comment by JasonJCross** [comment]
Hi @zhenlan! I'm trying to upgrade our framework wcf service (WCF service not under our control) and this is one of the issues I get connecting the Service. Including here as it seemed related to @BrettKoenig comment. If incorrect location, please advise. :)

Error Details:
Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='CustomBinding_IImportService']

Thanks!
Jason
