### ISSUE TITLE
Service Reference creating error in .net standard 2.0

### ISSUE THREAD

**Issue by CodyLuck** [dotnet/wcf#2369]
I trying to create WCF Wev service reference in .net standard 2.0 project. In process i`ve got error
![error](https://user-images.githubusercontent.com/26362826/32656611-8c6d9106-c623-11e7-90ca-bb59569d3942.PNG)

I rebuilt project to .net standard 1.3, created service reference and successfull rebuilt it back to 2.0, but it seems to me, that it is not good solution. I coun`t find any information, that service is not supported by .net standard 2.0. Visual Studio 2017 15.4.3. 
How can I solve the problem?

**Comment by mlacouture** [comment]
Hi @CodyLuck 

Thank you for reporting this issue.  The [WCF Web Service Reference](https://github.com/dotnet/wcf/blob/master/release-notes/WCF-Web-Service-Reference-notes.md) connected service tool is now part of Visual Studio 2017 starting with the [v15.5 Preview 1](https://blogs.msdn.microsoft.com/visualstudio/2017/10/11/visual-studio-2017-version-15-5-preview/) release and a fix for this issue is available with this release, I hope you can install this preview so you can get unblock and please let us know if you hit any other problems.

thanks again
Miguel Lacouture
[MSFT]

**Comment by zhenlan** [comment]
BTW, @CodyLuck, from the error, looks like you are not even updated to the last build we released on [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=WCFCORETEAM.VisualStudioWCFConnectedService#overview). We have added 2.0 support for a while. But as @mlacouture said, please consider upgrading to VS 15.5 to get our latest bug fixes/features.

**Comment by CodyLuck** [comment]
Hello. Installed VS 15.5 and problem became worse. Now service reference are not created on any .net standard project. Plugin, which creates service reference doesn`t see any wcf services in solution, but easily creates on .net framework projects.
![normasreference](https://user-images.githubusercontent.com/26362826/32888607-de4cc1b8-cad8-11e7-8965-d5eb8fd4a2b5.PNG)

Plugin doesn`t see wcf services in solution and can`t connect by URI
![createany](https://user-images.githubusercontent.com/26362826/32888623-e8954fc8-cad8-11e7-89da-670e4a29d64b.PNG)

![createappl](https://user-images.githubusercontent.com/26362826/32888629-eb4748ca-cad8-11e7-81ca-8efd299c3030.PNG)

**Comment by mlacouture** [comment]
Hi @CodyLuck 

It seems you hit a different issue which is the WCF connected service cannot start the local WCF host (IIS Express) and for which we have a fix to be available in the Visual Studio 2017 15.6 Preview 1 release.  You can work around this problem by manually starting the WCF host: right click the service file (<filename>.svc) in the corresponding project and select 'View in Browser' option, then try adding the service reference again.
Please let us know if this is helpful and if you still see the error you originally reported.

thank you!
Miguel Lacouture
