### ISSUE TITLE
WCF Code Generation on Visual Studio 2017 is broken!!! (incorrect service name?)

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2376]
I downloaded the Fedex  and UPS Rate Client API and spent hours trying to find the client classes after using add service.  It was there, but buried in a gigantic steaming pile of digital mush.  Both were named RatePortTypeClient..    Why didn't you use the service names?  Whose brilliant idea was it to change it for no good reason? 

```
**Fedex**
<portType name="RatePortType">
    <operation name="getRates" parameterOrder="RateRequest">
        <input message="ns:RateRequest" />
        <output message="ns:RateReply" />
    </operation>
</portType>
  <service name="RateService">
    <port name="RateServicePort" binding="ns:RateServiceSoapBinding">
      <s1:address location="https://wsbeta.fedex.com:443/web-services/rate" />
    </port>
  </service>

**UPS**
<wsdl:portType name="RatePortType">
    <wsdl:operation name="ProcessRate">
        <wsdl:input name="RateRequest" message="tns:RateRequestMessage"/>
        <wsdl:output name="RateResponse" message="tns:RateResponseMessage"/>
        <wsdl:fault name="RateError" message="tns:RateErrorMessage"/>
    </wsdl:operation>
</wsdl:portType>

	<wsdl:service name="RateService">
		<wsdl:port name="RatePort" binding="tns:RateBinding">
			<!-- Production URL -->
			<!-- <soap:address location="https://onlinetools.ups.com/webservices/Rate"/> -->
			<!-- CIE (Customer Integration Environment) URL -->
			<soap:address location="https://wwwcie.ups.com/webservices/Rate"/>
		</wsdl:port>
	</wsdl:service>

```

**Comment by mlacouture** [comment]
Hi @Joebeazelman 

Thank you for your feedback.  Can you be more specific about what's broken? is it the naming convention that you are not ok with? if so, it is the same naming convention <servicename+client> for the generated client used by other service reference generation tools from Microsoft, all these tools use the same runtime code base.  The 'client' part is added to the service name to compute the client class name as the generated class inherits from `System.ServiceModel.ClientBase<>`.

Hope this helps,

Miguel Lacouture
[MSFT]

**Comment by Joebeazelman** [comment]
No.  No.  The old version generated the correct name for the client, RateService.  No one ever complained about it and it worked. The new implementation is  not based on the Service name "RateService." It generates RatePortTypeClient, which makes no sense.  Did you guys get my wsdl files?

**Comment by mlacouture** [comment]
@Joebeazelman, I'll take a second look as soon as I have a chance ...

**Comment by mlacouture** [comment]
@Joebeazelman I tried the FedEx RateServiceDefinition.wsdl and both tools, the Add Service Reference (ASR) tool for .Net Framework projects and the WCF Web Service Reference (WCF CS) tool for .Net Core projects, generate code with the same naming convention, here my generated client classes:

ASR:
` [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RatePortTypeClient : System.ServiceModel.ClientBase<ConsoleApp20.ServiceReference2.RatePortType>, ConsoleApp20.ServiceReference2.RatePortType { ...
`
WCF CS:
`   [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class RatePortTypeClient : System.ServiceModel.ClientBase<ServiceReference2.RatePortType>, ServiceReference2.RatePortType
`

Can you confirm what tools you are using and verify the client classes?  

thank you!
