### ISSUE TITLE
Reference.svcmap (ASR) is utterly useless in VS 2017

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2377]
Apparently, there's supposed to be some nice client code customization features , but they're hidden away like everything else in WCF.  Microsoft believes your safety is more important than your productivity.  The Reference,svcmap is has the following options for changing how the code is generated:

```
<?xml version="1.0" encoding="utf-8"?>
<ReferenceGroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ID="707be5ca-d777-4610-ba5b-2ed0f78e7bb7" xmlns="urn:schemas-microsoft-com:xml-wcfservicemap">
  <ClientOptions>
    <GenerateAsynchronousMethods>false</GenerateAsynchronousMethods>
    <GenerateTaskBasedAsynchronousMethod>true</GenerateTaskBasedAsynchronousMethod>
    <EnableDataBinding>false</EnableDataBinding>
    <ExcludedTypes />
    <ImportXmlTypes>false</ImportXmlTypes>
    <GenerateInternalTypes>false</GenerateInternalTypes>
    <GenerateMessageContracts>true</GenerateMessageContracts>
    <NamespaceMappings />
    <CollectionMappings>
      <CollectionMapping TypeName="System.Collections.ObjectModel.ObservableCollection`1" Category="List" />
    </CollectionMappings>
    <GenerateSerializableTypes>false</GenerateSerializableTypes>
    <Serializer>Auto</Serializer>
    <UseSerializerForFaults>true</UseSerializerForFaults>
    <ReferenceAllAssemblies>true</ReferenceAllAssemblies>
    <ReferencedAssemblies />
    <ReferencedDataContractTypes />
    <ServiceContractMappings />
  </ClientOptions>
  <MetadataSources>
    <MetadataSource Address="E:\Software\ShipQuote\_Carriers\RateServiceDefinitions.wsdl" Protocol="file" SourceId="1" />
  </MetadataSources>
  <Metadata>
    <MetadataFile FileName="RateServiceDefinitions.wsdl" MetadataType="Wsdl" ID="083d6c48-1931-48b9-a05d-55c8f12e5329" SourceId="1" SourceUrl="file:///E:/Software/ShipQuote/_Carriers/RateServiceDefinitions.wsdl" />
  </Metadata>
  <Extensions>
    <ExtensionFile FileName="configuration91.svcinfo" Name="configuration91.svcinfo" />
    <ExtensionFile FileName="configuration.svcinfo" Name="configuration.svcinfo" />
  </Extensions>
</ReferenceGroup>
```

I changed some of these options, but couldn't figure out why they had no effect on the generated output.  I kept the svcmap open in VS2017 and without reason or warning, all my changes in the client options were ignored and reverted to their default state!  It didn't even ask me nicely if I want to reload the file as VS normally does with a file is updated externally.

Is Microsoft trying to frustrate and confound their developers into abandoning the Windows platform?  If so, you guys are doing a great job at it.

**Comment by mlacouture** [comment]
@Joebeazelman the reference.svcmap file is not intended for manual updates, it is used by the 'Add Service Reference' tool to be able to update the project when requested.

It seems that what you want to do is to update your service reference and the way to do that is by selecting the 'Add Service Reference' option from the project references item's context menu.

Hope this helps,
Miguel Lacouture

**Comment by zhenlan** [comment]
Just add a note, reference.svcmap is generated by the conventional "Add service reference" tool, which is not for .NET Core.

**Comment by ManojPatelA** [comment]
@zhenlan , @mlacouture It seems there is no use of Reference.svcmap at runtime. Is there a way we can exclude them with build output directory ? For my case copy to output directory is selected but whenever I build the code I see them all under "Service References" folder. Is there a way to exclude them ?
