### ISSUE TITLE
Server Support

### ISSUE THREAD

**Issue by wasabii** [dotnet/wcf#2378]
Not sure where else to put this.

On a lark I did a server-side ASP.Net integration for WCF. It provides middleware that spawns up a `ServiceHost` and routes requests into it. The promise is of the full WCF stack working (for HTTP).

https://github.com/wasabii/Cogito.AspNetCore.ServiceModel

I have it working for basic POST requests with text encoding. Using it is fairly simple:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddServiceModel();
}
        
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseServiceHost<MathService>("/math", configure =>
    {
        configure.AddServiceEndpoint<IMathService>("");
        configure.AddServiceEndpoint<IMathService>("/2");
    });
}
```

I'm going to keep working on it. But, I was thinking, this should be owned by somebody else.

Do any more official sources want to take a hold of this? I'd be happy to turn it over.

This is a little more advanced than just spawning up a `ServiceHost` listening on matching endpoints. There's a router infrastructure. Custom `ChannelListener` and `ReplyChannel`. And a weird service-endpoint abstraction to get it all to work (`aspnetcore://guid/relativeuri`).

But work it does.

Long term I can imagine this (or something like it) being the integration point between ASP.Net Core and WCF. And then, slowly weening it off the full framework as stuff becomes available in Core: ServiceHost, the other server components, etc.

I stuck a package in NuGet if anybody wants to try it out. It's pretty easy. Create a ServiceContract and impementation, and use the code above to register it on a URL path. And that's it.

**Comment by wsnell** [comment]
Cool... What is the name in NuGet and do you have documentation with it?  Can I use it in a console based .NET Core app (not ASP .net core)?
Thanks

**Comment by wasabii** [comment]
https://www.nuget.org/packages/Cogito.AspNetCore.ServiceModel/0.1.0-unstable0035

It requires the full framework. It's real WCF.

**Comment by zhenlan** [comment]
@wasabii what you did is very interesting. However, as you noticed, the support of WCF server side on core is pending the decision of #1200, so I am closing this issue at this point.

**Comment by dotnetchris** [comment]
WCF over http is borderline pointless, the real transports of WCF are in-memory/namedpipes, TCP, queues, and service bus communication. While i appreciate the effort in showing you can use WCF in some scenarios on Core we shouldn't be encouraging anyone to develop for http with WCF.

If full WCF isn't going to be built, what would be more valuable would be a straight forward way to make anything an ASP.NET controller that you can apply action filters to get the AOP that brings, that you pass by serialization between "controllers" using in-memory transport. That's the problem with ASP.NET, all of its expressiveness and AOP power dies the moment you hit the action method body. 

With WCF its trivial to have everything as a service that you can leverage AOP, out of band context sharing, and pass by serialization.

Until you can put an "ActionFilter" on any method. Until you can put a "MessageInspector" on any method and tamper with incoming or outgoing data transparently. None of this even scratches the surface of why WCF really matters.

**Comment by ccicchitelli** [comment]
@dotnetchris I totally agree. Your example of the MessageInspector is a good one. We use that to implement custom auth. We have a custom key in the request that is checked when the request is received. The MessageInspector itself is called from BehaviorExtensionElement to enable cross origin resource sharing. 

All in all it's this kind of power with services that is missing from .NET Core right now (AFAIK), and why I'm surprised that WCF isn't planned for inclusion at this time.
