### ISSUE TITLE
WCF client code generator is inconsistent depending on the project type.

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2380]
I've been spending the past couple of days trying to find out why WCF cannot generate quality code for my UWP project.  I decided to assist you guys in locating these issues, I've enclosed a zip files of the metadata I am using to generate my client.  Aside from the inability to charge the code generation options, it failed to include DataContracts defined in UPSSecurity.xsd.  

The code generates perfectly using a standard .NET project.  On .NET Core it generates near perfect code except some odd naming which I already posted about.  Finally, on UWP, it is a complete disaster!  I would expect UWP to have a larger code coverage than .NET Core.  

[Web Service Metadata.zip](https://github.com/dotnet/wcf/files/1469630/Web.Service.Metadata.zip)

**Comment by mlacouture** [comment]
@Joebeazelman 

Thank you for your feedback.  

This GitHub repository is explicitly for WCF in .Net Core Framework.  Although we sometimes might be able to help with WCF issues for other frameworks it is not always possible.  

In this case your feedback about the issues you are experiencing with your UWP project need to be tracked with a separate system internally and I'll make sure to reroute this issue to the UWP team.  Alternatively you can report the issue using the [Visual Studio feedback](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool.

Miguel Lacouture
[MSFT]
