### ISSUE TITLE
Can I consume .net WCF service in .net core ?

### ISSUE THREAD

**Issue by prasadmamidi7** [dotnet/wcf#2382]
Hi

Can some one tell whether we can consume .net WCF service in .net core 2.0 ?

.net WCF service 
---------------
- WCF duplex service published using netTcpBinding and wsDualHttpBinding

I want to consume this service in asp.net core .
 Is It possible and how 
 If not what are the current limitations.

**Comment by Joebeazelman** [comment]
I am assuming you want to build a client to talk to a preexisting WCF service.  Make sure you are using Visual Studio 2017.  Although the article is discussing WCF soap services, it should work the same.  The extension will generate code that gets compiled into a client you can call.  Here's the article:

https://medium.com/@narinkaew/using-wcf-soap-services-in-net-core-fb13180c4eda

**Comment by mlacouture** [comment]
Hi @prasadmamidi7 

Yes, as @Joebeazelman mentioned (thank you very much), the [WCF Web Service Reference](https://github.com/dotnet/wcf/blob/master/Documentation/WCF-Web-Service-Reference-guide.md) connected service is the tool you are asking for.  Please let us know if you hit any problems.

thanks,
Miguel Lacouture
[MSFT]

**Comment by prasadmamidi7** [comment]
Hi mlacouture

I was specifically looking for consuming WCF **duplex** service published using wsDualHttpBinding 

I need to make a decision whether we can use asp.net core 2.0 as technology for our new project. As part of it I need to understand the support for consuming the WCF services. Can you please answer below questions.

1) WCF Web Service Reference tool is not generating client code for wsDualHttpBinding and where I can find an example and documentation
2) Can I create client proxy using code approach ?
2) Is there any documentation like MSDN provides for WCF
3) Does it support all features of WCF .net from client perceptive.
4) What are the current limitation and where I can find upcoming changes.

thanks,
Prasad Mamidi.

**Comment by mlacouture** [comment]
@prasadmamidi7, `WSDualHttpBinding` is not yet supported in the .Net Core Framework, refer to [WCF features in .Net Core 2.0](https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v2.0.0.md) for the latest feature set; and the GitHub documentation for the [WCF Web Service Reference](https://github.com/dotnet/wcf/blob/master/Documentation/WCF-Web-Service-Reference-guide.md) for more information.

**Comment by sturlath** [comment]
This seems to be the place to as a similar question (hope I´m right).
 
But it´s more of **how do I configure my code** to be able to talk to a WCF service? I have asked this at [StackOverflow ](https://stackoverflow.com/questions/48625444/calling-a-soap-service-in-net-core) if you are interested in more details. 

When I connect to this WCF service using "old" .net 4.6.2 and config it works just fine but when I try it in .net core C# I get the the following exception because of something I doing wrong in my C# code but I just can´t find out what it is.

> An error occurred while receiving the HTTP response to https://someurl.com/ws/Thing.pub.ws:Something. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.

I have tried everything I can think off without luck also I find it almost impossible to find good examples on this topic.

**Comment by dasjestyr** [comment]
So, this isn't even coming up in search results in Extensions and Updates. Did something change?

**Comment by sonicmouse** [comment]
I am assuming the extension is dead? How are we to talk to an existing SOAP WCF service via ASP.NET Core 2?

**Comment by sturlath** [comment]
Take a look at my answer (to my question) on this subject https://stackoverflow.com/a/48660543/1187583 hope that it will help

**Comment by sonicmouse** [comment]
OK, so it's moved to Nuget: https://github.com/dotnet/wcf

Thanks!

**Comment by mlacouture** [comment]
The [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide) is part of Visual Studio 2017 v15.5 and higher.

**Comment by dmitry-pavlov** [comment]
**Workaround**, for anyone (using `Visual Studio 2017 - v15.8.0 Preview 1.1`) who is trying to understand why it fails with _**`Failed adding Microsoft WCF Web Service Reference Provider to the project.`**_ error on adding `WCF` reference to `ASP.NET Core 2.1` project - it can be added via `.NET Standard` class library. See the details here https://github.com/dotnet/docs/issues/5703
