### ISSUE TITLE
There's no way to update your client code in WCF .NET Core once it has been generated.

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2383]
Sigh...  Again, Microsoft masterfully lets me down.  Although the code generates with a fewer hiccups, you have delete client code and add it again.  Why is this broken?  This has nothing to do with .NET Core!  It's a just a tool that interfaces with VisualStudio and doesn't involve .NET core.

**Comment by mlacouture** [comment]
Hi @Joebeazelman, the "service reference update" feature in the WCF Web Service Reference connected service will be available with Visual Studio 2017 15.6 Preview 1 which is scheduled to be released in less than a month.

**Comment by zhenlan** [comment]
Duplicate of #1753
