### ISSUE TITLE
WCF Core does not provide control over HTTP Header KeepAlive using HttpTransportBindingElement

### ISSUE THREAD

**Issue by slavah** [dotnet/wcf#2389]
Hi, we need to be able control KeepAlive header.
For example, when connecting to IP camera through ONVIF (SOAP based) protocol, we need to remove KeepAlive header in request.
Functionality required is similar to classical WCF implementation:  [HttpChannelFactory.cs](https://github.com/Microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/Channels/HttpChannelFactory.cs
)

Here a PR with suggested implementation:
[https://github.com/dotnet/wcf/pull/2370](https://github.com/dotnet/wcf/pull/2370)

In case WCF Core has a different approach to solve this - please point me in right direction.

Thank you.

**Comment by zhenlan** [comment]
@mconnew can you please review this?
