### ISSUE TITLE
Cannot find WCF service endpoint in a project containing WCF service (.NET 4.61) and client (.NET Core 2.0) - Discover feature broken

### ISSUE THREAD

**Issue by wsnell** [dotnet/wcf#2401]
Cannot find WCF service endpoint in a project containing WCF service (.NET 4.61) and client (.NET Core 2.0), using latest WCF Connected Service Generator tool built into 15.5 Preview 2.
I would expect for it to search the solution looking at all projects and find my service for import.  Instead it cannot find anything and the only way for me to find the service is to run the service and brose for it by IP address and full connection string.  This is a pain.
Please fix.

**Comment by mlacouture** [comment]
Hi @wsnell 

Thank you for reporting this issue. I'm glad to let you know that we have a fix for this issue which will be available with the release of Visual Studio 15.6 Preview 1 sometime in December.

Miguel Lacouture

**Comment by mlacouture** [comment]
[Visual Studio 2017 15.6P1](https://blogs.msdn.microsoft.com/visualstudio/2017/12/07/visual-studio-2017-version-15-6-preview/), check it out!
