### ISSUE TITLE
.NET Core 2.0 WCF client is unable to use a secure connection with a WCF .NET Full service

### ISSUE THREAD

**Issue by wsnell** [dotnet/wcf#2404]
.NET Core 2.0 WCF client is unable to use a secure connection with a WCF .NET Full service.  I don't think all of the pieces are there.  Or maybe you simply need to write up documentation how to do this along with sample code.

**Comment by zhenlan** [comment]
Hi @wsnell, WCF on .NET Core does support a variety of security and authentication features. Please refer to our 2.0 supported features document below for a complete list. If you have any specific issue, please open an issue accordingly with details.

https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v2.0.0.md
