### ISSUE TITLE
dotnet-svcutil generates incorrect interface method (.NET Core 2.0 and Duplex NetTcpBinding issue)

### ISSUE THREAD

**Issue by amodi2** [dotnet/wcf#2407]
I have a .NET Core 2.0 WCF client that is talking to an .NET 4.5 WCF service that uses NetTcpBinding with Duplex callbacks. I have followed all the instructions (and used the WCF connected service plugin to generate the client code). Everything works fine and I am able to make calls to the service, except for the fact that I only get one callback from the server and after that my client is waiting forever to receive the second callback. The server gets the following exception:

_The client was unable to process the callback request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from CallbackBehaviorAttribute or from the <clientDebug> configuration behavior) on the client in order to send the exception information back to the server, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the client trace logs._

Can you please guide as to what I may be missing or doing wrong?

Here is the service configuration for the binding:

      <netTcpBinding>
        <binding name="duplexTcpNoReliableSessionKrb" sendTimeout="03:00:00" transferMode="Buffered"
        receiveTimeout="03:00:00"
        transactionProtocol="OleTransactions" maxBufferPoolSize="104857600"
        maxBufferSize="655360000" maxConnections="5000" listenBacklog="1000" maxReceivedMessageSize="655360000"
        portSharingEnabled="false">
          <readerQuotas maxStringContentLength="655360000" maxArrayLength="655360000"
            maxBytesPerRead="655360" />
          <reliableSession inactivityTimeout="03:00:00" enabled="false" />
          <security mode="Transport">
            <transport clientCredentialType="Windows" protectionLevel="Sign" />
            <message clientCredentialType="Windows" algorithmSuite="Basic128" />
          </security>
        </binding>
      </netTcpBinding>

**Comment by zhenlan** [comment]
@amodi2 could you please share a repro with us so we can take a further look?

**Comment by zhenlan** [comment]
@amodi2 please let us know when you have an update.

**Comment by amodi2** [comment]
After spending some time on troubleshooting and trying to reproduce this issue, I finally found the root-cause! The SvcUtil was generating the wrong interface for my callback contract. The callback contract was supposed to return void, but the auto-generated contract had a dummy OnDataAvailableResponse class which for some reason would work fine for the first callback, but hang for the second one.

This was the auto-generated contract code generated by SvcUtil:

  [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IUniqeCallback
    {        
        [OperationContractAttribute(Action="http://www.intel.com/IUniqe/OnDataAvailable", ReplyAction="http://www.intel.com/IUniqe/OnDataAvailableResponse")]
        OnDataAvailableResponse OnDataAvailable(OnDataAvailableSolicit request);
    }

whereas it should have been the following (returning void without a ReplyAction defined):

  [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IUniqeCallback
    {
        [OperationContractAttribute(Action="http://www.intel.com/IUniqe/OnDataAvailable")]
        void OnDataAvailable(OnDataAvailableSolicit request);
    }

Once I fixed this and made appropriate code changes to my client, everything is working fine for me. This was essentially a SvcUtil.exe bug!

**Comment by zhenlan** [comment]
Thanks for sharing more details, @amodi2. I am reopening this issue.

@mlacouture, can you take a look?

**Comment by dasetser** [comment]
@amodi2 I know this issue is pretty old, but is there any way you could share the wsdl for the service with us? If not could you provide the full file that dotnet-svcutil generated as well as what svcutil generates for the same service? As of now we don't have enough information to determine why it would have generated the incorrect return type.

**Comment by dasetser** [comment]
Let me know if you can provide the information I asked for so we can investigate this issue.
