### ISSUE TITLE
Azure ServiceBus/WCF Relay Binding

### ISSUE THREAD

**Issue by bsmithb2** [dotnet/wcf#2411]
Hi,

I'm currently trying to integrate with an Azure Service Bus Relay implementation with dotnet core WCF, and I can't work out  how to implement the TransportClientEndpointBehaviour so I can add the SAS Token Provider. 

Also, I can'tcreate a TCPRelay Binding or a HTTPRelayBinding to connect up like we've done in the past in the .net framework. 

Is there any advice or suggested examples and reading that I can use? 

Thanks in advance! Bsmithb2

**Comment by zhenlan** [comment]
@bsmithb2 this won't work on .NET Core because WCF needs message security feature from System.IdentityModel, which is not available on .NET Core.

**Comment by sanjaybhagia** [comment]
Do we have any update on this? I think this is still not supported yet?
