### ISSUE TITLE
.Net Framework 4.7.1 not supported by wcf reference provider

### ISSUE THREAD

**Issue by akhilesh78** [dotnet/wcf#2415]
Visual Studio 2017
ASP.NET **Core** MVC project
Target: .NET Framework 4.7.1

Importing web service metadata ...
Number of services found: 1
Error:The project 'c:\users\aagarwal.jba\source\repos\WebApplication1\WebApplication1\WebApplication1.csproj' does not target a supported .Net Core or a .Net Framework version. The supported framework versions are as follows: netcoreapp[1.0-2.0], netstandard[1.3-2.0] and net[4.5-4.6.2].

**Comment by mlacouture** [comment]
@akhilesh78 thank you for reporting this issue.  What version of Visual Studio 2017 are you using? would you be able to try to reproduce this problem in Visual Studio 2017 v15.5 Preview 4? we have made several fixes on this area and it seems to me you are using an old version of the tool.

Miguel Lacouture

**Comment by akhilesh78** [comment]
I used Visual Studio 2017 15.4.5 version and yes the issue is reproducible on this version with a new project. 

When testing with Visual Studio 2017 15.5 Preview 5 release, it does work with .NET Framework 4.7.1.

Do you have an updated nuget package to make this work on Visual Studio 2017 15.4.5 ?

Thanks,

Akhilesh Agarwal

**Comment by mlacouture** [comment]
@akhilesh78, we currently don't have any plans to port the tool back to previous versions of Visual Studio.  The good news is that [Visual Studio 2017 15.5 RTW](https://github.com/dotnet/wcf/issues/2384) is now available!
