### ISSUE TITLE
how can you run this from command line.

### ISSUE THREAD

**Issue by learn9969** [dotnet/wcf#2420]
Hi there
I have tried wcf connected services and it works,however I would like to be run from command line whenever my solution is build.

Is this possible. Tried svcutil and it generates duplicates classes whilst wcf connected services doesnt

suggestions?

**Comment by zhenlan** [comment]
@learn9969 thanks for the feedback. Yes, this is on our plan.

cc: @mlacouture 

Duplicate of #1222
