### ISSUE TITLE
SOAP service with WS-Security policies

### ISSUE THREAD

**Issue by hoffmanjon** [dotnet/wcf#2421]
I am trying to interact with a web service that implements ws-security using certificates.  My preference would be to use the service reference tool within Visual Studio 2017 to create the connection code however when I create the service reference the EndpointConfigutation file is not created.

I opened up a question in the WCF MSDN forum about this and was told the Windows UWP implementation of WCF does not support certificates with ws-security.  You can read more details about the issue within this forum post here:  https://social.msdn.microsoft.com/Forums/vstudio/en-US/99fc2a75-7291-4618-8da0-e44d3e7df7e9/soap-client-with-wssecurity?forum=wcf&prof=required

Then I attempted to build the XML envelope with header and payload by hand.  The first thing I wanted to do was to sign part of the document as described here:  https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-sign-xml-documents-with-digital-signatures.  It appears that the code in this document is also not compatible with a UWP app because some of the code, like the CspParameters type is not compatible with UWP apps.

I would like to see WCF fully implemented for UWP apps so we can access SOAP services that implement ws-security with certificates.  As a work around, we may have to implement a local service on the tablet with Java/Apache CXF that act as a proxy between the UWP app and the SOAP service which is definitely not ideal.  We would like to avoid the extra service and implement the connection to the SOAP service directly in the app.

**Comment by zhenlan** [comment]
Related to #31

**Comment by StephenBonikowsky** [comment]
Track with #31
