### ISSUE TITLE
Not able to add WCF reference to class library in VS2017

### ISSUE THREAD

**Issue by RG2712** [dotnet/wcf#2428]
I am able to add WCF reference in VS 2012. I am using ASP.Net Web Application(.Net Framework) MVC application. My VS version is Enterprise 2017 version 15.4.5

The problem I am facing is while adding the service reference in web project, its not adding endpoints in web.config file. And when am trying to add the service reference in class library project it showing the error:
"url does not have valid endpoints"
I have installed Microsoft WCF Web Service Reference Provider also to get the reference in class library.
Also checked with unchecking the checkbox in advanced section of referencing other assemblies.

Please suggest.

**Comment by mlacouture** [comment]
Hi @RG2712 

Usually when you get this error is because the web service metadata does not contain any endpoints.  Are you able to share the service URL or WSDL file with us so we can double check?

Also, please keep in mind that although sometimes we are able to help on questions for WCF on .Net Framework, this forum is for WCF on .NET Core/.Net Standard.

As per the WCF Web Service Reference tool, you won't find a web.config file as the .NET Core does not support configuration files; however, configuration is provided in code.

Hope this helps and waiting for your response.

thank you for your feedback.

Miguel Lacouture

**Comment by RG2712** [comment]
Hi @mlacouture 

Thanks for your response.

Below is the wsdl am referring. This is the third party service on which I do not have any control. I just need to access the contracts.

<?xml version="1.0" encoding="utf-8" ?> 
- <wsdl:definitions name="TimeReportService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
- <wsdl:types>
- <xsd:schema targetNamespace="http://tempuri.org/Imports">
  <xsd:import schemaLocation="http://TimeReportService.svc?xsd=xsd0" namespace="http:///" /> 
  <xsd:import schemaLocation="http://TimeReportService.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" /> 
  <xsd:import schemaLocation="http://TimeReportService.svc?xsd=xsd2" namespace="http://schemas.datacontract.org/2004/07/CommonLibraries" /> 
  <xsd:import schemaLocation="http://TimeReportService.svc?xsd=xsd3" namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" /> 
  </xsd:schema>
  </wsdl:types>
- <wsdl:message name="ITimeReportService_TestService_InputMessage">
  <wsdl:part name="parameters" element="tns:TestService" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_TestService_OutputMessage">
  <wsdl:part name="parameters" element="tns:TestServiceResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_FindEmployee_InputMessage">
  <wsdl:part name="parameters" element="tns:FindEmployee" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_FindEmployee_OutputMessage">
  <wsdl:part name="parameters" element="tns:FindEmployeeResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetEmployeeDetail_InputMessage">
  <wsdl:part name="parameters" element="tns:GetEmployeeDetail" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetEmployeeDetail_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetEmployeeDetailResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetNewTimeSheet_InputMessage">
  <wsdl:part name="parameters" element="tns:GetNewTimeSheet" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetNewTimeSheet_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetNewTimeSheetResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetExistingTimeSheet_InputMessage">
  <wsdl:part name="parameters" element="tns:GetExistingTimeSheet" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetExistingTimeSheet_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetExistingTimeSheetResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetNotifiedUser_InputMessage">
  <wsdl:part name="parameters" element="tns:GetNotifiedUser" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetNotifiedUser_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetNotifiedUserResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetTaskTypes_InputMessage">
  <wsdl:part name="parameters" element="tns:GetTaskTypes" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetTaskTypes_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetTaskTypesResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetProject_InputMessage">
  <wsdl:part name="parameters" element="tns:GetProject" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetProject_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetProjectResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetTask_InputMessage">
  <wsdl:part name="parameters" element="tns:GetTask" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetTask_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetTaskResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetAMSData_InputMessage">
  <wsdl:part name="parameters" element="tns:GetAMSData" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetAMSData_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetAMSDataResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetJiraData_InputMessage">
  <wsdl:part name="parameters" element="tns:GetJiraData" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetJiraData_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetJiraDataResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_IsPlanviewUserExist_InputMessage">
  <wsdl:part name="parameters" element="tns:IsPlanviewUserExist" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_IsPlanviewUserExist_OutputMessage">
  <wsdl:part name="parameters" element="tns:IsPlanviewUserExistResponse" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetPlanViewWork_InputMessage">
  <wsdl:part name="parameters" element="tns:GetPlanViewWork" /> 
  </wsdl:message>
- <wsdl:message name="ITimeReportService_GetPlanViewWork_OutputMessage">
  <wsdl:part name="parameters" element="tns:GetPlanViewWorkResponse" /> 
  </wsdl:message>
- <wsdl:portType name="ITimeReportService">
- <wsdl:operation name="TestService">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/TestService" message="tns:ITimeReportService_TestService_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/TestServiceResponse" message="tns:ITimeReportService_TestService_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="FindEmployee">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/FindEmployee" message="tns:ITimeReportService_FindEmployee_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/FindEmployeeResponse" message="tns:ITimeReportService_FindEmployee_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetEmployeeDetail">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetEmployeeDetail" message="tns:ITimeReportService_GetEmployeeDetail_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetEmployeeDetailResponse" message="tns:ITimeReportService_GetEmployeeDetail_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetNewTimeSheet">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetNewTimeSheet" message="tns:ITimeReportService_GetNewTimeSheet_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetNewTimeSheetResponse" message="tns:ITimeReportService_GetNewTimeSheet_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetExistingTimeSheet">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetExistingTimeSheet" message="tns:ITimeReportService_GetExistingTimeSheet_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetExistingTimeSheetResponse" message="tns:ITimeReportService_GetExistingTimeSheet_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetNotifiedUser">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetNotifiedUser" message="tns:ITimeReportService_GetNotifiedUser_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetNotifiedUserResponse" message="tns:ITimeReportService_GetNotifiedUser_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetTaskTypes">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetTaskTypes" message="tns:ITimeReportService_GetTaskTypes_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetTaskTypesResponse" message="tns:ITimeReportService_GetTaskTypes_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetProject">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetProject" message="tns:ITimeReportService_GetProject_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetProjectResponse" message="tns:ITimeReportService_GetProject_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetTask">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetTask" message="tns:ITimeReportService_GetTask_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetTaskResponse" message="tns:ITimeReportService_GetTask_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetAMSData">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetAMSData" message="tns:ITimeReportService_GetAMSData_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetAMSDataResponse" message="tns:ITimeReportService_GetAMSData_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetJiraData">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetJiraData" message="tns:ITimeReportService_GetJiraData_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetJiraDataResponse" message="tns:ITimeReportService_GetJiraData_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="IsPlanviewUserExist">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/IsPlanviewUserExist" message="tns:ITimeReportService_IsPlanviewUserExist_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/IsPlanviewUserExistResponse" message="tns:ITimeReportService_IsPlanviewUserExist_OutputMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="GetPlanViewWork">
  <wsdl:input wsaw:Action="http://tempuri.org/ITimeReportService/GetPlanViewWork" message="tns:ITimeReportService_GetPlanViewWork_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/ITimeReportService/GetPlanViewWorkResponse" message="tns:ITimeReportService_GetPlanViewWork_OutputMessage" /> 
  </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="TimeReportService" /> 
  </wsdl:definitions>

**Comment by mlacouture** [comment]
@RG2712 can you provide a full wsdl? this one has references to schema files that cannot be resolved.  To do that, you can enter the service url in the browser and append the '?singlewsdl' query.  thanks,

**Comment by mlacouture** [comment]
Hi @RG2712, we haven't heard from you in a while.  I'd like to let you know that [Visual Studio 2017 v15.6 Preview 3 is now available](https://www.visualstudio.com/vs/preview/) and we have made several improvements to the tool in the recent releases.  Please give it a try. If you still experience this issue then please reopen it.
thank you!
