### ISSUE TITLE
Can't Remove WCF Web Service Reference Provider - Preview Extension

### ISSUE THREAD

**Issue by Citizen39** [dotnet/wcf#2429]
I just updated my VS Ent. from 15.4.? to  15.5.0. I previously had the Preview of the WCF Web Service Reference Provider installed. With the update, I now have two instances of the extension. 

I can't seem to get rid of the Preview extension, which shows up when adding a connected service.

![2017-12-06 09_58_39](https://user-images.githubusercontent.com/23709502/33674273-3f2bf9a2-da6c-11e7-8fb3-cade19dc1dd9.png)

**Comment by mlacouture** [comment]
Hi @Citizen39 

Can you confirm whether you tried to remove the preview version of the tool from the Visual Studio Extensions menu option? **Tools -> Extensions and Updates**, locate and select the extension and click **Uninstall**.

Thank you very much for your feedback.

**Comment by Citizen39** [comment]
Only one "Microsoft WCF web Service Reference Provider" item was appearing in the Extensions and Updates list. Nothing showing for a "Preview" extension. I tried disabling the one that was displayed, which resulted in both items in the Connected Services tab (shown in the earlier message) to disappear. 

I've since _Uninstalled_ the one item that was in the Extensions and Updates list. This seems to have worked.

**Comment by mlacouture** [comment]
Thank you @Citizen39 for the additional information, I realize it is confusing ...
