### ISSUE TITLE
Need to support ChannelFactory.Credentials.ServiceCertificate

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#243]
Without this feature, we will not be able to use test certificate for some of the security scenarios, such as  DnsEndpointIdentity NetTcpBinding server identify verification scenario.

**Comment by hongdai** [comment]
There are valid custom scenarios to support ChannelFactory.Credentials.ServiceCertificate.Authentication.
* Client needs to be able to specify Service cert authentication mode.

**Comment by iamjasonp** [comment]
Resolved as part of #308
