### ISSUE TITLE
Error: No endpoints compatible with .Net Core apps

### ISSUE THREAD

**Issue by dotnetdan** [dotnet/wcf#2434]
I'm using the connected services tool in VS2017 to connect to a SOAP basicHttp endpoint hosted in a .NET 4.7 WCF self-hosted application. The following error occurs, is there anyway I can troubleshoot this?

Importing web service metadata ...
Number of service endpoints found: 1
Restoring NuGet packages ...
Building solution ...
Scaffolding service reference code ...
Restoring NuGet packages for bootstrapper ...
Building bootstrapper solution ...
Updating bootstrapper project ...
Warning:Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://sungard.com/vpm/core/bindings/2010/11/httpbasic']/wsdl:binding[@name='BankServiceBasicHttp']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.sungard.com/vpm/core/tables/Bank/']/wsdl:service[@name='BankService']/wsdl:port[@name='BankServiceBasicHttp']
Error:Error: No endpoints compatible with .Net Core apps were found.
Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.

**Comment by mlacouture** [comment]
Hi @dotnetdan 

this usually happens when the binding of the service endpoint contains an element (feature) that is not supported in .NET Core, for instance some security elements (message security).  Do you know the binding details for this service? if you need further assistance it would be helpful if you can share the service URL or a wsdl file with us so we can investigate.

thanks
Miguel Lacouture

**Comment by mlacouture** [comment]
similar to issue #1354

**Comment by dotnetdan** [comment]
Hi, the security mode is TransportWithMessageCredential, so it looks like you are right about message security. Will this be supported in the future? 

It would be nice to have a list of what features are supported, to help in design a service that is interoperable with .net core.

The binding (from the client side, generated by wcftestclient.exe) looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.serviceModel>
        <bindings>
            <basicHttpBinding>
                <binding name="BankServiceBasicHttp" sendTimeout="00:01:00">
                    <security mode="TransportWithMessageCredential" />
                </binding>
            </basicHttpBinding>
        </bindings>
        <client>
            <endpoint address="https://localhost:9012/BankService"
                binding="basicHttpBinding" bindingConfiguration="BankServiceBasicHttp"
                contract="BankService" name="BankServiceBasicHttp" />
        </client>
    </system.serviceModel>
</configuration>
```

**Comment by mlacouture** [comment]
Hi @dotnetdan 
Thank you for confirming this is a message security issue.  As mentioned in issue #1354, support for message security in .NET Core is in the backlog but it is going to take a while as it requires several other APIs not yet in the framework.'

For a list of supported features you can visit the [WCF in .NET Core 2.0 release notes](https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v2.0.0.md), or for a detailed API list you can visit the [.Net API Catalog](https://apisof.net/catalog/System.ServiceModel).

dup of #1354
