### ISSUE TITLE
Criteria for reuse types to work. Any guidelines?

### ISSUE THREAD

**Issue by learn9969** [dotnet/wcf#2441]
what is the criteria for reuse types to work with a shared assembly which contain all dtos?
Do they have to  have attributes like (DataContract-DataMember etc..)

Whatever I do it still generates its own classes?

Many thanks

**Comment by Joebeazelman** [comment]
What are you using to generate your code?  Visual Studio menu or svcutils.exe?  Are your DTOs in exactly the same namespace?  Do you set the namespace when you generate your classes?

**Comment by learn9969** [comment]
Sorry for lack of info .I use svcutil.exe for generation. All my dtos are in the same assembly ,same namespace .I tried both with and without setting namespace!

I will try to put a noddy project together to prove point.Can you attach a zip here?

**Comment by Joebeazelman** [comment]
Well that's an important piece of information there.   I think what's confusing you is the nomenclature Microsoft likes to use to confound innocent developers.  First, in VS Add Service Reference it's called reuse existing types.  In SvcUtil.exe it's not clear and not automatic either.  You should look at the following switches:

/reference:<file path>             – Reference types in the specified assembly. When generating clients, use this option to specify assemblies that might contain types representing the metadata being imported.  (Short Form: /r)

/excludeType:<type>                – A fully-qualified or assembly-qualified type name to exclude from referenced contract types. (Short Form: /et)

/dataContractOnly                  – Generate code for Data Contract types only. Service Contract types will not be generated. (Short Form: /dconly)


Use a combination of these switches to see what works for you.  It's not clear what /reference means by "reference types."  I am assuming it means types that are referenced and don't need to be generated and the /et means exclude them from being excluded. 

If the all of your POCO objects exist, you should try /dconly.

You may want

**Comment by mlacouture** [comment]
@learn9969, does the help provided by @Joebeazelman (thank you!) resolved your issue? thanks,
