### ISSUE TITLE
Argh!!  WCF Code Generator uses arrays instead of Generic Lists

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2442]
WCF Code generator generates arrays instead of lists even when I told it not to. Come on guys!

**Comment by mlacouture** [comment]
@Joebeazelman, sounds like the same issue as #1274, can you confirm?

**Comment by Joebeazelman** [comment]
Yes, it is.

**Comment by mlacouture** [comment]
thanks! dup of #1274

**Comment by Joebeazelman** [comment]
You know, perhaps it is better just to handout install some T4 templates for generating the proxy rather than create an elaborate fanch GUI tool that's completely useless.  It appears the designers of WCF allowed for high granularity of customization and configuration, but created horrible tooling for common use cases.  The idea of hiding Reference.cs and its supporting metadata files from the developers is like hiding knives from children, which is insulting. Moreover, creating additional code at runtime and build time is even worse.  

If you're going to rewrite the WCF and the tooling, then take it as an opportunity to fix these bad design choices.  I have fear .NET, despite it incredible productivity, will soon follow the fate of other great technologies of the past such as Delphi, CodeWarrior and Classic Macintosh.  They were all products ahead of their time, but had fatal flaws preventing them from becoming standards. In the case of .NET, Microsoft is it's fatal flaw.
