### ISSUE TITLE
Cannot make the WCF client work on Linux mint 18.3

### ISSUE THREAD

**Issue by txiangyang** [dotnet/wcf#2450]
Hi,
When move the Net Core WCF client project from windows to Linux, it fails. 
Net core sdk version: 2.1.2. (both on windows and Linux)
Steps:
1. Create an net core project, and add connected reference from local WCF service. Build and run successfully. 
2. Copy project to Linux, run command: **dotnet build**: 
Error: 
Restoring packages for /home/userName/NetCore/Core212Client/Core212Client/Core212C                                                                                                              lient.csproj...
'lib/netstandard2.0/System.Net.Http.WinHttpHandler.dll'
'lib/netstandard2.0/System.Net.Http.WinHttpHandler.dll'
/usr/share/dotnet/sdk/2.1.2/NuGet.targets(103,5): error : Unable to load the ser                                                                                                              vice index for source https://api.nuget.org/v3/index.json. [/home/tang/NetCore/C                                                                                                              ore212Client/Core212Client/Core212Client.csproj]
/usr/share/dotnet/sdk/2.1.2/NuGet.targets(103,5): error :   The HTTP request to                                                                                                               'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms. [/home/t                                                                                                              ang/NetCore/Core212Client/Core212Client/Core212Client.csproj]
Build FAILED.
/usr/share/dotnet/sdk/2.1.2/NuGet.targets(103,5): error : Unable to load the ser                                                                                                              vice index for source https://api.nuget.org/v3/index.json. [/home/tang/NetCore/C                                                                                                              ore212Client/Core212Client/Core212Client.csproj]
/usr/share/dotnet/sdk/2.1.2/NuGet.targets(103,5): error :   The HTTP request to                                                                                                               'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms. [/home/t                                                                                                              ang/NetCore/Core212Client/Core212Client/Core212Client.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:05:00.87

3. Try to used DLL built on windows. directly run: dotnet 
➜  netcoreapp2.0 dotnet Core212Client.dll
Error:
  An assembly specified in the application dependencies manifest (Core212Client.deps.json) was not found:
    package: 'System.Net.Http.WinHttpHandler', version: '4.4.0'
    path: 'lib/netstandard2.0/System.Net.Http.WinHttpHandler.dll'
--

So how to make the client work on Linux. Is it available on Linux. 
Thanks so much in advance.

**Comment by zhenlan** [comment]
@txiangyang The failure in your step 3 is expected, because System.Net.Http.WinHttpHandler is a Windows only package and WCF implementation for Linux actually does not need it, so if you run the Windows compiled assembly on Linux, it is expected to fail.

Because WCF package System.Private.ServiceModel does have a package dependency on System.Net.Http.WinHttpHandler, so package restore will try to download System.Net.Http.WinHttpHandler even if on Linux. From step 2, looks like the error is about NuGet cannot download System.Net.Http.WinHttpHandler package and timed out. Can you please double check your internet connection with nuget.org or try on a different machine?

**Comment by txiangyang** [comment]
Thanks, after following yours steps mentioned at marketplaces , i need to use dotnet restore before building, and finally it success.
Thanks so much
________________________________

**Comment by zhenlan** [comment]
Glad it worked for you. Thanks for using WCF and giving us feedback!
