### ISSUE TITLE
VS2017 15.5.2 WCF Web Service Reference Provider Error (MaximumResolvedReferences)

### ISSUE THREAD

**Issue by ermancetin** [dotnet/wcf#2461]
Hi,
I am trying to add a new service reference with new Microsoft WCF Service Reference Provider UI, but getting this error: "_The MetadataExchangeClient has resolved more than MaximumResolvedReferences_"

![image](https://user-images.githubusercontent.com/10434301/34382580-e7d972d6-eb20-11e7-9159-f7eb03fec7d3.png)

**Comment by mlacouture** [comment]
Hi @ermancetin 
Thanks for reporting this issue.  This happens, as the error implies, when there are too many metadata references to resolve, looking at the code it is currently set to 200 which seems like a huge number.  Are you able to download the metadata from the browser?

**Comment by ermancetin** [comment]
Hi @mlacouture 
Yes, i can download the metadata from browser, and also from VS2015 UI.

**Comment by ermancetin** [comment]
Hi,
I tried to get metadata programmatically. And after setting MaximumResolvedReferences property of MetadataExchangeClient to 400, metadataset successfully acquired from server.

![image](https://user-images.githubusercontent.com/10434301/34483312-c333a8f4-efce-11e7-807b-c3f54b9447f5.png)

**Comment by mlacouture** [comment]
@ermancetin thank you for going the extra mile, this information is very useful.  It sounds like the limitation we have in the tool is incorrect.  we will consider changing this in a future release.

**Comment by mlacouture** [comment]
@ermancetin, we have increased the message quotes and the fix wil be available in VS 2017 v15.6 Preview 3 scheduled to be released next week, I hope you can try this preview.  thanks,

**Comment by mlacouture** [comment]
Hi all!
[VS 2017 Preview 3 is now available](https://www.visualstudio.com/vs/preview/), please give it a try.
Thank you!

**Comment by ermancetin** [comment]
@mlacouture 
I tried vs2017 v15.6 Preview 3. It seem like MaximumResolvedReferences problem is resolved.

But now Visual Studio show me this error:

![image](https://user-images.githubusercontent.com/10434301/35680713-2b8365c0-076c-11e8-9b0f-95bb26c4617a.png)

**Comment by mlacouture** [comment]
@ermancetin, that's unfortunate. Do you mind reporting a separate issue to track this as it is unrelated to the original one? also, can you provide some information about your project that could help narrow down this issue? information about file names, and the length of the %temp% folder path would be helpful.
thank you!
