### ISSUE TITLE
Not possible to create a web service reference in Xamarin Forms shared assembly

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/wcf#2464]
I've already reported this here: https://developercommunity.visualstudio.com/content/problem/173283/xamarin-forms-configure-wcf-web-service-ref.html?childToView=173285#comment-173285

1) use VS 2017 15.5.2
2) Create an empty cross platform Xamarin Forms app and select the '.NET standard' option.
3) Use 'Add connected service' on the shared project.
4) Select 'Microsoft WCF Web service reference provider'.
5) Attempt to add a reference to an existing WCF service (basic http binding).
We get:

Importing web service metadata ...
Number of service endpoints found: 1
Restoring NuGet packages ...
Building solution ...
**Error:The solution cannot be built, please try to rebuild the solution and fix any build problems.
There are no build errors.**
Nothing appears under 'Dependencies'.

Note that it is possible to create a web service reference from a .NET standard 2.0 class library project.

**Comment by mlacouture** [comment]
Hi @PhilPJL 
I just replied on the [VS feedback page](https://developercommunity.visualstudio.com/content/problem/173283/xamarin-forms-configure-wcf-web-service-ref.html), here's my response for convenience:

Thank you for reporting this issue. I have reviewed it and verified this is a bug in our tool and we'll consider a fix for the next release. In the meantime, you can work around this issue by unselecting the 'Reuse types in referenced assemblies' option in the 'Data Type options' tab/page, this will prevent the toll from attempting to build the solution.

sorry for the inconvenience and thanks again for helping us build a better Visual Studio.
Miguel Lacouture
[MSFT]

**Comment by mlacouture** [comment]
@PhilPJL, a fix for this issue will be available with the release of VS 2017 Preview 3 next week, I hope you can try this preview, thanks,

**Comment by PhilPJL** [comment]
yes of course.

**Comment by luisdaviddela** [comment]
I have the same error, how can I fix it? :/

**Comment by Jsrc1990** [comment]
I unselect the 'Reuse types in referenced assemblies' option and ok consume but Servicio_Web.Obtener_RopasCompletedEventArgs and Cliente.Obtener_RopasCompleted += Delegado event not exists, is missing, i need it in xamarin before was ok and now all is broken

**Comment by mlacouture** [comment]
Hi @luisdaviddela, did you try unselecting the 'Reuse types in reference assemblies' option?

**Comment by mlacouture** [comment]
Hi @Jsrc1990, can you provide more details about your problem? it seems you were able to generate the proxy code but you are now having a compile-time error where an event is not generated? It seems to me you are using client code from a proxy previously generated for a .NET Framework project, if this is the case, this is not supported in a .NET Core project.  Can you please confirm/provide details? 

thanks,
Miguel Lacouture

**Comment by mlacouture** [comment]
Hi all! 
[VS 2017 Preview 3 is now available](https://www.visualstudio.com/vs/preview/), please give it a try.
Thank you!

**Comment by PhilPJL** [comment]
Failed:

Importing web service metadata ...
Number of service endpoints found: 2
Scaffolding service reference code ...
Restoring NuGet packages for bootstrapper ...
Building bootstrapper project ...
Error:Error: Microsoft (R) Build Engine version 15.6.54.9755 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\passp\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.targets(55,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\passp\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\passp\AppData\Local\Temp\WCFConnectedService\2018_Jan_26_18_48_15\svcutil_bootstrap\SvcUtilBootstrapper.csproj]

Build FAILED.

C:\Users\passp\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.targets(55,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\passp\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\passp\AppData\Local\Temp\WCFConnectedService\2018_Jan_26_18_48_15\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.37

An error occurred while bootstrapping svcutil. This usually happens when processing references.  You might be able to work around this problem by not providing reference parameters, and manually removing any types redefined in the generated proxy code.
Done.

**Comment by mlacouture** [comment]
hmm, let us take a second look ...

**Comment by giuliorisi** [comment]
I have the same problem

C:\Users\myname\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.targets(55,3): error MSB4062: non � stato possibile caricare l'attivit� "Xamarin.Forms.Build.Tasks.GetTasksAbi" dall'assembly C:\Users\g.risi\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Impossibile trovare il file specificato. Verificare che la dichiarazione <UsingTask> sia corretta, che l'assembly e tutte le relative dipendenze siano disponibili e che l'attivit� contenga una classe pubblica che implementa Microsoft.Build.Framework.ITask. [C:\Users\g.risi\AppData\Local\Temp\WCFConnectedService\2018_Feb_08_20_53_14\svcutil_bootstrap\SvcUtilBootstrapper.csproj]

**Comment by fgiacomelli** [comment]
same problem for me, using .NET standard

**Comment by mlacouture** [comment]
Hi all!

Thank you for reporting the new issue. For the records, observe that this is a different issue as I will explain next; the original issue regarding "The solution cannot be built" was indeed fixed with the release of [Visual Studio 2017 v15.6 Preview 3](https://www.visualstudio.com/vs/preview/).

Regarding the new issue, the build error happens when trying to compile the bootstrapping project (a .Net Core project used for processing project references), this is due to the fact that the Xamarin platform does not support building projects using the dotnet engine (dotnet.exe build).

In order to work around this problem you can either disable the 'Reuse types in referenced assemblies' option from the Data Types Option page (as suggested previously), or manually select all references except the Xamarin ones as shown in the picture.

![reusetypes](https://user-images.githubusercontent.com/7647255/36233856-de0733b8-119c-11e8-99c3-992dffe03f42.jpg)

Unfortunately, even if you get passed this problem, you will hit issue #2463; the fact is that Xamarin does not yet fully support .Net Core/Standard.  Please follow issue #2463 in case a workaround is provided.

Hope this helps,
Miguel Lacouture

**Comment by erfankh67** [comment]
you can use application => "Service Reference Generator For .net Standard & Xamarin.Forms" from : https://files.fm/u/mduffseg

  first read help in application

**Comment by emtcho** [comment]
Please be aware - the RAR file offered under https://files.fm/u/mduffseg contains a virus and is automatically deleted after download. I hope it was not intended...

**Comment by erfankh67** [comment]
Hi
The file does not contain a virus, probably because it contains an executable file as a threat by your system
________________________________

**Comment by emtcho** [comment]
Please see the Windows Defender warning below:

![fuery](https://user-images.githubusercontent.com/28629255/42375846-352a1b34-811d-11e8-8fca-b81301f2e391.PNG)

I think it is self explaining...

**Comment by NeloHuerta** [comment]
Looks like this problem is yet here.

Im using VS2017 Version 15.9.22

I observe the same behavior as reported by  @PhilPJL on 29 Dec 2017.

I can workaround it disabling the 'Reuse types in referenced assemblies' 

This problem is not present when using VS2019.
