### ISSUE TITLE
Unable To Ignore Server Certificate Error In Windows

### ISSUE THREAD

**Issue by easternstar88** [dotnet/wcf#2466]
In dotnet FrameWork i could ignore Server Certificate Error With 
`ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;`
but here That Solution Doesn't work and i get **System.ServiceModel.Security.SecurityNegotiationException**:
"could not establish trust relationship for the ssl/tls secure channel with authority..."

**Comment by zhenlan** [comment]
@easternstar88 can you please try this?

```c#
factory.Credentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication();
factory.Credentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = X509CertificateValidationMode.None;
```

**Comment by easternstar88** [comment]
Solved! Thanks a lot.
