### ISSUE TITLE
Setting "BasicHttpBinding.UseDefaultWebProxy = false" not supported on OSX 10.12

### ISSUE THREAD

**Issue by f0rt** [dotnet/wcf#2467]
Team,
I'm using[ this example](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-use-the-channelfactory) on OSX. I've added the following line:

```c#
myBinding.UseDefaultWebProxy = false;
```
This throws operation not supported exception on OSX 10.12 . Is this expected? 

P.S. The problem exist with CustomBinding too.

**Comment by f0rt** [comment]
The problem can be reproduced on Ubuntu 16.04.

**Comment by zhenlan** [comment]
Duplicate of #1592
