### ISSUE TITLE
WCF Web Service Reference and 'Discover'

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/wcf#2470]
The 'Discover' button fails unless WCF projects in the solution are first manually started.
This is different to adding a WCF reference in a .NET framework project/solution.

![image](https://user-images.githubusercontent.com/271656/34497994-8d7272e4-eff7-11e7-823e-af662cdb77ff.png)

I can work around this by first manually starting 'WcfService' with Ctrl-F5.

**Comment by mlacouture** [comment]
Hi @PhilPJL 

Thank you for reporting this issue.  Can you please tell us what version of Visual Studio are you using? 

Miguel Lacouture
[MSFT]

**Comment by PhilPJL** [comment]
VS 2017 15.5.2

**Comment by mlacouture** [comment]
@PhilPJL, we fixed this issue in [VS 2017 15.6 Preview 1](https://blogs.msdn.microsoft.com/visualstudio/2017/12/07/visual-studio-2017-version-15-6-preview/), will you be able to try the preview?

**Comment by PhilPJL** [comment]
@mlacouture seems to work ok in Preview 1.

**Comment by mlacouture** [comment]
thank you @PhilPJL  for confirming.
