### ISSUE TITLE
System.ServiceModel.Web is missing

### ISSUE THREAD

**Issue by varcario** [dotnet/wcf#2473]
I'm migrating a Web API app from .NET Core RC1 to .NET Core 2.0 and having trouble finding a good replacement for one line of code. The project is an ASP.NET Web API that calls a SOAP service, the SOAP service requires request headers.  Works great in RC1 targeting dnx451 but can't get this one last line converted to call it done.  

System.ServiceModel.Web.WebOperationContext.Current.OutgoingRequest.Headers.Add("key", "value");

Does anyone know how to perform the above function inside a .NET Core 2.0 app targeting netcoreapp2.0?

**Comment by zhenlan** [comment]
It should work if your ASP.NET Core Web API app targets net461 (you were targeting dnx451, which is also full framework). The System.ServiceModel.Web.* APIs are not supported on .NET Core.

**Comment by varcario** [comment]
The idea of being able to run this app on linux really appealed to me.  If I target net461 will the option of hosting on linux go away?  Also, is there an alternative to perform the function above by some other means?

**Comment by zhenlan** [comment]
@varcario this is an alternative way to set request headers
https://github.com/dotnet/wcf/blob/9cff0c81e535ac177f60ab25dff904a3144d62b3/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs#L58

**Comment by zhenlan** [comment]
@varcario, please let me know if this worked for you. Closing.

**Comment by varcario** [comment]
Yes, it sure did.

Thank you!

**Comment by White99** [comment]
@zhenlan  I have the same problem...
I added a reference to WCF through via “WCF Web Service Reference”, then generate the client code from remote WCF which include " [System.ServiceModel.ServiceContractAttribute" "System.ServiceModel.XmlSerializerFormatAttribute",  But I need to make it run in a linux environment，
but something went wrong :" System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.serviceModel", 

So , what should i do please?
