### ISSUE TITLE
Memory leak when consuming SOAP endpoint

### ISSUE THREAD

**Issue by coldraydk** [dotnet/wcf#2474]
Hi guys,

I've encountered a memory leak when consuming SOAP endpoints in my .NET applications. The memory usage of my application continues to increase over time to a point where it obviously kills the application.

My application is running on .NET Core 2.0 in a Docker container. At first, I was suspecting new technology to be causing the leak, so I've narrowed it down to a simple test application running locally without using Docker but where I could still replicate the leak consistently:

```using System;
using System.Threading.Tasks;
using System.ServiceModel;
using System.ServiceModel.Channels;
using MyService.CprSearchService;

namespace MemoryLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            var binding = new BasicHttpBinding();
            var endpoint = new EndpointAddress(new Uri("http://172.20.1.1:5000/"));

            ChannelFactory<CprServiceChannel> factory = new ChannelFactory<CprServiceChannel>(binding, endpoint);

            Parallel.For(0, 10000, index =>
            {
                CprServiceChannel channel = factory.CreateChannel();
  
                try
                {
                    channel.Open();
                    channel.cprSearchAsync(new cprSearch { arg0 = new cprSearchRequest { cpr = "0000000001" } }).GetAwaiter().GetResult();
                }
                catch (Exception e)
                {
                    System.Console.WriteLine($"{index} | Exception {e.Message}.");
                }
                finally
                {
                    channel.Close();
                    System.Console.WriteLine($"{index} | State: {channel.State}");

                    if (channel.State == CommunicationState.Faulted)
                        channel.Abort();
                    else
                        channel.Dispose();

                    channel = null;

                    System.Console.WriteLine($"{index} | Channel closed.");
                }
            });
            factory.Close();
            factory = null;

            Console.WriteLine("Factory closed.");
            Console.ReadLine();
        }
    }
}
```
Memory usage continues to increase, and is not cleaned up properly when factory is closed. In this example, I'm trying to close as much as I can explicitly as well. The code for the proxies is generated by SvcUtil 4.4.0, however the leak is also present when handfeeding it with requests:
```
Message request = Message.CreateMessage(MessageVersion.Soap12WSAddressing10, "example");
Message reply = channel.Request(request);
request.Close();
```
I got curious, so I downloaded VS 2017 CE and started taking snapshots of the memory usage there. After execution, the snapshots showed a lot of detected cycles on various types, but I haven't been able to pinpoint the cause of the leak.

My next step was to try to target other frameworks and/or use earlier versions of System.ServiceModel. I get the same behaviour on 4.5 and 4.6.1 using both System.ServiceModel 4.4.0 and 4.0.0. The leak is present in a default console application running 4.6.1 in VS using the integrated "Add Service Reference" implementation of SvcUtil. This is also not a OS specific issue, since I'm able to replicate it on both Windows and Linux (.NET Core).

**Comment by mconnew** [comment]
@coldraydk, please have a read through issue #2351 and let me know if that addresses your concern?

**Comment by mconnew** [comment]
@coldraydk, do you have any more questions after reading the other issue?
