### ISSUE TITLE
I can not add my webservices

### ISSUE THREAD

**Issue by Snayder187** [dotnet/wcf#2489]
Hello, how are you? I have a problem with the new version of Xamarin, I already have my webservices created and it works to me 100% but when I create a Xamarin project, I no longer get the portable now I get the .NET Standard, when I create it and I want to make a reference to my webservices I get an error but when I recompile all my "new" file xamarin I get everything OK, I can not find what the problem is.

![2](https://user-images.githubusercontent.com/33837035/34786412-1c830df8-f602-11e7-81a4-3ef2349f202c.png)

**Comment by mlacouture** [comment]
Hi @Snayder187 
Thank you for reporting this issue, it looks like the same as #2464 for which we are considering a fix for the next release (Visual Studio 2017 v15.6 Preview 3). Please check issue #2464 for a workaround.  I'm closing this as a dup. please reactivate if you think this is not the same issue.

thanks,
Miguel Lacouture
