### ISSUE TITLE
How to Add a service that requires a Soap Header

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/wcf#2509]
I need to Generate code for this WCF Service, 
https://servicoshm.saude.gov.br/cadsus/PIXManager
 but they require Soap Header, so just opening it in a WebBrowser, for example, returns

**_Access Denied_**
![image](https://user-images.githubusercontent.com/6307623/35186122-dbd792da-fded-11e7-8a64-4ca08ccce06d.png)
This screens gets stuck on "Please wait..."
![image](https://user-images.githubusercontent.com/6307623/35186118-ccf63d34-fded-11e7-8894-4a6c793b2c08.png)

This Service documentation states that a Soap Header is required to connect to this service:

```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Header xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis200401-wss-wssecurity-secext-1.0.xsd">
      <wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-utility-1.0.xsd" wsu:Id="Id-0001334008436683-000000002c4a1908-1">
         <wsse:Username>CADSUS.CNS.PDQ.PUBLICO</wsse:Username>
         <wsse:Password Type="http://docs.oasisopen.org/wss/2004/01/oasis-200401-wss-username-token-profile1.0#PasswordText">kUXNmiiii#RDdlOELdoe00966</wsse:Password>
      </wsse:UsernameToken>
   </wsse:Security>
</soap:Header>
```

**How to add this Header, and then use the Add WCF Service Reference?**

**Comment by mlacouture** [comment]
Hi @TonyHenrique 

I tried the provided service URL and what I can see is that the request gets shut down on the server site.  It seems to me that the specified address does not refer to a metadata exchange endpoint (which when secured it is usually done at the IIS level, see [this web post ](https://blogs.msdn.microsoft.com/webdev/2017/06/28/wcf-web-service-reference-mex-authentication/)for details) but to the actual service endpoint which requires authentication.

In the case the MEX endpoint is somehow secured with WCF security, you would have to implement the code to download the metadata and save it to disk to be able to use the WCF Web Service reference tool and generate proxy code from the service metadata in disk.  You can look at the [MetadataExchangeClient](https://msdn.microsoft.com/en-us/library/system.servicemodel.description.metadataexchangeclient(v=vs.110).aspx) and the [WsdlImporter](https://msdn.microsoft.com/en-us/library/system.servicemodel.description.wsdlimporter(v=vs.110).aspx) classes in MSDN for implementing this.

My suggestion is to contact the service provider and ask whether they provide a separate address for the service metadata or ask them for the WSDL docs directly.

hope this helps,
Miguel Lacouture

**Comment by ramonleo** [comment]
Hi @TonyHenrique, I'm getting the same problem. Did you solve this?
