### ISSUE TITLE
Create a duplex scenario test to use Xml in the callback contract

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#251]
First, determine whether it is a supported scenario for a duplex callback contract to specify an [XmlSerializerFormat] attribute or an XmlSerializerOperationBehavior so that its "Ping" callback passes the value as xml rather than data contract.  And for the type, use a complex type not used in any service contract.

If supported, create a scenario test that does this.  This is to verify 3 things:
1. An xml serializer will be generated in NET Native for this type
2. The ContractDescription creation correctly recognizes this operation behavior on a callback contract
3. The e2e serialization+deserialization works correctly

**Comment by StephenBonikowsky** [comment]
If I understand this correctly the XmlSerializerOperationBehavior is server side functionality that gets access to the XmlSerializerFormatAttribute, XmlSerializerOperationBehavior is not supported in K/N but XmlSerializerFormatAttribute is.
