### ISSUE TITLE
Authentication failure when adding a WCF Web Service Reference with the correct auth (Not a web service URL)

### ISSUE THREAD

**Issue by bipasac2000** [dotnet/wcf#2510]
I am trying to add a WCF Web service reference to the following service with an authentication certificate that I have locally on my machine -
 https://mseventswwppe.partners.extranet.microsoft.com/VendorRegistrationServices/RegistrationServices.svc. 

From a fiddler trace I see that the authentication fails with a 403 error even though I am using the correct certificate and in the UI I see a infinite authentication loop.. I am asked to pick a authentication certificate each time after a failure.

I am able to authenticate correctly with this service from the web browser. 

Does anyone have any pointers to resolve this issue?

**Comment by mlacouture** [comment]
Hi @bipasac2000 
Thank you for reporting this issue.  The service at the specified address does not seem to be a web service as the document that is downloaded is not wsdl or schema.  However, the tool should be able to let you know about it, we will look into this issue.
Miguel Lacouture

**Comment by mlacouture** [comment]
We have a fix for certificate issue and we are planning to make it available with the release of VS 2017 v15.7 Preview 2.

**Comment by mlacouture** [comment]
[VS 2017 v15.7 Preview 2](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes) is now available.
