### ISSUE TITLE
Tuple<string,string> started being generated as TupleOfstringstring custom object

### ISSUE THREAD

**Issue by hburgess** [dotnet/wcf#2511]
I deleted an existing connected service that had methods with parameters of type Tuple<string,string> and recreated the connected service to the same URL and all parameters of this type had been replaced with a newly generated custom object called TupleOfstringstring (which of course broke all references to the generated code). Manually changing all the TupleOfstringstring parameter types back to Tuple<string,string> fixed the problem (I was able to call the services successfully).

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TupleOfstringstring", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class TupleOfstringstring : object
    {
        
        private string m_Item1Field;
        
        private string m_Item2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Item1
        {
            get
            {
                return this.m_Item1Field;
            }
            set
            {
                this.m_Item1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Item2
        {
            get
            {
                return this.m_Item2Field;
            }
            set
            {
                this.m_Item2Field = value;
            }
        }
    }

**Comment by zhenlan** [comment]
@hburgess, thanks for reporting the issue. We will take a look.

**Comment by Lxiamail** [comment]
Thank you for the feedback, but our team was unable to prioritize it at this time as they are working on problems with broader customer impact. Please comment below if you have additional data or details that will help us appropriately reprioritize this issue.
