### ISSUE TITLE
System.ServiceModel.* nuget packages missing portable RID assets

### ISSUE THREAD

**Issue by safern** [dotnet/wcf#2531]
When you take a dependency on any of the ServiceModel packages, if you try to publish for a portable RID (only tried in windows: win-x86, win-x64) the dlls are not present in the published closure. 

```
System.ServiceModel.Duplex, 4.1.0.0
        Missing: System.Private.ServiceModel, 4.1.2.1
System.ServiceModel.Http, 4.1.2.0
        Missing: System.Private.ServiceModel, 4.1.2.1
System.ServiceModel.NetTcp, 4.1.2.0
        Missing: System.Private.ServiceModel, 4.1.2.1
System.ServiceModel.Primitives, 4.2.0.0
        Missing: System.Private.ServiceModel, 4.1.2.1
System.ServiceModel.Security, 4.0.3.0
        Missing: System.Private.ServiceModel, 4.1.2.1
```

cc: @weshaggard @zhenlan

**Comment by zhenlan** [comment]
@safern, is this the same issue as #2349?

We did not go back and fix this in released versions, but this is fixed in v2.1.

**Comment by safern** [comment]
Ah, yes it is the same issue. Didn't see it was open. Perfect, whenever the v2.1 is released let me know so that we can update the compatibility package dependency.

**Comment by zhenlan** [comment]
Sure. Thanks.
