### ISSUE TITLE
Tool not appearing in "Connected Services"

### ISSUE THREAD

**Issue by grumble1965** [dotnet/wcf#2536]
I've installed the tool in VS2017, my project's "Connected Services" doesn't show the WCF tool as an option.  What's the right way to make the tool appear or to invoke it some other way?

**Comment by zhenlan** [comment]
Please make sure you update VS2017 to v15.5 or later. The tool is included in VS so you don't have to install it separately. The doc below has a simple walkthrough of how to use the tool. Please note, the tool is for .NET Core projects only. For conventional projects, you can continue to use "Add Service Reference" tool in VS.

https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide

**Comment by zhenlan** [comment]
@grumble1965 has your issue been solved? If not, it will be great if you can share more details like which version of VS2017 you are using, what kind of project you have etc., so we can see if you have the same issue as @Carolyn-Rae had.

**Comment by zhenlan** [comment]
@grumble1965, please let us know if you have an update. Closing for now.
