### ISSUE TITLE
why is the service contract method generated by the Web Service Reference Provider private 

### ISSUE THREAD

**Issue by koo9** [dotnet/wcf#2539]
in a dotnet core app, when referencing a web service, the proxy it generate has an explicit interface implementation but the method is private instead of public, so one need to explicitly cast it back to the service contract/interface in order to call it. is it a defect?

**Comment by zhenlan** [comment]
@koo9, did you try to select "Client Options" -> "Access Level for generated classes" -> "Public" in the wizard?

**Comment by koo9** [comment]
@zhenlan no, but why is that? isn't interface method public by default?

**Comment by zhenlan** [comment]
@koo9, "Public" is the default option in the wizard. I am trying to confirm "Public" is indeed selected in the wizard during your proxy code generation. Can you please confirm?

**Comment by mlacouture** [comment]
@koo9, can you provide more details? the service and service channel interfaces are public by default so are the methods in a public interface.  what are you trying to do? thank you!

**Comment by koo9** [comment]
Ok Here are the steps to reproduce this behavior. when generate service proxy, if leave the "Always generate message contracts" unchecked, the coder gen will generate the service contract but it will also generate the proxy that have implicit service contract implementation which is private. BUT if check "Always generate message contracts", the proxy generated will have an implicit service contract implementation which have all interface methods implemented as public methods.

**Comment by mlacouture** [comment]
Hi @koo9 
I still can't reproduce your issue with the information provided.  Let's try to identify what's missing, let's say you have a contract like the following:
```
    public interface IService1 {
        [OperationContract] string GetData(int value);
        [OperationContract] CompositeType GetDataUsingDataContract(CompositeType composite);
    }
```

the generated proxy using the default options (no message contracts) looks something like this:
```
namespace ServiceReferenceNoMsgContracts {
    [System.ServiceModel.ServiceContract]
    public interface IService1 {      
        [System.ServiceModel.OperationContract(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContract(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite);
    }
  
    public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1 {
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) { }
        public System.Threading.Tasks.Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite) { }
    }
}
```
and when the message contracts option is selected the code looks something like this:

```
namespace ServiceReferenceWithMsgContracts {
    [System.ServiceModel.ServiceContract]
    public interface IService1 {        
        [System.ServiceModel.OperationContract(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<GetDataResponse> GetDataAsync(GetDataRequest request);
        
        [System.ServiceModel.OperationContract(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(GetDataUsingDataContractRequest request);
    }

    public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1  {
        public System.Threading.Tasks.Task<GetDataResponse> GetDataAsync(GetDataRequest request) { }
        public System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(GetDataUsingDataContractRequest request) { }
    }
}
```
In both cases the generated service interface is public and so is its implementation by the client. 

Based on this information, can you please explain what's missing? you can also provide us with the service URL or WSDL if it is possible so we can investigate further.

thank you!
Miguel Lacouture

**Comment by koo9** [comment]
Hi @mlacouture 
please use this service to reproduce the issue. https://ibs.ct.rapidwebservices.cgi.com/rapidwebservices/WebServices/DriverClaimHistoryGoldWS.asmx

it maybe an asmx issue. 

generate the proxy with default options, and u will see the interface implementation is private.

Thx

**Comment by mlacouture** [comment]
Hi @koo9 
Thank you for providing the service address. I was able to reproduce the issue.  This is an interesting service, the service contract is based on request/response parameters as opposed to explicit parameters.  

Observe that even though the interface implementation is explicit (private) the generated code provides corresponding methods with explicit parameters:

```
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
System.Threading.Tasks.Task<NoMsgContract.GetDCHGCarbonCopyListResponse> NoMsgContract.DriverClaimHistoryGoldWSSoap.GetDCHGCarbonCopyListAsync(NoMsgContract.GetDCHGCarbonCopyListRequest request)
{
    return base.Channel.GetDCHGCarbonCopyListAsync(request);
}
        
public System.Threading.Tasks.Task<NoMsgContract.GetDCHGCarbonCopyListResponse> GetDCHGCarbonCopyListAsync(NoMsgContract.CredentialContext CredentialContext, NoMsgContract.Credentials Credentials, NoMsgContract.FederatedContext FederatedContext, NoMsgContract.FederatedCredentials FederatedCredentials, NoMsgContract.RequestMode RequestMode, NoMsgContract.RequestOrigin RequestOrigin, int MaxListItems)
{
    NoMsgContract.GetDCHGCarbonCopyListRequest inValue = new NoMsgContract.GetDCHGCarbonCopyListRequest();
    inValue.CredentialContext = CredentialContext;
    inValue.Credentials = Credentials;
    inValue.FederatedContext = FederatedContext;
    inValue.FederatedCredentials = FederatedCredentials;
    inValue.RequestMode = RequestMode;
    inValue.RequestOrigin = RequestOrigin;
    inValue.MaxListItems = MaxListItems;
    return ((NoMsgContract.DriverClaimHistoryGoldWSSoap)(this)).GetDCHGCarbonCopyListAsync(inValue);
}
```
This is consistent, the generated code implements service methods with request/response parameters when the 'Always generate message contracts' option is selected, otherwise, it generates methods with explicit parameters.

Hope this helps,
Miguel Lacouture
