### ISSUE TITLE
Unable to Import WSDL (Metadata contains a reference that cannot be resolved)

### ISSUE THREAD

**Issue by rjts** [dotnet/wcf#2543]
**VS 2017 Targetting .Net Standard 2.0 or .Net Core 2.0**
I tried the Connected Services - Microsoft WCF Web Service Reference Provider and it generates the error below...
I also tried the command line version of the same thing and it too reports a CData error as before.
If I change the project type to .Net Framework 4.6.2 which seems to use the old svcutil app - this does succeed but I need it to work with .Net Core 2.0.

Suggestions, workarounds or ideas appreciated.

This is the error. The WSDL is publically available if you want to try importing.

> An error occurred while attempting to find services at 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/PPP/6.35/EPS_ProfileCreateRQ.wsdl'. 
> CData elements not valid at top level of an XML document. Line 1, position 3
> Sub Error...
> Metadata contains a reference that cannot be resolved: 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/PPP/6.35/xml.xsd'.

**Comment by rjts** [comment]
Fyi: I've sent a support request to the Sabre developers in case its a schema issue in a sub file. I'll update this if I get a response. As well as it working with the .Net Framework 4.6.2 svcutil app, I also tried it with the really old wsdl.exe app and that works as well.

**Comment by sameera** [comment]
@rjts Could you be experiencing the same thing as:
https://github.com/dotnet/wcf/issues/2197
The fix is in VS 15.6 Beta or use the dotnet-svcutil as described in the thread.

**Comment by rjts** [comment]
Thanks - I'm was using VS 15.5.6

Just downloading VS 15.6.0 Preview 4.0 - I'll give you an update once its installed :-)

**Comment by mlacouture** [comment]
@rjts thank you for reporting this issue.  A fix for this issue is available in [Visual Studio 2017 v15.6-Preview 4](https://www.visualstudio.com/vs/preview/), I hope you can try the preview.

**Comment by rjts** [comment]
I Downloaded and tried with VS 15.6.0 Preview 4.0 - It generates exactly the same error.
I tried the command line version and it too generated the same error.

So no the "fix" didn't seem to correct the issue.

**Comment by mlacouture** [comment]
@rjts, you are right, the fix is not yet available, it will actually be available with the release of Visual Studio 2017 v15.7 Preview 1, currently scheduled to ship around March 7.  Sorry for the confusion.
