### ISSUE TITLE
How to set ClientCredentialType as UserName in .net Core?

### ISSUE THREAD

**Issue by sturlath** [dotnet/wcf#2544]
I have been trying to use WCF in a .net core 2.0 project, for 2 days without luck. I have a [StackOverflow ](https://stackoverflow.com/questions/48625444/calling-a-soap-service-in-net-core/48647785#48647785) question with all my tries and problems but I´m stuck! I just can´t reproduce my old code in .net Core.

Is it even possible to use ClientCredentialType.UserName í .net Core project? 
And how is it done?

If only there were more tests. [This unittest](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs) is basically the only thing I found and its quite basic.

I so hope somebody here can help me.

dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

**Comment by zhenlan** [comment]
@sturlath, what's the binding you are using? Please note message security is not supported (#8). Here are some examples of supported bindings.

https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs

**Comment by sturlath** [comment]
Thank you so much @zhenlan. My fault not finding these tests. I tried to search for them but maybe I did´t find them because I did´t know what to search for. The barrier to entry to WCF if quite high, especially if you don´t touch it often (years apart). I tried to amend that by [answering my own question](http://especially/) on StackOverflow and point to the resources needed to solve my problem. Please feel free to add to that answer if you have some other resources we should know about.

But thank you for your help. It was much appreciated!

**Comment by zhenlan** [comment]
I am glad it worked for you, @sturlath. Thanks for sharing your answers on the stackoverflow, which may help more people out there.
