### ISSUE TITLE
.NET Standard 2.0, WCF Connected Service (Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0)

### ISSUE THREAD

**Issue by cabadam** [dotnet/wcf#2546]
This is essentially the same thing that was reported in #2111.

1. Create a trivial WCF service (the one that comes from the VS template is fine).
2. Create a .NET Standard 2.0 library, and add a Connected Services item to this WCF service.
3. Create a Desktop console (.NET 4.6.2 in my case) and reference the .NET standard class library.
4. Create an instance of the WCF client object and execute a call.
5. Observe that the application throws an exception on startup:

> Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

6. Try the workaround mentioned in #2111 of modify the .NET standard library's csproj file to have the following instead of a single TargetFramework:
`<TargetFrameworks>net462;netstandard2.0</TargetFrameworks>`
7. Re-run the console application.  It will now get slightly further, before failing on:
> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

Similar reports:
https://www.codeproject.com/Questions/1198295/Do-I-need-to-install-NuGet-package-on-NET-standard
https://social.msdn.microsoft.com/Forums/vstudio/en-US/954059c8-adb6-4fe2-939a-e60da1587545/do-i-need-to-install-nuget-package-on-net-standard-library-or-executable-project-or-both?forum=wcf

Even if the workaround were to work, I'm not sure that would be the right answer, as now two DLLs are created, one for .NET Standard 2.0, and one for .NET 4.6.2.  That seems like it defeats the purpose of .NET Standard?

**Comment by cabadam** [comment]
I uploaded a sample solution demonstrating this:
https://github.com/cabadam/dotnet-wcf-2546

**Comment by mlacouture** [comment]
Hi @cabadam 
Thank you for reporting this issue. We will look into it.

**Comment by PeterMontgomery777** [comment]
I'm experiencing the same problem but in my case the console test app is also .net core 2.0

**Comment by electricessence** [comment]
This is an issue for me because I have a 'connected service' in my ASP.NET Core 2 web application.  If I remove the connected service. `dotnet publish` works without issue.  But this isn't an option for me.  I need the connected service. :(

**Comment by azbest208** [comment]
Same for me, but the exception is thrown when I connect to WCF service impersonated. Without impersonation works without issues.

**Comment by MSGaryWang** [comment]
WCF Connected Service would add "System.ServiceModel.Http" NuGet package to your netstandard2.0 library but this dependency won't be picked up by your console app project even it does reference to that netstandard2.0 library. The workaround is adding the same "System.ServiceModel.Http" NuGet package to your console app project by yourself so it would be referenced correctly. You can do this by using "Manage NuGet Package" menu item or just updating the packages.config file, for example

&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;packages&gt;
**&nbsp;&nbsp;&lt;package id="System.ServiceModel.Http" version="4.4.1" targetFramework="net461" /&gt;**
**&nbsp;&nbsp;&lt;package id="System.ServiceModel.Primitives" version="4.4.1" targetFramework="net461" /&gt;**
&lt;/packages&gt;

Please let me know if this solution working for you.

**Comment by electricessence** [comment]
@MSGaryWang I'll try it next week

**Comment by TobiasWen** [comment]
@MSGaryWang I had the exact same problem as the issue creator and for me your advice was at least a workaround to get things done. Thank you for that!

**Comment by mbasaran** [comment]
@MSGaryWang That solved the issue for me. Thanks.

**Comment by cabadam** [comment]
@MSGaryWang I can confirm this does workaround the issue.  For clarify:  Is manually adding these references the intended solution?  Or is the dependency supposed to be picked up automatically? (I'm hoping for the latter)

**Comment by MSGaryWang** [comment]
We will pass this issue to another team since this is not a WCF only problem but how netstandard library integrated with other project.

**Comment by Saritha535** [comment]
I am also facing the same issue. I am using window forms not the WCF.
**Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**

Please could you assist to solve this issue.

**Comment by AndyBevan** [comment]
In my scenario I had a framework project referencing my netstandard library.  I found that I had to add <RestoreProjectStyle>PackageReference</RestoreProjectStyle> to the framwork Project csproj file in addition to adding the nuget packages System.ServiceModel.Http and System.ServiceModel.Primitives

**Comment by Saritha535** [comment]
Which version you added reference for System.ServiceModel.Http and System.ServiceModel.Primitives from nuget packages.

**Comment by AndyBevan** [comment]
Actually - I believe that to use my Standard Library from netframework I only had to add `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` to the framework csproj.  

I used System.ServiceModel.Http and System.ServiceModel.Primitives version 4.4.1

**Comment by zhenlan** [comment]
Related to dotnet/standard#410.

**Comment by x6060x** [comment]
What fixed the issue for me was adding:
<Reference Include="System.Net.Http" />
in the WCF project (using 4.7.2) and adding:
<add assembly="System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"/>
to the web.config -> system.web -> compilation -> assemblies.

After doing this I was finally able to use HttpClient in the WCF project.

**Comment by AlpeshValvi123** [comment]
I have added these two packages from NuGet and its work for in .Net Console and MVC Core Web App but **not working MVC 5 web application**.
1. System.ServiceModel.Http
2. System.ServiceModel.Primitives

The application is just waiting for a response. 

**So it's not supported for MVC 5 Application?**
