### ISSUE TITLE
WSTrust13 not implemented

### ISSUE THREAD

**Issue by gislikonrad** [dotnet/wcf#2557]
In the TrustVersion class, there is no static property for WSTrust13. Normally, I wouldn't have a gripe with this, but the fact that the constructor for TrustVersion is internal blocks me from implementing WSTrust13 myself.

Any chance on changing the constructor on TrustVersion to protected, at least? ...or implementing WSTrust13?

**Comment by mconnew** [comment]
Unfortunately this isn't going to help you. We do have the class TrustVersion in our api surface, but this is an artifact of where our api's came from. Our current api's in netstandard are based on the api's which were available in Windows Store apps on Windows 8 which actually just used the full desktop framework under the covers. That api was largely derived from the api in Silverlight. We don't have all the dependencies in the rest of netstandard that we would need to implement a lot of the WS-* protocols, especially the security protocols such as WS-Trust. This means that most of the code you would need to implement WSTrust13 is simply missing and we have stubs behind the affected public api's which simply throw if you try to use them. We aren't able to remove api's, only add them which means we're stuck with having the TrustVersion class in our api but no way to provide any implementation.

**Comment by mconnew** [comment]
@gislikonrad, do you have any further questions? If not, I'll close the issue.

**Comment by gislikonrad** [comment]
I'm good. Feel free to close the issue.
