### ISSUE TITLE
ServiceHost class unavailable on .Net Core 2.0

### ISSUE THREAD

**Issue by apdirexyon** [dotnet/wcf#2559]
Hi,

I'm searching a lot of ways on the web and among the available Nuget packages, to implement ServiceHost and I found quite nothing, neither in the documentation...

Is it possible to obtain a code/package which ServiceHost class is implemented for .Net Core 2.0?

How can we resolve this problem otherwise? 

Thank you for your time.

**Comment by zhenlan** [comment]
@apdirexyon, WCF has only client support on .NET Core. The ServiceHost is a server feature, which is not supported on .NET Core. The readme of this repo has a bit details of targeted scenarios etc.

**Comment by karenkuang2013** [comment]
If ServiceHost is not available on .NET Core, how to host a WCF Service in a console app?

**Comment by VasTheGreek** [comment]
> 
> 
> If ServiceHost is not available on .NET Core, how to host a WCF Service in a console app?

You can use a 3rd party lib called SoapCore.

**Comment by AAATechGuy** [comment]
Try use CoreWCF 
https://github.com/CoreWCF/CoreWCF
