### ISSUE TITLE
how to use wcf service in vs code

### ISSUE THREAD

**Issue by MansoorJafari** [dotnet/wcf#2576]
Hi
how can I add wsdl service to dotnet core project in visual studio code on mac?

please help.

**Comment by zhenlan** [comment]
@MansoorJafari, we are working in progress making svcutil as a standalone CLI tool (#1222). With that, you will be able to run on mac.

**Comment by mlacouture** [comment]
Hi @MansoorJafari 
You now have the option to add a web service reference to your projects using the [dotnet-svcutil tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide). Let us know about your experience with this tool.
thank you!
