### ISSUE TITLE
Is client certificate authentication supported in Lambda (Linux)?

### ISSUE THREAD

**Issue by bungceting** [dotnet/wcf#2582]
here are the details I have got for both of my WCF server and client test apps:

- server is on IIS on WCF wshttpbinding, server certificate signed by our internal CA
- server requires client certificate
- client uses custombinding and client cert sign by same CA
- client's binding object uses both CustomBinding + HttpsTransportBindingElement (as per generated proxy) however it has been manually amended with HttpsTransportBindingElement.RequireClientCertificate = true (otherwise, in Kestrel, the client app does not use client cert upon initiating handshake with WCF server)
- client app uses a custom validator for validating the server cert ssl auth (myServiceClient.ClientCredentials.ServiceCertificate.SslCertificateAuthentication) to bypass server cert validity

All works fine in Kestrel (dev environment) but on Lambda (Linux) we are experiencing the following platform related exception

Caught AggregateException: 'System.AggregateException: One or more errors occurred. (The handler does not support client authentication certificates with this combination of libcurl (7.51.0) and its SSL backend ("NSS/3.28.4").) ---> System.PlatformNotSupportedException: The handler does not support client authentication certificates with this combination of libcurl (7.51.0) and its SSL backend ("NSS/3.28.4").
at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of inner exception stack trace ---

If you have seen this before or know the solution, please provide any inputs, much appreciated

Thanks

**Comment by zhenlan** [comment]
> The handler does not support client authentication certificates with this combination of libcurl (7.51.0) and its SSL backend ("NSS/3.28.4").

@mconnew suggested you may need to install the version of libcurl that uses the openssl backend.

**Comment by Lxiamail** [comment]
Please let us know if you have any other question.
