### ISSUE TITLE
WS Security in .NetCore 2.0

### ISSUE THREAD

**Issue by Giolla** [dotnet/wcf#2605]
Hi, i'm trying to implement following in .NetCore 

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cus="http://siebel.com/CustomUI">
   <soapenv:Header> 
      <wsse:Security xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/07/secext"> 
         <wsse:UsernameToken xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility"> 
         <wsse:Username>XXXXXX</wsse:Username> 
         <wsse:Password Type="wsse:PasswordText">XXXXXX</wsse:Password> 
         </wsse:UsernameToken> 
      </wsse:Security> 
      <soapenv:Header/>
```

Above Xml works in SoapUI with no problem.

Endpoint address:

```
if ((endpointConfiguration == EndpointConfiguration.Some_Query))
 {
 return new System.ServiceModel.EndpointAddress("https://..someUrl../?
 SWEExtCmd=Execute&SWEExtSource=SecureWebService");
 }
```

Calling Client:     
 
```
private QueryClient GetClient()
 {
 var uri = string.Format("https://..someUrl../?SWEExtCmd=Execute&UserName=
 {0}&Password={1}", userName, password);
 var client = new QueryClient(QueryClient.EndpointConfiguration.Some_Query, uri);

 client.ClientCredentials.UserName.UserName = getUserName;
 client.ClientCredentials.UserName.Password = getPassword;
 return client;
 }
```

When i imported WSDL with  Microsoft WCF Web Service Reference Provider, endpoint configuration was defaulted to : 

```
if ((endpointConfiguration == EndpointConfiguration.Some_Query))
 {
  System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
  result.Security.Transport.ClientCredentialType = 
  System.ServiceModel.HttpClientCredentialType.Basic;
  result.MaxBufferSize = int.MaxValue;
  result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
  result.MaxReceivedMessageSize = int.MaxValue;
  result.AllowCookies = true;
  result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
  return result;  
 }

```
Question: Should i be using BasicHttpBinding or BasicHttpsBinding? i tried both but i'm getting an error.

I'm getting 

><p>An error occurred while trying to process your request.  This error indicates a problem with the configuration of this server and should be reported to the webmaster (along with any errors listed below). We apologize for the inconvenience.</p>
no matter what i try

**Comment by zhenlan** [comment]
@Giolla WS security is not supported by WCF on .NET Core.

**Comment by Lxiamail** [comment]
Please let us know if you have any additional idea.

**Comment by seamys** [comment]
@zhenlan @Lxiamail 
Is there has other solution?

**Comment by zhenlan** [comment]
@seamys Sorry for lacking of details. The issue was closed as it's mostly part of issue #31, which does not have a solution at this point. You can find more details in the discussion of #31.

**Comment by Srinivas289** [comment]
@zhenlan  Is there any solution  ? I am in the same boat now.

**Comment by Srinivas289** [comment]
@Giolla did you find any alternative solution ?

**Comment by csevillasigtic** [comment]
I fond this 

https://www.example-code.com/dotnet-core/xmldsig_soap_wsse_SecurityTokenReference.asp
