### ISSUE TITLE
HttpTransportBindingElement.KeepAliveEnabled Incorrect at Service

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2624]
The test case...
Binding_Http_BasicHttpBindingTests/HttpKeepAliveDisabled_Echo_RoundTrips_True
Located: ...\System.Private.ServiceModel\tests\Scenarios\Binding\Http\BasicHttpBindingTests.4.0.0.cs

It is failing on the following platforms...
- Fedora.27.Amd64-x64-Release
- Fedora.26.Amd64-x64-Release
- Debian.90.Amd64-x64-Release 
- OSX.1013.Amd64-x64-Release 

The test case sets KeepAliveEnabled to false on the client and the Server side expects it to still be set to false, instead it has changed to true.

@mconnew is opening an issue in CoreFx where the bug exists.

**Comment by zhenlan** [comment]
The issue is tracked in dotnet/corefx#27566.

**Comment by Lxiamail** [comment]
SocketHttpHandler is available and may have fix it.

**Comment by StephenBonikowsky** [comment]
Still haven't had time to check and see if this is still an issue.

**Comment by StephenBonikowsky** [comment]
Enabled and testing in VSTS, build running.

**Comment by StephenBonikowsky** [comment]
PR #2798 for master.
Port to release/2.1.0 once it is in master.
