### ISSUE TITLE
Incorrect exception returned from Service in service-restart scenario.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2626]
When an operation fails mid-operation the client should receive a Communication Exception, instead we are getting an EndpointNotFoundException.

Test case: ExpectedExceptionTests/ServiceRestart_Throws_CommunicationException 
Located: ...\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.4.1.0.cs

This scenario is only failing on platform...
   - OSX.1013.Amd64-x64-Release 

This is a change of behavior as it returns the expected exception on OSX.1012

@mconnew to open CoreFx issue.

**Comment by Lxiamail** [comment]
SocketHttpHandler is available and should fix this

**Comment by StephenBonikowsky** [comment]
Haven't had time to verify yet.

**Comment by StephenBonikowsky** [comment]
Port to release/2.1.0 once PR #2787 is merged.

**Comment by StephenBonikowsky** [comment]
Port PR is #2797
