### ISSUE TITLE
How do you configure multiple Uri's in Connected Service .net Core 2.0?

### ISSUE THREAD

**Issue by DasNaughtie** [dotnet/wcf#2636]
I know I can do this by changing the generated reference file but can this not be done via some sort of config file out of the box?
Also, how do you edit a connected service?

**Comment by mlacouture** [comment]
Hi @DasNaughtie 

What exactly are you trying to achieve? if the service hosts different endpoints the generated code should have a corresponding configuration item in the client's `EndpointConfiguration `enum.

If what you are trying to do is to further configure an endpoint like to add user credentials, the generated code provides a partial method you can implement in your code for this purpose, it looks like the following:

`    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);`

hope this helps,
