### ISSUE TITLE
WCF uwp core  bug  Result corruption when using net.tcp

### ISSUE THREAD

**Issue by lvandenb** [dotnet/wcf#2642]
I have a bug in the UWP WCF client sided, with returned results  and net.tcp protocol.
And it only happens when also the datatable in the result type has no rows.  

When using net.tcp or https with wcf client in .net, everything is ok, 
and also when using http from core uwp client
But when using net.tcp from the core uwp client some strings are null  ( zonename below)

So it is dependent on the net.tcp protocol and a zero row datatable ?

The result type  is below. 
net.tcp used by  uwp WCF core returns correct results when there are rows in the table.

```
[DataContract]
    public class WhosInType
    {
        [DataMember]
        public string zoneName { get; set; }="-";
        [DataMember]
        public bool gz  { get; set; }=  false;
        [DataMember]
        public bool needVm { get; set; } = false;
        [DataMember]
        public bool oneVm { get; set; }= false;
        [DataMember]
        public System.Data.DataTable dtPeople { get; set; } =null;
         
        public  WhosInType ()
        {
            zoneName = "-";gz = false;needVm = false;oneVm = false; dtPeople = null;
        }

}
```

**Comment by lvandenb** [comment]
as a workaround, when I have the datatable with zero rows of data  ( = only the schema), I just set the datatable to null.
Then all other fields stay ok.

**Comment by zhenlan** [comment]
@lvandenb, which version of `Microsoft.NETCore.UniversalWindowsPlatform` package you using and which version of `TargetPlatformMinVersion` you have in your project?

It will be helpful for further investigation if you can share a repro.

**Comment by lvandenb** [comment]
@zhenlan 
the Microsoft.NETCore.UniversalWindowsPlatform  is 6.0.8
TargetPlatformMinVersion  is 16299

the behaviour is even stranger.
When in use the wcf via https, and use a null datatable in the result ( type WhosInType above) then all fields are zeroed. ( all bools are false, string is null) . But a datatable with zero rows works fine.
When use tcp, it is the opposite. A datatable with zero rows results in alle fields in the result type to be zeroed, but a null datatable leaves the other fields ok.

**Comment by zhenlan** [comment]
@lvandenb thanks for the information. Can you help the investigation a bit here? Without using WCF, just use DataContractSerializer to serialize and deserialize the data, do you observe the same behavior?

**Comment by Lxiamail** [comment]
Please let us know if there is anything that we can help.
