### ISSUE TITLE
When is issue #2368 going to be released for 2.0.x?

### ISSUE THREAD

**Issue by carlottokjellkvist** [dotnet/wcf#2656]
Hi,

We have solution that will soon be released for production. Our backend solution is implemented on .netcore 2.0 and we are at the moment needing to know if and when this issue will be released due to that we have some long time running requests that times out now and then. 

If we there will not be any release in a short amount of time we will be needing to change it to full .net framework which will make some headaches.

Br
Carl-Otto

**Comment by mconnew** [comment]
PR for the issue on the servicing branch is #2665

**Comment by zhenlan** [comment]
@carlottokjellkvist please check out https://github.com/dotnet/wcf/issues/2368#issuecomment-375775839. We have a release candidate build.

**Comment by zhenlan** [comment]
Version 4.4.2 System.ServiceModel.* packages have been released to nuget.org this morning.
https://github.com/dotnet/wcf/releases/tag/v2.0.7
