### ISSUE TITLE
Do not update Microsoft.Private.CoreFx.UAP

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2660]
Current CoreFx builds are producing empty Microsoft.Private.CoreFx.UAP packages.
Need to move master to LKG version of the ackage, disable auto updating of the package and track the fix in CoreFx so we know when to re-enable auto updates of this package.

- [x] Revert back to LKG version
- [x] Disable auto update for this package
- [ ] Track dotnet/corefx#27805 and re-enable auto update once it is merged and the new built version is available.

**Comment by Lxiamail** [comment]
the depended track item is completed, this work item is unblocked

**Comment by StephenBonikowsky** [comment]
Completed with #2785
