### ISSUE TITLE
User-Agent has incorrectly formatted header value

### ISSUE THREAD

**Issue by carntzen92** [dotnet/wcf#2673]
See [this StackOverflow post](https://stackoverflow.com/q/49262393/2957232).  

Basically, I've been working with a .NET Standard library with a WCF reference to a SOAP web service. When I add the library as a reference to a project using the .NET framework, and set the user agent using the method outlined by [this MSDN blog post](https://blogs.msdn.microsoft.com/mohamedg/2012/12/13/adding-http-headers-to-wcf-calls/), everything is just fine. When I reference the library in a .NET Core 2.0 project, I get a System.FormatException for the value I set to the "User-Agent" header.  

For example, something like the following works in the framework, but throws an exception in Core (see the SO link for full code, this is only the implementation of IClientMessageInspector.BeforeSendRequest): 
 
    public object BeforeSendRequest(ref Message request, IClientChannel channel)
    {
        HttpRequestMessageProperty property = new HttpRequestMessageProperty();
        
        //Bad, causes an exception
        property.Headers["User-Agent"] = "Mozilla/4.0 (compatible; MSIE 6.0; MS Web Services Client Protocol 4.0.30319.42000)";

        //Works, but insufficient
        //property.Headers["User-Agent"] = "Mozilla/4.0";

        request.Properties.Add(HttpRequestMessageProperty.Name, property);

        return null;
    }

In the above mentioned SO link, user [Jeroen Mostert](https://stackoverflow.com/users/4137916/jeroen-mostert) says it is [definitely a bug.](https://stackoverflow.com/questions/49262393/user-agent-has-incorrectly-formatted-header-in-net-core#comment85563745_49262393)

**Comment by mconnew** [comment]
I've done some poking around in the HttpHeaders code base and we can make a simple fix to correctly support this. HttpRequestHeaders.Add("User-Agent", value) actually looks up the User-Agent header name in a list of known headers and retrieves a special internal parser which handles the multi-valued ProductInfoHeaderValue collection taking into account the fact that User-Agent uses a space to delimit multiple values instead of the usual comma.

**Comment by mconnew** [comment]
I have a PR out to fix this issue.
