### ISSUE TITLE
How to provide credentials, unauthorized with "Anonymous"

### ISSUE THREAD

**Issue by entith** [dotnet/wcf#2679]
I am trying to connect to Microsoft Dynamics NAV web service and keep getting the below error:

```
The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Negotiate'.
```

I cannot figure out how to set the credentials to connect with. I have tried setting/changing `client.ClientCredentials.UserName`, `client.ClientCredentials.Windows.ClientCredential`, and `client.ClientCredentials.Windows.AllowedImpersonationLevel` (where `client` is an instance of the `System.ServiceModel.ClientBase` class generated by the tool) with absolutely no change to the resulting error.

**Comment by mconnew** [comment]
@entith, you aren't setting the client credential type. You need to tell the binding what type of credential is being used as well as set the correct credential on `ClientCredentials`. You would do something similar to this:
```csharp
  var basicHttpBinding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
  basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
  endpointAddress = new EndpointAddress("http://localhost/MyService.svc");
  factory = new ChannelFactory<IMyService>(basicHttpBinding, endpointAddress);
  factory.Credentials.UserName.UserName = username;
  factory.Credentials.UserName.Password = password;
```

The exception message is saying you are using authentication scheme `Anonymous` which means you are using `HttpClientCredentialType.None` which is the default value.
