### ISSUE TITLE
Ensure proper buildtools support story for uwp branches.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2681]
Buildtools never snapped a branch for uwp6.0 and only recently created one for uwp6.1, and this was done because of the TLS 1.2 requirement from GitHubClient.

The buildtools uwp6.1 branch has been fixed (was missing commits from master needed by WCF) but there is no dedicated uwp6.0 branch.

Issue and discussion at dotnet/buildtools#1957

**Comment by Lxiamail** [comment]
This has been completed in build tools
