### ISSUE TITLE
Request for support for certificate validation exceptions to the default HTTPS validation

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#2682]
As far as I know, currently the only way to validate server certificates in a custom way is through deriving from the X509CertificateValidator class.
That API provides only information on the certificate and by context the target host name. The HTTPS stack that is used by WCF has already validated the server using the default validation (e.g. the OS-based validation). The information of that validation is provided to WCF in the form of an SslPolicyErrors value and the status of the trust chain (according to the default chain policy).

My use case is that I would like to implement a server certificate validation that extends the default validation by handling only the cases where the default validation found errors and use the validation errors to decide if an exception would be made for this server.
The WCF API for this would always call my validator even if the default validation approved of the server.

This leaves me the only option to try to repeate the default validation process on the certificate provided by WCF. This means that I need either a way to call into the default implementation or reimplement the default validation.

I think there is no API (probably even native API) that would allow me to just validate a certificate for an HTTPS host without the actual TCP network stack. Reimplementing the default validation migth not be possible as that might change over time.

**Comment by mconnew** [comment]
@atanasa, you are correct for the current release. The difficulty we have is we are using the `System.IdentityModel` validation model which doesn't allow the SslPolicyErrors to be passed. When you tell WCF to explicitly use ChainTrust validation (even though that's what `HttpClientHandler` does by default if you don't specify this) then WCF installs it's own validation code. An example of how this is configured is [here](https://github.com/dotnet/wcf/blob/c375f6db81e57e0a8fd9b3c50f15264b6b85eab3/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs#L191). The implementation WCF uses for ChainTrust validation can be found [here](https://github.com/dotnet/wcf/blob/a2c95ad9e5cb2fff465655ae234454cf6f1c0f83/src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/X509CertificateValidator.cs#L157). We create and pass in the chain policy [here](https://github.com/dotnet/wcf/blob/1587d617b0073b6d054509160d5ada80b75a065c/src/System.Private.ServiceModel/src/System/ServiceModel/Security/X509ServiceCertificateAuthentication.cs#L49).  
In the next release, we've added a new extensibility point which will allow you to do exactly what you want. The new extensibility point allows you to modify or replace the HttpClientHandler before it is first used. An example of it's usage can be seen [here](https://github.com/dotnet/wcf/blob/c365d1a7421929f605942ef777b5cd772f5e3439/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs#L87). You will need to create a behavior to add your own delegate which is able to modify the HttpClientHandler. The behavior for our test can be found [here](https://github.com/dotnet/wcf/blob/54633f6a2a5870ca10cc916524a2896e60a6e3f9/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/HttpBindingTestHelpers.cs#L12) and is a lot more complicated than you need. All you need to do is replace the `GetHttpMessageHandler` method with an implementation similar to this:
```csharp
    public HttpMessageHandler GetHttpMessageHandler(HttpClientHandler httpClientHandler)
    {
        // modify HttpClientHandler to use your own service certificate validation callback handler
        return httpClientHandler;
    }
```
You don't need any other classes other than the behavior itself in your usage. This will be available with .Net Core 2.1.

**Comment by atanasa** [comment]
Are there any plans to support this on netstandard? I would like to converge my code to netstandard at some point. I assume the new feature would not be supported on .net framework.

**Comment by mconnew** [comment]
This feature didn't require any new public api surface so you can use it when targeting netstandard. It just won't do anything when the runtime isn't .Net Core. This feature can't work on the full .Net Framework as the entire implementation is different there. The full framework uses HttpWebRequest whereas .Net Core uses HttpClient/HttpClientHandler. So if you know you will only be running on .Net Core (or UWP when the next UWP release happens which is aligned with .Net Core 2.1), then you are safe to use this when targeting netstandard. If you do happen to run on a different runtime, it will just be a no-op.
