### ISSUE TITLE
Any chance of us extending core 1 wcf source to have http proxy address?

### ISSUE THREAD

**Issue by bungceting** [dotnet/wcf#2691]
Dumb question alert: what is the chance for us to extend core 1 wcf source to have the following feature so that we can specify proxy address?

https://github.com/dotnet/wcf/pull/1901/commits/567b71760dce959fc3cc11f2fa0d741bc1ecf84f?diff=unified

Thanks!

**Comment by zhenlan** [comment]
If I understand your question correctly, you mean you like to fork our v1 code and port the proxy feature back there? I'm worried some dependencies were not available in v1 but I will let @mconnew comment on this.

**Comment by bungceting** [comment]
Yes that is correct @zhenlan - I wonder if it is worth the effort

Thanks

**Comment by Lxiamail** [comment]
It will be a complicated port. In our opinion, it's not worth the effort.
