### ISSUE TITLE
Either enable Digest authentication test without a domain or add an instruction to run it in a domain

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#270]
It's preferable to run it in the CI machine. If not possible, we should add an instruction to run it in a domain.

**Comment by roncain** [comment]
We ultimately need all developers to be able to run this test, even if it requires special setup and xunit traits.  I understand we may be blocked on the xunit traits right now.  We should explore what new things we can do now that Bridge can run on a different machine.

**Comment by hongdai** [comment]
We have enabled a digest authentication test without a domain. However, it's still valuable to keep the domain test as it's the major scenario. The remaining work item here is to add the instruction to the manual test document.

**Comment by roncain** [comment]
I think the remaining work items are for me to use [ConditionalFact] on this test and add documentation for it.

**Comment by roncain** [comment]
Possible approaches are:
1. Compare env var USERDOMAIN to machine name,  If not same, it is domain joined (quick and dirty)
2. Compare env var LOGONSERVER and COMPUTERNAME.  If not same, is domain joined (quick and dirty)
3. Create new WebAPI endpoint that requires windows auth, then have BridgeClient attempt to contact it via HttpClient using default credentials.  Harder but is more accurate test.  Trade-off -- BridgeClient doesn't support windows auth, so test needs to be conditional.

**Comment by roncain** [comment]
Closing because we have added [ConditionalFact] to assert this test runs only on a domain-joined machine.  We still need #1007 and #958 to be resolved to detect when we are domain-joined before this test will run again.
