### ISSUE TITLE
Transform and Update Reference Provider on Build

### ISSUE THREAD

**Issue by Citizen39** [dotnet/wcf#2700]
Is it possible to transform and then update a WCF connected service on a client when building the client? Is there a pre-build command I can use for this?

I unit test locally, having a WCF based service running locally (e.g. with a uri of net.tcp://localhost:1234/MyWCFService). Once the service is deployed to another location (e.g. net.tcp://uat.internaluri.ourcompany.com:1234/MyWCFService), I need to first transform the ConnectedService.json for the service reference, and then do an "Update Microsoft WCF Service Reference Provider...", before publishing the client. 

Asking because the WCF service is deployed with configurations that define the host base address in the app.config (eg:  `<add baseAddress="net.tcp://localhost:1234/MyWCFService" />`. I have no problem transforming that when building for the appropriate deployment. Problem comes in when the service is deployed to a different location uri than where the client is. 

All would be fine if the client was on the same machine as the service. Localhost will work fine, but if the service is on a different machine, I need to make sure that connected service referenced in the client is valid, and that  `GetEndpointAddress()` in generated Reference.cs has the correct uri in the end point address.

Ref: Using VS 2017 Ent. V 15.7.0 Preview 1.0. Client is .NET CORE 2.0

**Comment by Citizen39** [comment]
Ah ha! Just found this: #2420 and #1222 . Anything else I might have missed?

**Comment by mlacouture** [comment]
@Citizen39, re-reading your post it sounds like you need to automate the web service reference generation for your unit-tests and in that case once issue #1222 is solved you will be able to implement a solution for this.  Let us know if you need further assistance, closing for now.  
thanks,
