### ISSUE TITLE
Rename repository to wcf client, is confusing

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/wcf#2713]
I see public charts, like this one https://twitter.com/ziki_cz/status/977239890642391040?s=19, and I thing is confusing using only the term wcf.

**Comment by Lxiamail** [comment]
@karelz looks like we have some confusion around the messaging. Can you respond?

**Comment by karelz** [comment]
@xrkolovos what exactly is confusing? The chart lists 4 dotnet repos - coreclr, corefx, core-setup and wcf. By name.

**Comment by xrkolovos** [comment]
The name "wcf" alone is confusing. There are people that still don't know everything about the .net evolution. By saying wcf you mean the full wcf. This is the wcf client.

**Comment by karelz** [comment]
Then you are questioning the repo name, but not the charts, correct?

**Comment by Lxiamail** [comment]
The repo has description about the scope of the repo, hope that helps to reduce any confusion. Changing the repo name is a breaking change.
