### ISSUE TITLE
Unable to "downgrade" protocol from HTTPS to HTTP

### ISSUE THREAD

**Issue by creyke** [dotnet/wcf#2714]
The service I want to consume is exposed over both HTTP and HTTPS... these work fine on my local box (64bit win10) over either HTTP or HTTPS, however they fail on 32bit Win10 in Azure Web Jobs (even though I've configured HTTP, not HTTPS). They also fail on Linux as well (error for both below).

Short term, I am happy to use HTTP, but I cannot work out how to tell the wcf client to do so, as even when I supply an "http" url as the endpoint (in the wcf client constructor), I still get the below exception (implying https is still being attempted).

Works:
```
  OSDescription : Microsoft Windows 10.0.16299
  OSArchitecture : X64
  ProcessArchitecture : X64
  FrameworkDescription : .NET Core 4.6.26020.03
```
Fails:
```
  OSDescription : Microsoft Windows 10.0.14393 
  OSArchitecture : X64
  ProcessArchitecture : X86
  FrameworkDescription : .NET Core 4.6.26212.01
```
Error:
```
An error occurred while sending the request.
at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
```

Relates to https://github.com/dotnet/corefx/issues/15661

**Comment by Lxiamail** [comment]
@creyke Can you provide the exception details and configuration of your bindings?

**Comment by Lxiamail** [comment]
@creyke Please let us know if you have any more question
