### ISSUE TITLE
ggggggggg

### ISSUE THREAD

**Issue by CrWiii** [dotnet/wcf#2721]

**Comment by mlacouture** [comment]
Hi @CrWiii 
I tried the service you provided and the generated code works just fine.  Can you please elaborate on what you are trying to accomplish?
thank you!

**Comment by mlacouture** [comment]
BTW: as a note of precaution just in case, if this service is yours and it is meant to be private you should implement some sort of access security.

**Comment by CrWiii** [comment]
it will be private np.
I don't know if my code is the problem, but i was trying to use any method but I can't, this is my code for other method call "Registrar" 

`public async Task<IActionResult> Index(){

            ServiceClient client = new ServiceClient();

            General oGeneral = new General();
            string oTipoComprobante = "1"; 
            ENComprobante oENComprobante = new ENComprobante();
            string Cadena = "";
            string TipoCodigo = "1";
            string CodigoBarras = "";
            string CodigoHash = "";
            ENErrorComunicacion oListaError = new ENErrorComunicacion();
            int IdComprobanteCliente = 0;
            string Otorgar = "1";
ENEmpresa ObjEmpresa = new ENEmpresa();
            ObjEmpresa.NombreComercial = "CLINICA PROVIDENCIA";
            ObjEmpresa.Ruc = "20477983708";
            ObjEmpresa.CodigoTipoDocumento = "06";
            ObjEmpresa.RazonSocial = "INVERCONSULT S.A.";
            ObjEmpresa.CodDistrito = "150136";
            ObjEmpresa.Calle = "CAL.CARLOS GONZALES NRO. 250 ";
            ObjEmpresa.Urbanizacion = "URB. MARANGA (250-252-256-260.ALT.CDRA.26 DE LA MARINA)";
            ObjEmpresa.Departamento = "LIMA";
            ObjEmpresa.Provincia = "LIMA";
            ObjEmpresa.Distrito = "SAN MIGUEL";
            ObjEmpresa.CodPais = "PE";
            oGeneral.oENEmpresa = ObjEmpresa;
ENComprobante ObjComprobante = new ENComprobante();
            ObjComprobante.FechaEmision = DateTime.Parse("02-04-2018 00:00:00");
            ObjComprobante.TipoComprobante = "01";
            ObjComprobante.Serie = "001";
            ObjComprobante.Moneda = "PEN";
            ObjComprobante.Ruc = "20549500553";
            ObjComprobante.TipoDocumentoIdentidad = "06";
            ObjComprobante.RazonSocial = "ASERCO EB EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA";
            ObjComprobante.ImporteTotal = 250.00M;
            oGeneral.oENComprobante = ObjComprobante;
RegistrarResponse Resultado = await client.RegistrarAsync(oGeneral, oTipoComprobante, Cadena, TipoCodigo, CodigoBarras, CodigoHash, oListaError, IdComprobanteCliente, Otorgar);`

but I got the same error 

NotImplementedException: The method or operation is not implemented.
TCI_WS_T.ServiceClient.RegistrarAsync(General oGeneral, string oTipoComprobante, string cadena, string tipoCodigo, string codigoBarras, string codigoHash, ENErrorComunicacion oListaError, int idComprobanteCliente, string otorgar) in Reference.cs, line 28702

@mlacouture  can you show me how can I consume thoose method ??? I'm new in asp.net core 2

**Comment by mlacouture** [comment]
@CrWiii can you tell me the steps you are following to get into this problem (repro steps starting from scratch), and what version of Visual Studio are you using?

**Comment by CrWiii** [comment]
Visual Studio 2017 Community Edition 15.6.1
1. Create a new project >.Net Core >ASP.NET Core Web App 
2. Add Connected Services >Microsoft WCF Web Service Reference Provider >
     add the uri > http://egestor.dev.efacturacion.pe/WCF_TCI/Service.svc?wsdl
     add the namespace: > TCI_WS_T 
then press next and finish.
now i got the Reference.cs autogenerated.
3. so I create a controller with these code: 

```
public async Task<IActionResult> Index(){

            ServiceClient client = new ServiceClient();
            General oGeneral = new General();
            string oTipoComprobante = "1"; 
            ENComprobante oENComprobante = new ENComprobante();
            string Cadena = "";
            string TipoCodigo = "1";
            string CodigoBarras = "";
            string CodigoHash = "";
            ENErrorComunicacion oListaError = new ENErrorComunicacion();
            int IdComprobanteCliente = 0;
            string Otorgar = "1";
ENEmpresa ObjEmpresa = new ENEmpresa();
            ObjEmpresa.NombreComercial = "CLINICA PROVIDENCIA";
            ObjEmpresa.Ruc = "20477983708";
            ObjEmpresa.CodigoTipoDocumento = "06";
            ObjEmpresa.RazonSocial = "INVERCONSULT S.A.";
            ObjEmpresa.CodDistrito = "150136";
            ObjEmpresa.Calle = "CAL.CARLOS GONZALES NRO. 250 ";
            ObjEmpresa.Urbanizacion = "URB. MARANGA (250-252-256-260.ALT.CDRA.26 DE LA MARINA)";
            ObjEmpresa.Departamento = "LIMA";
            ObjEmpresa.Provincia = "LIMA";
            ObjEmpresa.Distrito = "SAN MIGUEL";
            ObjEmpresa.CodPais = "PE";
            oGeneral.oENEmpresa = ObjEmpresa;
ENComprobante ObjComprobante = new ENComprobante();
            ObjComprobante.FechaEmision = DateTime.Parse("02-04-2018 00:00:00");
            ObjComprobante.TipoComprobante = "01";
            ObjComprobante.Serie = "001";
            ObjComprobante.Moneda = "PEN";
            ObjComprobante.Ruc = "20549500553";
            ObjComprobante.TipoDocumentoIdentidad = "06";
            ObjComprobante.RazonSocial = "ASERCO EB EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA";
            ObjComprobante.ImporteTotal = 250.00M;
            oGeneral.oENComprobante = ObjComprobante;
RegistrarResponse Resultado = await client.RegistrarAsync(oGeneral, oTipoComprobante, Cadena, TipoCodigo, CodigoBarras, CodigoHash, oListaError, IdComprobanteCliente, Otorgar);

return View();
}
```

run the app for test the Registrar method and o got the error that i mention.
