### ISSUE TITLE
Is any solution to compile wsdl at runtime in netcore?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/wcf#2730]
I find netcore support```Microsoft.CodeDom.Providers.DotNetCompilerPlatform```, but not support ```ServiceDescription```. Is any method to invoke webservice at runtime?

**Comment by Lxiamail** [comment]
No, this is not supported. Can you articulate the scenario that you may use the functionality?

**Comment by MiyamuraMiyako** [comment]
because server address not fixed, I need dynamic decrypt data to real url.

**Comment by Lxiamail** [comment]
At runtime, how will you use the compiled WSDL assuming that dynamically compiling WSDL is available?

**Comment by MiyamuraMiyako** [comment]
I don't know .net framework how to do it, but in other language, first,get wsdl xml,then parse xml, build soap request body and send it to server,finally, get response and parse it.

**Comment by Lxiamail** [comment]
Closing this issue and use #2220 to track it instead.
