### ISSUE TITLE
Asp.net Core 2.0 Sdk SoapClient' does not contain a constructor that takes 

### ISSUE THREAD

**Issue by murattdogan** [dotnet/wcf#2733]
![ekran alintisi](https://user-images.githubusercontent.com/5677481/38275672-40710244-379b-11e8-84f1-00252dcdb8d5.PNG)
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1729	'smsserviceSoapClient' does not contain a constructor that takes 0 arguments	WebApiCore	C:\Users\MDOGAN\source\repos\WebApiCore\WebApiCore\Controllers\ValuesController.cs	16	Active
Web Service Url: http://www.postaguvercini.com/api_ws/smsservice.asmx?wsdl
Asp.net 2.0 Sdk

**Comment by murat0058** [comment]
Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:portType[@name='smsserviceHttpGet']
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:portType[@name='smsserviceHttpGet']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:binding[@name='smsserviceHttpGet']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:service[@name='smsservice']/wsdl:port[@name='smsserviceHttpGet']
Warning:Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:portType[@name='smsserviceHttpPost']
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:portType[@name='smsserviceHttpPost']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:binding[@name='smsserviceHttpPost']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://83.66.137.24/PgApiWs']/wsdl:service[@name='smsservice']/wsdl:port[@name='smsserviceHttpPost']

**Comment by mlacouture** [comment]
Hi @murattdogan 
Thank you for reporting this issue.  Let me make sure I understand your concerns, you reported two different issues:

1. Compiler error: I looked at the generated code (Reference.cs) and noticed that it has multiple endpoint configurations so you need to provide the configuration you want to use when creating the service client, you have multiple constructors to choose from.

2. Metadata processing warnings: these warning messages are self-explanatory, the effect is that for some of the the web service bindings no code will be generated for the bindings' operations.

let me know if you still have any questions,
Miguel Lacouture
