### ISSUE TITLE
An error occurred in the tool. An item with the same key has already been added" when trying to add a Service Reference

### ISSUE THREAD

**Issue by DiegoSalvatore123** [dotnet/wcf#2741]
I am doing an Net Core 2.0 Console Application... 
1. I add a Reference "Microsoft WCF Web Services Reference Provider." versión 0.5.010808.800 
2. On URI Add http://10.0.56.33/CalypsoPolicySystemWeb/sca/PolicySystemExport1 and then GO
3. Click Finish.
4. Get an error "An error occurred in the tool. An item with the same key has already been added. Key: PolicySystem"

I though this problem was  resolve in this versión...

here in my wsdl... to copy and paste in browser... I do not find any error with duplicate Key PolicySystem

  <?xml version="1.0" encoding="UTF-8" ?> 
- <wsdl:definitions name="PolicySystemExport1_PolicySystemHttp_Service" targetNamespace="http://CalypsoPolicySystem_lib/service/PolicySystem" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://CalypsoPolicySystem_lib/service/PolicySystem" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="PolicySystem.wsdl" namespace="http://CalypsoPolicySystem_lib/service/PolicySystem" /> 
- <wsdl:binding name="PolicySystemExport1_PolicySystemHttpBinding" type="this:PolicySystem">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" /> 
- <wsdl:operation name="PolicySystem">
  <soap:operation soapAction="" /> 
- <wsdl:input name="PolicySystemRequest">
  <soap:body use="literal" /> 
  </wsdl:input>
- <wsdl:output name="PolicySystemResponse">
  <soap:body use="literal" /> 
  </wsdl:output>
  </wsdl:operation>
  </wsdl:binding>
- <wsdl:service name="PolicySystemExport1_PolicySystemHttpService">
- <wsdl:port binding="this:PolicySystemExport1_PolicySystemHttpBinding" name="PolicySystemExport1_PolicySystemHttpPort">
  <soap:address location="http://10.0.56.33:80/CalypsoPolicySystemWeb/sca/PolicySystemExport1" /> 
  </wsdl:port>
  </wsdl:service>
  </wsdl:definitions>

Thanks

**Comment by mlacouture** [comment]
Hi @DiegoSalvatore123 
It seems you are using an old version of the tool from the VS Marketplace which is no longer maintained as explained in the download page.  Can you try the tool in the latest [Visual Studio 2017 Preview ](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes)?
thanks,
