### ISSUE TITLE
Response types wrapped in *1 classes and client class name incorrect

### ISSUE THREAD

**Issue by edswangren** [dotnet/wcf#2742]
May be related to https://github.com/dotnet/wcf/issues/2670

I'm not experienced in SOAP, in fact this is my first outing. However, the generated code has some real oddities. I'm using the FedEx API, WSDL attached.

As an example, when I generate the proxies using Service Reference, I get a client `TrackService`. `TrackService` has a method `TrackReply track(TrackRequest)`.

Using your generator I get a client named TrackPortTypeClient with a method `Task<trackResponse>  trackAsync(trackRequest1)` (I understand the move to async, that's not an issue.)

`trackResponse` and `trackRequest1` simply wrap `TrackReply` and `TrackRequest`.  Is there any way to fix this without manually modifying Reference.cs? There are other instances of this issue in the generated code.

[TrackService_v14_dev.zip](https://github.com/dotnet/wcf/files/1885506/TrackService_v14_dev.zip)

**Comment by edswangren** [comment]
Update: I updated VS to 15.6.5 (was previously using the version of your code which I installed manually) and the behavior has changed, though still not quite correct.

My SOAP client is still named `TrackPortTypeClient`, and it still returns a `trackResponse` from `trackAsync` (as opposed to a `TrackReply`), but now that function takes a `TrackRequest` as its argument, which is correct.

**Comment by dasetser** [comment]
@edswangren Sorry this issue got missed for so long. Did you find a work around for this issue? If it is a bug in the tool we would want to investigate, but I'm not clear what exactly the bug is. Just that the names of the classes are different from what you would expect?

**Comment by Lxiamail** [comment]
Close the issue due to inactive. Please feel free to reopen if you still have the same problem with more information.
