### ISSUE TITLE
Duplex over WebSocket using NetHttpBinding fails

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#275]
The current error is...

Binding_NetHttp_WebSocketTests.DuplexOverWebSocket_Echo_RoundTrips_Guid [FAIL]
        System.InvalidCastException : Unable to cast object of type 'System.ServiceModel.Channels.HttpChannelFactory`1[System.ServiceModel.Channels.IDuplexSessionChannel]' to type 'System.ServiceModel.Channels.HttpChannelFactory`1[System.ServiceModel.Channels.IRequestChannel]'.

Stack Trace:
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs(254,0): at System.ServiceModel.Channels.HttpChannelFactory`1.OnCreateChannelCore(EndpointAddress remoteAddress, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs(248,0): at System.ServiceModel.Channels.HttpChannelFactory`1.OnCreateChannel(EndpointAddress remoteAddress, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(128,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ChannelFactoryBase.cs(122,0): at System.ServiceModel.Channels.ChannelFactoryBase`1.CreateChannel(EndpointAddress address, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs(578,0): at System.ServiceModel.Channels.ServiceChannelFactory.ServiceChannelFactoryOverDuplexSession.CreateInnerChannelBinder(EndpointAddress to, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs(310,0): at System.ServiceModel.Channels.ServiceChannelFactory.CreateServiceChannel(EndpointAddress address, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelFactory.cs(342,0): at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\DuplexChannelFactory.cs(241,0): at System.ServiceModel.DuplexChannelFactory`1.CreateChannel(InstanceContext callbackInstance, EndpointAddress address, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\DuplexChannelFactory.cs(203,0): at System.ServiceModel.DuplexChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\ChannelFactory.cs(568,0): at System.ServiceModel.ChannelFactory`1.CreateChannel()
c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Binding\NetHttp\WebSocketTests.cs(31,0): at Binding_NetHttp_WebSocketTests.DuplexOverWebSocket_Echo_RoundTrips_Guid()

**Comment by zhenlan** [comment]
This has been fixed PR #382.
