### ISSUE TITLE
VS2017 core framework 2.0.5 not supporting

### ISSUE THREAD

**Issue by TirthaNag** [dotnet/wcf#2751]
VS2017 core framework 2.0.5 not supporting

![untitled](https://user-images.githubusercontent.com/38285035/38615472-7182234a-3dae-11e8-890c-f2640b8e2732.png)

**Comment by mlacouture** [comment]
Hi @TirthaNag 
It sounds you hit the same problem as #2340. What version of Visual Studio 2017 are you using? Are you able to reproduced this on the latest version of VS? you can try it on a [preview version](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes) if you don't have a recent release version.

**Comment by TirthaNag** [comment]
Thanks @mlacouture ,

Well the problem got solved automatically when I tried the same on the next day. It might sound weird but its true.
