### ISSUE TITLE
Microsoft.Web.Services3 /digest password support

### ISSUE THREAD

**Issue by rajput81** [dotnet/wcf#2764]
Any chance of adding support for digest passwords and nonce in .net core?
We are trying to migrate to .Net core but we are having no luck setting up a digest password.

We also attempted to create a .Net standard 2.0 library but couldn't get it to work due to error:
Package 'Microsoft.Web.Services3 3.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. 
Although there were no compile errors but while executing/debugging the errors started coming  - System.Web.HttpContext missing, System.Configuration.ConcifugrationManager not found etc as soon as it hit this reference - Microsoft.Web.Services3 

It will be great if support can be added for something like this: 
[http://cxdeveloper.com/article/implementing-ws-security-digest-password-nonce-net-40-wcf](url)

**Comment by Lxiamail** [comment]
Digest authentication is supported by WCF .NET Core. Please check out our related tests and let us know if you need further information.

Microsoft.Web.Services3 is .NET Framework 2.0 package, which is not supported on .NET standard.

**Comment by Lxiamail** [comment]
@rajput81 Please let us know if you have more question.

**Comment by zhenlan** [comment]
Hi @rajput81, hope this helps
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.4.1.0.cs#L31
