### ISSUE TITLE
AsymmetricSecurityBindingElement  Binding in .NET Core

### ISSUE THREAD

**Issue by tpever** [dotnet/wcf#2766]
I am trying to consume service which is secure at transport and message level, I am trying to replicate following code into .NET Core.  

`//Setup custom binding with HTTPS + Body Signing 
CustomBinding currentBinding = new CustomBinding();

//Sign the body
AsymmetricSecurityBindingElement asec = (AsymmetricSecurityBindingElement)SecurityBindingElement.CreateMutualCertificateDuplexBindingElement(MessageSecurityVersion.WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10);
asec.SetKeyDerivation(false);
asec.IncludeTimestamp = false;
asec.EnableUnsecuredResponse = true;
asec.SecurityHeaderLayout = SecurityHeaderLayout.Lax;

if (config.UseSignedAndEncrypted)
{
	asec.LocalClientSettings.IdentityVerifier = new CustomeIdentityVerifier();
	asec.RecipientTokenParameters = new System.ServiceModel.Security.Tokens.X509SecurityTokenParameters { InclusionMode = SecurityTokenInclusionMode.Once };
	asec.MessageProtectionOrder = System.ServiceModel.Security.MessageProtectionOrder.SignBeforeEncrypt;
	asec.EndpointSupportingTokenParameters.SignedEncrypted.Add(new System.ServiceModel.Security.Tokens.X509SecurityTokenParameters());
	asec.SetKeyDerivation(false);
}

//Use custom encoder to strip unsigned timestamp in response
CustomTextMessageBindingElement textBindingElement = new CustomTextMessageBindingElement();

//Setup https transport 
HttpsTransportBindingElement httpsTransport = new HttpsTransportBindingElement();
httpsTransport.RequireClientCertificate = true;
httpsTransport.AuthenticationScheme = AuthenticationSchemes.Anonymous;
httpsTransport.MaxReceivedMessageSize = 2147483647;
httpsTransport.UseDefaultWebProxy = false;

//Bind in order (Security layer, message layer, transport layer)
currentBinding.Elements.Add(asec);
currentBinding.Elements.Add(textBindingElement);
currentBinding.Elements.Add(httpsTransport);
return currentBinding;`

Please let me know if any plan to support AsymmetricSecurityBindingElement in .net core or any alternative available for above code.

Thanks in advance.

**Comment by Lxiamail** [comment]
Thank you for the feedback. Message level security is not supported. Please reference the issues #3, #4, #8.

**Comment by dzambo2302** [comment]
Hi,
Are there any plans to make message level security supported?

Thanks.
