### ISSUE TITLE
I'm not able to Update Service Reference after creating the service on a .NET Standard 2.0 Library

### ISSUE THREAD

**Issue by RobertBickers** [dotnet/wcf#2767]
I have a .NET Standard Library with Target framework 2.0 that I'm using as my client communication library for a Forms Application.

I've been able to add the service reference to my service, but after it's creating I do not have the option to update it. My only option being to delete it, and create a new one with the same name.

**Comment by mlacouture** [comment]
Hi @RobertBickers 
We are going to need more information about this problem.  Can you confirm the following:
1. You are using the WCF Web Service Reference connected service provider on you .NET Standard library project.
2. What version of Visual Studio 2017 are you using?
3. Are you able to reproduce this problem on a recent release of Visual Studio 2017? you can try a [preview version](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes) if you don't have a recent version of VS installed.
4. What do you mean by 'Forms Application'? is this a Xamarin project? 
thank you!
Miguel

**Comment by RobertBickers** [comment]
Yes, using the WCF Web Reference:
![image](https://user-images.githubusercontent.com/2368988/38821794-7a117e4a-4199-11e8-9b0d-c484e45d681e.png)

![image](https://user-images.githubusercontent.com/2368988/38821966-fb49528a-4199-11e8-932b-8d69fa3ea2a6.png)


Visual Studio Version: 15.5.6

![image](https://user-images.githubusercontent.com/2368988/38821914-cb3b1c68-4199-11e8-868c-5228fd031143.png)


I haven't been able to make it work on any version of Visual Studio I have.

By Forms application, yes I do mean Xamarin Forms. However I don't think this is related as the project I'm working with is a library in and of its self which is referenced **by** the forms application, not the other way around.

**Comment by mlacouture** [comment]
Thank you @RobertBickers for providing the requested information.  Just to make sure, did you try to update the service as explained in the [original release notes](https://blogs.msdn.microsoft.com/visualstudio/2017/12/07/visual-studio-2017-version-15-6-preview/)?

**Comment by RobertBickers** [comment]
No, as I'm not able to see that option. Hence why I have to delete the
reference and add it again.

**Comment by RobertBickers** [comment]
Sure, but there's not much to it, which may be the problem I suppose?
{
  "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
  "Version": "0.5.10808.800"
}

**Comment by mlacouture** [comment]
Yes, this is definitely the problem.  You are using a very old version of the tool (the one from the VS Marketplace), instead of the one shipped with Visual Studio.  You should be able to uninstall the old tool from the Extensions and Updates option from the Tools menu.   I'm closing this issue, please let us know if you need any further help.

Miguel Lacouture

**Comment by RobertBickers** [comment]
Thanks for that, to solve it I unticked the option in my Visual Studio Installer within the components tab, from there I have been able to update the Service Reference.
