### ISSUE TITLE
Create "supported features" table for WCF 2.1 release

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#2773]
We may consider separate UWP column to a separate doc specific for UWP releases.

**Comment by Lxiamail** [comment]
https://github.com/dotnet/wcf/blob/master/release-notes/UWPSupportedFeatures-v6.1.md is the separated UWP table from https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v2.1.0.md.
