### ISSUE TITLE
JSON WCF server code in .Net Core

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/wcf#2774]
I would like to propose a version of WCF Server that uses JSON. Where our WCF server code could run but emit JSON. I know there is the asp.net core web api and we are using it, however I also know we have a big WCF server that runs great but we can't use it in .net core. We would love to be able to run it in .net core (because of cross platform), and we could with this proposal. Of course our transports would change, but I think emitting JSON would help developers with WCF server code to bridge the gap, and I hope this would be easy for the WCF team to accomplish. I love the WCF design because ,its simple and easy to use that is why I hope this proposal would be a win-win situation.

**Comment by Lxiamail** [comment]
Thank you for the suggestion. However, at this point, WCF Server is not in the scope of this project.
