### ISSUE TITLE
Where's SoapExtension

### ISSUE THREAD

**Issue by rui-ktei** [dotnet/wcf#2790]
Hi, could anyone give some help here?

How does .NET Core "intercept" a SOAP message, i.e., where did SoapExtension class go? I have a legacy system that I have to integrate with and I have to sign SOAP body. The sample code I have for now is using SoapExtension to do that, but I can't find the equivalent to the SoapExtension in .NET core. Do you guys still support this? If not, could you suggest an alternative? Thanks a million!

**Comment by Lxiamail** [comment]
SoapExtension is not supported in .NET core. Have you tried to use [SignedXML](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.signedxml?view=netcore-2.0)?

**Comment by Lxiamail** [comment]
@rui-ktei Please let us know if you have any other question.
