### ISSUE TITLE
System.ServiceModel.Primitives 4.5.0-preview2-26410-01 not compatible with 4.4.2 ?

### ISSUE THREAD

**Issue by rvanmaanen** [dotnet/wcf#2791]
Having a weird issue when referencing a .NET Standard class library from a .NET Core 2.1 preview 2 (2.1.300-preview2-008533) project, in particular with the System.ServiceModel.Primitives NuGet package.

There is a custom IEndpointBehavior implementation in the class library, which is using System.ServiceModel.Primitives version 4.4.2. When using that class in the the console app, which is referencing System.ServiceModel.Primitives 4.5.0-preview2-26410-01, the following error occurs: "Cannot convert from 'ClassLibrary1.CustomBehavior' to 'System.ServiceModel.Description.IEndpointBehavior'"

Suggested fix is "You must add a reference to assembly 'System.ServiceModel.Primitives, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'" Why is this neccessary? As far as I know .NET Core 2.1 is still .NET Standard 2.0 compliant and I should just be able to use this class library?

I created a small project to demo the issue here: https://github.com/rvanmaanen/dotnetcore21issue

Btw, using the latest Visual Studio 15.7.0 preview 4.0. Here's a screenshot:

![image](https://user-images.githubusercontent.com/4835258/39185734-6bdb942a-47c8-11e8-8552-62cd46c89842.png)

**Comment by StephenBonikowsky** [comment]
We are targeting 2.1 RTM for this fix, it is currently in the approval process.
PR #2817

**Comment by StephenBonikowsky** [comment]
It was approved and merged.
Thank youo for finding this @rvanmaanen
