### ISSUE TITLE
Travelport UAPI's WSDLs seems not usable as WCF Web Service Reference

### ISSUE THREAD

**Issue by martonx** [dotnet/wcf#2794]
Hi .Net Core developers,

[uAPI_WSDLschema_Release-V17.4.0.36.zip](https://github.com/dotnet/wcf/files/1946329/uAPI_WSDLschema_Release-V17.4.0.36.zip)
I have a serious issue. I have these WSDL Schemas from [Travelport](https://developer.travelport.com).

When I'm opening an empty .Net Core 2.0 console app and I want to use any of these wsdls (for example Air.wsdl) I got only an error message from the Configure WCF Web Service Reference wizard.

![image](https://user-images.githubusercontent.com/407433/39237066-c536756e-487a-11e8-86f0-58b3ae55688c.png)

While the old .Net Framework version of Add Service reference can handle these WSDLs:

![image](https://user-images.githubusercontent.com/407433/39245155-33c5ab5e-4893-11e8-893c-fd3d3d9451af.png)

Please help me, how to use these WSDLs from .Net Core?

**Comment by dasetser** [comment]
Hi martonx,

What version of Visual Studio are you using? I tried this out on VS2017 15.6.6 and was able to add a reference to the Air.wsdl file without any errors. Are you using an older version?

Thanks,
Daniel

**Comment by martonx** [comment]
@dasetser you're right. I tried it on a different PC with different VS and I was able to add. Anyway on my previous PC there is latest VS2017 I'm 100% sure, but it's an originally old install what was updated lots of times. This is a quite fresh install and it is working on this machine.

**Comment by dasetser** [comment]
@martonx Glad to hear you were able to add it on a different machine. 

On your previous machine did you have the old version of the connected service extension from the VS marketplace installed? I'm wondering If you were using an older marketplace version instead of the one included with Visual Studio, which would mean you wouldn't be using the version with the latest fixes even on the latest VS.

**Comment by martonx** [comment]
@dasetser  Yes on my other machine I have two kind of connected service on Preview and one without Preview. I used the without preview version. Actually I tried to add this wsdl with both of them.

**Comment by dasetser** [comment]
@martonx That's strange that you saw the same behavior with both versions when one should be up to date. I tried it out and when I had both the preview didn't work but the up to date version did. Can you try uninstalling the marketplace extension and seeing if it still reproduces after uninstalling it? That is a very old version that has been removed from the marketplace.

**Comment by mlacouture** [comment]
@martonx, thank you for contacting us.  I'm closing this issue as it seems @dasetser and you already figured out what was wrong.  Please let us know if you still have any problems.
