### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by akuckartz** [dotnet/wcf#28]
Support for JSON-LD would be helpful.

**Comment by iamjasonp** [comment]
Hi @akuckartz, 

I think what you want is for `DataContractJsonSerializer` to support JSON-LD?

DataContractSerializers first shipped with WCF in .NET 3.0, but there are more uses for them than just WCF, even if WCF are the primary consumers of these serializers (note the foresight: DataContractSerializers have *always* lived in the `System.Runtime.Serialization` namespace) :smile: 

For .NET Core, we've put the source files where they logically belong - unbundled from WCF and in the [dotnet/corefx](https://github.com/dotnet/corefx) repo. Would you mind re-opening this issue in the dotnet/corefx repo? 

Thanks!

**Comment by zhenlan** [comment]
@iamjasonp Please close this issue if it is already opened in dotnet/corefx

**Comment by iamjasonp** [comment]
@akuckartz - you want to open this issue in dotnet/corefx or should I?

**Comment by iamjasonp** [comment]
Closing this issue as an issue was opened in the dotnet/corefx repo.

**Comment by akuckartz** [comment]
@iamjasonp Thanks for moving this issue to the correct place !
