### ISSUE TITLE
Create a scenario test that uses IOperationBehavior on a service contract

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#280]
Steps:
1. Create a custom attribute that implements IOperationBehavior
2, Find a way to make this attribute a "test spy" that can report that its methods get called.
3. Add this attribute to at least one service operation in the service interface
4. Use a ClientBase<T> test to invoke that operation and verify that custom attribute's code was executed.

We have evidence that some Windows Store apps (Arkadium.SharedEntities) do this and need to verify that it works on a service interface.  It will also increase our code coverage and verify whether we ever need to reflect over the concrete implementation of that service interface (look at code coverage of TypeLoader.ProcessOpMethod.

**Comment by StephenBonikowsky** [comment]
Looks like the IOperationBehavior methods get called at the CreateChannel point, so this looks like a unit test to me.

**Comment by StephenBonikowsky** [comment]
I wrote the test but the IOperationBehavior methods are not getting hit. There is no exception thrown, doing additional debugging to see if I can root cause it.

**Comment by StephenBonikowsky** [comment]
Test is ready, the issue has been identified and Issue #315 opened.
