### ISSUE TITLE
Fix https tests that fail when Bridge runs remotely

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#281]
All the https OuterLoop tests fail when the Bridge is run remotely.  Investigate and solve.

**Comment by zhenlan** [comment]
This is a dup of issue #291

**Comment by SajayAntony** [comment]
On Desktop you would most likely do 
```
ServicePointManager.ServerCertificateValidationCallback +=
                new System.Net.Security.RemoteCertificateValidationCallback(RemoteCertValidate);
```
The question is on coreclr is this available. If not I guess installing the cert would most likely be what you need do and ensure that you remove it during cleanup.
