### ISSUE TITLE
The HTTP service located at ... is unavailable.

### ISSUE THREAD

**Issue by maracuja-juice** [dotnet/wcf#2821]
**What I'm trying to do**
I am trying to call a SOAP Service from .NET Core. 

**Repro Steps**
I generated the client class via the Connected Service, I provided the wsdl file clicked on next then unchecked `Reuse types in referenced assemblies`. The client was generated successfully. I call it via `await client.getAhvvnAsync(request);`

The service is this one right [here](https://www.zas.admin.ch/zas/de/home/partenaires-et-institutions-/unique-person-identification--upi-/upiservices.html).
Here is a minimal example of what I did: [WebApplication1.zip](https://github.com/dotnet/wcf/files/1974891/WebApplication1.zip)
The server needs a Username and Password which I provided locally but not in my downloadable example (see below)

**What I expected to happen**
The service should return the correct result. / In your case without Username/Password there should be an `InvalidOperationException -> The username is not provided: Specify username in ClientCredentials.`.

**What actually happened**
```
The HTTP service located at https://www.wupi-test.zas.admin.ch/wupi/UPIQueryService is unavailable. 
This could be because the service is too busy or because 
no endpoint was found listening at the specified address. Please ensure that the address is correct
and try accessing the service again later.
```

**Additional information**

I tried to use the service the same way in a .NET 4.6 project and it works wonderfully. (the service client is a bit different (-> naming) but more or less the same)
When I remove the password/username from there I get:
```
 InvalidOperationException -> The username is not provided: Specify username in ClientCredentials.
```

**Comment by maracuja-juice** [comment]
I got this working today.

```
            var basicHttpBinding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
            basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
            var endpointAddress = new EndpointAddress("https://www.wupi.zas.admin.ch:443/wupi/UPIQueryService");
            var factory = new ChannelFactory<UPIQueryServicePortTypeChannel>(basicHttpBinding, endpointAddress);
            factory.Credentials.UserName.UserName = "...";
            factory.Credentials.UserName.Password = "...";
            client = factory.CreateChannel();
```

Note that the URL changed here and that I set Basic as HttpClientCredentials. 
When I change the URL in the wsdl and regenerate the client and use the client the same as before, it's not enough though: 
```
The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic realm="default"'.
```
Haven't found out the correct way to say the connection that it should use Basic authentication with this way.

**Comment by KKhurin** [comment]
@maracuja-juice, I would have to take a look. There might be no easy way (in which case we'd have to involve the tooling team).

**Comment by KKhurin** [comment]
@mlacouture, do you have any context whether Windows authentication is supported via connected services' generated code?

**Comment by mlacouture** [comment]
Hi @KKhurin 
Yes, the generated code provides a partial method in the client class for this purpose, the signature looks like the following:

`static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);`

**Comment by maracuja-juice** [comment]
We don't use `Windows Authentication` but `Basic Authentication`.

**Comment by cyrilsamson** [comment]
Hi @maracuja-juice,
I'm trying to use the same Http service as you, and I have exactly the same error (the last one)

> The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic realm="default"'

Do you finally found a solution to use the basic authentication ?
Thanks
