### ISSUE TITLE
Add connected service with multiple WSDL files

### ISSUE THREAD

**Issue by zipswich** [dotnet/wcf#2852]
I am trying to figure out the difference between adding a service reference and adding a connected service.  Is the former obsolete and being replaced by the latter.
The former generates something like the following in Reference.cs:
```
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://somedomain/ver10/schema")]
    ...
```

The latter generates the following in Reference.cs:
```
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
    ...
```
If I want to generate one reference with multiple WSDL files, I can accomplish it by editing the MetadtaSources tag of Reference.svcmap.  How can I do the same for the latter?

**Comment by mlacouture** [comment]
Hi @zipswich 
The [WCF Web Service Reference](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide) connected service provider tool is for .NET Core projects and is not a replacement for the old Add Service Reference tool which supports .NET Framework projects.  This tool provides a Browse button so you can load a WSDL file from which the web service reference can be generated.
hope this answers your questions,
Miguel Lacouture

**Comment by zipswich** [comment]
Thank you for the clarification, @mlacouture 
Could you tell me how to generate a reference from multiple WSDL files?
It is important for me because I use multiple WSDL files that share many schemata.  It would be really messy if I generate separate services for them.

**Comment by mlacouture** [comment]
Currently the tool accepts only one WSDL file, it resolves any imported wsdl or schema documents.

**Comment by zipswich** [comment]
Thank you for the clarification, @mlacouture

**Comment by zipswich** [comment]
@mlacouture Could the team consider accommodating multiple WSDL files in the future?

```
For service reference, I do it by using the followingin file Reference.svcmap:
  <MetadataSources>
    <MetadataSource Address="http://my.domain.org/service/a.wsdl" Protocol="http" SourceId="1" />
    <MetadataSource Address="http://my.domain.org/service/b.wsdl" Protocol="http" SourceId="2" />
    <MetadataSource Address="http://my.domain.org/service/c.wsdl" Protocol="http" SourceId="3" />
    <MetadataSource Address="http://my.domain.org/service/d.wsdl" Protocol="http" SourceId="4" />
     ...
  </MetadataSources>
```
It works out extremely well.  It would be very messy because a, b, c, d... share many basic classes.  If different services are generated, the same classes will be under different namespaces.  Exchanging information among them will need extra tedious copying.

**Comment by zipswich** [comment]
Thanks a lot for reopening this, @mlacouture 
Let me give you a very brief background.  I develop apps targeting multiple platforms (UWP, Android, Web, iOS) using [Platform.uno](https://platform.uno/).   Yes, I know Xamarin and have spent a lot of time on it before deciding to use Uno.  I do not know if the proxy classes created by dotnet-svcutil  tool can target multiple platforms.   Adding service reference is not an option for Uno class library.   I guess I will just have to try it out.

**Comment by zipswich** [comment]
@mlacouture Is it possible to use multiple online WSDL files (i.e. URLs) as the input?
I tried the following:
`	dotnet svcutil http://my.domain.org/service/a.wsdl http://my.domain.org/service/b.wsdl`
I got the following error:

> Only metadata document files are allowed when multiple inputs specified!

**Comment by mlacouture** [comment]
@zipswich multiple wsdl inputs are supported for wsdl files on disk only, you need to download the files locally then pass them to the tool. 
regards,

**Comment by zipswich** [comment]
@mlacouture Thank you for the confirmation.
Is there a roadmap for these tools to help us plan our projects in the future. There are two ways to generate the Proxy classes:

1. The most powerful way - Add Service Reference - for UWP, ASP.net  MVC... that takes multiple WSDL URLs.
2. The relatively new Add Connected Service.
3. Command tool dotnet-svcutil.

Should we expect #1 to be deprecated in not far future and we should start to wean off from it?

**Comment by mlacouture** [comment]
@zipswich, Add Service Reference targets .NET Framework and we don't have any plans for depricating it but it is in maintenance mode (no new features/improvements planned).  The other two tools are for .NET Core projects and we still have some room for improvements for these tools, if you have any feature requests (like suport for multiple URLs) you can report an issue for consideration which dependes on the feature demand (votes).  Hope this helps,

**Comment by zipswich** [comment]
@mlacouture Thanks a lot for the clarification.  It is very helpful.   I should be all set if Add Service Reference is available for the foreseeable future.  I am adapting it for cross-platform apps.
