### ISSUE TITLE
Cannot load System.ServiceModel.Primitives, Version=4.2.0.0

### ISSUE THREAD

**Issue by red1laref** [dotnet/wcf#2862]
Hi, 

I'm working on a .net standard project. to build a Powershell Cmdlet.
When I add a WCF connected service reference to my project I get this error when I try to import my module.
 Import-Module : Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its 
dependencies. The system cannot find the file specified.

Someone has any ideas why? 

Thank you

**Comment by mlacouture** [comment]
Hi @red1laref 
Sounds like you are hitting the same problem as in issue #2546, can you try the workaround provided for this issue and see if that works for you?
thanks,

**Comment by red1laref** [comment]
It doesn't work for me. Do you have any other solutions? Or do you need more informations?

**Comment by mlacouture** [comment]
Yes, can you please provide details about the project type and target framework and details about what you mean by 'trying to import your module'.  
thank you

**Comment by red1laref** [comment]
I'am targeting .NET Standard 2.0
My project type is a Class Library .NET Standard. .NET Framework 4.5.
Trying to import module: I'am building a powershell cmdlet with c#.
I have to run import-module on the dll file generated by my project.

**Comment by ssashok10** [comment]
I am having the same issue with .NET standard Azure functions...I am able to find the DLL on the bin folder too...

Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

**Comment by mlacouture** [comment]
Again, this seems very much like the same problem as #2546.  If the project is a .NET Core or .NET Standard project, a workaround is to add the System.ServiceModel.Primitives NuGet package as a reference to the project, running the following command from the project's folder will add the reference:
>dotnet add package System.ServiceModel.Primitives -v 4.4.2
Please try this workaround or the one provided in #2546 for .NET Framework projects,
thanks,

**Comment by AlpeshValvi123** [comment]
I have added these two packages from NuGet and its work for in .Net Console and MVC Core Web App but **not working MVC 5 web application.**

System.ServiceModel.Http
System.ServiceModel.Primitives
The application is just waiting for a response.

**So it's not supported for MVC 5 Application?**

**Comment by goncalo-oliveira** [comment]
I'm having a similar issue when deploying to an Azure Web App (Linux). I have a web app that's referencing a library using Wcf, both .NET 5. The Wcf project includes the following package references

```
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.1" />
```
Both locally and running with a Docker image, everything works fine. But when deploying to an Azure Web App (Deployment Center, building from source), I get error

```
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

Any thoughts?

**Comment by dmki** [comment]
Same thing here. Seems like nuget package includes old binary for .NET 5.

**Comment by blalonde** [comment]
If you stumble on this, we are targeting net6.0, running on Powershell 7 and 
referencing a netstandard2.0 lib which in turn references System.ServiceModel.Primitives 4.10.2 

It happens we had to update Powershell 7.3.3 to 7.3.6 to make this error disappear.

**Comment by ddemeyer** [comment]
Thanks @blalonde ... Exactly your situation. Github Actions was on PowerShell 7.2.x and for now decided to use https://github.com/marketplace/actions/pwshupdater to push it higher.
