### ISSUE TITLE
MessageSecurity

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/wcf#2881]

**Comment by pthorsley** [comment]
When is this feature slated to be worked on? We have a 3rd party API that only supports Message security via their SOAP service. When using the proxy builder everything went fine until runtime and then found out that the security "Message" format was not supported only Transport was. 

Is there some kind of workaround for Core that could get me past this issue?

**Comment by gerritsen** [comment]
Any plans to support this in the future?

**Comment by StephenBonikowsky** [comment]
Tracking this work with #3424, closing this Epic.
