### ISSUE TITLE
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0

### ISSUE THREAD

**Issue by ssashok10** [dotnet/wcf#2885]
I am using Azure Function (C#) which is calling a .NET standard library to call an external WCF service and I am getting the below error. This file is located on the bin folder of my function and the version also correct.

Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Here are the platform information,
Microsoft.NET.Sdk.Functions (1.0.13)
.NET Standard Library 2.0
System.ServiceModel.Duplex 4.4.2
System.ServiceModel.Http 4.4.2
System.ServiceModel.NetTcp 4.4.2
System.ServiceModel.Security 4.4.2

**Comment by zhenlan** [comment]
Hi @ssashok10, just to help understand, what's the difference of this Azure Function app than the one you had in #2824?

**Comment by ssashok10** [comment]
The issue #2824 is different than this issue. The DLL is not copied into the "bin" folder on the issue #2824. Here we are seeing the DLL "System.ServiceModel.Primities" into the bin folder and version also matching. However, the function run time is not able to load it for some reason.

**Comment by zhenlan** [comment]
@ssashok10, I understand what you described. I am trying to see what caused this result, so that's why my question about what's the difference between the two projects (the project in this issue and the project in #2824). The difference between the two projects may help us to tell why the issue happens to one project but not the other.

**Comment by ssashok10** [comment]
@zhenlan It's the same project. We initially had an issue with "System.private.servicemodel.dll" which doesn't exist on the bin folder. We overcome this issue with your work around and we ended up facing the current issue. We are able to see the DLL "system.servicemodel.primitives.dll" into the BIN folder with the right version.

**Comment by zhenlan** [comment]
I see. Looks like somehow the project was trying to use an older version of S.SM.Primitives package. Does it help if you add package reference of `System.ServiceModel.Primitives 4.4.2` explicitly to your project?

**Comment by ssashok10** [comment]
we tried to add it explicitly and it's not helping at all as the DLL already exists in the bin folder. However, we are able to solve this issue something similar in the below article during runtime.

http://putridparrot.com/blog/dynamically-resolve-assemblies-at-runtime/

**Comment by zhenlan** [comment]
I didn't have this issue last time when I tried .NET Core Azure Functions. At this point, it probably will be helpful if you can share a repro for further investigation.

The [blog post](http://putridparrot.com/blog/dynamically-resolve-assemblies-at-runtime/) is about full framework, so I assume you worked around the issue by implementing assembly resolver using .NET Core APIs?

**Comment by ssashok10** [comment]
yes...we fixed this issue with assembly resolver.

**Comment by Lxiamail** [comment]
@ssashok10 Looks like [the fix in Azure function](https://github.com/Azure/azure-functions-host/issues/2877) may have fixed your problem. Have you tried it?

**Comment by chadgruka** [comment]
This is also an issue for me. Seems to crop up when referencing BasicHttpBinding or other Binding objects in code. I don't recall this being an issue a couple months back, as I have check-ins that were additive mid-to-late August.

I'm seeing this inside Azure Functions and Console apps. I'm running the latest VS Pro 2017 preview (15.9.5)

Hope this helps...

**Comment by melzoghbi** [comment]
I am facing the same issue using azure runtime Version: 2.0.12245.0 in VS2017. After i added the ServiceModel Primitives nuget package i get the following error:

Could not load file or assembly 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Any fix for this issue or workaround?

Thanks.

**Comment by Lxiamail** [comment]
@chadgruka Have you tried the [new Azure function version with the fix](https://github.com/Azure/azure-functions-host/issues/2877)? When you say the issue repro with "Console apps", can you share concrete repro steps?

**Comment by chadgruka** [comment]
Sorry, this is 2 months ago. I'll have to see where we landed on this since.

**Comment by Lxiamail** [comment]
@melzoghbi Have you tried [the new Azure function version with the fix](https://github.com/Azure/azure-functions-host/issues/2877)? If the issue that you ran into is about missing System.Private.ServiceModel.dll in Azure Function output directory, it may due to [a different Azure function issue](https://github.com/Azure/azure-functions-host/issues/3568). Can you try the work around suggested by Zhenlan in [#dotnet/wcf#2824](https://github.com/dotnet/wcf/issues/2824) ?

**Comment by Lxiamail** [comment]
@chadgruka Thanks

**Comment by Lxiamail** [comment]
Closing this issue. If you still run into the same issue. Please try [the new Azure function version with the fix](https://github.com/Azure/azure-functions-host/issues/2877). If it doesn't work, please open new issue in https://github.com/Azure/azure-functions-host repo.
