### ISSUE TITLE
Introducing dotnet-svcutil

### ISSUE THREAD

**Issue by mlacouture** [dotnet/wcf#2894]
# Introducing dotnet-svcutil

The Microsoft Windows Communication Foundation (WCF) **dotnet-svcutil** tool is a .NET Core CLI tool that retrieves metadata from a web service on a network location or from a WSDL file, and generates a WCF class containing client proxy methods that access the web service operations.

Similarly to the [Service Model Metadata - svcutil](https://docs.microsoft.com/en-us/dotnet/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe) tool for .NET Framework projects, the **dotnet-svcutil** is a command line tool for generating a web service reference compatible with .NET Core and .NET Standard projects. 

The **dotnet-svcutil** tool is an alternative option to the [WCF Web Service Reference ](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)Visual Studio connected service provider which first shipped with Visual Studio 2017 v15.5.  The **dotnet-svcutil** tool as a .NET Core CLI tool, is available cross-platforms on Linux and macOS and Windows.

## Getting started
Please visit the [Microsoft WCF **dotnet-svcutil** usage guide](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide)  for details.

## Known issues
1.  When the tool input is a wsdl file and it is run on Linux using the .NET Core SDK v1.x, the tool will fail with an error that looks like the following:
`Error: The specified URI '/path/to/file.wsdl' does not appear to be valid.`

Please share your thoughts and report any [issues](https://github.com/dotnet/wcf/issues/new) you may experience with this tool.   
Thank you!

**Comment by zhenlan** [comment]
@gfoidl thanks for the feedback. For the 1.0.0 release, this will be a project level CLI tool. We are open to a global tool idea. Can you please share more about why you think this can work better for you as a global tool (eg., scenarios)?

**Comment by gfoidl** [comment]
> share more about why you think this can work better for you as a global tool

* I'm lazy and don't want to remind myself to add the proper `DotNetCliToolReference`. As global tool it is just there and remembering `svcutil` is trivial.
* For prototyping a WCF-service when I just want to check the generated code. With the global tool I just need to open a shell and type `svcutil {serverurl}` to let the client-code be generated -- without the need to setup a client-project only for this (validating) purpose.
* The latter point generalized: Cient code can be generated w/o the need for an explicit client-project.

So in essence it just for lazyness, or in other words: The use as global tool seems more comfortable to me than as project level tool.

**Comment by poke** [comment]
This actually makes more sense as a global tool than things like `dotnet ef` (which is project specific in that it will require EF dependencies and some setup).

With `svcutil`, you will usually create the client once (unless the specification changes later), and then you check in the generated files with your code. So there is little benefit in having this as a tool registed with the project when it will be rarely used later on. As a global tool, this would much more fit the “set this up and then forget about it” way it works.

**Comment by mlacouture** [comment]
These are all very good points.  However, the CLI tool, having the project context, has (will have) some advantages like the following:
1. It can resolve the target framework automatically (no need to provide the -tf parameter)
2. It can add the WCF references to the project automatically (Getting Started step 6)
3. It can support the update feature w/o any input parameters from the user, something like:
`dotnet svcutil update`

All the above could be supported by the global tool but the user will have to provide the project path.

Please keep the discussion going by providing your thoguths ... thank you!

**Comment by gfoidl** [comment]
Both variants can co-exists, so the user can use the proper way. 

They don't have to be in a xor-fashion.

**Comment by poke** [comment]
Sorry, but the tool having a project context is not really a reason why it could not be a global tool. The three standard global tools, `dotnet watch`, `dotnet user-secrets`, and especially `dotnet ef` all require a project context as well, and yet they are global tools because they are useful in general.

**Comment by mlacouture** [comment]
Very good input, thank you!

I forgot to mentioned that the global tool is a .NET Core 2.1 thing and there is no plans for backward compat in earlier versions of the platform as far as I know.

**Comment by daberni** [comment]
I was very happy when I saw that the svcutil was ported to dotnetcore!

But why does dotnet-svcutil need a dependency on `netcoreapp.*`?
I really would like to use it in a library project too! I don't see why there should be a restriction on it? We pack the whole object model in a library which is then used by multiple executables which all use the underlying SOAP service.
