### ISSUE TITLE
Provide a mechanism to pass command line parameters into tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#29]
Our scenario tests will require the ability to redirect the URL of the test service to alternate machines.  One can also imagine other test inputs that might feed some [Theory] based test.
One technique to investigate is a pre-build step that accepts MSBuild properties of a known format, generates a temporary .cs file with the information (a Dictionary?), and adds that file to the @(Compile) collection.  The tests could be written to consult the dictionary for expected names.  Also we could create a [Theory] style test that pulls multiple values.  The implementation should not be tied only to scenario tests but available to all tests.

This would be more generally useful than just for WCF, so we should consider working with https://github.com/dotnet/buildtools

**Comment by mconnew** [comment]
Pull request #89 will need to be reverted as part of this change

**Comment by roncain** [comment]
I have a working prototype that injects MSBuild properties into a dictionary available at runtime.  I will get it ready for review shortly.  We will make the fiddler proxy an option that can be polled by our test helpers.

**Comment by SajayAntony** [comment]
I responded on the PR but should have added the info here. Basically consider falling back to GetEnvironmentVariable during runtime is critical since having to run msbuild each time seems like a productivity drain.

**Comment by mconnew** [comment]
@SajayAntony, I would prefer it be the other way around. That is, if the variable has been defined, check for an environment variable first and if it exists use that, otherwise use the compiled in version. If the environment variable is a fallback mechanism, you would still need to edit and recompile to override it anyway. Then when you are done, that change would need to be reverted. At which point you might as well have just changed the value in the source and not worried about using an environment variable.

**Comment by SajayAntony** [comment]
@mconnew I didn't know that that build would hardcode the values. My impression was that build args would not be populated unless it is a build. Are you looking for a way to override build props?

**Comment by roncain** [comment]
I was thinking to implement as Matt suggested, namely populate the name/value pairs at build time from MSBuild properties, but give precedence to Env vars at runtime.  That means the build is guaranteed to populate them with either the defaults or from MSBuild properties.  But if you want to just change something and re-run without building, just set the Env var.  It gives the nice behavior of allowing a build machine to avoid Env vars, but also allows a developer to manually override without rebuilding.

**Comment by SajayAntony** [comment]
@roncain @mconnew  sounds good. So lets just settle on Env vars takes precedence over .props
