### ISSUE TITLE
Enable client-side installation of certificates and firewall rules when Bridge is remote

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#291]
Currently, the Bridge.exe handles installation and uninstallation of certificates and the creation of firewall rules on an as-needed basis.  When the Bridge runs on the same machine as the tests, this is sufficient.
When the Bridge is run x-machine we need a story where any necessary certificates and firewall rules are installed on the client.  And this needs to be x-plat ready.

**Comment by SajayAntony** [comment]
On Desktop you would most likely do 
```
ServicePointManager.ServerCertificateValidationCallback +=
                new System.Net.Security.RemoteCertificateValidationCallback(RemoteCertValidate);
```
The question is on coreclr is this available. If not I guess installing the cert would most likely be what you need do and ensure that you remove it during cleanup.

**Comment by roncain** [comment]
This issue was resolved when @iamjasonp checked in dynamic cert generation
