### ISSUE TITLE
2.1 RTM packages missing netstandard1.3 symbol files

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/wcf#2912]

**Comment by StephenBonikowsky** [comment]
We didn't used to ship symbol files, so this is expected for 1.3 assemblies. Need to decide if we want to begin producing symbols in future servicing releases from our release/1.1 and release/1.0 branches.

**Comment by StephenBonikowsky** [comment]
Low priority, moving this to backlog.

**Comment by Lxiamail** [comment]
We never produced symbols for 1.3 or previous releases. Cut
