### ISSUE TITLE
WCF Duplex Service in Asp.Net Core throw exception "Exception of type 'System.Exception' was thrown"

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/wcf#2938]
I want to consume WCF duplex service in asp.net core, and hit issue while checking the result from callback. The error message it too general and there is inner message, fail to know how to resolve this issue.
Reproduce Steps:
1. Create WCF Duplex Service
2. Consume WCF Duplex Service from .net console app, it works correctly.
3. Create Asp.Net Core 2.0 project, and add service reference
4. Call the service from code below:
`            // Create a client.  
            CalculatorDuplexClient client = new CalculatorDuplexClient();
            // Call the AddTo service operation.  
            double value = 100.00D;
            object[] o = new object[1024];
            Exception exception = new Exception();
            bool isCancel = false;
            object final = new object();

            ServiceReference1.ResultReceivedEventArgs eventArgs = new ResultReceivedEventArgs(o, exception, isCancel, final); //the exception is not null
            //await client.AddToAsync(value); //test one way option
            string rr = await client.TestAsync(value); //test request-reponse
            var result = eventArgs.result1; //both methods throw exception here
`
Project: https://github.com/Edward-Zhou/WCFDuplexService.git

**Comment by dasetser** [comment]
@Edward-Zhou Sorry for the slow response. Did you figure out what the problem was with this? Or is this still an issue?

**Comment by Edward-Zhou** [comment]
@dasetser This is still a open issue.

**Comment by dasetser** [comment]
@Edward-Zhou The WCFCoreApp project included in your repro wasn't running correctly for me for some reason. However, I tried creating a .NET Core console app and copying the code of your WCFClient project. It didn't work at first, but modifying the main method slightly made it work as expected:
```
static void Main(string[] args)
{
    // Construct InstanceContext to handle messages on callback interface.  
    InstanceContext instanceContext = new InstanceContext(new CallbackHandler());

    // Create a client.  
    CalculatorDuplexClient client = new CalculatorDuplexClient();
    var factory = (DuplexChannelFactory<ICalculatorDuplex>)client.ChannelFactory;
    var proxy = factory.CreateChannel(instanceContext);

    Console.WriteLine("Press <ENTER> to terminate client once the output is displayed.");
    Console.WriteLine();

    // Call the AddTo service operation.  
    double value = 100.00D;
    proxy.AddToAsync(value);
    Console.WriteLine("add is called");
    Console.ReadLine();
}
```

I would expect this approach should work the same way in a .NET Core Console app and your ASP.NET Core web app (except you would want to await the AddToAsync). Can you try it out and see if it works for you or not?

**Comment by Lxiamail** [comment]
@Edward-Zhou Let us know if it doesn't resolve your problem.
