### ISSUE TITLE
TcpTransportSecurity class doesn't have ProtectionLevel property

### ISSUE THREAD

**Issue by karelz** [dotnet/wcf#2944]
_From @SteveL-MSFT on June 12, 2018 21:56_

Porting some .Net Framework code to dotnetcore.  The TcpTransportSecurity class doesn't have ProtectionLevel property so I can't set it to EncryptAndSign.  What is the impact of not setting this?  Is it secure by default?

_Copied from original issue: dotnet/corefx#30343_

**Comment by karelz** [comment]
_From @davidsh on June 12, 2018 22:2_

Are you referring to this class:

[System.ServiceModel.TcpTransportSecurity](https://msdn.microsoft.com/en-us/library/system.servicemodel.tcptransportsecurity(v=vs.110).aspx) ?

I think all System.ServiceModel classes are in the [WCF repo](https://github.com/dotnet/wcf):

See:
https://github.com/dotnet/wcf/blob/956ed464b7813940413ccad22c2dc37c3b2be723/src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs#L49-L57

https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/TcpTransportSecurity.cs

**Comment by SteveL-MSFT** [comment]
@karelz Thanks for moving this.  Still need an answer on whether this is secure by default.  Note that in the code I'm porting, they are not using ClientCert auth so they can't use SslProtocols.  It is using TcpClientCredentialType.Windows.

**Comment by SteveL-MSFT** [comment]
@mconnew still need an answer whether it's secure by default or if we need to do something else to ensure it's secure

**Comment by mconnew** [comment]
It is secure by default. You can see the list of values for ProtectionLevel [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.protectionlevel?view=netframework-4.7.2). We use `EncryptAndSign` as our default. Looking at the source for the constructor of [TcpTransportSecurity](http://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/TcpTransportSecurity.cs,26) you can see we set it to `DefaultProtectionLevel` which is [defined in the same class](http://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/TcpTransportSecurity.cs,17) as `EncryptAndSign`.

**Comment by mconnew** [comment]
Closing issue as I believe it's been answered as fully as possible.
