### ISSUE TITLE
Add code example to WCF Web Service Reference provider docs (Docs not great)

### ISSUE THREAD

**Issue by m3zercat** [dotnet/wcf#2947]
Expected at least a code example on the page purporting to explain the usage of the generated service reference: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide

**Comment by mlacouture** [comment]
Hi @m3zercat, thanks for your feedback.  

In the meantime in case you are block, you can open the generated Referenece.cs file in Visual Studio and look at the methods on the ClientBase derived class. You find this file under the generated ServiceReference folder under the Connected Services tab. 

hope this helps,

**Comment by dasetser** [comment]
We have added links to the bottom of the page that lead to documentation about how to use WCF.
