### ISSUE TITLE
.NET 4.6.1 DLLs not included in System.ServiceModel.Security NuGet package?

### ISSUE THREAD

**Issue by chrispatrick** [dotnet/wcf#2950]
I am having trouble trying to consume System.ServiceModel.Security via NuGet. Looking inside the downloaded package, I can see a folder for .NET 4.5 that uses the version included in the framework, but no sign of anything for any later versions of .NET Framework. Using ProcMon shows that the application is looking for later versions than exist in .NET Framework 4.5, but they don't seem to exist in the NuGet package.

Looking at `System.ServiceModel.Security.pkgproj` shows the following comment:

`<!-- although this contract is inbox in .Net 4.5, we ship the new version as out-of-box in .Net 4.6 and later. -->`

But there is no declaration of anything related to .NET 4.6 in that file.

Should there be? Or am I going about this all wrong?

**Comment by Lxiamail** [comment]
@chrispatrick Thank you for reporting the issue. The issue has been fixed with 4.5.1 package at https://www.nuget.org/packages/System.ServiceModel.Security/4.5.1
