### ISSUE TITLE
The new WSDL generation tool doesn't use the default namespace.

### ISSUE THREAD

**Issue by ghost** [dotnet/wcf#2953]
In the traditional WSDL tool (Create/Update Service Reference), the dialog asks you for the name for the reference. If you type in 'Import', the old version would take the default namespace and add it to 'Import' (resulting in the internal namespace MyCompany.MyNamespace.Import in the generated file). With the .NET Core tool, you are forced to provide a complete namespace in the dialog for the name of the web service interface (that is, if you were to type in 'Import', you get the namespace 'Import' in the generated file).

**Comment by mlacouture** [comment]
Thank you @Dark-Bond for reporting this issue, we will review it and consider implementing the same behavior as in the traditional ASR tool.

**Comment by dasetser** [comment]
While we understand that not appending the default namespace may not be intuitive for users used to Add Service Reference, doing the same with the new tool would change the behavior from what users of this tool are used to and may cause more confusion for them. For this reason we have chosen to keep the behavior as is.
