### ISSUE TITLE
WCF configuration validation warning: The 'name' attribute is invalid -...

### ISSUE THREAD

**Issue by taternoe** [dotnet/wcf#2963]
Hi, 

I'm getting the warning, above, in my project. The service name attribute matches the name of the WCF service in my code, so it was puzzling. I was finally was able to reproduce the issue in a simple project. The warnings appear only if the target is x64. Here is a link to the project to reproduce:

https://1drv.ms/u/s!AiAA3nt2sx-6aXAhMXHJ9Jfd_rE

Here is a bunch of discussion about the issue:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/b6e830c3-423a-40aa-b9fb-8c58676eaf24/wcf-configuration-validation-warning-the-name-attribute-is-invalid-?forum=wcf

Thanks for any help you can provide.

Nate

**Comment by dasetser** [comment]
Hi taternoe,

Thanks for reporting this issue. You are right that this warning is a false positive. This is a bug in how Visual Studio validates your WCF configuration. It does so by analyzing the types in your project assembly, which it can only load if it's the same bitness as the VS process itself (32 bit) or if your library is built as AnyCPU. Is there a reason you can't target AnyCPU and have to target 64-bit specifically for your library?

As a workaround, you can turn off WCF's config validation feature and get rid of this warning by right clicking your project and going to Properties, then WCF Options and unchecking the "Validate WCF configuration when building the project" option.

Thanks,
Daniel

**Comment by taternoe** [comment]
Hi Daniel,

We have many 64-bit dependencies, so switching target to 'AnyCPU' is not an option for us.

Thanks,
Nate

**Comment by dasetser** [comment]
That makes sense. For now I would suggest disabling the feature for this project with the option I mentioned above. We'll look into seeing if we can make this work correctly in this scenario in a future release of VS. If not we should be able to at least update the warning message to give a better idea of what is happening.

**Comment by dasetser** [comment]
We've made a change to improve the warning message in this scenario in Visual Studio 2019. 

Note: Please report any Visual Studio issues unrelated to the WCF Connected Service to https://developercommunity.visualstudio.com in the future.
