### ISSUE TITLE
System.IO.FileLoadException When Refferencing ClientBase<T>

### ISSUE THREAD

**Issue by rashadrivera** [dotnet/wcf#2972]
Hello All,

I recently upgraded my .NET Standard 2.0 project to use the System.ServiceModel.Primative v4.5.1 NuGet package and now my UWP application is throwing a System.IO.FileLoadException when the code gets to a method that references the ClientBase<T> class.  

My .NET Std library is used for in both UWP and .NET Framework solutions.  My issue is similar to the post located at https://github.com/dotnet/wcf/issues/2293. Unfortunately I need this class because it provides the ability to configure the Bindings via the app.config file by name and UWP does not otherwise I would use the recommended approach to declare my own factory and bindings in C# code.

My thought is that there was a breaking change introduced.  I've tried the following scenario to reproduce the exception

1. Create a UWP project (calling it TestUWP)
2. Create a .NET Standard project (calling it TestLib)
3. Add a reference to the TestLib from TestUWP
4. Add the System.ServiceModel.Primitives NuGet package to TestLib
5. In the Class1 file, add the following method: 
   public static void Test() => typeof(System.ServiceModel.ClientBase<>).ToString();
6. In the TestUWP app, add a Button with a click event that invokes the Class.Test() static method.

**Comment by rashadrivera** [comment]
I have to also add that the EndpointAddress class also causes the same exception.  I've also discovered that you cannot use the assembly binding redirect because the public key token between the NuGet package and the UWP assembly versions are different (NuGet's signature = **B03F5F7F11D50A3A** and UWP signature = **cc7b13ffcd2ddd51** for the System.ServiceModel.Primative.dll)

**Comment by StephenBonikowsky** [comment]
In PR #3067

**Comment by JKennedy24** [comment]
@StephenBonikowsky will i need to do anything to my project to get this fix?

like:
Re-add WCF service
Update visual studio?
Update any nugets?

**Comment by StephenBonikowsky** [comment]
@JKennedy24 we have fixed the assembly and it will be part of the next released Microsoft.NETCore.UniversalWindowsPlatform package and VS 2017 update.

So either updating visual studio or updating the nuget package will get you this fix once it is available.

**Comment by JKennedy24** [comment]
@StephenBonikowsky what release of Microsoft.NETCore.UniversalWindowsPlatform package and VS 2017 update is this in?

Has this now been released?

**Comment by JKennedy24** [comment]
Thanks @StephenBonikowsky. Are you saying this should be fixed in V6.2.0-preview1-26926-04?

**Comment by StephenBonikowsky** [comment]
Yes

**Comment by chrisgull** [comment]
Seeing similar symptom including System.ServiceModel.Http 4.5.3 into a NetStandard 2.0 project. Latest released VS2017 version. 
Looking for workarounds.
