### ISSUE TITLE
.Net Standard 2.0 Project consuming WCF service Throws System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel.Http, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by JKennedy24** [dotnet/wcf#2980]
I have a .Net Standard 2.0 project which references a WCF service and it is throwing the following on UWP:

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel.Http, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

**Comment by mconnew** [comment]
I have been able to reproduce this error and am still investigating.

**Comment by rafsojka** [comment]
The same has happened to me when tried to use `use dotnet-svcutil.xmlserializer` in the project referencing `System.ServiceModel.Http 4.5.1`.
Downgrading to `System.ServiceModel.Http 4.5.0` did not help.
Only when removing `System.ServiceModel.Http` and adding back version 4.5.0 the tool generated XmlSerializers.dll

**Comment by Lxiamail** [comment]
@rafsojka This is a different problem than #2997.

**Comment by Lxiamail** [comment]
@JKennedy24 This is the same problem as #2972. This is a bug. We are looking into it.
