### ISSUE TITLE
Can't use web service in .net project xamarin forms

### ISSUE THREAD

**Issue by abdoelzamalkawy** [dotnet/wcf#2981]
i followed all steps in your guide document
https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide
when i try to run this code to invoke my method i received an exception 
this is the code 
![image](https://user-images.githubusercontent.com/16548842/41986349-296ea3d4-7a36-11e8-96a2-8723dfde82b9.png)
this is the error 
![image](https://user-images.githubusercontent.com/16548842/41986357-312d98fa-7a36-11e8-9f28-da7b76565b3d.png)
i don't know what is the problem 
please anyone can help me 
it is an urgent issue

**Comment by Lxiamail** [comment]
We use #2463 to track this active issue. However, still need to figure solution.
