### ISSUE TITLE
How do you use this in a debug mode?

### ISSUE THREAD

**Issue by XDSDevSMorgan** [dotnet/wcf#2987]
My apologies up front for such a newbie question. :-) 
I have downloaded and built everything just fine; but I'm not sure how to actually make use of all the DLL files that have been generated. Do I add a reference to these in my project or is there a package I add in? Thanks in advance!

**Comment by mlacouture** [comment]
Hi @XDSDevSMorgan! You are always welcome to ask any questions :).  Can you provide more details about what you are trying to achieve? and details about what you downloaded? thank you!

**Comment by mlacouture** [comment]
@XDSDevSMorgan, I'm closing this as we haven't heard from you in a while, please let us know if you need any assistance.
