### ISSUE TITLE
Add Connected Service error (Unknown error invoking service metadata component)

### ISSUE THREAD

**Issue by felipegtx** [dotnet/wcf#2994]
Hi,

I'm trying to use the "Add Connected Service" feature inside the VS2017 but I'm getting the following error message all the time.

![image](https://user-images.githubusercontent.com/1022404/42180153-869c6c92-7e0c-11e8-859a-7937f12b84c0.png)

Is there a log file I can take a look at and troubleshoot what's going on here?

I can successfully import this WSDL via `svcutil.exe`, btw.

**Comment by mlacouture** [comment]
Hi @felipegtx, thank you for reporting this issue.  What version of Visual Studio are you using? it seems to me based on the error message you are running an old version of the tool.  You need Visual Studio 2017 v15.5 or later, see the [docs ](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)for more info.
thanks

**Comment by felipegtx** [comment]
@mlacouture Thanks for such a fast reply. I'm actually using version `15.7.4` so it's probably something else.

![image](https://user-images.githubusercontent.com/1022404/42180955-85d82a32-7e0f-11e8-876b-124e715da137.png)

**Comment by mlacouture** [comment]
Thanks for confirming.  Please upgrade to a recent version of [Visual Studio 2017](https://visualstudio.microsoft.com/vs/preview/), Community or Preview releases are for free.  Alternatively, you can use the recently released [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) if upgrading VS is not an option for you.

**Comment by felipegtx** [comment]
@mlacouture I think you misunderstood me. I *have* the latest version.

**Comment by mlacouture** [comment]
oh sorry, I misread the VS version … do you happen to have the old version of the tool from the VS Marketplace installed? You can find out by looking at Tools -> Extensions and Updates (WCF Web Service Reference Preview).  if you do, please uninstall this tool and use the one that comes with VS.  If this is not the case, can you find the version of the tool you are using? you can find this information by looking at the version of the following file:  "%vsinstalldir%Common7\IDE\Extensions\Microsoft\WCF Connected Service\Microsoft.VisualStudio.ConnectedServices.Wcf.dll". 
thanks again

**Comment by felipegtx** [comment]
@mlacouture I don't have the Preview version. 

here's the information regarding the `ConnectedServices` dll:

![image](https://user-images.githubusercontent.com/1022404/42183383-02bd3a44-7e18-11e8-963a-64e67997db5f.png)

**Comment by mlacouture** [comment]
Thank you @felipegtx, it seems you are using a recent version of the tool.  Can you check if you have logs under %temp%\\WCFConnectedService? if so, can you send them to me (email on my profile)? thanks,

**Comment by felipegtx** [comment]
@mlacouture Nice. I just sent you the files!

Thanks!

**Comment by mlacouture** [comment]
Thank you @felipegtx, the logs were very useful.  I think you are hitting the same problem discussed in issue #2719, this problem occurs on VS 2017 v15.7P2 to v15.8P1 when running on .NET Core v2.1.

You have a couple of options:
1. Upgrade to the most recent release of Visual Studio 2017 [v15.8 Preview 3](https://visualstudio.microsoft.com/vs/preview/)
2. Apply the workaround discussed on issue #2719 

Alternatively, you could look into using [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) tool.

I hope this resolves your problem.  Let me know if you need any further assistance.

**Comment by felipegtx** [comment]
@mlacouture FYI, the fix from #2719 did fix this issue as well.

Thanks!
