### ISSUE TITLE
X509 certificate security support

### ISSUE THREAD

**Issue by alex-training** [dotnet/wcf#2996]
Hi everyone,

Are there any plans to support **X509CertificateEndpointIdentity**?

I believe it should be a part of the "**System.ServiceModel.Security**" nuget package

Also I'm wondering what is a replacement for **DefaultClaimSet** class ...

**Comment by StephenBonikowsky** [comment]
Tracking the addition of the X509CertificateEndpointIdentity in #3881 
Closing this issue in favor of that one.
