### ISSUE TITLE
dotnet-svcutil.xmlserializer issues when using with existing netcore 2.1 project

### ISSUE THREAD

**Issue by rafsojka** [dotnet/wcf#2997]
Hello,
I tried to use `dotnet-svcutil.xmlserializer` to speed up WCF client first requests by pregenerating XmlSerializers.dll.
When following [instructions](https://github.com/dotnet/core/blob/master/samples/dotnet-svcutil.xmlserializer-instructions.md) everything works seamlessly.

However when using with a real service, I have faced the following issues:

1. 
`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel.Http, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`
When tried to use use dotnet-svcutil.xmlserializer in the project referencing System.ServiceModel.Http 4.5.1.
Downgrading to System.ServiceModel.Http 4.5.0 did not help.
Only when removing System.ServiceModel.Http and adding back version 4.5.0 the tool generated XmlSerializers.dll (locally on Windows).

2. 
    The tool still complains about other assemblies:
    

> Microsoft (R) Service Model Metadata Tool\r\n[Microsoft (R) Windows (R) Communication Foundation, Version 1.0.0-preview1]\r\nCopyright (c) Microsoft Corporation. All rights reserved.\r\n
>     Generating XML serializers...
>     EXEC : warning : There were errors loading types in an assembly loaded from '***.dll' some types in the assembly could not be loaded and will not be available to the tool. [***.csproj]
> 
>     Could not load file or assembly 'Swashbuckle.AspNetCore.Examples, Version=2.9.0.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.Examples, Version=2.9.0.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.Examples, Version=2.9.0.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.Examples, Version=2.9.0.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.Examples, Version=2.9.0.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.Examples, Version=2.9.0.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'. The system cannot find the file specified.
>     Could not load file or assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'StatsdClient, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>     ***.XmlSerializers.cs

One thing is why it cannot load these assemblies but other is why it even attempts to load them?

3.
On the build agent (running Ubuntu) the tool fails to generate XmlSerializers.dll altogether, showing the same list of assemblies it cannot load but also

> [16:00:09][Step 1/4] ci-build_1 | /src/src/***/./obj/Release/netcoreapp2.1/***.XmlSerializers.cs
>     [16:00:09][Step 1/4] ci-build_1 | /root/.nuget/packages/dotnet-svcutil.xmlserializer/1.0.0-preview1/build/dotnet-svcutil.xmlserializer.targets(18,5): warning : Warning : Fail to generate the serializer for ***.dll. [/src/src/***.csproj]

It is hard to guess what it does not like this time, what I do not like is that it seem to mix up two types of slashes in the first message.

Does anybody know any way around these issues?
I ended up referencing the locally generated XmlSerializers.dll in the project but it is obviously not an ideal solution.

Thanks!

**Comment by huanwu** [comment]
@rafsojka We just released 1.0 version of dotnet-svcutil.xmlserializer. Could you try if it solve your problem?

**Comment by rafsojka** [comment]
@huanwu thanks, I am struggling to find a time to verify.
Will post an update once I get down to that.

**Comment by Lxiamail** [comment]
The issue should be fixed by 1.0 version of dotnet-svcutil.xmlserializer. Please let us know if you still have problem.
