### ISSUE TITLE
Support MessageSecurityOverTcp.ClientCredentialType in NetTcpBinding

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#3]
NetTcpBinding does not support MessageSecurityOverTcp.ClientCredentialType and will throw PlatformNotSupportedException if the property is read or set.

**Comment by roncain** [comment]
This is currently blocked by the lack of message security feature.

**Comment by bigswede74** [comment]
I'm trying to set the MaxClockSkew property when using the NetTcpBinding with TransportWithMessageCredential security mode. I assume this issue is why I cannot set the property as the feature is not supported? I'm targeting .NET Framework 4.7.1.

**Comment by mconnew** [comment]
It only took 3 years, but this is finally supported!!
