### ISSUE TITLE
Support non Active Directory based foreign realm identities with Kerberos auth

### ISSUE THREAD

**Issue by csharmath** [dotnet/wcf#30]
In a **cross platform environment** where there are separate Kerberos realms with a 2-way trust, current WCF implementation does not allow foreign non-windows AD based identities with Kerberos authentication unless the foreign realm identity has a mapped AD account with altSecurityIdentities = "Kerberos:user@linux.realm"

The issue with this is the unnecessary enforcement to **duplicate users between Kerberos realms** mapping them together even when there is no real need for that. 
This results in unnecessary duplication process work at large enterprises.
There can be cases, where the WCF service only needs to know the identity / authentication and it has it's *own implementation of the authorization bits which are not AD based*. 
In that case, it's not possible to have only the foreign realm by itself / not having it mapped to a Windows AD account.

**Example setup:**
  * A Kerberos realm for a Linux infrastructure with it's own KDC and a Windows AD having it's own Kerberos realm with a 2-way cross realm trust between the 2
  * Linux realm has a krb5.config pointing to the Windows AD as KDC for the windows domain
  * Linux realm has a user@linux.realm which is not mapped to an AD account
  * Windows AD having an IIS server with Kerberos:Negotiate authentication 
  * Windows IIS server configured with Service Principal Name ( SPN ) for default port 80 - like HTTP/hostname.windows.fqdn
  * IIS host to have a simple WCF service configured with windows integrated auth ( kerberos )
  * Linux user making a kerberized connection - curl --negotiate -u : http://iisbox.windows.fqdn/service.svc

**Results:**
   * Since there is a cross realm trust, the Linux client successfully obtain the tickets and makes the request
   * IIS authenticates and even logs the linux realm user in the IIS logs
   * WCF will try to find the mapped account in AD to get the SID and group membership
   * As the account is not mapped to and AD account, WCF will change the identity to be anonymous ( this is the problem )
   * the ValidateAnonymityConstraint method will throw an exception, resulting in a 401 unauthenticated HTTP response as the incoming identity cannot be anonymous when windows integrated auth is being used

**Other working setups:**
   * IIS is capable to authenticate and serve requests with Kerberos for non-mapped foregin realm users
   * ASP.NET as well and the non-mapped foreign realm identity will be added to the context user with no issue

So this is just a **WCF only issue** on the Microsoft stack. 

Reference code with ValidateAnonymityConstraint 
http://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Security/SecurityUtils.cs,87f77a91918ba8d2,references

**Proposal**
Just because the foreign realm identity can't be mapped to a Windows AD identity, it does not mean that the authentication has failed. Kerberos auth with IIS works fine, so as in ASP.NET. The proposal  could be to leave the identity as the foreign realm identity and do not switch to anonymous.
Also don't mix up authentication with authorization, let the app layer decide if the incoming identity can be authorized to make that particular service call.
With .NET Core being cross platform targeted this is definitely going to be an issue in other cases as well, not just the one presented in this issue.

**Notes on duplication**
While you could get away to just have a placeholder windows AD user account and map all foregin realm identities to that, that is not considered as a best practice by most of the IT Security policies, so the only option remains is a one-to-one mapping between the users from the 2 realms.
Also even if the many-to-one mapping was alowed, how many identites can you map to a single user ? 
Plus it's still an extra work to be done for each user in the foreign realm

**Question**
Once the relevant code is also on Github, would you accept a fix with this proposal or willing to review and fix it ?

**Comment by mountgellert** [comment]
+1

**Comment by roncain** [comment]
Thanks for such an extraordinarily detailed question @csharmath and the vote up @mountgellert . Let's continue the conversation here with @iamjasonp and @mconnew and anyone else who has thoughts on this. I need to come up to speed on what you propose.  And yes, we will be evaluating PR's. This is a good issue to start that thread.

**Comment by csharmath** [comment]
Thanks @roncain. Let me know if you have any questions, we've exhaustively debugged this issue before and I can dig up more details or happy to further clarify.
The TLDR version of the proposal is to let foreign realm identities which are not in AD and not mapped to any AD accounts to do Kerberos auth with WCF.  If there is a trust between the Kerberos realms, then IIS windows auth module will do it's job to authenticate and to set the identity properly, WCF should just accept it as a valid identity instead of mapping it to Anonymous.

**Comment by mconnew** [comment]
@csharmath, the issue you describe is a service side problem. The current open source effort is for WCF client scenarios, e.g. in a mid-tier situation. Unfortunately this means there isn't an opportunity to fix this issue in this repository. This issue might be better addressed by submitting to a bug to https://connect.microsoft.com/VisualStudio which is the current route for getting bugs addressed in the desktop version of .Net. If there's an aspect of this issue which affects WCF clients, for example with delegation in an asp.net hosted application, then there might be opportunity for solving at least part of the problem in this code base.

**Comment by csharmath** [comment]
Yes, it's a server side issue, nothing to do with clients.
I've missed the fact that this effort only focuses on the client side. Hopefully that will change soon, then it can be relevant to this repo. 
I was hoping that WCF as a whole is going opensource including services as well. It's not that clear/ easy to overlook btw in the communications...

I've filed it here as well
https://connect.microsoft.com/VisualStudio/feedback/details/1363858/wcf-support-non-active-directory-based-foreign-realm-identities-with-kerberos-auth

Thanks

**Comment by mconnew** [comment]
Closing the issue as opened on connect
