### ISSUE TITLE
An error occurred while attempting to find services (Message Security?)

### ISSUE THREAD

**Issue by derwasp** [dotnet/wcf#3000]
I tried adding a service reference for the following endpoint:
`https://ehpz-test.fa.em2.oraclecloud.com/fscmService/ErpIntegrationService` (`https://ehpz-test.fa.em2.oraclecloud.com/fscmService/ErpIntegrationService?wsdl`)

and this is the exception I got:
```
An error occurred while attempting to find services at 'https://ehpz-test.fa.em2.oraclecloud.com/fscmService/ErpIntegrationService'. The service at the following URI does not have any valid endpoints:'https://ehpz-test.fa.em2.oraclecloud.com/fscmService/ErpIntegrationService'. 
```

The same endpoint worked perfectly fine with the old .NET

What am I doing wrong?

**Comment by mlacouture** [comment]
Hi @derwasp!
Thank you for reporting this issue.  Looking at the service metadata it seems it requires Message Security which is not yet supported in the .NET Core platform (issue #8).

**Comment by mlacouture** [comment]
@derwasp, let us know if you need any further assistance.
