### ISSUE TITLE
Consider to add Namespace to MessageParameterAttribute

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/wcf#3007]
Right now both .net framework and .net core doesn't support specification of message part namespace if you define operation contract using parameters. You can do it only using message contracts by setting MessageBodyMemberAttribute.Namespace.

I don't know why this functionality is missing from parameters-based definition, but it an issue for us as we use parameter-based definition and now need to rewrite it to message contracts, becase one of our clients expose service where mesage parts have namespace != service namespace.

Interesting part that client's implementation (it is not .net) doesn't even validate namespaces so we can send request successfully, but response is not accepted due to namespace validation on our side.

I would suspect that MessageParameterAttribute will need two namespace properties to support ref parameters.

For reference, problem is here:
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs#L1256

**Comment by MaceWindu** [comment]
After looking into source code more, found workaround for our specific case, so we can still stick to parameter-based contracts.
```
[XmlSerializerFormat(Style = OperationFormatStyle.Rpc)]
// ...service interface here...
```

**Comment by StephenBonikowsky** [comment]
@MaceWindu Sorry we didn't get to this sooner but I'm glad you were able to find a workaround.

**Comment by Lxiamail** [comment]
@MaceWindu Your workaround is the right way to do it.
