### ISSUE TITLE
DuplexChannelFactoryTests will fail due to lack of WindowsStreamSecurity

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#301]
There are numerous tests that fail in DuplexChannelFactory testing because of a dependency on NetTcpBinding's use of WindowsStreamSecurity - #300. 

Upon calling `CreateChannel`, the factory will throw an exception as 
`System.ServiceModel.Channels.WindowsStreamSecurityBindingElement.BuildClientStreamUpgradeProvider(BindingContext context)` is not yet implemented. 

These tests would previously pass due to the binding entirely omitting WindowsStreamSecurity, but as we are turning on more features (and hence stubbing others), we have run into this. 

Fix by either implementing #300, or by changing the tests not to depend on the default ctor of NetTcpBinding.

**Comment by iamjasonp** [comment]
Two action items to this one: 

1. Add new tests for the same scenarios but using no security on the binding 
2. Re-enable these tests when WindowsStreamSecurity makes it into WCF Core

**Comment by StephenBonikowsky** [comment]
This is my proposal for each test that I found was touched as part of PR #311 
	SCENARIO TESTS
	Test Case: Scenarios.Security.TransportSecurity.Tcp.ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString()
	Was already being skipped using Issue 81, Jason updated it to Issue 300
	ACTION: Leave alone.
	
	Test Case: Scenarios.Security.TransportSecurity.Tcp.ClientCredentialTypeTests.SameBinding_SecurityModeTransport_EchoString()
	Was already being skipped using Issue 81, Jason updated it to Issue 300
	ACTION: Leave alone.
	
	Test Case: Scenarios.Security.TransportSecurity.Tcp.ClientCredentialTypeTests.SameBinding_SecurityModeTransport_ClientCredentialTypeCertificate_EchoString()
	Is a new test being skipped with Issue 310
	ACTION: Leave alone.
	
	UNIT TESTS
	Test Case: Unit.Primitives.ServiceModel.DuplexChannelFactoryTest.CreateChannel_Using_NetTcpBinding_Defaults()
	Was already being skipped using Issue 81, Jason updated it to Issue 300
	ACTION: Leave alone.
	
	Test Case: Unit.Primitives.ServiceModel.DuplexChannelFactoryTest.CreateChannel_EndpointAddress_Null_Throws()
	Verifies that creating a DuplexChannelFactory with a NULL EndpointAddress throws an InvalidOperationException.
	PR311 causes this test to now fail for a different reason.
	ACTION: This test should not care whether the binding is using transport security or not, should modify this test to remove transport security from the binding and then remove the ActiveIssue attribute.
	
	Test Case: Unit.Primitives.ServiceModel.DuplexChannelFactoryTest.CreateChannel_ExpectedNetTcpScheme_HttpScheme_ThrowsUriFormat()
	Verifies that creating a DuplexChannelFactory with the wrong scheme throws an ArgumentException.
	ACTION: This test should not care whether the binding is using transport security or not, should modify this test to remove transport security from the binding and then remove the ActiveIssue attribute.
	
	Test Case: Unit.Primitives.ServiceModel.DuplexChannelFactoryTest.CreateChannel_ExpectedNetTcpScheme_InvalidScheme_ThrowsUriFormat()
	Verifies that creating a DuplexChannelFactory with an invalid scheme throws an ArgumentException.
	ACTION: This test should not care whether the binding is using transport security or not, should modify this test to remove transport security from the binding and then remove the ActiveIssue attribute.

**Comment by iamjasonp** [comment]
#317 fixes three tests, four remaining.

**Comment by StephenBonikowsky** [comment]
Actually three remaining, they will be fixed when Issue #300 and Issue #310 get merged.
SameBinding_SecurityModeTransport_EchoString()
CreateChannel_EndpointAddress_Null_Throws()
CreateChannel_Using_NetTcpBinding_Defaults()

**Comment by iamjasonp** [comment]
- [x] SameBinding_SecurityModeTransport_EchoString()
- [x] CreateChannel_EndpointAddress_Null_Throws()
- [x] CreateChannel_Using_NetTcpBinding_Defaults()
