### ISSUE TITLE
NetSuite WSDL Not Working

### ISSUE THREAD

**Issue by LightspeedNZ** [dotnet/wcf#3023]
I've tried using this tool (Add Connected Service, Microsoft WCF Web Service Reference Provider into a .Net Core 2.1 console application) but it does not bring in the NetSuite WSDL service correctly.

https://webservices.netsuite.com/wsdl/v2017_2_0/netsuite.wsdl

Importing this in a .NET Framework WinForm application via the 'Add Service Reference, Advanced, Add Web Reference' works fine and I can access the NetSuite service with the following line of code.

`public NetSuiteService service = new NetSuiteService();`

Any idea what is going on here?

**Comment by mlacouture** [comment]
Hi @LightspeedNZ 
Thank you for reporting this issue.  Can you please provide more details about the problem? what is not correct? Also, please let us know the version of Visual Studio 2017 you are using.

thanks,

**Comment by mlacouture** [comment]
Observe that the generated client name is NetSuitePortTypeClient and not NetSuiteService ...

**Comment by LightspeedNZ** [comment]
Hi Miguel, sorry I missed the name change. I have found this now and will do some testing.

Thanks for your clarification on this!

**Comment by benwmills** [comment]
I have a related problem.  On the old NetSuiteService type there was an add method that had a Record parameter and returned a WriteResponse object.  This is in line with NetSuite's documentation.  Consuming the service using WCF, I now see the new NetSuitePortTypeClient object and it has an add method, but it now has this signature:

public DocumentInfo add(Passport passport, TokenPassport tokenPassport, ApplicationInfo applicationInfo, PartnerInfo partnerInfo, Preferences preferences, Record record, out WriteResponse writeResponse)

Is there any way to have WCF generate objects and methods in the way that old style web references did?
