### ISSUE TITLE
Light up async paths needed for Ssl StreamSecurity

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#303]
The work done for #9 has for the moment stripped out any async paths in the interest of time. These paths needs to be added back. 

In: 
* src/System.Private.ServiceModel/src/System/ServiceModel/Channels/FramingChannels.cs

**Comment by shmao** [comment]
`SecurityUtils.OpenCommunicationObject()` is not currently being covered by any test case. Let `SslStreamSecurityUpgradeInitiator.OpenAsync()` keep calling `SecurityUtils.OpenTokenProviderIfRequired()` for now.

**Comment by shmao** [comment]
Fixed by #509
