### ISSUE TITLE
can not consume service netcoreapp2.1

### ISSUE THREAD

**Issue by SurushS** [dotnet/wcf#3030]
I'm pretty sure it has to be me but just to make sure.
Does svcutil integration with Visual Studio have support for NetCore 2.1?
If i start out by creating a console application and then selecting "Add Connected Service" followed by "Microsoft WCF Web Service Reference Provider" and consuming any wsdl, i get the following message. Im using the latest Visual Studio 2017 (15.7.3). I get this error when consuming. If i downgrade the framework to netcoreapp2.0, it works fine. 

![screen shot 2018-07-16 at 11 37 22](https://user-images.githubusercontent.com/35565295/42752171-5cb7f324-88ed-11e8-811b-ee95b344779e.png)

Anyone got tips on what i'm missing?

**Comment by bungceting** [comment]
could that be the SDK you're on that is not supported yet? it happened to me as well when I had 2.1.2 SDK v2.1.302, but according to https://github.com/dotnet/wcf/releases (as of today) it only supports up to 2.1.1. Therefore I installed 2.1.1 as well from here: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.1-download.md

**Comment by mlacouture** [comment]
Hi @SurushS, thank you for reporting this issue.  This is a dup of #2994.
