### ISSUE TITLE
Expect: 100-continue

### ISSUE THREAD

**Issue by giovanibarili** [dotnet/wcf#3048]
I had problems to calling a WSDL and detect that this problems start with release 4.5.0+. 
Below source to reproduce the problem.

```
static void Main(string[] args) {
 var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
 binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
 binding.Security.Transport.ProxyCredentialType = HttpProxyCredentialType.None;
 binding.UseDefaultWebProxy = true;


 var endpointAddress = new EndpointAddress("https://apphom.correios.com.br/logisticaReversaWS/logisticaReversaService/logisticaReversaWS");

 var clientWS = new logisticaReversaWSClient(binding, endpointAddress);

 clientWS.ClientCredentials.UserName.UserName = "empresacws";

 clientWS.ClientCredentials.UserName.Password = "123456";

 var retorno = clientWS.solicitarPostagemReversaAsync("123",
  "123",
  "123",
  new pessoa() {
   bairro = "",
    cep = "",
    cidade = "",
    complemento = "",
    ddd = "",
    email = "",
    logradouro = "",
    nome = "",
    numero = "",
    referencia = "",
    telefone = "",
    uf = ""
  },
  new List < coletaReversa > () {
   new coletaReversa() {
    id_cliente = "1564"
   }
  }.ToArray()).Result;
}
}
```

```
The remote server returned an unexpected response: (100) Continue.
```

```
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
```

**Comment by StephenBonikowsky** [comment]
@giovanibarili thanks for reporting the issue, we'll look into it.

**Comment by mconnew** [comment]
@giovanibarili, we made a change in the 4.5.0 release to enable using the Expect header as there is a new HttpClientHandler stack which now supports this on all platforms. Basically it's purpose is to prevent the request body to be sent repeatedly for every part of an authentication handshake. The HttpClient sends all the HTTP headers along with the Expect header and waits for the server to either return a 100 status code which means everything is good with the headers so go ahead and send the request body, or it returns a different status code with a full response. For example, the server could return a 401 status code along with a WWW-Authenticate challenge header to indicate the client needs to authenticate using the provided authentication challenge header.  
HttpClient shouldn't ever return a 100 response back to the caller so this is a bug in HttpClientHandler. I need a bit more info though as there isn't enough info to open a meaningful bug against that component. Could you time how long your call to solicitarPostagemReversaAsync is taking? You can do it simply like this:
```c#
var sw = Stopwatch.StartNew();
try
{
    // Make your call
}
finally
{
    Console.WriteLine($"Call took {sw.Elapsed.TotalSeconds} seconds to complete");
}
```
If the 100 continue response doesn't come back within an expected period of time (1 second by default I believe), HttpClientHandler will go ahead and send the request body anyway. If the server responded with the 100 continue status at the same time as the HttpClient timed out waiting, I suspect there's a race condition where it's taking the 100 status as the final status. Knowing how long your call took before you got the exception will help in determining this.

**Comment by mconnew** [comment]
I've just spent some more time with the code in the new HttpClientHandler stack and the code around this is very robust. I couldn't find any opportunity for a race condition. I believe this could be a server issue when the Expect header is being sent. Would you be able to capture a [fiddler trace](https://www.telerik.com/fiddler). You will need to turn on streaming mode as otherwise it might interfere with how the expect header behaves. You turn this on by clicking the button on the toolbar which says "Stream" and has 2 down arrows which causes the button to have a box around it. You will also need to enable decrypting of HTTPS traffic under options.

**Comment by mconnew** [comment]
I've had a closer look at the HTTP spec in RFC7231 and the server sending multiple 100 continue status responses is valid. It's valid according to the spec, I believe to account for intermediate proxy's return their own 100 continue header causing the client to see multiple. I'll open an issue in the corefx repo about this.

**Comment by mconnew** [comment]
@giovanibarili, if you update to the latest version of .NET Core, this problem should now be fixed. Can you please verify that you aren't seeing this problem any longer?
