### ISSUE TITLE
Use x509Certificates for both CoreCLR and NET Native when available

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#306]
The current security work underway is adding a dependency on x509Certificates for only the CoreCLR version.  This current issue is to track the deliver of NET Native x509Certificates and to update the code where it is currently #if FEATURE_CORECLR.

**Comment by zhenlan** [comment]
There are two steps for this item:
First, we want to look into feasibility of converting x509Certificate to RT certificate so that it can be used in UWP apps.
Second, we need to plum through and update the code.

**Comment by shmao** [comment]
I've done my experiments with certificates and verified that conversions between WinRT cert and X509 cert were possible.

I'm waiting for X509Certificate support being available in Net Native.

**Comment by zhenlan** [comment]
According to @mconnew the x509certificate support was just added in .NET Native. @shmao you should be able to proceed with this work item.
