### ISSUE TITLE
Misc build failures in 'official/wcf/release/2.0.0/' - '20180725.01'

### ISSUE THREAD

**Issue by MattGal** [dotnet/wcf#3060]
Due to commit fbf87b79510e361b0f45a097ba6efd4fd770f93d, the WCF Release 2.0 build is no longer able to harvest stable package versions. 

@dotnet-mc-bot commented on [Tue Jul 24 2018](https://github.com/dotnet/core-eng/issues/3934)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1888800
  - **Agent:** DDVSOWINAGE015
  - **Error log:** E:\A\_work\0\s\Tools\Packaging.targets(0,0): error : Cannot harvest package 'System.Private.ServiceModel' version '4.3.4' because E:\A\_work\0\s\packages/System.Private.ServiceModel\4.3.4 does not exist.  Harvesting is needed to r...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1888801
  - **Agent:** DDVSOWINAGE018
  - **Error log:** E:\A\_work\0\s\Tools\Packaging.targets(0,0): error : Cannot harvest package 'System.Private.ServiceModel' version '4.3.4' because E:\A\_work\0\s\packages/System.Private.ServiceModel\4.3.4 does not exist.  Harvesting is needed to r...

@StephenBonikowsky let me know if you need any infra-support from this, it looks more like you may need to manually (or via some other build?) publish these stable package versions before the changes can build.

**Comment by StephenBonikowsky** [comment]
Sorry for the noise @MattGal I got ahead of myself with a check-in, I fixed it pretty quickly but you caught the one build with the problem :(
