### ISSUE TITLE
Configure WCF URLs during deployment

### ISSUE THREAD

**Issue by RaviTejaKaruturi** [dotnet/wcf#3070]
Hi,
I have a class library project which contains two WCF client references. This library is referenced in a Web app. Previously, with in .NET framework Web app, all that we need to do is change WCF URLs in web.config file during deployment depending on ENV. 
But with .NET core we do not have .config file. Even ConnectedService.json files are added to the release folder. So, how do I replace WCF URLs during deployment?
Do I have to configure WCF URLs in appsettings.json and implement partial method `ConfigureEndpoint` ?

**Comment by mlacouture** [comment]
Hi @RaviTejaKaruturi 
This is a very good question and you hit the points that lead to the answer.  Implementing the partial method is the preferred way.  Another option is to add the service reference again but this time generated from the production URI (after removing the previous reference folder).  The last option as you guessed, is to edit the _connectedservice.json_ file with the production URI and update the web service reference (right-click the service reference folder and select _Update Microsoft WCF Web Service Reference Provider …_) option.
hope this helps,

**Comment by RaviTejaKaruturi** [comment]
Hi @mlacouture 
Thank you.
Correction from my above comment
ConnectedService.json files are **not** added to the release folder.
I am going with the preferred way.

**Comment by mlacouture** [comment]
sounds good, thank you for confirming @RaviTejaKaruturi
