### ISSUE TITLE
Make dotnet-svcutil a global tool (Unable to install as dotnet global tool)

### ISSUE THREAD

**Issue by galloglach** [dotnet/wcf#3071]
I would like to run dotnet-svcutil from the command line without it having to be included as a DotNetCliToolReference element in a csproj file.
Thought it could be installed as a tool, but I get an error when I try `dotnet tool install -g dotnet-svcutil`.

> error NU1212: Invalid project-package combination for dotnet-svcutil 1.0.1. DotnetToolReference project style can only contain references of the DotnetTool type
> The tool package could not be restored.
> Tool 'dotnet-svcutil' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.

**Comment by mlacouture** [comment]
Hi @galloglach 
This is currently not supported.  I have changed the title to track your request and consider it for the near future.
thanks,

**Comment by dasetser** [comment]
This is done as part of the dotnet-svcutil 2.0.0 release.
