### ISSUE TITLE
Add new functionality to WCF contracts - 2015.10 edition

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#308]
As we start turning on new features, we will start encountering issues where we would like to add new contract. This issue will keep track of all the issues that require contract additions. 

Please open an issue and add to the list below.

New APIs to be added:
* X509 Certificates: expose client cert setters - #302
* ChannelFactory.Credentials.ServiceCertificate.Authentication - #243
* Add support to specify SSL/TLS version for NetTcp with certificate security - #39

**Comment by hongdai** [comment]
* Service Certificate Authentication mode: client can configure Service Certificate Authentication mode( X509ServiceCertificateAuthentication) from ChannelFactory.Credentials.ServiceCertificate.Authentication - #243

**Comment by zhenlan** [comment]
Add support to specify SSL/TLS version for NetTcp with certificate security - #39

**Comment by iamjasonp** [comment]
All resolved now. 

Part3: #440
Part2: #436
Part1:#429 (#411)
Master PR: #385
