### ISSUE TITLE
Can't select serializer in WCF Web Service Reference Provider Tool

### ISSUE THREAD

**Issue by kevinoid** [dotnet/wcf#3082]
When using the Microsoft WCF Web Service Reference Provider Tool in Visual Studio, there does not appear to be a way to set the serializer to XmlSerializer (corresponding to the `--serializer XmlSerializer` option to `dotnet svcutil`).  This would be a very useful feature for projects which require the use of `XmlSerializer` (e.g. due to #3081).

Note:  For my current needs it is not necessary to provide a GUI option for setting the serializer.  In the full .NET Framework version it was possible to edit `Reference.svcmap` to set `<Serializer>XmlSerializer</Serializer>`.  If it were possible to add `"Serializer": "XmlSerializer"` or similar to `ConnectedService.json` that would be sufficient for me.

Thanks,
Kevin

**Comment by dasetser** [comment]
@kevinoid This is now possible in Visual Studio 2019. We did not add a UI option for it, but after adding the connected service you can modify the ConnectedService.json and add the following line:
 "serializer": "XmlSerializer"

If you then update the service reference it should use the correct serializer.

**Comment by kevinoid** [comment]
Sounds great.  Thanks @dasetser!
