### ISSUE TITLE
Missing Realm property in HttpTransportSecurity

### ISSUE THREAD

**Issue by farlop** [dotnet/wcf#3087]
I'm having trouble trying to Access some SAP web services using the 'WCF Connected Service' in a .NET Core 2.1 app.

In first place, after adding the reference to the service, I've found that the `ClientCredentialType `property in `GetBindingForEndpoint `method  of auto-generated Reference.cs was not set to Basic, so it was ignoring my username/password with this message 

`The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic realm="XISOAPApps"'. `

After fixing this, now the error changes to

`The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm="XISOAPApps"'. `

I've tried to change the Realm property, but I've found that it no longer appears in HttpTransportSecurity. 

How can I set the realm?

**Comment by mlacouture** [comment]
Hi @farlop!
The problem you are experiencing doesn't seem to be related to the security realm, please refer to issue #1992 for more information.  Just to make sure, did you check with your service provider to ensure your client credentials are correct?
thanks,

CC @mconnew

**Comment by mlacouture** [comment]
Hi @farlop, are you still seeing this issue? were you able to verify your credentials? thanks,

**Comment by farlop** [comment]
Hi! Sorry for not updating sooner. In the end, it was a bad credentials issue (after double checking with provider). Why the error message is so misleading?

Thank you for your help.

**Comment by mlacouture** [comment]
Thank you for the update.  The message is provided by the server.  I'm glad you were able to figure out this issue.

**Comment by colewerner** [comment]
I'm getting the same error you originally pasted however I have not been able to make it past that:

> The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic realm="XISOAPApps"'.

My wcf config should be specifying that it's using basic auth and not anonymous:

```
<binding name="some_binding_name">
    <security mode="TransportCredentialOnly">  
        <transport clientCredentialType="Basic" />  						
    </security>  
</binding>
```

**Comment by farlop** [comment]
My original issue was using .NET Core, but it seems that you are using .NET Framework, due to your XML configuration, am I right?

**Comment by colewerner** [comment]
@farlop Yes you are correct and as it turns out the configuration I posted above was right for me but the first time it was tried the other party involved didn't save the config file correctly so those settings were not being used.  Thanks for responding!
