### ISSUE TITLE
ASP Core - There was no endpoint listening at [url] that could accept the message. 

### ISSUE THREAD

**Issue by PepekT** [dotnet/wcf#3090]
Hello,

I am developing ASP.NET Core application (core 2.1) and using connected WCF service.
Everything was fine, but I have new computer and now I have with same project problem.

I am getting this error:

> There was no endpoint listening at http://10.xxx.xxx.xxx:12345/Service.svc that could accept the message. This is often caused by an incorrect address or SOAP action

I tested this project on 4 devices:

- New computer (WIN 10, VS 2017 professional, connecting to IP) --> Not working
- Old computer (WIN 7, VS 2017 community, connecting to IP) --> Working
- Colleague's computer (WIN10, VS 2017 professional, connecting to IP) --> Not working
 - Virtual computer (WIN10, VS community, WCF host, connection to localhost) --> Working

**On new computer:**
-  I am able to access service through web browser (I am able to see wsdl file)
- When I create WPF project --> WCF is working correctly

I tried to use project  from home (I have to connect to corporate network through VPN) and everything working! So my opinion is that there some problem with connection.

So finally my questing - There are some requirements for WCF client to set ? I already spent 4 days with this problem and I don't know what to check.. Thank you for every advice.

**Comment by PepekT** [comment]
Finally I found a sollution.

I find out, that I am able to use service from home through VPN. So I searched some problem where are people able to access through VPN.

It was problem with proxy -  This post helped me fix problem:
 [](https://github.com/dotnet/wcf/issues/1592)

According to mconnew's answer:

    HttpClient in .Net Core doesn't use WinINet which picks up its proxy settings from the same place as you configure IE/Edge proxy settings. It uses WinHTTP instead which maintains its own proxy settings. From an administrative command prompt execute the command netsh winhttp
      reset proxy to reset WinHTTP to use direct connections instead. If you want to see what it's currently set as, execute the command netsh winhttp show proxy before you modify it. It looks like your IT department probably missed resetting this configuration when getting rid of the proxy.

So I tried netsh winhttp show proxy on both computers.

New computer had some reccords about proxy and old none. Then I tried netsh winhttp reset proxy then i had same WinHTTP proxy settings as old computer.

Then I was able to use WCF service :-)

**Comment by holatade** [comment]
Hi PepekT am a newbie, but am getting/experiencing the same, how do i go about running this command, the project was deployed via azure devops. Would appreciate any help.
