### ISSUE TITLE
Push message from wcf service to Windows Universal App with no data

### ISSUE THREAD

**Issue by BarryWangMSFT** [dotnet/wcf#3108]
Hi all,

This is a question ping back from a MSDN thread: 
https://stackoverflow.com/questions/51310389/push-message-from-wcf-service-to-windows-universal-app

The problem is "when service push data to the client using callback. When service broadcasts to app, app gets nothing. Next time service try to broadcast or client try to send request the channel is broken. Client gets no exception, just doesn't receive response."

This issue can be reproduced from us and looks like it is a platform specific issue. So report it for the customer.

**Comment by mconnew** [comment]
@BarryWangMSFT, do you have a repro project for this?

**Comment by Lxiamail** [comment]
@BarryWangMSFT Since haven't heard from you for a while, close this issue. Please let us know if there is still an issue
