### ISSUE TITLE
Is it possible to serialize object exactly as it's done underneath?

### ISSUE THREAD

**Issue by itrofimow** [dotnet/wcf#3109]
Basically what title says - i need to get serialized object to reuse it somewhere else, but can't find a proper way to do so. 

I mean i'd like to get exactly the same representation, as in IClientMessageInspector.BeforeSendRequest, but seem unable to do so, cause some MessageContract attributes get ignored by whatever combination of serealizers i use(but they aren't ignored by generated wcf client).
Google says TypedMessageConverter has to be used for these attributes to be serialized, but that class is missing.

**Comment by Lxiamail** [comment]
@itrofimow Not sure if you still have the same problem. If so, can you share a repro program?

**Comment by itrofimow** [comment]
Well it's not a bug i guess, more of a question, so a repro just can't be provided.  

Basically the question is: given the client class and DTO classes, generated by svcutil, how do i serialize any generated DTO to a string, that matches BYTE-to-BYTE what would be sent over the network, without actually sending it or even creating connections, channelFactories, channels etc (all that wfc stuff)?

**Comment by Lxiamail** [comment]
@itrofimow It's not supported.
