### ISSUE TITLE
Convert projects to SDK-style

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/wcf#3116]
We recently migrated all our projects to SDK-style ones in corefx (https://github.com/dotnet/corefx/pull/29831). Coreclr is doing the same now and migrate the 10k+ test projects with https://github.com/dotnet/coreclr/pull/19282. Core-setup already migrated.

To make certain assumptions and make buidltools / arcade updates easier WCF should also migrate to SDK style projects to align with corefx. You can take a look at the corefx PR for what was necessary. Note that a lot of work in buildtools is of course already done and can just be consumed. If you need help with the migration let us know.

cc @eerhardt @danmosemsft

**Comment by ViktorHofer** [comment]
Related: https://github.com/dotnet/corefx/pull/31260 which also needs to be done in wcf and would benefit from this.

**Comment by StephenBonikowsky** [comment]
@Lxiamail we should discuss this, also I think the 'tooling' label is incorrect. It should be Infrastructure.

**Comment by StephenBonikowsky** [comment]
This has been done.
