### ISSUE TITLE
Difference between System and Microsoft namespaces

### ISSUE THREAD

**Issue by antonioortizpola** [dotnet/wcf#3129]
We have an old project that we migrate to Core 2.1, now we are trying to add a new WSDL service, so i added the dependency for the cli:

`<PackageReference Include="dotnet-svcutil" Version="1.0.2" />`

Then i created my files, however i see the base generates:

`Microsoft.CodeDom.Compiler.GeneratedCodeAttribute`

And this library is not found in my project, checking my old services y see

`System.CodeDom.Compiler.GeneratedCodeAttribute`

What is the difference between both libraries? what is the correct library to use in a Net Core 2.1 app?.

I also noticed that the same namespace change was applied for the serialization also

`System.Xml.Serialization.XmlTypeAttribute`

versus

`Microsoft.Xml.Serialization.XmlTypeAttribute`

I check an option `--noStdLib` in the help says:

> Do not reference standard libraries. By default System.Runtime (mscorlib) and System.ServiceModel (WCF) libraries are referenced

Why choose this or the other libs? what is the right aproach to make my app run in a linux server?, i Tried adding `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` but it does not include `Microsoft.CodeDom.Compiler.GeneratedCodeAttribute`, and installing the dotnet-svcutil as library imports these classes, but it breaks my app duplicating some dll

> Cannot resolve constructor 'Exception(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)', candidates are: Exception(string, System.Exception) (in class Exception) Exception(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext) (in class Exception)

**Comment by mlacouture** [comment]
Hi @antonioortizpola 

Thank you for reporting this issue!  I noticed you added the tool as a regular package reference instead of a tool reference, it should look like the following:

`<DotNetCliToolReference Include="dotnet-svcutil" Version="1.0.*" />`

Using the tool as a package reference is not supported.  For more details, check the [tool guide doc](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide).

Still, I'm curious about how you got the code generated with the wrong namespaces, did you get any warnings during code generation? if so, can you re-run the tool with the verbosity option set to 'debug' and redirect the output to a log file that you can send to us?

thank you!

**Comment by antonioortizpola** [comment]
Thanks for the quick response!

First, sorry, my mistake, First I added `dotnet-svcutil` as a tool reference, I just added it also as a package reference after the namespaces errors where shown.

So, to clarify better, my old services are something like this:

```
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.csapi.org/wsdl/userprofile/service", ConfigurationName = "AmHubUserProfileService.UserProfile")]
public interface IUserProfile
{

	[System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
	[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
	System.Threading.Tasks.Task<AmHubUserProfileService.obtainProfileResponse1> obtainProfileAsync(AmHubUserProfileService.obtainProfileRequest1 request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/userprofile/local")]
public partial class obtainProfileRequest
{
	public string msisdn { get; set; }
}
```

It is worth notice that this services are working fine in Core 2.0 and 2.1, so, i add the `scv-util` only as tool:

```
...
<ItemGroup>
<DotNetCliToolReference Include="dotnet-svcutil" Version="1.0.2" />
</ItemGroup>
<ItemGroup>
<PackageReference Include="System.ServiceModel.Http" Version="4.5.3" />
<PackageReference Include="System.ServiceModel.Security" Version="4.5.3" />
</ItemGroup>
...
```

Everything seems fine, so I generate my definition:

`dotnet svcutil userprofile.wsdl --verbosity Debug`

> Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
> [dotnet-svcutil, Version 1.0.2]
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Attempting to load metadata from 'C:\Users\Antonio\source\repos\VTAE\vtae.integrations\userprofile.wsdl'.
> [876.279] Importing metadata ...
> Error: An item with the same key has already been added. Key: UserProfile
> [876.279] Time elapsed: 00:00:00.9493981
> [876.229] Processing Code DOM ...
> Generating files...
> C:\Users\Antonio\source\repos\VTAE\vtae.integrations\ServiceReference1\Reference.cs
> [876.229] Time elapsed: 00:00:00.0716109

The error maybe comes from the wsdl definition file, i can post it if is necessary. Despite the error, a file is generated, but the namespaces are different:

```
[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.2")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.csapi.org/wsdl/userprofile/service", ConfigurationName="UserProfile")]
public interface UserProfile
{
    
    // CODEGEN: Generating message contract since the operation obtainProfile is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    obtainProfileResponse1 obtainProfile(obtainProfileRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<obtainProfileResponse1> obtainProfileAsync(obtainProfileRequest1 request);
}

/// <remarks/>
[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.2 @[f181c88bd2b6502ff196e6d95545b6d9c45f0163]")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[Microsoft.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/userprofile/local")]
```

The file is using `Microsoft.CodeDom` and `Microsoft.Xml` namespaces, I do not know how to get that packages, or what is the difference between them and the ones used in our old services

**Comment by antonioortizpola** [comment]
The file is read fine in SoapUI, generating a very simple body:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:loc="http://www.csapi.org/schema/userprofile/local">
   <soapenv:Header/>
   <soapenv:Body>
      <loc:obtainProfileRequest>
         <loc:msisdn>?</loc:msisdn>
      </loc:obtainProfileRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

If can help, this is the wsdl file to be parsed:
```
<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
   name="userprofile"
   targetNamespace="http://www.csapi.org/wsdl/userprofile/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/userprofile/service"
   xmlns:userprofile_local_xsd="http://www.csapi.org/schema/userprofile/local">

   <wsdl:types>
      <xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.csapi.org/schema/userprofile/local">

         <xsd:complexType name="UserProfile">
            <xsd:sequence>
               <xsd:element name="msisdn" type="xsd:string"/>
               <xsd:element name="pago" type="xsd:string"/>
               <xsd:element name="region" type="xsd:string" minOccurs="0" maxOccurs="1"/>
               <xsd:element name="iva" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
         </xsd:complexType>

         <xsd:element name="obtainProfileRequest" type="userprofile_local_xsd:obtainProfileRequest"/>
         <xsd:complexType name="obtainProfileRequest">
            <xsd:sequence>
               <xsd:element name="msisdn" type="xsd:string"/>
            </xsd:sequence>
         </xsd:complexType>

         <xsd:element name="obtainProfileResponse" type="userprofile_local_xsd:obtainProfileResponse"/>
         <xsd:complexType name="obtainProfileResponse">
            <xsd:sequence>
               <xsd:element name="result" type="xsd:int"/>
               <xsd:element name="userProfile" type="userprofile_local_xsd:UserProfile" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
         </xsd:complexType>
      </xsd:schema>
   </wsdl:types>

   <wsdl:message name="UserProfile_obtainProfileRequest">
      <wsdl:part name="parameters" element="userprofile_local_xsd:obtainProfileRequest"/>
   </wsdl:message>

   <wsdl:message name="UserProfile_obtainProfileResponse">
      <wsdl:part name="result" element="userprofile_local_xsd:obtainProfileResponse"/>
   </wsdl:message>

   <wsdl:portType name="UserProfile">
      <wsdl:operation name="obtainProfile">
         <wsdl:input message="tns:UserProfile_obtainProfileRequest"/>
         <wsdl:output message="tns:UserProfile_obtainProfileResponse"/>
      </wsdl:operation>
   </wsdl:portType>

   <wsdl:binding name="UserProfileBinding" type="tns:UserProfile">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="obtainProfile">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="UserProfileService">
      <wsdl:port name="UserProfile" binding="tns:UserProfileBinding">
         <soap:address location="http://localhost:9080/UserProfileService/services/UserProfile"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
```

**Comment by mlacouture** [comment]
@antonioortizpola, thank you very much for providing the details.  This is the same issue as #3103 for which we have a fix that will be available with the next release of the tool.   This happens when the same name is used for a port type (contract) and a composite type, in your case the 'UserProfile'.  You may be able to work around it by changing the name of the port type (and associated usage) to 'IUserProfile' for instance.
Please stay tuned for the next release which should be out in a couple of weeks or so ...

**Comment by antonioortizpola** [comment]
Ok, i understand, should i close the issue or wait until the next release to double check?

**Comment by antonioortizpola** [comment]
Thanks, i understand and will wait for the next release, just, to confirm, this error causes the failed imports to be included? I am still in doubt about why the is `Microsoft.CodeDom` and `Microsoft.Xml` in one side and `System.CodeDom` and `System.Xml`, what is the difference between both and what are the right types to use in a Net core 2.1 project

**Comment by mlacouture** [comment]
@antonioortizpola, the generated code should not have the Microsoft.* namespaces; these are private to the tool and you should not have to worry about them.

**Comment by antonioortizpola** [comment]
Fair enough, thanks @mlacouture a lot for the time and the information! I will be stay tuned for the next releases (we connect a lot to old wsdl services, so...), Good Day!
