### ISSUE TITLE
Solve poor performance of WcfEventSource in CHK builds

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#313]
In CHK builds the tests run on TFS machines cause TestHost.exe to take 100% cpu for several minutes. See issue https://github.com/dotnet/coreclr/issues/1461 for a discussion and analysis.  Conclusion appears to be that DebugCheckEvent is doing excessive work due to the relatively large (62k) array it has constructed.

Renumbering the event ID's solves the issue but breaks existing tooling.

The purpose of this issue is to understand the root problem and find a solution.  This may involve a fix in this repo or as a PR to the CoreCLR repo.

**Comment by zhenlan** [comment]
@roncain has verified and this is not a problem after @dmetzgar's fix is merged.
