### ISSUE TITLE
How insert an Authorization header for insert a bear token in request?

### ISSUE THREAD

**Issue by ClaudioNunes** [dotnet/wcf#3133]
I have not found any way of inserting an Authorization heard in the proxy class created by WCF Service Reference Provider (Preview).

**Comment by Lxiamail** [comment]
[Here is a scenario](https://github.com/dotnet/wcf/blob/8589daec6cd3d7d4b1e90238cae951a91e937c03/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs#L57) test that demonstrates how to add an HTTP header before making a request. Please let us know if it helps.

**Comment by StephenBonikowsky** [comment]
@ClaudioNunes If you have any further questions let us know.
