### ISSUE TITLE
WCF Web Service Reference Provider doesn't report an error when project directory is read-only (doesn't work again!)

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#3137]
I thought you guys fixed this malware?  After a long vacation, I tried to add a service reference to an https location and stuck progress bar section.  No error messages displayed.  Why can't it give at least an error message?  Why is that dumb progress bar there if it doesn't update itself?

Do you guys need a project manager?  I wouldn't mind helping a former monopoly become more competitive in the world of Google and Apple.

**Comment by mlacouture** [comment]
Hi @Joebeazelman 

What version of Visual Studio 2017 are you using? If not on a recent version of Visual Studio, will you be able to try v15.8?

Also, we need more details to try to reproduce the problem and do proper investigation, are you able to share the web service URL or a wsdl file with us?

thanks,

**Comment by Joebeazelman** [comment]
I solved the issue.  The directory containing my project didn't have enough permissions.  Instead of telling me it didn't have enough permissions, it stalled.  As for the version of VS, I was running the latest or at least a version back.  This happened both with a beta and recent release.  Try removing VS from having write permissions and then try creating a service reference.

**Comment by mlacouture** [comment]
glad you solved the issue.  How did you figure out it was a permission issue?

**Comment by Joebeazelman** [comment]
It so happened I created a new repo on a shared volume in my solution using another machine.  The files had read only permission.  Some of the project files were copied over to the new repo from another project in the solution.  It is quite odd that SvcUtil doesn't reporr an error.

**Comment by HongGit** [comment]
Thank you for the feedback, but our team was unable to prioritize it at this time as they are working on problems with broader customer impact.

**Comment by Joebeazelman** [comment]
> Thank you for the feedback, but our team was unable to prioritize it at this time as they are working on problems with broader customer impact.

How do you know how broad or how narrow this issue is to your "customers?"  Most developers accept issues like this because they've come to expect mediocrity from Microsoft. There are thousands of bugs in Microsoft's products that haven't been fixed even after decades of releases. Do you think they would bother to file a bug report given Microsoft's track record?  Every software engineer worth their salt knows you should fix all fatal error conditions.
