### ISSUE TITLE
How to host a WCF service in an ASP.Net Core 2.1 MVC app?

### ISSUE THREAD

**Issue by wstaelens** [dotnet/wcf#3139]
We have ASP.NET MVC 5 application which hosts a WCF service in that MVC website.

How can this be done in asp.net core 2.1 mvc? I don't mean consuming it by adding a reference to a service, but really by hosting the wcf service in the asp.net core 2.1 mvc application.

**Comment by Lxiamail** [comment]
@wstaelens WCF service on .NET Core is not supported yet. The feature request is tracked by issue #2695.

**Comment by Lxiamail** [comment]
Close this issue and please reference to #2695 for future updates.
