### ISSUE TITLE
Increase code coverage for security related features.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#314]
Making this Issue a little more targeted in scope.
 Tasks to complete are...
 
- [x] List Namespace and Classes considered security related.
- [x] Get current coverage for these.
- [x] Break into manageable chunks (Issues) for triage.

The triage process should categorize as best as possible everything into one of three buckets...
   1. Unsupported product code that needs to be removed.
   2. Unsupported product code that we want to support relatively soon so keep it.
   3. Supported product code that needs test coverage.

**Comment by iamjasonp** [comment]
#301 tracks the disablement. Use this issue to track any additional issues that need additional code coverage

**Comment by StephenBonikowsky** [comment]
Making this Issue a little more targeted in scope.
Tasks to complete are...
1. List files to be considered security related.
2. Get current coverage for these files.
3. Decide what the coverage percentage target should be for this specific Issue.
4. Identify needed test scenarios to be added.
5. Fix product issues blocking existing test cases.

**Comment by StephenBonikowsky** [comment]
Summary Chart of Security Namespaces...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.IdentityModel**                |72      |	1702     | 1774     | 32747 |	4%
|**System.IdentityModel.Claims**         |166     |	666	     | 832	    | 1957	|  19.90%
|**System.IdentityModel.Policy**         |49      |	161	     | 210	    | 410	|  23%
|**System.IdentityModel.Selectors**      |166     |	284	     | 450	    | 994	|  37%
|**System.IdentityModel.Tokens**         |76      |	425	     | 501	    | 1120	|  15%
|**System.ServiceModel.Security**        |532     |	5259     | 5791	    | 28503 |	9%
|**System.ServiceModel.Security.Tokens** |135     |	635	     | 770	    | 1735	|  18%
|**totals**                              |1196    |	9132     | 10328    | 67466 |  12%

**Comment by StephenBonikowsky** [comment]
Class level details of System.IdentityModel namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.IdentityModel**											|72	|1702 |1774	|32747	|4%
|**System.IdentityModel.CanonicalFormWriter**						|0	|48	  |48	|84	    |0%
|**System.IdentityModel.CryptoHelper**							    |0	|24	  |24	|81	    |0%
|**System.IdentityModel.DictionaryManager**						    |0	|62	  |62	|150	|0%
|**System.IdentityModel.EmptyReadOnlyCollection**					|0	|1	  |1	|421	|0%
|**System.IdentityModel.ExclusiveC14NDictionary**					|0	|19	  |19	|1886	|0%
|**System.IdentityModel.HashStream**								|0	|52	  |52	|141	|0%
|**System.IdentityModel.IdentityModelDictionary**					|0	|68	  |68	|105	|0%
|**System.IdentityModel.IdentityModelString**						|0	|0	  |0	|0	
|**System.IdentityModel.IdentityModelStringsVersion1**			    |0	|285  |285	|585	|0%
|**System.IdentityModel.SamlDictionary**							|0	|125  |125	|1886	|0%
|**System.IdentityModel.SecureConversationDec2005Dictionary**		|0	|61	  |61   |1886	|0%
|**System.IdentityModel.SecureConversationDictionary**			    |0	|14	  |14   |1886	|0%
|**System.IdentityModel.SecureConversationFeb2005Dictionary**		|0	|59	  |59   |1886	|0%
|**System.IdentityModel.SecurityAlgorithmDec2005Dictionary**		|0	|13	  |13   |1886	|0%
|**System.IdentityModel.SecurityAlgorithmDictionary**				|0	|61	  |61   |1886	|0%
|**System.IdentityModel.SecurityJan2004Dictionary**				    |0	|71	  |71   |1886	|0%
|**System.IdentityModel.SecurityMessageSerializationException**	    |0	|9	  |9    |23	    |0%
|**System.IdentityModel.SecurityUniqueId**						    |19	|0	  |19   |46	    |100%
|**System.IdentityModel.SecurityUtils**							    |40	|197  |237	|421	|16.80%
|**System.IdentityModel.SecurityXXX2005Dictionary**				    |0	|35	  |35	|1886	|0%
|**System.IdentityModel.SignatureResourcePool**					    |0	|0	  |0	|0	
|**System.IdentityModel.SignedXml**								    |0	|7	  |7	|38	    |0%
|**System.IdentityModel.SimpleAuthorizationContext**				|13	|7	  |20	|421	|65%
|**System.IdentityModel.TrustDec2005Dictionary**					|0	|139  |139	|1886	|0%
|**System.IdentityModel.TrustDictionary**							|0	|14	  |14	|1886	|0%
|**System.IdentityModel.TrustFeb2005Dictionary**					|0	|113  |113	|1886	|0%
|**System.IdentityModel.UtilityDictionary**						    |0	|23	  |23	|1886	|0%
|**System.IdentityModel.XD**										|0	|66	  |66	|1886	|0%
|**System.IdentityModel.XmlBuffer**								    |0	|11	  |11	|55	    |0%
|**System.IdentityModel.XmlEncryptionDictionary**					|0	|51	  |51	|1886	|0%
|**System.IdentityModel.XmlSignatureDictionary**					|0	|67	  |67	|1886	|0%

**Comment by StephenBonikowsky** [comment]
Class level details of System.IdentityModel.Claims namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.IdentityModel.Claims**|166|666|832|1957|19.90%
|**System.IdentityModel.Claims.Claim**|30|57|87|203|34.40%
|**System.IdentityModel.Claims.ClaimComparer**|17|146|163|297|10.40%
|**System.IdentityModel.Claims.ClaimSet**|28|34|62|119|45.10%
|**System.IdentityModel.Claims.ClaimTypes**|10|21|31|77|32.20%
|**System.IdentityModel.Claims.DefaultClaimSet**|10|48|58|106|17.20%
|**System.IdentityModel.Claims.Rights**|2|0|2|16|100%
|**System.IdentityModel.Claims.WindowsClaimSet**|0|147|147|253|0%
|**System.IdentityModel.Claims.X509CertificateClaimSet**|62|160|222|443|27.90%
|**System.IdentityModel.Claims.X509Identity**|7|53|60|443|11.60%

**Comment by StephenBonikowsky** [comment]
Class level details of System.IdentityModel.Policy namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.IdentityModel.Policy**|49|161|210|410|23.30%
|**System.IdentityModel.Policy.AuthorizationContext**|3|0|3|23|100%
|**System.IdentityModel.Policy.DefaultAuthorizationContext**|0|19|19|60|0%
|**System.IdentityModel.Policy.DefaultEvaluationContext**|0|28|28|74|0%
|**System.IdentityModel.Policy.EvaluationContext**|0|0|0|0	
|**System.IdentityModel.Policy.UnconditionalPolicy**|46|114|160|253|28.70%

**Comment by StephenBonikowsky** [comment]
Class level details of System.IdentityModel.Selectors namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.IdentityModel.Selectors**|166|284|450|994|36.80%
|**System.IdentityModel.Selectors.KerberosSecurityTokenProvider**|0|29|29|72|0%
|**System.IdentityModel.Selectors.SecurityTokenAuthenticator**|16|25|41|74|39%
|**System.IdentityModel.Selectors.SecurityTokenManager**|0|0|0|0	
|**System.IdentityModel.Selectors.SecurityTokenProvider**|6|24|30|71|20%
|**System.IdentityModel.Selectors.SecurityTokenRequirement**|57|23|80|171|71.20%
|**System.IdentityModel.Selectors.SecurityTokenResolver**|0|7|7|29|0%
|**System.IdentityModel.Selectors.SecurityTokenSerializer**|0|110|110|245|0%
|**System.IdentityModel.Selectors.SecurityTokenVersion**|0|0|0|0	
|**System.IdentityModel.Selectors.UserNameSecurityTokenProvider**|8|2|10|30|80%
|**System.IdentityModel.Selectors.WindowsSecurityTokenAuthenticator**|0|15|15|43|0%
|**System.IdentityModel.Selectors.X509CertificateChain**|0|0|0|0	
|**System.IdentityModel.Selectors.X509CertificateValidator**|43|13|56|113|76.70%
|**System.IdentityModel.Selectors.X509SecurityTokenAuthenticator**|25|10|35|74|71.40%
|**System.IdentityModel.Selectors.X509SecurityTokenProvider**|11|26|37|72|29.70%

**Comment by StephenBonikowsky** [comment]
Class level details of System.IdentityModel.Tokens namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.IdentityModel.Tokens**|76|425|501|1120|15.10%
|**System.IdentityModel.Tokens.BinaryKeyIdentifierClause**|0|41|41|75|0%
|**System.IdentityModel.Tokens.EncryptedKeyIdentifierClause**|0|38|38|84|0%
|**System.IdentityModel.Tokens.InMemorySymmetricSecurityKey**|0|60|60|116|0%
|**System.IdentityModel.Tokens.KerberosRequestorSecurityToken**|0|24|24|71|0%
|**System.IdentityModel.Tokens.LocalIdKeyIdentifierClause**|0|46|46|87|0%
|**System.IdentityModel.Tokens.SamlSerializer**|0|3|3|14|0%
|**System.IdentityModel.Tokens.SecurityKey**|0|0|0|0	
|**System.IdentityModel.Tokens.SecurityKeyIdentifier**|0|86|86|149|0%
|**System.IdentityModel.Tokens.SecurityKeyIdentifierClause**|0|23|23|69|0%
|**System.IdentityModel.Tokens.SecurityKeyTypeHelper**|8|3|11|34|72.70%
|**System.IdentityModel.Tokens.SecurityKeyUsageHelper**|7|3|10|32|70%
|**System.IdentityModel.Tokens.SecurityToken**|0|0|0|0	
|**System.IdentityModel.Tokens.SecurityTokenException**|3|6|9|23|33.30%
|**System.IdentityModel.Tokens.SecurityTokenTypes**|3|2|5|27|60%
|**System.IdentityModel.Tokens.SecurityTokenValidationException**|3|6|9|23|33.30%
|**System.IdentityModel.Tokens.SymmetricSecurityKey**|0|0|0|0	
|**System.IdentityModel.Tokens.UserNameSecurityToken**|16|5|21|67|76.10%
|**System.IdentityModel.Tokens.WindowsSecurityToken**|0|54|54|118|0%
|**System.IdentityModel.Tokens.X509SecurityToken**|36|25|61|131|59%

**Comment by StephenBonikowsky** [comment]
Class level details of System.IdentityModel.Security namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.ServiceModel.Security**|532|5259|5791|28503|9.10%
|**System.ServiceModel.Security.Basic128Rsa15SecurityAlgorithmSuite**|0|5|5|642|0%
|**System.ServiceModel.Security.Basic128SecurityAlgorithmSuite**|0|23|23|642|0%
|**System.ServiceModel.Security.Basic128Sha256Rsa15SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.Basic128Sha256SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.Basic192Rsa15SecurityAlgorithmSuite**|0|5|5|642|0%
|**System.ServiceModel.Security.Basic192SecurityAlgorithmSuite**|0|23|23|642|0%
|**System.ServiceModel.Security.Basic192Sha256Rsa15SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.Basic192Sha256SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.Basic256Rsa15SecurityAlgorithmSuite**|0|5|5|642|0%
|**System.ServiceModel.Security.Basic256SecurityAlgorithmSuite**|0|23|23|642|0%
|**System.ServiceModel.Security.Basic256Sha256Rsa15SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.Basic256Sha256SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.BasicSecurityProfileVersion**|0|7|7|27|0%
|**System.ServiceModel.Security.BinaryNegotiation**|0|53|53|87|0%
|**System.ServiceModel.Security.ChannelProtectionRequirements**|0|260|260|373|0%
|**System.ServiceModel.Security.CommunicationObjectSecurityTokenAuthenticator**|0|83|83|500|0%
|**System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider**|0|90|90|500|0%
|**System.ServiceModel.Security.EmptyReadOnlyCollection`1**|1|0|1|1048|100%
|**System.ServiceModel.Security.HttpDigestClientCredential**|22|2|24|51|91.60%
|**System.ServiceModel.Security.IdentityVerifier**|102|60|162|283|62.90%
|**System.ServiceModel.Security.InMemoryNonceCache**|0|87|87|160|0%
|**System.ServiceModel.Security.MessagePartSpecification**|42|102|144|229|29.10%
|**System.ServiceModel.Security.MessageProtectionOrderHelper**|0|5|5|22|0%
|**System.ServiceModel.Security.MessageSecurityException**|4|18|22|53|18.10%
|**System.ServiceModel.Security.MessageSecurityTokenVersion**|0|118|118|202|0%
|**System.ServiceModel.Security.NonceCache**|0|24|24|63|0%
|**System.ServiceModel.Security.OperationWithTimeoutAsyncResult**|0|28|28|1048|0%
|**System.ServiceModel.Security.ProtectionLevelHelper**|8|25|33|1048|24.20%
|**System.ServiceModel.Security.ReceiveSecurityHeader**|0|7|7|37|0%
|**System.ServiceModel.Security.RequestSecurityToken**|0|319|319|559|0%
|**System.ServiceModel.Security.RequestSecurityTokenResponse**|0|310|310|567|0%
|**System.ServiceModel.Security.RequestSecurityTokenResponseCollection**|0|28|28|58|0%
|**System.ServiceModel.Security.ScopedMessagePartSpecification**|0|136|136|205|0%
|**System.ServiceModel.Security.SecureConversationDriver**|0|11|11|73|0%
|**System.ServiceModel.Security.SecureConversationVersion**|0|28|28|86|0%
|**System.ServiceModel.Security.SecurityAccessDeniedException**|0|6|6|18|0%
|**System.ServiceModel.Security.SecurityAlgorithmSuite**|0|188|188|642|0%
|**System.ServiceModel.Security.SecurityAuditHelper**|0|3|3|16|0%
|**System.ServiceModel.Security.SecurityChannel`1**|0|60|60|115|0%
|**System.ServiceModel.Security.SecurityContextKeyIdentifierClause**|0|27|27|66|0%
|**System.ServiceModel.Security.SecurityCredentialsManager**|1|0|1|14|100%
|**System.ServiceModel.Security.SecurityHeader**|0|70|70|163|0%
|**System.ServiceModel.Security.SecurityKeyEntropyModeHelper**|0|11|11|33|0%
|**System.ServiceModel.Security.SecurityMessageProperty**|21|172|193|318|10.80%
|**System.ServiceModel.Security.SecurityNegotiationException**|3|6|9|23|33.30%
|**System.ServiceModel.Security.SecurityPolicyVersion**|0|27|27|79|0%
|**System.ServiceModel.Security.SecurityProtocol**|0|23|23|68|0%
|**System.ServiceModel.Security.SecurityProtocolFactory**|3|686|689|1141|0.40%
|**System.ServiceModel.Security.SecurityStandardsManager**|0|17|17|68|0%
|**System.ServiceModel.Security.SecurityStateEncoder**|0|1|1|18|0%
|**System.ServiceModel.Security.SecurityTimestamp**|0|100|100|193|0%
|**System.ServiceModel.Security.SecurityTokenAttachmentModeHelper**|0|33|33|67|0%
|**System.ServiceModel.Security.SecurityTokenSpecification**|6|4|10|35|60%
|**System.ServiceModel.Security.SecurityUniqueId**|0|18|18|1048|0%
|**System.ServiceModel.Security.SecurityUtils**|105|394|499|1048|21%
|**System.ServiceModel.Security.SecurityVersion**|17|98|115|286|14.70%
|**System.ServiceModel.Security.SendSecurityHeader**|0|9|9|46|0%
|**System.ServiceModel.Security.SignatureConfirmationElement**|0|20|20|52|0%
|**System.ServiceModel.Security.SignatureTargetIdManager**|0|3|3|22|0%
|**System.ServiceModel.Security.SslProtocolsHelper**|11|3|14|1048|78.50%
|**System.ServiceModel.Security.SspiSecurityTokenProvider**|7|4|11|38|63.60%
|**System.ServiceModel.Security.SupportingTokenAuthenticatorSpecification**|0|24|24|68|0%
|**System.ServiceModel.Security.SupportingTokenProviderSpecification**|0|16|16|47|0%
|**System.ServiceModel.Security.SupportingTokenSpecification**|0|10|10|39|0%
|**System.ServiceModel.Security.TimeBoundedCache**|0|334|334|513|0%
|**System.ServiceModel.Security.TokenImpersonationLevelHelper**|5|74|79|1048|6.30%
|**System.ServiceModel.Security.TripleDesRsa15SecurityAlgorithmSuite**|0|5|5|642|0%
|**System.ServiceModel.Security.TripleDesSecurityAlgorithmSuite**|0|23|23|642|0%
|**System.ServiceModel.Security.TripleDesSha256Rsa15SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.TripleDesSha256SecurityAlgorithmSuite**|0|7|7|642|0%
|**System.ServiceModel.Security.TrustDriver**|0|14|14|141|0%
|**System.ServiceModel.Security.TrustVersion**|0|28|28|86|0%
|**System.ServiceModel.Security.UserNamePasswordClientCredential**|29|2|31|63|93.50%
|**System.ServiceModel.Security.WSSecurityOneDotOneReceiveSecurityHeader**|0|3|3|24|0%
|**System.ServiceModel.Security.WSSecurityOneDotOneSendSecurityHeader**|0|3|3|31|0%
|**System.ServiceModel.Security.WSSecurityOneDotZeroReceiveSecurityHeader**|0|3|3|20|0%
|**System.ServiceModel.Security.WSSecurityOneDotZeroSendSecurityHeader**|0|3|3|19|0%
|**System.ServiceModel.Security.WSSecurityPolicy**|0|3|3|122|0%
|**System.ServiceModel.Security.WSSecurityTokenSerializer**|0|247|247|441|0%
|**System.ServiceModel.Security.WSUtilitySpecificationVersion**|0|66|66|164|0%
|**System.ServiceModel.Security.WindowsClientCredential**|16|32|48|92|33.30%
|**System.ServiceModel.Security.WrapperSecurityCommunicationObject**|0|76|76|500|0%
|**System.ServiceModel.Security.X509CertificateInitiatorClientCredential**|22|14|36|73|61.10%
|**System.ServiceModel.Security.X509CertificateRecipientClientCredential**|41|42|83|148|49.30%
|**System.ServiceModel.Security.X509CertificateValidationModeHelper**|10|3|13|59|76.90%
|**System.ServiceModel.Security.X509ClientCertificateAuthentication**|0|10|10|32|0%
|**System.ServiceModel.Security.X509ServiceCertificateAuthentication**|56|39|95|160|58.90%
|**System.ServiceModel.Security.XmlHelper**|0|261|261|397|0%

**Comment by StephenBonikowsky** [comment]
Class level details of System.ServiceModel.Security.Tokens namespace...

|Namespace	                             |Covered |Uncovered |Coverable	|Total	|Line Coverage|
|----------------------------------------|--------|----------|----------|-------|-------------|
|**System.ServiceModel.Security.Tokens**|135|635|770|1735|17.50%
|**System.ServiceModel.Security.Tokens.ClaimTypeRequirement**|0|16|16|42|0%
|**System.ServiceModel.Security.Tokens.DerivedKeySecurityToken**|0|51|51|154|0%
|**System.ServiceModel.Security.Tokens.InitiatorServiceModelSecurityTokenRequirement**|19|18|37|83|51.30%
|**System.ServiceModel.Security.Tokens.NonValidatingSecurityTokenAuthenticator**|0|8|8|27|0%
|**System.ServiceModel.Security.Tokens.RecipientServiceModelSecurityTokenRequirement**|0|13|13|31|0%
|**System.ServiceModel.Security.Tokens.SecureConversationSecurityTokenParameters**|0|63|63|128|0%
|**System.ServiceModel.Security.Tokens.SecurityContextCookieSerializer**|0|9|9|44|0%
|**System.ServiceModel.Security.Tokens.SecurityContextSecurityToken**|0|162|162|327|0%
|**System.ServiceModel.Security.Tokens.SecurityTokenContainer**|0|8|8|26|0%
|**System.ServiceModel.Security.Tokens.SecurityTokenInclusionModeHelper**|0|12|12|35|0%
|**System.ServiceModel.Security.Tokens.SecurityTokenParameters**|17|11|28|68|60.70%
|**System.ServiceModel.Security.Tokens.SecurityTokenProviderContainer**|12|5|17|45|70.50%
|**System.ServiceModel.Security.Tokens.ServiceModelSecurityTokenRequirement**|23|92|115|239|20%
|**System.ServiceModel.Security.Tokens.ServiceModelSecurityTokenTypes**|1|5|6|23|16.60%
|**System.ServiceModel.Security.Tokens.SspiSecurityToken**|21|21|42|108|50%
|**System.ServiceModel.Security.Tokens.SupportingTokenParameters**|31|77|108|173|28.70%
|**System.ServiceModel.Security.Tokens.TokenReferenceStyleHelper**|0|9|9|31|0%
|**System.ServiceModel.Security.Tokens.UserNameSecurityTokenParameters**|11|4|15|30|73.30%
|**System.ServiceModel.Security.Tokens.WindowsSidIdentity**|0|38|38|84|0%
|**System.ServiceModel.Security.Tokens.X509SecurityTokenReferenceStyleHelper**|0|13|13|37|0%

**Comment by StephenBonikowsky** [comment]
New Issues created as part of completing step three.
System.IdentityModel #638
System.IdentityModel.Claims #639
System.IdentityModel.Policy #640
System.IdentityModel.Selectors #641
System.IdentityModel.Tokens #642
System.ServiceModel.Security #643
System.ServiceModel.Security.Tokens #644
