### ISSUE TITLE
Impossible to generate web service client with Microsoft WCF Web Service Reference Provider

### ISSUE THREAD

**Issue by gicat** [dotnet/wcf#3143]
I have the following error using Microsoft WCF Web Service Reference Provider:

> Importing web service metadata ...
> Number of service endpoints found: 2
> Scaffolding service reference code ...
> Error:Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
> Done.

This are my Visual Studio infos:

> Microsoft Visual Studio Enterprise 2017 
> Version 15.8.2
> VisualStudio.15.Release/15.8.2+28010.2016
> Microsoft .NET Framework
> Version 4.7.02556
> 
> Installed Version: Enterprise
> 
> Application Insights Tools for Visual Studio Package   8.13.10627.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017   15.8.05077.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Core Razor Language Services   15.8.31590
> Provides languages services for ASP.NET Core Razor.
> 
> ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   15.8.05023.0
> Azure App Service Tools v3.0.0
> 
> Azure Functions and Web Jobs Tools   15.8.05023.0
> Azure Functions and Web Jobs Tools
> 
> C# Tools   2.9.0-beta8-63208-01
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Fabric.DiagnosticEvents   1.0
> Fabric Diagnostic Events
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> Microsoft Azure Service Fabric Tools for Visual Studio   2.3
> Microsoft Azure Service Fabric Tools for Visual Studio
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2
> 
> Microsoft Continuous Delivery Tools for Visual Studio   0.4
> Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft Library Manager   1.0
> Install client-side libraries easily to any web project
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual Studio Tools for Containers   1.1
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> Node.js Tools   1.4.20802.1 Commit Hash:97e1085d8b4b8e3e51c398e910177f87e86d135e
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   4.6.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension   1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension   1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> Snapshot Debugging Extension   1.0
> Snapshot Debugging Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools   15.1.61808.07020
> Microsoft SQL Server Data Tools
> 
> TypeScript Tools   15.8.20801.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   2.9.0-beta8-63208-01
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: c55dd2c3d618eb93a8d16e503947342b1fa93556.
> Microsoft Visual F# Tools 10.2 for F# 4.5
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Tools for Containers   1.0
> Visual Studio Tools for Containers

**Comment by mlacouture** [comment]
Hi @gicat 
The error you are seeing comes from a NuGet package restore operation, the tool generates a project (the bootstrapper) and something is preventing the restoring of packages for this project.

Some suggestions:
- Do you have any custom nuget.config file under your project's directory? if so, can you copy it under the %temp% directory and try to add the web service reference again?
- Can you try it on a different machine?

**Comment by gicat** [comment]
Hi @mlacouture 
I have no custom nuget.config, and currently no different machine to try it. Any other suggestion?
Thanks.

**Comment by gicat** [comment]
Hi @mlacouture
I have solved it installing dotnet-svcutil

Install-Package dotnet-svcutil -Version 1.0.3

In fact launching the command

dotnet svcutil --additionalprobingpath "C:\Users\XXXXX.nuget\packages" "C:\Users\XXXXX\AppData\Local\Temp\WCFConnectedService\2018_Aug_31_08_58_24\SvcUtilParams.txt"

on command line, the result was the following error:

No executable found matching command "dotnet-svcutil"

Thanks.

**Comment by mlacouture** [comment]
Hi @gicat 
I'm glad you are unblocked.  However, this tool is not designed to be installed as a project reference, this is the reason you are seeing the error message. You need to edit the project reference as below so it becomes a tool reference; additionally, the project needs to be restored.  For more info refer to the [tool guide](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide).

`<DotNetCliToolReference Include="dotnet-svcutil" Version="1.0.*" />`

hope this helps,

**Comment by kbvishnu** [comment]
Confused on the solution, Struggling to identify a fix for this. 
Visual Studio 2017
ASP.NET Core 2.2
WCF Service with Transport with Protocal. 
Appreciated if you provide any leads to the solution The work around mentioned above were tried, Nothing worked so far.
