### ISSUE TITLE
StackOverFlowException to generate web service client with Microsoft WCF Web Service Reference Provider (chameleon schemas with cyclic includes)

### ISSUE THREAD

**Issue by Sebacad** [dotnet/wcf#3149]
I have the following error using last Microsoft WCF Web Service Reference Provider:

> dotnet svcutil GestionDossierPatientPartage.wsdl
> Outil de génération de proxy du modèle de service Microsoft (R) WCF pour plateforme .Net Core
> [dotnet-svcutil, version 1.0.3]
> Copyright (c) Microsoft Corporation. Tous droits réservés.
> Tentative de chargement des métadonnées à partir de 'GestionDossierPatientPartage.wsdl'.
> 
> Process is terminating due to StackOverflowException.

thank for helping me!

**Comment by cadsebastien** [comment]
[wcf.zip](https://github.com/dotnet/wcf/files/2344683/wcf.zip)
Here the WSDL with the error

**Comment by mlacouture** [comment]
Hi @Sebacad 

Thank you for reporting this issue and for providing the wsdl files for investigation.  

You are hitting this problem because the schema documents have cyclic includes (datatypes-base.xsd -> voc.xsd -> datatypes.xsd -> datatypes-base.xsd).

However, I think the WCF Web Service Reference provider should be able to handle this situation.  We'll consider a fix for a future release.

**Comment by Sebacad** [comment]
Thanks @mlacouture  

Do you know the delay of the future release with the fix?
For now, I try to generate reference by hand using the reference generated with the .Net framework and applying the differences of the .Net Core Framework

Good alternative for you?

Thanks,

**Comment by mlacouture** [comment]
Hi @Sebacad 
We plan to make a fix for this issue available with the next release of the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) tool in a few weeks.  As per the WCF Web Service Reference tool the fix will be available in Visual Studio 2017 v16.0.

The workaround you are using looks good to me.  As an alternative, you could fix up the WSDL by removing the cyclic references.

**Comment by Sebacad** [comment]
Hi @mlacouture 

I have removed the cyclic references. Its Perfect!
Just for information. The WSDL is an export, so the endpoint URI is empty

`<port binding="tns:GDP_Binding_Soap12" name="GDP_Binding_Soap12">
				<wsoap12:address location=""/>
			</port>`

I get the following error
> Erreur : URI non valide : L'URI est vide.
XPath vers la source de l'erreur : //wsdl:definitions[@targetNamespace='asip:ci-sis:gdp:2010']/wsdl:service[@name='GDP_Service']/wsdl:port[@name='GDP_Binding_Soap12'] 

Maybe no generate error if URI empty

**Comment by Sebacad** [comment]
So I solved my problem.
Thanks for your help!

**Comment by mlacouture** [comment]
Thank you @Sebacad  for the update.  I will be providing a fix for this issue in a future release.

**Comment by dasetser** [comment]
The fix for this is included in dotnet-svcutil v1.0.4, which is now released. The fix will be included in the WCF Web Service Reference Provider as part of Visual Studio 2019.
