### ISSUE TITLE
Incorrect logic in GetCustomAttributes breaks IOperationBehavior

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#315]
System\ServiceModel\Description\ServiceReflector.GetCustomAttributes expects that all CustomAttributes it gets derive from Attribute. This is incorrect as CustomAttributes can also derive from interfaces such as IOperationBehavior.

The logic needs to be changed to get all CustomAttributes on the Operation and add to the collection any that match the Type being looked for.

**Comment by roncain** [comment]
After fixing ServiceReflector.GetCustomAttributes (to get all custom attributes and then subset the list to which ones are assignable to the requested type), scan the code for calls to this method that pass in an interface, like this:
```
ServiceReflector.GetCustomAttributes(interfaceType, typeof(IContractBehavior), false);
```
For every one of these we find, write the corresponding unit or scenario test to ensure we cover that case.  The fact GetCustomAttributes() was silently returning an empty array when given interface types means we have a test gap for a custom attribute that implements that interface type.

**Comment by StephenBonikowsky** [comment]
Ok

**Comment by StephenBonikowsky** [comment]
Looks like we pass in two other interfaces, IContractBehavior and IEndpointBehavior.
I'll make sure we have coverage for them.
