### ISSUE TITLE
Issue converting Legacy WCF Code to NetCore Version?

### ISSUE THREAD

**Issue by iby-dev** [dotnet/wcf#3150]
Hi, I have the below sandbox version working:

![image](https://user-images.githubusercontent.com/12273467/44982478-f4504f00-af6d-11e8-9024-d9d1732a74b7.png)

For **_two_** weeks now, I have been trying to convert it to netcore code and so far nothing works for me.  I keep running into the same issue again and again; 
>_System.AggregateException: One or more errors occurred. (An error occurred when verifying security >for the message.) ---> System.ServiceModel.FaultException: An error occurred when verifying security >for the message._

~~In the older .netframework version, the auth info is not passed as a soap header (_I added a message inspector to compare the outgoing request_) and is passed as basic auth headers on the request itself. Forgive if have misunderstood how auth works on SOAP Requests.~~

Slight Update here: with Fiddler we can see how WCF generates the Request and how the auth is handled.

![image](https://user-images.githubusercontent.com/12273467/44986899-2321f180-af7d-11e8-8f6e-b6405426ec1d.png)

With netcore, I am aware there is a platform not supported exception that is thrown for 'TransportWithMessageCredential'. 

1. In light of this how do i pass the username and password then?
2. Do i have to add in the soap header myself manually;

``` XML
      <q1:UsernameToken p3:Id="_UT97686b71de71489f9ed0f064ffe394e5" xmlns:p3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <q1:Username> user </q1:Username>
        <q1:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText"> pass </q1:Password>
      </q1:UsernameToken> 
```

Now, I can make calls to the target service, when there is no auth involved. Anyways over to you guys, hopefully someone on here can help.

**Comment by iby-dev** [comment]
My First crack at - aptly named.

``` CSHARP
        public void PilferedFromWeb()
        {
            const string basicUsernameHeaderName = "BasicUsername";
            const string basicPasswordHeaderName = "BasicPassword";

            const string username = "someusername";
            const string password = "somepassword";

            ChannelFactory<IGlobalAuthenticate> factory = null;
            IGlobalAuthenticate serviceProxy = null;

            try
            {
                var binding = new BasicHttpsBinding(BasicHttpsSecurityMode.Transport);
                binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Digest;
                
                var uri = new Uri("https://pilot.id3global.com/ID3gWS/ID3global.svc/Soap11_Auth");
                var address = new EndpointAddress(uri); // test endpoint
                factory = new ChannelFactory<IGlobalAuthenticate>(binding, address);

                factory.Credentials.UserName.UserName = username;
                factory.Credentials.UserName.Password = password;

                serviceProxy = factory.CreateChannel();

                using (var scope = new OperationContextScope((IContextChannel) serviceProxy))
                {
                    HttpRequestMessageProperty requestMessageProperty;
                    if (!OperationContext.Current.OutgoingMessageProperties.ContainsKey(HttpRequestMessageProperty.Name)
                    )
                    {
                        requestMessageProperty = new HttpRequestMessageProperty();
                        OperationContext.Current.OutgoingMessageProperties[HttpRequestMessageProperty.Name] =
                            requestMessageProperty;
                    }
                    else
                    {
                        requestMessageProperty =
                            (HttpRequestMessageProperty) OperationContext.Current.OutgoingMessageProperties[
                                HttpRequestMessageProperty.Name];
                    }

                    requestMessageProperty.Headers[basicUsernameHeaderName] = username; //username
                    requestMessageProperty.Headers[basicPasswordHeaderName] = password; //password

                    // TestData
                    var request = BuildRequest();

                    var result = serviceProxy.AuthenticateSPAsync(request).Result;
                    result.Should().NotBeNull();
                }

                factory.Close();
                ((ICommunicationObject) serviceProxy).Close();
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            finally
            {
                CloseCommunicationObjects((ICommunicationObject)serviceProxy, factory);
            }
        }
```

**Comment by iby-dev** [comment]
I just want to know if the above is possible in netcore and if so how?

**Comment by Lxiamail** [comment]
@iby-dev BasicHttpsSecurityMode.TransportWithMessagecredential is not supported yet in WCF Core. This feature request is tracked by #8. Close this issue and please track the future update with #8 .

**Comment by OpenSpacesAndPlaces** [comment]
@iby-dev 
See workaround in:
https://github.com/dotnet/wcf/issues/8

**Comment by iby-dev** [comment]
@OpenSpacesAndPlaces - i saw that and realised that's a lot of work - do you have a working sandbox to share on github. Just so that I can get my head round how it all works together. Also no guarantee that netcore port of wcf class libs will successfully deserializer the response object. I went through this already with the 'Simple Soap Client'. You can make and recieve a valid xml request and response from a Soap Wcf Service. But then it was impossible to deserialise it. So i gave up.

I have lost over 3 weeks to this issue so I cannot really afford to spend much more time on this issue anymore. I have decided to go back to .net 47 for now and perhaps come back to it a year later.

**Comment by OpenSpacesAndPlaces** [comment]
@iby-dev 

The approach used isn't anything from scratch - the basis is a  WCF "Connected Service". e.g.:
https://aspdotnetcodehelp.wordpress.com/2017/03/27/how-to-access-wcf-service-in-asp-net-core-application/

In the sample shown (https://github.com/dotnet/wcf/issues/8), the code is using the scaffold-ed class from the WCF util normally. The only change is the additiona of the four extension classes and the way the credentials are added.
```
AuthenticationHeader : MessageHeader
AuthenticationHeaderBehavior : IEndpointBehavior
AuthenticationHeaderExtensions
AuthenticationHeaderInspector : IClientMessageInspector
```

```
client = new MyClient(new BasicHttpBinding(BasicHttpSecurityMode.TransportWithMessageCredential), new EndpointAddress(BaseUrl));
client.ClientCredentials.UserName.UserName = UserName;
client.ClientCredentials.UserName.Password = Password;
```

to 

```
client = new MyClient(new BasicHttpBinding(BasicHttpSecurityMode.Transport), new EndpointAddress(BaseUrl));
client.Endpoint.SetMessageCredentials(UserName,Password);
```

We're using that approach in Production for two different SOAP services that are use relying on "UsernameToken" SOAP headers for security.

From the looks of your original post, the only modification you'd have to make to the posted samples is in massaging the XML output the namespace/attributes you have:

e.g. you needed:
```
<q1:UsernameToken p3:Id="_UT97686b71de71489f9ed0f064ffe394e5" xmlns:p3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <q1:Username> user </q1:Username>
        <q1:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText"> pass </q1:Password>
      </q1:UsernameToken> 

```

and the samples makes:

```
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <wsse:UsernameToken>
        <wsse:Username>user</wsse:Username>
        <wsse:Password>password</wsse:Password>
      </wsse:UsernameToken>
    </wsse:Security>
```

Which, if that's all you need different - the only modification would be in this section:
```
public override string Name => "Security";

		public override string Namespace => "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd";

		protected override void OnWriteStartHeader(System.Xml.XmlDictionaryWriter writer, System.ServiceModel.Channels.MessageVersion messageVersion)
		{
			writer.WriteStartElement("wsse", Name, Namespace);
			writer.WriteXmlnsAttribute("wsse", Namespace);
		}

		protected override void OnWriteHeaderContents(XmlDictionaryWriter writer, MessageVersion messageVersion)
		{
			//TODO Timestamp - If Needed

			writer.WriteStartElement("wsse", "UsernameToken", Namespace);

			writer.WriteStartElement("wsse", "Username", Namespace);
			writer.WriteValue(_UserName);
			writer.WriteEndElement();

			writer.WriteStartElement("wsse", "Password", Namespace);
			writer.WriteValue(_Password);
			writer.WriteEndElement();

			writer.WriteEndElement();
		}
```

**Comment by ermac0** [comment]
Hi @iby-dev

Did you get anywhere with it? I'm having the same problem with the same service. Spent half a day trying different things but to no avail.

**Comment by OpenSpacesAndPlaces** [comment]
@ermac0 

There's more active discussion here:
https://github.com/dotnet/wcf/issues/8

The short: If you want to use  scaffolded code, you'll need to-do some workarounds - WCF isn't fully implemented yet in .Net Core (has been stated by project contributors). Assuming the requirements aren't too complex, you should be able to get something going without too much headache.

---

A few alternatives:
- generate the SOAP with the scaffolded code, but then send it with a plain HttpClient.
- generate the SOAP with XMLSerializer, then send it with a plain HttpClient.
- if you only have a few requests - generates SOAP templates and then replace placeholder values, send it with a plain HttpClient.
- Third party libraries
- Load .Net Framework side by side.
---

**Comment by lmcarreiro** [comment]
I used a similar workaround as described here: https://github.com/dotnet/wcf/issues/8#issuecomment-464888793
