### ISSUE TITLE
SignatureConfirmationsOccursAfterPrimarySignature exception

### ISSUE THREAD

**Issue by g-lorieto** [dotnet/wcf#3151]
I managed to consume a java based web service (third party) with WS-Security 1.1 protocol. The web service needs only to be signed over a x509 certificate, not encrypted. But I'm getting this error:

> The signature confirmation elements cannot occur after the primary signature.

Reading packages I can see the server responding OK,

The exception is thrown by the ReceiveSecurityHeader class - see the source code of it here: https://referencesource.microsoft.com/#system.servicemodel/system/servicemodel/Security/ReceiveSecurityHeader.cs

Search for SignatureConfirmationsOccursAfterPrimarySignature and see line 1464:

```
    if (this.orderTracker.PrimarySignatureDone)
    {
        throw TraceUtility.ThrowHelperError(new MessageSecurityException(SR.GetString(SR.SignatureConfirmationsOccursAfterPrimarySignature)), this.Message);
    }
```
I can't find any references to any kind of standard supporting this either...

**Comment by Lxiamail** [comment]
@g-lorieto Is this WCF Core client app or WCF full framework client app? Since you reference to https://referencesource.microsoft.com/#system.servicemodel/system/servicemodel/Security/ReceiveSecurityHeader.cs, which is .NET full framework reference source, which makes me wonder you may work on WCF full framework client app.

**Comment by g-lorieto** [comment]
@Lxiamail It's full framework client app. I found the wrong place to post my problem. Corrrect me if I'm wrong, but WS-Security still reamins unsupported by .NET Core, am I right?

Any known workarround? Or where I can post my issue? Any .NET full framework alternative site?

**Comment by Lxiamail** [comment]
@g-lorieto You are right. WS-Security is still not supported by .NET Core. For .NET full framework issue, please report at https://developercommunity.visualstudio.com.

**Comment by g-lorieto** [comment]
@Lxiamail https://github.com/Microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/Security/ReceiveSecurityHeader.cs
line 1464. Why is that exception thrown?
