### ISSUE TITLE
Nuget packages contain libraries targeting the wrong framework

### ISSUE THREAD

**Issue by kjbartel** [dotnet/wcf#3152]
The 4.5.3 versions of `System.ServiceModel.Http` and `System.ServiceModel.Primitives` contains libraries taergetting .Net Framework v4.7.1 instead of .Net Standard 2.0. This causes the libraries to not load if using .Net Core / ASP.Net Core runtime.

> Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

**Comment by Lxiamail** [comment]
@kjbartel  I can't repro the problem. Which directory are the System.ServiceModel.Http and System.ServiceModel.Primitives files that you ran into problem? Can you share the repro project?

**Comment by StephenBonikowsky** [comment]
@kjbartel If you still have any questions please let us know.
