### ISSUE TITLE
dotnet-svcutil support for old csproj projects

### ISSUE THREAD

**Issue by roysanchez** [dotnet/wcf#3154]
Is there any plan of allowing the new tool to run on old projects? The idea is to use this new client instead of the old generated one as a step in migrating to .net core.

**Comment by mlacouture** [comment]
Hi @roysanchez 
I guess when you say 'old csproj' you mean support for .NET Framework projects, if so the answer is no, we don't have any plans for that. However, you can have a .netcore project that targets a .NET Framework platform like net46, it seems this is what you need?

hope this helps,
