### ISSUE TITLE
Add an option to choose the output file

### ISSUE THREAD

**Issue by ErosGuil** [dotnet/wcf#3160]
`dotnet-svcutil` writes its files to `ServiceReference1/Reference.cs`, but I want to add them in `ServiceReference/Ver10/Device.cs`.

Is there an option to specify the output file? If not, can you add it?

**Comment by mlacouture** [comment]
Hi @ErosGuil 
Thanks for reporting this issue.  We will consider exposing such option in a future release.

**Comment by dasetser** [comment]
dotnet-svcutil 2.0 added the --outputFile option to specify this.
