### ISSUE TITLE
How to configure a customized behavior in  ConnectedService.json

### ISSUE THREAD

**Issue by shaka0919** [dotnet/wcf#3161]
Hi all
I have some projects contain some WCF dependencies. when I add these services to my aspnetcore project.
I cannot find any spec about how to configure the connectedservice.json to add some behavior.
For example, I wanna migrate my customized header behavior to the .net core project. How and where should I configure it?

**Comment by mlacouture** [comment]
Hi @shaka0919 
It seems you used the [wcf web service reference](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide) to add a web service ref to your project and got the connectedservice.json file as well, is this correct?

The connectedservice.json file is generated by the tool to support the service update functionality, it is not meant for configuring the web service client.

The generated code contains a partial method that is meant to be used for this purpose, the method signature looks like the following:
`    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
`
hope this help,
