### ISSUE TITLE
Blocking error when trying to create instance of EventHubClient in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/wcf#3172]
@allenh100 commented on [Sat Sep 15 2018](https://github.com/dotnet/core/issues/1943)

I am building a ASP.NET Core 2.1 MVC application and when I attempt to create an instance of the EventHubClient as follows:

```
EventHubClient client = EventHubClient.CreateFromConnectionString("connString", "hubName");
```

I receive the following exception:
```
$exception.Message = "The type initializer for 'Microsoft.ServiceBus.Messaging.Constants' threw an exception."

$exception.InnerException.Message = "Could not load type 'System.UriTemplate' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."
```

I have added references to the following packages as advised by numerous online posts but still continue to receive the above exception:
```
System.ServiceModel.Duplex
System.ServiceModel.Http
System.ServiceModel.NetTcp
System.ServiceModel.Primitives
System.ServiceModel.Security
```

Any advice/guidance on how to address this issue?

Thanks,
allen

---

@Petermarcu commented on [Sat Sep 15 2018](https://github.com/dotnet/core/issues/1943#issuecomment-421618826)

Are you targeting .NET Framework or .NET Core?

**Comment by allenh100** [comment]
I am targeting ASP.NET Core 2.1

**Comment by allenh100** [comment]
I think i found my answer on the [WindowsAzure.ServiceBus NuGet page](https://www.nuget.org/packages/WindowsAzure.ServiceBus/)

*Please note that this package requires .Net Framework 4.6.*

We can go ahead and close this issue.

Thanks,
allen

**Comment by allenh100** [comment]
Ultimate solution for ASP.NET Core 2.1 [Azure Event Hubs in .NET Standard](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send)

**Comment by Petermarcu** [comment]
Glad you found the solution.
