### ISSUE TITLE
Configure message logging

### ISSUE THREAD

**Issue by galloglach** [dotnet/wcf#3173]
Hi,
could someone point me at the documentation for configuring message logging with .net core.
Thanks in advance.

**Comment by galloglach** [comment]
@Lxiamail, I'm looking for the equivalent of the "_Tracing and Message Logging_" that is done for the _.Net Framework_, as documented at [https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/tracing-and-message-logging](url)

**Comment by Lxiamail** [comment]
@galloglach Message logging is not supported on WCF Core.

**Comment by mrflo** [comment]
@Lxiamail What would you recommend to log all the XML messages send and received from a dotnet core web app ? Do you know an example somewhere? Thanks!

**Comment by Lxiamail** [comment]
@mrflo Please see answer at #3231
