### ISSUE TITLE
dotnet-svcutil mac osx - no executable found

### ISSUE THREAD

**Issue by scottmchargue** [dotnet/wcf#3179]
swmretina1:coreBrierlyClientTest scottmchargue$ **dotnet add package dotnet-svcutil**
  Writing /var/folders/l0/wf24khkn4z15f_xmbqb7rb8m0000gn/T/tmp5SQOaN.tmp
info : Adding PackageReference for package 'dotnet-svcutil' into project '/Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj'.
log  : Restoring packages for /Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/dotnet-svcutil/index.json
info : Package 'dotnet-svcutil' is compatible with all the specified frameworks in project '/Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj'.
info : PackageReference for package 'dotnet-svcutil' version '1.0.3' updated in file '/Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj'.
swmretina1:coreBrierlyClientTest scottmchargue$ **dotnet svcutil http://uat-essapi-aline.brierley.com/LWIntgrService.svc**
**No executable found matching command "dotnet-svcutil"
swmretina1:coreBrierlyClientTest scottmchargue$**

**Comment by scottmchargue** [comment]
swmretina1:coreBrierlyClientTest scottmchargue$ dotnet add package dotnet-svcutil
  Writing /var/folders/l0/wf24khkn4z15f_xmbqb7rb8m0000gn/T/tmp5SQOaN.tmp
info : Adding PackageReference for package 'dotnet-svcutil' into project '/Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj'.
log  : Restoring packages for /Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/dotnet-svcutil/index.json
info : Package 'dotnet-svcutil' is compatible with all the specified frameworks in project '/Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj'.
info : PackageReference for package 'dotnet-svcutil' version '1.0.3' updated in file '/Users/scottmchargue/Projects/coreBrierlyClientTest/coreBrierlyClientTest/coreBrierlyClientTest.csproj'.
swmretina1:coreBrierlyClientTest scottmchargue$ dotnet svcutil http://uat-essapi-aline.brierley.com/LWIntgrService.svc
No executable found matching command "dotnet-svcutil"
swmretina1:coreBrierlyClientTest scottmchargue$

**Comment by dasetser** [comment]
In your csproj file try replacing "PackageReference" with "DotNetCliToolReference" for the dotnet-svcutil entry. That should let dotnet know that you want to use the package as a cli tool instead of a standard package reference.

**Comment by scottmchargue** [comment]
Thanks!  That fixed it.

**Comment by zipswich** [comment]
Exactly the same problem on Windows 10, and the solution also works.
