### ISSUE TITLE
Generating proxy fails on WCF service

### ISSUE THREAD

**Issue by nbelley** [dotnet/wcf#3184]
_Originally posted by @nbelley in https://github.com/dotnet/wcf/issue_comments#issuecomment-424308920_

**Comment by nbelley** [comment]
I just can't get it to work consistently, cannot get by this:

[9/25/2018 7:51:34.114 AM] Adding Microsoft WCF Web Service Reference Provider to the project.
[9/25/2018 7:51:34.117 AM] Importing web service metadata ...
[9/25/2018 7:51:34.933 AM] Number of service endpoints found: 1
[9/25/2018 7:51:34.948 AM] Scaffolding service reference code ...
[9/25/2018 7:51:39.801 AM] Restoring NuGet packages for bootstrapper ...
[9/25/2018 7:51:42.883 AM] Building bootstrapper project ...
[9/25/2018 7:51:44.742 AM] Invoking bootstrapper ...
[9/25/2018 7:51:48.911 AM] Warning:Warning: There was a validation error on a schema generated during export:
    Source: 
    Line: 714 Column: 8
   Validation Error: Type 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:ArrayOfguid' is not declared.
[9/25/2018 7:51:48.915 AM] Warning:Warning: There was a validation error on a schema generated during export:
    Source: 
    Line: 716 Column: 8
   Validation Error: Type 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:ArrayOfguid' is not declared.
[9/25/2018 7:51:48.935 AM] Warning:Warning: There was a validation error on a schema generated during export:
    Source: 
    Line: 492 Column: 8
   Validation Error: Type 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:ArrayOfstring' is not declared.
[9/25/2018 7:51:48.960 AM] Warning:Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: The datatype 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:ArrayOfstring' is missing.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IDataSynchronization']
[9/25/2018 7:51:49.071 AM] Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IDataSynchronization']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='basicHttp_DataSynchronization']
[9/25/2018 7:51:49.094 AM] Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:service[@name='DataSynchronization']/wsdl:port[@name='basicHttp_DataSynchronization']
[9/25/2018 7:51:49.102 AM] Warning:Warning: No endpoints compatible with .Net Core apps were found.
[9/25/2018 7:51:49.124 AM] Generating files...
[9/25/2018 7:51:49.181 AM] Updating project ...
[9/25/2018 7:51:50.359 AM] Done.
[9/25/2018 7:51:51.326 AM] Finished adding Microsoft WCF Web Service Reference Provider to the project.

**Comment by mlacouture** [comment]
Hi @nbelley 

What version of Visual Studio are you using? I suspect you are using an old version of the tool.  Did you try this on a recent version of [Visual Studio 2017](https://visualstudio.microsoft.com/vs/)?
thanks,

**Comment by petekapakos** [comment]
I had this exact same issue, but I just got this working.  I had two issues.

1) I have added wcf service references to many projects prior to .net core and I have always used the format url/service.svc in the service reference UI.  This has always worked for me.  With this format in the new tool, hitting Go correctly finds all the methods and everything looks like it should work just like it always has.  Then it fails when I actually add it.  However when I appended ?singleWsdl to the url it suddenly worked.  I'm not sure why you are now required to do this, but it took me a long time to realize it.

2)This was a followup error I ran into on one endpoint.  I have a WCF service that has a reference to an external WCF service.  I was returning a value of type List<T> where T was an object in the external wcf service reference that was auto generated.  You used to be able to do this.  However the new tooling in .net core, it complains that PropertyChangedEventHandler is not serializable.  I simply made a DTO, mapped the values across and now return List<TDTO> and that fixed the issue.

**Comment by mlacouture** [comment]
Hi @petekapakos 
Thank you for helping resolve this issue and reporting the problems you are hitting. 

For #1 it should just work with the WCF Web Service Reference, that's why I'm asking about the version of the tool you are using. If you are using a recent version of the tool, would it be ok for you to share the service URL so we can investigate?

For #2, do you mind reporting a separate issue?

**Comment by petekapakos** [comment]
I am using the most recent version of visual studio.  15.8.6, I had just updated that day.  Is the tooling supposed to update with visual studio?  The service is internally hosted so I don't believe I'll be able to provide the url.  I can create a new issue for #2.

**Comment by dasetser** [comment]
@nbelley It looks like you were most likely using an old version of the tool. I'm closing this issue for now, but let us know if you still have the same problem using Visual Studio 2019 and we can investigate more.

@petekapakos It's strange that you have to append ?singleWsdl for it to work if you're using 15.8.6. We made some additional changes around how this worked recently. Can you try using Visual Studio 2019 or the dotnet-svcutil 2.0 command line tool? If it still doesn't work without ?singleWsdl it would be great if you could open a new issue with the output of dotnet-svcutil with the "-v Debug" parameter so we can see what's going on.
