### ISSUE TITLE
Remove Header Expect 100-continue with client certificate

### ISSUE THREAD

**Issue by VincentDW** [dotnet/wcf#3185]
Hi everyone,

I'm using a SOAP Client within a dotnetcore projet. I have to use a client certificate but the problem is that the soap server doesn't support the header "Except 100-Continue". 

I tried this old solution

`System.Net.ServicePointManager.Expect100Continue  = false; `

but it doesn't seem to work..

I found an internal property, but it doesn't allow to be override (or I didn't find a way out) : 
https://github.com/dotnet/wcf/blob/8589daec6cd3d7d4b1e90238cae951a91e937c03/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs#L230

I looked to add Interceptor or middleware, but I can't find something which allow me to remove the header.

Do you have any solution to remove this header ?

Thank you,

Vincent

**Comment by mconnew** [comment]
It looks like you are hitting a different issue. HttpClientHandler in .NET Core 2.1 doesn't correctly implement Windows authentication with the Expect header. There's an issue tracking this at dotnet/corefx#30760.

**Comment by mconnew** [comment]
As your specific request (disable the 100-Continue header) has been answered and you are unblocked, I'm going to close this issue. We're tracking the Windows auth with Expect header problem in issue #2923.
