### ISSUE TITLE
Generating proxy fails on WCF with WSDL with wildcards (Add Service Reference)

### ISSUE THREAD

**Issue by afvieira** [dotnet/wcf#3189]
Hi guys!
I'm adding a new Service Reference in Service Studio 2017 (15.8.4) using .Net Framework 4.7
The WSDL that I'm trying to import is this [WSDL file](https://pastebin.com/V4TbqduK).

The proxy is generated with errors.
It cannot resolve the `Any` parameteres.

Are you aware of this?
Thanks in advance.

![devenv_2018-10-03_12-15-32](https://user-images.githubusercontent.com/1200312/46407249-2805cc80-c706-11e8-94e8-496365c7d88c.png)

**Comment by Lxiamail** [comment]
@afvieira Looks like the proxy generation code may have a bug. We will look into this. BTW, for visual studio or .NET Full framework bug, please report it on https://developercommunity.visualstudio.com next time.

**Comment by afvieira** [comment]
Hi @Lxiamail, thanks for your quick reply.
Ok, I'll do it next time.

Cheers

**Comment by dasetser** [comment]
Closing since this issue does not happen on dotnet-svcutil or WCF Connected Service. Add Service Reference bugs aren't tracked on Github, so please report this on https://developercommunity.visualstudio.com if you are still encountering the issue.
