### ISSUE TITLE
Is dotnet-svcutil open-source?

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/wcf#3191]
Hi,
I'd like to contribute to this project by fixing some bugs in dotnet-svcutil, but I can't find it in this repository.
Is it open source? Where can I find it?

**Comment by mlacouture** [comment]
Hi @jeremyVignelles 
No, it is not open source, we've been thinking about it but it is not currently a priority to make it open source.
thank you for offering help.

**Comment by DickvdBrink** [comment]
Hmz, what is this for then?
https://github.com/dotnet/wcf/tree/master/src/svcutilcore/src
It looks like at least part of the code for the dotnet-svcutil, all the strings and stuff are there.

**Comment by mlacouture** [comment]
Yeah, that’s a bit confusing, that’s the .NET Core XmlSerializer … I will reopen the issue and keep it there, maybe we have a chance to open source this project in the future …

**Comment by StephenBonikowsky** [comment]
We want to do this, making an up-next item.

**Comment by skironDotNet** [comment]
there is a flag --enableDataBinding, but how to disable? with or without this flag it generates the fields and RaisePropertyChanged. Can dotnet-svcutil generate autoproperties without fields and RaisePropertyChanged?

**Comment by dasetser** [comment]
@skironDotNet Your question does not appear to be related to this issue. Please open a new issue if you need any follow up.

The short answer to your question is that the default if you don't pass the --enableDataBinding flag then the generated code should be to not implement the System.ComponentModel.INotifyPropertyChanged interface on all classes, there is no way to explicitly disable it. The tool does not have a way to specify to generate autoproperties without fields, but I don't think we should be calling RaisePropertyChanged unless you specifically pass -edb. 

If you're seeing the tool always generate this please open a new issue with information about how we can reproduce it (version of the tool and .NET SDK you're using, and project/wsdl if it's specific to anything).

**Comment by HongGit** [comment]
Thanks for your feedback!

dotnet-svcutil.exe is now open source in this repo.
