### ISSUE TITLE
Unable to serialize PropertyChangedEventHandler when returning objects from external wcf services

### ISSUE THREAD

**Issue by petekapakos** [dotnet/wcf#3193]
I have a WCF service project that has a reference to an external WCF service. I was returning a value of type 
`List<T>`
from my service where T was an object in the external wcf service reference that was auto generated. You used to be able to do this, as this same endpoint is currently being consumed by my .net framework application.  However the new tooling in .net core, it complains that PropertyChangedEventHandler is not serializable. I simply made a DTO, mapped the values across and now return `List<TDTO>` and that fixed the issue for now.

**Comment by Lxiamail** [comment]
@petekapakos Can you share repro steps and concrete error message? Can you also share the repro WSDL?

**Comment by petekapakos** [comment]
I have determined that the process only seems to error when I compile and run the service in release mode.  If I compile and run the service for debug it adds successfully.  If I compile it for release and run it on my local machine or on our development server it errors.  I have looked for documentation that indicates whether or not this is expected behavior and was unable to find any.  If this is working as intended then I apologize.

I created a project here
https://github.com/petekapakos/Wcf

**Comment by StephenBonikowsky** [comment]
Thanks @petekapakos we'l take a look.

**Comment by Lxiamail** [comment]
Looks like PropertyChangedEventHandler is not used in WSDL. It may be a bug in WCF Core code. It maybe either connectedservice shouldn't generate PropertyChangedEventHandler (or set serialization to ignore the type) or the type is not ignored as expected as runtime.
