### ISSUE TITLE
PlatformNotSupportedException for security message soap service, workaround requested

### ISSUE THREAD

**Issue by meyerovb** [dotnet/wcf#3195]
Create a new service from: https://id3global.com/ID3gWS/ID3global.svc

Try to execute this line of code: new GlobalAuthenticateClient().AuthenticateSPAsync(null, null, null);

Receive this error: System.PlatformNotSupportedException: 'TransportSecurityBindingElement.BuildChannelFactoryCore is not supported.'

I understand the security message feature is not yet supported in core, but is there any kind of workaround I can do to get this specific soap service working?

**Comment by Lxiamail** [comment]
@meyerovb We will look into this.

**Comment by Lxiamail** [comment]
@meyerovb We have looked into this, unfortunately, there is no work around that we can suggest.
