### ISSUE TITLE
Add a method to generate a proxy into a string

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/wcf#32]
In order to avoid parsing the wsdl myself, I'm using Silverlight SDK Microsoft.ServiceReference.dll to get the Silverlight generated proxy that I modify then before generating it.

I don't want to use svcutil that can only generate a file as far as I know.

However, I would like to remove my dependence to Silverlight. So I would love to see a such method here.

Thanks

Matthieu

**Comment by zhenlan** [comment]
cc: @mlacouture

**Comment by mlacouture** [comment]
This is a very good idea and we'll consider it for our next planning cycle.  We just published a prerelease version of the [WCF Connected Service] (http://blogs.msdn.com/b/webdev/archive/2015/12/15/wcf-connected-service-visual-studio-extension-preview-for-asp-net-5-projects.aspx) extension for ASP.Net 5 and Visual Studio 2015 Update 1, and are currently working on a version of svcutil.exe for the same platform (DNX).

**Comment by mlacouture** [comment]
Hi @MatthieuMEZIL
It's been a while since this issue was reported.  We are gathering interest for new features, are you still interested in having this feature available? 

Anyone else?

thanks,

**Comment by MatthieuMEZIL** [comment]
@mlacouture : No I don't need it anymore. So I think you can close it.
