### ISSUE TITLE
Generated X509 Certificates should contain a Subject Alternative Name

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#320]
We need to generate certificates that contain a **Subject Alternative Name (SAN)** field. This is to support testing X509Certificate claims. 

According to this: http://blogs.technet.com/b/uday/archive/2012/06/21/makecert-exe-san-and-wildcard-certificate.aspx and http://stackoverflow.com/questions/6383054/add-or-create-subject-alternative-name-field-to-self-signed-certificate-using 

`makecert.exe` is now deprecated and we can't expect a fix for this in the tool.

**Comment by zhenlan** [comment]
@iamjasonp you may like to look into this as well while you are looking into issue #324
