### ISSUE TITLE
Major security scenarios for supporting SecurityMode.Transport for NetTcpBinding

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#322]
This should include scenarios for #9, #12 and #81

**Comment by hongdai** [comment]
### NetTcpBinding Security.Transport Positive E2E scenarios

1. NetTcpBinding Security.Transport Positive E2E scenarios

a. Verify Service Identity Match DnsEndpointIdentity(Test already written), it covers below setting:

	ClientCredentialType = TcpClientCredentialType.None;
	
	Server certificate validation mode: None

b. Pairwise to cover the test pivots:
	PeerTrust is lower priority because it's mainly used in Message security.
	
Test pivot 1: Server certificate validation mode
	Authentication.RevocationMode = X509RevocationMode.NoCheck
	
	X509CertificateValidationMode.None
	
	X509CertificateValidationMode.PeerTrust(lower priority)
	
	X509CertificateValidationMode.ChainTrust
	
	X509CertificateValidationMode.PeerOrChainTrust(lower priority)
	
	X509CertificateValidationMode.ChainTrust
	
	X509CertificateValidationMode.PeerOrChainTrust
	
	X509CertificateValidationMode.Custom
	
Test pivot 2: Client certificate Type

	ClientCredentialType = TcpClientCredentialType.None;
	
	ClientCredentialType = TcpClientCredentialType.Certificate;
	
	ClientCredentialType = TcpClientCredentialType.Windows;
	
Test pivot 3:  Client Certificate Validation Mode

	This pivot is lower priority as the check is mostly done in server side
	
	Authentication.RevocationMode = X509RevocationMode.NoCheck
	
	X509CertificateValidationMode.None
	
	X509CertificateValidationMode.PeerTrust(lower priority)
	
	X509CertificateValidationMode.ChainTrust
	
	X509CertificateValidationMode.PeerOrChainTrust(lower priority)
	
	X509CertificateValidationMode.ChainTrust
	
	X509CertificateValidationMode.PeerOrChainTrust
	
    X509CertificateValidationMode.Custom    
	
### NetTcpBinding Security.Transport negative E2E scenarios

a. Service Identity does not match the identify specified by DnsEndpointIdentity

b. Invalid service certificate

	i. Certification authority revokes a certificate
	
	This can be tested using the test certificate and the default
	 
	RevocationMode-Online.
	
	ii. Wrong CN, CN is not the machine name
	
	iii. Expired Service Certificate
	
	iv. Wrong intend of the Cert(does not have Server Authentication in the intended)
	
	v. P2: PeerTrust: Cert not in trusted store
	
	vi. ChainTrust: fails to validate the chain
	
	vii. P2: PeerOrChainTrust - failed both peer and chain trust
	
	viii. Custom Validator: fail to validate 

c. Invalid Client certifice

   This is lower priority except i. as the validation path is mainly on server side
   
   	i. Multiple certificates with the same subject name
	   
	ii. Certification authority revoke a certificate
	
	iii. Wrong CN, CN is not the machine name
	
	iv. Expired Client cert
	
	v. Wrong intend of the Cert(does not have Client Authentication in the intended)
	
	vi. P2: PeerTrust: Cert not in trusted store
	
	vii. P2: PeerOrChainTrust - failed both peer and chain trust
	
	viii. ChainTrust: fails to validate the chain
	
	ix. Custom validator: fail to validate

**Comment by hongdai** [comment]
Closing the issue as this issue only tracks major scenarios are defined.

**Comment by iamjasonp** [comment]
@hongdai, does this bug being closed mean that all scenarios are simply defined, or *defined and implemented*? If not implemented, consider adding issues for each of the +ve and -ve groups so we can track their implementation.

**Comment by StephenBonikowsky** [comment]
During triage today
Tests exist for...
 - ClientCredentialType = TcpClientCredentialType.None
- ClientCredentialType = TcpClientCredentialType.Windows

ClientCredentialType = TcpClientCredentialType.Certificate cannot be implemented now due to X509Certificate not being in contract.

Items in test pivot 3 are not worth writing.

Negative scenario 'a' is legit
Negative scenario 'b' is pending the same contract update
Negative scenario 'c' not worth doing

**Comment by hongdai** [comment]
@iamjasonp Yes, the plan is to create new issues for those not implmented yet. I haven't got chance to do so before I left for vacation. I will sync up with Stephen where we are now and follow up.
