### ISSUE TITLE
dotnet svcutil --collectionType System.Collections.Generic.List`1 still outputs arrays

### ISSUE THREAD

**Issue by markmattes** [dotnet/wcf#3223]
I've been using svcutil for my proxy creation for a long time. I'm just starting on using dotnet core to make web service calls from Linux. So I'm replacing my /xx options with --xx. When I run the dotnet svcutil command from VS Code and put -ct System.Collections.Generic.List`1 (I added the `1 because that is what I've used in the past and that is what the Examples section said) the command doesn't execute, I get a continuation, e.g. '>' prompt. I can hit ctrl-D from a bash terminal but the command doesn't run. If I drop off the `1, then the array[] doesn't get converted to a List.

**Comment by markmattes** [comment]
Ok, I'm using the bash shell, so I just escaped the ` with a \`. However, I still didn't get the List. When I run:
$ dotnet svcutil http://orionunittest/PrintService.svc --serializer XMLSerializer -ct System.Collections.Generic.List\`1
I get this as an example:
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://PrintService.ServiceContracts/2007/07", Order=0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] CscIdCollection;

However, if I run similar command from svcutil, e.g.
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\Bin\NETFX 4.6.1 Tools\svcutil.exe" http://orionunittest/%2Service.svc /out:%1\%2\%2Service.cs /collectionType:System.Collections.Generic.List`1 /config:%1\%2\app.config /namespace:*,%3 /messageContract /serializable

I get what I expected:
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HealthCheckRequest", WrapperNamespace="http://PrintService.ServiceContracts/2007/07", IsWrapped=true)]
    public partial class HealthCheckRequest
    {  
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://PrintService.ServiceContracts/2007/07", Order=0)]
        public System.Collections.Generic.List<string> CscIdCollection;

**Comment by markmattes** [comment]
When I use the Connected Services tool in VS 2017 (15.7.5) I get the Generic.List:
public System.Collections.Generic.List<string> CscIdCollection;
And it's dotnet-svcutil 1.0.0.0, and the command line version is 1.0.3.
So what am I missing when I run the command line dotnet svcutil?
The command again is:
dotnet svcutil http://orionunittest/PrintService.svc --serializer XMLSerializer --collectionType "System.Collections.Generic.List\`1" -
-messageContract --namespace "*,Levi.LSA.USDistribution.Orion.Linux.ServiceReference.PrintService"

**Comment by dasetser** [comment]
The --collectionType parameter is only used when generating data contracts, so if you're using XmlSerializer the option is ignored. Is there a reason you're forcing XmlSerializer when using dotnet-svcutil but not with svcutil? I would expect the same behavior from both if you're using XmlSerializer. 

This limitation is something we can definitely make clearer in the tool. It looks like svcutil's documentation has a note about this, but there's no easy way to know if you're using dotnet-svcutil at the moment.

**Comment by markmattes** [comment]
Like I mentioned, we have been using the Frameworks svcutil for years and I thought that I was using XmlSerializer with that svcutil, e.g. with /serializable option. Geeze, I ran DataContractSerializer and it matches much better with what I had and I get the Generic.List. You rock!  
I'm still only getting the Async methods, but that is my #3227 post. Got an easy answer for that one? This thread can close.
