### ISSUE TITLE
Problems with adding WCF Service Reference to asp.net core 2.0 project

### ISSUE THREAD

**Issue by 25alex** [dotnet/wcf#3225]
Hi !

I'm trying to **add WCF Service Reference** to my **asp.net core 2.0** project using this manual from MSDN (https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)

I'm following all of those steps, but eventually i got an **error message**: 

"_Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj_".

![addingerrornew](https://user-images.githubusercontent.com/31659910/47140855-012fc480-d2c8-11e8-9340-c6dcd4a1032c.PNG)

Any ideas what the problem is ?

**Comment by 25alex** [comment]
btw, the wcf service does **works** with my another asp.net mvc (**.net framework**) project !

**Comment by dasetser** [comment]
Something is going wrong with the dotnet SDK you have installed. I would guess it's related to the issue reported at: https://github.com/dotnet/sdk/issues/2128

 Can you try updating your .NET Core SDK and seeing if it still reproduces?

**Comment by 25alex** [comment]
I've installed latest version of .NET Core SDK (2.1.403) and still got the error. Here's result of cmd `dotnet --info` command execution:

**_.NET Core SDK (reflecting any global.json):_**
 _Version:   2.1.403_
 _Commit:    04e15494b6_

**_Runtime Enviroment:_**
 _OS Name:     Windows_
 _OS Version:  6.3.9600_
 _OS Platform: Windows_
 _RID:         win81-x64_
 _Base Path:   C:\Program Files\dotnet\sdk\2.1.403\_

**_Host (useful for support):_**
  _Version: 2.1.5_
  _Commit:  290303f510_

**_.NET Core SDKs installed:_**
  _2.1.200 [C:\Program Files\dotnet\sdk]_
  _2.1.403 [C:\Program Files\dotnet\sdk]_

**_.NET Core runtimes installed:_**
  _Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]_
  _Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]_
  _Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]_

**_To install additional .NET Core runtimes or SDKs:_**
  _https://aka.ms/dotnet-download_

**Comment by dasetser** [comment]
That's very strange that you're seeing the same thing with the latest version of the SDK. Can you try running [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) directly to see if you get the same problem? And if so run it with diagnostics enabled (dotnet -d svcutil) to see what the underlying error is? In the issue I linked the problem was not having permission to the SDK directory. It would be helpful to know if you're hitting the same issue or something else.

**Comment by 25alex** [comment]
Now i got these error:

_Error: Connot obtain metadata from http://localhost:2422/Service1.svc_

_If this is a Windows (R) Communication Foundation service to which you have access, please check that_ _you have enabled metadata publishing at the specified address.  For help enabling metadata publishing,_ _please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455._

_WS-Metadata Exchange Error_
_URI: http://localhost:2422/Service1.svc_

_The remote server returned an error: (502) Proxy Error_

**Comment by jmf191** [comment]
I am also seeing this exact same error in Visual Studio Enterprise 2017 Version 15.9.2. 

dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]


```

**Comment by dasetser** [comment]
@25alex I'm not sure why you would be getting a proxy error. Can you access your service using other methods but only hit this error with this tool? 

@jmf191 Thanks for reporting that you're hitting the sdk issue too. Can you try running the dotnet-svcutil command on this machine to see if it has the same issue? It would be really helpful to see the underlying error. You should be able to see it if you just go through the steps from the [dotnet-svcutil getting started](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide#getting-started) but call "dotnet -d svcutil" instead of just "dotnet svcutil".

**Comment by dasetser** [comment]
It looks like the restore is failing because it can't load the nuget.org source, and later the Nuget.Versioning package can't be found, even though it should exist in the nuget.org feed. Are you using a network proxy or something else that would impact your ability to communicate with nuget.org?

**Comment by dasetser** [comment]
Are either of you still encountering this problem? Or did you find what the cause was?

**Comment by atifalibhatti** [comment]
I am facing the same issue.

**Comment by Lxiamail** [comment]
@atifalibhatti have you tried to go through the steps from the dotnet-svcutil getting started but call "dotnet -d svcutil" instead of just "dotnet svcutil" as @dasetser suggested earlier?

**Comment by atifalibhatti** [comment]
> @atifalibhatti have you tried to go through the steps from the dotnet-svcutil getting started but call "dotnet -d svcutil" instead of just "dotnet svcutil" as @dasetser suggested earlier?

For some strange reason, my %temp% paths had semicolons which were causing the problem. Got rid of them and bingoo! Thanks a bunch.

**Comment by Lxiamail** [comment]
@atifalibhatti I'ts happy it works out.
