### ISSUE TITLE
ConfigureEndpoint method not being generated

### ISSUE THREAD

**Issue by jmiller-bayshore** [dotnet/wcf#3226]
I have been looking for some samples on working with services in .net core and came across this thread that suggested a ConfigureEndpoint method (https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide).  When I use the tool to generate the code from my endpoint it doesn't create this method for me. 

Miguel Lacouture on that thread requested add the issue here.  Below are the details on my issue:
Service Url: https://services.hsp.transunion.com/submissionportal/submissionportal.asmx
Framework: .NET Core 2.0
Visual Studio 2017

Code that was generated attached here 
[GeneratedCodeForWebService.zip](https://github.com/dotnet/wcf/files/2493648/GeneratedCodeForWebService.zip)

Any additional information you need i can provide, just let me know

**Comment by dasetser** [comment]
Sorry for the delay in responding to this. This looks like a bug in the tool causing us to not find the endpoints correctly. Looking at the wsdl the service has a binding name with XML encoded spaces in it (MedData_x0020_External_x0020_Submission_x0020_PortalSoap), and we aren't dealing with them correctly. We'll work on a fix for this.

**Comment by s4lvo** [comment]
Hello,
I have the same problem, but in my case the binding name on wsdl is a simple string without encoded chars.

Attached the wsdl and the Reference.cs
[ServiceReferenceTS.zip](https://github.com/dotnet/wcf/files/2936149/ServiceReferenceTS.zip)

**Comment by dasetser** [comment]
This is fixed in dotnet-svcutil 2.0.1, which is now available. It's not fixed in the UI tool (WCF Web Service Reference Provider) yet, but we plan to update it in VS 2019 16.3.
