### ISSUE TITLE
Is there a way to log messages while consuming a soap service?

### ISSUE THREAD

**Issue by mrflo** [dotnet/wcf#3231]
Hi,
I'm looking for a simple way to log each request and answer send/receive while consuming a soap service generated with VS and with this dot net core wcf tool. I know that the default logging from ap.net is not there but has anyone an idea how I could implement this even manually? 

Thanks in advance!

**Comment by mconnew** [comment]
Which binding are you using?

**Comment by mrflo** [comment]
Hi @mconnew , it's just an httpBinding with no specific security

**Comment by mrflo** [comment]
Anyone can help or have an example? At least an example of how to look at the messages sent with BasicHttpBinding?

**Comment by mconnew** [comment]
For HTTP, you could implement a custom HttpMessageHandler/Delegating hander and log it using your favorite logging mechanism. An example behavior showing how to do this can be found [here](https://github.com/dotnet/wcf/blob/8589daec6cd3d7d4b1e90238cae951a91e937c03/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/HttpBindingTestHelpers.cs). An example of usage can be found [here](https://github.com/dotnet/wcf/blob/8589daec6cd3d7d4b1e90238cae951a91e937c03/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs#L87).

**Comment by mrflo** [comment]
Thank you @mconnew for pointing me in the right direction!

**Comment by Lxiamail** [comment]
Looks like this issue has been resolved. Closing it
