### ISSUE TITLE
WCF service datatable serialization

### ISSUE THREAD

**Issue by srinivaskacham** [dotnet/wcf#3242]
Hi,

I am consuming WCF service in ASP.Net core application, this service returns DataTable. VS generated async methods, when I add service reference to the project.

Is there anyway serialize service ResponseAsDataTable to DataTable directly/easily? Right now, I am adding data columns manually to data table and using DataSet.ReadXml().

Thanks in Advance.

**Comment by srinivaskacham** [comment]
Hi,

I am consuming WCF service in ASP.Net core application, this service returns DataTable. VS generated async methods, when I add service reference to the project.

Is there anyway serialize service ResponseAsDataTable to DataTable directly/easily? Right now, I am adding data columns manually to data table and using DataSet.ReadXml().

Thanks in Advance.

**Comment by StephenBonikowsky** [comment]
Hi @srinivaskacham is the WCF Service using a Typed DataTable, a type derived from DataTable?
https://referencesource.microsoft.com/#System.Data/System/Data/DataTable.cs,5906

If not could you provide us the WSDL and the generated client code to help us with further investigation.

Thanks

**Comment by srinivaskacham** [comment]
Hi,

It is not Type DataTable, it is a type derived from DataTable. Please let me know if you need any other information.

Thank you.

**Comment by Lxiamail** [comment]
@srinivaskacham Looks like this is by design. per comments [here ](https://referencesource.microsoft.com/#System.Data/System/Data/DataTable.cs,5906) Typed DataTable is not supported in WSDL (SQLBU 444636)
 
        either fails because xsd generates its typed DataTable with an internal parameterless ctor
        
        or System.NullReferenceException: Object reference not set to an instance of an object.   (if namespace of StronglyTyped DataTable is not set)
           at System.Data.XmlTreeGen.FindTargetNamespace(DataTable table)
 
        or System.InvalidOperationException: Schema Id is missing. The schema returned from WebServiceDataSetServer.Service+StudentsDataTable.GetSchema() must have an Id.
           at System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema()
