### ISSUE TITLE
WCF NetCore Skip Certificate Validation

### ISSUE THREAD

**Issue by xVishera** [dotnet/wcf#3250]
I'm trying to use a WCF api with .Net Core 2.1.2, but i'm currently facing some issues with certified validations.

The main problem is, when I'm DEBUGGING I can make requests against the server. When I deploy a executable file of my project and run in my machine, I can make requests either. But, when I copy the same executable to the acceptance environment, the code throws an exception "could not establish trust relationship for the SSL/TLS secure channel"

My machine is outside of the acceptance environment (I'm using a VPN). The acceptance machine is inside the environment.

Any ideas of what is going on ?

Thanks !

```
private WSClient InstantiateProxy()
{
    WSClient accessWSClient = new WSClient(EndpointConfiguration.MIAccessPort, Configuration["AppConfiguration:Endpoint"]);

    accessWSClient.ClientCredentials.Windows.ClientCredential =
        new NetworkCredential(Configuration["AppConfiguration:Username"], Configuration["AppConfiguration:Password"]);

    ConfigureBinding(accessWSClient);

    accessWSClient.ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication
    {
        CertificateValidationMode = X509CertificateValidationMode.None,
        RevocationMode = X509RevocationMode.NoCheck,
    };

    return accessWSClient;
}

private static void ConfigureBinding(WSClient accessWSClient)
{
    System.ServiceModel.BasicHttpBinding binding = new System.ServiceModel.BasicHttpBinding
    {
        MaxBufferSize = int.MaxValue,
        ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max,
        MaxReceivedMessageSize = int.MaxValue,
        AllowCookies = true
    };

    binding.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
    binding.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;

    accessWSClient.Endpoint.Binding = binding;
}
```

**Comment by xVishera** [comment]
Hello @Lxiamail 
Of course!

1. No, my machine is not in the domain. Both the webserver and the acceptance VM are in the same domain.
2. Yes, they are both in the same domain but in different subnetworks, but connected.
The Acceptance env is in the subnet 10.240.241 and the server is in the subnet 10.31.10

If I open a browser in the acceptance env and navigate to the server IP, I can see all the definitions of the WCF APIs, I can freely ping the server and connect in the IP/Port via telnet.

Thanks

**Comment by petwal11** [comment]
What type of certificate are you using? A self-signed certificate or a certificate from an authority? 
Errors of type "could not establish trust relationship" often has something to do with the certificate.
Verify "Issued to" of the certificate, DNS name and things like that. You must access the service using
exactly the same "path" that was used to generate the certificate (mycomputer.mydomain.com is not a match for mycomputer for instance). 

It could be a rights issue, is the user running the code on the server allowed to access the certificate store that has the certificate? Try to copy the certificate to a different store (such as trusted root), this can sometimes solve errors like this (especially if using self-signed certificate). When you debug you are running the code as a yourself (a domain user), but when running the code on the server you may be running the code as a different user (the user assigned to run an application pool for example). Even the same user often have different rights on different machine.

**Comment by xVishera** [comment]
@petwal11 Hi!

From Authority. The authority certificate is already included in my trusted root.

I'm acessing with the exact same path. 

The certificate is issued to  "machine.domain.local" and I'm trying to make a call to this exact path ( the only diff is the port number )

I already tried to add both ( the certificate from the authority and from the machine ) to my certificate folders ( through mmc ).

I think that the machine from my acceptance env is being blocked by a firewall rule or something like that.

**Comment by petwal11** [comment]
Do you have remote access to the acceptance environment (such as remote desktop)? 

If so, try to open web browser on the acceptance machine and access the service url that way. Do you get a "login dialog", do you get the option to download a certificate, do you get any warnings regarding the certificate? This can point a finger to what the issue is. If result is 403 or 404, then something is blocking the access. Pay attention to security settings in the browser (if using Internet explorer, you may have to add the url to your intranet zone before trying to access).

**Comment by xVishera** [comment]
@petwal11 

Yes, I have RDP access.

When I do that, the browser doesn't ask for a login, instead It shows me the information page about the WS.

The certificate is RED, pointing to a invalid certificate. But, when I click the certificate and check, both the machine certificate and the authority certificate are flagged as valid.


Br,

**Comment by mconnew** [comment]
I don't think this is a certificate validation problem as you have set the validation mode to none. I would expect a different exception message if that was the case. There's some other issue with the handshake going on. 
Which browser are you using to connect to the service which is working? Are you using SNI on the server? Can you try using HttpClient to connect to the the page which you are viewing in your browser? You can disable certificate validation by setting HttpClientHandler.ServerCertificateCustomValidationCallback to HttpClientHandler.DangerousAcceptAnyServerCertificateValidator.

**Comment by xVishera** [comment]
@mconnew 

Hi!

I've made two calls, one only using HttpClient and another one using the ClientHandler.

Both of them returned a inner exception "The Local Security Authority cannot be contacted".

**Comment by xVishera** [comment]
Solved.

Adding the following key to the serve registry solved the issue

 [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman] "ClientMinKeyBitLength"=dword:00000200

Thank to all the help!

**Comment by mconnew** [comment]
@xVishera, that registry key weakens the security requirements of the TLS connection. See [this article](https://support.microsoft.com/en-us/help/3061518/ms15-055-vulnerability-in-schannel-could-allow-information-disclosure) and [this article](https://docs.microsoft.com/en-us/security-updates/SecurityBulletins/2015/ms15-055) for details. According to the second article, Windows Server uses 1024 bits as the minimum key bit length by default so this suggests to me that your server isn't running Windows. I highly recommend installing any recommended security patches to your server so that it doesn't use a weak key length.
