### ISSUE TITLE
Can you coerce "Add Connected Service" to generate sync methods? 

### ISSUE THREAD

**Issue by koide** [dotnet/wcf#3254]
We have a sizeable amount of code using the standard sync versions of the methods generated by the old "Add Service Reference" Visual Studio tool. 

We are now migrating that to .NET Core. If we use the new "Add Connected Service" tool all we get are Async methods and this means changing lots of otherwise working code.

Is there any way to coerce the new tool to generate the old style sync methods? This would reduce a lot the impact of the migration.

**Comment by mlacouture** [comment]
Hi @koide, thank you for your request.  See issue #654 as for why we can't do this.
