### ISSUE TITLE
Peformance .NetCore vs .Net4.6.1

### ISSUE THREAD

**Issue by fabianeichfeldt** [dotnet/wcf#3272]
Hey folks,  
I am implementing a SOAP client with .NetCore 2.1 on Ubuntu 18.04. 
The service is an ONVIF camera. 
Currently I am wondering about the poor performance of my synchronous code. In some parts of the code the I need the synchronism. For example. Asking the device for it's capabilities, after that proceeding dependent on the result...
So, to debug my problem I've compared the performance with a small test client, running on .NetCore 2.1 and .Net 4.6.1. 
The performance of the .Net4.6.1 client was dramatically better (factor 10-15). For a better understanding I`ve also sniffed my network traffic, and see that I am loosing 1 second after each respond of the camera, before the next request is sent (see pictures)
![onvif_performancetest_net641](https://user-images.githubusercontent.com/44608348/48766142-14adc100-ecb4-11e8-8177-9152c5d8fa73.png)
![onvif_performancetest_netcore](https://user-images.githubusercontent.com/44608348/48766149-17a8b180-ecb4-11e8-89f3-4afdf5655665.png)

This is my very reduced code for debugging:  
```C#
  static void Main(string[] args)
  {
    //PREPARATION START
    var messageElement = new TextMessageEncodingBindingElement()
    {
        MessageVersion = 
           MessageVersion.CreateVersion(EnvelopeVersion.Soap12,
                            AddressingVersion.None)
    };

    HttpTransportBindingElement httpBinding = new 
       HttpTransportBindingElement()
    {
        AuthenticationScheme = AuthenticationSchemes.Digest
    };

    var binding = new CustomBinding(messageElement, httpBinding);
    var factory = new ChannelFactory<Device>(binding, new 
        EndpointAddress("http://1x.x.x.x/onvif/device_service"));

    //create Onvif device client
    var client = factory.CreateChannel();
    //PREPARATION END

    var start = DateTime.Now;
    Console.WriteLine($"Starting ...");
    //PERFORMANCE TEST (just ask 50 times for capabilities)

    for (int i = 0; i < 50; i++)
        client.GetCapabilities(new GetCapabilitiesRequest(new
            CapabilityCategory[] { CapabilityCategory.All }));

    Console.WriteLine($"Finished task... it took {DateTime.Now-start}");
  }
```

I would be really happy to get some hints how to improve this.

I have tested this on .NetCore 2.1 running on Ubuntu 18.04 and Win10  and .Net4.6.1 on Win10

**Comment by fabianeichfeldt** [comment]
Thanks for your relpy. The result was quite surpring for me. On my Windows 10 machine the switch boosted up my test program to the same performance as the .Net4.6.1 client-> so from this point of view I would say yes it might be a problem with the new `SocketsHttpHandler`.

I've tested this also on my Ubuntu machine (running in VMWare, not native) and it didn't change anything. Was this expected?

**Comment by mconnew** [comment]
Pre `SocketsHttpHandler`, on Windows the implementation was based on WinHTTP and on Linux, it was based on libcurl. This means the performance characteristics of the libcurl based implementation and SocketsHttpHandler are similar for your use case. As it's quite clear that this is an issue with SocketsHttpHandler, can you open an issue in the corefx repo? They will likely want some addition logging, the details of which can be found [here](https://github.com/dotnet/corefx/blob/release/2.2/Documentation/debugging/windows-instructions.md). Search on that page for the text "Helper scripts are available at" to get to the relevant section where they reference some simple scripts to run before and after you repro the issue to collect the relevant logs and provide the etl file.

**Comment by Lxiamail** [comment]
The issue is tracked by dotnet/corefx#33703

**Comment by oocx** [comment]
We had the same problem and could fix it with the solution provided by @fabianeichfeldt here: https://github.com/dotnet/wcf/issues/3185#issuecomment-425261773

Thank you Fabian for sharing your solution!
