### ISSUE TITLE
Error on reference WSDL Service

### ISSUE THREAD

**Issue by yalexandr** [dotnet/wcf#3292]
When I try to reference a WSDL Service (http://files.developer.sabre.com/wsdl/sabreXML1.0.00/usg/TokenCreateRQ.wsdl),  I'm getting some validation errors, but dont receive proxy TokenCreateRQService class in Reference. Wsdl has info about it. VS version 15.9.2

**Comment by dasetser** [comment]
@yalexandr I see you closed this issue. Did you figure out what the problem was? We should treat the validation errors as warnings (saying the service had some schema problems) and still generate the proxy class.
