### ISSUE TITLE
Status of uwp6.2 branch.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#3298]
We have never shipped anything out of the uwp6.2 branch and after some discussion we decided to support uwp6.2 from our release/2.1.0 branch since there are no product differences and our build process also produces uwp builds.

- [x] Disable/remove ADO build pipeline for uwp6.2
- [x] Disable auto-update process for uwp6.2 branch.
- [x] Remove reporting infra (MC) for uwp6.2 branch.
- [x] Remove the uwp6.2 branch from dotnet/wcf.

**Comment by StephenBonikowsky** [comment]
For removal from auto-updating process...
https://github.com/dotnet/versions/pull/403

**Comment by StephenBonikowsky** [comment]
@Lxiamail I don't see any reason for keeping this branch around in any form. We never shipped from it and it doesn't contain anything that is not also part of release/2.1.0 branch.

**Comment by Lxiamail** [comment]
@StephenBonikowsky I agree that we don't seem to need it any more.

**Comment by StephenBonikowsky** [comment]
All tasks completed.
Closing.
