### ISSUE TITLE
Deadlock in .Net Core but works in full framework

### ISSUE THREAD

**Issue by Eneuman** [dotnet/wcf#3303]
Hi!

I think I might have found a deadlock bug when calling a WS with client certificate.
I have attached source code to show the problem.

When running the code, no response is returned and it's stuck in a await loop.
The same code works great running in full .net framework.
Using fiddler shows that the service is returning a result.

The code can be downloaded [here](https://links-my.sharepoint.com/:u:/g/personal/per_bornsjo_links_se/ESerOiBgyCVMmfFMMUau1AgBc_HwSpHv6kz2MK_Wm6taSQ?e=TolhK2)

**Comment by StephenBonikowsky** [comment]
@imcarolwang 
Could you have your team create a repro based on the code provided by @Eneuman 
It would be great to have the same code working on desktop and failing on .NET Core.

**Comment by StephenBonikowsky** [comment]
@dasetser is working with @imcarolwang to create a repro.

**Comment by StephenBonikowsky** [comment]
@dasetser Do you have any update on this?

**Comment by dasetser** [comment]
@Eneuman Thanks for reporting this and providing a repro project. Sorry for the delay in responding. Did you find a way to work around this problem? Or is this still impacting you?

**Comment by Eneuman** [comment]
I didn’t find a workaround so I rescheduled that integration for a later date In hope that they would make a REST service available or the problem would be fixed in a later core release :)

**Comment by dasetser** [comment]
Alright, thanks. I'm looking into this now to see if I can determine the root cause. I just wanted to check if you found a workaround that could give me a hint. I'll keep you updated on our findings.

**Comment by mconnew** [comment]
@Eneuman, when a web service doesn't request the client certificate until after it has received the HTTP headers (this is the default with a WCF service hosted in IIS), there's a potential race condition when sending a large request with a high enough latency. The solution to this is to use the `Expect: 100-Continue` header. This wasn't supported by HttpClientHandler in older versions of .NET Core. As of .NET Core 2.1, this is now supported. You need to be using a late enough WCF package version to enable the Expect header. I can't remember which version we introduced it, but 4.5 has the support.  

Can you make sure you are using at least .NET Core 2.1 and System.ServiceModel.* package version >= 4.5. This should fix your issue.

**Comment by StephenBonikowsky** [comment]
@Eneuman Let us know if this doesn't work.
