### ISSUE TITLE
Soap header was not understood

### ISSUE THREAD

**Issue by yalexandr** [dotnet/wcf#3304]
remote wcf service need custom header 'MessageHeader' in envelop. Im adding this header, but processing response return this error:
'The header 'MessageHeader' from the namespace 'http://www.ebxml.org/namespaces/messageHeader' was not understood by the recipient of this message, causing the message to not be processed.  This error typically indicates that the sender of this message has enabled a communication protocol that the receiver cannot process.  Please ensure that the configuration of the client's binding is consistent with the service's binding. '

In classic .net recommend change BasicHttpBinding on WsHttpBinding, but core dont support it. Can you give me some advices?

**Comment by Lxiamail** [comment]
@yalexandr Have you tried to set MessageHeader.MustUnderstand to false by MessageHeader.CreateHeader()?

**Comment by Lxiamail** [comment]
@yalexandr Hope you worked out the issue. Closing the issue due to being inactive for a while.
