### ISSUE TITLE
Change Permissions to agent folder for cleanup step causing timeouts

### ISSUE THREAD

**Issue by MattGal** [dotnet/wcf#3305]
@riarenas commented on [Fri Nov 30 2018](https://github.com/dotnet/core-eng/issues/4727)

Email from @StephenBonikowsky 

> I’ve gotten several Linux builds failing recently with…
> ```
> ##[Error 1]
> The job running on agent DDVSOLINUXAGE011 has exceeded the maximum execution time of 60. 
> ```

> In comparing them to good runs it looks like the step “Change permissions to agent folder for cleanup steps” is taking way longer than normal and is causing the run to hit the 60 minute timeout.

> I didn’t see anything in the core-eng repo about this.

> Bad runs…
> https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2246238
> https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2244647

> Good run for comparison…
> https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2241438
> 
> Thanks,
> -Stephen

@ilyas1974  Maybe the work folders are getting too large in these agents?

---

@alexperovich commented on [Fri Nov 30 2018](https://github.com/dotnet/core-eng/issues/4727#issuecomment-443384535)

Can we please just git rid of the step that is causing the problem?
`chmod 777 -R .` is a very odd thing to do. We should just `/bin/sh foo.sh` the things we need to run.

---

@MattGal commented on [Mon Dec 03 2018](https://github.com/dotnet/core-eng/issues/4727#issuecomment-443788700)

Moving this issue to WCF.  This command is run inside your build definition and not in any piece we control or own:
![image](https://user-images.githubusercontent.com/7862010/49389433-22fbd400-f6db-11e8-92d7-c77550ac8650.png)

... feel free to ping us for guidance but we don't own your build definition.

**Comment by StephenBonikowsky** [comment]
We are moving our build infrastructure to Arcade, this issue should get resolved as part of that move.
wcf #3400

**Comment by StephenBonikowsky** [comment]
I haven't seen any failures due to this issue with our build definitions for our 2.1 branch that still has this step.
For master branch we have moved to Arcade.
