### ISSUE TITLE
Accept encoding in header

### ISSUE THREAD

**Issue by boris008** [dotnet/wcf#3308]
Hello,I need to disable gzip accept encoding in service request in .net core. I have web service which accepts and send only non compressed text xml. In .net 4.5 I was solved this by web.config httpstransport decompressionenabled=false in service model section. Is it possible in .net core? Thank you very much.

**Comment by Lxiamail** [comment]
@boris008 The config setting for decompressionenabled=false is not supported on .Net Core. However, you can gzip decompression can be set at [HttpChannelFactory level](https://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/Channels/HttpChannelFactory.cs,337) . [This discussion](https://github.com/dotnet/wcf/issues/3230#issuecomment-431921166) may be helpful for you to figure out how to do it.

**Comment by Lxiamail** [comment]
@boris008 Hope you worked out the issue. Closing the issue due to being inactive for a while.
