### ISSUE TITLE
Update project.json dependencies to be beta7 or above

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#331]
Beta7 (23225) appears to have updated the minor build number of all NuGet packages (example, 4.0.0 became 4.0.1, and 4.0.10 became 4.0.11.  This applies to at least all System.Net.*, System.ServiceModel.* and System.Serialization.* packages.

As a consequence, we are currently building and testing against only the previously shipped 4.0.0 versions and are not testing with any of the recent fixes for the streaming test failures.

To complete this task, update all the project.json and project.lock.json files to reflect the newer dependencies at or above beta7, including the new higher minor build number.

**Comment by roncain** [comment]
We have the same issue as https://github.com/dotnet/corefx/pull/3177 , namely we get errors building projects after updating our dependencies.  Waiting for a version of build-tools > 85 to fix this.

**Comment by iamjasonp** [comment]
This is being worked on in https://github.com/iamjasonp/wcf/tree/beta7-packages - there are some package dependency issues right now that I'm working through though.

**Comment by iamjasonp** [comment]
#339 was part one, still following up with updating the packages

**Comment by iamjasonp** [comment]
dotnet/buildtools#278 added a meta-package which updates the test-runtime references - this item can proceed.
