### ISSUE TITLE
Client access for named pipe connection

### ISSUE THREAD

**Issue by tirth** [dotnet/wcf#3314]
Is it possible to include the NetNamedPipeBinding class for clients on .NET Core? We have a fairly substantial codebase that has a single remaining dependency on Framework specific code, which is accessing a key service out of our control that communicates via named pipes.

With .NET Core 3, we would like to move our WPF applications/libraries that currently have to target net461 over to netcoreapp/netstandard, as things like self contained deployment would be very beneficial.

As it is Windows specific, having access through the Windows Compatibility Pack would also work.

**Comment by Lxiamail** [comment]
@tirth thank you for your suggestion. We will prioritize this request with the other feature request based on customer votes. In the meantime, do you use NetTcpBinding instead?

**Comment by tirth** [comment]
Unfortunately the service only uses named pipes, so NetTcpBinding won't work for our use case, but glad to know it's being worked on!

**Comment by Lxiamail** [comment]
Closing this issue and use #2535 to track the same issue.

**Comment by rsankardayal** [comment]
Dynamics GP eConnect has a WCF service with an netnamedpipebinding endpoint (net.pipe://localhost...). I am very much interested if there is a solution to consume this service with .Net Core.

Is there any way this class could be added to the compatibility pack?
