### ISSUE TITLE
Potential issue with Microsoft WCF Web Service Reference Provider

### ISSUE THREAD

**Issue by JELHolloway** [dotnet/wcf#3318]
I am having a issue upgrading some of my .net framework library projects to .net core library projects.

The main issue is with integrating with 3rd party services. 

Here are the steps to reproduce:

- Create new .net core library project 
- Add > Connected Service
- Use URI: 'https://bgtest.landregistry.gov.uk/b2b/BGStubService/DaylistEnquiryV2_0WebService?wsdl'
- Click go 

This will fail because the wsdl is behind Client Certificate Authentication. in .net framework "I would get a Certificate prompt", however, I do not in .net core.

I get the the following error:
"An error occurred while attempting to find services at 'https://bgtest.landregistry.gov.uk/b2b/BGStubService/DaylistEnquiryV2_0WebService?wsdl'. CData elements not valid at top level of an XML document. Line 1, position 3. (details)".

Fiddler shows this to be a "An attempt to authenticate with a client certificate failed. 
A valid client certificate is required to make this connection."

Expected result : at the Go step get use certificate prompt similar to .net framework

**Comment by dasetser** [comment]
@JELHolloway When you say this is working for .NET framework but not .NET Core, do you mean using Add Service Reference works, but the WCF Web Service Reference provider is failing? 

It looks like something may be wrong with the server's certificate. Both tools (and a browser) are showing the same behavior for me stating that they don't trust the certificate, and even if I force them to proceed I get the error you mentioned immediately without getting a request for a client cert.

**Comment by JELHolloway** [comment]
@dasetser please see attached image, this is just a blank .netframework form project. when going to the url (https://bgtest.landregistry.gov.uk/b2b/BGStubService/DaylistEnquiryV2_0WebService?wsdl) it asks to use the vaild cert,
however i cant get this functionality in a .netcore project

![image](https://user-images.githubusercontent.com/45971101/50588806-a562e980-0e7b-11e9-8686-c5badeace3ee.png)

**Comment by JELHolloway** [comment]
@dasetser Downloading the WSDL files and selecting them works as expected 
I will look forward to your response on the other issue

**Comment by HongGit** [comment]
It seems that this issue has resolved, closing.

Feel free top reactivate if this issue persists.

**Comment by johnstaveley** [comment]
Hi, How did you resolve this? I downloaded the wsdl as single file to make a reference but when I try and connect using the client certificate I too get the error "Certification authentication failed. An attempt to authenticate with a client certificate failed.". I am using:
                var client = new PropertyDescriptionEnquiryV2_0ServiceClient();
                client.ChannelFactory.Endpoint.EndpointBehaviors.Add(new HMLRBGMessageEndpointBehavior(username, password));
                client.ClientCredentials.ClientCertificate.Certificate = HMLRCertificate.GetLRClientCertificate();
                client.ChannelFactory.Credentials.ClientCertificate.Certificate = HMLRCertificate.GetLRClientCertificate();
and variants on the above, but it still acts as if I am not using the client certificate.

**Comment by johnstaveley** [comment]
In case it helps anyone, the solution to the second problem was to add a binding as described here: https://stackoverflow.com/questions/57331142/net-core-connected-service-with-ssl-certificate

**Comment by TehWardy** [comment]
That solves the problem once the client is generated ... 
How did you solve the issue of getting the WSDL description in the first place with a client cert?

I can't find an answer to this anywhere.

**Comment by JohnStaveleyGB** [comment]
I seem to remember you download them as a pack from the Land Registry website so it wasn't an issue we had.

**Comment by TehWardy** [comment]
Ah that's frustrating ... 
    I have to deal with a Major European banks API and they tell me that is not an option.
    
 I've asked for further instructions as to how they plan to get me up and running with this 20 year old approach to security but as of yet I've not had a reply back. I can't seem to make even simple rest get calls with the cert they've given me though so maybe my approach on the code side isn't quite right.
