### ISSUE TITLE
Several types in S.Security.Claims are not ported and have usage

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/wcf#3319]
_From @danmosemsft on November 12, 2018 22:25_

Top of the list are these types
```
T:System.Security.Claims.ClaimsAuthorizationManager
T:System.Security.Claims.AuthorizationContext
T:System.Security.Claims.ClaimsAuthenticationManager
```
Usage is under 1% except that one of our porting partners is using ClaimsAuthorizationManager.

_Copied from original issue: dotnet/corefx#33440_

**Comment by danmosemsft** [comment]
_From @jkotas on November 13, 2018 4:49_

This is WCF. It does not belong to CoreFX.

**Comment by danmosemsft** [comment]
Ah, identity model.

**Comment by danmosemsft** [comment]
These came up (albeit low in the list I think) in desktop port attempts by customers.

**Comment by Lxiamail** [comment]
@danmosemsft S.Security.Claims are not part of identity Model, they are part of CoreFx

**Comment by jkotas** [comment]
@Lxiamail S.Security.Claims namespace in .NET Framework contains types from multiple different technology stacks. You are right that some of them are part of CoreFx.

[System.Security.Claims.ClaimsAuthorizationManager](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsauthorizationmanager?view=netframework-4.7.2) and other types referenced by this issue are part of System.IdentityModel.dll in .NET Framework.

**Comment by jkotas** [comment]
I do not think it makes sense to look at these in isolation. The discussion about these types should be part of much higher level conversation what to do about WCF in .NET Core in general.

**Comment by Lxiamail** [comment]
@jkotas It makes sense if WCF is the primary user of these APIs. IdentityModel actually is owned by a different team rather than WCF team. @brentschmaltz, how does your team like to track this request? 
@danmosemsft, can you share the usage data?

**Comment by danmosemsft** [comment]
@Lxiamail to get usage data, ask @OliaG for the latest aggregated data from scans that customers recently chose to share with us.

**Comment by brentschmaltz** [comment]
@jkotas @Lxiamail 
These types below would be used by a ASP.NET 4.x application.
Katana and ASP.NET CORE use something completely different.

```
T:System.Security.Claims.ClaimsAuthorizationManager
T:System.Security.Claims.AuthorizationContext
T:System.Security.Claims.ClaimsAuthenticationManager
```

**Comment by mconnew** [comment]
I looked through the WCF codebase to find usage and the only usage by WCF of anything in IdentityModel in the System.Security.Claims namespace that I could find is by System.ServiceModel.Security.IdentityModelServiceAuthorizationManager which is an internal class and couldn't be used by WCF in .NET Core without the rest of IdentityModel being there anyway.

**Comment by brentschmaltz** [comment]
@mconnew ClaimsAuthorizationManager et al are used by WIF in the Fx partition under ida.

**Comment by mconnew** [comment]
@brentschmaltz, I was trying to explain why this issue doesn't belong in the WCF repo.

**Comment by Lxiamail** [comment]
@danmosemsft @brentschmaltz, where are the right place to track the issue?

**Comment by brentschmaltz** [comment]
@Lxiamail I am not sure, is there a plan to port this types?
@mconnew that makes sense.

**Comment by danmosemsft** [comment]
@Lxiamail I do not mind - if the code change would be in CoreFX, then the issue probably should be there and I should not have ported it to this repo.

But first I would decide whether you want to port it. It is your call

**Comment by Lxiamail** [comment]
@danmosemsft It will be @brentschmaltz's call if to port it. :)

**Comment by brentschmaltz** [comment]
@danmosemsft It's not just my call, but the team has no plans to port this as it's used by asp.net 4.x. We don't think it will every be useful in Core.

**Comment by danmosemsft** [comment]
OK. @terrajobst FYI in case he is tracking this. Feel free to close the issue.
