### ISSUE TITLE
Add NetNamedPipeBinding to Windows Compat Pack

### ISSUE THREAD

**Issue by joperezr** [dotnet/wcf#3322]
Moving issue from corefx to wcf. The original issue had the following discussion:

@tirth commented on [Wed Dec 05 2018](https://github.com/dotnet/corefx/issues/33847)

The only thing preventing our codebase from fully moving to .NET Core is a service out of our control that uses NetNamedPipeBinding. WCF through the compatibility pack currently provides all the other necessary pieces, this one class is the only missing bit. And as it's a base service, all things built on top of it have to run on Framework, even though they would benefit greatly from moving to Core.

Is there any way this class could be added to the compatibility pack?

---

@karelz commented on [Sun Dec 09 2018](https://github.com/dotnet/corefx/issues/33847#issuecomment-445518947)

Shouldn't that be part of https://github.com/dotnet/wcf repo?
It is part of `System.ServiceModel` assembly on .NET Framework: https://apisof.net/catalog/System.ServiceModel.NetNamedPipeBinding

---

@tirth commented on [Sun Dec 09 2018](https://github.com/dotnet/corefx/issues/33847#issuecomment-445559119)

Oh I wasn't sure what the best place was, I can open the issue there instead. Didn't realize WCF was going Core too, I figured it would only be through the compat pack. Thanks!

**Comment by Lxiamail** [comment]
Closing this issue and use #2535 to track the same issue.
