### ISSUE TITLE
Cannot import wsdl:binding Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on. XPath to wsdl:portType: 

### ISSUE THREAD

**Issue by izzetuslu** [dotnet/wcf#3327]
error details:
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://com/thy/service/websdom']/wsdl:binding[@name='WebsdomServiceSoapBinding']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://com/thy/service/websdom']/wsdl:service[@name='WebsdomService']/wsdl:port[@name='WebsdomSoapPort']
Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://com/thy/service/websdom']/wsdl:portType[@name='Websdom']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://com/thy/service/websdom']/wsdl:binding[@name='WebsdomServiceSoapBinding']
Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://com/thy/service/websdom']/wsdl:portType[@name='Websdom']

[Websdom.xml.zip](https://github.com/dotnet/wcf/files/2589070/Websdom.xml.zip)

_Originally posted by @izzetuslu in https://github.com/dotnet/wcf/issues/3157#issuecomment-439156168_

**Comment by dasetser** [comment]
@izzetuslu Have you been able to use this service with a WCF client using any other tools (svcutil, add service reference for example)?

It looks like this wsdl does not comply with the guidelines for interop defined in http://www.ws-i.org/Profiles/BasicProfile-1.1.html because of the way it's using the http://schemas.xmlsoap.org/soap/encoding/:Array type. You would need to work with the service owner or modify the wsdl to be compliant for the tool to generate the client correctly.

**Comment by izzetuslu** [comment]
> @izzetuslu Have you been able to use this service with a WCF client using any other tools (svcutil, add service reference for example)?
> 
> It looks like this wsdl does not comply with the guidelines for interop defined in http://www.ws-i.org/Profiles/BasicProfile-1.1.html because of the way it's using the http://schemas.xmlsoap.org/soap/encoding/:Array type. You would need to work with the service owner or modify the wsdl to be compliant for the tool to generate the client correctly.

Did you try to import zipped WSDL file using svcutil on Add Reference in Visual Studio?

**Comment by dasetser** [comment]
@izzetuslu I tried running both svcutil and Add Service Reference on your wsdl file and they both had warnings similar to dotnet-svcutil.

**Comment by dasetser** [comment]
Closing because this service's wsdl doesn't meet the interop guidelines and it appears we have the same behavior as other .NET client generation tools. The service owner should update their service or wsdl if they want more clients to be able to use this service.
