### ISSUE TITLE
Set User-Agent in CONNECT request

### ISSUE THREAD

**Issue by joscalv** [dotnet/wcf#3330]
Hi, 
I am performing a wcf request to an https service and I am having problems behind a proxy due user-agent filter.
I have configured the request to include a valid one, but it neither connect because proxy drops the CONNECT request because it haven't got user-agent header.
I have tried adding a IClientMessageInspector to include it, but it only includes the user-agent in GET request, not in the previous CONNECT.
I have checked it with fiddler.
Is there any solution? 
thanks in adavance

**Comment by Lxiamail** [comment]
Close the inactive issue. we will continue monitoring incoming issue report to prioritize investigation.
