### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'NTLM' 

### ISSUE THREAD

**Issue by Stephan-Ghequiere** [dotnet/wcf#3336]
With Version 4.3 (nuget) my web client can connect to a webservice that runs on an IIS server that only allows NTLM, but when I update to 4.5.3 I get this exception "The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'NTLM' "
The client  uses HttpClientCredentialType.Windows for ClientCredentialType. 
This had always worked before, so it seems it might be a bug that slipped in some version between 4.3 and 4.5.3.

**Comment by StephenBonikowsky** [comment]
Hi @Stephan-Ghequiere there shouldn't be any differences in how NTLM works. Could you help us narrow down your scenario a little bit by providing some additional information? A repro would be ideal.

We have tests that run regularly covering NTLM, take a look, maybe we are missing your exact scenario.
[NegotiateStream_Http_Tests](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs)

**Comment by Stephan-Ghequiere** [comment]
just came across this... https://github.com/dotnet/wcf/issues/2641#issuecomment-414869671

**Comment by StephenBonikowsky** [comment]
From that thread it looks like if your Service requires NTLM you should change your HttpClientCredentialType from 'Windows' to 'HttpClientCredentialType.Ntlm'.

@mconnew Do you have any feedback here for @Stephan-Ghequiere ?

**Comment by Stephan-Ghequiere** [comment]
So apparently, there was a change in the way athauntication is handled. Changing both BasicHttpBinding.Security.Transport.ClientCredentialType to HttpClientCredentialType.Ntlm will allow ntlm authentication to work with version 4.5.3; HttpClientCredentialType.Windows apparently no longer works (at least not in my scenario)...

**Comment by mconnew** [comment]
The reason why this broke was we made a change to start using CredentialCache. This adds a constraint that the credentials can only be used for the specified server and the authentication mechanism that the server is requesting. This prevents unintended leaking of credentials, for example if the server requests Basic authentication. With basic auth, you effectively send the username and password and without using CredentialCache, the server and coerce the client to send the actual credentials. So with this change, specifying a credential type of Windows limits the credentials to only be used with Negotiate.
