### ISSUE TITLE
"The service at the following URI does not have any valid endpoints" exception when am using .NetCore

### ISSUE THREAD

**Issue by naresh7453** [dotnet/wcf#3342]
Am facing this exception only in .net core but working in fine and able to create Web Service reference with .Net Farmework.

**Comment by dasetser** [comment]
@naresh7453 Are you using the latest version of Visual Studio? It looks like that message is from an older version of the tool, so it may work if you update to the latest version of VS and try again.

**Comment by naresh7453** [comment]
@dasetser am using Visual studio Community 2017, Version 15.5.1.

**Comment by dasetser** [comment]
@naresh7453 I would suggest updating the a more recent version of VS 2017 and trying again. 15.9 is the latest update for VS2017, and it should include a fix for this.

The behavior in the version you have is that if no endpoints were found in the wsdl the tool would show this error and not generate any code. Other tools for the full framework (svcutil, add service reference) still attempt to generate some code even if there aren't any endpoints in the wsdl, and we made a change to this tool to do the same.

**Comment by naresh7453** [comment]
@dasetser I have updated VS 2017 and now able to create web service reference and able to consume WCF service. Thank you for information.
