### ISSUE TITLE
Experiencing timeouts with WCF client running with .NET core 2.2 on Linux

### ISSUE THREAD

**Issue by edavedian** [dotnet/wcf#3344]
@mconnew We have a .NET core project which was originally deployed on Windows in Azure App Service.  This project makes REST based and SOAP based calls.  For REST based calls the project uses HttpClient via HttpClientFactory and for SOAP based calls the project uses WCF client.  We are now trying to port this project to Linux (on Centos).  In the load environment, I have a set of mock services that receive the requests from the application and respond immediately for both REST and SOAP calls.  

After porting and deploying the application on Linux,  under heavy load, there are no issues with the REST requests but every 2 minutes or so the WCF client reports a timeout as follows

```
System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The HTTP request to 'https://mue1olpaggsrvloadmock01.np.norton.com/mockservice/colpsoap' has exceeded the allotted timeout of 00:00:10 while reading the response. The time allotted to this operation may have been a portion of a longer timeout.
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
```

I am 100% sure that the issue is not in the mock service as everything works fine under the same load when the application is deployed on Windows in Azure App Service.  When I am monitoring the open sockets on the server where the mock services are hosted,  I can see that when the application is running on Linux there are on average about 150 open sockets compared to on average of 50 sockets when the application is running on Windows in Azure App Service and I feel this is where the issue might be.

Any suggestions you might have on how to narrow this down further or any other changes I can do to eliminate this socket saturation while running on Linux.

**Comment by mconnew** [comment]
You could be running into a thread starvation issue. If you don't have enough threads, then handling the completion will get delayed, which makes each request take longer. As you have more sockets, it sounds like this results in you having more concurrent requests in progress. Which then applies more thread pool pressure. Try [increasing your min threads](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=netframework-4.7.2) value for the worker thread pool and your IO thread pool. As an experiment, set them both to 1000, and make sure your [max threads](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setmaxthreads?view=netframework-4.7.2) are also at least 1000. If this improves things, then it's a thread pool warmup issue and you need to work out a reasonable min threads value to use. Having it cranked to 1000 can have unintended consequences elsewhere in some scenarios so I wouldn't leave it that high in production without significant testing to make sure you aren't hitting that problem. Keep an eye on the CPU usage as the issue would be lots of unnecessary CPU spinning consuming CPU if you are unfortunate enough to have one of those scenarios.

**Comment by edavedian** [comment]
@mconnew Thank you very much.  But what I am wondering though why the REST requests, which are using HttpClient via HttpClientFactory, aren't suffering from thread starvation.  The application actually makes more REST calls than SOAP based calls and if thread starvation was the culprit, shouldn't the application experience timeouts from HttpClient used for REST requests.  The timeout value for both REST and SOAP based calls are 10 seconds.

**Comment by mconnew** [comment]
It depends how you use WCF. If you are calling synchronous service methods (don't return a `Task<T>` but just return `T`), then you block on the calling thread and all the work happens on another background thread. So you end up using 2 threads there. We also have some code paths where we can write directly to the output stream using a synchronous API depending on how you configure your binding. I haven't checked on the new managed HttpClientHandler but on the older implementation it didn't have a way to do synchronous completions, it always used another thread to complete the write while the calling thread blocked.  
This may not be your problem, but based on the fact that you have more sockets open, it's my first guess and is easy to validate.
After I wrote all that, I realized it's worth checking, do you mean REST calls happening concurrently with SOAP calls?

**Comment by edavedian** [comment]
Correct, REST and SOAP calls are happening concurrently in the application.  For both REST and SOAP based calls, the application uses asynchronous methods to send requests.  And as indicated, this issue is not happening when the application is running on Windows in Azure App Service.  Can you see anything different about thread/socket management in WCF that might function differently on Linux?

**Comment by mconnew** [comment]
@edavedian, the socket management in HttpClientHandler is different in .NET Core with the newer SocketsHttpHandler. I've been told (by someone who I trust on these sorts of things) that an await on HttpClient SendAsync using SocketsHttpHandler continues on an IO thread as an IO thread is where the OS callback for a completed IO occurs. Also, Linux doesn't have a concept of an IO Thread pool like Windows does, so I wouldn't expect the continuation to happen on an IO Thread on Linux. Instead I would expect it to happen on a Threadpool worker thread.  
Have you tried increasing the minimum number of threads like I suggested? Did it make a difference?

**Comment by wfurt** [comment]
The new implementation certainly put more stress on thread pools and we have seen starvation cases when high concurrency is used. Tuning thread pool sizes should help.

**Comment by edavedian** [comment]
@mconnew @wfurt Thank you very much.  I will certainly try the thread pool tuning and update this issue with the results.  But what I am still wondering though why is the thread starvation not an issue with RESTful calls using HttpClient via HttpClientFactory which occur concurrently in the application with SOAP based calls using WCF.  The RESTful based calls have more load and concurrency in the application than SOAP based calls. If there was an underlying issue with SocketsHttpHandler then I would have expected for both RESTful and SOAP based calls to experience the thread starvation.  
I also tried providing a new instance ```HttpClientHandler``` through ```IHttpMessageHandlerFactory``` in the delegate ```Func<HttpClientHandler, HttpMessageHandler>```, but that didn't seem to make a difference.
May this have something to do with the singleton nature of the HttpClient used in WCF and if so, would introducing a mechanism for consumers of WCF to be able to provide their own instance of HttpClient help solve this issue?
Even though I will try the thread pool tuning, I am very hesitant though to solve this issue by that approach not knowing why RESTful based calls aren't affected by thread starvation.

**Comment by mconnew** [comment]
@edavedian, I'm not suggesting the issue stops there if it does solve your problem. It's very difficult to know what's going on with your codebase so I'm making a best guess. I'm doing a "Dr House" and diagnosing by using the treatment for the problem to verify if that's the problem. If it is, then the next step is to work out why. If it does turn out to be the issue, one simple explanation could be that SendAsync is called in a different way by WCF. We use the overload which accepts HttpCompletionOption and pass in HttpCompletionOption.ResponseHeadersRead. The default behavior is ResponseContentRead. This would cause WCF to need at least one more async continuation than if the default behavior is used. If you have thread starvation happening, lets say it causes an average 500ms delay for each continuation to be scheduled. Then each additional await that WCF does would delay things by 500ms. This could then cause WCF to have more delays than a simple REST call and cause it to timeout where the REST call doesn't. We have a couple of areas where we force a Task continuation to execute on another thread. The reason being that if you don't, then you can get into the situation where after calling TaskCompletionSource<TResult>.TrySetResult() you don't get to continue execution until the continuation completes and that might be a while. Basically WCF is a LOT more complicated in the number of things it needs to do that HttpClient and we need to force Task continuations to execute on a fresh thread to avoid some edge cases which cause really bad things to happen if the stars align. But I'm still guessing here. We need to confirm this is the issue, then we can investigate further.

**Comment by edavedian** [comment]
@mconnew Thank you very much.  I will try the thread pool tuning sometime this week and update this issue.

**Comment by edavedian** [comment]
@mconnew Tuning the thread pool as you indicated above does seem to eliminate the intermittent timeout issues in WCF.

**Comment by Lxiamail** [comment]
@edavedian It's great to know the problem is resolved.

**Comment by forgotten-warrior** [comment]
@edavedian I'm facing the same issue which happened with you, I have a .NET Core 2.2 application which makes a call to a WFC service via their proxy. There an intermittent timeout issue with the calls, can you share with me what have you done to fix the issues thoroughly?

Thanks in advance.
