### ISSUE TITLE
The Bridge should release certificates based on common naming pattern

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#335]
Today the Bridge uninstalls certificates it knows it has installed.  But this solution is not good for the scenario where it crashes, and also does not work well x-machine.

Solution is to add code in both Bridge.exe and the Bridge ResourceController to uninstall all certificates based on a fixed naming pattern we use when we create them.

**Comment by iamjasonp** [comment]
We currently generate with `CN = <subject> O = DO_NOT_TRUST, OU = Created by https://github.com/dotnet/wcf`, so it's probably all right to key off the OU. 

Otherwise, we could include something in the FriendlyName field.

**Comment by zhenlan** [comment]
@iamjasonp please proceed with the plan you proposed.

**Comment by zhenlan** [comment]
This is done.
