### ISSUE TITLE
Implement a certificate IResource for the Bridge

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#336]
Today the Bridge supports the abstraction of IResources, but the only implementation is for WCF endpoints.

I propose we create a new IResource capable of creating and installing a certificate for the POST verb, and returning the certificate content via the GET response.  Then we should make the Endpoints.cs test helper that accesses WCF endpoint IResources that require certificates first acquire the necessary certificate IResource.

The BridgeClient needs to be modified to install these certificates after it has acquired them.

**Comment by zhenlan** [comment]
@iamjasonp is currently working on this

**Comment by iamjasonp** [comment]
This is ready - however, we are blocked per approvals on #324
