### ISSUE TITLE
Set the SecurityProtocol (Ssl3 or TLS) for the different endpoints

### ISSUE THREAD

**Issue by apiliuhin** [dotnet/wcf#3360]
Hi, 

would like to clarify if there is a possibility to set up different protocols in the client app.config to use for example:
1) url 1 set to use TLS 1.2
2) url 2 set to Ssl3 (Ssl3 only)

using .NET Framework 4.5.2

Thanks.

**Comment by Lxiamail** [comment]
@apiliuhin on .NET Framework 4.5.2, WCF is hard coded to use Ssl3 and TLS1.0. If you want to specific which TLS version to use , you need to use .NET Framework 4.6+. You can set different SSL3/TLS version  to different binding, like 
`
<netTcpBinding>
    <binding>
        <security
         mode="None|Transport|Message|TransportWithMessageCredential">
            <transport clientCredentialType="None|Windows|Certificate"
             protectionLevel="None|Sign|EncryptAndSign"
             sslProtocols="Ssl3|Tls|Tls11|Tls12" >
                <extendedProtectionPolicy
                     policyEnforcement="Never|WhenSupported|Always"
                     protectionScenario="TransportSelected|TrustedProxy">
                    <customServiceNames></customServiceNames>
                        </extendedProtectionPolicy>
            </transport>
        </security>
    </binding>
</netTcpBinding>
`

Please reference to https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls for more info. 
BTW, for WCF on .NET Framework issue/question, please report at [Developer community](https://developercommunity.visualstudio.com/spaces/8/index.html) . This Github repo is for WCF Client on .NET Core.
