### ISSUE TITLE
I can not binding wsdl in .net core 2 console app

### ISSUE THREAD

**Issue by joaopauloit** [dotnet/wcf#3371]
See you my stack trace:

Importing web service metadata ...
Number of service endpoints found: 1
Scaffolding service reference code ...
Restoring NuGet packages for bootstrapper ...
Building bootstrapper project ...
Invoking bootstrapper ...
Warning:Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowSyncBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:service[@name='RightNowSyncService']/wsdl:port[@name='RightNowSyncPort']
Warning:Warning: Cannot import wsdl:binding
Detail: An exception was thrown in a call to a policy import extension.
Extension: System.ServiceModel.Channels.SecurityBindingElementImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowFedAuthSyncBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:service[@name='RightNowSyncService']/wsdl:port[@name='RightNowFedAuthSyncPort']
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Generating files...
Updating project ...
Done.

Could anyone help?

Regards.

**Comment by joaopauloit** [comment]
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowFedAuthSyncBinding']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:service[@name='RightNowSyncService']/wsdl:port[@name='RightNowFedAuthSyncPort']
Cannot import wsdl:binding
Detail: An exception was thrown in a call to a policy import extension.
Extension: System.ServiceModel.Channels.SecurityBindingElementImporter
Error: An unsupported security policy assertion was detected during the security policy import: <sp:SignedSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"><wsp:Policy xmlns:wsp="http://www.w3.org/ns/ws-policy"><sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient"><sp:RequestSecurityTokenTemplate><t:TokenType xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0</t:TokenType><t:KeyType xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer</t:KeyType><t:CanonicalizationAlgorithm xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2001/10/xml-exc-c14n#</t:CanonicalizationAlgorithm><t:SignWith xmlns:t="http://d...
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowFedAuthSyncBinding']

**Comment by dasetser** [comment]
@joaopauloit It looks like that service uses TransportWithMessageCredential for the security type, which is currently not supported on WCF for .NET Core. You can find more information and monitor when this is available in issue #8.
