### ISSUE TITLE
Allow only selecting a certain subset of the WSDL published API

### ISSUE THREAD

**Issue by MeikTranel** [dotnet/wcf#3379]
Is it really necessary that an entire API is generated? Wouldn't it be possible to select only certain methods and let svcutil figure all exchange types to generate?
Some APIs expose some metric tons of methods behind a single endpoint. It'd really help if i could select only the methods i need.

**Comment by Lxiamail** [comment]
@MeikTranel This is a feature request. We will prioritize this request depending on customer feedbacks.

**Comment by StephenBonikowsky** [comment]
This is not likely to ever be added. There are many other requests for features that break scenarios that are higher priority.
