### ISSUE TITLE
Log Bridge output file or memory and allow access to it.

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#338]
The Bridge currently writes some useful information to Console or Trace.  Consolidate on a common tracing mechanism and provide a way for a client to access it.  This could be in the form of an Http GET to the /bridge endpoint.

Also consider how the generated WCF services might log traces to a location accessible to the Bridge and offer a way for a client to download them.

**Comment by roncain** [comment]
My thinking in this area is to have a new LogController (ala BridgeController and ResourceController).  A GET request would obtain logs.  A DELETE request would clear them.  A PUT request would allow us to configure what level of loging we want.  We could also parameterize the GET to filter do different levels if we think that useful.

**Comment by SajayAntony** [comment]
@shhsu please provide a strawman for the set of API's and verbs and their usage.

**Comment by zhenlan** [comment]
Not applicable anymore.
