### ISSUE TITLE
Consume WCF with simple android app

### ISSUE THREAD

**Issue by KonstantinosP7** [dotnet/wcf#3380]
I want a simple android App consuming a wcf through client.

**Comment by Lxiamail** [comment]
@KonstantinosP7 You may try to use Xamarin.

**Comment by KonstantinosP7** [comment]
@Lxiamail Thanks for your reply. I AM using xamarin forms, I perform every step of the official walkthrough "Working with WCF" but the error I get is "System error. Endpoint not found". My service is working because I test it on my browser, I also get results when using UWP but throws error when I set android application as start up project. Thanks

**Comment by Lxiamail** [comment]
@KonstantinosP7 if you search for the open issues with Xamarin label in this repo, you can find multiple Xamarin related work items, which are blocked by Xamarin supports.
