### ISSUE TITLE
No executable found matching command "dotnet-svcutil"

### ISSUE THREAD

**Issue by miksh7** [dotnet/wcf#3381]
3 developers work on the same project using netcore 2.2.0 and VS2017 (15.9.6) and only one developer has an issue generating a new or updating the existing WCF service reference.

[2/5/2019 10:52:54.422 AM] Updating Microsoft WCF Web Service Reference Provider in the project.
[2/5/2019 10:52:54.433 AM] Resolving project references ...
[2/5/2019 10:52:54.575 AM] Importing web service metadata ...
[2/5/2019 10:52:55.459 AM] Number of service endpoints found: 1
[2/5/2019 10:52:55.485 AM] Scaffolding service reference code ...
[2/5/2019 10:52:58.269 AM] Error:No executable found matching command "dotnet-svcutil"
[2/5/2019 10:52:58.508 AM] Done.
[2/5/2019 10:52:58.549 AM] Failed updating Microsoft WCF Web Service Reference Provider in the project.

How to troubleshoot this issue? Adding 
`<DotNetCliToolReference` Include="dotnet-svcutil" Version="1.0.*" /> 
didn't help.
Perhaps, any troubleshooting tips in this window will be very helpful.

**Comment by bboxstart** [comment]
See solution in[ issue 3179](https://github.com/dotnet/wcf/issues/3179). In my case (on Windows) the problem was that I used the add package command which automatically created a 'PackageReference' instead of a 'DotNetClitoolReference'.

**Comment by dasetser** [comment]
@miksh7, you're using the WCF Web Service Reference Provider as part of Visual Studio, correct? You shouldn't need to manually add a dotnet-svcutil reference to your project if you're using this feature from VS. The tool will internally create a placeholder project and add dotnet-svcutil to it in order to call it. It looks like that is what's failing here. 

After the tool fails take a look in the %localappdata%\Temp\WCFConnectedService directory. You should see a folder that has this placeholder project. If you zip up and attach this folder here we can take a look at the problem, or you can try troubleshooting this yourself. Some things you could look for are: 

Can you run the "dotnet svcutil" command from the svcutil_starter directory? Does the svcutil_starter.csproj have the correct DotNetCliToolReference? Does the nuget.config point to a directory that has the dotnet-svcutil nuget package?

**Comment by miksh7** [comment]
@dasetser, yes it's WCF Web Service Reference Provider. Here is the content of %localappdata%\Temp\WCFConnectedService directory
[2019_Feb_14_13_45_23.zip](https://github.com/dotnet/wcf/files/2866425/2019_Feb_14_13_45_23.zip)

Running the "dotnet svcutil" command from the svcutil_starter directory resulted in the same error:
C:\Users\****\AppData\Local\Temp\WCFConnectedService\2019_Feb_14_09_04_52\svcutil_starter>dotnet svcutil
No executable found matching command "dotnet-svcutil"

Hope it helps you to troubleshoot.

**Comment by dasetser** [comment]
@miksh7 Thanks for attaching that. Everything looks correct to me. The csproj has the reference, and the nuget.config points to what should be the correct location. However, it looks like the package isn't getting restored. Do you get any kind of error message if you run `dotnet restore` in that folder on the machine having this problem?

On my machine I can just run a restore, then call dotnet svcutil and it succeeds. The log shows that the tool did run `dotnet restore --ignore-failed-sources` in that folder before it attempted to run dotnet svcutil, but there's no obj folder which makes me think the restore had a problem.

My guess is there's some kind of nuget.config file or some other nuget setting somewhere on that specific machine that's interfering with how we find the package.

**Comment by bboxstart** [comment]
@dasetser I was not using visual studio, but visual studio code and added the package using the dotnet cli.

**Comment by dasetser** [comment]
@bboxstart In that case you are not hitting the problem described in this issue (which is specific to a tool in Visual Studio). It sounds like you were indeed having the same problem as #3179, which is just the way the DotNetCliToolReference is designed. There's an issue at https://github.com/NuGet/Home/issues/4190 asking for them to improve this. For dotnet-svcutil specifically, this will be better once we move it to a global CLI tool (coming soon), as the install experience is better.

**Comment by sumtec** [comment]
Hi all,

For anyone who faces the problem as I do, please first run this in cmd or powershell:
dotnet tools install --global dotnet-svcutil --version 2.0.0

And then, go to the folder %localappdata%\temp\WCFConnectedService_lastDateTimeYouTriedImportWebServicesInVS2017_ and try this magic spell in the powershell:

$logcmd=(cat .\WCFConnectedServiceLog.txt | select-string 'dotnet "svcutil"').ToString().Trim()
$arr=$logcmd.SubString(1,$logcmd.Length-2) - split ' '
$part1 = $arr[0..($arr.Length-2)] -join ' '
$part2 = (cat $arr[-1].Trim('"')) -replace '/(\w{0,3}):', '-$1 ' -replace '/(\w+):?', '--$1 ' -replace '-out', '-o' -replace '`', '``'
iex ($part1 + ' ' + $part2)

Good Luck!

Thanks,
Frank

**Comment by dasetser** [comment]
We don't have enough information to investigate this right now. Let us know if you're still running into it and if you can answer the questions I asked so we have more information to investigate.
