### ISSUE TITLE
WCF Web service Reference provider: error: The Build Failed

### ISSUE THREAD

**Issue by drhdrhdrhdrh** [dotnet/wcf#3383]
With VS2017 v15.9.6, dotnetcore v2.2  SDK, the service is discovered and ref code is scaffolded, but the bootstrapper fails. The messaging in the output is not specific enough to help me figure out where to look for the problem. On exiting the wizard, nothing has been saved to the project.

![image](https://user-images.githubusercontent.com/47429766/52435785-e6c86380-2acf-11e9-8832-7732698a0998.png)

**Comment by dasetser** [comment]
@drhdrhdrhdrh You can find the bootstrapper project that's failing to build in the %localappdata%\Temp\WCFConnectedService directory after the tool fails. If you check that folder you should be able to see why the bootstrapper project is failing to build. If you can let us know why it's failing (or attach a zip of the directory so we can investigate) it would help us identify what went wrong generating the bootstrapper project.

**Comment by drhdrhdrhdrh** [comment]
Thanks for the support. Looking at the projects, both the svcutil_starter and svcutil_bootstrapper projects, upon opening in VS2017, indicate this error below. 
I didn't get time yet to dig into the details, I just wanted to post this initial evidence in case it rings any bells with you...

NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.	svcutil_starter	C:\Program Files\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137

**Comment by drhdrhdrhdrh** [comment]
Looking at the svcutil_bootstrapper project properties, the highlighted framework target drop down was balnk. I set it to the desired core 2.2 and the project builds without complaint. 
![image](https://user-images.githubusercontent.com/47429766/52794279-c008b080-302c-11e9-8f14-ccbbda93e1bf.png)

**Comment by dasetser** [comment]
@drhdrhdrhdrh Thanks for the additional information. Do you have a .NET Core 3.0 preview sdk installed? Try running `dotnet --version` on the command line to see if 3.0 preview is the sdk being used.

I was able to reproduce this after installing the .NET Core 3.0 preview on my machine. This looks like a bug in the tool where we aren't using the target framework of your project correctly, and instead use whatever target framework is the default for your current sdk (e.g. when a project is created using "dotnet new"). I'll investigate how to fix this and update this thread once we can get it fixed.

For now, I was able to work around this by specifying an older sdk version in a global.json at the root of my drive. To do this just open an admin command prompt in the C:\ directory and run:
`dotnet new globaljson --sdk-version 2.2.104`

Replace the version with whatever 2.2 version you have installed. You can check this with `dotnet --info`.

**Comment by drhdrhdrhdrh** [comment]
Well done! Unbeknownst to me, I do have 3.0 preview. Maybe it came across when I updated VS2017 a few days ago. I certainly didn't intentionally get it...

I followed your instructions above and tried to create the service again, and this time it worked fine.

Thanks for the fast and excellent response!

**Comment by Weldryn** [comment]
The very same issue happened to me while using VS 2017 on a .Net Core 2.2 project while I also having VS 2019 installed. The bootstrap project was as mentioned before targeting netcoreapp3.0 instead of 2.2.
The following workaround provided by @dasetser did the trick.

> 
> 
> @drhdrhdrhdrh Thanks for the additional information. Do you have a .NET Core 3.0 preview sdk installed? Try running `dotnet --version` on the command line to see if 3.0 preview is the sdk being used.
> 
> I was able to reproduce this after installing the .NET Core 3.0 preview on my machine. This looks like a bug in the tool where we aren't using the target framework of your project correctly, and instead use whatever target framework is the default for your current sdk (e.g. when a project is created using "dotnet new"). I'll investigate how to fix this and update this thread once we can get it fixed.
> 
> For now, I was able to work around this by specifying an older sdk version in a global.json at the root of my drive. To do this just open an admin command prompt in the C:\ directory and run:
> `dotnet new globaljson --sdk-version 2.2.104`
> 
> Replace the version with whatever 2.2 version you have installed. You can check this with `dotnet --info`.

Is this bug on the roadmap?

**Comment by dasetser** [comment]
@Weldryn We made a fix for this in VS2019, but don't plan to port it back to VS2017. I would suggest anyone hitting this issue upgrades to VS2019, or use the dotnet-svcutil command line tool if they're unable to upgrade.

**Comment by Myo-Gyi** [comment]
> @drhdrhdrhdrh Thanks for the additional information. Do you have a .NET Core 3.0 preview sdk installed? Try running `dotnet --version` on the command line to see if 3.0 preview is the sdk being used.
> 
> I was able to reproduce this after installing the .NET Core 3.0 preview on my machine. This looks like a bug in the tool where we aren't using the target framework of your project correctly, and instead use whatever target framework is the default for your current sdk (e.g. when a project is created using "dotnet new"). I'll investigate how to fix this and update this thread once we can get it fixed.
> 
> For now, I was able to work around this by specifying an older sdk version in a global.json at the root of my drive. To do this just open an admin command prompt in the C:\ directory and run:
> `dotnet new globaljson --sdk-version 2.2.104`
> 
> Replace the version with whatever 2.2 version you have installed. You can check this with `dotnet --info`.

Thanks, it works
