### ISSUE TITLE
Svcutil not generating all classes

### ISSUE THREAD

**Issue by MartPed** [dotnet/wcf#3392]
I have been provided with an .wsdl file and a set .xsd files to create proxy classes for interacting with an external service. Using svcutil i do not get all the classes corresponding to the defined types in the .xsd files. For example some xml on the form:
```xml
<xs:complexType name="ValidationReply" abstract="false">
  <xs:complexContent>
    <xs:extension base="common:Reply">
      <xs:sequence>
        <xs:element name="data" type="ns:ValidationReplyData" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
<xs:complexType name="ValidationReplyData" abstract="false">
  <xs:sequence>
    <xs:element name="errors" type="ns:Error" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>
```
Generates the code:
```c#
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Namespace")]
public partial class ValidationReply: Reply
{

    private Error[] dataField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Error[] data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}
```
But it should generate:
```c#
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Namespace")]
public partial class ValidationReply: Reply
{

    private ValidationReplyData dataField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public ValidationReplyData data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Namespace")]
public partial class ValidationReplyData
{

    private Error[] errorsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public Error[] errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField= value;
        }
    }
}
```
Other wise the xml returned by the external service will not deserialize correctly (ValidationReply.data always null).

Are others experiencing this issue?

**Comment by dasetser** [comment]
Hi @MartPed. If you're failing to deserialize the response then the wsdl/xsd files you have don't match what the service is actually sending.

The XML for a ValidationReply that matches the xsd snipped you posted would look something like this:
```
<ValidationReply>
  <data>
    <errors>error1</errors>
    <errors>error2</errors>
  </data>
<ValidationReply>
```
The ValidationReply element has an element named "data" inside of it. The data element is of type ValidationReplyData, which is defined as a sequence of some number of elements named "errors". Each of these errors elements will be of type Error.

If you convert the above XML snippet to code, it looks like what svcutil is generating. The data element is just a sequence of Error types, so it makes sense to generate it as an Error[].

Looking at the code you say it should generate, that would be converted to XML looking like this:
```
<ValidationReply>
  <data>
    <errors>
      <Error>error1</Error>
      <Error>error1</Error>
    </errors>
  </data>
</ValidationReply>
```


This XML does not match the xsd snippet you posted. According to the xsd the "errors" element occurs between 0 and unbounded times. It does not define there being exactly one "errors" element with some number of child "Error" elements.

From what I can tell this looks like svcutil is generating the right code, but that the wsdl does not match the data the service is sending.

**Comment by Lxiamail** [comment]
Closing the issue. Please feel free to reopen if you have further information to determine that it is svcutil tool issue.
