### ISSUE TITLE
Endpoint now found exception in asp.net core when try to consume WebSocket wcf Services

### ISSUE THREAD

**Issue by gopi247** [dotnet/wcf#3393]
I am having WCF custom binding web socket Service. Below are service configurations settings.
```xml
<system.serviceModel>
    <bindings>
      <customBinding>
        <binding name="CustomWsBinding" receiveTimeout="03:00:00">
          <byteStreamMessageEncoding/>
          <httpTransport>
            <webSocketSettings transportUsage="Always" createNotificationOnConnection="true" keepAliveInterval="03:00:00"/>
          </httpTransport>
        </binding>
      </customBinding>
    </bindings>
    <services>
      <service name="WCF_WebSocket.TestService" behaviorConfiguration="ServiceBehavior">
        <endpoint address="" binding="customBinding" bindingConfiguration="CustomWsBinding" contract="WCF_WebSocket.ITestService"/>
        <host>
          <baseAddresses>
            <add baseAddress="http://localhost:13060/"/>
          </baseAddresses>
        </host>
        <endpoint address="mex" binding="mexHttpBinding" contract="IMetadataExchange" />
      </service>
    </services>
    <behaviors>
      <serviceBehaviors>
        <behavior name="ServiceBehavior">
          <serviceDebug includeExceptionDetailInFaults="false" />
          <!-- Set to true for debugging-->
          <serviceMetadata httpGetEnabled="true"/>
        </behavior>
      </serviceBehaviors>
    </behaviors>
  </system.serviceModel>
```

When i am trying consume my service in my asp.net core application I am getting exception as EndpointNotFoundException: There was no endpoint listening at ws://localhost:13060/ that could accept the message.

I generated a scaffolding of my wcf service by **Add connected service**

`var client = new ServiceReference1.TestServiceClient();
            var x =  client.GetDataAsync("Hello");
            x.Wait();
            var result=x.Result;
            Console.WriteLine("result");`

Any help is much appericated.
![capture](https://user-images.githubusercontent.com/40033282/51596845-dcc73200-1f1f-11e9-94d7-968d8017b465.PNG)

![capture1](https://user-images.githubusercontent.com/40033282/51597243-c7063c80-1f20-11e9-8e2b-44dfffcf014d.PNG)

**Comment by Lxiamail** [comment]
@gopi247  does the client code work using add service reference on Desktop .NET Framework project?

**Comment by Lxiamail** [comment]
Close the inactive issue. Please feel free to reopen it if you have further information.
