### ISSUE TITLE
Change Minimum Required Version for Serialization Package to beta-8

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#341]
We need to change the minimum required version for the Serialization package to take the fix (https://github.com/dotnet/corefx/pull/2596).

**Comment by roncain** [comment]
@shmao , @zhenlan, @iamjasonp  -- I am uncertain how to proceed.  As far as I can tell, the latest S.R.Serialization.Xml package is 4.0.11-beta-023324.  But adding to the API surface area should have required bumping the minor version (example: 4.1.0-beta-*).   Though we could update to 4.0.11, I believe this version is inconsistent with versioning rules, and we would need to update again to 4.1.* after that error is corrected.  Thoughts?

**Comment by shmao** [comment]
@roncain Confirmed. Updating the dependency is only to take fixes made to S.R.Serializaiton.Xml. No new APIs.

**Comment by roncain** [comment]
Currently experiencing issues with xunit dependencies when I update the project.lock.json files.  Investigating...

**Comment by zhenlan** [comment]
@shmao the version of serialization package has been updated to 4.1.0-*. You should be unblocked on this item.

**Comment by shmao** [comment]
Closing the issue for the same reason that we closed https://github.com/dotnet/wcf/pull/359.
