### ISSUE TITLE
WCF package on .Net Core 3 is incorrectly configured for self contained

### ISSUE THREAD

**Issue by jmiddour** [dotnet/wcf#3437]
I tried to convert one of our desktop applications to .net Core 3.
This application made a simple WCF call.  The conversion compiled and runs correctly as a framework dependent app.  However, when self-contained, it crashes at startup due to missing System.Private.ServiceModel.dll.

We chose self-contained in order to build an MSIX package.  We worked around the issue by publishing with the win7-x64 runtime id.  This did work.  We updated the Visual Studio desktop bridge props file to

``` xml
<DesktopBridgeRuntimeIdentifier Condition="'$(Platform)' == 'x64'">win7-x64</DesktopBridgeRuntimeIdentifier>
```
We looked at the system.private.servicemodel nuget package and it appears it is incorrectly authored.  It should have the win-x64 instead of win7-x64.

@richlander @rido-min

**Comment by Lxiamail** [comment]
@jmiddour Thank you for reporting the issue. Which version of WCF nuget package that you used?

**Comment by jmiddour** [comment]
We used Microsoft.Windows.Compatibility version 2.1.0-preview3.19128.7
which references System.ServiceModel.* version 4.4.1
and System.ServiceModel.Syndication version 4.6.0-preview3.19128.7

**Comment by StephenBonikowsky** [comment]
@jmiddour This issue was fixed with WCF Core packages 4.5.0 and above, the Microsoft.Windows.Compatibility package should get updated to use the 4.5.0 and above WCF Core packages, we will open an issue with them to get that fixed.

Thank you!

**Comment by StephenBonikowsky** [comment]
Opened dotnet/corefx#35961

**Comment by StephenBonikowsky** [comment]
The package Microsoft.Windows.Compatibility has been updated to reference WCF packages version 4.5.3
