### ISSUE TITLE
DataContractSerializerOperationBehavior missing DataContractSurrogate

### ISSUE THREAD

**Issue by MattB-msft** [dotnet/wcf#3476]
While porting a large scale .net framework based application, we have been blocked by the missing property of DataContactSurrogate on the DataContractSerializerOperationBehavior . 

We have our own IDataContractSurrogate implementation that we use to do dynamic object serialization / deserialization of objects from WCF. 

We require a means to provided a custom bidirectional serializer for the DataContractSerializerOperationBehavior,  can this interface be added to the .net core / standard implementation.

**Comment by Lxiamail** [comment]
@MattB-msft Looks like we need to add a new API to DataContractSerializerOperationBehavior enable ISerializationSurrogateProvider. It is a new feature request.

**Comment by MattB-msft** [comment]
Ok, can this be done for 3.0?
otherwise can you offer an alternative?

**Comment by Lxiamail** [comment]
@MattB-msft We are investigating the issue to see if it is possible to get this in 3.0.
