### ISSUE TITLE
dotnet-svcutil with multiple namespaces validates WCF namespace wrong

### ISSUE THREAD

**Issue by Doomblaster** [dotnet/wcf#3494]
When using dotnet-svcutil from commandline and trying to map specific namespaces, code generation fails with 
`Error: The specified namespace mappings 'http://tempuri.org/Account/,Account' contain invalid identifiers.   at Microsoft.Tools.ServiceModel.Svcutil.CommandProcessorOptions.ProcessNamespaceMappingsOptionAsync(CancellationToken cancellationToken) in E:\A\_work\1\s\dotnet-svcutil-lib\Source\CommandProcessorOptions.cs:line 651
   at Microsoft.Tools.ServiceModel.Svcutil.CommandProcessorOptions.ResolveAsync(CancellationToken cancellationToken) in E:\A\_work\1\s\dotnet-svcutil-lib\Source\CommandProcessorOptions.cs:line 220`

It seems like the servicenamespace is validated as a c# codenamespace. It's not uncommon to have servicenamespace as a url, so this shouldn't fail. By servicenamespace/codenamespace, I mean --namespace "servicenamespace,codenamespace". Removing any : or / from the servicenamespace makes it work, but obviously the mapping fails.

**Comment by dasetser** [comment]
@Doomblaster Thanks for reporting this. You're right that this behavior is incorrect. It looks like this is a bug that was introduced in dotnet-svcutil 2.0. As a workaround you could try using an older version of the tool (1.0.4 for example), where the namespace mapping should still work as expected. We'll work on a fix for this.

**Comment by dasetser** [comment]
This is fixed in dotnet-svcutil 2.0.1, which is now available.
