### ISSUE TITLE
Memory leak when consuming SOAP endpoint on Linux ,but it is normal on windows

### ISSUE THREAD

**Issue by mcq1212** [dotnet/wcf#3504]
Hi guys,
I've encountered a memory leak when consuming SOAP endpoints in my .NET applications. The memory usage of my application continues to increase over time to a point where it obviously kills the application.My application is running on .NET Core 2.2

```
 public class TestService : ITesttInerface
    {
	    public GetTestOut Test()
        {
            using (var factory = new ChannelFactory<IPkgFiftStaffMng>(new BasicHttpBinding(), new EndpointAddress(Wcfurl.StaffUri())))
            {
                var callClient = factory.CreateChannel();
                var t = callClient.GetTestAsync().Result;
                (callClient as ICommunicationObject).Close();
                return t;
            }
		}
	}
```

**Comment by Lxiamail** [comment]
@mcq1212 memory management is different between Linux and Windows. To determine if this is a real leak, can you try to call GC.Collect() to force the GC to happen?

**Comment by Lxiamail** [comment]
Please feel free to reopen the issue if you have determined that it is a real leak in WCF code.
