### ISSUE TITLE
Make the Bridge shadow copy from BridgeResourceFolder to temporary folder

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#352]
Today the Bridge loads its resource DLL's directly from the specified BridgeResourceFolder.  Attempting to recompile/upload to that folder requires that the Bridge's AppDomains have first been torn down, otherwise we would get "file in use by other process" errors.

Instead, when the Bridge is told to reset, it should bulk copy everything from BridgeResourceFolder into a temporary folder, and it should always load DLLs from there.  This means we will be able to recompile/upload new DLLs to the BridgeResourceFolder while the Bridge is still in use or sitting idle after a prior run.  This will make it more robust in multi-machine scenarios.

**Comment by SajayAntony** [comment]
Would this work - https://msdn.microsoft.com/en-us/library/system.appdomainsetup.shadowcopyfiles(v=vs.110).aspx

**Comment by roncain** [comment]
I'm now thinking a better approach might be for the client to send to the server a zip of its entire resource folder and let the Bridge unzip it into its own temporary.  This will allow a single copy of the Bridge to run almost indefinitely, because the resources will always be fed by the client.

**Comment by roncain** [comment]
Closing this because it is not clear this will be needed.  If the Bridge is eventually equipped to take binaries or c# files or a Git SHA for its services, we will decide then now to manage where the binaries live
