### ISSUE TITLE
Could not load type 'System.ServiceModel.EndpointAddress' from assembly 'System.ServiceModel.Primitives, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by sagarwasule** [dotnet/wcf#3540]
I'm using connected service to connect to soap service from dotnet standard library. 

referencing to various issues already open I have added below packages 

<PackageReference Include="System.ServiceModel.Duplex" Version="4.5.3" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.5.3" />
    <PackageReference Include="System.ServiceModel.Primitives" version="4.5.3" />
    <PackageReference Include="System.Private.ServiceModel" version="4.5.3" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.5.3" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.5.3" />

Endpoint = new EndpointAddress('url');
            Binding = new BasicHttpBinding
            {
                MaxReceivedMessageSize = int.MaxValue,
                MaxBufferSize = int.MaxValue,
                ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max,
                AllowCookies = true,
                OpenTimeout = TimeSpan.FromMinutes(10),
                ReceiveTimeout = TimeSpan.FromMinutes(10),
                SendTimeout = TimeSpan.FromMinutes(10)
            }

using (var proxy = new ServiceProxy<Type>(Binding, Endpoint))
{
  // other code
}

I'm still having this issue.

**Comment by Lxiamail** [comment]
@sagarwasule can you share your project? what platform that you run the program on?

**Comment by sagarwasule** [comment]
Project is .net 2.0 standard library which is consumed in .netcore app 2.1
trying to deploy on windows server 2016 x64

**Comment by Lxiamail** [comment]
@sagarwasule Can you share a repro program/project?

**Comment by Lxiamail** [comment]
Close the issue. Please feel free to reopen the issue once you have repro program.
