### ISSUE TITLE
Could not find a configuration for ProjectReference 

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/wcf#3546]
When opening any of the solutions in Visual Studio 2017/2019, there are errors such as:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a configuration for ProjectReference 'C:\Source\wcf\src\System.ServiceModel.Primitives\ref\System.ServiceModel.Primitives.csproj' from configurations 'netfx;netstandard;uap;netcoreapp' when building 'Infrastructure.Common' for configuration 'netstandard2.0-Windows_NT-Debug-x64' .	Infrastructure.Common			
```
When this occurs, many of the normally available classes such as `System.Object` are marked as undefined.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0518	Predefined type 'System.String' is not defined or imported	System.Private.ServiceModel	C:\Source\wcf\bin\obj\Windows_NT.AnyCPU.Debug\System.Private.ServiceModel\uap\SR.cs	3408	Active

```

The developer guide (https://github.com/dotnet/wcf/blob/master/Documentation/developer-guide.md#building-the-repository) needs to be updated with instructions on how to deal with this scenario.

**Comment by Lxiamail** [comment]
@Grauenwolf Thank you for your feedback. Yes, the developer guide doc needs to be updated. We are working on improving the WCF repo infrastructure to work better within VS.
