### ISSUE TITLE
.Net core wsdl service import fails

### ISSUE THREAD

**Issue by bjorneb78headit** [dotnet/wcf#3547]
I import the following service to an Azure function:

https://api.24sevenoffice.com/authenticate/v001/authenticate.asmx

When trying to run I get the following error;

Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.ServiceModel, Version=4.1.2.4, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Systemet finner ikke angitt fil.
File name: 'System.Private.ServiceModel, Version=4.1.2.4, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()

importing the following;

Please advise,

Best regards 

Bjørn

**Comment by Lxiamail** [comment]
@bjorneb78headit Looks you may have run into the issue issue as https://github.com/Azure/azure-functions-host/issues/2877, can you try the solution suggested there?

**Comment by Lxiamail** [comment]
Closing the issue and use Azure/azure-functions-host#2877 to track the issue
