### ISSUE TITLE
update 4.4 to 4.5

### ISSUE THREAD

**Issue by asleeguilez** [dotnet/wcf#3548]
Hi.
I have a project that refers to a web service, with integrated windows authentication when I use versions 4.4. * (Duplex, Http, NetTcp, Security) everything works fine.
but for the reason that I have to expose in web service in SOAP, these NuGet were updated to 4.5. * and it does not work anymore.
This is an example that I use:

```c#
        public string enviar(string user, string pasword, string domain)
        {
            var binding1 = new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly);
            binding1.Security.Transport.ClientCredentialType = HttpClientCredentialType.Ntlm;
            CorreoSoapClient client = new CorreoSoapClient(binding1, new EndpointAddress("http://wscorreos/correosis/correo.asmx"));
            client.ClientCredentials.Windows.ClientCredential = new System.Net.NetworkCredential(user, pasword, domain);
            client.ClientCredentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Identification;
            return client.EnviarAsync("<MsgCorreo></MsgCorreo>").Result;
        }
```

**Comment by mconnew** [comment]
Can you provide more information about what you mean by "it does not work anymore"?

**Comment by asleeguilez** [comment]
when you update from 4.4. * to 4.5. * This source code example does not send credentials.

**Comment by Lxiamail** [comment]
@asleeguilez Have you reproduced the issue on more than one machines? If so, can you please share a simple repro program with us?

**Comment by Lxiamail** [comment]
Please feel free to reopen the issue when you have simple repro program.
