### ISSUE TITLE
Provide extensibility point to add DelegatingHandlers to HttpClient

### ISSUE THREAD

**Issue by epignosisx** [dotnet/wcf#3549]
Currently WCF [has full control of the HttpClient instances](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs) making it impossible to intercept, inspect or modify HTTP requests/responses.

It would be great if client applications could hook into some mechanism to add their own `DelegatingHandler`s. This would unblock quite a few important scenarios that currently happen inconveniently at a higher layer or cannot happened at all like:

1- On demand logging of entire or partial pieces of the HTTP request or response.
2- Apply retry or circuit breaker logic.
3- Allow to record http interactions and replay them later for reliable integration tests. [VCR style](https://github.com/vcr/vcr).

@mconnew provided some solid points why this is more involved than expected in this [issue](https://github.com/dotnet/wcf/issues/1592#issuecomment-299076735): 

>  the limitation we have is we can't add an api which isn't available on the full framework. On the full framework, we use HttpWebRequest so it would be quite a lot of work to make a delegating handler work with HttpWebRequest in a reliable clean way.

It is my understanding .NET Core stance on this has changed and new APIs has been added that will not be ported to Full Framework. 

> On UWP we don't even use HttpClientHandler and have our own implementation in order to make Certificate authentication work.

Is this still the case? Would the recently introduced `SocketsHttpHandler` fix this?

> It's definitely a nice feature ask and we might be able to accommodate it in the future via some api agnostic mechanism. Off the top of my head, maybe we could add some support for adding something to the BindingParameterCollection used when creating a ChannelFactory. The question though is what? We create a new instance of HttpClientHandler for each remote hostname/credentials combination to prevent any security issues with cached credentials for one request being used for a different request which needs different credentials. This means we need to be able to instantiate the DelegatingHandler inside WCF on demand.

An API like this would would satisfy your the above requirements (assuming we do not have the UWP issue anymore):

```cs
var binding = new HttpBasicBinding(...);
binding.DelegatingHandlers.Add(new RetryHandler());
binding.DelegatingHandlers.Add(new LoggingHandler());
```

Then inside the `HttpChannelFactory`, we would put the entire HttpClient middleware together similiar to this [implementation](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpClientFactory.cs#L58-L90)

With this design WCF is still in full control of the `HttpClientHandler` creation and even owns the creation of the delegating handlers in case it wants to add its own handlers.

**Comment by mconnew** [comment]
This was completed last year as part of issue #2400. Read that issue for the discussion on the approach, and there's a link to a test which uses it.

**Comment by epignosisx** [comment]
Music to my ears! I’ll take it for a spin.
