### ISSUE TITLE
Support Basic Http/Https Binding with TransportWithMessageCredential

### ISSUE THREAD

**Issue by muralinekkanti** [dotnet/wcf#3552]
Requesting to support the TransportWithMessageCredential for BasicHttpBinding & BasicHttpsBinding.

**Comment by Lxiamail** [comment]
Yes, we have an implementation in PR. Please use https://github.com/dotnet/wcf/issues/8 to track the status.

**Comment by se7vanj** [comment]
With **DotNet 3.1.100-preview3-014645**, problem still exists, getting below error when consuming a service which requires wsse:Security. Am I missing anything.. 

**Error:** The value 'TransportWithMessageCredential' is not supported in this context for the binding security property 'securityMode'
