### ISSUE TITLE
Self Contained .net Core Console with WCF proxy : File or Assembly System.Private.ServiceModel 4.1.2.4 Not Found

### ISSUE THREAD

**Issue by nicoclau** [dotnet/wcf#3554]
Hello, I made a project Console .net Core 2.2 with a WCF Client.
All works well, but when I tried to publish self contained, an expection is thrown when running 

![image](https://user-images.githubusercontent.com/16133485/56281209-55e3b900-610c-11e9-898a-faed394409af.png)

It seems to look for the wrong version of System.Private.ServiceModel : Version 4.1.2.4
but the project depends on the version 4.4.4

![image](https://user-images.githubusercontent.com/16133485/56281331-a2c78f80-610c-11e9-8440-c51908be7fac.png)

Moreoever the assembly seems to be missing in the publish folder...

Can you please tell me what steps can I follow to troubleshoot this problem?

Thanks :)

**Comment by nicoclau** [comment]
Well I made it work, it is weird though...
I just upgraded the nuget to a more recent version

<ItemGroup>    
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.5.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.5.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.5.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.5.*" />
  </ItemGroup>

![image](https://user-images.githubusercontent.com/16133485/56288378-f93dc980-611e-11e9-9257-8347e6bee4cc.png)

So System.Private.ServiceModle is also at the version 4.5.3, and the self-contained app works properly with WCF now.

Do you know why?
It is annoying to stumble over a problem like that.
The version 4.4.4 was used by Visual Studio 2017 v 15.7.2 with the last version of .net core 2.2

![image](https://user-images.githubusercontent.com/16133485/56288572-56397f80-611f-11e9-8145-0a9297752f97.png)

![image](https://user-images.githubusercontent.com/16133485/56288596-62bdd800-611f-11e9-8f31-edda5dad94ee.png)

I used this version 2.2.106 which is compatible for Visual Studio 2017
As 2.2.203 is compatible only for Visual Studio 2019 it seems.

That is also not clean in my humble opinion..

Can you tell us why the version 4.4.4 didnt work in self contained version?
Thank you guys :)

**Comment by Lxiamail** [comment]
@nicoclau can you share a project file repro the issue that you originally reported?

**Comment by nicoclau** [comment]
No problem Alicia, I made another project which just used a simple web service the famous calculator.

I tested the "Add" for adding 2 numbers. 
You must publish the self contained app yourself as it is too big to send here :(

I didnt update the nugets, I left them as Visual Studio added when I used the service reference wizard.
You will see the error when running the exe of the published self contained app "Test.exe"

Here the project
[Test.zip](https://github.com/dotnet/wcf/files/3093782/Test.zip)

Please make me know what happens :)
Thanks

Kind regards
Nicolas

**Comment by nicoclau** [comment]
Could you reproduce the problem Alicia? 

Thanks :)

**Comment by Lxiamail** [comment]
@nicoclau Yes, I can repro it. Thank you for the standalone repro program! We still need to investigate why it happens. In the meantime, please to update to WCF 4.5.3 package.

**Comment by nicoclau** [comment]
Perfect :) Glad you could see the problem.
Anyway it is better to update, but still it interests me to know why the bug came up :+1:
