### ISSUE TITLE
About 'Use the WCF Web Service Reference Provider Tool'

### ISSUE THREAD

**Issue by hehetiger** [dotnet/wcf#3557]
I refer to web service according to the method of "https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide" of the web site, and there is an error as shown in the figure. My project uses. net core 2.1. There are two questions: 1. Where is the "Error Details Window"? 2. What causes this mistake and how to solve it?
![image](https://user-images.githubusercontent.com/20674115/56331665-e3341580-61bf-11e9-9b94-d956e90067d3.png)，After the translation of the errors in the figure:An unknown error occurred when calling the service metadata component

**Comment by YonglianQian** [comment]
WCF is not well compatible for Asp.net Core project. such as ws-* Binding.
[https://github.com/dotnet/wcf/issues/31](https://github.com/dotnet/wcf/issues/31)
[https://github.com/dotnet/wcf/issues/1370](https://github.com/dotnet/wcf/issues/1370)

**Comment by Lxiamail** [comment]
@hehetiger can you provide a simple repro project and the service endpoint so that we can try to repro it?

**Comment by jges42** [comment]
@hehetiger had the same error -> in uninstalled dotnet core sdk version 3 preview and than it worked again. 

There is an incompatibility issue that needs to be fixed. 

For example with this WebService: https://tst2.logpay.de/atlas/WalletService?wsdl 
with .NET Core SDK V3 installed -> error
without .NET Core SDK V2 installed -> works fine

**Comment by Lxiamail** [comment]
@hehetiger Thanks for the information. We will look into it.

**Comment by dasetser** [comment]
@hehetiger @jges42 I can reproduce this on Visual Studio 2017, but not in Visual Studio 2019. Are you using VS2019?

**Comment by jges42** [comment]
@dasetser I was using VS2017, update in my company will only happen in a few month

**Comment by dasetser** [comment]
@jges42 It sounds like you're running into issue #3383, which is different from the error message for this issue which is related to metadata processing. It's recommended to use the latest version of VS2019 when using .NET Core 3.0, so if you need to use use the .NET Core 3.0 SDK before your company upgrades to VS2019 I'd suggest using the dotnet-svcutil command line tool for adding a service reference, but know that you may run into other issues with VS.

@hehetiger Unfortunately this error message doesn't seem very specific, so I'm not sure how to investigate the problem. Can you provide the wsdl file for the service you're trying to add a reference to? That would help us investigate this.

**Comment by dasetser** [comment]
Let us know if you can provide the wsdl or have any additional information that would help us investigate this.

**Comment by xiongze666** [comment]
![image](https://user-images.githubusercontent.com/47880804/60419682-70f89c00-9c18-11e9-9c8a-fe2b9542cfd3.png)
我也遇到这个问题，什么原因啊

**Comment by xiongze666** [comment]
> 如果您能提供wsdl或有任何其他信息可以帮助我们对此进行调查，请告诉我们。
![image](https://user-images.githubusercontent.com/47880804/60419732-971e3c00-9c18-11e9-80bc-5afca480105d.png)
我的这个问题也是不知道什么原因

**Comment by StephenBonikowsky** [comment]
@xiongze666 We have your issue #3716, this issue has been closed.

**Comment by kuntalbose** [comment]
Facing same problem with Asp.net Core 3.1 with **Microsoft Visual Studio Community 2019 Version 16.4.6**  detailed issue posted [here](https://github.com/dotnet/aspnetcore/issues/21395)
