### ISSUE TITLE
No endpoints compatible with .Net Core apps were found importing SAP WSDL

### ISSUE THREAD

**Issue by kayakingcoder** [dotnet/wcf#3565]
I get the message "No endpoints compatible with .Net Core apps were found" when trying to import a SAP WSDL into 'n .Net Core 2.2 project .

The same service works fine in a Framework 4.6 app with the following HttpBinding.

                    binding = new BasicHttpBinding();
                    binding.Security.Mode = BasicHttpSecurityMode.Transport;
                    binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
                    binding.MaxReceivedMessageSize = 2097152;
                    binding.SendTimeout = new TimeSpan(0, 3, 0);
                    binding.ReceiveTimeout = new TimeSpan(0, 3, 0);

I thought it was the same problem as [Issue 8](https://github.com/dotnet/wcf/issues/8), but apparently not (as I can now see in the above code).

Below is the WSDL:

	<?xml version="1.0" encoding="utf-8"?>
	<wsdl:definitions targetNamespace="urn:sap-com:document:sap:rfc:functions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:sap-com:document:sap:rfc:functions" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
		<wsdl:documentation>
			<sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
		</wsdl:documentation>
		<wsp:UsingPolicy wsdl:required="true"/>
		<wsp:Policy wsu:Id="IF_IF_ZES_GET_CUSTOMER_DATA">
			<sapsession:Session xmlns:sapsession="http://www.sap.com/webas/630/soap/features/session/">
				<sapsession:enableSession>false</sapsession:enableSession>
			</sapsession:Session>
		</wsp:Policy>
		<wsp:Policy wsu:Id="OP_IF_OP_Z_WEB_GET_CUSTOMER_DATA">
			<sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
			<sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
			<saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
			<saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
		</wsp:Policy>
		<wsdl:types>
			<xsd:schema attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:rfc:functions">
				<xsd:simpleType name="char1">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char10">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char11">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="11"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char12">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="12"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char130">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="130"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char132">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="132"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char14">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="14"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char15">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="15"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char16">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="16"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char18">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="18"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char2">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char20">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char220">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="220"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char25">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="25"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char3">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="3"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char30">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="30"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char31">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="31"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char32">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="32"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char35">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="35"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char4">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char5">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="5"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char50">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="50"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char6">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="6"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="char7">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="7"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="cuky5">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="5"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="curr13.2">
					<xsd:restriction base="xsd:decimal">
						<xsd:totalDigits value="13"/>
						<xsd:fractionDigits value="2"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="date10">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"/>
						<xsd:pattern value="\d\d\d\d-\d\d-\d\d"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="decimal23.4">
					<xsd:restriction base="xsd:decimal">
						<xsd:totalDigits value="23"/>
						<xsd:fractionDigits value="4"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="decimal3.0">
					<xsd:restriction base="xsd:decimal">
						<xsd:totalDigits value="3"/>
						<xsd:fractionDigits value="0"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="lang">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric1">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric2">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric3">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="3"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric4">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric5">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="5"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric6">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="6"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric7">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="7"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="numeric8">
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="8"/>
						<xsd:pattern value="\d*"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:simpleType name="time">
					<xsd:restriction base="xsd:time">
						<xsd:pattern value="[0-9]{2}:[0-9]{2}:[0-9]{2}"/>
					</xsd:restriction>
				</xsd:simpleType>
				<xsd:complexType name="ZSSD_WEB_GET_CUSTOMER_DATA">
					<xsd:sequence>
						<xsd:element name="CUSTOMER" type="tns:ZBAPI_CUSTOMER_DETAILS_KNB1"/>
						<xsd:element name="GENERAL" type="tns:BAPICUSTOMER_KNA1"/>
						<xsd:element name="ADDRESS" type="tns:BAPICUSTOMER_04"/>
						<xsd:element name="CUSTEXTRA" type="tns:ZSSD_WEB_CUST_EXTRA"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="ZBAPI_CUSTOMER_DETAILS_KNB1">
					<xsd:sequence>
						<xsd:element name="CUSTOMER" type="tns:char10"/>
						<xsd:element name="COMP_CODE" type="tns:char4"/>
						<xsd:element name="PERSONNEL_NUMBER" type="tns:numeric8"/>
						<xsd:element name="CONTROL_ACCOUNT" type="tns:char10"/>
						<xsd:element name="PAYMENT_METHODS" type="tns:char10"/>
						<xsd:element name="PMNTTRMS" type="tns:char4"/>
						<xsd:element name="PSTG_BLK_B" type="tns:char1"/>
						<xsd:element name="SORT_KEY" type="tns:char3"/>
						<xsd:element name="CLERK" type="tns:char2"/>
						<xsd:element name="AUTH_GROUP" type="tns:char4"/>
						<xsd:element name="HD_OFFICE" type="tns:char10"/>
						<xsd:element name="ALT_PAYER" type="tns:char10"/>
						<xsd:element name="PMNT_NOTICE_WITH_CI" type="tns:char1"/>
						<xsd:element name="PMNT_NOTICE_SALES" type="tns:char1"/>
						<xsd:element name="PMNT_NOTICE_LEGAL" type="tns:char1"/>
						<xsd:element name="PMNT_NOTICE_ACC" type="tns:char1"/>
						<xsd:element name="PMNT_NOTICE_WO_CI" type="tns:char1"/>
						<xsd:element name="CUVD_CLEAR" type="tns:char1"/>
						<xsd:element name="PMNT_BLOCK" type="tns:char1"/>
						<xsd:element name="BILL_EXC_CHARGES_TRMS" type="tns:char4"/>
						<xsd:element name="INTEREST_IND" type="tns:char2"/>
						<xsd:element name="LAST_INTEREST_RUN" type="tns:date10"/>
						<xsd:element name="INTEREST_CYCLE" type="tns:numeric2"/>
						<xsd:element name="ACT_AT_CUS" type="tns:char12"/>
						<xsd:element name="CUST_USER" type="tns:char15"/>
						<xsd:element name="ACCOUNT_MEMO" type="tns:char30"/>
						<xsd:element name="PLANNING_GROUP" type="tns:char10"/>
						<xsd:element name="INSTITUTION_NUMBER" type="tns:char2"/>
						<xsd:element name="AMOUNT_INSURED" type="tns:curr13.2"/>
						<xsd:element name="INSURANCE_LEAD_MONTHS" type="tns:decimal3.0"/>
						<xsd:element name="DEDUCTIBLE_PERCENTAGE" type="tns:decimal3.0"/>
						<xsd:element name="POLICY_NUMBER" type="tns:char10"/>
						<xsd:element name="INSURANCE_VALIDITY_DATE" type="tns:date10"/>
						<xsd:element name="COLLECTIVE_INVOICE_VAR" type="tns:char1"/>
						<xsd:element name="LOCAL_PROCESSING" type="tns:char1"/>
						<xsd:element name="BANK_STATEMENT" type="tns:char1"/>
						<xsd:element name="BILL_EXCHANGE_LIMIT" type="tns:curr13.2"/>
						<xsd:element name="NEXT_PAYEE" type="tns:char10"/>
						<xsd:element name="LAST_KEY_DATE" type="tns:date10"/>
						<xsd:element name="REC_PMNT_HISTORY" type="tns:char1"/>
						<xsd:element name="TOLERANCE_GROUP" type="tns:char4"/>
						<xsd:element name="CHECK_CASHING_TIME" type="tns:decimal3.0"/>
						<xsd:element name="HOUSEBANKID" type="tns:char5"/>
						<xsd:element name="CUST_INDIV_PMNT" type="tns:char1"/>
						<xsd:element name="SUBSIDY_INDICATOR" type="tns:char2"/>
						<xsd:element name="PREV_ACCOUNT_NUMBER" type="tns:char10"/>
						<xsd:element name="PMNT_GROUPING" type="tns:char2"/>
						<xsd:element name="KNOWN_NEG_LEAVE" type="tns:char4"/>
						<xsd:element name="DUNNING_NOTICE_GRP" type="tns:char2"/>
						<xsd:element name="LOCKBOX" type="tns:char7"/>
						<xsd:element name="PMTMTHSUPL" type="tns:char2"/>
						<xsd:element name="SELECTION_RULE" type="tns:char3"/>
						<xsd:element name="EDI_PMNT_ADVICE" type="tns:char1"/>
						<xsd:element name="RELEASE_GROUP" type="tns:char4"/>
						<xsd:element name="REASON_CODE_CONV" type="tns:char3"/>
						<xsd:element name="FAX" type="tns:char31"/>
						<xsd:element name="INTERNET" type="tns:char130"/>
						<xsd:element name="CREDIT_MEMO_PMNT_TERM" type="tns:char4"/>
						<xsd:element name="ACTIVITY_CODE" type="tns:char2"/>
						<xsd:element name="DISTRIBUTION_TYPE" type="tns:char2"/>
						<xsd:element name="VALUE_ADJUSTMENT" type="tns:char2"/>
						<xsd:element name="TEL" type="tns:char30"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="BAPICUSTOMER_KNA1">
					<xsd:sequence>
						<xsd:element name="CUSTOMER" type="tns:char10"/>
						<xsd:element name="ACC_1_TIME" type="tns:char1"/>
						<xsd:element name="ADDRESS" type="tns:char10"/>
						<xsd:element name="ORDR_BLK_G" type="tns:char2"/>
						<xsd:element name="EXPR_STAT" type="tns:char25"/>
						<xsd:element name="TRAIN_STAT" type="tns:char25"/>
						<xsd:element name="LOC_NO_1" type="tns:numeric7"/>
						<xsd:element name="LOC_NO_2" type="tns:numeric5"/>
						<xsd:element name="AUTH_GROUP" type="tns:char4"/>
						<xsd:element name="INDUSTRY" type="tns:char4"/>
						<xsd:element name="CHK_DIGIT" type="tns:numeric1"/>
						<xsd:element name="DATA_LINE" type="tns:char14"/>
						<xsd:element name="CREAT_DATE" type="tns:date10"/>
						<xsd:element name="ENTERED_BY" type="tns:char12"/>
						<xsd:element name="UNLOAD_PT" type="tns:char1"/>
						<xsd:element name="BILL_BLK_G" type="tns:char2"/>
						<xsd:element name="FISK_ADDR" type="tns:char10"/>
						<xsd:element name="WORK_TIME" type="tns:char2"/>
						<xsd:element name="ALT_PAYER" type="tns:char10"/>
						<xsd:element name="GROUPKEY" type="tns:char10"/>
						<xsd:element name="ACCNT_GRP" type="tns:char4"/>
						<xsd:element name="CLASSIFIC" type="tns:char2"/>
						<xsd:element name="VENDOR_NO" type="tns:char10"/>
						<xsd:element name="DELI_BLK_G" type="tns:char2"/>
						<xsd:element name="LOC_CODE" type="tns:char10"/>
						<xsd:element name="DEL_FLAG_G" type="tns:char1"/>
						<xsd:element name="REG_MARKET" type="tns:char5"/>
						<xsd:element name="PSTG_BLK_G" type="tns:char1"/>
						<xsd:element name="TAX_NO_1" type="tns:char16"/>
						<xsd:element name="TAX_NO_2" type="tns:char11"/>
						<xsd:element name="EQUAL_TAX" type="tns:char1"/>
						<xsd:element name="SLS_PUR_TX" type="tns:char1"/>
						<xsd:element name="PAYER_DOC" type="tns:char1"/>
						<xsd:element name="TRADE_ID" type="tns:char6"/>
						<xsd:element name="VAT_REG_NO" type="tns:char20"/>
						<xsd:element name="COMPETITOR" type="tns:char1"/>
						<xsd:element name="SLSPARTNER" type="tns:char1"/>
						<xsd:element name="PROSPECT" type="tns:char1"/>
						<xsd:element name="CUSTTYPE_4" type="tns:char1"/>
						<xsd:element name="DFLT_SP" type="tns:char1"/>
						<xsd:element name="LEGALSTAT" type="tns:char2"/>
						<xsd:element name="IND_CODE_1" type="tns:char10"/>
						<xsd:element name="IND_CODE_2" type="tns:char10"/>
						<xsd:element name="IND_CODE_3" type="tns:char10"/>
						<xsd:element name="IND_CODE_4" type="tns:char10"/>
						<xsd:element name="IND_CODE_5" type="tns:char10"/>
						<xsd:element name="INITCONTCT" type="tns:char10"/>
						<xsd:element name="ANN_SALES" type="tns:decimal23.4"/>
						<xsd:element name="SALES_YEAR" type="tns:numeric4"/>
						<xsd:element name="CURRENCY" type="tns:cuky5"/>
						<xsd:element name="CURRENCY_ISO" type="tns:char3"/>
						<xsd:element name="EMPLOYEES" type="tns:numeric6"/>
						<xsd:element name="EMPL_YEAR" type="tns:numeric4"/>
						<xsd:element name="ATTRIBUTE" type="tns:char2"/>
						<xsd:element name="ATTRIB_2" type="tns:char2"/>
						<xsd:element name="ATTRIB_3" type="tns:char2"/>
						<xsd:element name="ATTRIB_4" type="tns:char2"/>
						<xsd:element name="ATTRIB_5" type="tns:char2"/>
						<xsd:element name="ATTRIB_6" type="tns:char3"/>
						<xsd:element name="ATTRIB_7" type="tns:char3"/>
						<xsd:element name="ATTRIB_8" type="tns:char3"/>
						<xsd:element name="ATTRIB_9" type="tns:char3"/>
						<xsd:element name="ATTRIB_10" type="tns:char3"/>
						<xsd:element name="SOLE_PROP" type="tns:char1"/>
						<xsd:element name="ANN_SALES1" type="tns:decimal23.4"/>
						<xsd:element name="TAXJURCODE" type="tns:char15"/>
						<xsd:element name="FY_VARIANT" type="tns:char2"/>
						<xsd:element name="DLVSCHEDUSE" type="tns:char3"/>
						<xsd:element name="INSPBYCUST" type="tns:char1"/>
						<xsd:element name="INSPAFTDEL" type="tns:char1"/>
						<xsd:element name="REF_ACTGR" type="tns:char4"/>
						<xsd:element name="PLANT" type="tns:char4"/>
						<xsd:element name="DME_IND" type="tns:char1"/>
						<xsd:element name="INSTR_KEY" type="tns:char2"/>
						<xsd:element name="DATA_TRANS" type="tns:char1"/>
						<xsd:element name="ASSIGN_HI" type="tns:numeric2"/>
						<xsd:element name="PMNT_BLOCK" type="tns:char1"/>
						<xsd:element name="LABCUSTGRP" type="tns:char10"/>
						<xsd:element name="NON_MILIT" type="tns:char1"/>
						<xsd:element name="MILIT_USE" type="tns:char1"/>
						<xsd:element name="CUST_COND_GRP1" type="tns:char2"/>
						<xsd:element name="CUST_COND_GRP2" type="tns:char2"/>
						<xsd:element name="CUST_COND_GRP3" type="tns:char2"/>
						<xsd:element name="CUST_COND_GRP4" type="tns:char2"/>
						<xsd:element name="CUST_COND_GRP5" type="tns:char2"/>
						<xsd:element name="ALTPAYERAC" type="tns:char1"/>
						<xsd:element name="TAX_TYPE" type="tns:char2"/>
						<xsd:element name="TAX_NO_TY" type="tns:char2"/>
						<xsd:element name="TAX_NO_3" type="tns:char18"/>
						<xsd:element name="TAX_NO_4" type="tns:char18"/>
						<xsd:element name="NO_ICMS" type="tns:char1"/>
						<xsd:element name="NO_IPI" type="tns:char1"/>
						<xsd:element name="SUBT_GRP" type="tns:char3"/>
						<xsd:element name="CFOP_CAT" type="tns:char2"/>
						<xsd:element name="TAXLAWICMS" type="tns:char3"/>
						<xsd:element name="TAXLAWIPI" type="tns:char3"/>
						<xsd:element name="BCW" type="tns:char1"/>
						<xsd:element name="NUCL_NONP" type="tns:char1"/>
						<xsd:element name="NATL_SEC" type="tns:char1"/>
						<xsd:element name="MISS_TECH" type="tns:char1"/>
						<xsd:element name="SALES_BLKG" type="tns:char2"/>
						<xsd:element name="URL" type="tns:char132"/>
						<xsd:element name="REP_NAME" type="tns:char10"/>
						<xsd:element name="BUS_TYPE" type="tns:char30"/>
						<xsd:element name="IND_TYPE" type="tns:char30"/>
						<xsd:element name="CONF_ST" type="tns:char1"/>
						<xsd:element name="CONF_DATE" type="tns:date10"/>
						<xsd:element name="CONF_TIME" type="tns:time"/>
						<xsd:element name="NO_DELETE" type="tns:char1"/>
						<xsd:element name="CONSUMER" type="tns:char1"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="BAPICUSTOMER_04">
					<xsd:sequence>
						<xsd:element name="CUSTOMER" type="tns:char10"/>
						<xsd:element name="NAME" type="tns:char35"/>
						<xsd:element name="NAME_2" type="tns:char35"/>
						<xsd:element name="NAME_3" type="tns:char35"/>
						<xsd:element name="NAME_4" type="tns:char35"/>
						<xsd:element name="CITY" type="tns:char35"/>
						<xsd:element name="DISTRICT" type="tns:char35"/>
						<xsd:element name="PO_BOX" type="tns:char10"/>
						<xsd:element name="POBX_PCD" type="tns:char10"/>
						<xsd:element name="POSTL_CODE" type="tns:char10"/>
						<xsd:element name="REGION" type="tns:char3"/>
						<xsd:element name="COUNTYCODE" type="tns:char3"/>
						<xsd:element name="CITY_CODE" type="tns:char4"/>
						<xsd:element name="STREET" type="tns:char35"/>
						<xsd:element name="TELEPHONE" type="tns:char16"/>
						<xsd:element name="COUNTRY" type="tns:char3"/>
						<xsd:element name="COUNTRYISO" type="tns:char2"/>
						<xsd:element name="POBX_CTY" type="tns:char35"/>
						<xsd:element name="LANGU" type="tns:lang"/>
						<xsd:element name="LANGU_ISO" type="tns:char2"/>
						<xsd:element name="SORT_FLD" type="tns:char10"/>
						<xsd:element name="MATCHCODE1" type="tns:char25"/>
						<xsd:element name="MATCHCODE2" type="tns:char25"/>
						<xsd:element name="MATCHCODE3" type="tns:char25"/>
						<xsd:element name="FORMOFADDR" type="tns:char15"/>
						<xsd:element name="TELEBOX" type="tns:char15"/>
						<xsd:element name="TELEPHONE2" type="tns:char16"/>
						<xsd:element name="TELETEX" type="tns:char30"/>
						<xsd:element name="TELEX" type="tns:char30"/>
						<xsd:element name="TRANSPZONE" type="tns:char10"/>
						<xsd:element name="NIELSEN_ID" type="tns:char2"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="ZSSD_WEB_CUST_EXTRA">
					<xsd:sequence>
						<xsd:element name="CUSTOMERTYPE" type="tns:char15"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="BAPIRET2">
					<xsd:sequence>
						<xsd:element name="TYPE" type="tns:char1"/>
						<xsd:element name="ID" type="tns:char20"/>
						<xsd:element name="NUMBER" type="tns:numeric3"/>
						<xsd:element name="MESSAGE" type="tns:char220"/>
						<xsd:element name="LOG_NO" type="tns:char20"/>
						<xsd:element name="LOG_MSG_NO" type="tns:numeric6"/>
						<xsd:element name="MESSAGE_V1" type="tns:char50"/>
						<xsd:element name="MESSAGE_V2" type="tns:char50"/>
						<xsd:element name="MESSAGE_V3" type="tns:char50"/>
						<xsd:element name="MESSAGE_V4" type="tns:char50"/>
						<xsd:element name="PARAMETER" type="tns:char32"/>
						<xsd:element name="ROW" type="xsd:int"/>
						<xsd:element name="FIELD" type="tns:char30"/>
						<xsd:element name="SYSTEM" type="tns:char10"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="ZTSD_WEB_GET_CUSTOMER_DATA">
					<xsd:sequence>
						<xsd:element name="item" type="tns:ZSSD_WEB_GET_CUSTOMER_DATA" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:complexType name="BAPIRET2_T">
					<xsd:sequence>
						<xsd:element name="item" type="tns:BAPIRET2" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
				<xsd:element name="Z_WEB_GET_CUSTOMER_DATA">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="IV_CUSTOMER" type="tns:char10" minOccurs="0"/>
							<xsd:element name="IV_CUSTOMER_EXTERNAL" type="tns:char10" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Z_WEB_GET_CUSTOMER_DATAResponse">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ET_CUSTOMER_DATA" type="tns:ZTSD_WEB_GET_CUSTOMER_DATA"/>
							<xsd:element name="ET_RETURN" type="tns:BAPIRET2_T"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:schema>
		</wsdl:types>
		<wsdl:message name="Z_WEB_GET_CUSTOMER_DATA">
			<wsdl:part name="parameters" element="tns:Z_WEB_GET_CUSTOMER_DATA"/>
		</wsdl:message>
		<wsdl:message name="Z_WEB_GET_CUSTOMER_DATAResponse">
			<wsdl:part name="parameter" element="tns:Z_WEB_GET_CUSTOMER_DATAResponse"/>
		</wsdl:message>
		<wsdl:portType name="ZES_GET_CUSTOMER_DATA">
			<wsdl:documentation>
				<sapdoc:sapdoc xmlns:sapdoc="urn:sap:esi:documentation">
					<sapdoc:docitem applicationComponent="SD"/>
				</sapdoc:sapdoc>
			</wsdl:documentation>
			<wsp:Policy>
				<wsp:PolicyReference URI="#IF_IF_ZES_GET_CUSTOMER_DATA"/>
			</wsp:Policy>
			<wsdl:operation name="Z_WEB_GET_CUSTOMER_DATA">
				<wsp:Policy>
					<wsp:PolicyReference URI="#OP_IF_OP_Z_WEB_GET_CUSTOMER_DATA"/>
				</wsp:Policy>
				<wsdl:input message="tns:Z_WEB_GET_CUSTOMER_DATA"/>
				<wsdl:output message="tns:Z_WEB_GET_CUSTOMER_DATAResponse"/>
			</wsdl:operation>
		</wsdl:portType>
	</wsdl:definitions>

Is it possible to see what feature is not available in .Net Core and what can be done about it or what the timeframe is for getting it?
Or is there something specific I can ask the SAP team to change on their side? It's SAP R/3, which I believe is fairly old.

**Comment by kayakingcoder** [comment]
For the record, I continued porting the Framework 4.6 version into .Net Core and despite the above warning, the Core app can call the SAP web service successfully.

**Comment by dasetser** [comment]
@kayakingcoder I believe you can ignore this warning in this case if it's working for you. It looks like it's showing up because your wsdl does not contain any information about your endpoint. Normal svcutil.exe doesn't generate a config file for this wsdl for the same reason, it just generates as much as it can and doesn't give you a warning about it.

In dotnet-svcutil we filter out anything that isn't compatible with .NET Core, and we spit out a warning if we don't find any endpoints afterwards (in case you were expecting us to generate code related to endpoints that aren't compatible). This just means you'll need to add the information about the binding and endpoint in code yourself, which it sounds like you were already doing on your .NET 4.6 client.

So I think in this case the warning message is correct that no endpoints compatible with .NET Core were found, but in reality there weren't any endpoints at all found.

**Comment by Lxiamail** [comment]
Please let us know if there is more WCF product related issue.

**Comment by AlpeshValvi123** [comment]
Importing web service metadata ...
Number of service endpoints found: 0
Scaffolding service reference code ...
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Updating project ...
Done.


**Getting this error while adding service(SAO WSDL) to the class library.**

**Comment by HstAdmin** [comment]
Importing web service metadata ...
Number of service endpoints found: 0
Scaffolding service reference code ...
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Updating project ...
Done.

Getting this error while adding WCF Service, Please help
