### ISSUE TITLE
Although I have granted the current user corresponding permission, on my client side, it still prompts me that the process doesn't have the right access rights for the certificate private key.

### ISSUE THREAD

**Issue by YonglianQian** [dotnet/wcf#3567]
Hi Product owner,
I ran into a problem when I used the below official document to use a certificate to authenticate the client.
Content: [https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/message-security-with-a-certificate-client:](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/message-security-with-a-certificate-client) 
On two virtual machines, I built a WCF application using certificates to authenticate each other based on message security. I created a WCF application on a vabqia593vm host, and hosted it on IIS, as shown in the above official example.
I consume this WCF application in the console program by adding a service reference on the vabqia864vm host.
The configuration file refers fully to the above official page configuration.
Also, I used Powershell command **New-selfsignedcertificate** to create two self-signed certificates for each machine.
```
New-SelfSignedCertificate -CertStoreLocation cert:\LocalMachine\My -DnsName "vabqia593vm"
New-SelfSignedCertificate -CertStoreLocation cert:\LocalMachine\My -DnsName "vabqia864vm" -KeyUsage KeyEncipherment,DigitalSignature
```

On both certificates, I added some users to manage private key, such as Everyone, IIS_IUSRS, network service, in the certificate management interface(certlm.msc), but on the client side, the console application still prompted that the process might not have permission to access the certificate private key.
Feel free to let me know if you need more details.

**Comment by Lxiamail** [comment]
@YonglianQian I'm wondering if you enable export permission when you import the cert to cert store?

**Comment by YonglianQian** [comment]
@Lxiamail I didn't import the cert to cert store since the command automatically generated the cert to localmachine store(certlm.msc), and I set up the cert by the below code snippets in two projects. 
**Server** 
`          <serviceCredentials>
            <serviceCertificate storeLocation="LocalMachine" storeName="My" x509FindType="FindByThumbprint" findValue="869f82bd848519ff8f35cbb6b667b34274c8dcfe"/>
          </serviceCredentials>
        </behavior>
      </serviceBehaviors>`
**Client.**
` <behaviors>
        <endpointBehaviors>
          <behavior name="myendpointbehavior">
            <clientCredentials>
              <clientCertificate findValue="9ee8be61d875bd6e1108c98b590386d0a489a9ca" storeLocation="LocalMachine" storeName="My" x509FindType="FindByThumbprint"/>
            </clientCredentials>`
Besides, I manage the private key permission of the cert in the following GUI(it's not the actual cert in the screenshot).
![04251](https://user-images.githubusercontent.com/21968523/56704842-4a624480-6741-11e9-8972-b17873b2aeb8.PNG)
![image](https://user-images.githubusercontent.com/21968523/56704815-2e5ea300-6741-11e9-8cc4-4c1291782c46.png)
Feel free to let me know if there is anything I can help with.
Regards

**Comment by Lxiamail** [comment]
@YonglianQian , This repo is for WCF Client on .NET Core, not for full .NET Framework. Since you already reported the same issue on Doc repro. Let's use it to track the issue. Closing this one.
