### ISSUE TITLE
WCF FaultException<T> - .NET Core 2.2

### ISSUE THREAD

**Issue by Henkolicious** [dotnet/wcf#3568]
I belive my other issue: https://github.com/dotnet/docs/issues/11786 should be posted here.

**Comment by Lxiamail** [comment]
@Henkolicious Looks like both FaultException and FaultContractAttribute are exposed in WCF Core public surface. What's the problem that you ran into?

**Comment by Henkolicious** [comment]
@Lxiamail it's simply the error handling during a try/catch/catch block.
<pre>
try {
   _client.getData(); // server throws an error of type MyErrorType as the fault contract specifies
}
catch(FaultException< MyErrorType> e)
{
   // this never triggers in .NET Core
   // but it does work fine in .NET Framework 4.x.x
}
catch(Exception e)
{
   // always end up here in .NET Core
}
</pre>

The code is equivalent in my sample tests (Core vs Framework 4.x.x)

**Comment by Lxiamail** [comment]
```c#
[WebInvoke(
      Method = "GET",
      UriTemplate = "/GetData?foo={foo}",
      BodyStyle = WebMessageBodyStyle.Bare,
      RequestFormat = WebMessageFormat.Json,
      ResponseFormat = WebMessageFormat.Json)]
ExpectedResultType GetData(int foo);
```
@Henkolicious WebInvoke attribute is not supported on WCF Core since WSHttpBinding is not supported. That may be why that you got different exception. BTW, what exception that you got?

**Comment by romuloteixeira** [comment]
The same issue, Isn't possible reference System.ServiceModel.Web (WebInvoke) on .Net Standard 2.0.

**Comment by romuloteixeira** [comment]
> ```cs
> [WebInvoke(
>       Method = "GET",
>       UriTemplate = "/GetData?foo={foo}",
>       BodyStyle = WebMessageBodyStyle.Bare,
>       RequestFormat = WebMessageFormat.Json,
>       ResponseFormat = WebMessageFormat.Json)]
> ExpectedResultType GetData(int foo);
> ```
> 
> @Henkolicious WebInvoke attribute is not supported on WCF Core since WSHttpBinding is not supported. That may be why that you got different exception. BTW, what exception that you got?

Hi,
I got it these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Web' does not exist in the namespace 'System.ServiceModel' (are you missing an assembly reference?)	ProjectName(netstandard2.0)	c:\xxxxx\Iyyyyyy.cs	2	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'WebInvokeAttribute' could not be found (are you missing a using directive or an assembly reference?)	ProjectName(netstandard2.0)	c:\xxxxx\Iyyyyy.cs	17	Active


`using System.ServiceModel;
using System.ServiceModel.Web;

namespace ProjectName
{
    [ServiceContract]
    public interface Iyyyyyyy
    {
        [OperationContract]
        [WebInvoke(UriTemplate = "/zzzzz", Method = "POST", ResponseFormat = WebMessageFormat.Json)]
        ssssssResponse yyyyyyyy(ssssssRequest input);
    }
}`

**Comment by HongGit** [comment]
@Henkolicious WebInvoke attribute is not supported on WCF Core since WebHttpBinding is not supported.
