### ISSUE TITLE
Why timeout helper not passed to GetStreamAsync()

### ISSUE THREAD

**Issue by BogdanovKirill** [dotnet/wcf#3590]
Hi all,

I'm trying to understand why my application sometimes hangs when working with WCF (net core 2.2). I'm using HttpTransportBindingElement with TransferMode equal to StreamedResponse.
And the question is, why timeoutHelper is not used in GetStreamAsync() here ? 
https://github.com/dotnet/wcf/blob/f0b35d2f8d8352082d1e4f4f413db62b24e25ec5/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs#L299
Where is guarantee that we will not hang here because of a network error ?
Let me give some additional info. Here we say that we don't need timeout for HttpClient:
https://github.com/dotnet/wcf/blob/f0b35d2f8d8352082d1e4f4f413db62b24e25ec5/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L358
Then we say that only response headers should be read:
https://github.com/dotnet/wcf/blob/f0b35d2f8d8352082d1e4f4f413db62b24e25ec5/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L1024
So, response's body should be read manually by ReadAsync/PreReadBufferAsync in GetStreamAsync() method and we don't have any protection from network timeouts. I'm right?

**Comment by mconnew** [comment]
@BogdanovKirill, sorry for the crickets. I think you have found a bug.

**Comment by mconnew** [comment]
@BogdanovKirill, the issue is limited to a problem with receiving the first first buffer of content of the response body. Once the receive buffer has been filled once at the beginning, the timeout is being used. So basically the failure mode is the server sends the response headers fine, but doesn't send any response body. I have a fix I'll have out for PR very soon.

**Comment by mconnew** [comment]
@BogdanovKirill, could you take a look at #3709 to see if it looks like it addresses the problem you found? BTW, thank you for spending the time to pinpoint where the bug in the code was as this would have been difficult to find without a local repro.

**Comment by BogdanovKirill** [comment]
@mconnew 
Thank you very much for feedback, fix looks right to me. I think we could checkt it in real environment on test instances.

**Comment by mconnew** [comment]
@BogdanovKirill, I've merged the change. Feel free to reopen this issue if it doesn't fix your problem. 
@StephenBonikowsky, are we pushing nightly builds to myget at the moment?

**Comment by StephenBonikowsky** [comment]
We are no longer using MyGet since they couldn't accommodate our storage needs.
Let me look into the best way to make these packages available, I'll update this Issue.

**Comment by StephenBonikowsky** [comment]
Here are the packages produced by the build with @mconnew's changes.
[PackageArtifacts.zip](https://github.com/dotnet/wcf/files/3336645/PackageArtifacts.zip)

**Comment by BogdanovKirill** [comment]
@StephenBonikowsky 

Thank you!

**Comment by BogdanovKirill** [comment]
@mconnew 

Hello! Sorry, but we have troubles again here. It seems that in StreamedResponse mode bug still exists.
Could you check this line please:
https://github.com/dotnet/wcf/blob/61aacede5002f4f191fcbc4d80830eb129cd83ac/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs#L310
Is it possible to stuck here because of infinite timeout in HttpClient ?

**Comment by BogdanovKirill** [comment]
It seems that ReadAsStreamAsync will call:
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L453
And then:
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L377
So, can we stuck here because of empty cancellation token here?
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L385
?

**Comment by mconnew** [comment]
The non-obvious thing you are missing is that you are looking at the base `HttpContent` class. The actual class derived from `HttpContent` that you will get is `System.Net.Http.HttpConnectionResponseContent`. The method `CreateContentReadStreamAsync` is virtual, and the actual implementation that will run can be found [here](https://github.com/dotnet/corefx/blob/release/3.1/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionResponseContent.cs#L57). As you can see, it has no ability to wait indefinitely as it returns a `Stream` object which was already created. It's actually a synchronous implementation with no blocking or waiting.

**Comment by BogdanovKirill** [comment]
Thank you very much for explanation, you are absolutely right. I should continue my research then.
