### ISSUE TITLE
SelfHostWcfService should not place build artifacts in src/ tree

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#36]
When building the SelfHostWcfService at src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfService.csproj, the build artifacts (bin/ and obj/) are placed in same directory as the csproj file, polluting the tree. `.gitignore` will prevent the build artifacts from getting committed. 

Consider changing the project file to write binaries and build artifacts for SelfHostWcfService in the bin/ directory of the repo root.

**Comment by roncain** [comment]
This also applies to runtime generated artifacts.  For example, the .svclog should definitely not be created under the src folder.  When fixing this issue, also ensure .gitignore will ignore .svclog files

**Comment by zhenlan** [comment]
@roncain, has your recent change fixed this already?

**Comment by roncain** [comment]
No, but it has enabled it.  The wcf.targets at the root defines the property $(WcfToolsOutputPath) that needs to be used by all "tools" projects as their $(OutputPath).  The property $(BridgeResourceFolder) defines where resources should be placed that are intended to be used by the Bridge.  When the Bridge has been checked in, I can modify the necessary projects to make them follow these conventions.

**Comment by roncain** [comment]
This was resolved when #202 was merged.  It made the WCF service project build to a location defined by TestProperties, and it made the Bridge fetch it from there.
