### ISSUE TITLE
.NET 5 support and self hosted servers?

### ISSUE THREAD

**Issue by KarloX2** [dotnet/wcf#3607]
Hi !

I read about Microsofts plans for .NET 5 and I understand that they will discontinue WCF !!

I found this repro and I have two questions:

1. Does this project intends to support .NET 5 and evolve to a full replacement? (What is needed is nettcp + soap + sw-* client+server, duplex/callbacks.)?

2. Is this project based on the original WCF source codes or is it a new implementation?

Thanks!
Karlo

**Comment by BhaaLseN** [comment]
And don't forget about named pipes for interprocess communication, or MSMQ.

**Comment by StephenBonikowsky** [comment]
@KarloX2 
This repo is based on the desktop implementation of WCF, however; it is only the client side of WCF and not all features are supported. We add features from the desktop implementation based on community feedback and as time permits as we are not a large team.

To see what is supported see the release docs...
https://github.com/dotnet/wcf/tree/master/release-notes

This repo is not part of .NET Core but depends on it, think of it as a third party repo built on top of .NET Core. So we will work on top of .NET 5 as well.

As for the WCF Server side, there are no plans for it to be included as part of this repo. There is a lot of interest in server side and you can follow the ongoing discussion in #2695 particularly comments made recently in there by @mconnew 

I hope this answered your questions.
