### ISSUE TITLE
How to share common types from 2 services?

### ISSUE THREAD

**Issue by philip-reed** [dotnet/wcf#3608]
With a .Net Framework project, you used to be able to share types from common WCF services by adding any additional services to the Reference.svcmap file as follows:

[![add metadata source][1]][1]

Source:
[https://cgeers.wordpress.com/2011/07/31/wcf-sharing-types-using-svcmap/][2]

Now, with .net core, we have connected services, and all we get is a `ConnectedService.json` file that looks like this:

    {
        "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
      "Version": "15.0.30311.775",
      "ExtendedData": {
        "inputs": [
          "http://hostname/appname/ExampleService.svc"
        ],
        "collectionTypes": [
          "System.Array",
          "System.Collections.Generic.Dictionary`2"
        ],
        "namespaceMappings": [
          "*, ExampleService"
        ],
        "targetFramework": "netstandard2.0",
        "typeReuseMode": "None"
      }
    }

See:
[https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide][3]

Does anyone know how to do the same with the connectedservice.json / SVCUTIL?

Note, the types are built from WSDL entirely, there are no referenced assemblies from which to share types.

  [1]: https://i.stack.imgur.com/twLkl.png
  [2]: https://cgeers.wordpress.com/2011/07/31/wcf-sharing-types-using-svcmap/
  [3]: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide

**Comment by dasetser** [comment]
The WCF Connected Service does not support a feature like this where you can create a single service reference for two different services and share the types automatically. If you need to avoid using the two different objects that are generated the only options I can think of are:
1) Manually modify the service references after generation so both proxy classes use the same copy.
2) After generating the first service reference manually move the generated classes to a reference that you can tell the tool to reuse types from.
