### ISSUE TITLE
System.Xml.Serialization.XmlChoiceIdentifierAttribute is not valid in Item (.Net Core Client)

### ISSUE THREAD

**Issue by michisnewsletter** [dotnet/wcf#3615]
The "svcutil" generates der References.cs file (Visual Studio 15.9, .net core 2.2) within "Connected Services".

It also generate this Line:
```
[System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.org.at/genehmigung_svc/V2013_01", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item;
```

I get this error message:
`XmlSerializer attribute System.Xml.Serialization.XmlChoiceIdentifierAttribute is not valid in Item. Only XmlElement, XmlArray, XmlArrayItem, XmlAnyAttribute and XmlAnyElement attributes are supported when IsWrapped is true`

When i uncommited the second Line, it is possible to call another function from the endpoints.

Is this in .Net Core 2.2 not supported ?
Is it supportet in .net core 3.0

Here are the generated files from "svcuitil"
[ConnectedService.json.txt](https://github.com/dotnet/wcf/files/3159401/ConnectedService.json.txt)
[Reference.cs.txt](https://github.com/dotnet/wcf/files/3159402/Reference.cs.txt)

**Comment by dasetser** [comment]
@michisnewsletter Can you attach the .wsdl file you are using? It would help us reproduce the issue so we can see why this is happening.

**Comment by StephenBonikowsky** [comment]
Without the wsdl we can't create a repro.
