### ISSUE TITLE
Getting an error trying to add a new Web Service reference to my c# project in VS2019

### ISSUE THREAD

**Issue by perharjnk** [dotnet/wcf#3648]
I am not able to add new Web Service references to my C# project. Visual Studio 2019 fails to open the dialog to add the Web Service.

When I launch the Add Connected Services option in my .NET 4.7.2 C# project, and try to add a SOAP Web Service reference using the "Microsoft WCF Web Service Reference Provider", instead of showing the dialog to add the Web Service reference, it shows an alert message with the following error:

**The connected services component 'Microsoft WCF Web Service Reference Provider' failed: The project reference specification 'Microsoft.Csharp' does not have a file path.**

BTW, even though this is a regular .NET framework assembly project, I am using the new .NET SDK style project file. Also, it works fine for the first web service reference that I add. Any further attempts to add more web service references cause this error!

**Comment by dasetser** [comment]
Thanks for the information. This sounds like it's the same problem reported in [this feedback](https://developercommunity.visualstudio.com/content/problem/526584/connected-services.html), which we're currently working on a fix for. You can work around it by using the tool on a .NET Core/.NET Standard project and copying the Service Reference folder to your full framework project.

**Comment by perharjnk** [comment]
Yes. That is what I ended up doing for now. Thanks.

**Comment by StephenBonikowsky** [comment]
@dasetser Is there an issue you could link to this one for the fix you referenced working on? Then close this issue.

**Comment by dasetser** [comment]
[Feedback 526584](https://developercommunity.visualstudio.com/content/problem/526584/connected-services.html) is what we'll update once this fix is released. I'll close this issue, but anyone looking for updates can follow the feedback item.
