### ISSUE TITLE
Clean up certificates installed by BridgeClient 

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#365]
For x-machine testing, BridgeClient will necessarily install certificates on the client machine for HTTPS/TCP+SSL testing. 

However, the cleanup logic currently does not exist in the BridgeClient. 

Investigate and implement a way to clean up certificates on a BridgeClient. For example, use an executable that runs as part of test cleanup

**Comment by roncain** [comment]
Done in PR #499 and #501
