### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Negotiate, NTLM' 

### ISSUE THREAD

**Issue by mkalkere** [dotnet/wcf#3650]
I see all the issues related to this are closed but I still get the error :  _**The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Negotiate, NTLM'**_ when I am trying to access the WCF service(which requires NTLM authentication) from .net core. 

**WCF service binding**
`<basicHttpBinding>

        <binding ........>

          <readerQuotas ........ />

                <security mode="TransportCredentialOnly">
                <transport clientCredentialType="Ntlm" />

            </security>

        </binding>

      </basicHttpBinding>`

I tried the below solutions/workarounds mentioned below and nothing works.

1. AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
2. Setting the client credential to System.Net.CredentialCache.DefaultNetworkCredentials;
3. Rolling back the System.ServiceModel.* references to the previous version (4.4.2)

**It works when I provide the credentials explicitly as below:**
`client.ClientCredentials.Windows.ClientCredential = new NetworkCredential("userName", "password", "domain");`

I am using .Net core 2.2 and 4.5.3 for System.ServiceModel.* dll references

_Note:_ WCF calls work fine for bindings where `<security mode="None"/>`

I can provide the additional info if required.

**Comment by mkalkere** [comment]
Ok. So here is an update, I managed to find a workaround for this error by changing the  _clientCredentialType_ from **Ntlm** to **Windows**

```
<binding ........>
      <readerQuotas ........ />
            <security mode="TransportCredentialOnly">
            <transport clientCredentialType="Windows" />
        </security>
</binding>
```
This works.

**Comment by towhidJ** [comment]
I know this question is old, but the solution to my application, was different to the already suggested answers. If anyone else like me still have this issue, and none of the above answers works, this might be the problem solution:

```
var binding = new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly);
    // Configure transport security
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
binding.Security.Transport.ProxyCredentialType = HttpProxyCredentialType.Windows;
binding.Security.Transport.Realm = "";

// Configure message security
binding.Security.Message.ClientCredentialType = BasicHttpMessageCredentialType.UserName;

binding.MaxReceivedMessageSize = 10485760; //10MB limit
EndpointAddress endpointAddress = new EndpointAddress(SSRSReportExecutionUrl);

//Create the execution service SOAP Client
var rsExec = new ReportExecutionServiceSoapClient(binding, endpointAddress);




if (rsExec.ClientCredentials != null)
{

    rsExec.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Impersonation;
    // rsExec.ClientCredentials.Windows.ClientCredential = clientCredentials;
    rsExec.ClientCredentials.UserName.UserName = "Your PC Login USERNAME";
    rsExec.ClientCredentials.UserName.Password = "Your PC Login PASSWORD";
}

//This handles the problem of "Missing session identifier"
rsExec.Endpoint.EndpointBehaviors.Add(new ReportingServicesEndpointBehavior());

await rsExec.LoadReportAsync(null, "/" + "YOUR_REPORT_FOLDER_PATH"+ "/" + "REPORT_NAME", null);
```
This is solution
