### ISSUE TITLE
Server Side WCF in .NET Core

### ISSUE THREAD

**Issue by sravansurabhi** [dotnet/wcf#3651]
We have huge Implementations of WCF. Organization is under taking initiative to modernize the legacy applications. There is no equivalent of WCF in .NET Core.

Describe the solution you'd like

Build automated conversion procedure for WCF migration to ASP.NET Web API

**Comment by StephenBonikowsky** [comment]
@sravansurabhi 
This repo implements WCF client side features.
Server side implementation is not currently available in .NET Core, see this ongoing discussion about the server side, #2695 

An automated process for migrating from WCF to ASP.NET Web API would be cool, but not really feasible.
