### ISSUE TITLE
Can I consume .net WCF service in .net core on a Linux system？？？

### ISSUE THREAD

**Issue by White99** [dotnet/wcf#3652]
I am doing a project migration, from .netframework to .netcore in order to run on a Linux system, but the client code generated by the "add reference "  , which cannot be run on the Linux system(service.model.* is not organization). Is there anyone can solve it?
Thanks!

**Comment by dasetser** [comment]
@White99 Add Service Reference will generate code for the full .NET Framework. You'll want to use one of our tools that generate code for .NET Core. 

[WCF Web Service Reference Provider](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide) is a UI tool included in Visual Studio. You can also use the command line tool [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x).

**Comment by sinistram** [comment]
@dasetser do you mean that the same code for WCF communication will work in both Windows and Linux oses?
