### ISSUE TITLE
dotnet-svcutil: Generate classes with [SerializableAttribute] opt-in

### ISSUE THREAD

**Issue by stukselbax** [dotnet/wcf#3656]
We have SOAP client which works with vSphere ESX(i) infrastructure, generated with wsdl.exe for .net framework. Currently we are trying to migrate the client to .netstandard2.0 in order to use it with .netcoreapp2.x.

One of program has used `BinaryFormatter` in order to store objects of generated classes. It works on .net framework because generated classes have [SerializableAttribute] specified on it. But classes generated using "Add Connected Services" didn't decorate classes with this attributes.

Thus we have to set [SerializableAttribute] on every class generated in order to make it work. We have to deal with it because the program persists resulted stream and later uses it to deserialize data.

Could you please provide an option --serializable like [svcutil /serializable](https://docs.microsoft.com/en-us/dotnet/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe#code-generation) switch?

_(Just for fun: here is the [wsdl](https://github.com/vmware/vsphere-automation-sdk-.net/blob/master/wsdl/vim-service/vimService.wsdl) used to generate client - git clone and try;)_

**Comment by StephenBonikowsky** [comment]
@stukselbax Thank you for the feedback, that is a reasonable request but we would not be able to get to it in the short term. We will put it in our list of things to do in a future release.

@mconnew brought up that as a workaround you could create a partial class for the classes that you need to decorate with the Serializable attribute. Matt, do you have anything you would like to add?

**Comment by stukselbax** [comment]
This workaround which I have used, but instead of manually decorate partial classes the program was written to walk the object graph and decorate every class with `[Serializable]`. Turns out that there are ~2000 classes require the attribute.

If the [utility was open source](3191), community could contribute.

**Comment by StephenBonikowsky** [comment]
@stukselbax we have taken some initial steps to make it open source. We will use #3191 to track this work.
Thanks.
