### ISSUE TITLE
Use fully quallified Types incuding global:: when generating Client

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/wcf#3667]
Generating a Client will output code like this:
```c#
 /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uri.seeburger.com/seefx/sendFile")]
    public partial class System
    {
        //...
    }
```

However if the service someone consumes uses the name `System`, it will produce build errors. Since `System` is not interpreted as the namespace but as the class. Like in the example above.

Not sure there are other names that would make problems.

A solution would be to generate the `global` keyword.

```c#
    /// <remarks/>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uri.seeburger.com/seefx/sendFile")]
    public partial class System
    {
        //...
    }
```

**Comment by StephenBonikowsky** [comment]
Thanks for your feedback @LokiMidgard 
It doesn't seem like having a class named System is a very good idea, however, you are correct.
I also don't think I've ever seen this brought up before, svcutil.exe has been around for quite a long time.

@dasetser Do you have any feedback on this?

**Comment by dasetser** [comment]
We investigated adding this to the full framework version of svcutil.exe in the past. The conclusion of that investigation was that we were unable to find a way to add this in all scenarios without causing regressions. 

We haven't specifically looked into this for dotnet-svcutil, but I would think the result would likely be the same.

**Comment by mconnew** [comment]
Could we instead create the class with a name other than System? We don't have a requirement to have the class name match the xsd type name. In fact, the class name isn't ever used unless it's a top level object being serialized as the xml element tag used is the name of the property which is of that type.

**Comment by StephenBonikowsky** [comment]
@mconnew This is too low a priority relative to other work we have in WCF Core.
