### ISSUE TITLE
GUI doesn't generate Proxy when there are minor issues with WSDL, but dotnet svcutil does.

### ISSUE THREAD

**Issue by lemoinem** [dotnet/wcf#3675]
The following WSDL can be imported in VS2015 using "Add Web Reference" or "Add Service Reference", but cannot be imported using VS2019's "Connected Services, WCF Web Service Reference".

http://www.mcommunicator.ru/m2m/m2m_api.asmx?WSDL

Error:
```
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:binding[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpPost']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:service[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_API']/wsdl:port[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpPost']
Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:portType[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpPost']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:binding[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpPost']
Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:portType[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpPost']
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:binding[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpGet']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:service[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_API']/wsdl:port[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpGet']
Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:portType[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpGet']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:binding[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpGet']
Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: Referenced type 'http://schemas.xmlsoap.org/soap/encoding/:Array' is only valid for encoded SOAP.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://mcommunicator.ru/M2M']/wsdl:portType[@name='MTS_x0020_Communicator_x0020_M2M_x0020_XML_x0020_APIHttpGet']
There was an error verifying some XML Schemas generated during export:
Undefined complexType 'http://schemas.xmlsoap.org/soap/encoding/:Array' is used as a base for complex type restriction.
```

The error seems similar to what was mentioned in https://github.com/dotnet/wcf/issues/3157 and https://github.com/dotnet/wcf/issues/3327

But since legacy tools (namely Web References and Service References) supported these WSDL, I was curious as to how I could use it in new Apps?

Note: dotnet svcutil (https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) seems to generate valid code, despite giving out the same errors. Should this be considered the correct way to load such WSDL?

**Comment by StephenBonikowsky** [comment]
@dasetser Could you provide @lemoinem some guidance on this?

**Comment by dasetser** [comment]
@lemoinem It looks like you're running into the same problem as the two issues you linked. The proxy you get from dotnet-svcutil will be a best effort to generate it through the error, so the parts that it generated should work, but some elements may not have been generated. Taking a quick look at what dotnet-svcutil generated I think it handled it correctly.

You should be able to use the proxy from dotnet-svcutil and be okay. If you want to generate it without errors you can download the wsdl and run the tool on a modified version of the wsdl that does not use soapenc:Array. I believe if you change the StringArray definition to be similar to the ArrayOfString definition it would get rid of the errors.

**Comment by lemoinem** [comment]
I'll go with that (using the code generated by dotnet-svcutil, if there are any issue, I'll try to modify the wsdl myself). Thanks for the details and help.

I still think it would be a usability enhancement to allow the GUI to generate the proxy even when there are errors? It might help quite a bit to debug an erroneous WSDL...

**Comment by StephenBonikowsky** [comment]
@lemoinem We agree that would be a much better result. Moving to our backlog with higher priority.

Investigate why using the UI in VS is not producing the wsdl in spite of the errors since it just calls dotnet-svcutil under the covers, we would expect to get the same behavior.

**Comment by lemoinem** [comment]
Thanks, that will be a great help!
It it helps, as far as I can tell, the issue with the UI is that there is a Pre-processing/validation steps (when entering the WSDL path/URL and clicking on "Go").

If this validation step raises errors, the UI doesn't allow going through the next ones until the actual Proxy generation.

**Comment by imcarolwang** [comment]
I am able to generate proxy code for http://www.mcommunicator.ru/m2m/m2m_api.asmx?WSDL from `"Connected Services->Microsoft WCF Web Service Reference Provider"` tool on a test machine installed with Visual Studio 2019 - 16.10.0 Preview1.0, the generated code is the same as with running dotnet-svcutil (version2.0.2).  

So please try the scenario on a newer version of Visual Studio 2019, feel free to re-activate if you still see a problem.
