### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme .net core 2.1 with Service security model 4.5.3 authorization issue 

### ISSUE THREAD

**Issue by twu027** [dotnet/wcf#3677]
Hi, 
This is not a duplicated issue for me. Please don't close it without reading. Thanks!
I have searched everywhere online. Even the error message is the same but none of the fixes or workarounds worked for me.
This is my setup .net core 2.1 with Service security model 4.5.3 
I have been struggling to get it working to call an old WCF service we have (possibly written in .net framework 4.0). 

           var binding = new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly);
           binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
                
           var myEndpoint = new EndpointAddress("http://webappserviceframeworktest.asbbank.co.nz:9012/SuspendService.svc");

            var client = new SuspendServiceClient(binding, myEndpoint);

            client.ClientCredentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;

             client.ClientCredentials.Windows.ClientCredential = new NetworkCredential("username","password","domain");

            var r = client.ApplyAccountHoldAsync(blockAccountRequest).GetAwaiter().GetResult();

          

This error message I am getting is "The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'Negotiate, NTLM'."

if I change to `binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Ntlm;`
and provide explicit username password and domain
I got this strange error:
**Context Extension of type 'CommonMessageContext' failed to load with exception message 'Application name '' or namespace '' is blank.'. Refer to the inner exception for details.**

But if I don't provide username or password explicitly, I got the error:
"The HTTP request is unauthorized with client authentication scheme '**Ntlm**'. The authentication header received from the server was 'Negotiate, NTLM'."

I have tried all combinations, with or without explicit credentials, or 
` client.ClientCredentials.Windows.ClientCredential = CredentialCache.DefaultNetworkCredentials;`

with or without Impersonation setting.

None of them worked!
The WCF service on the server has this configuration which is pretty standard
`<security mode="TransportCredentialOnly">
            <transport clientCredentialType="Ntlm" />
</security>
`

**Comment by twu027** [comment]
Context Extension of type 'CommonMessageContext' failed to load with exception message 'Application name '' or namespace '' is blank.'. Refer to the inner exception for details. 
is the inner exception itself.

**Comment by twu027** [comment]
The exactly same code works without problem with .net framework 4.7.2

 var myBinding = new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly);
                myBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Ntlm;
                myBinding.Security.Transport.ProxyCredentialType = HttpProxyCredentialType.None;

                var myEndpoint =
                    new EndpointAddress("http://webappserviceframeworktest.asbbank.co.nz:9012/SuspendService.svc");

                var suspendService = new SuspendServiceClient_Proxy(myBinding, myEndpoint);
                var response = suspendService.ApplyAccountHold(blockAccountRequest);

**Comment by mconnew** [comment]
ImpersonationLevel doesn't do anything as HttpClient in .NET Core doesn't support it. I believe the behavior you get is Identification.  
Can you provide the stack trace for the exception mentioning CommonMessageContext? It's not coming from managed code as far as I can tell. What version of .NET Core are you using?  
Can you try adding the following right at the start of execution. I want to see if this is a problem with SocketsHttpHandler:
```c#
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

**Comment by twu027** [comment]
@mconnew Stacktrace below
  at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass7_0`1.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ASB.FraudMessage.Consumer.MessageProcessor.ProcessMessage(ConsumeResult`2 consumeResult) in C:\Users\dev.tonyw\Source\ASB.FraudMessage.Consumer\MessageProcessor.cs:line 49

**Comment by twu027** [comment]
@mconnew Hi Matt, also tried your suggestion, same authorization error.

"The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Negotiate, NTLM'.

**Comment by twu027** [comment]
@mconnew Hi Matt, thanks for your help and we have figured out the issue. At our server end, we have some customer headers which is causing this, that is not your code's issue. Issue closed.
