### ISSUE TITLE
Make `SslStreamSecurityBindingElement.RequireClientCertificate` public

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/wcf#3678]
I have the following config:

```xml
<customBinding>
  <binding name="bindingName">
    <binaryMessageEncoding compressionFormat="GZip" />
    <sslStreamSecurity requireClientCertificate="true" />
    <tcpTransport />
  </binding>
</customBinding>
```

I can't set this up the same way in .NET Core because `SslStreamSecurityBindingElement.RequireClientCertificate` is internal. However, if I change it to `true` in the debugger or via reflection, then it works just fine. Can this be made public?

**Comment by StephenBonikowsky** [comment]
@twsouthwick We'll take a look at this and see if that is something we can consider doing.

**Comment by mconnew** [comment]
This absolutely should be made public. It's an oversight that it isn't. I was going to suggest how to achieve this without reflection but I realized that we also haven't exposed BinaryMessageEncodingBindingElement.CompressionFormat so you will still be blocked. I presume you need us to expose CompressionFormat too? I just had a quick look over our implementation and it looks like it is complete so it should be ready to expose and add a scenario test for.

**Comment by StephenBonikowsky** [comment]
Adding to the current release.

**Comment by StephenBonikowsky** [comment]
@mconnew Looks like BinaryMessageEncodingBindingElement.CompressionFormat is already public, so just adding RequireClientCertificate to the public surface area.
