### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Negotiate, NTLM'.

### ISSUE THREAD

**Issue by efillion** [dotnet/wcf#3694]
Hi,

We have a bunch of WCF Services (.NET Framework 4.6.1) that need to be consumed by an ASP.NET Core (2.2 in IIS) client over an endpoint configured to use a custom binding with the Ntlm authorization scheme. Both WCF Service and the ASP.NET Core client are configured to use Windows Authentication with Negociate and NTLM as providers. Every time we try to consume the service, we have this error message: “The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Negotiate, NTLM'.” I have to say that I’ve tried almost every voodoo thing’s I’ve found on the Internet to solve this without success. Changing provider order on both sides didn’t have any effect. Even If I remove Negotiate in the client providers, it still sends Negociate in the message header (see attached screenshots).  I don’t understand why… The only way I can make this thing work is to remove the Negociate provider from the WCF Service. We need Negociate and NTLM so this is not a solution for us. I’m wondering if this is a bug or is there something I’m missing?

Thank you!

![fail - 1 - client NTLM only](https://user-images.githubusercontent.com/51968538/59712448-43a0fc80-91db-11e9-8672-955eccceba3a.PNG)
![fail - 2 - service Negociate, NTLM](https://user-images.githubusercontent.com/51968538/59712450-43a0fc80-91db-11e9-986a-4f1cbb1cdd8b.PNG)
![fail - 3 - Negociate in client header even if its not in its provider](https://user-images.githubusercontent.com/51968538/59712451-43a0fc80-91db-11e9-8893-c4d735d20d51.PNG)
![succes - 1 - client with negociate and ntlm](https://user-images.githubusercontent.com/51968538/59712452-43a0fc80-91db-11e9-82f0-e45ee67faead.PNG)
![succes - 2 - server NTLM only](https://user-images.githubusercontent.com/51968538/59712454-44399300-91db-11e9-8857-2a18cc7b69fe.PNG)
![succes - 3 - client negociate, ntlm and service ntlm only](https://user-images.githubusercontent.com/51968538/59712455-44399300-91db-11e9-9e86-6937a839fc17.PNG)

[BasicWcfFromCore.zip](https://github.com/dotnet/wcf/files/3306339/BasicWcfFromCore.zip)

**Comment by StephenBonikowsky** [comment]
@efillion I believe you have to set the ClientCredentialType to "Windows".
@mconnew Could you elaborate on why this is the case?

**Comment by mconnew** [comment]
According to the issue title, the server returned an authentication challenge of "Negotiate, NTLM". Negotiate basically means "Windows". We provide a CredentialCache to HttpClientHandler with the credentials limited to using the authentication scheme that you have configured to be used. This means when you set the ClientCredentialType to NTLM, HttpClientHandler can't use them to respond to a Negotiate challenge, even though Negotiate might actually used NTLM as the negotiated security package. I believe that HttpClientHandler has some differences in behavior compared to .NET Framework and HttpWebRequest where it won't use a secondary authentication challenge scheme if there are only credentials for that.

**Comment by efillion** [comment]
There’s no ClientCredentialType property in a custom binding but there’s an AuthenticationScheme that I can set to IntegratedWindowsAuthentication but it give me this error. The 'IntegratedWindowsAuthentication' authentication scheme has been specified on the HTTP factory. However, the factory only supports specification of exactly one authentication scheme. Valid authentication schemes are Digest, Negotiate, NTLM, Basic, or Anonymous.

I just want to point out something strange in the first error message. Usually, when we send validation error message, we always put in the value that we have received and those that we are expecting. With that in mind, Ntlm is different from NTML and fail in a case sensitive test. Can it be the problem?

**Comment by mconnew** [comment]
ClientCredentialType.Windows maps to AuthenticationSchemes.Negotiate. The `Ntlm` value is the output from calling ToString() on the provided AuthenticationSchemes value. We actually lowercase the AuthenticationSchemes value when we put it into the CredentialCache. When the credentials are retrieved from the CredentialCache, it does a case-insensitive comparison. This can be seen [here](https://github.com/dotnet/corefx/blob/v2.2.5/src/System.Net.Primitives/src/System/Net/CredentialCache.cs#L486). The limitation on not supporting IntegratedWindowsAuthentication was carried over from .NET Framework as we're trying to keep the same behavior. I need to give it some thought, but it might be possible to support this. IntegratedWindowsAuthentication is basically `(Ntlm | Negotiate)` in which case we could add it to the CredentialCache twice, once for each of them. I think the problem with supporting multiple is that it can't be expressed through a WSDL and I don't think that's an issue here.

**Comment by StephenBonikowsky** [comment]
Putting this into our backlog of issues to consider.
@efillion This is a great candidate for the community to take on, adding the 'Up For Grabs' label.

**Comment by pruivo-ca** [comment]
Hi,

in my current .NET core 2.2 project I had to access a legacy WCF endpoint with this kind of binding defined. I can't control the binding because it's from a partner and will not be changed. Does anyone have any clue if someone is looking into this ?

Thanks

**Comment by StephenBonikowsky** [comment]
@pruivo-ca we are not working on this right now. It will be considered for .NET Core 5.0 which we will begin working on in January.

**Comment by pruivo-ca** [comment]
@StephenBonikowsky  Thank you for the answer!

**Comment by mconnew** [comment]
@pruivo-ca, when specifying NTLM, all we do is add the credential to a CredentialCache with the restriction that the credential is only used with NTLM to prevent potential raw credential leakage if the server for instance asks for Basic auth. If HttpClientHandler isn't authenticating with NTLM credentials when the server provides the choice of Negotiate or Ntlm, that's a bug in HttpClientHandler and needs to be addressed by dotnet/corefx.

**Comment by mconnew** [comment]
@rodrigobelo, WCF doesn't require you to use the latest version of .NET Core to use our latest packages as we only have a dependency on netstandard2.0. I created a fix for our latest release (4.8.x nuget package version) to support specifying integrated authentication which allows for either NTLM or Negotiate. You will need to use a custom binding to modify the AuthenticationScheme property on the HttpsTransportBindingElement. If you set it to AuthenticationSchemes.IntegratedWindowsAuthentication, WCF will populate the CredentialsCache passed to HttpClientHandler with the credentials added twice, once for NTLM and once for Negotiate. If this doesn't fix your issue, please open a new issue (closed issues don't get noticed during triage).
