### ISSUE TITLE
Unable to generate deps.json, it may have been already generated. 

### ISSUE THREAD

**Issue by bdsipon** [dotnet/wcf#3697]
I follow the link guidelines: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide but getting an error. The error as follows. When I was trying install the tool (dotnet-svcutil), It was not installed in my machine. Any solution please?

Error:
Importing web service metadata ...
Number of service endpoints found: 2
Scaffolding service reference code ...
Error:Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.2.107\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
Done.

**Comment by bdsipon** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/10099435/59808843-47e72a00-9341-11e9-9638-5f8928da3529.png)
I checked out the previous solutions, it is not working.

**Comment by StephenBonikowsky** [comment]
@bdsipon We've seen this issue come up a few times, it is generally something in your machine configuration, such as semicolons in your %temp% path.

Here are the issues where this has been resolved for other folks...
#3225
#3391
#3155
#3143
