### ISSUE TITLE
Support StreamFormatter.SerializeAsyncResult

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#37]
StreamFormatter.SerializeAsyncResult currently throws PlatformNotSupportedException because it required API not available via public contracts.  The external implementation it required is small enough that the implementation can be duplicated locally in StreamFormatter

Issue https://github.com/dotnet/wcf/issues/7 (Support TransferMode.Streamed) depends on this issue being done first.

**Comment by shmao** [comment]
Fixed with #209
