### ISSUE TITLE
Connected Services in .Net Core project fails.

### ISSUE THREAD

**Issue by raziqpv** [dotnet/wcf#3703]
Trying to consume a wcf service in a .Net Core project, 

- adding reference from connected services with the wsdl url fails with "**The encoding in the declaration 'ISO-8859-1' does not match the encoding of the document 'utf-8'.
Done.**"

- running dotnet-svcutil with the wsdl file fails with "**Warning: No endpoints compatible with .Net Core apps were found**"  and "**Error: No code was generated**"

the url works fine with old Dot Net framework projects and able to consume the service from there.

Please let me know if there is any work around to consume the service without changing anything on the old service end, as we cannot do that and no code is available for our access.

**Comment by StephenBonikowsky** [comment]
@raziqpv Could you try the workaround described in #2550 and see if this helps you?

**Comment by StephenBonikowsky** [comment]
@raziqpv If you still need help you can re-open and let us know.
