### ISSUE TITLE
SecurityBindingElement does not expose EnableUnsecuredResponse

### ISSUE THREAD

**Issue by hector-quintero** [dotnet/wcf#3705]
`BindingElementCollection elements = Client.Endpoint.Binding.CreateBindingElements();
            elements.Find<SecurityBindingElement>().EnableUnsecuredResponse = true;`

Line 2 above results in compile time error stating SecurityBindingElement does not contain a definition for EnableUnsecuredResponse. 
Our team is currently using a local build of master branch version: 4.6.0-ci.19325.1

I see the property here:
[System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs#L118) 
But not here: 
[System.ServiceModel.Security/ref/System.ServiceModel.Security.cs](https://github.com/dotnet/wcf/blob/master/src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs#L54)

**Comment by hector-quintero** [comment]
I see there is a current workaround [here](https://github.com/dotnet/wcf/issues/3653#issuecomment-503734676) that works for me.

**Comment by mconnew** [comment]
The property is on the implementation class as it was copied across from .NET Framework, but it wasn't exposed in the contract as it's not hooked up to anything functional. I'm glad the workaround fixed this for you.
Closing as it looks like there's nothing more that's needed. Feel free to re-open if you still have problems.

**Comment by echavez087** [comment]
@mconnew Is it possible that you can provide a specific example of how to set the EnableUnsecuredResponse property using your workaround? Thanks!

**Comment by gustavogavancho** [comment]
I concur with @echavez087. @mconnew an example of how to set the EnableUnsecuredResponse property would be really helpful.
