### ISSUE TITLE
Bridge: Implement caching for GETs and PUTs on the client side 

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#372]
When clients make multiple calls to the Bridge host, we should consider caching the GET and PUT responses so we don't hammer the Bridge for redundant requests. 

The Bridge config is assumed to be stable during the lifetime of a BridgeClient instance, so we don't have to clean up the cache(s).

**Comment by SajayAntony** [comment]
this defeats the purpose of the bridge. Inability to connect to the brigde is the one way that the client is certain that it can invoke a service and possibly continue. 

Caching data within the bridge service is a better option. If we see something like 1000s of request per second or there is a CPU issue with the bridge them it makes sense to make the test smarter somehow to avoid pounding it.

**Comment by roncain** [comment]
Yes, I meant that any GET request the BridgeClient has made to the Bridge resource endpoint to obtain a resource really ought to be cached for the lifetime of the BridgeClient.  By definition the Bridge resources themselves are stable during the test run (i.e. the lifetime of the BridgeClient instance).  I don't advocate any kind of process-wide or Bridge-side cache of GET's.  I just wanted tests to avoid pounding the Bridge for data that is effectively immutable during their lifetime.

**Comment by SajayAntony** [comment]
Makes sense. If we can somehow make sure there is a ping before a test then that should be good enough if the rest is cached. Basically ensure a fail fast path when `BridgeNotAvailable` :)

**Comment by roncain** [comment]
We have a fail-fast mechanism after we determine the Bridge is not reponding (EnsureBridgeIsRunning) and every test after that will fail fast.  I haven't found a way to say "fail this entire project of tests" in xunit, so we see each test failing with a "Bridge is not running" error.

**Comment by hongdai** [comment]
The bridge resource address and host name are cached now. We can reopen the issue if there is a need to cache other things in the future.
