### ISSUE TITLE
Generate synchronous operations checkbox does not update color for dark theme

### ISSUE THREAD

**Issue by fepettersen** [dotnet/wcf#3721]
The label on the checkbox "Generate synchronous operations" is black in the dark theme of VS 2019 Preview Version 16.2.0. This makes it very hard to read.

**Comment by StephenBonikowsky** [comment]
@fepettersen thanks for reporting this!
We will be fixing this in the next release.

**Comment by dasetser** [comment]
This is fixed in the latest preview version of Visual Studio (VS 2019 16.3 Preview 2), which is now available from https://visualstudio.microsoft.com/vs/preview/. Thanks for letting us know so we could fix it.
