### ISSUE TITLE
Timeouts are not fully respected by the WCF client

### ISSUE THREAD

**Issue by lexxdark** [dotnet/wcf#3724]
## Description

When sending data to a client some of the timeouts seem ignored. With timeouts set to 20s I'm able to keep a connection open for hours in specific situations.

## Relation to other bugs

Initially I thought this behavior would be fixed by https://github.com/dotnet/wcf/pull/3709
But I tested with a version of WCF containing this fix and it is still reproduced (packages retrieved from https://github.com/dotnet/wcf/issues/3590)
Note the packages I tested with are within the attached project, but Nuget.config requires some adaptation on your environment

## Reproduction

The general idea is to slowly send data from the SOAP server to the client. There seems to be a general timeout around 15m when not sending anything (ie activate the oddDelay in the provided reverse proxy), but if you do write something to the stream it seems to wait without a limit.

I'm attaching an [example project](https://github.com/dotnet/wcf/files/3363159/TimeoutBug.zip) where the behavior is highlighted. It is intended to be run on windows with linux docker.

The test project is provided and contains the projects:
* WCF server - TimeoutBugWCF - Windows hosted under IIS express
* WCF dotnet core client - TimeoutBugClient - (Linux container, under windows docker)
* Node js reverse proxy - TimeoutBugReverseProxy - (Linux container - under windows docker)

The connectivity/flow is:
* TimeoutBugClient connects to http://TimeoutBugReverseProxy:3000
* TimeoutBugReverseProxy connects to http://10.0.75.1:5790 - which is the windows host on usual docker installation under windows
* TimeoutBugWCF - hosted under windows it's expected to be exposed to the docker network somehow - IIS Express by default refuses to expose itself to the local network; hosted on my machine on port 5790

The client and server have nothing special. What is special is the reverse proxy which:
* sends the first 50 bytes of the response
* waits 30s then sends another 70 bytes of the response
* repeat above until reply is complete

Note that with the above behavior you could in theory wait for the reply without limit. My record was 2h 30m for a reply of ~1500bytes.

The outputs on my machine are:

### WCF client

Relevant code:

```
                Console.WriteLine($"{DateTime.UtcNow:O} Welcome!");
                var binding = new BasicHttpBinding(BasicHttpSecurityMode.None)
                {
                    OpenTimeout = timeout,
                    CloseTimeout = timeout,
                    SendTimeout = timeout,
                    ReceiveTimeout = timeout,
                    MaxReceivedMessageSize = 2097152
                };
                var client = new ServiceClient(binding, new EndpointAddress(remoteAddress));

                Console.WriteLine($"{DateTime.UtcNow:O} Sending request");
                var stopwatch = new Stopwatch();
                stopwatch.Start();
                string str = await client.GetDataAsync(30);
                stopwatch.Stop();
                Console.WriteLine($"{DateTime.UtcNow:O} Got back {str} in {stopwatch.Elapsed}");
                if (stopwatch.Elapsed > timeout)
                    Console.WriteLine($"{DateTime.UtcNow:O} Here is the bug {stopwatch.Elapsed} > {timeout}");
                await client.CloseAsync();
```

Output: 

```

2019-07-05T13:56:49.0179378Z Welcome!
2019-07-05T13:56:49.0999428Z Sending request
2019-07-05T13:58:20.8653629Z Got back ############################## in 00:01:31.7647301
2019-07-05T13:58:20.8654700Z Here is the bug 00:01:31.7647301 > 00:00:20
```

### Reverse Proxy (node js)

Relevant code:

```
        let bodyStr = body.toString();
        // console.log("res from proxied server:", bodyStr);
        console.log("res len from proxied server:", body.length);
        console.log("server data:", bodyStr);

        let currentPos = 0;
        let partSize = 70;

        function queueNextSend() {
            const delay = 30000;
            console.log(`Sending next batch (starting from ${currentPos}) in ${delay}ms`);
            setTimeout(nextBatch, delay);
        }

        function nextBatch() {
            sendNextBatch(partSize);
            if (currentPos < body.length) {
                queueNextSend();
            } else {
                console.log("Sending end");
                res.end();
            }
        }

        function sendNextBatch(batchSize) {
            let nextPos = Math.min(currentPos + batchSize, body.length);
            let bufferPart = body.toString(undefined, currentPos, nextPos);
            console.log(`Sending next batch ${currentPos}-${nextPos}.\n${bufferPart}`);
            res.write(bufferPart);
            currentPos = nextPos;
        }
...
        sendNextBatch(50);
        queueNextSend();

```

output:

```
[HPM] Proxy created: /  ->  http://10.0.75.1:5790/
[HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'proxyRes', 'error', 'close' ]
2019-07-05T13:56:44.403Z Console replaced
2019-07-05T13:56:44.410Z Example app listening on port 3000! Go to http://revproxy:3000/
2019-07-05T13:56:49.466Z Delaying request (1000)...
2019-07-05T13:56:50.468Z Starting request processing
[HPM] POST /Service.svc -> http://10.0.75.1:5790/
2019-07-05T13:56:50.474Z next() processed
2019-07-05T13:56:50.475Z onProxyReq()
2019-07-05T13:56:50.761Z onProxyRes
2019-07-05T13:56:50.762Z proxy-data
2019-07-05T13:56:50.763Z proxy-end
2019-07-05T13:56:50.763Z res len from proxied server: 218
2019-07-05T13:56:50.763Z server data: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><GetDataResponse xmlns="http://tempuri.org/"><GetDataResult>##############################</GetDataResult></GetDataResponse></s:Body></s:Envelope>
2019-07-05T13:56:50.763Z Sending next batch 0-50.
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/so
2019-07-05T13:56:50.764Z Sending next batch (starting from 50) in 30000ms
2019-07-05T13:57:20.791Z Sending next batch 50-120.
ap/envelope/"><s:Body><GetDataResponse xmlns="http://tempuri.org/"><Ge
2019-07-05T13:57:20.792Z Sending next batch (starting from 120) in 30000ms
2019-07-05T13:57:50.803Z Sending next batch 120-190.
tDataResult>##############################</GetDataResult></GetDataRes
2019-07-05T13:57:50.804Z Sending next batch (starting from 190) in 30000ms
2019-07-05T13:58:20.834Z Sending next batch 190-218.
ponse></s:Body></s:Envelope>
2019-07-05T13:58:20.834Z Sending end
```

### Example project

[Example project](https://github.com/dotnet/wcf/files/3363159/TimeoutBug.zip)

**Comment by StephenBonikowsky** [comment]
@lexxdark Thank you reporting this and providing an example project, we will take a look at it this week.

**Comment by lexxdark** [comment]
@StephenBonikowsky thanks

After the discussion on the gitter channel I also tried with 
`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`
and I get the same behavior

**Comment by StephenBonikowsky** [comment]
@lexxdark Sorry for the delay, we have some vacations going on right now but we will get to this.

**Comment by mconnew** [comment]
I finally worked out all the kinks to get this working on my dev box. BTW, the trick to getting IIS Express to work is to tell your reverse proxy to connect to the LAN ip address of you dev machine instead of the NAT bridge Docker IP address.  
I can reproduce the problem, but I'm having problems with tooling limitations trying to remote debug this on Linux (can't take process dump without major hoops and then analysis must be in gdb) so I'm going to need to re-work the repro to run locally on Windows outside of Docker so I can use WinDbg to find the hanging Task. So it's going to be a few more days but thought you would appreciate an update.

**Comment by mconnew** [comment]
I found the problem and your test scenario now times out after 20 seconds. I have created a PR for the fix.

**Comment by StephenBonikowsky** [comment]
WCF packages have been built containing this fix, they are available at this feed...
https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

Package version 4.6.0-preview6.19379.1 or greater for WCF packages...
System.ServiceModel.Duplex
System.ServiceModel.NetTcp
System.ServiceModel.Http
System.ServiceModel.Primitives
System.ServiceModel.Security
