### ISSUE TITLE
How to set Soap header in NetCore those should be available in wsdl as we have in asmx wsdl

### ISSUE THREAD

**Issue by usmanaliabbasse** [dotnet/wcf#3734]
I have just stuck with this problem while putting different solution in parallel to make this one to a success but not getting it at all. How this MessageHeaders with custom authentication type taking userid and passwd can be set in WSDL generated by .Net Core configured and defined asmx services?

I have tried this one but unfortunately, it never goes called upon wsdl loading of a service.

```c#
public class SoapSecurityHeaderInspector2 : IMessageInspector2
        {
            public object AfterReceiveRequest(ref Message message, ServiceDescription serviceDescription)
            {
                message.Headers.Add(new SoapSecurityHeader());
                return null;
            }

            public void BeforeSendReply(ref Message reply, ServiceDescription serviceDescription, object correlationState)
            {
                //throw new NotImplementedException();
            }
        }
```

Have anyone tried a better solution or any custom way to achieve this functionality? please recommend a way for this to be solved.

**Comment by StephenBonikowsky** [comment]
@usmanaliabbasse Thanks for reporting this to us, I'm not entirely sure I understand what your issue is. It would be helpful if you could provide us with some additional information, ideally you can just attach a project with the WSDL you are using and the client code that isn't working.

We do have some tests that may do something similar to what you are asking...
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/MessageInspectorTests.4.4.0.cs
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ClientBaseTests.4.0.0.cs
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.cs

**Comment by usmanaliabbasse** [comment]
Thank you @StephenBonikowsky  for sharing information on this issue.

PleaSe find the attached WSDL for more details that we get once access a soap service created using dotnet core (soapCore nuget package)

Here's that soap project service repository url:
[https://github.com/shehryarkn/DotNet-Core-Soap-Service-Example](url)

Also, I am attaching a WSDL file we get from this service, please find that one.

[ServiceWSDL.zip](https://github.com/dotnet/wcf/files/3391886/ServiceWSDL.zip)

With in this Service.asmx, How can we configure our Message Headers input to be part of this metadata xml information? so once we add this link through SoapUI, there should be a tag added for <Soap:Headers><Authentication><UserName/><Password/></Authentication></SoapHeaders>

**Comment by usmanaliabbasse** [comment]
For more clarification to this issue, I am attaching this image as well where in SOAPUI, i need to add Authentication class with in our soap headers tag:

![image](https://user-images.githubusercontent.com/52812791/61211044-d61fb780-a717-11e9-94f6-c6a2b9cf3d57.png)

**Comment by StephenBonikowsky** [comment]
@usmanaliabbasse Thank you for the additional information! We'll follow-up with you on this shortly.

**Comment by mconnew** [comment]
@usmanaliabbasse, you are on the right path to do this. A message inspector is the correct way to achieve this. You are implementing the interface `IMessageInspector2` which isn't a WCF interface. The interface you need to implement is `IClientMessageInspector`. You also need an `IEndpointBehavior` to install the message inspector and you need to add the behavior to your channel factory. See the links provided in Stephen's [earlier comment](https://github.com/dotnet/wcf/issues/3734#issuecomment-511006685) for examples how to do this. I can't guarantee that your class `SoapSecurityHeader` will create the correct XML as you haven't provided it's implementation. It will at least add a header to the soap headers.

**Comment by StephenBonikowsky** [comment]
Let us know if you have any further questions.

**Comment by JZambranoGS** [comment]
@usmanaliabbasse can you do it?..

**Comment by tapizquent** [comment]
> @usmanaliabbasse, you are on the right path to do this. A message inspector is the correct way to achieve this. You are implementing the interface `IMessageInspector2` which isn't a WCF interface. The interface you need to implement is `IClientMessageInspector`. You also need an `IEndpointBehavior` to install the message inspector and you need to add the behavior to your channel factory. See the links provided in Stephen's [earlier comment](https://github.com/dotnet/wcf/issues/3734#issuecomment-511006685) for examples how to do this. I can't guarantee that your class `SoapSecurityHeader` will create the correct XML as you haven't provided it's implementation. It will at least add a header to the soap headers.

@mconnew 
What would be a similar solution for implementing `BeforeSendReply` using `IClientMessageInspector`?

We need to do an xslt transform before sending a reply but this method is only present in `IDispatchMessageInspector`.

**Comment by PankajRawat333** [comment]
@usmanaliabbasse did you get any solution Or workaround for this problem? I am facing exact same problem.

**Comment by usmanaliabbasse** [comment]
Yes, I managed to fix this problem by a workaround implementation, I did on that time and this was the workaround which I did & luckily, it worked fine for my requirement to authenticate user name and password comes from SOAP incoming request envelop:
        public class SoapSecurityHeaderInspector2 : IMessageInspector2
        {
            public object AfterReceiveRequest(ref Message message, ServiceDescription serviceDescription)
            {
                var isAuthenticated = false;
                if (IsHeaderRequiredForRequestedApi(_httpContext.HttpContext.Request.Path.Value))
                {
                    if (message != null && message.Headers != null && message.Headers.FirstOrDefault() != null)
                    {
                        var authenticationHeader = message.Headers.FirstOrDefault(p => p.Name.Equals(nameof(Models.Authentication), StringComparison.OrdinalIgnoreCase))?.ToString();

                        if (authenticationHeader != null)
                        {
                            using (var stringReader = new StringReader(authenticationHeader))
                            {
                                var authRequest = Deserialize<Models.Authentication>(authenticationHeader);
                                if (authRequest != null && !string.IsNullOrWhiteSpace(authRequest.Userid) && !string.IsNullOrWhiteSpace(authRequest.Passwd))
                                    isAuthenticated = SoapSecurityHeader.ValidateRequestCredentials(_IocContainer, authRequest.Userid, authRequest.Passwd);
                            }
                        }
                    }
                    if (!isAuthenticated)
                    {
                        _httpContext.HttpContext.Response.Clear();
                        _httpContext.HttpContext.Response.StatusCode = 401;
                        _httpContext.HttpContext.Response.ContentType = "text/xml";

                        var result = new Models.AuthenticationFailure { FailureReason = "Invalid user id or password. please try with correct credentials", FailureCode = "401" };
                        var unAuthorizedResponse = XmlUtility.Serialize<Models.AuthenticationFailure>(result);
                        _httpContext.HttpContext.Response.WriteAsync(unAuthorizedResponse);
                        return null;
                    }
                    else
                        return isAuthenticated;
                }
                return null;
            }

            public void BeforeSendReply(ref Message reply, ServiceDescription serviceDescription, object correlationState)
            {
                //throw new NotImplementedException();
            }

            private static bool IsHeaderRequiredForRequestedApi(string requestedPath)
            {
                var configuration = CommonDependencyResolver._IocContainer.GetInstance<IConfiguration>();
                var anonymousAccessService = configuration.GetSection("SoapAuthenticServices").Value;

                var services = anonymousAccessService.Split(',');

                foreach (var service in services)
                {
                    if (!string.IsNullOrWhiteSpace(service))
                        if (requestedPath.StartsWith(service.Trim(), StringComparison.OrdinalIgnoreCase))
                            return true;
                }

                return false;
            }

			public static T Deserialize<T>(string xml)
			{
				T result;
				var myDesrializer = new XmlSerializer(typeof(T));

				try
				{
					using (var stringReader = new StringReader(xml))
					{
						result = (T)myDesrializer.Deserialize(stringReader);
					}
				}
				catch (Exception)
				{
					result = default(T);
				}

				return result;
			}
        }

**Comment by examitymadhu** [comment]
is solution with donetcore? if yes how to call in startup file.
when developed above code getting issues . please share proper logic.
