### ISSUE TITLE
Create tags and release notes for the prior releases

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#374]
Create tags in the repo for the prior releases (beta8, beta7, etc) and add release notes to them.
Example: https://github.com/aspnet/Home/releases
How to: https://github.com/blog/1547-release-your-software

**Comment by zhenlan** [comment]
This is related to the Markdown table work (issue #493) @roncain is working on.

**Comment by roncain** [comment]
We have release notes for rc1.  Leaving this open for when rc2 locks down.  We will also need to create a newer version of the supported-feature table for rc2.

**Comment by zhenlan** [comment]
We've done this work for rc2 already.
