### ISSUE TITLE
DateTimeOffset not transfered correct

### ISSUE THREAD

**Issue by Jan-Magerl** [dotnet/wcf#3749]
If i generate  A WCF Client with Visual Studio 16.1.6.
All Properties of type DateTimeOffset will not transfert correct.
They all are set to default values

**Comment by StephenBonikowsky** [comment]
@Jan-Magerl Thanks for reporting this issue. Could you please provide us some additional information so we can more quickly investigate this?

- code examples, a simple repro project would be best.
- the WSDL you are using to generate the client.

**Comment by StephenBonikowsky** [comment]
Looks like this is a serialization issue and has been reported with dotnet/corefx#31720

**Comment by StephenBonikowsky** [comment]
There is a workaround for this problem, see the full discussion on [stackoverflow](https://stackoverflow.com/questions/3377036/how-can-i-xml-serialize-a-datetimeoffset-property) ...

```
[XmlElement("lastUpdatedTime")]
public string lastUpdatedTimeForXml // format: 2011-11-11T15:05:46.4733406+01:00
{
   get { return lastUpdatedTime.ToString("o"); } // o = yyyy-MM-ddTHH:mm:ss.fffffffzzz
   set { lastUpdatedTime = DateTimeOffset.Parse(value); } 
}
[XmlIgnore] 
public DateTimeOffset lastUpdatedTime;
```

**Comment by StephenBonikowsky** [comment]
Any further action will take place in the [serialization issue](https://github.com/dotnet/corefx/issues/31720).
