### ISSUE TITLE
Next steps after add "Connected Service"?

### ISSUE THREAD

**Issue by RussianDragon** [dotnet/wcf#3752]
Hello.
Link [Use the WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
not answered on next questions...
* How use?
* How correct add service in dependency injection?
* How set proxy address for service?
* How set logger?
* Maybe simple example?

**Comment by StephenBonikowsky** [comment]
@RussianDragon it looks like the doc has a pretty detailed set of steps explaining how to use the tool...
[**How to use the extension**](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide#how-to-use-the-extension)

I'm not sure that your other questions are specifically related to the tool? @dasetser can you provide additional info and guidance?

**Comment by dasetser** [comment]
@RussianDragon We are planning to add a simple example to that doc page soon, which should help with your first and last questions. However, the other questions are beyond the scope of this doc page. This page is only for using the WCF Service Reference Provider tool, your other questions are general WCF questions and you should find documentation about them in the WCF framework documentation.
