### ISSUE TITLE
Error when set UseDefaultWebProxy equals false

### ISSUE THREAD

**Issue by RussianDragon** [dotnet/wcf#3753]
Hello.
If i set UseDefaultWebProxy equals false, i will have exception.
"When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy." 

.net Core 2.2
```
 private static Binding GetBinding(ACSIServiceSettings settings)
        {
            BasicHttpBinding binding = new BasicHttpBinding();
            binding.MaxBufferSize = int.MaxValue;
            binding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            binding.MaxReceivedMessageSize = int.MaxValue;
            binding.AllowCookies = true;
            binding.ReceiveTimeout = settings.ReceiveTimeout;
            binding.SendTimeout = settings.SendTimeout;
            binding.UseDefaultWebProxy = false;
            binding.ProxyAddress = new Uri("http://***.***.***.***:8080");
            return binding;
        }
        private static EndpointAddress GetEndpointAddress(ACSIServiceSettings settings)
        {
            return new EndpointAddress(settings.EndpointAddress);
        }
```
I found very many old issues, with this problem, but i not found answer - what my do?

**Comment by StephenBonikowsky** [comment]
@RussianDragon Thanks for reporting this.

@mconnew This same issue was reported in #1592 and a couple other issues closed as duplicates of that one. Looks like a fix was made #3125, could you take a look at this?

**Comment by mconnew** [comment]
@RussianDragon, it sounds like you aren't using the latest version of WCF as WindowsProxyUsePolicy is only used by WinHttpHandler which we switched away from using a while ago. Can you try updating to the latest version of WCF?

**Comment by StephenBonikowsky** [comment]
@RussianDragon Let us know if updating to a more recent version of WCF does not resolve your issue.
