### ISSUE TITLE
[P1] Support System.ServiceModel.Security.SecurityAlgorithmSuite

### ISSUE THREAD

**Issue by soyang2828** [dotnet/wcf#3759]
| APIs | Port/Implement | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
`class SecurityAlgorithmSuite` | <ol><li>[x] Merged</li></ol> | <ol><li>[x] Added</li></ol> | <ol><li>[x] Unit <li>[x] Scenario</li></li></ol> |
`SecurityAlgorithmSuite.TripleDes` | <ul><li>[x] Merged</li></ul> | <ul><li>[x] Added</li></ul> | <ul><li>[x] Unit <li>[x] Scenario</li></li></ul> |
`S.SM.Channels.SecurityBindingElement. DefaultAlgorithmSuite` | <ul><li>[x] Merged</li></ul> | <ul><li>[x] Added</li></ul> | <ul><li>[x] Unit <li>[x] Scenario</li></li></ul> |
***
**API Notes**
- class SecurityAlgorithmSuite: No instance members needed
- SecurityAlgorithmSuite.TripleDes: Static property
- Also need to expose S.SM.Channels.SecurityBindingElement.DefaultAlgorithmSuite because that is how they set SecurityAlgorithmSuite.TripleDes on the binding.
***
**Implementation Notes**

***
**Public Contract Notes**

- Public Contract for SecurityAlgorithmSuite: System.ServiceModel.Security
- Public Contract for S.SM.Channels.SecurityBindingElement.DefaultAlgorithmSuite: System.ServiceModel.Security
***
**Testing Notes**
- Unit tests are required.
- Scenario tests needed: Yes
      Take existing TransportWithMessageCredential test and duplicate. In the new test, modify the DefaultAlgorithmSuite to use TripleDes. This will need a new service endpoint which uses TripleDes too.

***
**PR Links**
Porting and Adding to the PC: #3875
Unit tests added via: #3915
Scenario tests tracked by: #4022

**Comment by mconnew** [comment]
Can you please list the properties that you need available? We have this implemented but not added to the contract but we are currently only using (so only have implementation for) `SecurityAlgorithmSuite.Basic256`. Do you only need the static properties to select a security algorithm suite or do you need to access the instance properties on a concrete implementation such as the instance property DefaultDigestAlgorithm?

**Comment by soyang2828** [comment]
This is from our internal scan. I take it as the instance property on SecurityAlgorithmSuite

System.ServiceModel.Security.SecurityAlgorithmSuite
System.ServiceModel.Security.SecurityAlgorithmSuite.get_TripleDes

**Comment by mconnew** [comment]
That's a static property. So you only need the static method SecurityAlgorithmSuite.TripleDes which returns an instance of SecurityAlgorithmSuite which is then used elsewhere. Do you happen to know which api you are setting the instance on?

**Comment by soyang2828** [comment]
Yes, here is code snippet:            

IssuedSecurityTokenParameters istp = new IssuedSecurityTokenParameters
            {
...

            WSFederationHttpBinding federationBinding = new WSFederationHttpBinding();

            Uri internetWebProxy = CommonUtils.GetLocalServerProxyAddress(context);
...
                federationBinding.ProxyAddress = internetWebProxy;
                federationBinding.UseDefaultWebProxy = false;
                federationBinding.BypassProxyOnLocal = true;
...

            istp.IssuerBinding = federationBinding;

            // Create binding as specified by the RMS service pipelines
            TransportSecurityBindingElement securityBinding = SecurityBindingElement.CreateIssuedTokenOverTransportBindingElement(istp);
            securityBinding.DefaultAlgorithmSuite = SecurityAlgorithmSuite.TripleDes;

**Comment by mconnew** [comment]
This means we also need to expose `SecurityBindingElement.DefaultAlgorithmSuite`. I'll add this to the top comment.

**Comment by krispenner** [comment]
May I request that the static property `SecurityAlgorithmSuite.Basic128Rsa15` also be added? As this is what is required for us to connect to a third party web service. Otherwise, how can I find out how to derive my own `SecurityAlgorithmSuite` that implements the same `Basic128Rsa15` algorithm from .NET framework?

**Comment by StephenBonikowsky** [comment]
@krispenner Let's handle this request as part of your ask in #3860.
