### ISSUE TITLE
[P0] Support System.ServiceModel.ClientCredentialsSecurityTokenManager

### ISSUE THREAD

**Issue by soyang2828** [dotnet/wcf#3761]
| APIs | Implementation | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
class S.SM.ClientCredentialsSecurityTokenManager | <ol><li>[ ] Merged</li></ol> | <ol><li>[ ] Added</li></ol> | <ol><li>[ ] Unit <li>[ ] Scenario</li></li></ol> |
***
**API Notes**
This pulls in a lot of additional abstract classes which will also need to be exposed making it a medium to large task.
***
**Implementation Notes**

***
**Public Contract Notes**
Public Contract: ???
***
**Testing Notes**
- Unit tests are required.
- Scenario tests needed: ???

***
**PR Links**

**Comment by StephenBonikowsky** [comment]
Duplicate of #3861- closing
