### ISSUE TITLE
[P3] Support System.ServiceModel.WSFederationHttpBinding

### ISSUE THREAD

**Issue by soyang2828** [dotnet/wcf#3763]
| APIs | Port/Implement | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
class S.SM.WS2007HttpBinding | <ol><li>[ ] Merged</li></ol> | <ol><li>[ ] Added</li></ol> | <ol><li>[ ] Unit <li>[ ] Scenario</li></li></ol> |
ctor S.SM.WS2007HttpBinding((SecurityMode securityMode)) | <ul><li>[ ] Merged</li></ul> | <ul><li>[ ] Added</li></ul> | <ul><li>[ ] Unit <li>[ ] Scenario</li></li></ul> |
***
**API Notes**
No work for WCF, we will need to let them know what to replace the call to this binding with.
***
**Implementation Notes**

***
**Public Contract Notes**

- Which WCF Contract should this API be added to: ???

***
**Testing Notes**
- Unit tests are required.
- Scenario tests needed: ???

***
**PR Links**

**Comment by StephenBonikowsky** [comment]
Closing this work item.
Usage of this binding goes away with the removal of the Exchange implementation of the WS Trust Client.
Any work needed in WCF related to the communication with the new WS Trust Client being provided by the Identity team will be tracked in #3871
