### ISSUE TITLE
BuildChannelFactoryCore method of the class TransportSecurityBindingElement is not supported in .Net Core 2.1 when using CreateUserNameOverTransportBindingElement

### ISSUE THREAD

**Issue by HemaSK** [dotnet/wcf#3769]
I wish to call a WSDL service from .Net Core 2.1 version web application.
I have created a .Net Core 2.1 Web application, 
I have added a Connected Service through WCF Service Provider
When I try to pass parameters through Custom Binding, I am getting PlatformNotSupportedException: TransportSecurityBindingElement.BuildChannelIFactoryCode is not supported 
How can we overcome this issue? Or any workaround for this please?

Thanks
Hemalatha. J

**Comment by StephenBonikowsky** [comment]
@HemaSK Support was added with PR #3538 this change is part of our 3.0 release.
It is included in our 3.0 release Preview6 packages...

https://www.nuget.org/packages/System.ServiceModel.Duplex/4.6.0-preview6.final
https://www.nuget.org/packages/System.ServiceModel.Http/4.6.0-preview6.final
https://www.nuget.org/packages/System.ServiceModel.NetTcp/4.6.0-preview6.final
https://www.nuget.org/packages/System.ServiceModel.Primitives/4.6.0-preview6.final
https://www.nuget.org/packages/System.ServiceModel.Security/4.6.0-preview6.final

**Comment by HemaSK** [comment]
Hi
Will this 4.6.0 preview packages supported in .Net Core 2.1 version?

**Comment by HemaSK** [comment]
Hi,
Thanks for the 4.6.0 preview package. Now, the platform issue fixed

But, I have similar few issues as follows

1. System.Web is not available in this NuGet package
 (For the code System.Web.HttpContext.Current.User.Identity.Name)

2. WriteMethod is not available in System.ServiceModel.Channels 
 (For the code System.ServiceModel.Channels.MessageFault.WriteTo)

In which Assembly package can we find these methods HttpContext and WriteTo in .Net Core 2.1 version?

Thanks
Hemalatha. J

**Comment by StephenBonikowsky** [comment]
@HemaSK 
This Repo is for client side WCF features only and within the client side not all things have yet been ported from the full framework.

Both APIs you mentioned are not currently supported in .NET Core.

System.Web isn't a WCF API.
System.ServiceModel.Channels.MessageFault is a WCF API, @mconnew is this only used for server side purposes?
