### ISSUE TITLE
.Net core3.0  Does not support dual  authentication schemes(NTLM+ Negotiate)

### ISSUE THREAD

**Issue by fngch** [dotnet/wcf#3775]
I am developing a microservice which interact with Sharepoint SOAP service hosted in docker(linux),getting {System.ServiceModel.Security.MessageSecurityException: 
The server require authentication scheme Negotiate,NTLM,
The HTTP request is unauthorized with client authentication scheme 'Ntlm'.
Thank in advance,
-fngch

**Comment by StephenBonikowsky** [comment]
Closing this  as a duplicate of #3774
