### ISSUE TITLE
Enable Bridge GET request to obtain list of resources

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#378]
It should be possible to issue a GET request to a Bridge resource endpoint to obtain a list of all known resources.  Investigate the best REST convention for this, but it could be just a GET without a named resource to start with.  The return would probably just be a json array of resource names, but final design is TBD.

**Comment by SajayAntony** [comment]
closed by - ee31c3255753d86e6431b69c7af55fe10277616c
refer - https://github.com/dotnet/wcf/pull/377#issuecomment-144219006
