### ISSUE TITLE
Signing the body of a SOAP request message using WCF

### ISSUE THREAD

**Issue by NCRKRK** [dotnet/wcf#3781]
I am currently using the project to invoke a WCF in .net core (3.0 preview 6) and I am trying to sign the body of SOAP request message.

So far I have seen in the internal sealed class SendSecurityHeader, the use of the method SetupExecution that sets both the boolean signBody and the boolean encryptBody to false internally in the method.
The method SecurityAppliedMessage then sets the bodyProtectionMode based on these values.

Is there any way to change it so that the body will be signed as well?

I am using a customBinding for the WCF and if there is a way to set it here, then that is preferable:

`

            var binding = new BasicHttpBinding(BasicHttpSecurityMode.TransportWithMessageCredential);
            binding.Security.Message.ClientCredentialType = BasicHttpMessageCredentialType.Certificate;

            // Create custom binding from basic binding
            var customBinding = new CustomBinding(binding);

            var textBindingElement = new TextMessageEncodingBindingElement()
            {
                MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap11, AddressingVersion.WSAddressing10),
                WriteEncoding = Encoding.UTF8
            };
            var httpsTransportBindingElement = new HttpsTransportBindingElement()
            {
                RequireClientCertificate = true
            };

            var count = customBinding.Elements.Count;

            for (int i = 0; i < count; i++)
            {
                if (customBinding.Elements[i] is TextMessageEncodingBindingElement)
                {
                    customBinding.Elements[i] = textBindingElement;
                }
                else if (customBinding.Elements[i] is HttpTransportBindingElement)
                {
                    customBinding.Elements[i] = httpsTransportBindingElement;
                }
            }
`

**Comment by NCRKRK** [comment]
Looks like #3424 should be the solution to this problem.

**Comment by StephenBonikowsky** [comment]
That is correct @NCRKRK, you can monitor that issue to see when support for Message security.
