### ISSUE TITLE
OperationContext.Current is null

### ISSUE THREAD

**Issue by AnReZa** [dotnet/wcf#3784]
I'm providing a WCF service in my .net core project via *SoapCore*. In one of the methods, I want to access the SOAP envelope header info. To test that, I've added the following code:

```c#
[ServiceContract]
public interface IDataService {
    [OperationContract]
    string TransmitObject(XElement node);
}

// -------------------------------------------------------------------------

public string TransmitObject(XElement node) {
    foreach(var header in OperationContext.Current.IncomingMessageHeaders) {
        Console.WriteLine(header.ToString());
    }

    return JsonConvert.SerializeXNode(node, Formatting.None);
}
```

However, in this case, the OperationContext.Current attribute is always `null`. What do I need to change in order to make that work?

**Comment by StephenBonikowsky** [comment]
@mconnew 
@AnReZa 
WCF server side code is not yet supported in .NET Core, this repo is for WCF client side only.
I'm not too familiar with SoapCore but assuming [this is it](https://github.com/DigDes/SoapCore) then the readme docs say that it

> It is possible to use SoapCore with .net legacy WCF and Web Services, both as client and service.

I don't know what they may or may not support doing but it would be based on the Full Framework implementation of WCF, I would start there...
[OperationContext.IncomingMessageHeaders Property](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.operationcontext.incomingmessageheaders?view=netframework-4.8
)
[Samples - Accessing OperationContext](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/samples/accessing-operationcontext)

**Comment by AnReZa** [comment]
@StephenBonikowsky
I actually created a [ticket on SoapCore's repository](https://github.com/DigDes/SoapCore/issues/300) as well. I just wasn't sure, if the error lays on your or their side. As far as I know, SoapCore is nothing more than a middleware to the regular Framework methods. However, I couldn't find a single reference to the `OperationContext` in their source code. Therefore, I don't really know, if this is the actual problem, or if the problem lays deeper in the Framework or Core code.

**Comment by StephenBonikowsky** [comment]
I would first mock up something using framework code, the sample I linked above for instance. Make sure you have it working then use that code with SoapCore.
Hopefully you get some response on the issue you opened there.
I'm closing this issue here since there is no action we can take on this.
