### ISSUE TITLE
WCF tracing in Linux

### ISSUE THREAD

**Issue by Cronan** [dotnet/wcf#3789]
Is there a way to enable WCF tracing  in .NET Core in Linux?

I'm seeing a situation where a few (out of hundreds) of Linux clients timeout when  hitting a Windows WCF server, but basic network connectivity seems to be OK.

I read #1243, but couldn't work out how the example will help me to write an event listener in Linux.

**Comment by Cronan** [comment]
Can anyone help?

**Comment by StephenBonikowsky** [comment]
@Cronan the example linked in #1243 instantiates a new "TestEventListener"
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs#L27

Which you can find here...
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/TestEventListener.cs

This is mostly boiler-plate code, in this example the test is listening for all events from the target source  "Microsoft-Windows-Application Server-Applications". The logging happens between lines 74 to 105 but in this case is all in memory, you would probably want to modify that to log to a file.

Another option you can take a look at which may be closer to what you want is...
https://code.msdn.microsoft.com/windowsapps/Logging-Sample-for-Windows-0b9dffd7/sourcecode?fileId=67472&pathId=1209661119

In this case it logs to a file.

The key point is that you need to write your own class that derives from EventListener, listen for the events you want and log them how you wish.

@mconnew

**Comment by mconnew** [comment]
I've just checked up on the progress of something I heard rumblings about a while ago and there's another option which might be useful. .NET Core 3.0 is shipping with a new feature to enable tracing in an easy way. You can find details [here](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md).

**Comment by mconnew** [comment]
@Cronan, have you considered tracing from the server side?

**Comment by Cronan** [comment]
Thanks for the suggestion @mconnew 
I did the following:

1. Set the service config up like this:

```
    <diagnostics wmiProviderEnabled="true">  
      <messageLogging   
           logEntireMessage="true"   
           logMalformedMessages="true"  
           logMessagesAtServiceLevel="true"   
           logMessagesAtTransportLevel="true"  
           maxMessagesToLog="3000"   
       />  
    </diagnostics> 
  </system.serviceModel>

  <system.diagnostics>  
    <sources>  
      <source name="System.ServiceModel"  
              switchValue="Information, ActivityTracing"  
              propagateActivity="true" >  
        <listeners>  
          <add name="xml"/>  
        </listeners>  
      </source>  
      <source name="System.ServiceModel.MessageLogging">  
        <listeners>  
          <add name="xml"/>  
        </listeners>  
      </source>  
      <source name="myUserTraceSource"  
              switchValue="Information, ActivityTracing">  
        <listeners>  
          <add name="xml"/>  
        </listeners>  
      </source>  
    </sources>  
  <sharedListeners>  
    <add name="xml"  
        type="System.Diagnostics.XmlWriterTraceListener"  
              initializeData="logs\Traces.svclog" />  
  </sharedListeners> 
```

This started generating a Traces.svclog file which I am analyzing by using MS Service Trace Viewer.
In the calls from the majority of clients (which succeed) I see this kind of thing:

![image](https://user-images.githubusercontent.com/777435/63000805-ee473b80-be69-11e9-8fb4-f73aa4d400f1.png)

I see a successful socket connection like this:

```
<E2ETraceEvent xmlns="http://schemas.microsoft.com/2004/06/E2ETraceEvent">
<System xmlns="http://schemas.microsoft.com/2004/06/windows/eventlog/system">
<EventID>262169</EventID>
<Type>3</Type>
<SubType Name="Information">0</SubType>
<Level>8</Level>
<TimeCreated SystemTime="2019-08-13T08:53:33.7382538Z" />
<Source Name="System.ServiceModel" />
<Correlation ActivityID="{b1947001-57a6-4fe9-aad1-b65d50d197d9}" />
<Execution ProcessName="My.Service" ProcessID="37760" ThreadID="21" />
<Channel />
<Computer>MYHOSTNAME</Computer>
</System>
<ApplicationData>
<TraceData>
<DataItem>
<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Information">
<TraceIdentifier>http://msdn.microsoft.com/en-GB/library/System.ServiceModel.Channels.SocketConnectionCreate.aspx</TraceIdentifier>
<Description>SocketConnection create</Description>
<AppDomain>My.Service.exe</AppDomain>
<Source>System.ServiceModel.Channels.SocketConnection/61112600</Source>
<ExtendedData xmlns="http://schemas.microsoft.com/2006/08/ServiceModel/DictionaryTraceRecord">
<State>Open</State>
<LocalEndpoint>10.220.11.227:10666</LocalEndpoint>
<RemoteEndPoint>10.222.40.32:34987</RemoteEndPoint>
</ExtendedData>
</TraceRecord>
</DataItem>
</TraceData>
</ApplicationData>
</E2ETraceEvent>
```

Followed by messages back and forth, as expected.
10.220.11.227:10666 is my server, 10.222.40.32:34987 is my client.

In the calls that eventually timeout and fail, I see this:

![image](https://user-images.githubusercontent.com/777435/63000862-120a8180-be6a-11e9-8bec-6d1adf2c32a0.png)

Curiously, the trace log is actually broken, in that the last event (the one that should be the SockerConnection) is partially written:

```
<E2ETraceEvent xmlns="http://schemas.microsoft.com/2004/06/E2ETraceEvent">
<System xmlns="http://schemas.microsoft.com/2004/06/windows/eventlog/system">
<EventID>262169</EventID><Type>3</Type>
<SubType Name="Information">0</SubType>
<Level>8</Level><TimeCreated SystemTime="2019-08-13T08:57:45.9869966Z" />
<Source Name="System.ServiceModel" />
<Correlation ActivityID="{3afd2961-6ce1-4806-a8ee-85d18622e8c0}" />
<Execution ProcessName="My.Service" Proce
```

If I run a utility like ncat, on my client to create a port in the range 34900+, I am able to successfully telnet from the server and exchange comms, so basic networking looks fine.

I have checked the EvemtViewer on the server, there is nothing obvious showing up.

**Comment by Cronan** [comment]
@StephenBonikowsky will your samples compile and run on Centos Linux, some of the stuff looks windows-specific?

**Comment by StephenBonikowsky** [comment]
The logging sample I linked to was created in the context of Windows Store Apps so yes it has windows specific stuff in some of the methods which you would need to modify for your purposes on Linux but the general logging concept works on any platform.

**Comment by Cronan** [comment]
@StephenBonikowsky Thank you, I'll have a go. I hope it will be more informative than the server tracing.

**Comment by Cronan** [comment]
I've added `<trace autoflush="true"/>` to try to prevent partial trace writes.

**Comment by StephenBonikowsky** [comment]
If you need any additional help please let us know.
