### ISSUE TITLE
I need to use more than 1 certificate in classes generated by WCF Service Reference Provider

### ISSUE THREAD

**Issue by kamilk91** [dotnet/wcf#3791]
**Describe the bug**
```
  cli.ChannelFactory.Credentials.ClientCertificate.SetCertificate
```
it allows me to set one of certificate, and it is not enough. 

In System.NET client i wrote (its harder to use, i want to use autogenerated model) 
```
  X509Certificate2Collection certs = new X509Certificate2Collection();
            certs.Import("../../../", "password", X509KeyStorageFlags.DefaultKeySet);
```

**To Reproduce**
```
SomeClient cli = new SomeClient();
cli.ClientCredentials.ClientCertificate.SetCertificate(StoreLocation.LocalMachine, StoreName.Root, X509FindType.FindByThumbprint, "536dbffed57314c9ce442adefebe1115bd3000ab");

//set certificate allows to use only one.
```
i can't provide wsdl file because of NDA

**Expected behavior**
I want to use more than 1 certificate, because server i have to use needs it. Im using p12 format localy, or certificate storage. 

**Additional context**

**Comment by StephenBonikowsky** [comment]
@mconnew 
I dug around but as far as I can tell we can't set more than one certificate even in full framework, is there some way of doing this or is this a feature request?

**Comment by mconnew** [comment]
@kamilk91, the tls protocol only uses a single certificate for authentication. Is what your wanting to do is bundle the intermediate public certs which chains the primary certificate to a known root?
