### ISSUE TITLE
dotnet-svcutil. Properties (not marked with DataMember) are missing from the generated class

### ISSUE THREAD

**Issue by GroosKJ** [dotnet/wcf#3792]
dotnet-svcutil generates reference.cs that includes all datacontract classes.

In these classes all properties with attribute DataMember are included.

In these classes all properties without attribute DataMember or with attribute IgnoreDataMemberare are not included.

In .net framework these properties are included.

Example in the following generated class 

        public PlugFanResults PlugFanResults { get; set; }
        public List<PlugFanCombination> PlugFanCombinations { get; set; }
        public PlugFanCombination PlugFanCombination { get; set; }

are missing

[DataContract]
    public class PlugFan
    {
        [DataMember]
        public int PlugFanId { get; set; }
        [DataMember]
        public string VerhulstFrameMaterial { get; set; }
        [DataMember]
        public string FanDesign { get; set; }
        [DataMember]
        public string FanType { get; set; }
        [DataMember]
        public string FanManufacturer { get; set; }
        [DataMember]
        public string MotorEfficiencyClass { get; set; }
        [DataMember]
        public string MotorThermalProtection { get; set; }
        [DataMember]
        public string MotorManufacturer { get; set; }
        [DataMember]
        public string SupplierFrequencyInverter { get; set; }
        [DataMember]
        public string MotorMaximumSpeed { get; set; }
        [DataMember]
        public string FanArrangement { get; set; }
        [DataMember]
        public double MotorSafetyFactor { get; set; }
        [DataMember]
        public double AirVolume { get; set; }
        [DataMember]
        public int InternalStatic { get; set; }
        [DataMember]
        public int ExternalStatic { get; set; }
        [DataMember]
        public int ExtraStatic { get; set; }
        [DataMember]
        public bool FrequencyInverterMounted { get; set; }
        [DataMember]
        public bool Atex3GZone2 { get; set; }
        [DataMember]
        public bool Coating40Micron { get; set; }
        [DataMember]
        public bool Coating90Micron { get; set; }
        [DataMember]
        public double TotalAirVolume { get; set; }
        [DataMember]
        public double SectionAirVelocity { get; set; }

        [IgnoreDataMember]
        public PlugFanResults PlugFanResults { get; set; }
        public List<PlugFanCombination> PlugFanCombinations { get; set; }
        public PlugFanCombination PlugFanCombination { get; set; }

Generated by dotnet-svcutil:

[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlugFan", Namespace="http://schemas.datacontract.org/2004/07/VekasSharedLibrary.Model")]
    public partial class PlugFan : object
    {
        
        private double AirVolumeField;
        
        private bool Atex3GZone2Field;
        
        private bool Coating40MicronField;
        
        private bool Coating90MicronField;
        
        private int ExternalStaticField;
        
        private int ExtraStaticField;
        
        private string FanArrangementField;
        
        private string FanDesignField;
        
        private string FanManufacturerField;
        
        private string FanTypeField;
        
        private bool FrequencyInverterMountedField;
        
        private int InternalStaticField;
        
        private string MotorEfficiencyClassField;
        
        private string MotorManufacturerField;
        
        private string MotorMaximumSpeedField;
        
        private double MotorSafetyFactorField;
        
        private string MotorThermalProtectionField;
        
        private int PlugFanIdField;
        
        private double SectionAirVelocityField;
        
        private string SupplierFrequencyInverterField;
        
        private double TotalAirVolumeField;
        
        private string VerhulstFrameMaterialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AirVolume
        {
            get
            {
                return this.AirVolumeField;
            }
            set
            {
                this.AirVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Atex3GZone2
        {
            get
            {
                return this.Atex3GZone2Field;
            }
            set
            {
                this.Atex3GZone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Coating40Micron
        {
            get
            {
                return this.Coating40MicronField;
            }
            set
            {
                this.Coating40MicronField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Coating90Micron
        {
            get
            {
                return this.Coating90MicronField;
            }
            set
            {
                this.Coating90MicronField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExternalStatic
        {
            get
            {
                return this.ExternalStaticField;
            }
            set
            {
                this.ExternalStaticField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraStatic
        {
            get
            {
                return this.ExtraStaticField;
            }
            set
            {
                this.ExtraStaticField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FanArrangement
        {
            get
            {
                return this.FanArrangementField;
            }
            set
            {
                this.FanArrangementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FanDesign
        {
            get
            {
                return this.FanDesignField;
            }
            set
            {
                this.FanDesignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FanManufacturer
        {
            get
            {
                return this.FanManufacturerField;
            }
            set
            {
                this.FanManufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FanType
        {
            get
            {
                return this.FanTypeField;
            }
            set
            {
                this.FanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FrequencyInverterMounted
        {
            get
            {
                return this.FrequencyInverterMountedField;
            }
            set
            {
                this.FrequencyInverterMountedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InternalStatic
        {
            get
            {
                return this.InternalStaticField;
            }
            set
            {
                this.InternalStaticField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotorEfficiencyClass
        {
            get
            {
                return this.MotorEfficiencyClassField;
            }
            set
            {
                this.MotorEfficiencyClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotorManufacturer
        {
            get
            {
                return this.MotorManufacturerField;
            }
            set
            {
                this.MotorManufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotorMaximumSpeed
        {
            get
            {
                return this.MotorMaximumSpeedField;
            }
            set
            {
                this.MotorMaximumSpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MotorSafetyFactor
        {
            get
            {
                return this.MotorSafetyFactorField;
            }
            set
            {
                this.MotorSafetyFactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotorThermalProtection
        {
            get
            {
                return this.MotorThermalProtectionField;
            }
            set
            {
                this.MotorThermalProtectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlugFanId
        {
            get
            {
                return this.PlugFanIdField;
            }
            set
            {
                this.PlugFanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SectionAirVelocity
        {
            get
            {
                return this.SectionAirVelocityField;
            }
            set
            {
                this.SectionAirVelocityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierFrequencyInverter
        {
            get
            {
                return this.SupplierFrequencyInverterField;
            }
            set
            {
                this.SupplierFrequencyInverterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalAirVolume
        {
            get
            {
                return this.TotalAirVolumeField;
            }
            set
            {
                this.TotalAirVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerhulstFrameMaterial
        {
            get
            {
                return this.VerhulstFrameMaterialField;
            }
            set
            {
                this.VerhulstFrameMaterialField = value;
            }
        }
    }
}

**Comment by StephenBonikowsky** [comment]
@dasetser adding to tooling.

**Comment by dasetser** [comment]
@GroosKJ If your server has a class with [DataContract] then any properties that don't have [DataMember] shouldn't shouldn't be included in the wsdl or serialized at all. The dotnet-svcutil tool works off the wsdl, so if the members aren't included in that we can't generate properties for them. Is your service doing something to include properties that aren't marked with [DataMember] in the wsdl? I'm not sure how this scenario could work in .net framework unless there's something to hint to the server to include it anyway (which is what the DataMember attribute is normally doing).

**Comment by GroosKJ** [comment]
I understand that properties not marked as [DataMember] are not serialized, but I don't understand why they should or can not be included in the wsdl. This concept works in .net framework 4.6.
The datacontract class is shared between server and client. Thus I can use the same datacontract class on the client side and the server side. The non datamember properties are used as  placeholder to be filled on the client side. If the non datamember properties are not included in the wsdl, a new class has to be created on the client side referencing the datacontract class.
It is not consistent that on the server side non datamember properties can be used but on the client side those non datamembers don't exist.
My workaround is that I include those properties by hand in the generated code, but I have to redo it everytime the wsdl is updated. So if it is not too much effort could the non datamembers be included in the generated wsdl as well?

**Comment by dasetser** [comment]
The wsdl is from the service and defines what is serialized and sent over the wire. I don't know of any way to include a property in the wsdl without serializing it, because the wsdl tells the client side what needs to be serialized when communicating with the service. WCF on core is only the client-side, so the server is always using the full .NET Framework. The server is the same, the wsdl is the same. The only difference when using .NET Core is that dotnet-svcutil reads the wsdl to generate the code instead of svcutil (or add service reference). Do you have a wsdl (or sample project) you can share that shows this working on .NET Framework but not on Core?

From the description of your scenario, if you are able to reference the actual type I would think you don't want dotnet-svcutil to generate these classes at all. Are you sure these types are being generated in the full .NET Framework case? Or do they just use your referenced version of the type? Dotnet-svcutil implements a feature similar to Add Service Reference's "Reuse types in all referenced assemblies" feature that looks through the assemblies your client project references and tries to use them instead of generating a type for them. Do you have the type referenced in your client project when you run dotnet-svcutil? We've seen some issues with types not always being reused correctly with the tool (#3812 for example). So I'm wondering if you're running into something similar.
