### ISSUE TITLE
Support ETW tracing

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#38]
Add support for ETW tracing throughout the WCF libraries.
Before starting this issue, please provide a description of the intended approach so that we can discuss it here.

**Comment by mconnew** [comment]
This feature should use [EventSource.](https://msdn.microsoft.com/en-us/library/system.diagnostics.tracing.eventsource.aspx) Additionally, the same GUID and name as WCF uses on desktop should be used for the ETW provider GUID and name. This is to allow compatibility with existing analysis tools such as [Service Trace Viewer.](https://msdn.microsoft.com/en-us/library/ms732023%28v=vs.110%29.aspx)

**Comment by zhenlan** [comment]
@roncain Can this be considered done with the EventSource fix @dmetzgar did? Are there anything else supposed to be covered by this item?

**Comment by zhenlan** [comment]
This is considered done. We should add unit tests for this.

**Comment by zhenlan** [comment]
@hongdai can we please consider to do this as part of our E2E validation in the future?

**Comment by hongdai** [comment]
E2E validation will cover most of the outloop tests. So if we have ETW outloop coverage or unit coverage, it will get covered in E2E validation.

 E2E validation runs typically once, at the end of each milestone. Thus we cannot rely on it to find functional issues, only integration level issues.
