### ISSUE TITLE
[P0] Support System.IdentityModel.Tokens.SamlAssertionKeyIdentifierClause

### ISSUE THREAD

**Issue by soyang2828** [dotnet/wcf#3803]
# This Item is dependent on [[P0] Support WCF usage of SecurityToken from MSAL.](https://github.com/dotnet/wcf/issues/3871)

| APIs | Port/Implement | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
class S.IM.Tokens.SamlAssertionKeyIdentifierClause | <ol><li>[ ] Merged</li></ol> | <ol><li>[ ] Added</li></ol> | <ol><li>[ ] Unit <li>[ ] Scenario</li></li></ol> |
ctor S.IM.T.SamlAssertionKeyIdentifierClause(string assertionId) | <ul><li>[ ] Merged</li></ul> | <ul><li>[ ] Added</li></ul> | <ul><li>[ ] Unit <li>[ ] Scenario</li></li></ul> |
***
**API Notes**

***
**Implementation Notes**
Not ported.
***
**Public Contract Notes**

- Public Contract: System.ServiceModel.Security

***
**Testing Notes**
- Unit tests are required.
- Scenario tests needed: ???

***
**PR Links**

**Comment by StephenBonikowsky** [comment]
Closing this work item.
Usage of this API goes away with the removal of the Exchange implementation of the WS Trust Client.
Any work needed in WCF related to the communication with the new WS Trust Client being provided by the Identity team will be tracked in #3871
