### ISSUE TITLE
Configure Web Service Reference - Reuse types in referenced assemblies - Still broken

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/wcf#3812]
Create a web service reference with a shared assembly.  If the DTO has a DataContract that specifies a namespace the type isn't reused.

This [bug ](https://github.com/dotnet/wcf/issues/3253) was supposed to have been fixed.  It appears to be fixed if the DataContract doesn't have a namespace.

Say we have the shared type
```
[DataContract]
public class CompositeType
```
This is reused.

But if we have

```
[DataContract(Namespace = "nowhere.com")]
public class CompositeType2

```

it isn't.

See the attached sample app. [WCFTest.zip](https://github.com/dotnet/wcf/files/3490383/WCFTest.zip)

**Expected behavior**
I expect shared types to be reused whether they have an explicit namespace or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/271656/62838896-3273e980-bc7a-11e9-8119-f330d7594ac2.png)

**Additional context**
VS 16.3.0 Preview 1.0

**Comment by StephenBonikowsky** [comment]
Thanks for reporting this @PhilPJL 
@dasetser can you take a look when you have time please.

**Comment by StephenBonikowsky** [comment]
Needs to be fixed but lower priority.

**Comment by PhilPJL** [comment]
@StephenBonikowsky This isn't low priority for us.  We have 20 WCF services which all use shared types across our code base.  If we want to move to .NET Core (which we do because we're now developing for Xamarin/Android) this is a big problem.  Obviously we can get rid of WCF and switch to WebApi or Grpc but really shouldn't have to.

If you do get around to fixing this don't forget it's possible for a WCF service to consume two (or more classes) with the same name disambiguated by namespace, e.g

namespace Company.Project1.Types
{
  [DataContract(namespace="namespace1)]
  public class AThing {}
}

namespace Company.Project2.Types
{
  [DataContract(namespace="namespace2)]
  public class AThing {}
}

**Comment by StephenBonikowsky** [comment]
Thanks for the additional context @PhilPJL we will discuss this further.

**Comment by PhilPJL** [comment]
@StephenBonikowsky: When if ever will this be fixed?

**Comment by StephenBonikowsky** [comment]
@dasetser We need to add this issue into our planning for 3.1 Servicing/5.0 release. Going to add it to 3.1.1 for right now to make sure we don't miss it.

**Comment by Thraka** [comment]
@StephenBonikowsky @dasetser Please make sure you update the docs to either indicate the current problem (as in something isn't working as expected) and to update it when it's fixed.  

https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md

**Comment by PsMaster** [comment]
We're using 3rd party services which we have no control of, they provide about 40 services which use common types but each service has different namespaces. When I add the references none of the types are reused, no matter where the common assemblies are placed (same or reference project). Tried adding DataContract attributes with or without namespaces, it just doesn't work. A huge blocker since we can't properly integrate to third party services. 
The only option at this point would be to use 40 different namespaces and map between all types, which is just crazy in terms of development time, performance and maintenance...

**Comment by StephenBonikowsky** [comment]
@dasetser The [wcf-web-service-reference-guide](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide#release-notes) mentions looking at the Release notes for "Known Issues".

Currently the Release notes doesn't mention any known issues, can we add a section in there with this issue?

**Comment by mishael-o** [comment]
Has there been any traction or work around on this, as we are currently stuck when migrating our existing software to .net core.

**Comment by StephenBonikowsky** [comment]
We are working on the last couple of fixes for the dotnet-svcutil 2.0.3 release which is expected to be completed soon.
This issue is planned for the following release dotnet-svcutil 2.0.4.

**Comment by conckrish** [comment]
Any workaround for this issue?

**Comment by PhilPJL** [comment]
@dasetser 

I've managed to fix this bug locally, but I'm not 100% confident my solution is correct since I had to turn off assembly signing.

Steps:

1. Download latest source
2. Turn off assembly signing in the dotnet-svcutil-lib project or it won't build for me (no .snk)
3. I need to apply the fix mentioned here [https://github.com/dotnet/wcf/issues/4308](https://github.com/dotnet/wcf/issues/4308) so I can debug using NoBootstrap (-nb)
4. Comment out the contents of "...\wcf\src\dotnet-svcutil\lib\src\FrameworkFork\System.Runtime.Serialization\System\Runtime\Serialization\DataContractAttribute.cs" and DataMemberAttribute.cs

The problem I found when debugging is that TryGetDCAttribute fails to find the DataContractAttribute.  Then all referenced types get the default namespace "http://schemas.datacontract.org/2004/07/" which causes the issue with reuse.

```
        internal static bool TryGetDCAttribute(Type type, out DataContractAttribute dataContractAttribute)
        {
            dataContractAttribute = null;

            // Problem: GetCustomAttributes returns empty collection
            object[] dataContractAttributes = type.GetTypeInfo().GetCustomAttributes(Globals.TypeOfDataContractAttribute, false).ToArray();
            if (dataContractAttributes != null && dataContractAttributes.Length > 0)
```

Below, with my fix, the test type 'CompositeTypeWithNamespace' gets the correct namespace and Reference.cs is generated correctly.

I'm not 100% sure this is a valid fix because I've had to turn of assembly signing, which may be the reason GetCustomAttributes never returns anything.

![image](https://user-images.githubusercontent.com/271656/87658421-12835a80-c754-11ea-8b32-b6562afb5067.png)

[test.zip](https://github.com/dotnet/wcf/files/4930695/test.zip)

**Comment by SamJongenelen** [comment]
Any update on the progress @imcarolwang ?

**Comment by pekkah** [comment]
Any update on this? Causing major headache in government projects where Soap is the new thing.

**Comment by PhilPJL** [comment]
Hey it's priority 1.  Must be fixed soon.

![image](https://user-images.githubusercontent.com/271656/110924004-6e20da80-8319-11eb-9b68-eec21f38e1e6.png)

Wait, it's been priority 1 for a year.  Hmmm.  Stopped holding breath a long time ago.

**Comment by StephenBonikowsky** [comment]
@mconnew @HongGit

**Comment by haldiggs** [comment]
> We have 12 WCF service which are using shared namespaces. Any workaround for this issue? Thanks

I am in the same boat. I need the contracts that have namespaces to be reused. Not a low priority. Production needs to be production and use correct namespaces.

**Comment by PhilPJL** [comment]
![image](https://user-images.githubusercontent.com/271656/113261790-c79c7980-92c7-11eb-9314-efd9bcf3bf40.png)

**Comment by haldiggs** [comment]
I had really hoped that. Net 5.0 would have heralded the fix for this issue. Having duplicate objects generated all over the place creates its own little personal hell and sync issue. 

We work with banks and other Financial entities that don't just jump up and change their code every year because we have a new version. This issue really need some attention. Of course the workaround is to simply delete all the references that the generator generates. It's not pretty and you better hope the next guy understands what you did

**Comment by pekkah** [comment]
As an workaround we use AutoMapper to map between the same types in different namespaces. Our mapping profile automatically creates maps between same named types in given namespaces. This works but as the object graphs are complicated it adds a large performance penalty to the code. Maintenance is also tedious.

**Comment by lisyandi** [comment]
Any solution for this issue?

**Comment by brewfreedom** [comment]
This is pathetic. I swore this also used to work. A decade ago or so. Can we get a commitment to see this fixed by 2030?

**Comment by imcarolwang** [comment]
This is fixed in the latest release of the tool, download it from [nuget.org](https://www.nuget.org/packages/dotnet-svcutil) to get the fix.
