### ISSUE TITLE
calling web service (username, password credentials) from .net core 2.2 web api 

### ISSUE THREAD

**Issue by Srinivas289** [dotnet/wcf#3822]
**Describe the bug**
I am trying to consume a web service with, "WS-Security defined schema to pass user name and password in clear text on HTTPS" in dotnet core 2.2 (tried on 2.1 as well).

But I am getting, following error

 Invalid Authentication - Username Password not found - possible security namespace mismatch

**To Reproduce**
Call stack,
at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
— End of stack trace from previous location where exception was thrown —
at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
at generatedProxy_1.ProcessMessage(ProcessMessageRequest )

**Expected behavior**
If we try to consume same service in .Net Framwork 4.5, it is working.

**Screenshots**

**Additional context**

**Comment by StephenBonikowsky** [comment]
@Srinivas289 Thank you for reporting this issue.
We need additional information.

Which WCF Core packages are you using? (version)
Can you send us your binding information, we need to know how you are using WCF.
The more client side code you can send us the better.

**Comment by Srinivas289** [comment]
thanks @StephenBonikowsky for your response.

I am not using any WCF Core packages.

I am trying to invoke a 3rd party service, using their WSDL. The header for the request should be in following format

<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Header>
<wsse:Security soapenv:mustUnderstand="1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<wsse:UsernameToken>
<wsse:Username>UserName</wsse:Username>
<wsse:Password>PassWord</wsse:Password>
</wsse:UsernameToken>
</wsse:Security>
</soapenv:Header>



To consume that service, following is the my code,


ThirdParyService svc = new ThirdParyService(binding, address);
svc.ClientCredentials.UserName.UserName = "Username";
svc.ClientCredentials.UserName.Password = "Password";

await svc.InvokeMethod();

But looks like, username password are not included in the request from dotnet core and the error says,
**Invalid Authentication - Username Password not found - possible security namespace mismatch**


Note: The same functionality is already implemented in .Net Framework 4.5, using custom binding. But most of the classes used are not exists in dotnet core. Following are few classes,method used, 

SymmetricSecurityBindingElement.CreateSecureConversationBindingElement()
SecurityBindingElement.CreateUserNameOverTransportBindingElement();

If, I tried to follow same custom bindings, I am getting following error,
**System.PlatformNotSupportedException: TransportSecurityBindingElement.BuildChannelFactoryCore is not supported**

**Comment by Srinivas289** [comment]
I got the issue resolved with help of following interfaces/classes,

- MessageHeader
- IClientMessageInspector
- IEndpointBehavior

**Comment by 8600272825** [comment]
Hi,

I am facing same issue. Can i tell us what changes you have done in
MessageHeader
IClientMessageInspector
IEndpointBehavior
