### ISSUE TITLE
Can't Update WCF Web Service Reference Provider due Microsoft.Xaml.Behaviors.Wpf

### ISSUE THREAD

**Issue by Rynaret** [dotnet/wcf#3827]
**Describe the bug**
I'm trying to update a WCF service by Microsoft WCF Web Service Reference Provider. But get the exception. 

```
Resolving project references ...
Importing web service metadata ...
Number of service endpoints found: 1
Scaffolding service reference code ...
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:service[@name='ForecastService']/wsdl:port[@name='BasicHttpBinding_IForecastService']
Warning:Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: Could not load file or assembly 'System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IForecastService']
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:portType[@name='IForecastService']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='BasicHttpBinding_IForecastService']
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Error:Error: No code was generated.
If you were trying to generate a client, this could be because the metadata documents did not contain any valid contracts or services, or because all contracts/services were discovered to exist in --reference assemblies. Verify that you passed all the metadata documents to the tool.
Done.
```

**To Reproduce**
1. Create WPF core 3.0 project
2. Add package `Microsoft.Xaml.Behaviors.Wpf 1.0.1`
3. Add a WCF web service reference to a project

https://github.com/Rynaret/WeatherApp

**Expected behavior**
Successful update of the WCF reference.

**Screenshots**
![image](https://user-images.githubusercontent.com/22418129/63216866-a3b51000-c144-11e9-9191-ca6966edf28d.png)

**Additional context**
I have noticed this behavior creating a project https://github.com/Rynaret/WeatherApp. If I remove `Microsoft.Xaml.Behaviors.Wpf 1.0.1` update is working as expected.

**Comment by dasetser** [comment]
@Rynaret When I add this reference to a project (or restoring your project) I get the following warning:
```
Warning	NU1701	Package 'Microsoft.Xaml.Behaviors.Wpf 1.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.
```

It looks like this package only supports .NET Framework, not .NET Standard or .NET Core. Are you doing something to use these APIs successfully in a .NET Core project? I'm not sure why you would want to reference a full framework package in a .NET Core project.

This is caused by our logic when trying to reuse types in your referenced assemblies. We don't know how to handle a full framework assembly referenced by a .NET Core project. You should be able to avoid this error in the WCF Web Service Reference provider if you uncheck the "Reuse types in referenced assemblies" checkbox when adding it.

**Comment by Rynaret** [comment]
@dasetser Thank you for the response! 

> uncheck the "Reuse types in referenced assemblies" checkbox when adding it.

It has helped me.
