### ISSUE TITLE
dotnet-svcutil - update documentation for all options

### ISSUE THREAD

**Issue by Thraka** [dotnet/wcf#3831]
Hello,

The page for the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) doesn't have all of the information, such as command line options, that the [old WCF tool has](https://docs.microsoft.com/en-us/dotnet/framework/wcf/servicemodel-metadata-utility-tool-svcutil-exe).

The dotnet docs repo received a bug talking about how the user can't get the `/namespace` option to work on the old WCF tool in a .NET Core project. I wanted to point them to the .NET Core topic but there is literally no information about what options are available on the tool so I cannot guide the user correctly.

**Comment by StephenBonikowsky** [comment]
@dasetser to talk with Doc folks to get the help doc ported.

**Comment by HongGit** [comment]
This has already been done, see [doc](https://github.com/dotnet/wcf/tree/main/src/dotnet-svcutil#using-dotnet-svcutil).
