### ISSUE TITLE
Inconsistent signing used in  4.6.0 Preview8

### ISSUE THREAD

**Issue by jrinker03** [dotnet/wcf#3833]
This is related to #3787 and @StephenBonikowsky since he handled the referenced issue.

Within the same package for 4.6.0 Preview 8, the same DLL is signed differently in different directories.

```
C:\Users\jamesri>sn -Tp C:\Users\jamesri\.nuget\packages\system.servicemodel.http\4.6.0-preview8.final\lib\netstandard2.0\System.ServiceModel.Http.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key (hash algorithm: sha1):
002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9
f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad2361321
02900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93
c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc09334
4d5ad293

Public key token is b03f5f7f11d50a3a

C:\Users\jamesri>sn -Tp C:\Users\jamesri\.nuget\packages\system.servicemodel.http\4.6.0-preview8.final\ref\netstandard2.0\System.ServiceModel.Http.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key (hash algorithm: sha1):
0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67
871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0b
d333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307
e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c3
08055da9

Public key token is 31bf3856ad364e35
```
Unfortunately VS by default picks the assembly from the _ref_ directory so this leads to issues like  #3787 since the expected public key token b03f5f7f11d50a3a matches what is from previous packages.

**Comment by StephenBonikowsky** [comment]
@jrinker03 really sorry about this. We already discovered this and fixed it with #3830 this should have been part of the first fix but we didn't catch that the ref assemblies were also a problem.

Trying to get this out with the next release (preview9).

**Comment by jrinker03** [comment]
OK, thanks Stephen.  Looking forward to Preview 9

**Comment by odrozd** [comment]
While I am in debug and try to inspect any variable I am seeing error like:

The type 'BasicHttpBinding' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.ServiceModel, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

May it be related to this issue?
