### ISSUE TITLE
contractRef should be supported bu the Microsoft WCF Web Service Reference Provider tool

### ISSUE THREAD

**Issue by yuriy-zatuchnyy-prax** [dotnet/wcf#3845]
**Describe the bug**
I have a commercial we service which URL looks like https://<*>?wsdl
It uses Digest authentication. If seen in a browser it gives back xml like follow:

`<discovery xmlns="http://schemas.xmlsoap.org/disco/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<contractRef ref="<some url>" xmlns="http://schemas.xmlsoap.org/disco/scl/"/>
...
</discovery>`

I am using VS 2019.
I can add the service reference to .Net Framework project.
But the Microsoft WCF Web Service Reference Provider tool give me an error in both cases (Go and Discover). I have tried to remove add "?wsdl" but it did not helped either.

![image](https://user-images.githubusercontent.com/52656380/63862725-f5f7fb80-c9a4-11e9-883a-799ae60609d9.png)

or 
![image](https://user-images.githubusercontent.com/52656380/63862903-41aaa500-c9a5-11e9-9aa8-7f07bbff0068.png)

If I save the xml to a file, the tool  does not find any services: 

![image](https://user-images.githubusercontent.com/52656380/63862351-58043100-c9a4-11e9-9f23-8dfffa127edd.png)

Could you add contractRef support to the tool please?

**Comment by dasetser** [comment]
@yuriy-zatuchnyy-prax Try navigating to the url but replacing ?wsdl with ?singleWsdl, saving the wsdl file, and adding that. Just the normal wsdl document can contain references to other xsd files that the tool won't be able to access if they're behind authentication. Using ?singleWsdl should include the information from those xsd files into the wsdl and allow the tool to work correctly.

**Comment by yuriy-zatuchnyy-prax** [comment]
@daseter Well, the tool which full framework is using is able to process the service right. I tried to add each contractRef as separate service, and it did worked. I still prefer the way how it is working for full framework project if it is possible.

**Comment by dasetser** [comment]
@yuriy-zatuchnyy-prax I misunderstood the problem originally, now I understand what you mean. It sounds like your service is using the disco protocol to define where the metadata is (which is what the contractRef is used for). This protocol is deprecated, so the tool does not currently support it (unlike Add Service Reference and svcutil).

This is something we could look into adding support for if more customers run into this problem, so I'll keep this issue open and add it to our backlog. However, for now I'd suggest downloading the metadata files beforehand and passing them into the tool. You can do this manually in the browser like you mentioned, or use the svcutil tool to download them with `svcutil /t:metadata`.

**Comment by dasetser** [comment]
The work required to add support for this is too much to be justified for a deprecated protocol in a new tool. Please use the workaround I mentioned above to manually download the metadata and generate the proxy using that.
