### ISSUE TITLE
[P2] Support System.IdentityModel.Selectors.SecurityTokenProvider

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#3853]
| APIs | Port/Implement | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
abstract class S.IM.Selectors.SecurityTokenProvider | <ol><li>[x] Merged</li></ol> | <ol><li>[x] Added</li></ol> | <ol><li>[x] Unit <li>[x] Scenario</li></li></ol> |
ctor S.IM.Selectors.SecurityTokenProvider() | <ul><li>[x] Merged</li></ul> | <ul><li>[x] Added</li></ul> | <ul><li>[x] Unit <li>[x] Scenario</li></li></ul> |
***
**API Notes**
***
**Implementation Notes**
Ported methods as is but will need to re-work them to support Task based methods.
***
**Public Contract Notes**

- Public Contract: System.ServiceModel.Primitives

***
**Testing Notes**
- Unit tests are required.
- Scenario tests needed: ???

***
**PR Links**
Added to the public contract with: #3877
Implementation and Unit tests added with: #3931
Scenario tests tracked by: #4022

**Comment by HongGit** [comment]
#3872
