### ISSUE TITLE
OperationFormatUse.Encoded not adding "encodingStyle" attribute to generated SOAP message

### ISSUE THREAD

**Issue by maheshnlrb** [dotnet/wcf#3870]
- [x] master (#4001) Issue for adding a scenario test: #4005
- [x] release/3.1.0 (pr #4021)

I have a soap service that needs RPC encoded messages as input.
 The generated reference.cs class correctly added the following attribute to definition
        `[XmlSerializerFormatAttribute(Style=OperationFormatStyle.Rpc, SupportFaults=true, Use=OperationFormatUse.Encoded)]`

BUT generated SOAP message does not contain the required `s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"` attribute.

This is the generated message body.
`<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <q1:eServContactQueryById xmlns:q1="http://siebel.com/asi/">
      <PrimaryRowId xsi:type="xsd:string">1-14UFS15</PrimaryRowId>
    </q1:eServContactQueryById>
  </s:Body>`

For testing, I changed the XmlSerializerFormatAttribute to `[XmlSerializerFormatAttribute(SupportFaults=true )]` and this is what I got in body

`<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <eServContactQueryById xmlns="http://siebel.com/asi/">
      <PrimaryRowId>1-14UFS15</PrimaryRowId>
    </eServContactQueryById>
  </s:Body>`

Searching in source code, I did find a method `GetEncoding` in class `XmlSerializerOperationFormatter` that should give the correct value for the attribute, but this method is not being called from anywhere. 

NOTE: This seems to be related to bug  #2359

M

**Comment by StephenBonikowsky** [comment]
@maheshnlrb thanks for reporting this.
Looks like we are missing some lines of code, it should be a fairly simple fix.
Adding to our next release milestone.

**Comment by StephenBonikowsky** [comment]
PR exists...
https://github.com/dotnet/wcf/pull/3891

Just need to fix the commit history.

**Comment by StephenBonikowsky** [comment]
Closed PR #3891 and opened #4001 instead.

**Comment by StephenBonikowsky** [comment]
Completed.
