### ISSUE TITLE
[P0] Support WCF usage of SecurityToken from MSAL.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#3871]
# This Issue is a place holder for work we know will need to be done in WCF but we can't know what that work will be until MSAL provides WCF with their representation of a SecurityToken which WCF will then need to adapt for WCF internal use.

| APIs | Port/Implement | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
API 1 | <ol><li>[ ] Merged</li></ol> | <ol><li>[ ] Added</li></ol> | <ol><li>[ ] Added</li></ol> |
API 2 | <ul><li>[ ] Merged</li></ul> | <ul><li>[ ] Added</li></ul> | <ul><li>[ ] Added</li></ul> |
API 3 | <ul><li>[ ] Merged</li></ul> | <ul><li>[ ] Added</li></ul> | <ul><li>[ ] Added</li></ul> |
***
**API Notes**
- API 1: \<Your notes or comments here.\>
- API 2: \<Your notes or comments here.\>
***
**Implementation Notes**
- \<Your notes or comments here.\>
***
**Public Contract Notes**
- API 1: \<The contract this API be added to.\>
- API 2: \<The contract this API be added to.\>
- API 3: \<The contract this API be added to.\>
***
**Testing Notes**
- \<Scenario tests needed?\>

**Comment by HongGit** [comment]
This becomes obsolete as we take Microsoft.IdentityModel.xxx from Azure Identity team.
