### ISSUE TITLE
Calling Open on ICommunication leaves async timer running which closes socket.

### ISSUE THREAD

**Issue by peteri** [dotnet/wcf#3895]
**Describe the bug**
If Open is called on a netTcp connection (unsure about other types) then if a ServiceContract method is invoked AFTER the open time has expired then the socket will have been closed.

This appears to be due the BeginWriteCore method in SocketConnection.cs starting an timer for  asynchronous send operations. The EndWrite method does not cancel the _sendTimer which expires and closes the socket.

Calling a method sends synchronously which calls SetWriteTimeout with synchronous set to true. SetWriteTimeout then clears the _sendTimer by cancelling it.

 I believe this is new as the calls to System.Net.NegotiateStream is now async (comparing to the reference source code)

**To Reproduce**
Add and run the test in this commit (I used Binding.Tcp.IntegrationTests)
https://github.com/peteri/wcf/commit/cd6d1f1bbce4234e799d4e218219607c38c0ad8b

Apologies for the "hacky" nature of this as I can't build the current master so tested on the release/2.1.0 branch and the Thread.Sleep.

**Expected behavior**
Calling Open does not abort the connection.

**Comment by peteri** [comment]
Reference source code version ends up calling this code:
https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System/net/System/Net/SecureProtocols/_NegoStream.cs

**Comment by StephenBonikowsky** [comment]
@peteri Thanks for reporting this! We will target this fix for the next release before the end of the year.

**Comment by peteri** [comment]
Sorry about the test being quite so crappy (I hate using Thread.Sleep) but at least it gives you something to work with.

**Comment by mconnew** [comment]
@peteri, I think you can make test methods async and do `await Task.Delay(1000)` instead.

**Comment by StephenBonikowsky** [comment]
Potentially fixed by https://github.com/dotnet/wcf/pull/3994

**Comment by StephenBonikowsky** [comment]
The PR has been merged, the change will be part of 3.1 preview3 which will be released sometime in November.
