### ISSUE TITLE
Apply EditorBrowsableAttribute to contract items which aren't functioning

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#3898]
- [x] master (#4016)
- [x] release/3.1.0 (pr #4021)

Some of the API's on our contract aren't usable. For example, SecurityTokenManager.CreateSecurityTokenAuthenticator has been added as it is an abstract method on an abstract class and without it, you can't derive SecurityTokenManager in a way which will work on .NET Framework on .NET Core. We also have many api's which accept a configuration name such as a constructor for CustomBinding.  

By adding the EditorBrowsableAttrribute to these api's with the state EditorBrowsableState.Never we prevent these api's from being shown by intellisense when using our contract.

**Comment by StephenBonikowsky** [comment]
Done
