### ISSUE TITLE
Add support to specify SSL/TLS version for NetTcp with certificate security

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#39]
On .Net 4.5.x and earlier, NetTcp with certificate security was only able to use SSL3.0 and TLS1.0 when upgrading the transport to use certificate security. Support was added to .Net 4.6 to allow specifying the version of SSL/TLS to use. The following properties need to be added (both of type System.Security.Authentication.SslProtocols):

System.ServiceModel.TcpTransportSecurity.SslProtocols
System.ServiceModel.Channels.SslStreamSecurityBindingElement.SslProtocols

This issue is blocked on Certificate support being added to NetTcp.

**Comment by iamjasonp** [comment]
Resolved as part of #308
