### ISSUE TITLE
[P1] Support System.ServiceModel.FaultException

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#3911]
| APIs | Port/Implement | Public Contract | Testing |
| :------------ | :-------------: | :------------: | :------------: |
ctor FaultException(TDetail detail, string reason) | <ol><li>[x] Merged</li></ol> | <ol><li>[x] Added</li></ol> | <ol><li>[x] Unit <li>[x] Scenario</li></li></ol> |
***
**API Notes**
***
**Implementation Notes**
Already ported.
***
**Public Contract Notes**
Add to System.ServiceModel.Primitives
***
**Testing Notes**
- Unit tests are required.
- Scenario tests needed: ???
***
**PR Links**
Added to the PC with: #3930
Unit tests: #3959
Scenario tests tracked by: #4022

**Comment by wouterroos** [comment]
Hi, 

Any ETA on when this will be available? Will it be in the 4.7.0 release? Is there also a possibility to expose this one as well? 

https://github.com/dotnet/wcf/blob/f0b3b4935eb97807dbed7b73f25fbf160a523eac/src/System.Private.ServiceModel/src/System/ServiceModel/FaultException.cs#L330

Regards,

Wouter

**Comment by StephenBonikowsky** [comment]
@wouterroos All the new APIs we exposed for the WSFederation feature are available as part of the .NET Core 3.1 preview1 release.
https://github.com/dotnet/wcf/releases/tag/v3.1.0-preview1
Please be aware that not all WSFederation scenarios are enabled and that it is a work in progress, let us know if you run into any problems using any of the new APIs.

I'll follow-up regarding the additional FaultException ctor you've requested.

**Comment by wouterroos** [comment]
@StephenBonikowsky Great, let me know if I can be of any assistance.

**Comment by wouterroos** [comment]
@StephenBonikowsky any update on whether this constructor can be added?
