### ISSUE TITLE
Web Reference .NET Framework 2.0  is not compatible with .NET Core

### ISSUE THREAD

**Issue by Sammi-Ullah** [dotnet/wcf#3922]
I am working on Asp.net Core 2.2 WebApi and Unable to add Web Reference .NET Framework 2.0 it's works for standard .Net Framework but Not with Asp.net Core

**Comment by StephenBonikowsky** [comment]
@Sammi-Ullah That is correct and by design. If you want to try and use the more recent '[WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)'. And see if that does what you need.
