### ISSUE TITLE
Adding MS Dynamics Business Central SOAP web service to .net core project

### ISSUE THREAD

**Issue by ara3n** [dotnet/wcf#3933]
I have a SOAP webservice that when opened looks like this.  I can add this to .net 4.7 project as web reference it finds all the endpoints but in WCF web service reference it does not.  
I have to add each reference one by one in Order for see them in my .net core project. 

<discovery><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/SystemService"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Codeunit/ADCS"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Codeunit/M365Mgmt"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365BinContent"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365Item"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ItemJnlLine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ItemVariant"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365Location"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365LotsByBin"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ProdOrder"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ProdOrderCompLine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ProdOrderLine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ProdOrderRoutingLine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365ScrapCode"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WAHeader"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WALine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WarehouseEmployee"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WarehouseEntries"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WhseJnlLine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WRHeader"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WRLine"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WSHeader"/><contractRef ref="http://morpheus:7047/DynamicsNAV100/WS/Page/M365WSLine"/></discovery>

[Services.txt](https://github.com/dotnet/wcf/files/3658210/Services.txt)

**Comment by ara3n** [comment]
[salesDocumentLines.xml.txt](https://github.com/dotnet/wcf/files/3658403/salesDocumentLines.xml.txt)

**Comment by StephenBonikowsky** [comment]
@dasetser This has to do with supporting Disco, can you take a look?

**Comment by ara3n** [comment]
I tested with VS 2019 16.3 and it's working.  Thank you.

**Comment by StephenBonikowsky** [comment]
Great! Let us know if we can help with anything else.
