### ISSUE TITLE
Support for System.ServiceModel.Description.MetadataExchangeClient

### ISSUE THREAD

**Issue by nabinpuri** [dotnet/wcf#3934]
When will System.ServiceModel.Description.MetadataExchangeClient be avaialable? or Is this even going to be supported?
Also, other missing types from https://github.com/microsoft/referencesource/tree/master/System.ServiceModel/System/ServiceModel/Description will be supported in near future?

**Comment by StephenBonikowsky** [comment]
@nabinpuri We are regularly adding support in WCF Core for features from the full framework. MetadataExchangeClient is part of the task to support IWsdlImportExtension which is quite a large feature. This work is not currently planned.

We have been focused on some higher priority feature areas such as WS Federation.
