### ISSUE TITLE
VS2019 16.4.0 Add WCF Web Service Reference using WSDL failed: access denied on nuget.config

### ISSUE THREAD

**Issue by msneijders** [dotnet/wcf#3949]
Using this tool to add a web service, if fails with the error message:

Access to the path '..\AppData\Local\Temp\WCFConnectedService\2019_Oct_04_13_04_54\svcutil_starter\nuget.config' is denied.

This folder is newly created by the tool I assume, the file nuget.config in it is marked 'read-only'.

**Comment by msneijders** [comment]
In a completly new and empty solution with single new .net core project, adding the same WCF Web Service Reference WSDL is succeeding. The solution that fails adding is a mixture of (full) .net framework projects en .net core project, perhaps something collides?

**Comment by StephenBonikowsky** [comment]
@msneijders It sounds like the WCFConnected Service has found an existing nuget.config that is part of one of the other projects and copied it over. If that nuget.config was already read-only it would have kept it as such. Can you check that?

**Comment by msneijders** [comment]
Ah, and now I found the nuget.config also. It was at the same folder level as the project folder. It was under source control, checking it out and WCFConnected Service seems not to be bothered by it anymore. Thank you @StephenBonikowsky I wouldn't have guessed the tool would copy this file.

**Comment by StephenBonikowsky** [comment]
No problem, glad it was an easy solution :)
