### ISSUE TITLE
.NET Core WCF ready to use?

### ISSUE THREAD

**Issue by alejandro5042** [dotnet/wcf#3953]
Is there a nuget with the .NET Core versions of WCF? It's not super clear currently--the nugets linked from https://github.com/dotnet/wcf are over a year old; e.g. https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.ServiceModel.Http

If not, what is the plan for being ready?

**Comment by StephenBonikowsky** [comment]
@alejandro5042 sorry for the delay in answering you.
Those links in the Readme.md were out-of-date.
I have just created PR #3981 to fix that.

We have been shipping WCF Core nuget packages for quite a while now, we use to put pre-release and daily builds on MyGet but stopped doing that, we have always published public releases including preview versions to NuGet.

You can review all of our [release tags](https://github.com/dotnet/wcf/releases) and follow links to the packages on NuGet.

**Comment by alejandro5042** [comment]
Thank you for updating the README. It's much clearer now, thanks!
