### ISSUE TITLE
BasicHttpBinding does not automatically add Authorization HTTP header

### ISSUE THREAD

**Issue by gthvidsten** [dotnet/wcf#3955]
**Description**
When setting up `BasicHttpBinding` and setting UserName+Password on the client, the `Authorization` HTTP header is not added to the request

**To Reproduce**
1. Use the `Add > Service Reference...` functionality in Visual Studio to create web service reference classes from WSDL
2. Use this code, as described in numerous places online to set up a client to use basic authentication:
```
BasicHttpBinding binding = new BasicHttpBinding();
binding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

EndpointAddress endpoint = new EndpointAddress("http://address.to.webservice/");

WebserviceClient client = new WebserviceClient(binding, endpoint);
client.ClientCredentials.UserName.UserName = "YourUsername";
client.ClientCredentials.UserName.Password = "YourPassword";

getSomethingResponse result = client.getSomethingAsync(new getSomething()).Result;
```

3. Inspect the network traffic using Fiddler/Wireshark
4. Observe that the request does not contain a `Authorization` HTTP header

**Expected behavior**
The request should contain a `Authorization` HTTP header

**Screenshots**
![Annotation 2019-10-09 120322](https://user-images.githubusercontent.com/8248605/66472149-eb914d00-ea8c-11e9-9267-f7d96aebc557.png)

**Comment by mconnew** [comment]
Do you get an authentication challenge response and then WCF sends the request again with an Authentication header? This could be a difference in behavior between HttpClientHandler on .NET Core and HttpWebRequest on .NET Framework. We do set the PreAuthentication property to true, but if my memory is correct, HttpClientHandler is a lot more conservative about sending headers with a challenge first.

**Comment by gthvidsten** [comment]
In Wireshark I can't see any other HTTP message being exchanged other than the HTTP POST I already provided a screenshot of.

**Comment by mconnew** [comment]
@gthvidsten, does the response contain a `WWW-Authenticate` authentication challenge header? What is the HTTP response status code? Is it returning a 401 Unauthorized status, or a 403 Forbidden status or something else?

**Comment by StephenBonikowsky** [comment]
@gthvidsten please feel free to re-open this issue if you can provide the info that @mconnew requested.
Thanks.

**Comment by gthvidsten** [comment]
The HTTP response status code from the server is `500 Internal Server Error`, and does not contain a `WWW-Authenticate header`.
Only when I manually insert an `Authorization` header (through code) does the server respond with actual data. All other requests results in a 500.

**Comment by JuHwon** [comment]
@gthvidsten i am having the same issue with a 3rd party soap service, did you find any solution exception building/setting the header yourself?

**Comment by hxchintakunta** [comment]
@gthvidsten Can you give me some references on how to set Authorization header through code using BasicHttpBinding .

**Comment by Eccenux** [comment]
LOL. 5 years and this wasn't even re-opened. .NET is great 😜

This is how you can encode credentials manually:
```csharp
using System;
using System.Text;

public class BasicAuthHelper
{
    public static string Header(string login, string password)
    {
        string loginPassword = $"{login}:{password}";
        string base64EncodedLoginPassword = Convert.ToBase64String(Encoding.UTF8.GetBytes(loginPassword));
        string authHeader = $"Basic {base64EncodedLoginPassword}";
        return authHeader;
    }
}

// Usage example:
string login = "YourLogin";
string password = "Your Pass / Key";
string basicAuthHeader = BasicAuthHelper.Header(login, password);
```

So this is kind of simple... But .NET seems to require doing things the hard way (unless you can find a way to add custom header to the request)...

**IClientMessageInspector impl**
```csharp
using System;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Dispatcher;
using System.Text;

public class BasicAuthMessageInspector : IClientMessageInspector
{
    private string _authHeader;

    public BasicAuthMessageInspector(string username, string password)
    {
        string encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{username}:{password}"));
        _authHeader = $"Basic {encoded}";
    }

    public void AfterReceiveReply(ref Message reply, object correlationState) { }

    public object BeforeSendRequest(ref Message request, IClientChannel channel)
    {
        HttpRequestMessageProperty httpRequestMessage;
        if (request.Properties.ContainsKey(HttpRequestMessageProperty.Name))
        {
            httpRequestMessage = (HttpRequestMessageProperty)request.Properties[HttpRequestMessageProperty.Name];
        }
        else
        {
            httpRequestMessage = new HttpRequestMessageProperty();
            request.Properties.Add(HttpRequestMessageProperty.Name, httpRequestMessage);
        }

        httpRequestMessage.Headers["Authorization"] = _authHeader;
        return null;
    }
}
```
**IEndpointBehavior impl**
```csharp
public class BasicAuthEndpointBehavior : IEndpointBehavior
{
    private string _username;
    private string _password;

    public BasicAuthEndpointBehavior(string username, string password)
    {
        _username = username;
        _password = password;
    }

    public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters) { }

    public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
    {
        clientRuntime.ClientMessageInspectors.Add(new BasicAuthMessageInspector(_username, _password));
    }

    public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher) { }

    public void Validate(ServiceEndpoint endpoint) { }
}
```

**Usage**:
```csharp
var client = new ServiceReference1.YourServiceClient(binding, new EndpointAddress("https://example.com/someapp/services/theservice"));

string login = "YourLogin";
string password = "Your Pass / Key";
client.Endpoint.EndpointBehaviors.Add(new BasicAuthEndpointBehavior(login, password));
```
