### ISSUE TITLE
Missing Members From SecurityBindingElement and SecurityAlgorithmSuite

### ISSUE THREAD

**Issue by bassem-mf** [dotnet/wcf#3957]
Hello! I am trying to migrate a .Net Framework project to .Net Core 3.0. But my code does not compile because of missing members.

Here is the code I am trying to migrate:

```
var binding = new CustomBinding();
TransportSecurityBindingElement transportSecurityBindingElement = SecurityBindingElement.CreateUserNameOverTransportBindingElement();
transportSecurityBindingElement.DefaultAlgorithmSuite = SecurityAlgorithmSuite.Basic128;
transportSecurityBindingElement.SetKeyDerivation(true);
transportSecurityBindingElement.SecurityHeaderLayout = SecurityHeaderLayout.Lax;
transportSecurityBindingElement.IncludeTimestamp = true;
transportSecurityBindingElement.MessageSecurityVersion = MessageSecurityVersion.WSSecurity11WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10;
transportSecurityBindingElement.LocalClientSettings.DetectReplays = false;
transportSecurityBindingElement.LocalServiceSettings.DetectReplays = false;
binding.Elements.Add(transportSecurityBindingElement);
```

It does not compile because the following members are missing:

System.ServiceModel.Security.SecurityAlgorithmSuite.Basic128
System.ServiceModel.Channels.SecurityBindingElement.LocalServiceSettings

Are there any plans to add these members to the WCF client libraries? If Yes, when do you think they will be added?
Is there a way to do this same binding configuration using other members that are currently supported?

unfortunately we have no control over this service and we cannot make any changes to it. And this issue is preventing us from moving our client application to .Net Core. So any help will be greatly appreciated.

**Comment by StephenBonikowsky** [comment]
@bassem-mf we'll add SecurityAlgorithmSuite.Basic128 to the contract in our 3.1 release.
We'll double check the other members you listed in your code and make sure they are also present.

You shouldn't need SecurityBindingElement.LocalServiceSettings as that is for server side functionality only.

**Comment by StephenBonikowsky** [comment]
@mconnew it doesn't look like [SecurityBindingElement.SetKeyDerivation](https://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/Channels/SecurityBindingElement.cs,408) is supported either.

It looks like all the code is there but it goes into System.ServiceModel.Security.Tokens and at that point I'm not sure if it something we can add to the contract without any further work. Could you take a look?

**Comment by bassem-mf** [comment]
Thank you so much guys for looking into that!

**Comment by mconnew** [comment]
It looks like derived keys isn't supported. You can see the [comment here](https://github.com/dotnet/wcf/blob/2b2c6aafb4037c6b14494779cdac597e3e250d30/src/System.Private.ServiceModel/src/System/ServiceModel/Security/SendSecurityHeader.cs#L547) where I didn't bring in the implementation for derived keys. I had a quick look to get an idea of how much work it would be and it's a medium sized work item simply because the implementation is spread out all over the code base and finding the one piece of code that was missed will likely be a laborious process.

**Comment by StephenBonikowsky** [comment]
@bassem-mf We will not be able to add support for derived keys in the 3.1 time frame. We can still add Basic128 but it only makes sense doing so if it unblocks your scenario. You can investigate and make sure that you really do need `transportSecurityBindingElement.SetKeyDerivation(true);`, let us know, but for now I am moving this to our 5.0 milestone.

**Comment by bassem-mf** [comment]
We ended up commenting these 4 lines that were giving compilation errors
```
transportSecurityBindingElement.DefaultAlgorithmSuite = SecurityAlgorithmSuite.Basic128;
transportSecurityBindingElement.SetKeyDerivation(true);
transportSecurityBindingElement.LocalClientSettings.DetectReplays = false;
transportSecurityBindingElement.LocalServiceSettings.DetectReplays = false;
```
And to our surprise, the application continued to work without problems.

So the current version of the WCF client library has everything we need. Thank you so much for your help!

**Comment by StephenBonikowsky** [comment]
That's great news @bassem-mf

**Comment by nmarun** [comment]
I'm trying to consume a WCF service into our .net core 2.2 project. The configuration of the WCF project is as below:

`<binding name="GDASServFY14R22binding" hostNameComparisonMode="StrongWildcard" re
  <readerQuotas maxDepth="2147483647" maxStringContentLength="2147483647" maxArra
  <security mode="TransportCredentialOnly">
    <transport clientCredentialType="Ntlm" proxyCredentialType="None" realm="" />
    <message clientCredentialType="UserName" algorithmSuite="Default" />
  </security>
</binding>
`
In .net core I see only TripleDes for SecurityAlgorithmSuite and not Default. Is there a work-around for this?

**Comment by StephenBonikowsky** [comment]
@nmarun 
Looks like the [SecurityBindingElement ](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs#L19)uses it `SecurityAlgorithmSuite.Default`

SecurityBindingElement is used in turn by the [BasicHttpBinding ](https://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/BasicHttpBinding.cs,72)and [BasicHttpsBinding](https://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/BasicHttpsBinding.cs,76) when [BasicHttpSecurityMode ](https://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/BasicHttpSecurityMode.cs,13)is set to TransportWithMessageCredential.
