### ISSUE TITLE
The DataContractSerializerOperationBehavior.SerializationSurrogateProvider property is not available in a library netstandard 2.0

### ISSUE THREAD

**Issue by FrancescoCrimi** [dotnet/wcf#3967]
The "DataContractSerializerOperationBehavior.SerializationSurrogateProvider" property is available in library netcore but not available in library netstandard.

This https://github.com/FrancescoCrimi/DCSOB-Error is a simple solution with two same simple project one library netcore and one library netstandard, just clone with VisualStudio and open the file ServiceClient in both project to see the error in the library netstandard and not in library netcore.

I expected  to use DataContractSerializerOperationBehavior.SerializationSurrogateProvider method in the netstandard library same as netcore library. Moreover, it's no possible referece a netcore library in an UWP project but it's possible for netstandard library.

This https://github.com/FrancescoCrimi/wcf is my wcf fork with a little modify at the file System.ServiceModel.Primitives.Ref.csproj to resolve a problem, see #3968 pull request

Thanks you

**Comment by StephenBonikowsky** [comment]
@FrancescoCrimi This is expected behavior. Our latest WCF Core releases continue to support .NET Standard2.0 which is also supported by .NET Framework 4.8. This type does not exist in net4.8 so we couldn't add it to our public contract targeting .NET Standard2.0 so instead it targets netcoreapp2.1.

If I understand you correctly you want to be able to use that API from a UWP project, we could look into adding this API to our UWP public contract in an up-coming release.

Could you give us any more details about your scenario, are you migrating an application to .NET Core or writing a new application?

**Comment by FrancescoCrimi** [comment]
@StephenBonikowsky  Thanks for the reply.

I wanted to be able to use this API in a "UWP" project, in an attempt to migrate an app from "Net Framework" to "Net Core" and at the same time add a ui "UWP".

In "Net Framework" I used "DataContractSerializerOperationBehavior.DataContractSurrogate" to be able to use a custom implementation of "IList <T>" in my "Domain Models" but this is not available in "netstandard" and "netcoreapp".

**Comment by StephenBonikowsky** [comment]
@mconnew your thoughts?

**Comment by FrancescoCrimi** [comment]
Hello, i close this issue because  it is expected behavior @StephenBonikowsky and I open another one where I ask why this api does not exist in the UWP platform, see #4020

Thanks you

**Comment by mconnew** [comment]
@FrancescoCrimi, I have some good news and some bad news. The bad new is the amount of work to add this api to UWP would add too much ongoing support costs (extra testing for each release etc). The good news is I have another solution for you.  
The DataContractSerializerOperationBehavior can be derived and you can add the capability and use your derived class. This is roughly the code you will need (I haven't ran this through a compiler so there might be some minor mistakes):
```c#
public class DCSWithSurrogatesOperationBehavior : DataContractSerializerOperationBehavior
{
    public DCSWithSurrogatesOperationBehavior(DataContractSerializerOperationBehavior dcsBehavior)
        : base(null, dcsBehavior.DataContractFormatAttribute) 
    {
        MaxItemsInObjectGraph = dcsBehavior.MaxItemsInObjectGraph;
        IgnoreExtensionDataObject = dcsBehavior.IgnoreExtensionDataObject;
        DataContractResolver = dcsBehavior.DataContractResolver;
    }
    public DCSWithSurrogatesOperationBehavior() 
        : base(null) { }
    public DCSWithSurrogatesOperationBehavior(DataContractFormatAttribute dataContractFormatAttribute) 
        : base(null, dataContractFormatAttribute) { }
    public ISerializationSurrogateProvider SerializationSurrogateProvider { get; set; }
    public override XmlObjectSerializer CreateSerializer(Type type, string name, string ns, IList<Type> knownTypes)
    {
        var dcs = (DataContractSerializer)base.CreateSerializer(type, name, ns, knowntypes);
        dcs.SetSerializationSurrogateProvider(SerializationSurrogateProvider);
        return dcs;
    }
    public override XmlObjectSerializer CreateSerializer(Type type, XmlDictionaryString name, XmlDictionaryString ns, IList<Type> knownTypes)
    {
        var dcs = (DataContractSerializer)base.CreateSerializer(type, name, ns, knowntypes);
        dcs.SetSerializationSurrogateProvider(SerializationSurrogateProvider);
        return dcs;
    }
}
```

And here's how you would use it:
```c#
var factory = new ChannelFactory<IMyService>(binding, endpointAddress);
ContractDescription cd = factory.Endpoint.Contract;
foreach(var od in cd.Operations)
{
    DCSWithSurrogatesOperationBehavior newBehavior = null;
    var oldBehavior = od.OperationBehaviors.Find<DataContractSerializerOperationBehavior>();
    if (oldBehavior != null)
    {
        newBehavior = new DCSWithSurrogatesOperationBehavior(oldBehavior);
        od.OperationBehaviors.Remove(oldBehavior);
    }
    else
    {
        newBehavior = new DCSWithSurrogatesOperationBehavior();
    }
    newBehavior.SerializationSurrogateProvider = mySurrogateProvider;
    od.OperationBehaviors.Add(newBehavior);
}
```
You might wonder why I set the OperationDescription parameter to null on the base class. It's only there for the implementation of the interface IWsdlExportExtension which is a server feature so isn't available in this code base. There's no null checking on it, and it's not re-exposed via a property so it can't be copied so no need to try and do anything with it.
