### ISSUE TITLE
Remove dependency on System.Net.NameResolution from BridgeClientCertificateManager

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#397]
BridgeClientCertificateManager is using Dns.GetHostEntryAsync() which requires System.Net.NameResolution.  But N does not support this contract.

Refactor the test not to require this dependency, and also fix the TFS ToF test wrapper that added it to allow the tests to pass in CoreCLR

**Comment by iamjasonp** [comment]
ACK. Treating this as high-pri

**Comment by mconnew** [comment]
Take a look at DnsCache.cs in the repo for the NetNative equivalent.

**Comment by iamjasonp** [comment]
Thanks @mconnew - not sure why this didn't make it in, but i feel that a rebase messed me up

**Comment by iamjasonp** [comment]
For now, we don't need the certs on the BridgeClient side to use the name of the name of the machine. Change the BridgeClient side so we just use some name.
