### ISSUE TITLE
EnableUnsecuredResponse is missing in donet core

### ISSUE THREAD

**Issue by urza** [dotnet/wcf#3979]
I have working WCF Client in full .NET framework that connects to soap service that requires message credentials in requests, but doesn't send security headers in response. Full .NET Framework has **EnableUnsecuredResponse** property on SecurityBindingElement that enables this client to communicate with the service. However this is missing in net core wcf.

Code in .NET 4.8:
```
var elements = vyhledatService.Endpoint.Binding.CreateBindingElements();
elements.Find<SecurityBindingElement>().EnableUnsecuredResponse = true;
vyhledatService.Endpoint.Binding = new CustomBinding(elements);

```
EnableUnsecuredResponse is not available in donet core framework.

Without this, the requests ends with exception 

```
System.ServiceModel.Security.MessageSecurityException: Security processor was unable to find a security header in the message. This might be because the message is an unsecured fault or because there is a binding mismatch between the communicating parties.   This can occur if the service is configured for security and the client is not using security.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
```

Will this be added to net core? It would help us a lot.

Attached is example project with the service definition and connection that you can use
[KatastrAPI.zip](https://github.com/dotnet/wcf/files/3745044/KatastrAPI.zip)
.

**Comment by StephenBonikowsky** [comment]
@urza It is in our backlog of work to do, but in the meantime there is a workaround. Please see #3653 for additional details on the workaround.

Thanks!

**Comment by Tschrock** [comment]
@StephenBonikowsky Is this still in the backlog to work on? (I don't see an open issue for it, so I just want to make sure it hasn't been forgotten.) It would be great to have this supported instead of relying on a complex workaround to inject the security header.

**Comment by StephenBonikowsky** [comment]
@HongGit and @mconnew

**Comment by ph1f1** [comment]
Is this still in the backlog in 2024 or is there an official fix available by now?
