### ISSUE TITLE
DebuggerDisplay attribute of System.ServiceModel.Description.OperationDescription is incorrect

### ISSUE THREAD

**Issue by tmat** [dotnet/wcf#3987]
The attribute contains references to non-existing fields.

https://github.com/dotnet/wcf/blob/08d1b084aaa1abf75066bb5b0de808b00c7f631c/src/System.Private.ServiceModel/src/System/ServiceModel/Description/OperationDescription.cs#L14

The attribute usage also does not follow the guidelines: 
https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2019#using-expressions-in-debuggerdisplay.

Reported via VS Feedback: https://developercommunity.visualstudio.com/content/problem/787246/non-critical-error-in-various-systemservice-classe.html

**Comment by StephenBonikowsky** [comment]
This is a confirmed problem that needs to be fixed.
Can't get it into the 3.1 release but will add it to the next release.

**Comment by HongGit** [comment]
@imcarolwang  can you please look into this implementation?

**Comment by imcarolwang** [comment]
This is now fixed, closing issue.
