### ISSUE TITLE
Separate stress scenarios to the group of those that expect certain exceptions and those that don't expect exceptions (was: Stress run: intermittent System.ObjectDisposedException when accessing a channel as the channel is in the "Closed" state)

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#399]
This could be related to issue #108.

Mark it as a test issue at the time being. I will need to further investigate it to rule out test issues as the stress run recycles channels periodically. 

Note that The stress run explicitly opened the channel once before using it.

Inspect the channel object, the state System.ServiceModel.ICommunicationObject.State = Closed

CallStack:
>	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.StreamingTest.TestEchoStream(WcfService1.IStreamingService channel, int requestedStreamSize, int bufSize) Line 111	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.StreamingTest.RunAllScenarios(WcfService1.IStreamingService channel) Line 80	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.StreamingTest.UseChannel.AnonymousMethod__14_0(WcfService1.IStreamingService channel) Line 68	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.RecyclablePooledFactoriesAndChannels_OpenOnce<WcfService1.IStreamingService, SharedPoolsOfWCFObjects.StreamingTest>.UsePooledChannels.AnonymousMethod__0() Line 433	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.CallStats.CallActionAndRecordStats(System.Action action) Line 49	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.RecyclablePooledFactoriesAndChannels_OpenOnce<WcfService1.IStreamingService, SharedPoolsOfWCFObjects.StreamingTest>.UsePooledChannels() Line 430	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.RecyclablePooledFactoriesAndChannels_OpenOnce<WcfService1.IStreamingService, SharedPoolsOfWCFObjects.StreamingTest>.RunAllScenariosWithWeights(int useWeight, int recycleChannelsWeight, int recycleFactoriesWeight) Line 367	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.Program.RunAllHttpStressTests() Line 169	C#
 	SharedPoolsOfWCFObjects!SharedPoolsOfWCFObjects.Program.DoTheRun.AnonymousMethod__0() Line 60	C#

**Comment by zhenlan** [comment]
This is likely a test issue

**Comment by KKhurin** [comment]
I believe this is the issue with the stress tests mixing together the scenarios that will open and close the channel while using it and scenarios that will only open and use the channel.
Changing the title to reflect the work that needs to be done here.

**Comment by KKhurin** [comment]
This is going to be fixed as part up upcoming PR.
