### ISSUE TITLE
Fix xUnit warnings

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#4006]
- [x] master (no need to go into release/3.1.0)

Fix all of the xUnit warnings we are currently suppressing.
Add to this list below if I missed any.

- [x] xUnit1003 (master:#4011,#4042)
- [x] xUnit1006 (master:#4011)
- [x] xUnit1013 (master:#4011, #4043)
- [x] xUnit1014 (master:#4011, #4046)
- [X] xUnit1019 (master:#4049)
- [X] xUnit1024 (master:#4032)
- [x] xUnit2000 (insert PR #4019, #4053)
- [x] xUnit2006 (master:#4011,#4055)
- [x] xUnit2009 (insert PR #4024,#4060)
- [x] xUnit2010 (master:#4011,#4065)
- [X] xUnit2013 (master:#4031)

**Comment by StephenBonikowsky** [comment]
Added master and release/3.1 check boxes.
After it has been merged into master, move this issue into the "Cherry-pick to release/3.1.0" pipeline of the 'WCF Core 3.1' project.

**Comment by StephenBonikowsky** [comment]
Removed from the 3.1 project, no need to cherry-pick to 3.1 branch.

**Comment by imcarolwang** [comment]
Hi @StephenBonikowsky, I just found the PRs I submitted earlier only handled xUnit warnings in test projects under System.Private.ServiceModel, and there're more test folders/projects not checked.

I'm planning to create PRs for each xUnit warning fixing for the remaining folders. Please help review. Sorry for the extra effort/inconvenience brought.

**Comment by StephenBonikowsky** [comment]
Ok, will do.

**Comment by imcarolwang** [comment]
Close as all suppressed xUnit warnings have been removed from test projects.

**Comment by StephenBonikowsky** [comment]
Terrific, thanks @imcarolwang !
