### ISSUE TITLE
Svcutil  There was no endpoint listening at Url

### ISSUE THREAD

**Issue by gokhanfeali** [dotnet/wcf#4014]
Hi,

I added connected service to asp.net core project. Svcutil is created a Reference.cs as you can see codes . i can run project with vs2019 everything is okey but i want to publish code and run with iis so  i did ,when i call project i am getting a exception that "There was no endpoint listening at http://localhost/CustomerWS/CustomerLimitWs.svc that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details." I think service getting endpoint url in Reference.cs  when published in iis why getting endpoint url in ConnectedService.json ?

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Basic))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/CustomerWS/CustomerLimitWs.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

{
  "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
  "Version": "15.0.30730.948",
  "GettingStartedDocument": {
    "Uri": "https://go.microsoft.com/fwlink/?linkid=858517"
  },
  "ExtendedData": {
    "inputs": [
      "http://testservices/CustomerWS/CustomerLimitWs.svc"
    ],
    "collectionTypes": [
      "System.Array",
      "System.Collections.Generic.Dictionary`2"
    ],
    "namespaceMappings": [
      "*, CustomerLimitWs"
    ],
    "references": [...],
    "sync": true,
    "targetFramework": "netcoreapp2.2",
    "typeReuseMode": "All"
  }
}

**Comment by dasetser** [comment]
@gokhanfeali This exception means that WCF is trying to connect to an endpoint at a URL that a service is not listening at. It looks like as part of publishing the code to IIS you changed the URL of the endpoint, and WCF is trying to connect to the wrong one. You will need to either generate generate a new proxy by passing in the new URL to svcutil, or update the URL in code or configuration to the new URL.
