### ISSUE TITLE
"DataContractSerializerOperationBehavior.SerializationSurrogateProvider" property is not available in the UWP platform.

### ISSUE THREAD

**Issue by FrancescoCrimi** [dotnet/wcf#4020]
The "DataContractSerializerOperationBehavior.SerializationSurrogateProvider" property is not available in the UWP platform. See #3967 now close.

Thanks you

**Comment by StephenBonikowsky** [comment]
We are looking into the logistics of adding a new target framework for UAP and how to get it into the next UAP release. Will update this issue when we have more info.

**Comment by mconnew** [comment]
@FrancescoCrimi, we aren't going to be able to do this for UWP, but I've provided another solution for you in the original issue. Closing this issue. If you have any follow up questions, please re-open the original issue and ask them there.
