### ISSUE TITLE
Unable to install dotnet-svcutil if only .NET 3.0 SDK is installed

### ISSUE THREAD

**Issue by woofer4444** [dotnet/wcf#4030]
I noticed the release milestone is ready and currently wondering when the release is going to come out. Im trying to use dotnet-svcutil to generate a wsdl, with only the 3.0 sdk installed

In the terminal I got: 
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

**Comment by dasetser** [comment]
@woofer4444 .NET Core 3.0 has already been released. It looks like there is a problem with installing dotnet-svcutil if only the .NET 3.0 SDK is installed. We'll investigate why and work on a fix. For now I would suggest working around this by installing the .NET 2.1 SDK, which it should work with.

**Comment by dcormier** [comment]
I'm able to install it, but when I run it I get this:

```txt
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64
```

**Comment by deniss-simanis** [comment]
I've run into the same problem. I haven't seen any updates on this issue since February. Does this mean there are no plans to support `dotnet-svcutil` beyond .Net Core 2.x?

**Comment by imcarolwang** [comment]
Latest [preview](https://www.nuget.org/packages/dotnet-svcutil/2.0.3-preview1.20574.1) release of the commandline tool should contain the fix of supporting .NETCore3.1, could you please give it a try?

Closing for now, feel free to reopen if you still see problem.
