### ISSUE TITLE
Facing issue while Adding WCF service ( Which have 3 types of binding BinaryHttpService,  BasicHttpService,ConfigHttpService ) as connected service.  

### ISSUE THREAD

**Issue by Kuldeeparyamca** [dotnet/wcf#4056]
once i add it as connected services it shows me warnings : 
Warning: The following Policy Assertions were not Imported:
  XPath://wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='ConfigService.V3.ConfigHttpService']
  Assertions:
    <cfg:ConfigEncoding xmlns:cfg='URL'>..</cfg:ConfigEncoding>

Still if i continue i get another warning and having issues with references.cs file 
Importing web service metadata ...
Number of service endpoints found: 3
Scaffolding service reference code ...
Restoring NuGet packages for bootstrapper ...
Building bootstrapper project ...
Invoking bootstrapper ...
Warning:Warning: The following Policy Assertions were not Imported:
   XPath://wsdl:definitions[@targetNamespace='http://tempuri.org/']/wsdl:binding[@name='ConfigService.V3.ConfigHttpService']
  Assertions:
    <cfg:ConfigEncoding xmlns:cfg='URL'>..</cfg:ConfigEncoding>
Warning:Warning: Unsupported binding element type: 'System.ServiceModel.Channels.UnrecognizedAssertionsBindingElement'.
Warning:Warning: Endpoint 'ConfigService.V3.ConfigHttpService' at address 'URL/configHttp' contains one or more bindings not compatible with .Net Core apps, skipping...
Generating files...
Updating project ...
Done.

I only need  BasicHttpService please help me how to do this.

**Comment by StephenBonikowsky** [comment]
@Kuldeeparyamca I believe you have a .NET Framework service and you are trying to use it from a WCF Core client application. Not everything in the full .NET Framework is supported in WCF Core. 

The tooling is telling you that the ConfigHttpService contains a binding that is not compatible with .NET Core.

Based on the name of the service I would guess that it includes one or more configuration based bindings which are not supported in Core.

@dasetser @mconnew Do you guys have anything else to add?

**Comment by dasetser** [comment]
@Kuldeeparyamca It looks like these are all warnings and it skips the incompatible bindings but still generates the Reference.cs file. What problems are you having with the generated file? Can you attach your wsdl and generated Reference.cs so we can see what's happening?

**Comment by Kuldeeparyamca** [comment]
Thanks for your reply. I have resolved the issue.

**Comment by GaraYaka** [comment]
@Kuldeeparyamca what did you do to solve this issue?

**Comment by Pravin8705** [comment]
How you resolved this issue ?
