### ISSUE TITLE
Running x-machine tests should not require admin privileges on client side

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#407]
Currently, when running cross machine tests, the BridgeClient needs admin privileges in order to install the trusted root cert into the LOCAL MACHINE\Trusted Root Authorities store. 

However, this causes exceptions to be thrown if the launching prompt isn't already in elevated. The exceptions are fairly clear in what they say, but we'd like to avoid them. 

Investigate whether or not it would be okay to instead install into the Current User store. I haven't yet tried to see whether or not that requires privileged access though. Alternatively, we might want to catch these exceptions and fail fast for these tests when we aren't able to write to the necessary store. 

This has impact on the cleanup side too - #365

**Comment by iamjasonp** [comment]
Investigated today - I think that all we need on the BridgeClient is to install certs into the CurrentUser store; the Bridge (server) needs to install into LocalMachine though.

**Comment by iamjasonp** [comment]
... Grumble. The problem is that if we want to install root certs, there is a UI prompt that pops up asking if you want to install the root cert, and there doesn't seem to be a way to bypass this.

**Comment by iamjasonp** [comment]
We may have to let this one slide x-machine :frowning: We may want to tag tests that require elevated permissions to prevent them from running. 

There's still an issue to be fixed here, as testing TCP on localhost needs elevation with the current BridgeClient after #403 (we have no tests running that hit this right now, but the tcp client credential tests will hit this)

We should probably still get to a state where if testing locally on a machine that is already running the Bridge, we shouldn't require admin - this helps with local testing.

**Comment by roncain** [comment]
I don't understand why #403 changed the situation but agree we should prioritize this lower than RC1 work.  In the meantime, do we know whether ToF or CI machines run elevated?  Will they break due to a UI appearing?

**Comment by iamjasonp** [comment]
Prior to #403: 
- The BridgeClient would look up its own hostname and send that to the Bridge as part of a certificate creation request
- If the hostname reported by BridgeClient was the same as the one as the Bridge, then the BridgeClient will not attempt to install the certs. This is because the Bridge already installed the correct certs. 
- else, retrieve the cert from the bridge and install

After #403: 
- The BridgeClient could no longer look up its own hostname as we needed to remove the dependency from System.Net.NetworkInformation. 
- Hence, we don't report this information to the Bridge
- We now simply generate a user cert titled "WCF Client Certificate"
- As the BridgeClient has no knowledge of whether it's on the same machine as the Bridge, it will always try to install "WCF Client Certificate" as well as the Root CA, and thus causes a problem. 

One of the ways i am looking to circumvent this is to do a read of the LOCAL MACHINE cert store (read doesn't need elevation). If the LOCALMACHINE cert store contains the current run's root cert, it's safe to assume we are running on the same machine as the Bridge and no new certs need to be installed.

**Comment by roncain** [comment]
Could there be a problem if a prior run left a cert in the store, but the current run is not on the same machine?  Just checking whether previously aborted test runs could leave behind certs that would fool that test.  Is there a more reliable way to detect the Bridge is running on the same machine (such as a ping to localhost)?

**Comment by iamjasonp** [comment]
w.r.t. https://github.com/dotnet/wcf/issues/407#issuecomment-148135803
We shouldn't run into this problem if the Bridge changes and the Bridge has a different set of certs. If we query (GET) the MachineCertificateResource on the server, it will return the correct thumbprint for the cert and cert authority that's currently valid. 

We should not ever depend on the name of the cert to determine which one is correct; the Bridge is always going to be the authoritiative source for what's correct. 

Yes, pinging localhost might be a good way to figure out whether or not the Bridge is running locally. Let's incorporate the functionality in BridgeClient. But for the moment, there's no need to figure this information out.

**Comment by iamjasonp** [comment]
We can't bypass this. If we install a cert to the Trusted Root Authorities in Windows, we get either: 

* exceptions if installing non-elevated to LocalMachine
* a modal dialog if installing to CurrentUser and the root authority is not already trusted

I see no way to avoid this issue in Windows.

**Comment by roncain** [comment]
@iamjasonp -- what is the recommended plan of action to move forward?  Require the tests to run elevated?

**Comment by iamjasonp** [comment]
To heck with this. I declare that when testing x-machine on Windows, we need to run elevated.

**Comment by iamjasonp** [comment]
Closing this issue; there's no good way to solve the problem at this point.
