### ISSUE TITLE
Using dotnet-svcutil To Generate Separate Classes for Types & Service Reference

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/wcf#4075]
I am trying to use dotnet-svcutil to do the following:

1. Create Types (models) only in .cs file.
2. Create SoapClient types only in separate .cs file.

The reason is that I want to create separate projects for the two. Any ideas? I can't figure it out from the help for the utility.

**Comment by StephenBonikowsky** [comment]
@RealDotNetDave Unfortunately that isn't a supported feature of the tool.

**Comment by RealDotNetDave** [comment]
Can it be? I believe the svcutil.exe does support what I'm asking for? I tried using that, but it won't reference .NET Core assemblies.

**Comment by StephenBonikowsky** [comment]
I know for sure that dotnet-svcutil doesn't support that feature.

@dasetser Does svcutil.exe support this feature?

**Comment by RealDotNetDave** [comment]
Also, it would be super helpful if each class would be created in it's on .cs file. I'm dealing with a WSDL from SalesForce that creates a 49K line file! This is too much for VS 2019 and causes it to crash often.

**Comment by dasetser** [comment]
@RealDotNetDave It sounds like this is the same feature you asked for in #3512, right? This is a feature request that is in our backlog to look into when we can, but we haven't had the chance to look into it yet.

**Comment by RealDotNetDave** [comment]
Yes, it looks like I already asked for that. Sorry I forgot.
