### ISSUE TITLE
Message encoder sample compatibility

### ISSUE THREAD

**Issue by LordBenjamin** [dotnet/wcf#4076]
Can someone please advise on differences between the new WCF packages and the original framework implementation with respect to the sample message encoder provided by Microsoft?

https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/custom-message-encoder-compression-encoder

It seems that there are a number of missing dependencies that prevent building such an encoder:

* `System.ServiceModel.Description.IPolicyExportExtension`
* `System.ServiceModel.Configuration.BindingElementExtensionElement`
* `MessageEncodingBindingElement.BuildChannelListener<TChannel>(BindingContext context)`
* `MessageEncodingBindingElement.CanBuildChannelListener<TChannel>(BindingContext context)`

Are these planned? Are there any alternatives?

**Comment by StephenBonikowsky** [comment]
@LordBenjamin Sorry for the delayed response. Those dependencies are not needed on Core, you can just remove them. They are related to feature areas that are not supported on Core.

**Comment by LordBenjamin** [comment]
Thanks @StephenBonikowsky!

Seems to be another difference somewhere - although it compiles with the dependencies noted above removed, the server throws an exception:

```
Content Type application/x-gzip was sent to a service expecting application/soap+xml; charset=utf-8.  The client and service bindings may be mismatched.
```

I'm not sure why the service expects `application/soap+xml`, since it's using the `GZipMessageEncoder` (via a `CustomBinding` with `GZipMessageEncodingBindingElement`).

Unless I'm mistaken, the removed code would not have run before anyway (bindings all configured in code-behind), so I wouldn't expect any behavioural differences?

**Comment by LordBenjamin** [comment]
From reference source, [HttpChannelHelpers.cs line 398](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Channels/HttpChannelHelpers.cs,398) calls `IsContentTypeSupported()` on the message encoder and throws if this returns `false`.

```c#
if (!messageEncoder.IsContentTypeSupported(ContentType))
{
    // <snip>
    ThrowHttpProtocolException(SR.GetString(SR.ContentTypeMismatch, ContentType, messageEncoder.ContentType), HttpStatusCode.UnsupportedMediaType, statusDescription);
}
```

I have overridden `IsContentTypeSupported()` in the `GzipMessageEncoder` class with:

```c#
public override bool IsContentTypeSupported(string contentType) {
    return true;
}
```

So I wouldn't expect this exception.

Does this mean the server-side binding is not using the correct encoder?

**Comment by LordBenjamin** [comment]
The Watch window evaluates `messageEncoder` at the `ParseMessageAsyncResult.BeginParse()` stack frame as being of type `System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder`.

The `hostedHttpContext.Listener.messageEncoderFactory` member is of type `System.ServiceModel.Channels.TextMessageEncoderFactory`

So it looks like the channel listener is misconfigured.

Given that in .NET Standard 2.0, the `BuildChannelListener()` and `CanBuildChannelListener()` methods are not available to override on `MessageEncodingBindingElement`, how do I ensure the server constructs a channel listener with the correct encoder factory?

**Comment by LordBenjamin** [comment]
I guess that since there is no intention to support server-side WCF from .NET Core, that the answer here will actually be to multi-target `net472;netcoreapp3.0` and conditionally compile the overrides for `BuildChannelListener()` and `CanBuildChannelListener()`.

**Comment by mconnew** [comment]
@LordBenjamin, unfortunately that is what you need to do. Server-side WCF isn't going to be available in the Microsoft supported System.ServiceModel.* packages so we won't be adding those api's.  
There is a community supported (so no official Microsoft support although I am very active there) server side project that's in development over at https://github.com/CoreWCF/CoreWCF if you are wanting to bring your service to .NET Core. This doesn't help with your current issue, more of an FYI.

**Comment by LordBenjamin** [comment]
Thanks for the link to CoreWCF - might be useful, at least as a stopgap measure during porting!
