### ISSUE TITLE
Building WCF in Visual Studio - Unable to locate the .NET Core SDK.

### ISSUE THREAD

**Issue by gojimmypi** [dotnet/wcf#4078]
When opening a freshly cloned WCF `System.ServiceModel.sln` [solution file](https://github.com/dotnet/wcf/blob/master/System.ServiceModel.sln) in Visual Studio 2019, I receive an error message:

![image](https://user-images.githubusercontent.com/13059545/70557862-88797080-1b38-11ea-8f01-7dcff8e6cd89.png)

The output window then has this error message repeated for every project:

```
C:\workspace\wcf\src\System.ServiceModel.Primitives\src\System.ServiceModel.Primitives.Facade.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

```
When doing a `dotnet --list-sdks` at a command prompt, I see these versions:

```
1.1.0 [C:\Program Files\dotnet\sdk]
2.0.0 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.0.3 [C:\Program Files\dotnet\sdk]
2.1.2 [C:\Program Files\dotnet\sdk]
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.100 [C:\Program Files\dotnet\sdk]
2.1.101 [C:\Program Files\dotnet\sdk]
2.1.103 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.2.102 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
```
I downloaded the [.NET Core 3.1 SDK](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.100-windows-x64-installer) and installed it fresh today as well.

There's a note in the error message about _Check that it is installed and that the version specified in `global.json` (if any) matches the installed version_. Sure enough, [that file](https://github.com/dotnet/wcf/blob/master/global.json) appears to be looking for DSK Version 3.0.101, whereas the version I installed today is 3.1.00

```
{
  "tools": {
    "dotnet": "3.0.101",
    "runtimes": {
      "dotnet": [
        "2.1.9"
      ]
    }
  },
  "sdk": {
    "version": "3.0.101"
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "5.0.0-beta.19608.1",
    "Microsoft.DotNet.Helix.Sdk": "5.0.0-beta.19608.1"
  }
}

```

Although that does not really explain why the project files, such as [System.ServiceModel.Duplex.Facade.csproj](https://github.com/dotnet/wcf/blob/master/src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj) way down in `wcf\src\System.ServiceModel.Duplex\src` with no `global.json` file give the same error.

I tried editing the `global.json` file at the root solution level directory to set the SDK Version to the 3.1.100 version I have installed, and that seemed to work!

Perhaps this issue belongs more in the Visual Studio general dotnet core projects queue, as needing to manually edit the `global.json` by hand, and not via Visual Stdudio itself is not intuitive at all - particularly for the projects located in sub-directories.

I was hoping to compile the WCF myself to try and diagnose and hopefully resolve the problem described in Issue #4071

Eventually, I was able to get everything to compile except `dotnet-svcutil.xmlserializer.IntegrationTests` that returns this `9009` error:

```
Error	MSB3073	The command "\dotnet C:\workspace\wcf\artifacts\bin\dotnet-svcutil.xmlserializer.IntegrationTests\Debug\netcoreapp2.1\dotnet-svcutil.xmlserializer.dll C:\workspace\wcf\artifacts\bin\dotnet-svcutil.xmlserializer.IntegrationTests\Debug\netcoreapp2.1\ScenarioTests.Common.Tests.dll --quiet --out:C:\workspace\wcf\artifacts\bin\dotnet-svcutil.xmlserializer.IntegrationTests\Debug\netcoreapp2.1\ScenarioTests.Common.Tests.XmlSerializers.cs --smreference:C:\workspace\wcf\artifacts\bin\System.Private.ServiceModel\Debug\netstandard2.0\System.Private.ServiceModel.dll --reference=C:\Users\gojimmypi\.nuget\packages\microsoft.testplatform.objectmodel\16.1.1\lib\netstandard1.5\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll" exited with code 9009.	

```

There were a variety of other problems getting it to compile: mainly dependencies that are not in the solution. I created https://github.com/dotnet/wcf/pull/4077 if you'd like to merge, although adding these projects seems to break other builds:

![image](https://user-images.githubusercontent.com/13059545/70567394-bcf62800-1b4a-11ea-9660-1a33089385dc.png)

I believe there's still a fresh clone, build _order_ problem as well that is not addressed in my PR.

btw - I found a similar Issue #3282 regarding doing command-line builds, but there does not seem to be a `build.cmd` file in the repo anymore?

**Comment by RamkiPannerselvam** [comment]
Any update on this?

**Comment by mconnew** [comment]
The WCF repo doesn't actually use the installed dotnet sdk, it pulls down it's own version. The docs are currently out of sync with the state of the repo. @StephenBonikowsky? Normally running `eng\common\CIBuild.cmd` from a command line first should be sufficient to get VS working.

**Comment by StephenBonikowsky** [comment]
Using this issue to track documentation updates in the repo.
