### ISSUE TITLE
Update contract version dependencies in TFS test wrappers

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#408]
We have "wrapper" projects in TFS that allow us to run the OSS tests under our "ToF" framework.  These wrapper projects contain "contract references" rather than normal package dependencies.  The versions used here are out of date and no longer match the nuget dependencies..

To resolve this issue, update the wrapper projects directly in TFS to match project dependencies in OSS.

This is a temporary situation -- work is underway to make the TFS test runs use real package dependencies.  At that time we will either modify or delete these wrapper projects.

**Comment by zhenlan** [comment]
ToF uses different version resolution which is not an issue. The necessary package version that our product has a dependency on will actually be used.
