### ISSUE TITLE
BasicHttps

### ISSUE THREAD

**Issue by paulosiquiero** [dotnet/wcf#4082]
**Describe the bug**
When I try to use dotnet-svcutil to create the service files I am getting a warning that wsdl:binding and wsdl:port could not be imported.
The service has two endpoints and I need to consume endpint basic but the import does not occur.

**To Reproduce**
1. Open Package Manager Console
2. Navigate to project directory 
3. Execute the command: dotnet-svcutil https://www.jucesp.sp.gov.br/Jucesp.Services/Viabilidades/Viabilidade.svc?wsdl

**Expected behavior**
The following message will appear:

Attempting to download metadata from 'https://www.jucesp.sp.gov.br/Jucesp.Services/Viabilidades/Viabilidade.svc?wsdl' using WS-Metadata Exchange and HttpGet.
Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='Jucesp.Services.Viabilidades.Viabilidade']/wsdl:binding[@name='Jucesp_BasicHttpBinding']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='Jucesp.Services.Viabilidades.Viabilidade']/wsdl:service[@name='Viabilidade']/wsdl:port[@name='Jucesp_BasicHttpBinding']
Generating files...

**Comment by StephenBonikowsky** [comment]
Based on the WSDL it looks like you are using transport security with message credential which is supported in the runtime but the dotnet-svcutil tool does not yet support it but it is planned, you can track #3969.

Let us know if you have any other questions.
