### ISSUE TITLE
dotnet-svcutil output directory documentation

### ISSUE THREAD

**Issue by bri2** [dotnet/wcf#4115]
When executing "dotnet-svcutil --help", the --outputDir documentation states that the default should be the current directory.
However, when omitting --outputDir, the output directory will be (new) a directory named ServiceReference. I do not have "ServiceReference" defined anywhere in the .svc or wsdl.

Is this correct behavior? If so, should the documentation be changed?

**Comment by StephenBonikowsky** [comment]
@dasetser Could you comment?

**Comment by StephenBonikowsky** [comment]
The help documentation needs to be updated.
It won't make it into the next planned release of the tool.

**Comment by imcarolwang** [comment]
Tried the latest release, behavior of --outputDir is now aligned with the help document:

> dotnet-svcutil --help
> Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
> [Microsoft.Tools.ServiceModel.Svcutil, **Version 2.0.3-preview1.20574.1**]
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Options:
> 
>  --outputDir <directory>                  - Directory to create files in. **Default: A directory called ServiceReference
>                                             inside the current directory.** (Short Form: -d)

Closing issue.
