### ISSUE TITLE
Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0 after deploying Function to Azure

### ISSUE THREAD

**Issue by AGuyCalledGerald** [dotnet/wcf#4118]
I use an Azure v1 Function (C#) to call an external WCF service and to make it work, I added a reference to System.ServiceModel. This works fine on my local dev machine, but after deploying the function to Azure, I get the following error:

Error: Unable to load one or more of the requested types. Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

I tried adding the dll as a local copy but this caused another error:

... (as above)
Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. 

The same error occurs when I remove the assembly reference and install nuget package System.ServiceModel.Primitives instead.

Here are the platform informations:

Microsoft.NET.Sdk.Functions (1.0.24)
.NET Framework 4.6.1

**Comment by StephenBonikowsky** [comment]
@AGuyCalledGerald Sorry for the delayed response.
WCF in the full framework is mostly contained in the System.ServiceModel.dll while in .NET Core WCF is represented by [5 facade packages](https://github.com/dotnet/wcf#wcf-library-components) that only contain publicly available APIs which type forward to one single implementation package that cannot be referenced directly.

You are using the full framework (.NET Framework 4.6.1) so you can't just reference the WCF Core packages.

Normally the error you got would indicate that .NET Framework has not been installed or the wrong version. I am not familiar with the Azure Functions SDK but I would check to make sure that the Azure environment has everything you need.

@mconnew Anything you want to add?

**Comment by StephenBonikowsky** [comment]
Let us know if there is anything else you need from us.
I don't think this is a WCF issue, it's more likely to be a problem with Azure Functions that is missing something related to how it identifies references and pulls in dependencies.
