### ISSUE TITLE
dotnet-svcutil use std in/out

### ISSUE THREAD

**Issue by mikeTWC1984** [dotnet/wcf#4125]
First of all - dotnet-svcutil doesn't seem to be compatible with dotnet sdk3 projects, any news on updating it?

Going back to request - the feature that might be useful is feeding wsdl through standard input and getting type definition from standard output. This would give some better options  to generate types dynamically, like you can do with New-WebServiceProxy command in windows powershell.
For example below shell commands should print type definition. 

```cat ./myService.wsdl | dotnet-svcutil```
or
```curl https://...wsdl | dotnet-svcutil```

**Comment by StephenBonikowsky** [comment]
@dasetser Could you comment?

**Comment by dasetser** [comment]
@mikeTWC1984 We're aware of it not working with .NET Core 3 SDK as expected (as tracked in #4030)

As for your other request, this is a feature request that I don't think we'll be able to get to. It's a different approach from how any of our tools work, and is something you should be able to write a script to do for you. If this would be useful for your scenario I would suggest writing a wrapper script around the tool that writes the contents of stdin to a file, calls dotnet-svcutil pointing to the file, and then writes the contents of dotnet-svcutil's output file to stdout.
