### ISSUE TITLE
System.PlatformNotSupportedException DuplexChannelFactory

### ISSUE THREAD

**Issue by gronlund013** [dotnet/wcf#4135]
I'm in the process of migrating a .net framework application to .net core.
I'm getting System.PlatformNotSupportedException when trying to create a DuplexChannelFactory<T>

.net core version 3.1

Any tips ?

**Comment by StephenBonikowsky** [comment]
@gronlund013 Could you give us more info on how you are trying to create the DuplexChannelFactory? If you are using the constructor that expects a configuration name, configuration is not supported in Core.

**Comment by StephenBonikowsky** [comment]
If you still need assistance please re-open the issue and provide us some additional information about your scenario.
