### ISSUE TITLE
Incomplete wcf client service stack, missing IServiceBehavior, NetTcpRelayBindingElement etc...

### ISSUE THREAD

**Issue by rsaa** [dotnet/wcf#4136]
**Describe the bug**
It's understood that WCF listener stack is not available in .Net core and that's fine but we were hoping for complete WCF client stack be available in the Windows Compatibility Pack. We are ok to stay in Windows and not go cross platform. In our current solution, we are using behaviors, custom nettcp relay binding etc. and none of that is available in WCF client libraries. We get following messages in client application: "Reference to type 'IServiceBehavior' claims it is defined in 'System.ServiceModel', but it could not be found."

Any guidance/ help?

**Comment by StephenBonikowsky** [comment]
@rsaa Could you provide us the specific WCF code you are trying to use so we can see if it can be made available in core. (Or the APIs you are trying to call)

**Comment by vikassingh281** [comment]
@StephenBonikowsky **NetNamedPipeBinding** binding is also missing in **System.ServiceModel** for inter process communication with in system.
Can you please help for find the nuget package or this is deprecated in .net core?

**Comment by StephenBonikowsky** [comment]
@vikassingh281 NetNamedPipeBinding is not currently supported in WCF Core, it is on our list of features to support.

**Comment by vikassingh281** [comment]
@StephenBonikowsky what will be release date for netnamepipe binding in .net core?

**Comment by rsaa** [comment]
@StephenBonikowsky 

We are using 

- IServiceBehavior, IEndpointBehavior, MessageHeader, IClientMessageInspector to send custom data to WCF listener.

- IServiceBehavior, IErrorHandler, BehaviorExtensionElement, NetDataContractSerializer to send exceptions from server to client

**Comment by StephenBonikowsky** [comment]
@vikassingh281 We don't currently have a date for adding NetNamedPipe support, we are working on other features and bug fixes.

@rsaa Thanks for the additional info, @mconnew Can we discuss these APIs and determine if it is something we can support?

**Comment by StephenBonikowsky** [comment]
@rsaa NetDataContractSerializer is a feature that is not likely to be supported in Core.
IServiceBehavior is a server side feature which isn't part of this repo but is part of the https://github.com/corewcf/corewcf
BehaviorExtensionElement is for configuring the client using AppConfig which is not supported in Core.
