### ISSUE TITLE
How to add certificate for client certificate authentication

### ISSUE THREAD

**Issue by HengzheLi** [dotnet/wcf#4141]
I try to add a certificate to a ClientCredential's cert property for using of client certificate authenticate. 
But as therer is a check ThrowIfImmutable() before setting the certificate in X509CertificateInitiatorClientCredential which can be bypass. And here always throw the exception. 

So is there a way to set my certificate in client side?

**Comment by StephenBonikowsky** [comment]
@HengzheLi You need to modify the client credential before the channel factory is opened.

**Comment by HengzheLi** [comment]
Thanks @StephenBonikowsky . The customized cert can be set now. But I encountered another exception:
```
System.ServiceModel.CommunicationException : Connection failed to service. The client certificate is not provided. Specify a client certificate in ClientCredentials. 
```
I set the cert in Opening event of ChannelFactory. Does it the correct way?

**Comment by StephenBonikowsky** [comment]
It would help if we could see how you are setting up your binding and ChannelFactory.

You can search our scenario tests for what you are trying to do... https://github.com/dotnet/wcf/tree/master/src/System.Private.ServiceModel/tests/Scenarios

For instance here is an example of a test that sets a certificate on the client and sets up a certificate in the ChannelFactory.
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs#L15

**Comment by HengzheLi** [comment]
Here is how I set the cert
```
class MtApiProxy : DuplexClientBase<IMtApi>, IMtApi, IDisposable
    {
        public MtApiProxy(InstanceContext callbackContext, Binding binding, EndpointAddress remoteAddress)
            : base(callbackContext, binding, remoteAddress)
        {
            InnerChannel.Faulted += InnerDuplexChannel_Faulted;
            ChannelFactory.Opening += InnerChannel_Opening;
        }

        private void InnerChannel_Opening(object sender, EventArgs e)
        {
            var cert = new X509Certificate2("cert_key.p12", "*******");
            ChannelFactory.Credentials.ClientCertificate.Certificate = cert;
        }
}
```
cert_key.p12 is the certificate I generated using openssl. And the code will be packed into docker, but I test it in Windows.
Here is the binding:
```
var bind = new NetTcpBinding(SecurityMode.Transport)
            {
                MaxReceivedMessageSize = 2147483647,
                MaxBufferSize = 2147483647,
                MaxBufferPoolSize = 2147483647,
                SendTimeout = new TimeSpan(12, 0, 0),
                ReceiveTimeout = new TimeSpan(12, 0, 0),
                ReaderQuotas =
                {
                    MaxArrayLength = 2147483647,
                    MaxBytesPerRead = 2147483647,
                    MaxDepth = 2147483647,
                    MaxStringContentLength = 2147483647,
                    MaxNameTableCharCount = 2147483647
                }
            };

            bind.Security.Transport = new TcpTransportSecurity()
            {
                ClientCredentialType = TcpClientCredentialType.Certificate
            };
```
I checked the unit test code in your provided link. Seems the difference  is that the binding I used is Tcp and the unit test's is Http. Is this the point?

**Comment by StephenBonikowsky** [comment]
We also have tcp variants of the tests...
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs#L19
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs#L226

In the tests we use `factory.Credentials.ClientCertificate.SetCertificate` to find the client certificate, try that instead of `ChannelFactory.Credentials.ClientCertificate.Certificate = cert;`

@mconnew Do you see anything else that could be the issue?

**Comment by HengzheLi** [comment]
OK. I set the cert in the overrided method CreateChannel and it works.

**Comment by StephenBonikowsky** [comment]
Great!
