### ISSUE TITLE
Set max timeouts on all scenario tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#416]
Most scenario tests do not currently alter the default timeout, and when testing x-plat (where several operations timeout), it often takes a very long time for test runs to complete.

This current task counts as test cleanup but also facilitates x-plat testing.  All scenario tests should ensure a max timeout using ScenarioTestHelpers.TestTimeout.  This also allows debugging because this value can be set via an Environment variable prior to running tests.

**Comment by StephenBonikowsky** [comment]
This needs to be increased in priority, currently a WebSockets test is hanging due to a product issue, the test hangs for 20 mins (tof timeout for the entire test project) which results in only two of the WebSockets tests getting run, the one that hangs being the second one.

**Comment by zhenlan** [comment]
This issue was originally reported for x-plat only. @StephenBonikowsky, is this also a problem for Windows now?

**Comment by roncain** [comment]
I intended it to be used on Windows too.  It was just that on x-plat we were getting huge timeout waits for tests that succeeded in Windows, making it difficult to use.  We are seeing the same in NET Native with WebSockets.  Basically, any test that fails due to a timeout should not stall for 20-30 minutes as some of them appear to do.

**Comment by zhenlan** [comment]
I understand the intend of this issue. It's just that if the timeout becomes an issue on Windows too now I agree with @StephenBonikowsky that we should prioritize this (or disable the offending tests for now).

**Comment by StephenBonikowsky** [comment]
Discussed with @mconnew and @hongdai and we think we should be fine to just use the x-unit timeout. It doesn't help with debugging but solves the problem of test runs hanging.

The property to set is: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/CloudTest.targets#L60
