### ISSUE TITLE
Missing public parameterless constructor for System.ServiceModel.Channels.ServiceChannelProxy

### ISSUE THREAD

**Issue by vidir-svanberg** [dotnet/wcf#4170]
CreateProxy in System.ServiceModel.Channels.ServiceChannelProxy calls System.Reflection.DispatchProxy.Create<TChannel, ServiceChannelProxy>() which fails because  System.ServiceModel.Channels.ServiceChannelProxy does not have a public parameterless constructor

**Comment by StephenBonikowsky** [comment]
This class is not a public class in either the full framework or .NET Core.
System.Private.ServiceModel package is not supposed to be directly referenced which is the only way you could be running into this problem.

**Comment by vidir-svanberg** [comment]
The error occurs when using a WCF client in Blazor WebAssembly App. 
See https://github.com/dotnet/aspnetcore/issues/19349

**Comment by StephenBonikowsky** [comment]
Thanks for the additional info, I'll respond on the aspnetcore issue and talk to whoever is the owner over there.

**Comment by StephenBonikowsky** [comment]
Chatted with the PM for Blazor, he will respond on the other issue.
