### ISSUE TITLE
Update target framework for test projects to netcoreapp3.1

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#4183]
All test projects currently target netcoreapp3.0, update to netcoreapp3.1

**Comment by StephenBonikowsky** [comment]
@imcarolwang this should just be a matter of updating all the test projects like this one...
https://github.com/dotnet/wcf/blob/master/src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj#L3

Both scenario and unit test projects.

**Comment by imcarolwang** [comment]
Closing, test project targets have been updated in https://github.com/dotnet/wcf/pull/4314/commits/092b35cff8da8f4c57152f55f0d6298bc7d95f52.
