### ISSUE TITLE
Question: binding with full message security (both encryption and signing)

### ISSUE THREAD

**Issue by jdvor** [dotnet/wcf#4187]
I would like someone with deep knowledge of the dotnet/wcf project and most importantly its feature road-map to assess following binding and tell me whether there are any plans to support missing features (listed bellow).
If some of it is simply not known I would like to hear your best guess on the matter (event if the guess might be "never"). Thanks very much in advance.
```
using System;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Security;
using System.ServiceModel.Security.Tokens;
using System.Text;
using System.Xml;

private static Binding CreateClientBinding()
{
    var binding = new CustomBinding
    {
        OpenTimeout = TimeSpan.FromSeconds(20),
        CloseTimeout = TimeSpan.FromSeconds(20),
        SendTimeout = TimeSpan.FromSeconds(30),
        ReceiveTimeout = TimeSpan.FromSeconds(30),
    };

    // 1. WS-Security
    // https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.asymmetricsecuritybindingelement?view=netframework-4.7.2
    var msgSecVer = MessageSecurityVersion.WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10;
    var asbe = (AsymmetricSecurityBindingElement)SecurityBindingElement.CreateMutualCertificateBindingElement(msgSecVer);
    asbe.DefaultAlgorithmSuite = SecurityAlgorithmSuite.Basic256;
    asbe.IncludeTimestamp = true;
    asbe.SetKeyDerivation(false);
    asbe.KeyEntropyMode = SecurityKeyEntropyMode.CombinedEntropy;
    asbe.SecurityHeaderLayout = SecurityHeaderLayout.Lax;
    asbe.MessageProtectionOrder = MessageProtectionOrder.SignBeforeEncrypt;
    asbe.ProtectTokens = false;
    asbe.EnableUnsecuredResponse = true;

    if (asbe.InitiatorTokenParameters is X509SecurityTokenParameters itp)
    {
        itp.X509ReferenceStyle = X509KeyIdentifierClauseType.Any;
        itp.InclusionMode = SecurityTokenInclusionMode.AlwaysToRecipient;
    }

    if (asbe.RecipientTokenParameters is X509SecurityTokenParameters rtp)
    {
        rtp.X509ReferenceStyle = X509KeyIdentifierClauseType.Any;
        rtp.InclusionMode = SecurityTokenInclusionMode.Never;
    }

    var userNameToken = new UserNameSecurityTokenParameters
    {
        InclusionMode = SecurityTokenInclusionMode.AlwaysToRecipient,
    };
    asbe.EndpointSupportingTokenParameters.Signed.Add(userNameToken);

    // 2. WS-Addressing
    var msgEnc = new TextMessageEncodingBindingElement(MessageVersion.Soap12WSAddressingAugust2004, Encoding.UTF8)
    {
        ReaderQuotas = new XmlDictionaryReaderQuotas
        {
            MaxStringContentLength = 65536, // 64KB
            MaxArrayLength = 65536,
        },
    };

    // 3. transport HTTPS
    var https = new HttpsTransportBindingElement
    {
        KeepAliveEnabled = true,
        MaxReceivedMessageSize = 32 * 1048576, // 32MB
    };

    binding.Elements.Add(asbe);
    binding.Elements.Add(msgEnc);
    binding.Elements.Add(https);

    return binding;
}
```

1. class System.ServiceModel.Channels.AsymmetricSecurityBindingElement
2. static method CreateMutualCertificateBindingElement of class System.ServiceModel.Channels.SecurityBindingElement
3. static property Basic256 of class System.ServiceModel.Security.SecurityAlgorithmSuite
4. enum System.ServiceModel.Security.MessageProtectionOrder
5. class System.ServiceModel.Security.Tokens.X509SecurityTokenParameters
6. property InclusionMode of class System.ServiceModel.Security.Tokens.UserNameSecurityTokenParameters 
7. enum System.ServiceModel.Security.Tokens.SecurityTokenInclusionMode

Regarding `AsymmetricSecurityBindingElement` (point 1) I've found https://github.com/dotnet/wcf/issues/3860#issuecomment-546049552, so this one is clear - full message security will not be supported for quite some time (at best .NET 5, but even that is in no way guaranteed if I understand the communication well enough).
What about the other points. Will they be supported?

FYI: this binding is from in-production app and this is how need to communicate (it's the only way) with many electric power exchanges throughout the Europe. The details differ from time to time, but it's usually the whole shebang of WS-Security (both message-level signing & encryption), WS-Addressing, and so on.

**Comment by HongGit** [comment]
@jdvor  AsymmetricSecurityBindingElement is full Message Security feature request, we don't plan to support full Message Security feature in the near future.

**Comment by makacenko** [comment]
Hello, I think, I have the same scenario (electric power exchanges using SOAP messages) and same troubles as @jdvor did. @jdvor - did you find any acceptable solution? I'm afraid that migration of communication engine from .NET Framework to .NET Core isn't possible :-(.

**Comment by jdvor** [comment]
@makacenko at the end yes, but not by using dotnet/wcf. We had to wrote request builder & reader almost from scratch and learn a lot of details around SOAP, creds, signing, encryption, etc. which we would otherwise not have to.

**Comment by peterlindholm** [comment]
@jdvor 2 years later and this is still not supported. Any chance you have any samples you can share?
