### ISSUE TITLE
Missing APIs

### ISSUE THREAD

**Issue by ilgb** [dotnet/wcf#4189]
I'm trying to port an existing WCF Client library from Net 4.0 to Net Core 3.1 but it missing some WCF API. 
See attached report (JSON) of the .NET Portability Analyzer.
[ApiPortAnalysis.json.txt](https://github.com/dotnet/wcf/files/4291789/ApiPortAnalysis.json.txt)

Do you plan a next release that will add these APIs?

Thanks

**Comment by mconnew** [comment]
If you are able to make code changes you are probably okay with what api's are there currently as it looks like you have some server side code that you are using which shouldn't be needed on the client side.
* AuthorizationContext - Server side code
* IdentityVerifier - This is client side but there's often other ways to achieve the same thing. If you can provide your usage, I might be able to provide an alternate way to do the same thing.
* ClaimTypes - Server side
* SslStreamSecurityBindingElement - What's your use case here? We have the functionality, just haven't exposed the class so you might not need access to the actual class.
* BasicHttpBinding.MaxReceivedMessageSize - This gets passed through to the message encoder so you should just be able to modify that on the message encoder instead.
* CreateSpnIdentity - This is a simple helper which just returns new SpnEndpointIdentity(name). That class and it's constructor are available.
* CreateDnsIdentity - This is similar, you can just new up an instance of DnsEndpointIdentity
* BasicHttpBinding.ReaderQuotas - This just gets passed through to the message encoder so set this on the message encoder
* Claim/ClaimSet - should only be needed on the server side. If you are using this on the client, can you provide your use case

If there's anything which there isn't a workaround or alternative way to achieve and is needed for client usage, none of what you've asked for requires a lot of work so we can most likely add it in .NET 5.

**Comment by HongGit** [comment]
@ilgb please let us know if anything else is needed.
