### ISSUE TITLE
Erro no arquivo deps.json ao realizar refresh no serviço de WCF.

### ISSUE THREAD

**Issue by michaelpedro** [dotnet/wcf#4197]
[English]
Guys, good morning.

I'm trying to perform a refresh in the WCF service connected to the SAP integration, however when trying to perform the refresh an error occurs in the file: deps.json as shown in the image below.

I looked on several pages on the internet and I couldn't solve the error, can someone help me?
__________________________________________________________________________________________________________
[Português]
Pessoal, bom dia.

Estou tentando realizar um refresh no serviço de WCF conectado a integração do SAP, no entanto ao tentar realizar o refresh ocorre um erro no arquivo: deps.json conforme imagem abaixo.

Procurei em diversas paginas na internet e não consegui resolver o erro, alguém pode me ajudar?

![image](https://user-images.githubusercontent.com/51841955/76218419-fe9e7980-61f2-11ea-9528-5ea7356303a9.png)

**Comment by dasetser** [comment]
@michaelpedro01 Thanks for reporting this and I'm sorry we missed responding to this when you first reported it. We have a change that should fix this issue checked in for dotnet-svcutil. This should be fixed in a future release once we're able to get this inserted into Visual Studio.

**Comment by michaelpedro01** [comment]
Okay,
Thank you very much for the feedback @dasetser .

**Comment by imcarolwang** [comment]
This should have been fixed in the recent release of VS16.11 Preveiw2 which download link could be found [HERE](https://visualstudio.microsoft.com/vs/preview/). Please give it a try. If problem persist feel free to re-activate this issue.
