### ISSUE TITLE
System.ServiceModel.ServerTooBusyException while making WCF Web Client Call above 30 Seconds

### ISSUE THREAD

**Issue by serkanz** [dotnet/wcf#4198]
I created a WCF Web Service Client in my .Net Core Console App which I'm successfully using. 

However even if I set the timeout durations to 2 minutes, I keep getting **System.ServiceModel.ServerTooBusyException** if the server response time is above **30 seconds**. 

I run the console app (.Net Core 3.1, System.ServiceModel 4.7.0) in Windows Server 2016 and start it as a scheduled task.

Below is the code that I use. 

```c#
            DateTime requestTime = new DateTime();
            try
            {
                using (var client = new ServisClient(ServisClient.EndpointConfiguration.BasicHttpBinding_ISSBServis, Configuration.GetValue<string>("ServiceUrl")))
                {
                    client.Endpoint.Binding.OpenTimeout = new TimeSpan(0, 2, 0);
                    client.Endpoint.Binding.SendTimeout = new TimeSpan(0, 2, 0);
                    client.Endpoint.Binding.ReceiveTimeout = new TimeSpan(0, 2, 0);
                    requestTime = DateTime.Now;
                    var result = await client.SorguAsync(firma, tarih.ToString("dd/MM/yyyy", culture), tarih.ToString("dd/MM/yyyy", culture));

                    if (result.hatalar == null)
                    {
                        return new FirmaResult() { firma = firma, beyannameler = result, tarih = tarih };
                    }
                    else
                        return new FirmaResult() { firma = firma, beyannameler = null, tarih = tarih };
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(DateTime.Now.ToLongTimeString() + "#" + requestTime.ToLongTimeString() + "#" + firma.VergiNo + "#" + tarih.ToString("dd/MM/yyyy", culture) + "#" + ex.ToString());
                hataListesi.Add(new Hata() { FirmaId = firma.Id, tarih = tarih, exception = ex });
                return new FirmaResult() { firma = firma, beyannameler = null, tarih = tarih };
            }

```
Is there a default 30 second timeout setting which I could override?

Kind regards

**Comment by serkanz** [comment]
I checked the service that my client make request and saw that it responded 110 seconds later. However my WCF client throws error below just after 30 seconds :

```log
System.ServiceModel.ServerTooBusyException: The HTTP service located at http://xxx.xxx.xxx.xx/apigateway/xxx/ is unavailable.  This could be because the service is too busy or because no endpoint was found listening at the specified address. Please ensure that the address is correct and try accessing the service again later.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at xxx.xxx.xxx(Firma firma, DateTime tarih) in C:\xxx\xxx\source\repos\xxx\xxx\Program.cs:line xxx
```

**Comment by mconnew** [comment]
The server is responding with a too busy response. When you say you saw it responded 110 seconds later, do you mean the server supplied the HTTP response or do you mean your service call completed 110 seconds later? Those are two very different things.

**Comment by serkanz** [comment]
> The server is responding with a too busy response. When you say you saw it responded 110 seconds later, do you mean the server supplied the HTTP response or do you mean your service call completed 110 seconds later? Those are two very different things.

Hi @mconnew , when I look at the server logs I see that it responded with http 200 after 110 seconds. However my WCF client throws ServerTooBusyException after 30 seconds not waiting the server response.

**Comment by mconnew** [comment]
There are a few reasons why that exception is thrown. You can see the places it's thrown here: https://source.dot.net/#System.Private.ServiceModel/System/ServiceModel/ServerTooBusyException.cs,05eaa52d90a0c6f3,references

First reference on that page shows when it gets a fault message with an EndpointNotAvailable fault code. Second one is related to NetTcp. Thrid one is when receiving a 503 http status. Fourth one is when using a third party authentication server and that server returns a soap fault code of SecurityServerTooBusyFault
So you can see, it only throws that exception when the server provides a response saying it's too busy. A SOAP Fault will still have a 200 response.
