### ISSUE TITLE
Refactor System.Servicemodel.ClientBase to have non-generic base

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#42]
This issue was originally submitted by @rcollet as https://github.com/dotnet/corefx/issues/300 but I am taking it over to the WCF issues for further consideration.

The following is an example of  a generic extension method I would like to write, but cannot because `ClientBase<T>` does not inherit from a base class containing the non generic members.   It would be very helpful if `ClientBase<T>` was refactored into `ClientBase<T>:ClientBase`

``` C#
using DotNetOpenAuth.OAuth2;
using System;
using System.Net;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading;
using System.Threading.Tasks;

namespace OAuthClient
{
    public static class ExtensionMethods
    {
        public static async Task<T> CallAsync<TClient, TChannel, T>(this TClient wcfClient, Func<TClient, T> predicate, IAuthorizationState authorization, CancellationToken cancellationToken) where TClient : ClientBase<TChannel> where TChannel : class
        {
            if (authorization == null)
            {
                throw new InvalidOperationException("No access token!");
            }

            // Refresh the access token if it expires and if its lifetime is too short to be of use.
            if (authorization.AccessTokenExpirationUtc.HasValue)
            {
                await AuthorizationServer.Client.RefreshAuthorizationAsync(authorization, TimeSpan.FromSeconds(30));
            }

            var httpRequest = (HttpWebRequest)WebRequest.Create(wcfClient.Endpoint.Address.Uri);
            ClientBase.AuthorizeRequest(httpRequest, authorization.AccessToken);

            var httpDetails = new HttpRequestMessageProperty();
            httpDetails.Headers[HttpRequestHeader.Authorization] = httpRequest.Headers[HttpRequestHeader.Authorization];
            using (var scope = new OperationContextScope(wcfClient.InnerChannel))
            {
                OperationContext.Current.OutgoingMessageProperties[HttpRequestMessageProperty.Name] = httpDetails;
                bool isError = true;
                try
                {
                    T result = predicate(wcfClient);
                    // If there is an error on the channel, the close call will throw an exception.
                    wcfClient.Close();
                    isError = false;
                    return result;
                }
                finally
                {
                    // If we have an error on the channel, we cannot close the channel so we abort.
                    // Exceptions that occur will still be raised unmodified.
                    if (isError)
                    {
                        wcfClient.Abort();
                    }
                }
            }
        }
    }
}
```

When making a call to the extension like: 

``` C#
var client = new ProfileServiceClient();
UserProfile userProfile = 
    await client.CallAsync(c => c.UserProfile(), authorization, response.ClientDisconnectedToken);
```

The compiler generates the following error at the call to the extension function:

`Error  89  'OAuthClient.SampleResourceServer.ProfileServiceClient' does not contain a definition for 'CallAsync' and no extension method 'CallAsync' accepting a first argument of type 'OAuthClient.SampleResourceServer.ProfileServiceClient' could be found (are you missing a using directive or an assembly reference?)`

While intellisense shows the extension method as available for ProfileServiceClient, I'm assuming the compiler isn't able to infer the type TChannel (At least not in VS 2012) because there is no parameter associated with that type. 

I need to be able to access `ClientBase<T>` properties like `InnerChannel`.   If the non-generic properties and methods of `ClientBase<T>` were refactored into a non-generic base class `ClientBase`, then I could declare the extension method like:

``` c#
public static async Task<T> CallAsync<TClient, T>(this TClient wcfClient, Func<TClient, T> predicate, IAuthorizationState authorization, CancellationToken cancellationToken) where TClient : ClientBase
```

The problem with inferring the type of TChannel then goes away.  In general I have found it a useful design pattern to place all non-generic members of a generic class in non-generic base, for just this reason.

**Comment by eddiegroves** [comment]
This would have been handy, ah well.
