### ISSUE TITLE
Binding.NetHttp tests using WebSockets hang on Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#420]
Binding.NetHttp.Tests hangs on Linux with no messages.
Investigation/instrumentation required to know how far it got or if it would ever timeout.
I waited 5 minutes and it was still hung

**Comment by roncain** [comment]
Update: they eventually timeout claiming it exceeded the timeout of 00:20:00, but it was about an hour or so after the test had been started.

**Comment by zhenlan** [comment]
For now @roncain will add active issue to skip this for *nix.

**Comment by roncain** [comment]
Tests marked with [ActiveIssue] for Linux. Reassigning to @mconnew to investigate cause of hang on Linux.
