### ISSUE TITLE
Leverage HttpClientFactory to get benefits of handers

### ISSUE THREAD

**Issue by AlanCS** [dotnet/wcf#4204]
Hi there !

Firstly, thanks for all your good work, I use this library and it has been working very well for me :)

My suggestion for improvement is to use the [HttpClientFactory](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) instead of creating HttpClients manually [like this line](https://github.com/dotnet/wcf/blob/f0b3b4935eb97807dbed7b73f25fbf160a523eac/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L343)

The benefits is that we can leverage useful HttpMessageHandler from other tools.

I feel strongly about it because I have an [open source tool](https://github.com/AlanCS/SystemTestingTools/) that allows you to intercept http calls, allowing you to return a mock for testing, or record the whole request and response (including headers and body); but because we are not using HttpChannelFactory, my IHttpMessageHandlerBuilderFilter is not being picked up.

I have tried [alternative solutions](https://stackoverflow.com/questions/52090368/wcf-tracing-in-asp-net-core), but those only log the request and response bodies, and introduces dependencies to System.ServiceModel.*; if we just leverage the existing functionality around HttpClientFactory, it will be a lot more complete and neater.

This would also allow us to leverage other tools such as [Polly](https://github.com/App-vNext/Polly) for circuit breakers and retries, or custom inspectors to log size / timing of requests and responses.

**Comment by HongGit** [comment]
@mconnew  could you please chime in?

**Comment by mconnew** [comment]
I created a way to modify and/or replace the HttpMessageHandler. A description of some of the details and the following discussion [starts here](https://github.com/dotnet/wcf/issues/3230#issuecomment-431921166). Someone has written a blog post on [how to do this here](https://medium.com/trueengineering/realization-of-the-connections-pool-with-wcf-for-net-core-with-usage-of-httpclientfactory-c2cb2676423e).  

I'm closing this issue as I believe everything you need can be found in those two links. If that's not the case, please re-open.
