### ISSUE TITLE
Improve HttpAuthorizationForbidden message for HTTPS with client certificates

### ISSUE THREAD

**Issue by simon-biber** [dotnet/wcf#4210]
**Describe the bug**
The exception message generated by WCF "The HTTP request was forbidden with client authentication scheme 'Anonymous'." is misleading in multiple ways. Firstly it gives the impression that unsecured HTTP was used, which could be a red herring in investigating an issue. Secondly it's not obvious that 'forbidden' means the remote system returned an HTTP 403 status code. Thirdly the 'Anonymous' implies that the client attempted to connect anonymously, without identifying itself. The authentication schemes it will show are limited to those in an enumeration AuthenticationSchemes, which has values for Anonymous, Basic, Digest, IntegratedWindowsAuthentication, Negotiate, None and Ntlm. There is no value for authentication using a client certificate. When using a client certificate, the certificate is configured in the client, but the authentication schemes enum remains as Anonymous.

**To Reproduce**
Invoke a SOAP web service using HTTPS with a client certificate, where the service returns an HTTP error code 403 Forbidden.

**Expected behavior**
An error message indicating that the HTTPS request (not HTTP) received a 403 Forbidden status with client certificate authentication (not Anonymous).

**Comment by HongGit** [comment]
@simon-biber thanks for raising this issue!

WCF uses [HTTP protocol](https://tools.ietf.org/html/rfc2817), not HTTPS (which is a scheme), and according to protocol, [403](https://tools.ietf.org/html/rfc7231#section-6.5.3) is Forbidden.  In addition, certificate is not an HTTP authentication scheme, it's possible to use HTTP authentication with client certificate, they are not mutually exclusive.
