### ISSUE TITLE
.NET Core 3.1 WCF Web Service Reference Provider error

### ISSUE THREAD

**Issue by mujgancihan** [dotnet/wcf#4216]
Hi,
I have an application created in NET Core 3.1 and I am trying to add a web service by
WCF Web Service Reference Provider.
But it fails and shows the error below;

Importing web service metadata ...
Number of service endpoints found: 2
Scaffolding service reference code ...
Error:Unable to generate deps.json, it may have been already generated. You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d ": C:\Program Files\dotnet\sdk\3.1.200\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
Done.

Could you please help me to understand the error reason?

Regards,
Mujgan Chan

**Comment by dasetser** [comment]
Thanks for reporting this. We'll look into a fix for this bug in a future release. For now I would suggest using the [dotnet-svcutil comand line tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) to work around this bug.

**Comment by imcarolwang** [comment]
This issue should have been fixed in the recent release of VS16.11 Preveiw2 which could be downloaded from [HERE](https://visualstudio.microsoft.com/vs/preview/). Please give it a try. If issue persist feel free to re-activate this issue.
