### ISSUE TITLE
Custom binding with mutual certificate. How can we do this now?

### ISSUE THREAD

**Issue by Jonah-Jordan** [dotnet/wcf#4220]
Currently we are facing some issues when calling a WCF service in .net core (2.1).

Because .net core doesn't support the System.Servicemodel binding in the web.config we are trying to create this custom binding programmatically.

(This is well explained in this stackoverflow question: How can I programmatically create this custom binding?)

Our custom binding looks like this:

```
<bindings>
  <customBinding>
    <binding name="customBinding">
      <security enableUnsecuredResponse="true" authenticationMode="MutualCertificate"
        messageSecurityVersion="WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10" />
      <textMessageEncoding messageVersion="Soap11" />
      <httpsTransport maxReceivedMessageSize="2097152" requireClientCertificate="true" />
    </binding>
  </customBinding>
</bindings>
```
How can we achieve this in code?

In .net framework 4.7.x there was on option to create this binding in this way:

```
CustomBinding binding = new CustomBinding();
SecurityBindingElement sbe = SecurityBindingElement.CreateMutualCertificateBindingElement();
```
But in .net core 2.1 it isn't there. How can we achieve this?

Or how can we do a WCF call in .net core with this custom binding. Kind regards and many thanks for helping us out!

**Comment by HongGit** [comment]
@Jonah-Jordan this is not supported yet, because requires full MessageSecurity feature.  Not sure when that will be supported, certainly it's not going to be the near future.

**Comment by jbh-aros** [comment]
Still not supported?

**Comment by jbh-aros** [comment]
No I didn't. Unfortunately, we are stuck on .net framework 4.8 until either there's a solution or the API we are using gets an upgrade.
