### ISSUE TITLE
One ServiceHost with many EndPoint or many ServiceHost with One EndPoint ,Which is better?

### ISSUE THREAD

**Issue by HanWangwang** [dotnet/wcf#4232]
I want to get their advantages or disadvantages.Thanks!

**Comment by mconnew** [comment]
Use a single ServiceHost unless one of these scenarios:
- Different implementation types are to be used for the different endpoints
- Different security configuration is needed for different endpoints (you can do it with one, but you need to write a LOT of code to achieve it)
- You need to add new endpoints dynamically
- You want different throttling behavior for the different endpoints

Using different ServiceHost instances means you don't get to share as many things. For example, if you are using a singleton context mode, each servicehost would have it's own instance. If you use single concurrency mode, each servicehost would have it's own lock around making a call so you would need to enforce the concurrency between servicehost instances yourself.

**Comment by mconnew** [comment]
I you have any follow up questions, feel free to re-open this issue.
