### ISSUE TITLE
dotnet-svcutil not compatible with Core 2.1 error message

### ISSUE THREAD

**Issue by hrafnkel** [dotnet/wcf#4234]
**Describe the bug**
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package dotnet-svcutil 2.0.1 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package dotnet-svcutil 2.0.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any	WebApplication1	C:\Users\\****\Source\Workspaces\WebApplication1\WebApplication1\WebApplication1.csproj	1	

**To Reproduce**
Use NuGet to install dotnet-svcutil from within VS2019

**Expected behavior**
I'd like it to install

**Comment by imcarolwang** [comment]
Could you please follow  [this document](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) which has the recommend way to try out the tool? Feel free to reopen if it's still a problem.
