### ISSUE TITLE
Add net6.0 TFM to packages

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#4237]
Today our packages suppress our implementation for xamarin based applications. The next version of the xamarin platform will be based on .NET 5. The previous version of xamarin was based on mono and carried it's own implementation of WCF which is why we suppressed our assets. Based on the design [here](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#precedences) we need to add a net5.0 TFM to our packages so that newer xamarin apps can use our implementation.

**Comment by HongGit** [comment]
push out to .NET 6.0, move this to .NET 6.0.

**Comment by akoeplinger** [comment]
@HongGit just checking whether this is still planned for .NET6? We need it for Xamarin scenarios, I'm happy to send a PR if it's just a matter of adding the net6.0 TFM to the projects.

**Comment by mconnew** [comment]
@akoeplinger, the delay has been in finding bandwidth to test it. Adding net6.0 is simple to do, but when the reason is to enable Xamarin usage, we should test the generated packages with a Xamarin app to make sure it is picked up and used at runtime. If you can do that validation, then I'm happy to accept a PR adding net6.0. I'm just not comfortable adding something blindly without testing it in the intended scenario it's addressing.

**Comment by akoeplinger** [comment]
@mconnew ok, I think we can do the testing/validation on our side.

**Comment by akoeplinger** [comment]
I forced using the netcoreapp2.1 assets in the System.ServiceModel.Primitives 4.8.1 package from nuget into a sample .NET 6 Xamarin Android app and was able to call a SOAP service with a WCF client generated from the WSDL by `dotnet-svcutil` and it worked so we know at least the basics are working :)

@mconnew I'll look at adding net6.0 to the .csproj's and test with that too.
