### ISSUE TITLE
dotnet-svcutil.xmlserializer 1.2 fails during Azure Pipelins build

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/wcf#4238]
We have a project using dotnet-svcutil.xmlserializer 1.2.  Everything builds and runs fine locally.

We just setup an Azure Pipeline for our project and the tool is failing with the generic "exited with code 1" error.

How can we diagnose what is going wrong?  Is there a way to force the removal of the --quite command line option sent to the tool so we can see any errors it is generating?

Here is the relevant line from the build log.

C:\Users\VssAdministrator\.nuget\packages\dotnet-svcutil.xmlserializer\1.2.0\build\dotnet-svcutil.xmlserializer.targets(35,5): 
Warning MSB3073: The command "dotnet svcutil.xmlserializer obj\Release\netstandard2.0\SA.Core.SymXchange.WSDL.dll 
--quiet 
--out:obj\Release\netstandard2.0\SA.Core.SymXchange.WSDL.XmlSerializers 
--smreference:"C:\Users\VssAdministrator\.nuget\packages\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.memory\4.5.0\lib\netstandard2.0\System.Memory.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.numerics.vectors\4.4.0\lib\netstandard2.0\System.Numerics.Vectors.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.private.servicemodel\4.7.0\lib\netstandard2.0\System.Private.ServiceModel.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.reflection.dispatchproxy\4.5.0\lib\netstandard2.0\System.Reflection.DispatchProxy.dll;
		C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.compilerservices.unsafe\4.5.0\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll;
		C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.accesscontrol\4.5.0\lib\netstandard2.0\System.Security.AccessControl.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.security.cryptography.cng\4.4.0\lib\netstandard2.0\System.Security.Cryptography.Cng.dll;
		C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.cryptography.pkcs\4.5.0\lib\netstandard2.0\System.Security.Cryptography.Pkcs.dll;
		C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.cryptography.xml\4.5.0\lib\netstandard2.0\System.Security.Cryptography.Xml.dll;
		C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.permissions\4.5.0\lib\netstandard2.0\System.Security.Permissions.dll;
		C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.principal.windows\4.5.0\lib\netstandard2.0\System.Security.Principal.Windows.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.servicemodel.duplex\4.7.0\lib\netstandard2.0\System.ServiceModel.Duplex.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.servicemodel.http\4.7.0\lib\netstandard2.0\System.ServiceModel.Http.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.servicemodel.nettcp\4.7.0\lib\netstandard2.0\System.ServiceModel.NetTcp.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.servicemodel.primitives\4.7.0\lib\netstandard2.0\System.ServiceModel.Primitives.dll
		C:\Users\VssAdministrator\.nuget\packages\system.servicemodel.primitives\4.7.0\lib\netstandard2.0\System.ServiceModel.dll;
		C:\Users\VssAdministrator\.nuget\packages\system.servicemodel.security\4.7.0\lib\netstandard2.0\System.ServiceModel.Security.dll"
" exited with code 1.

**Comment by pmiddleton** [comment]
@StephenBonikowsky any guidance on this issue?

**Comment by StephenBonikowsky** [comment]
@pmiddleton Here is the line in the tagets file that executes the command you posted from the logs.
https://github.com/dotnet/wcf/blob/master/src/svcutilcore/files/dotnet-svcutil.xmlserializer.targets#L35
This target file in the package, you could modify it and remove the "--quiet" then run it again.

@dasetser or @mconnew should be able to provide you additional assistance.

**Comment by pmiddleton** [comment]
I worked on this all day today.  It turns out the --quiet flag is actually required in order for the tool to run.  After much tinkering the only error message I can get is.

Version for package `dotnet-svcutil.xmlserializer` could not be resolved

This occurs during the <Exec Command="dotnet svcutil.xmlserializer line of the build task.  

However the error isn't coming from the tool itself.  I built the tool from source locally and added  extra logging.  I can see the logging locally but the only error I am seeting in devops is the one mentioned above.

I replicated this issue with a simple 13 line project here.

[WCFTest.zip](https://github.com/dotnet/wcf/files/4506629/WCFTest.zip)

This project works fine locally, but fails in devops with the same error version error.

Any insights would be appreciated.

**Comment by pmiddleton** [comment]
@StephenBonikowsky , @dasetser,  @mconnew 

Today I tried a different approach of creating a library project for the serializer directly in my solution.

I ran dotnet-svcutil.xmlserializer manually and took the output source cs file and compiled that into a .net standard 2.0 library, making sure to follow the same assembly naming convention.  I then referenced that library from my application.  

That approach failed to work.  The serializer code was never accessed. 

I tried searching the System.Private.ServiceModel codebase for where the serializers are loaded, but couldn't find how you are loading that assembly.  My best guess is that somehow it deals with the  class GeneratedXmlSerializers but didn't see any code that loaded data into that classes private dictionary.

Any insights into why my manual approach didn't work or why the tool fails in devops would be helpful.

**Comment by HongGit** [comment]
@pmiddleton  sorry that you are running into this issue!

Since the code is open source , can you please try to inject some debugging code, compile and test this out?

**Comment by pmiddleton** [comment]
I tried that previously, see my comment from 3rd comment above.  The extra logging works locally but not in devops.  The code inside the tool is never called in devops.  The pipeline is having an issue resolving the executable code.  I have not been able to figure out why.  

Devops does manage to find the targets file inside of the package, because I can get extra logging into that msbuild file and that will print out.

**Comment by dasetser** [comment]
@pmiddleton So it's failing to find or download the cli tool on AzDo for some reason? In your zip project I see that you're referencing dotnet-svcutil.xmlserializer with a PackageReference. Does it make any difference if you change it to a cli tool reference? 
`<DotNetCliToolReference Include="dotnet-svcutil.xmlserializer" Version="1.2.0" />`

I believe it should be referenced like this to run the tool, but I don't know why your current approach works correctly on your local machine but not an AzDo machine. The only thing I can think of would be if you have something saved in your nuget cache that is causing it to work that doesn't exist on the cloud machine.

**Comment by dasetser** [comment]
Let us know if there's anything else we can help with for this issue.

**Comment by vzalamea** [comment]
Adding this worked for me.  <Project>.XmlSerializers.dll is now being created.  Thank you!!!  
<ItemGroup>
    <DotNetCliToolReference Include="dotnet-svcutil.xmlserializer" Version="1.2.0" />
  </ItemGroup>
