### ISSUE TITLE
Several WSDL 

### ISSUE THREAD

**Issue by nicoclau** [dotnet/wcf#4245]
We try to use wsdl from 

https://support.travelport.com/webhelp/uapi/Content/Resources/uAPI_WSDLschema_Release-V19.2.0.12.zip with 

"inputs": [
      "../../WSDL/air_v49_0/Air.wsdl",     
      "../../WSDL/universal_v49_0/UniversalRecord.wsdl"
    ],

If we try "../../WSDL/air_v49_0/Air.wsdl", alone it works,
if we try   "../../WSDL/universal_v49_0/UniversalRecord.wsdl" alone it works

But we try these two together

it failed with , why?
Is there a way to reuse the types between the wsdl?

Thanks!

Resolving project references ...
Importing web service metadata ...
Number of service endpoints found: 0
Scaffolding service reference code ...
Warning:Warning: Cannot import wsdl:binding
Detail: Element message named AirRepriceSearchPortType from namespace http://www.travelport.com/service/air_v49_0 is missing.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:binding[@name='AirRepriceSearchBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:service[@name='AirService']/wsdl:port[@name='AirRepriceSearchPort']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:service[@name='AirService']/wsdl:port[@name='AirLowFareSearchAsynchPort']
Warning:Warning: Cannot import wsdl:binding
Detail: Element message named AirPricePortType from namespace http://www.travelport.com/service/air_v49_0 is missing.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:binding[@name='AirPriceBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:service[@name='AirService']/wsdl:port[@name='AirFareRulesPort']
Warning:Warning: Cannot import wsdl:binding
Detail: Element message named AirFareDisplayPortType from namespace http://www.travelport.com/service/air_v49_0 is missing.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:binding[@name='AirFareDisplayBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:service[@name='AirService']/wsdl:port[@name='SeatMapPort']
Warning:Warning: Cannot import wsdl:binding
Detail: Element message named AirRefundQuotePortType from namespace http://www.travelport.com/service/air_v49_0 is missing.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:binding[@name='AirRefundQuoteBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:service[@name='AirService']/wsdl:port[@name='AirRefundQuotePort']
Warning:Warning: Cannot import wsdl:binding
Detail: Element message named AirRefundTicketPortType from namespace http://www.travelport.com/service/air_v49_0 is missing.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://www.travelport.com/service/air_v49_0']/wsdl:binding[@name='AirRefundTicketBinding']
Warning:Warning: Cannot import wsdl:port
Detail:

**Comment by dasetser** [comment]
@nicoclau The tool is designed to only allow one per service reference, so this not working is expected. You should add one reference for each service and use them individually. 

As far as getting them to reuse types, the tool does try to reuse types from any references rather than generating new ones. So I would suggest taking the types that are common between the two services and putting them in a library that your project references. Then run the tool to add a reference for each service and make sure it reuses types from all references (which should be the default for the tool unless you're specifying differently).
