### ISSUE TITLE
"System.ServiceModel.Primitives, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" mismatch "System.ServiceModel.Primitives" "System.ServiceModel.Primitives, Version=4.5.0.4, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

### ISSUE THREAD

**Issue by l4nk4b3l** [dotnet/wcf#4269]
**To Reproduce**
1. Create a UWP-App 
2. Add a netstandard 2.0 classlibary
3. Add System.ServiceModel.Primitves Version=4.7.0.0 to classlibary
4. Add project reference in uwp-app to classlibary
5. Add some code that uses System.ServiceModel.Primitves in UWP
6. compile error

**Expected behavior**
it should compile

**Repository for Reproduction**
https://github.com/l4nk4b3l/compatibilitytestapp/tree/master/CompatibilityTestApp

**Comment by HongGit** [comment]
Thanks for reporting this issue!

This is not a WCF specific issue.  Try to update reference version in your app to 4.7, as the version specified in the app will override versions used by the dependencies.

**Comment by l4nk4b3l** [comment]
> Thanks for reporting this issue!
> 
> This is not a WCF specific issue. Try to update reference version in your app to 4.7, as the version specified in the app will override versions used by the dependencies.

As you can see i already referenced to version 4.7 and it is still not working. 
https://github.com/l4nk4b3l/compatibilitytestapp/blob/master/CompatibilityTestApp/CompatibilityTestApp.csproj#L157

**Comment by massijay** [comment]
I have this problem too
