### ISSUE TITLE
Error Adding Connected Service

### ISSUE THREAD

**Issue by roend83** [dotnet/wcf#4275]
I'm getting the following error trying to add connected service reference to an IBM hosted SOAP service in our internal network:

![image](https://user-images.githubusercontent.com/193979/81949286-ac9e1980-95d0-11ea-964a-3db6d7aabc03.png)

This service is hosted inside the company firewall so I can't give you a reproduction, but here's the associated WSDL:

```xml
<!--
File MS_Common_MessageRouter/com/adesa/schemas/ih/msgrouter/MsgRouter.wsdl, application I0021_APP_COMMON_MsgRouter, static library I0021_LIB_COMMON_MessageRouter
-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://schemas.adesa.com/IH/MsgRouter" xmlns:wsdl1="http://schemas.adesa.com/IH/MsgRouter" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://schemas.adesa.com/IH/MsgRouter" name="MsgRouter" targetNamespace="http://schemas.adesa.com/IH/MsgRouter">
<wsdl:documentation>
<wsdl:appinfo source="WMQI_APPINFO">
<MRWSDLAppInfo imported="true">
<generatedMXSD location="MsgRouter_InlineSchema1.mxsd"/>
<binding hasEncoding="false" imported="true" name="MsgRouterSOAP" originalBindingStyle="document"/>
</MRWSDLAppInfo>
</wsdl:appinfo>
</wsdl:documentation>
<wsdl:types>
<xsd:schema targetNamespace="http://schemas.adesa.com/IH/MsgRouter">
<xsd:include schemaLocation="http://inthub.test.auctionintegrationhub.com:80/MsgRouter?xsd=xsd0"/>
</xsd:schema>
<xsd:schema>
<xsd:import namespace="http://schemas.adesa.com/IH/MsgRouter" schemaLocation="http://inthub.test.auctionintegrationhub.com:80/MsgRouter?xsd=xsd1"> </xsd:import>
<xsd:import namespace="http://schemas.adesa.com/IH/MsgRouter" schemaLocation="http://inthub.test.auctionintegrationhub.com:80/MsgRouter?xsd=xsd2"> </xsd:import>
</xsd:schema>
</wsdl:types>
<wsdl:message name="RouteMessageRequest">
<wsdl:part element="xsd1:MsgRouterRequest" name="parameters"/>
</wsdl:message>
<wsdl:message name="RouteMessageResponse">
<wsdl:part element="xsd1:MsgRouterResponse" name="parameters"/>
</wsdl:message>
<wsdl:portType name="MsgRouter">
<wsdl:operation name="RouteMessage">
<wsdl:input message="tns:RouteMessageRequest"/>
<wsdl:output message="tns:RouteMessageResponse"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="MsgRouterSOAP" type="tns:MsgRouter">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="RouteMessage">
<soap:operation soapAction="http://schemas.adesa.com/IH/MsgRouter/RouteMessage"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="MsgRouter">
<wsdl:port binding="tns:MsgRouterSOAP" name="MsgRouterSOAP">
<soap:address location="http://inthub.test.auctionintegrationhub.com:80/MsgRouter"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
```

**Comment by roend83** [comment]
I'm running Visual Studio Enterprise 2019 version 16.5.4

**Comment by roend83** [comment]
Note the latest version of the dotnet-svcutil global tool does appear to work for this service

**Comment by dasetser** [comment]
@imcarolwang Can you try reproing this and let us know which version of dotnet-svcutil this works on and verify if the latest version of VS is using an older version? If it works with the latest dotnet-svcutil we just need to update the verison VS is using.

**Comment by imcarolwang** [comment]
@dasetser  I got other error: "the remote name couldn't be resolved: 'inthub.test.auctionintegrationhub.com'" when trying to reproduce the issue with the given wsdl, because the referenced schema and the service server are unavailable. Thoughts?

**Comment by roend83** [comment]
I can check for you if you tell me where the application is installed in
Visual Studio.

**Comment by imcarolwang** [comment]
Thanks @roend83. 

The tool version VS used can be found by checking path similar as: 

> "%systemdrive%\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\WCF Connected Service\Microsoft.Tools.ServiceModel.Svcutil.dll"

The global tool is a nuget package installed to the machine, file to check:

> "%userprofile%\.nuget\packages\dotnet-svcutil-lib\2.0.2\lib\netcoreapp2.1\dotnet-svcutil-lib.dll"

**Comment by imcarolwang** [comment]
Thank you for the sharing,@roend83. The versions seem matched. Is it possible you are hitting the same problem as in https://github.com/dotnet/wcf/issues/2546, https://github.com/dotnet/wcf/issues/2862?

**Comment by klinki** [comment]
Hello @imcarolwang ,

I have very similar problem.
When I create service in old .NET 4.8 project, everything works fine, Add service reference window can detect the SOAP service and generate code.

![2020-05-28](https://user-images.githubusercontent.com/1476175/83132206-59a08800-a0e1-11ea-8d52-2c30d28dfc16.png)

When I try to do the same with .NET Core 3.1 project and add WCF Web Service Reference, it shows warnings and doesn't detect any methods in soap service.

![2020-05-28 (1)](https://user-images.githubusercontent.com/1476175/83132311-7d63ce00-a0e1-11ea-9abb-8f569b15d674.png)

Warning details are following:
![2020-05-28 (2)](https://user-images.githubusercontent.com/1476175/83132408-a4220480-a0e1-11ea-9a05-982914b30418.png)

```
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:service[@name='AvangateService']/wsdl:port[@name='AvangateAPIPort']
Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: The complexType 'urn:order:SkuPricingOptionsArray' has already been declared.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
```

if I ignore these warnings and click finish, I get the same error windows as @roend83.

![2020-05-28 (3)](https://user-images.githubusercontent.com/1476175/83132639-fb27d980-a0e1-11ea-9cf6-b178a051f197.png)

```
Importing web service metadata ...
Number of service endpoints found: 0
Scaffolding service reference code ...
Warning:Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: The complexType 'urn:order:SkuPricingOptionsArray' has already been declared.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:service[@name='AvangateService']/wsdl:port[@name='AvangateAPIPort']
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
Error:Error: No code was generated.
If you were trying to generate a client, this could be because the metadata documents did not contain any valid contracts or services, or because all contracts/services were discovered to exist in --reference assemblies. Verify that you passed all the metadata documents to the tool.
Done.
```


I'm trying to generate client for this SOAP service: https://api.avangate.com/soap/6.0/?wsdl

**Comment by imcarolwang** [comment]
@klinki Your problem seems different than reported in this issue, check the error message:

> Error: The complexType 'urn:order:SkuPricingOptionsArray' has already been declared.

While @roend83 's problem is:

> Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.3, ...'

**Comment by klinki** [comment]
Oh I see, you are right. I will create another issue for that.

**Comment by HongGit** [comment]
@roend83 has your issue been resolved?
