### ISSUE TITLE
consuming third party WSDL endpoint with MTOM 

### ISSUE THREAD

**Issue by yalin78** [dotnet/wcf#4280]
Hi,

I have a .net core 2.2 application which is downloading a file over WSDL from third party. But i don't see an option to set MTOM encoding in basic http binding in .net core. Can you please help?

**Comment by RealHabix** [comment]
Sadly, the mtom is in "plan" for past 3 years.. WCF failed us big time..

**Comment by mconnew** [comment]
The community has created an external mtom encoder that you can find here: https://github.com/lennykean/WcfCoreMtomEncoder

**Comment by mconnew** [comment]
This is a duplicate of #1810 so closing.
