### ISSUE TITLE
MessageBodyStream.Read() with count=0 unexpectedly terminates Stream

### ISSUE THREAD

**Issue by mriehm** [dotnet/wcf#4281]
**Describe the bug**
If [MessageBodyStream.Read()](https://github.com/dotnet/wcf/blob/42b5572be18cb6d0d60718f24143a541b5dea755/src/dotnet-svcutil/lib/src/FrameworkFork/System.ServiceModel/System/ServiceModel/Dispatcher/StreamFormatter.cs#L239) is called with count=0, then _reader.ReadContentAsBase64() will return 0 bytes read, and so this code will execute which terminates the Stream:

[if (bytesRead == 0)](https://github.com/dotnet/wcf/blob/42b5572be18cb6d0d60718f24143a541b5dea755/src/dotnet-svcutil/lib/src/FrameworkFork/System.ServiceModel/System/ServiceModel/Dispatcher/StreamFormatter.cs#L278)
{
    Exhaust(_reader);
}

This 'Exhaust' case is presumably intended for when the bytesRead=0 result is due to no more bytes being able to be read from the XmlDictionaryReader, not for when bytesRead=0 simply is the trivial result of a count=0 argument.

I ran into this bug on .NET Desktop Framework, but the code appears the same here, so I'm filing an issue here, though I technically haven't reproduced this issue with this repo's .NET Core Nuget package.

**To Reproduce**
I think this bug is obvious from looking at the code, and my current projects in which I am reproducing this are too large to post here. So, I'm not posting a repro here, but let me know if you need one.

**Expected behavior**
I expect that calling MessageBodyStream.Read() with count=0 should have no side-effects on the state of the MessageBodyStream (i.e. should not advance Position and should not affect the result of any subsequent call to MessageBodyStream.Read()), since that is the behavior for any other Stream in .NET as far as I have observed.

Granted, the [Stream.Read() documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read) doesn't seem to explicitly call out how to handle count=0, and, actually, strictly interpreting this sentence in the documentation would actually support the current behavior: "Read returns 0 only when there is no more data in the stream and no more is expected". However, that seems to me to be a documentation bug since that is not the behavior of passing count=0 to any other .NET Stream that I've worked with, such as FileStream or MemoryStream.

**Additional context**
In my case, and, perhaps, in most cases, it is simple enough to adjust the consuming code to avoid calling MessageBodyStream.Read() in the first place if count is going to be passed as 0, which is probably ideally how code should be written anyway. However, in order to know to work around it, first we have to notice the behavior is not what we expected based on how our code works with all other .NET Streams. Also, the code making the call to MessageBodyStream.Read() may not always be under our control to change (e.g. in third-party library code). So, I think this should be fixed in MessageBodyStream itself.

**Comment by HongGit** [comment]
@mriehm very mice finding!

We won't fix this in .NET framework.  However, if you could submit a PR for .NET Core, we will review and accept it.

Thanks for your feedback!
