### ISSUE TITLE
Why is RequestSecurityToken marked internal ?

### ISSUE THREAD

**Issue by mikkeljohnsen** [dotnet/wcf#4287]
**Describe the bug**
I am trying to request a SecurityToken through a STS. But RequestSecurityToken is not available.

**To Reproduce**
1. "new RequestSecurityToken()" not available.

**Comment by HongGit** [comment]
@mikkeljohnsen we are in the process of releasing WSFederation support.  If you could wait for a few weeks, hopefully that will provide what you need.

**Comment by mikkeljohnsen** [comment]
@HongGit Thanks, I hope it will be available soon. I have checked out the branche "release/3.1.0" and can see that will be the 4.8.0 NuGet release. But "RequestSecurityToken" is still not available.

**Comment by mikkeljohnsen** [comment]
Has it not been a few weeks now :)

**Comment by PCDiver** [comment]
WsTrustChannelFactory and support for actas, onbehalfof, ... would be very much appreciated.

**Comment by HongGit** [comment]
The new 4.8.0-preview3 WCF Core Packages have been published to Nuget.org last week.

Please check them out.  @PCDiver feel free to open a new issue if WsTrustChannelFactory support is not in this release.

**Comment by mikkeljohnsen** [comment]
@HongGit I do not see that "RequestSecurityToken" is available in those NuGet packages ?
