### ISSUE TITLE
Cannot create connected service with duplicate complex types

### ISSUE THREAD

**Issue by klinki** [dotnet/wcf#4291]
**Describe the bug**
I cannot create connected service in .NET Core when it has duplicate complex types. 

When I create service in old .NET 4.8 project, everything works fine, Add service reference window can detect the SOAP service and generate code.

![2020-05-28](https://user-images.githubusercontent.com/1476175/83132206-59a08800-a0e1-11ea-8d52-2c30d28dfc16.png)

When I try to do the same with .NET Core 3.1 project and add WCF Web Service Reference, it shows warnings and doesn't detect any methods in soap service.

![2020-05-28 (1)](https://user-images.githubusercontent.com/1476175/83132311-7d63ce00-a0e1-11ea-9abb-8f569b15d674.png)

Warning details are following:
![2020-05-28 (2)](https://user-images.githubusercontent.com/1476175/83132408-a4220480-a0e1-11ea-9a05-982914b30418.png)

```
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:service[@name='AvangateService']/wsdl:port[@name='AvangateAPIPort']
Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: The complexType 'urn:order:SkuPricingOptionsArray' has already been declared.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
```

if I ignore these warnings and click finish, I get the same error windows as @roend83.

![2020-05-28 (3)](https://user-images.githubusercontent.com/1476175/83132639-fb27d980-a0e1-11ea-9cf6-b178a051f197.png)

```
Importing web service metadata ...
Number of service endpoints found: 0
Scaffolding service reference code ...
Warning:Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: The complexType 'urn:order:SkuPricingOptionsArray' has already been declared.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:service[@name='AvangateService']/wsdl:port[@name='AvangateAPIPort']
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Warning:Warning: Cannot import wsdl:binding
Detail: There was an error importing a wsdl:portType that the wsdl:binding is dependent on.
XPath to wsdl:portType: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:portType[@name='AvangateAPIPortType']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
Error:Error: No code was generated.
If you were trying to generate a client, this could be because the metadata documents did not contain any valid contracts or services, or because all contracts/services were discovered to exist in --reference assemblies. Verify that you passed all the metadata documents to the tool.
Done.
```

**To Reproduce**
1. Try to generate connected service from this WSDL: https://api.avangate.com/soap/6.0/?wsdl

**Expected behavior**
Client should be generated without errors.

**Comment by HongGit** [comment]
@imcarolwang could you please take a look and see why it is different between .NET and .NET Core?

**Comment by imcarolwang** [comment]
@klinki Can you confirm if on .NET4.8 the tool correctly generated usable Reference.cs? I tried using this wsdl https://api.avangate.com/soap/6.0/?wsdl to generate proxy code on both .NET4.8 and .NET Core, it looks like although .NET Framework tool showed the available operation list of the service, it generate an invalid empty Reference.cs without showing any warning or error, but with .NetCore tool you'll see the warning/error it detected.

**Comment by klinki** [comment]
I just tried again and it seems it didn't really work in .NET4.8 either. 

I guess I must have used https://api.avangate.com/soap/4.0/?wsdl after all. I was migrating our old code to .NET Core and I tried also to update some old APIs so I have been trying the newer version first.

I tested again and for version 4 it discovered services and appeared to start generating code, but at the end it didn't work for Core. In .NET 4.8 it worked.

Version 3 of the web service works also in .NET Core, but it shows this warning after finishing the code generation:
```
Importing web service metadata ...
Number of service endpoints found: 0
Scaffolding service reference code ...
Warning:Warning: Cannot import wsdl:binding
Detail: An item with the same key has already been added. Key: System.ServiceModel.Description.OperationDescription
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:service[@name='AvangateService']/wsdl:port[@name='AvangateAPIPort']
Warning:Warning: No endpoints compatible with .Net Core apps were found.
Updating project ...
Done.
``` 
![obrazek](https://user-images.githubusercontent.com/1476175/84511194-771b4780-acc6-11ea-9c1e-683eb894c706.png)

I tested again and it seems only version 4 is generated and it is generated in both, full .NET4.8 and .NET Core 3.1 too. Versions 5 and 6 appear to be working in .NET4.8 but it is not and it just generates empty `Reference.cs` file.


I tested following WSDLs:
https://api.avangate.com/soap/3.0/?wsdl - this one seems to be working in both Core and 4.8
https://api.avangate.com/soap/4.0/?wsdl - this one works only in 4.8
https://api.avangate.com/soap/5.0/?wsdl - these 2 are not working in either Core or 4.8
https://api.avangate.com/soap/6.0/?wsdl

**Comment by imcarolwang** [comment]
For WSDLs which seem "works" on .NET4.8  showed the same warning as reported by .NetCore Connected Service tool when I use command line tool svcutil.exe to generate service proxy:

> Cannot import wsdl:port
> Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
> XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
> XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:service[@name='AvangateService']/wsdl:port[@name='AvangateAPIPort']
> Cannot import wsdl:binding
> Detail: An item with the same key has already been added.
> XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:order']/wsdl:binding[@name='AvangateAPIBinding']
> There was an error verifying some XML Schemas generated during export:
> Type 'http://www.w3.org/2001/XMLSchema:complexType' is not declared.
> There was an error verifying some XML Schemas generated during export:
> 'all' is not the only particle in a group, or is being used as an extension.

It turns out the wsdl file itself got some problem. The difference is that for .NetFramework Add-Service-Reference tool it generate the proxy code without reporting warning/error, but the generated code doesn't seem work, while the .NETCore tool report the warning/errors and tried to generate code but failed for those "not working" WSDL ...

**Comment by HongGit** [comment]
Closing this issue as no response for over a year.

Feel free to reactivate if this issue persists or open a new issue if you run into other problems.

**Comment by tavisca-mnamdeo** [comment]
Hi @HongGit ,
Good afternoon.
I am getting the same issue.
I have WCF SVC created in .net 4.61 project.
When I amtrying to add referance in .net core project I am getting following error:

Importing web service metadata ...
Scaffolding service reference code ...
Number of service endpoints found: 0
ErrorNo code was generated.
If you were trying to generate a client, this could be because the metadata documents did not contain any valid contracts or services, or because all contracts/services were discovered to exist in --reference assemblies. Verify that you passed all the metadata documents to the tool.
Done.
ErrorFailed adding service reference(s). Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

I am using Visual studio professional 2019
16.11.17 update.

Please help.
thanks
Manmohan

**Comment by ramiabughazaleh** [comment]
@klinki Just wondering if you ever got the dotnet or Visual Studio tooling to work with https://api.avangate.com/soap/6.0/?wsdl?

Thank you.

**Comment by klinki** [comment]
Yeah but I think I had to download the WSDL file and manually edit it.
