### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm'.

### ISSUE THREAD

**Issue by jieling07** [dotnet/wcf#4292]
I developed it in ". Net formwork 4.7.2" and it was completely successful.
This is part of the file configuration. The following two configurations are important. 
<system.serviceModel>
        \<bindings>
            \<basicHttpBinding>
                \<binding name="QualificationService">
                    \<security mode="Transport">
                        \<transport clientCredentialType="Basic" />
                        \<message clientCredentialType="UserName" />
                    \</security>
                \</binding>
        \</bindings>
    </system.serviceModel>
Now, I developed it in ". Net Core 3.1" .
Download WCF Service Code:
    System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
Error Message:  The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic Realm'.

I try add : result.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
Error Message: The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm'.

Comparison with ". Net formwork 4.7.2",".net core" no “web.config”. I doubt “result.Security” Missing setting for 'Message' .
I'm Chinese, English is terrible.

**Comment by HongGit** [comment]
@jieling07 could you please try to set ChannelFactory.Credentials.UserName on the ChannelFactory and see if it works for you?

**Comment by HongGit** [comment]
Feel free to reopen if the above suggestion does not work for you, thanks for your suggestion!

**Comment by koohgard** [comment]
hi @jieling07  , @HongGit 
i have a same problem 
i set  ChannelFactory.Credentials.UserName  but not work for me 
@jieling07 If you have solved it please help me

**Comment by AmerHashima** [comment]
hi What You do  to solve this problem

**Comment by jieling07** [comment]
. net core cannot be implemented, so it can only be created Net formwork framework. After adding WCF service, modify the configuration "Web.config"
The production configuration is like this

<binding name="YourWcfService"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; <security mode="Transport" /&gt;
</binding&gt;

Change to


<binding name="YourWcfService" maxBufferSize="2147483647" maxReceivedMessageSize="2147483647"&gt;
&nbsp; &nbsp; &nbsp; <security mode="Transport"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<transport clientCredentialType="Basic" /&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<message clientCredentialType="UserName" /&gt;
&nbsp; &nbsp; &nbsp; &nbsp;</security&gt;
</binding&gt;

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnet/wcf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnet/wcf] The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm'. (#4292)





 
hi What You do  to solve this problem
