### ISSUE TITLE
Split service reference file in multiple files

### ISSUE THREAD

**Issue by bstordrup** [dotnet/wcf#4296]
When the SvcUtil is creating the service reference code, it would be nice to have an option to generate individual files per class in a folder instead of creating all classes in the Reference.cs file.

This file may depending on the used service grow extremely large - I have a setup where it generates a 217000+ lines of code reference.cs, and that causes Visual Studio 2019 (or an extension) to crash without any error message. Seems like it is an OutOfMemory exception when processing the reference.cs file.

**Comment by dasetser** [comment]
@bstordrup This sounds like it's the same feature request as #3512, so I'm going to close this issue. Please comment or react on that issue so we can keep one place to track the request.
