### ISSUE TITLE
Accessing raw XML in SOAP serive

### ISSUE THREAD

**Issue by hohounk** [dotnet/wcf#4299]
I'm using .net core and have to access a SOAP service. I can generate client side code for doing it with svcutil and it works fine. What I now need is to also get access to the raw XML being sent back and forth but for the life of me I can't see a way to do it.

With regular .net I could use SoapExtensions to make something that passes through all the XML messages but same doesn't seem to be possible with .net core. Are there any other ways to access the XML messages from within the code?

**Comment by HongGit** [comment]
@mconnew can you please provide the guidance?

**Comment by mconnew** [comment]
If you are using HTTP, you can install a custom MessageHandler and read the XML from the HTTP request on it's way out or on the reply. A blog post giving an overview of the mechanism is [here](https://medium.com/trueengineering/realization-of-the-connections-pool-with-wcf-for-net-core-with-usage-of-httpclientfactory-c2cb2676423e). There's an example of a behavior which accesses the request and response [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/HttpBindingTestHelpers.cs). And example of that behavior being used to access and modify the content body is [here](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs#L143).

**Comment by hohounk** [comment]
Thank you, awesome. I'll give it a try
