### ISSUE TITLE
wcf client with BasicHttpBinding miss proxy setting in .net core 3.1 and System.ServiceModel 4.7

### ISSUE THREAD

**Issue by marcocao** [dotnet/wcf#4305]
**Describe the bug**
if you have a proxy settting in os, wcf client with BasicHttpBinding miss it.

**To Reproduce**
1. call a wcf client endpoint with BasicHttpBinding miss proxy setting in .net core 3.1 and System.ServiceModel 4.7.
2. 
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
System.ServiceModel.Channels.HttpChannelFactory<TChannel>+HttpClientRequestChannel+HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
System.Runtime.TaskHelpers.WaitForCompletionNoSpin<TResult>(Task<TResult> task)
System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
System.ServiceModel.Channels.ServiceChannel.Call(string action, bool oneway, ProxyOperationRuntime operation, object[] ins, object[] outs, TimeSpan timeout)
System.ServiceModel.Channels.ServiceChannel.Call(string action, bool oneway, ProxyOperationRuntime operation, object[] ins, object[] outs)
System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, object[] args)
System.Reflection.DispatchProxyGenerator.Invoke(object[] args)
generatedProxy_1.protect(protectRequest1 )
Farfetch.PartnerPayment.Data.Gateway.Liaison.LiaisonProvider.TokenManagerWebServicedl23Client.Farfetch.PartnerPayment.Data.Gateway.Liaison.LiaisonProvider.TokenManagerWebServicedl23.protect(protectRequest1 request) in Reference.cs
3. For issues related to generating client code using dotnet-svcutil please provide the WSDL.

**Expected behavior**
 proxy setting should be filled to binding automatically

**Screenshots**

**Additional context**

**Comment by mconnew** [comment]
Which OS are you using? I use the automatic OS proxy config capability regularly when debugging new code for WCF. When I use fiddler and configure it as the system proxy, requests do go through fiddler. Are you trying to connect to a service running on localhost as system configured proxies get skipped when the service url is http://localhost. If this is your issue, you can instead use your machines hostname instead and the proxy will be used.

**Comment by HongGit** [comment]
@marcocao if @mconnew comments does not solve your problem, feel free to re-activate the issue!
