### ISSUE TITLE
Error al importar wsdl:binding del que depende wsdl:port. XPath a wsdl:binding: //wsdl:definitions[@targetNamespace

### ISSUE THREAD

**Issue by AlfredoDiaz13** [dotnet/wcf#4318]
Buenas tardes, estoy teniendo problemas al importar el Web Services

http://www.servifact.com.mx/timbrado/servicios.asmx

No se puede importar wsdl:port
Detalles: Error al importar wsdl:binding del que depende wsdl:port.
XPath a wsdl:binding: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:binding[@name='ServiciosHttpPost']
XPath al origen del error: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:service[@name='Servicios']/wsdl:port[@name='ServiciosHttpPost']
No se puede importar wsdl:binding
Detalles: Error al importar wsdl:portType del que depende wsdl:binding.
XPath a wsdl:portType: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:portType[@name='ServiciosHttpPost']
XPath al origen del error: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:binding[@name='ServiciosHttpPost']
No se puede importar wsdl:portType
Detalles: Se inició una excepción al ejecutar una extensión de importación WSDL: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: El tipo 'http://schemas.xmlsoap.org/soap/encoding/:Array' al que se hace referencia sólo es válido para SOAP codificado.
XPath al origen del error: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:portType[@name='ServiciosHttpPost']
No se puede importar wsdl:port
Detalles: Error al importar wsdl:binding del que depende wsdl:port.
XPath a wsdl:binding: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:binding[@name='ServiciosHttpGet']
XPath al origen del error: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:service[@name='Servicios']/wsdl:port[@name='ServiciosHttpGet']
No se puede importar wsdl:binding
Detalles: Error al importar wsdl:portType del que depende wsdl:binding.
XPath a wsdl:portType: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:portType[@name='ServiciosHttpGet']
XPath al origen del error: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:binding[@name='ServiciosHttpGet']
No se puede importar wsdl:portType
Detalles: Se inició una excepción al ejecutar una extensión de importación WSDL: System.ServiceModel.Description.XmlSerializerMessageContractImporter
Error: El tipo 'http://schemas.xmlsoap.org/soap/encoding/:Array' al que se hace referencia sólo es válido para SOAP codificado.
XPath al origen del error: //wsdl:definitions[@targetNamespace='http://servifact.com.mx/']/wsdl:portType[@name='ServiciosHttpGet']

**Comment by imcarolwang** [comment]
Closing as the service's wsdl doesn't meet the interop guidelines.
Similar issue was reported in https://github.com/dotnet/wcf/issues/3157 and https://github.com/dotnet/wcf/issues/3327.

**Comment by GGVK** [comment]
Hola señores, lo que pasa es qeu en una nueva version de WCF, Microsoft cambio las caracteristicas de default asi que el en ves de Reutilizar los tipos de ensamblado, debe desmarcarlo. Despues marcar el check de Generar siempre contratos de mensaje.

![Image](https://github.com/user-attachments/assets/f4819237-6a19-42e8-b891-e54d7b97714f)
