### ISSUE TITLE
GetCertificateSecurityToken blocks async flow

### ISSUE THREAD

**Issue by alexey-gusarov** [dotnet/wcf#4319]
**Describe the bug**
We used basicHttpBinding with client certificate. It's works, but our QA engineer observe slow performance.
In profiler I saw that we in waiting almost all time.

In callstack:
`async HttpsClientRequestChannel.GetHttpClientAsync` calls `sync HttpsChannelFactory.GetCertificateSecurityToken` that use **sync GetAwaiter().GetResult()**
https://github.com/dotnet/wcf/blob/5e5fd9e58cc410f48f4f9feed34801a0a6a65def/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs#L150

**To Reproduce**
Just use basicHttpBinding with client certificate

Stack from windbg
```
       Child SP               IP Call Site
00000081181FDE50 00007ff8794b0cba [GCFrame: 00000081181fde50] 
00000081181FDF98 00007ff8794b0cba [HelperMethodFrame_1OBJ: 00000081181fdf98] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
00000081181FE0C0 00007ff80cbed18a System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken) [/_/src/System.Private.CoreLib/shared/System/Threading/ManualResetEventSlim.cs @ 626]
00000081181FE160 00007ff80cbecc6b System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs @ 2941]
00000081181FE1D0 00007ff80cbeca39 System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs @ 2827]
00000081181FE250 00007ff80cbeb8c3 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs @ 141]
00000081181FE280 00007ff80d12ce26 System.ServiceModel.Channels.HttpsChannelFactory`1[[System.__Canon, System.Private.CoreLib]].GetCertificateSecurityToken(System.IdentityModel.Selectors.SecurityTokenProvider, System.ServiceModel.EndpointAddress, System.Uri, System.ServiceModel.Channels.ChannelParameterCollection, System.Runtime.TimeoutHelper ByRef) [/_/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs @ 163]
00000081181FE2E0 00007ff80d12cb76 System.ServiceModel.Channels.HttpsChannelFactory`1+HttpsClientRequestChannel+d__15[[System.__Canon, System.Private.CoreLib]].MoveNext()
00000081181FE370 00007ff80d12ca2c System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.ServiceModel.Channels.HttpsChannelFactory`1+HttpsClientRequestChannel+d__15[[System.__Canon, System.Private.CoreLib]], System.Private.ServiceModel]](d__15<System.__Canon> ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00000081181FE3E0 00007ff80d12c90f System.ServiceModel.Channels.HttpsChannelFactory`1+HttpsClientRequestChannel[[System.__Canon, System.Private.CoreLib]].GetHttpClientAsync(System.ServiceModel.EndpointAddress, System.Uri, System.Runtime.TimeoutHelper)
00000081181FE480 00007ff80cc39193 System.ServiceModel.Channels.HttpChannelFactory`1+HttpClientRequestChannel+HttpClientChannelAsyncRequest+d__13[[System.__Canon, System.Private.CoreLib]].MoveNext()
00000081181FE560 00007ff80d12c52c System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.ServiceModel.Channels.HttpChannelFactory`1+HttpClientRequestChannel+HttpClientChannelAsyncRequest+d__13[[System.__Canon, System.Private.CoreLib]], System.Private.ServiceModel]](d__13<System.__Canon> ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00000081181FE5D0 00007ff80d12c419 System.ServiceModel.Channels.HttpChannelFactory`1+HttpClientRequestChannel+HttpClientChannelAsyncRequest[[System.__Canon, System.Private.CoreLib]].SendRequestAsync(System.ServiceModel.Channels.Message, System.Runtime.TimeoutHelper)
00000081181FE6A0 00007ff80cc39d40 System.ServiceModel.Channels.RequestChannel+d__33.MoveNext()
00000081181FE760 00007ff80d12ba64 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.ServiceModel.Channels.RequestChannel+d__33, System.Private.ServiceModel]](d__33 ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00000081181FE7C0 00007ff80d12b9a8 System.ServiceModel.Channels.RequestChannel.RequestAsync(System.ServiceModel.Channels.Message, System.TimeSpan)
00000081181FE860 00007ff80cc3a3c2 System.ServiceModel.Channels.RequestChannel+d__32.MoveNext()
00000081181FE8D0 00007ff80d12b8a4 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.ServiceModel.Channels.RequestChannel+d__32, System.Private.ServiceModel]](d__32 ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00000081181FE930 00007ff80d12b7e5 System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(System.ServiceModel.Channels.Message, System.TimeSpan)
00000081181FE9A0 00007ff80d12b75d System.ServiceModel.Channels.RequestChannel.BeginRequest(System.ServiceModel.Channels.Message, System.TimeSpan, System.AsyncCallback, System.Object) [/_/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs @ 211]
00000081181FE9D0 00007ff80d12b734 System.ServiceModel.Dispatcher.RequestChannelBinder.BeginRequest(System.ServiceModel.Channels.Message, System.TimeSpan, System.AsyncCallback, System.Object) [/_/src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/RequestChannelBinder.cs @ 92]
00000081181FEA00 00007ff80d12b559 System.ServiceModel.Channels.ServiceChannel+SendAsyncResult.StartSend(Boolean) [/_/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs @ 1851]
00000081181FEA80 00007ff80d12b2a9 System.ServiceModel.Channels.ServiceChannel+SendAsyncResult.FinishEnsureOpen(System.IAsyncResult, Boolean) [/_/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs @ 1804]
00000081181FEAD0 00007ff80cc1b0e9 System.Runtime.Fx+AsyncThunk.UnhandledExceptionFrame(System.IAsyncResult) [/_/src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs @ 943]
00000081181FEB10 00007ff80d12b13d System.Runtime.TaskHelpers+c.b__2_1(System.Threading.Tasks.Task, System.Object) [/_/src/System.Private.ServiceModel/src/Internals/System/Runtime/TaskHelpers.cs @ 134]
00000081181FEB50 00007ff80cbedda1 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 315]
00000081181FEBA0 00007ff80cbd49bf System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs @ 2421]
00000081181FEC50 00007ff80cbc7881 System.Threading.ThreadPoolWorkQueue.Dispatch() [/_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs @ 699]
00000081181FF0D0 00007ff86b5c6b93 [DebuggerU2MCatchHandlerFrame: 00000081181ff0d0] 
```
Stack from JetBrains dotTrace profiler
![image](https://user-images.githubusercontent.com/2213498/88887182-91908c80-d244-11ea-959b-fdde9fc46d14.png)

**Expected behavior**
GetCertificateSecurityToken works as async and don't block async flow

**Links**
Async All the Way Down https://devblogs.microsoft.com/pfxteam/should-i-expose-synchronous-wrappers-for-asynchronous-methods/

**Comment by mconnew** [comment]
The certificate provider should complete that call synchronously. It basically takes the client certificate provided to ClientCredentials and wraps it in an X509SecurityToken. The concrete implementation of requestCertificateProvider should be an instance of X509SecurityTokenProvider and that should complete GetTokenAsync synchronously so the GetAwaiter().GetResult() shouldn't do a spin wait. There's a bit of convoluted logic to avoid cycles if someone derives SecurityTokenProvider but basically this should be the call path:  
SecurityTokenProvider.GetTokenAsync call GetTokenCoreAsync (implemented in SecurityTokenProvider and not overriden)  
GetTokenCoreAsync calls and returns TaskFactory.FromAsync(BeginGetTokenCore, EndGetTokenCore, timeout, null)  
BeginGetTokenCore calls GetTokenCoreInternalAsync(timeout).ToApm(callback, state)  
GetTokenCoreInternalAsync is overridden in X509SecurityTokenProvider and looks like [this] 
 (https://github.com/dotnet/wcf/blob/21cd3d45e495ea10d3b270a36390477bfd9b901b/src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/X509SecurityTokenProvider.cs#L43).  
That returns a completed Task. Can you verify what type requestCertificateProvider is? The only way I can see the spinwait being hit is if TaskFactory goes async even when the executing implementation completes synchronously.

**Comment by mconnew** [comment]
I've worked out the problem. Task's always return CompletedSynchronously as false so the double wrap of Task -> Apm -> Task is causing TaskFactory to presume the inner call hasn't completed yet and makes it go async. The calling code in HttpChannelFactory is left over from when we didn't have a synchronous implementation of GetToken (the api was internal only and we removed the sync implementation, but have since exposed it and added it back). I think the simplest fix here is to just make it call the synchronous GetToken method as we have that now.

**Comment by mconnew** [comment]
@alexey-gusarov, the fact this became apparent by your QA team does cause me a small bit of concern. In fact, I have 2 concerns about your usage of WCF. 

My first concern comes from your call stack. You aren't opening the channel factory before you use it. This code path is only executed on channel factory open. From the call stack, I can see that you aren't doing an explicit open, and instead are making a client call, at which point WCF opens the channel factory before making your first call. There is a side effect to this where you can end up preventing concurrent requests to the server if you make additional calls before the first call has completed. It queues the calls only starting the next call after the previous one has fully completed, and keeps doing this until there are no outstanding calls. At which point it switches back to doing concurrent calls.  

My second concern is directly related to your QA team finding this issue. This is only executed once per channel factory open so shouldn't be showing up in any profiles as a cause of concern. You should hopefully only hit this call stack once per process lifetime as you should be reusing your channel factory instance for all client channel creation. This leads me to believe you are doing one of two things. Either instantiating a ChannelFactory instance for every request, or more likely using a client generated by the WCF Connected Services tool and instantiating a new instance every time you make a call. If the former, just cache your ChannelFactory instance (and open it when you create it) for the lifetime of your process and create a new instance using CreateChannel each time. If you're doing the latter, things changed between .NET Framework and .NET Core. We don't support config which means the generated client (which derives from ClientBase<T>) is unable to cache the ChannelFactory instance it uses internally where it was able to on .NET Framework when using config. So you might be instantiating a new instance of your generated client every time you need a client which was okay to do on .NET Framework (not ideal, but not too costly if you did) but is super expensive on .NET Core. If this is the case, use a single instance of the generated client for your entire process. WCF is thread safe to use the same channel instance from multiple threads at once, and with the HTTP transports it will send concurrent requests over separate sockets to the server simultaneously so there's very little contention (we do take a brief lock for some bookkeeping to track outstanding requests but you need to do thousands of concurrent requests for that to even show up in a profile).

**Comment by sbakharev** [comment]
@mconnew, hi. I'm the QA who had originally reported the issue to @alexey-gusarov. He is currently OOO so we will give your fix a try a little later when we would be able to.

We request a .NET Framework WCF service from an ASP.NETCore application via a custom NETStandard client library. If I get things right, your concerns on correctness of ChannelFactory usage belong to the latter, and that's where I got nothing to say (but Alexey should have). But if you have any questions regarding usage context outside of that client library - you're welcome.

Thanks a lot for diving into this!

**Comment by mconnew** [comment]
You are correct. There's at least a little bit of incorrect usage (not opening the channel before using it) but that fact this even was discoverable leads me to think maybe there's more incorrect usage.

**Comment by alexey-gusarov** [comment]
@mconnew 
> You aren't opening the channel factory before you use it.

Hello! Thank you for help with our issue!
Before my vacation I also saw that ChannelBase in .net standard wan't cache ChannelFactory (https://github.com/dotnet/wcf/issues/2032). I implement my own cache and in my test speed increases in ten times.

Also thank you for you fix async->sync.
