### ISSUE TITLE
Problems with generation wsdl client with .NET Core 3.1

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/wcf#4331]
I try to connect to a open API: https://swea.riksbank.se/sweaWS/wsdl/sweaWS_ssl.wsdl

I generate the client just fine in VS 2019 16.7 and the Reference.cs file is created

When I try to execute the remote function I get a 404. 

With postman I can execute the remote function just fine, but I notice that I need to use this exact Content-type and request otherwise I also get a 404

Content-Type: application/soap+xml;charset=UTF-8;action="urn:getCalendarDays"

Request:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://swea.riksbank.se/xsd">
	<soap:Header/>
	<soap:Body>
		<xsd:getCalendarDays>
			<datefrom>2019-08-12</datefrom>
			<dateto>2021-08-12</dateto>
		</xsd:getCalendarDays>
	</soap:Body>
</soap:Envelope>
```

With above postman settings I get a response with correct data.

But if I try todo the same through my client I get a 404. So I though I would debug the WCF client with fiddler, but I cant seem to add a proxy to it, my code

```csharp
            var client = new SweaWebServicePortTypeClient(SweaWebServicePortTypeClient.EndpointConfiguration.SweaWebServiceHttpSoap12Endpoint, new EndpointAddress("https://swea.riksbank.se/sweaWS/services/SweaWebServiceHttpSoap12Endpoint"));
            var binding = client.Endpoint.Binding as CustomBinding;
            var htbe = binding.Elements.Find<HttpTransportBindingElement>();

            var prox = WebRequest.GetSystemWebProxy();
            htbe.UseDefaultWebProxy = false;
            htbe.ProxyAddress = new Uri("http://127.0.0.1:8866");
            htbe.BypassProxyOnLocal = true;
            htbe.UseDefaultWebProxy = false;
            //htbe.ProxyAuthenticationScheme = AuthenticationSchemes.Anonymous;

            var days = await client.getCalendarDaysAsync(DateTime.UtcNow.Date, DateTime.UtcNow.Date.AddDays(31));
```

call to client.getCalendarDaysAsync generates this exception

> 'When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy.'

Google turns up empty handed, please advice. Thanks

**Comment by imcarolwang** [comment]
@AndersMalmgren could you please try to update the referenced wcf package to the latest release and retry your scenario? As a reference you can check out issue #3311 which reported a similar exception thrown when using proxy and it turned out to be a bug in earlier release of the WCF product.

**Comment by HongGit** [comment]
Feel free to re-activate if this is an issue.
