### ISSUE TITLE
New WCF client instance faulted in .NET Core 3.1, works in 2.1

### ISSUE THREAD

**Issue by adolfsson** [dotnet/wcf#4338]
**Describe the bug**
I am using the WCF Web Service Reference Provider to add a service reference to a .NET Core 3.1 Console application. When I instantiate the client class, the State property is Faulted before calling an operation. Switching the console app to .NET Core 2.1 makes the app work as expected (State property is Created after instantiation and a call to the service succeeds).

Visual Studio 16.7.1
.NET Core SDK 3.1.401/.NET Core SDK 2.1.809
Web Service Reference Provider adds Nuget packages System.ServiceModel.Duplex, System.ServiceModel.Http, System.ServiceModelNetTcp and System.ServiceModel.Security 4.4.4. Updating to 4.7.0 makes no difference.

**To Reproduce**
[WcfService1.zip](https://github.com/dotnet/wcf/files/5086863/WcfService1.zip)
See the attached solution, created like this:
1. Start Visual Studio
2. Create a new project, use "WCF Service Application" template, Next, .NET Framework 4.8, Create
3. Add/New project..., use "Console App (.NET Core)" template, Next, Create. The project is created with Target Framework .NET Core 3.1.
5. Build the solution
6. On the console apps Dependencies, click  "Add Connected Service"
7. Under "Other Services" choose "Microsoft WCF Web Service Reference Provider"
8. Click Discover
9. Click Next, Next, Finish
10. Add code to Program.cs, Main() method:
var client = new ServiceReference1.Service1Client();
var result = client.GetDataAsync(1).Result;
Console.WriteLine(result);

11. Set the console app as the start project and run the program, it will fail because of the following exception:
'The communication object, System.ServiceModel.ChannelFactory`1[ServiceReference1.IService1], cannot be used for communication because it is in the Faulted state.'

12. Switch the console app to .NET Core 2.1. The program will run and print the result from the WCF Service, "You entered: 1"

**Expected behavior**
Same behavior regardless of .NET Core framework version set on the console app, the WCF client is able to get data from the WCF service.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/16435892/90446512-cd9b6c80-e0e1-11ea-843b-b2a34994c5dc.PNG)

**Comment by jesse-schein** [comment]
I dont contribute to this project... but I just setup a WCF reference yesterday and actually recorded the steps in a document just like you did. I have no problems using .net 3.1 console app. Are you sure the service is running on your localhost?

**Comment by mconnew** [comment]
I downloaded your test project and it worked exactly as expected. We don't have different implementations for difference .NET Core versions. We use the exact same binary on all supported versions on .NET Core.  
The only way how ChannelFactory could be faulted is if there's an exception on creation, maybe a type load issue with the service contract or something like that. After the channel factory has faulted, you should be able to see an exception that was thrown internally in the diagnostics debug window events. If you can get the exception details (exception type, message and callstack) I might be able to work out what's going on. But it's looking like an environment issue on your development machine as I am unable to repro the problem from your provided solution.

**Comment by HongGit** [comment]
Feel free to re-activate if this is still an issue.
