### ISSUE TITLE
Ignore xml schema validation

### ISSUE THREAD

**Issue by jnyrup** [dotnet/wcf#4343]
**Describe the bug**
I'm combining six WCF services in a single `Reference.cs` with a lot of shared types which gives me 5274 warnings of
```
Warning: There was an error verifying some XML Schemas generated during export:
The complexType '[path-to-type]' has already been declared.
```

Printing all these warnings in Visual Studio seems to slow down updating a service reference severely.
* Running [`dotnet-svcutil`](https://www.nuget.org/packages/dotnet-svcutil/2.0.1) from powershell takes 60s
* Clicking "Update Microsoft WCF Web Service Reference Provider" from VS 16.7.2 takes ~15 minutes, where all the time seems to be spend on printing the 5274 warnings in the "Microsoft WCF Web Service Reference Provider" dialog window.

**To Reproduce**
I can't share the WSDL files, I hope the description above is sufficient, otherwise please let me know.

**Expected behavior**
Generating a service reference from VS should take approximately the same time as generating it from cmd

**Comment by HongGit** [comment]
@imcarolwang could you please see if you could repro this issue?

**Comment by imcarolwang** [comment]
Without the repro wsdl files, it's hard for us to diagnose this issue.

**Comment by HongGit** [comment]
@jnyrup sorry we can't investigate further without the WSDL, close this issue for now.

Feel free to activate when you could isolate the issue and provide a simple repro WSDL.
