### ISSUE TITLE
UriTemplate not supported in .Net Standard/Core

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/wcf#4352]
The [UriTemplate](https://docs.microsoft.com/en-us/dotnet/api/system.uritemplate?view=netframework-4.8) class is not available in .Net Standard or Core.

Was there a technical reason for not porting it from .Net Framework?

**Comment by HongGit** [comment]
This will be grouped together when #1413 is completed.

**Comment by gregsdennis** [comment]
Why is this being closed if it's not done?
