### ISSUE TITLE
XML response parse exception in WCF client asp.net core3.1

### ISSUE THREAD

**Issue by dev-masih** [dotnet/wcf#4358]
Sorry about the long note, I appreciate your time.
I connected a soap wcf web service to my asp.net core 3.1 with `Connected Service` feature and generated `Reference.cs` file, but anytime i tried to call one of wcf web service methods i got xml parse error. I'm not controlling the wcf web service so i can't change the response xml.    
  
the wsdl for the webservice is [here](https://gist.github.com/dev-masih/c82dd78cd0f6a0de65ad4da9d0910bd2)  
when i tried to call the `getSubjectFieldsByName` i get the error `Namespace='https://localhost:8443/ira/ws' is not supported with rpc\literal SOAP. The wrapper element has to be unqualified.`  
In search results some people suggested that with changing `OperationFormatStyle.Rpc` to `OperationFormatStyle.Document` it will get fix. i tried it and i can confirm that i can now send and receive xml. but with calling `getSubjectFieldsByName` method another error is popping out and it's xml parsing error.
here is the complete stack trace:  

      System.ServiceModel.CommunicationException: Error in deserializing body of reply message for operation 'getSubjectFieldsByName'.
     ---> System.InvalidOperationException: There is an error in XML document (1, 254).
     ---> System.Xml.XmlException: End element 'item' from namespace '' expected. Found element 'subjectDnField' from namespace ''. Line 1, position 254.
       at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
       at System.Xml.XmlBaseReader.ReadEndElement()
       at System.Xml.XmlBaseReader.ReadElementContentAsString()
       at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderRaService.Read22_getSubjectFieldsByNameResponse()
       at Microsoft.Xml.Serialization.GeneratedAssembly.ArrayOfObjectSerializer12.Deserialize(XmlSerializationReader reader)
       at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       --- End of inner exception stack trace ---
       at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
       at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
       --- End of inner exception stack trace ---
       at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, XmlSerializer serializer, MessagePartDescription returnPart, MessagePartDescriptionCollection bodyParts, Object[] parameters, Boolean isRequest)
       at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.DeserializeBody(XmlDictionaryReader reader, MessageVersion version, String action, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
       at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeBodyContents(Message message, Object[] parameters, Boolean isRequest)
       at System.ServiceModel.Dispatcher.OperationFormatter.DeserializeReply(Message message, Object[] parameters)
       at System.ServiceModel.Dispatcher.ProxyOperationRuntime.AfterReply(ProxyRpc& rpc)
       at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
       at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
       at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
    --- End of stack trace from previous location where exception was thrown ---
       at RA.Services.CAService.GetProfileDetailAsync(Int64 pkiId, String profileName) in C:\IRIBroadcasting\RA\RA\Services\CAService.cs:line 164

I logged the xml request and responce from wcf and thoes are correct.  
the responce xml is:

    <?xml version="1.0" encoding="utf-16"?>
    <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
      <env:Header />
      <env:Body>
        <ns1:getSubjectFieldsByNameResponse xmlns:ns1="https://localhost:8443/ira/ws">
          <return xmlns:ns2="https://localhost:8443/ira/ws">
            <item>
              <subjectDnField>DN_PKIX_COMMONNAME</subjectDnField>
              <defaultValue></defaultValue>
              <isRequired>true</isRequired>
              <isModifiable>true</isModifiable>
            </item>
            <item>
              <subjectDnField>DN_PKIX_SERIALNUMBER</subjectDnField>
              <defaultValue></defaultValue>
              <isRequired>true</isRequired>
              <isModifiable>true</isModifiable>
            </item>
          </return>
        </ns1:getSubjectFieldsByNameResponse>
      </env:Body>
    </env:Envelope>  
  
The generated class and methods for this function in `Reference.cs` are like these:  
  

    [OperationContractAttribute(Action="", ReplyAction="*")]
    [FaultContractAttribute(typeof(CA2ServiceReference.InvalidEndEntityProfileNameException), Action="", Name="InvalidEndEntityProfileNameException")]
    [FaultContractAttribute(typeof(CA2ServiceReference.RaServiceException), Action="", Name="RaServiceException")]
    [XmlSerializerFormatAttribute(SupportFaults=true)]
    Task<getSubjectFieldsByNameResponse> getSubjectFieldsByNameAsync(getSubjectFieldsByNameRequest request);  

    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    System.Task<getSubjectFieldsByNameResponse> RaService.getSubjectFieldsByNameAsync(getSubjectFieldsByNameRequest request)
    {
        return base.Channel.getSubjectFieldsByNameAsync(request);
    }
        
    public Task<getSubjectFieldsByNameResponse> getSubjectFieldsByNameAsync(string profileName)
    {
        getSubjectFieldsByNameRequest inValue = new getSubjectFieldsByNameRequest();
        inValue.profileName = profileName;
        return ((RaService)(this)).getSubjectFieldsByNameAsync(inValue);
    }

    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [MessageContractAttribute(WrapperName="getSubjectFieldsByNameResponse", WrapperNamespace="https://localhost:8443/ira/ws", IsWrapped=true)]
    public partial class getSubjectFieldsByNameResponse
    {
        [MessageBodyMemberAttribute(Namespace="", Order=0)]
        [XmlArrayAttribute()]
        [XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SubjectItem[] @return;
        
        public getSubjectFieldsByNameResponse()
        {
        }
        
        public getSubjectFieldsByNameResponse(SubjectItem[] @return)
        {
            this.@return = @return;
        }
    }

    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [DebuggerStepThroughAttribute()]
    [XmlTypeAttribute(Namespace="https://localhost:8443/ira/ws")]
    public partial class SubjectItem
    {
        private string subjectDnFieldField;
        private string defaultValueField;
        private string valueField;
        private bool isRequiredField;
        private bool isModifiableField;
        
        /// <remarks/>
        [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string subjectDnField
        {
            get
            {
                return this.subjectDnFieldField;
            }
            set
            {
                this.subjectDnFieldField = value;
            }
        }
        
        /// <remarks/>
        [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string defaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isRequired
        {
            get
            {
                return this.isRequiredField;
            }
            set
            {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isModifiable
        {
            get
            {
                return this.isModifiableField;
            }
            set
            {
                this.isModifiableField = value;
            }
        }
    }
  

I didn't sure what is the problem is here so I tried to include most of what I think is involved in this problem  
I tried to change several attributes and parameters but the best result that I got was an empty output object. Is this a bug about generating a wrong class and xml attribute?

**Comment by HongGit** [comment]
@imcarolwang could you please create a repro project and understand whether this is a regression?

**Comment by dev-masih** [comment]
@HongGit I tried this service with .net framework 4.5 too and get the same result, so i think the server side xml is not correct somehow. I ended up using a ClientMessageInspectors and parse and change the reply XML message manually before deserialization

**Comment by felixsis6** [comment]
I faced that obstacle and worked out the answer



https://stackdev.space/questions/converting-xml-to-html-using-net
