### ISSUE TITLE
Support Latest Net Core framework - 3.*

### ISSUE THREAD

**Issue by tlogik** [dotnet/wcf#4361]
Problem (Mac osX 10.13.6): 
When i execute : `dotnet-svcutil --help`
I get the error that the Net Core runtime version is not supported.
Seems only 2.1.0 is supported right now.

The tool was installed via nuget package:
`dotnet tool install --global dotnet-svcutil`
And should be the latest version

```
dotnet-svcutil --help
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.4 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.13-x64
```

Expectation:
The latest framework of net core should be supported and the tool should work with the latest major net core releases.
Currently version 3.*

**Comment by HongGit** [comment]
@imcarolwang can you please check whether this is still an issue?  If the latest release of dotnet-svcutil.exe fix this issue?

**Comment by imcarolwang** [comment]
The latest release of dotnet-svcutil should be supporting .NETCore 3.1 now. The support of .NET5 is pending release.

**Comment by imcarolwang** [comment]
The latest release of the tool currently supports .NetCore version up to 5.0. 

Install the tool with command:
` dotnet tool install --global dotnet-svcutil --version 2.0.3-preview2.21264.1`
