### ISSUE TITLE
Downloading a file with net core 3.1 web service - Invalid Content type error

### ISSUE THREAD

**Issue by obi111** [dotnet/wcf#4365]
When i try do download a file from a web service i get the following error:

The content type application/dime of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were ...

There was also a similar issue for the web service client in the .Net Framework:
https://stackoverflow.com/questions/8084742/error-consuming-web-service-due-to-content-type-of-application-dime-net

There is a similar problem also in net core 3.1 WCF Service ... any ideas?

**Comment by mconnew** [comment]
I had never heard of DIME before so had to go read up about it. In computing terms, it was an archeological dig. This was a protocol proposal submitted by Microsoft which never made it to RFC status and was long ago withdrawn. Support for the DIME protocol was last available in the Web Services Enhancements (WSE) 2.0 which was released in 2004. Support for it was dropped in WSE 3.0 which was released in 2005 as the industry decided it didn't want to go with DIME and instead preferred MTOM. DIME and MTOM achieve the same thing, avoiding XML encoding binary data and instead attaching it as an external entity to the request or response. The [documentation accompanying the WSE 3.0 release](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-2.0/aa529283(v=msdn.10)) explained how to migrate away from DIME and to using MTOM.  
I'm sorry, we're not going to add support for the DIME protocol as it never made it past the proposal stage and was never supported by WCF in .NET Framework. To be able to make calls to the web service, you're going to need to update the web service to use more modern protocols.
