### ISSUE TITLE
Reference.cs crashing VS2019 16.7.3 (and earlier)

### ISSUE THREAD

**Issue by makingbloke** [dotnet/wcf#4368]
I've added a reference to a webservice to my C# project. This creates a 102000 line Reference.cs file (The webservice itself is a wrapper round a legacy Mainframe app so pretty large). When I open Reference.cs in VS then VS gets progressively slower and slower when text editing another file and eventually locks up and sometimes it restarts. 

Now, I appreciate this is a VS fault. For the moment I've split the Reference.cs into two files (Reference1.cs and Reference2.cs). VS seems fine if I have one or the other open but not both. This works for me, I just have to be careful.

However, what I'd like to know is, is there anyway to automatically split the Reference into smaller files when it is generated. I'm sure this would be useful to other users as handling large files (I use these files as a reference when coding) isn't a lot of fun.

Thanks

**Comment by HongGit** [comment]
Please open a VSFeedback Ticket with Visual Studio following [this instruction](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).
