### ISSUE TITLE
Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.1.401\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

### ISSUE THREAD

**Issue by ivanalie** [dotnet/wcf#4375]
I am not able to add a service reference (WSDL file) to my project in Visual Studio 2019 (.NET Core). Ard installed dotnet-svcutil v1.0.4. It shows the following error. Any clue how to fix this? 

Importing web service metadata ...
Number of service endpoints found: 1
Scaffolding service reference code ...
Error:Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.1.401\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
Done.

Running `dotnet -d svcutil --help` in the project folder gives this:

Telemetry is: Enabled
projectfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\3.1.401\MSBuild.dll
projectfactory: MSBuild project path = C:\Users\ababc1\source\repos\MyProject\MyProject\MyProject.csproj
projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
projecttoolscommandresolver: failed to resolve commandspec from library.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-svcutil does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by imcarolwang** [comment]
Have you tried below?
1. Run WCF Connected Service from VS to add the wsdl. Update your installation of visual studio 2019 to the latest release, this will make sure you're using the latest release of WCF CS tool which might have your encountered problem fixed.
2. You can also use commandline counterpart of the tool which is dotnet-svcutil. You can install it globally with command:
`dotnet tool install -g dotnet-svcutil`
then add service reference via running commandline as below:
`dotnet-svcutil [given-wsdl-path]`

Another note is, the latest release of the tool currently required .NETCore2.1 SDK to be installed on your machine, so please make sure that condition is met when trying out suggestions above.

**Comment by ivanalie** [comment]
Thanks for the quick response @imcarolwang
I added the wsdl by following the instruction [here ](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide), which prompted the error message above. Will reinstall Visual studio 2019 and see if it fixes the issue for now. 

As for the dotnet-svcutil, the installations (dotnet-svcutil 1.0.4 and the dependencies) were installed offline (no internet on my server, can only go for offline installation). Not sure if I missed anything here. 

I have .NET Core 3.1 installed (The sdk version is 3.1.401). Will this version work or it must be .NetCore2.1 ?

**Comment by imcarolwang** [comment]
> I have .NET Core 3.1 installed (The sdk version is 3.1.401). Will this version work or it must be .NetCore2.1 ?

Test of the tool shows that: if your machine has **ONLY .NetCore SDK version 3.1** installed, when using the `2.*.*`  version of dotnet-svcutil tool, the tool would be unusable complaining "_**The framework 'Microsoft.NETCore.App', version '2.1.0' was not found**_".  If in any case you're running into this error install .NetCore2.1 SDK would fix it.
