### ISSUE TITLE
Consider changing calls from GetNonZeroBytes to GetBytes

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/wcf#4377]
The file https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Security/WSTrust.cs contains two calls to `RandomNumberGenerator.GetNonZeroBytes`. Is it intentional that this code use `GetNonZeroBytes` over the preferred API `RandomNumberGenerator.GetBytes`? Using `GetNonZeroBytes` reduces entropy somewhat, so it should only be used when the caller absolutely needs to prevent any zero bytes from being included in the buffer.

**Comment by mconnew** [comment]
This is actually dead code, this method was pulled in by mistake and is only used in NetFx by server side code. So the action here is to remove the the entire ProcessRstAndIssueKey method.

**Comment by HongGit** [comment]
@imcarolwang could try to submit a PR for this issue?

**Comment by mconnew** [comment]
This is now fixed
