### ISSUE TITLE
WsTrustTokenParameters target property should of type "EndpointReference"

### ISSUE THREAD

**Issue by adroit85** [dotnet/wcf#4386]
Currently target property is of type string and is ignored during conversion to SecurityTokenRequirement.

SecurityTokenRequirement expects the type to be of EndpointAddress.

**Comment by mconnew** [comment]
It looks like we should remote the Target property as it's not actually used. I believe the endpoint address you use when creating the channel (either passed to ChannelFactory constructor or passed to CreateChannel) is what's ultimately actually used for the Target field of the WS-Trust request. I'll update with more info once this has been verified.

**Comment by adroit85** [comment]
Hmm but what if target in auth token generation is different than the channel end point where the request is being made? Since auth audience a.k.a "target" is more generic in nature and channel end point is more specific. Is there any way to override target in securitytokenrequirement if it is different than channel endpoint?

Appreciate your help.

**Comment by mconnew** [comment]
I haven't tested it, but I would expect using manual addressing would achieve this. With manual addressing, you configure everything for how you want the SOAP message contents to reflect but then can override the actual Url that the transport sends the message to. I think the steps would be to turn on manual addressing then you would need to set the Via header using either an OperationContextScope or a message inspector to tell it what the request Url that's passed to HttpClient is.
Do you currently do this on .NET Framework? If so, could you provide a code snippet of how you do this? I want to work out how that Target address would be passed around in .NET Framework and then follow it backwards on .NET Core to see if we have the right API's exposed and wired up to achieve the same thing.

**Comment by mconnew** [comment]
We resolved this by removing the property. It wasn't being used by any code and was a remnant of the initial design phase.
