### ISSUE TITLE
How to get string returned from a decorated method's return value with XmlElement attribute

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/wcf#4392]
**Describe the bug**
Using BasicHttpBinding against web services server.
Can't get string return value from a web service when it is marked with `[return: System.Xml.Serialization.XmlElementAttribute]` decoration.

**To Reproduce**
I have an existing legacy webservice method implementation (simplified):

```
[return: System.Xml.Serialization.XmlElementAttribute("ServerInfo")]
string SendConnectionHello() { return "Connection successful!"; }
```
and calling it like

`var result = serviceClient.SendConnectionHello();`

Returned simplified SOAP body looks like
`<soap:Body><ServerInfo>Connection successful!</ServerInfo></soap:Body>`

**Expected behavior**
`result` variable should contain "Connection successful!";

**Actual result**
`result` variable is always null

**Comment by HongGit** [comment]
@imcarolwang  could you try to see if you can setup a repro?

**Comment by MihaMarkic** [comment]
@HongGit Will do, thought it was something obvious

**Comment by MihaMarkic** [comment]
@HongGit @imcarolwang I've created a [sample repro](https://misc.rthand.com/wcf_sample.rar).
It has two parts (ApsManager, .net framework server) and (ApsManagerClient, .net core 3.1 client).
First run the server and then the client. The later should output raw message but no string returned.

**Comment by imcarolwang** [comment]
@MihaMarkic , thanks for providing the sample repro. 

I can get the returned result string when using client proxy code generated from running **"add->Connect Services->Microsoft WCF Web Service Reference Provider"** in the ApsManagerClient project targeting .net core 3.1. Can you give that a try and see if it works for you?

**Comment by MihaMarkic** [comment]
@imcarolwang Doing it with code generator does the trick, thanks. Thought it might be easier to just reuse the interface definition.
