### ISSUE TITLE
Incorrect timeout being used in HttpChannelFactory to open token providers

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#44]
In [`HttpChannelFactory<TChannel>.GetHttpRequestMessageAsync`](https://github.com/dotnet/wcf/blob/7daf79957a65f42b966710f32d5efc0389241a96/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L604), only a `CancellationToken` is passed in. When using manual addressing, a call is made to `CreateAndOpenTokenProviders` which requires a timeout. As the timeout isn't available, the value of 1 minute is used.

```csharp
    if (this.ManualAddressing)
    {
        TimeoutHelper timeoutHelper = new TimeoutHelper(TimeSpan.FromMinutes(1));
        this.Factory.CreateAndOpenTokenProviders(to, via, _channelParameters, timeoutHelper.RemainingTime(),
            out httpClientTokenProvider);
    }
```

Two possible solutions come to mind, I'm sure there are others :smiley: 
1. Pass a `TimeoutHelper` to `GetHttpRequestMessageAsync` as that contains a `CancellationToken` as well as the remaining time. This will work for the call to `CreateAndOpenTokenProviders` as well as the code that follows which requires a `CancellationToken`.
2. Modify `CreateAndOpenTokenProviders` to use a `CancellationToken`. This will require making changes in further called code. This may not be possible depending on how the timeout is currently used as a `CancellationToken` might not be compatible.

**Comment by shmao** [comment]
@mconnew It seemed to me that you had already done this change (see commit ddcd6e4). Can you please confirm?

**Comment by shmao** [comment]
Closing the bug as the bug had been fixed by @mconnew .
