### ISSUE TITLE
Not able to use dotnet-svcutil with .NET Core 3.1 framework on macOS

### ISSUE THREAD

**Issue by dsimanis** [dotnet/wcf#4414]
**Describe the bug**
When running `dotnet-svcutil` on macOS 10.15.7 and .NET Core 3.1.9 it throws an error "It was not possible to find any compatible framework version".

**To Reproduce**
1. Run `dotnet-svcutil`.

```
~ ᐅ dotnet-svcutil
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.9 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64
```

**Expected behavior**
Want to be able to run `dotnet-svcutil` with .NET Core 3.1.

**Comment by osipovas** [comment]
I ran into the same issue today. The documentation here: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x seems to indicate that it should work with later versions.

![image](https://user-images.githubusercontent.com/3442121/99435083-e11ac700-28cc-11eb-9faf-050add847d21.png)

**Comment by bogdanmaxim** [comment]
> I ran into the same issue today. The documentation here: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x seems to indicate that it should work with later versions.
> 
> ![image](https://user-images.githubusercontent.com/3442121/99435083-e11ac700-28cc-11eb-9faf-050add847d21.png)

It doesn't. Here is my output on dotnet core 5:
```
dotnet svcutil

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.100

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.11.0-x64
```

**Comment by osipovas** [comment]
> I ran into the same issue today. The documentation here: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x seems to indicate that it should work with later versions.
> 
> ![image](https://user-images.githubusercontent.com/3442121/99435083-e11ac700-28cc-11eb-9faf-050add847d21.png)

I was able to work around this by downloading a 2.1.x version of the .NET Core SDK. The exact version I downloaded was 2.1.300 from this page: https://dotnet.microsoft.com/download/dotnet-core/2.1

**Comment by dsimanis** [comment]
All of our systems are at 3.1 since long ago. The current release is 5.0. 2.1 capabilities for us are not enough.

**Comment by HongGit** [comment]
@imcarolwang can you please look into this and see if you can repro?

**Comment by dsimanis** [comment]
I have installed version 2.0.2 and it is finally working.

**Comment by imcarolwang** [comment]
@dsimanis  Thank you for your update, glad to hear it's working with the new version.

**Comment by Blackleones** [comment]
Same issue here. I've installed it locally into my project and I receive the following error whenever I try to run dotnet-svcutil.

```
dotnet dotnet-svcutil

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.16 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
```
I've solved it by installing .NET Core 2.x.x.

I want to reopen this issue because the documentation should be edit because the prerequisites aren't _true_ as @osipovas and @bogdanmaxim reported

**Comment by youssef-ali** [comment]
Hi Dears,

Any updates for .Net 5?

**Comment by siraj-mansour-deltatre** [comment]
Seeing this now on .NET 6
