### ISSUE TITLE
TransportWithMessageCredentials with security session over HTTP should use a single connection pool

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#4434]
**Describe the bug**
TransportWithMessageCredentials with HTTP when using EstablishSecuritySession, 2 instances of ChannelFactory are used. One is used to establish the SecureConversation, the second is used to make service calls using the Secure Conversation Token. These two instances need to share an HttpClient instance due to problems with multiple servers behind a load balancer.

**Comment by HongGit** [comment]
This is fixed.
