### ISSUE TITLE
Continuously degrading performance in repeated one-way calls (S.SM 4.8, netcore3.1)

### ISSUE THREAD

**Issue by ssa3512** [dotnet/wcf#4435]
**Describe the bug**
When calling a one way service with reliable sessions repeatedly, the time to make the call continually increases on the client side.

**To Reproduce**
https://github.com/ssa3512/wcf-reliable-sessions/tree/perf-repro
1) Run the wcfasynctestservice project
2) From wcfasynctestclient directory run `dotnet run -f netcoreapp3.1`
Observe the call time gradually increase (starts at ~5ms and after a few minutes it is over 500ms)
3) From wcfasynctestclient directory run `dotnet run -f net472`
Observe the call time is consistently <10ms over any time frame

**Expected behavior**
Subsequent calls to a service are as performant as the first call

**Screenshots**
![image](https://user-images.githubusercontent.com/1991399/99726526-90e66500-2a84-11eb-98ea-676506884a49.png)

**Additional context**
I set up an azure function that is calling a legacy one way WCF service on a timer (every three minutes). This is designed to replace a windows service that is calling the service on a timer. I noticed over the span of 24 hours that the function execution time increased from ~10ms to about 2.5 seconds. Stopping and starting the app service immediately reset the execution time back to the expected 10ms.

Some notes from console app repro tests:
- Using a ClientBase implementation or ChannelFactory does not seem to make a difference
- Async vs sync does not seem to make a difference
- Using separate binding/contract/endpoint address objects does not seem to make a difference
- Reusing the proxy/leaving the channel open seems to alleviate the issue, but that isn't an option in my scenario as the function execution does not allow reuse of the channel from one execution to the next.
- Edit: This occurs with both NetTcpBinding and WSHttpBinding

**Comment by ssa3512** [comment]
@mconnew are you able to take a look at this to at least let me know if there is a possible workaround? Right now this is going to be completely unworkable. I let this run for just a few days and the execution time goes from 10ms to around 40 seconds. Something seems to be going on that is taking increasing amounts of CPU time with each call. Below is the CPU graph of my functions app from app insights - after a few days the CPU usage is just climbing higher and higher.

![image](https://user-images.githubusercontent.com/1991399/100645453-ad975e00-330a-11eb-9853-f44a4ebe2bcd.png)

**Comment by denisky** [comment]
Hi,
we are experiencing a similar issue where the performance is degrading overtime.
The CPU usage keep increasing over time.
![image](https://user-images.githubusercontent.com/38464498/112329124-4de40a80-8c8d-11eb-87b5-0b31099dbdcd.png)

We have a web api in .NET 5.0 hosted in Azure App Service for Containers.
Our docker image is based on alpine.

I see that there is a PR open for this issue, is there a build available that we can test to see if it solves our issue?

**Comment by ssa3512** [comment]
@mconnew any updates on this? Do you think we will see the fix for this in time for .NET 6?

**Comment by mconnew** [comment]
I now have a fix locally which looks promising. I've been running it for about 5 minutes and still getting 1ms response times, and the memory usage isn't going up. I'm going to leave it running for a few hours and then make sure there's no memory leaks.

**Comment by mconnew** [comment]
@ssa3512, I've updated PR 4485 with my new implementation. I ran your repro over it and verified that the request timings remained consistent and that memory didn't grow. I also took memory dumps and validated that we're not holding on to any extra instances of objects I store in an AsyncLocal. If you are able, it would be useful to get extra validation that this causes your problem to go away in your actual scenario..

**Comment by ssa3512** [comment]
@mconnew I pulled your branch down and was able to build the nuget packages from it. I will work on integrating them tomorrow and will report back.

**Comment by ssa3512** [comment]
@mconnew - I am having issues with strong name signing. Do you have instructions on how to build packages that are signed?

Could not load file or assembly 'System.ServiceModel.NetTcp, Version=4.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by mconnew** [comment]
That error message is odd because .NET Core doesn't care about validating strong name signatures. I believe you still need a strong name signed binary to refer from another strong name signed binary and the public key needs to match, but you can skip the private signature and it shouldn't care. You should be able to delay sign the binaries and it will work. I'll do a bit of digging and see if we have any built in capability to generate delay signed binaries.

**Comment by mconnew** [comment]
@ssa3512, when you build at the command line, if you add the -sign parameter, it will delay sign the assembly. So something like this:
```
build  -build -c Release -sign
```
Let me know if that works for you.

**Comment by ssa3512** [comment]
> @ssa3512, when you build at the command line, if you add the -sign parameter, it will delay sign the assembly. So something like this:
> 
> ```
> 
> build  -build -c Release -sign
> 
> ```
> 
> Let me know if that works for you.

This has since been rolled out to our production environments and is working very well. We aren't seeing any of the odd cpu behavior from prior to the update.
