### ISSUE TITLE
net5.0 on non-windows System.ArgumentNullException at System.Threading.Overlapped.Free 

### ISSUE THREAD

**Issue by richamo** [dotnet/wcf#4449]
**Describe the bug**
After upgrading our application to .net5.0 we experience regular exceptions on linux docker containers with the stack below

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'nativeOverlappedPtr')
   at System.Threading.Overlapped.Free(NativeOverlapped* nativeOverlappedPtr)
   at System.Runtime.IOThreadScheduler.ScheduledOverlapped.Cleanup()
   at System.Runtime.IOThreadScheduler.Cleanup()
   at System.Runtime.IOThreadScheduler.Finalize()
Aborted (core dumped)
``` 

**To Reproduce**
.net5.0 application calling an external resource through WCF generated client code wsdl [here](https://s7sps3apissl.scene7.com/scene7/IpsApi-2014-04-03.wsdl)
running in linux docker container 

**Additional context**
We highly suspect something related to #4360 . At first glance the comments and changes seems to match our current issue. Strangely the change made in `IOThreadScheduler.cs` file seems to be the opposite of the original purpose of the PR. 

Any help would be greatly appreciated
Thanks in advance
Morgan

**Comment by BogdanovKirill** [comment]
Same issue with System.ServiceModel.Http 4.8 and System.ServiceModel.Primitives 4.8 packages. Downgrading to 4.7 could avoid this bug.

**Comment by mconnew** [comment]
You're right, I got the logic backwards on the cleanup code in ScheduledOverlapped.Cleanup. Is this causing a process crash or is it an annoyance when debugging/logging?

**Comment by BogdanovKirill** [comment]
@mconnew 
unexpected crash :(

**Comment by waf** [comment]
Any chance this could be released as patch? We're also seeing this on Linux in production, and it's crashing the process.

**Comment by markmario** [comment]
this is something we are seeing in our production environments as well. Getting a release out is critical

**Comment by richamo** [comment]
Downgrading wcf libs to 4.7 (suggested by @BogdanovKirill)  did the trick for us while waiting for this to be released
