### ISSUE TITLE
Duplex netTcp Service Callbacks Not Called

### ISSUE THREAD

**Issue by itsalexjones** [dotnet/wcf#4456]
**Describe the bug**
I am accessing a third party WCF service from dotnet core 3.1 via a service reference generated in Visual Studio. 
This service produces an 'OnChanged' callback to notify that items in the third party system have changed. This works fine in .NET Framework, but I cannot make it work in .NET Core 3.1.
I have tried both using the ClientBase class and the Client class that contains an event handler for the on change event, but the callback is never called.
All methods on the service seem to work fine, it's only the callbacks that seem to fail

**To Reproduce**
I can provide a sample solution privately, but I'm not sure that sharing the WSDL etc publicly would be allowed.
For reference, here is the code (using the ClientBase method) that I've been trying. The class also implements the callback interface specified by the WCF service. This is very similar to code used to access the service successfully in .NET Framework
```
internal void Open()
        {
            var context = new InstanceContext(this);
            client = new StatusFeed2ClientBase(context);
            var identity = new UpnEndpointIdentity("[removed]");
            client.Endpoint.Address = new EndpointAddress(new Uri(
                $"net.tcp://[removed]"), identity);
            client.ChannelFactory.Opened += (sender, args) => Console.WriteLine("Opened");
            client.ChannelFactory.Closed += (sender, args) => Console.WriteLine("Closed");
            client.ChannelFactory.Faulted += (sender, args) => Console.WriteLine("Faulted");
        }
```

**Expected behavior**
As in .NET Framework, the callback is called.

**Comment by HongGit** [comment]
@imcarolwang can you please try to see if you can repro this?

**Comment by mconnew** [comment]
@itsalexjones, are you still having a problem with this? If so, can you send me the repro to my email? My email address is my username at the microsoft.com domain.

**Comment by HongGit** [comment]
Close as no response, feel free to re-activate if this is still an issue.
