### ISSUE TITLE
which version of nuggett package should use for dotnet-svcutil.xmlserializer to upgrade my project to .net core 3.1

### ISSUE THREAD

**Issue by yalin78** [dotnet/wcf#4457]
Hello,

I am currently using dotnet-svcutil.xmlserializer 1.2.0 for my project which is running under .net core 2.1. Currently I am working on upgrading my project to .net core 3.1 and it is breaking with xmlserializer 1.2.0  with following errors.

>proxy.netcore.corexchange -> C:\service-corexchange\api\proxy.netcore.corexchange\bin\Debug\netcoreapp3.1\proxy.netcore.corexchange.dll
1>Load Assembly From C:\Users\npatel\.nuget\packages\system.private.servicemodel\4.8.0\lib\netstandard2.0\System.Private.ServiceModel.dll
1>Successfully Load C:\Users\npatel\.nuget\packages\system.private.servicemodel\4.8.0\lib\netstandard2.0\System.Private.ServiceModel.dll
1>Load Assembly From C:\Users\npatel\.nuget\packages\system.servicemodel.primitives\4.8.0\lib\netcoreapp2.1\System.ServiceModel.Primitives.dll
1>Successfully Load C:\Users\npatel\.nuget\packages\system.servicemodel.primitives\4.8.0\lib\netcoreapp2.1\System.ServiceModel.Primitives.dll
1>Microsoft (R) dotnet-svcutil.xmlserializer tool, Version 1.2.0.
1>[Microsoft (R) Windows (R) Communication Foundation]
1>Copyright (c) Microsoft Corporation.  All rights reserved.
1>
1>Generating XML serializers...
1>EXEC : warning : There were errors loading types in an assembly loaded from 'C:\service-corexchange\api\proxy.netcore.corexchange\obj\Debug\netcoreapp3.1\proxy.netcore.corexchange.dll' 
some types in the assembly could not be loaded and will not be available to the tool.
1>
1>  Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

1>EXEC : warning : An error occurred in the tool.
1>
1>EXEC : warning : Could not load file or assembly 'System.Diagnostics.Tools, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
1>
1>C:\Users\npatel\.nuget\packages\dotnet-svcutil.xmlserializer\1.2.0\build\dotnet-svcutil.xmlserializer.targets(35,5): 
warning MSB3073: The command "dotnet svcutil.xmlserializer obj\Debug\netcoreapp3.1\proxy.netcore.corexchange.dll 
--quiet --out:obj\Debug\netcoreapp3.1\proxy.netcore.corexchange.XmlSerializers 
--smreference:"C:\Users\npatel\.nuget\packages\alliant.netcore.api.authorization\20.332.273.56-beta\lib\netcoreapp3.1\component.netcore.api.authorization.dll;C:\Users\npatel\.nuget\packages\alliant.netcore.api.common.configuration\20.336.161.48-beta\lib\netcoreapp3.1\component.netcore.api.common.configuration.dll;C:\Users\npatel\.nuget\packages\alliant.netcore.api.framework.mock\20.332.95.27-beta\lib\netcoreapp3.1\component.netcore.framework.mock.dll;C:\Users\npatel\.nuget\packages\alliant.netcore.api.logger\20.332.159.32-beta\lib\netcoreapp3.1\component.netcore.logger.dll;C:\Users\npatel\.nuget\packages\alliant.netcore.caching\20.332.159.29-beta\lib\netcoreapp3.1\component.netcore.caching.dll;C:\Users\npatel\.nuget\packages\alliant.netcore.client.adminproxy\20.332.347.17-beta\lib\netcoreapp3.1\component.netcore.client.adminproxy.dll;C:\Users\npatel\.nuget\packages\alliant.netcore.client.contentproxy\20.332.347.25-beta\lib\netcoreapp3.1\component.netcore.client.contentproxy.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.apiclient.adminsetting\20.306.1414.34-beta\lib\netstandard2.0\component.netstd.apiclient.adminsetting.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.apiclient.content\20.306.1424.16-beta\lib\netstandard2.0\component.netstd.apiclient.content.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.apiclient.identityservice\20.307.30.16-beta\lib\netstandard2.0\component.netstd.apiclient.identityservice.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.common.constants\20.329.362.54-beta\lib\netstandard2.0\component.netstd.common.constants.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.common.model\20.260.409.21-beta\lib\netstandard2.0\component.netstd.common.model.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.discoveryclient\20.304.359.45-beta\lib\netstandard2.0\component.netstd.discoveryclient.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.exception\20.331.245.30-beta\lib\netstandard2.0\component.netstd.exception.dll;C:\Users\npatel\.nuget\packages\alliant.netstd.sessiontoken\20.317.295.40-beta\lib\netstandard2.0\component.netstd.sessiontoken.dll;C:\Users\npatel\.nuget\packages\autofixture\4.14.0\lib\netstandard2.0\AutoFixture.dll;C:\Users\npatel\.nuget\packages\autofixture.xunit2\4.14.0\lib\netstandard2.0\AutoFixture.Xunit2.dll;C:\Users\npatel\.nuget\packages\automapper\10.1.1\lib\netstandard2.0\AutoMapper.dll;C:\Users\npatel\.nuget\packages\automapper.extensions.microsoft.dependencyinjection\8.1.0\lib\netstandard2.0\AutoMapper.Extensions.Microsoft.DependencyInjection.dll;C:\Users\npatel\.nuget\packages\castle.core\4.4.0\lib\netstandard1.5\Castle.Core.dll;C:\Users\npatel\.nuget\packages\dotnet-svcutil.xmlserializer\1.2.0\lib\netcoreapp2.1\dotnet-svcutil.xmlserializer.dll;C:\Users\npatel\.nuget\packages\fare\2.1.1\lib\netstandard1.1\Fare.dll;C:\Users\npatel\.nuget\packages\fubarcoder.restsharp.portable.core\4.0.8\lib\netstandard1.3\FubarCoder.RestSharp.Portable.Core.dll;C:\Users\npatel\.nuget\packages\fubarcoder.restsharp.portable.httpclient\4.0.8\lib\netstandard1.1\FubarCoder.RestSharp.Portable.HttpClient.dll;C:\Users\npatel\.nuget\packages\identitymodel\4.5.0\lib\netstandard2.0\IdentityModel.dll;C:\Users\npatel\.nuget\packages\identitymodel.aspnetcore.oauth2introspection\4.0.1\lib\netcoreapp3.0\IdentityModel.AspNetCore.OAuth2Introspection.dll;C:\Users\npatel\.nuget\packages\identityserver4.accesstokenvalidation\3.0.1\lib\netcoreapp3.0\IdentityServer4.AccessTokenValidation.dll;C:\Users\npatel\.nuget\packages\jsonsubtypes\1.2.0\lib\netstandard1.6\JsonSubTypes.dll;C:\Users\npatel\.nuget\packages\microsoft.aspnetcore.authentication.jwtbearer\3.0.0\lib\netcoreapp3.0\Microsoft.AspNetCore.Authentication.JwtBearer.dll;C:\Users\npatel\.nuget\packages\microsoft.aspnetcore.http\2.2.2\lib\netstandard2.0\Microsoft.AspNetCore.Http.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.http.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Abstractions.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.http.features\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Features.dll;C:\Users\npatel\.nuget\packages\microsoft.aspnetcore.jsonpatch\3.1.10\lib\netstandard2.0\Microsoft.AspNetCore.JsonPatch.dll;C:\Users\npatel\.nuget\packages\microsoft.aspnetcore.mvc.newtonsoftjson\3.1.10\lib\netcoreapp3.1\Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.webutilities\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.WebUtilities.dll;C:\Users\npatel\.nuget\packages\microsoft.bcl.asyncinterfaces\5.0.0\lib\netstandard2.1\Microsoft.Bcl.AsyncInterfaces.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.caching.abstractions\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Caching.Abstractions.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.caching.memory\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Caching.Memory.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.configuration\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.configuration.abstractions\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.configuration.binder\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.configuration.fileextensions\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.FileExtensions.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.configuration.json\5.0.0\lib\netstandard2.1\Microsoft.Extensions.Configuration.Json.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.dependencyinjection\5.0.0\lib\netstandard2.1\Microsoft.Extensions.DependencyInjection.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\5.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.fileproviders.abstractions\5.0.0\lib\netstandard2.0\Microsoft.Extensions.FileProviders.Abstractions.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.fileproviders.physical\5.0.0\lib\netstandard2.0\Microsoft.Extensions.FileProviders.Physical.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.filesystemglobbing\5.0.0\lib\netstandard2.0\Microsoft.Extensions.FileSystemGlobbing.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.http\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Http.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.logging\5.0.0\lib\netstandard2.1\Microsoft.Extensions.Logging.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.logging.abstractions\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.objectpool\2.2.0\lib\netstandard2.0\Microsoft.Extensions.ObjectPool.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.options\5.0.0\lib\netstandard2.0\Microsoft.Extensions.Options.dll;C:\Users\npatel\.nuget\packages\microsoft.extensions.primitives\5.0.0\lib\netcoreapp3.0\Microsoft.Extensions.Primitives.dll;C:\Users\npatel\.nuget\packages\microsoft.identitymodel.jsonwebtokens\6.8.0\lib\netstandard2.0\Microsoft.IdentityModel.JsonWebTokens.dll;C:\Users\npatel\.nuget\packages\microsoft.identitymodel.logging\6.8.0\lib\netstandard2.0\Microsoft.IdentityModel.Logging.dll;C:\Users\npatel\.nuget\packages\microsoft.identitymodel.protocols\5.5.0\lib\netstandard2.0\Microsoft.IdentityModel.Protocols.dll;C:\Users\npatel\.nuget\packages\microsoft.identitymodel.protocols.openidconnect\5.5.0\lib\netstandard2.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll;C:\Users\npatel\.nuget\packages\microsoft.identitymodel.tokens\6.8.0\lib\netstandard2.0\Microsoft.IdentityModel.Tokens.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.net.http.headers\2.2.0\lib\netstandard2.0\Microsoft.Net.Http.Headers.dll;C:\Users\npatel\.nuget\packages\microsoft.win32.systemevents\5.0.0\lib\netstandard2.0\Microsoft.Win32.SystemEvents.dll;C:\Users\npatel\.nuget\packages\moq\4.15.2\lib\netstandard2.0\Moq.dll;C:\Users\npatel\.nuget\packages\newtonsoft.json\12.0.3\lib\netstandard2.0\Newtonsoft.Json.dll;C:\Users\npatel\.nuget\packages\newtonsoft.json.bson\1.0.2\lib\netstandard2.0\Newtonsoft.Json.Bson.dll;C:\Users\npatel\.nuget\packages\nlog\4.7.2\lib\netstandard2.0\NLog.dll;C:\Users\npatel\.nuget\packages\nlog.extensions.logging\1.6.4\lib\netcoreapp3.0\NLog.Extensions.Logging.dll;C:\Users\npatel\.nuget\packages\nlog.web.aspnetcore\4.9.3\lib\netcoreapp3.0\NLog.Web.AspNetCore.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.concurrent\4.0.12\lib\netstandard1.3\System.Collections.Concurrent.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.nongeneric\4.3.0\lib\netstandard1.3\System.Collections.NonGeneric.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.specialized\4.3.0\lib\netstandard1.3\System.Collections.Specialized.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel\4.3.0\lib\netstandard1.3\System.ComponentModel.dll;C:\Users\npatel\.nuget\packages\system.componentmodel.annotations\4.3.0\lib\netstandard1.4\System.ComponentModel.Annotations.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.primitives\4.3.0\lib\netstandard1.0\System.ComponentModel.Primitives.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.typeconverter\4.3.0\lib\netstandard1.5\System.ComponentModel.TypeConverter.dll;C:\Users\npatel\.nuget\packages\system.configuration.configurationmanager\5.0.0\lib\netstandard2.0\System.Configuration.ConfigurationManager.dll;C:\Users\npatel\.nuget\packages\system.diagnostics.diagnosticsource\5.0.0\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll;C:\Users\npatel\.nuget\packages\system.drawing.common\5.0.0\lib\netcoreapp3.0\System.Drawing.Common.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.dynamic.runtime\4.3.0\lib\netstandard1.3\System.Dynamic.Runtime.dll;C:\Users\npatel\.nuget\packages\system.identitymodel.tokens.jwt\6.8.0\lib\netstandard2.0\System.IdentityModel.Tokens.Jwt.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll;C:\Users\npatel\.nuget\packages\system.linq\4.3.0\lib\netstandard1.6\System.Linq.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq.expressions\4.3.0\lib\netstandard1.6\System.Linq.Expressions.dll;C:\Users\npatel\.nuget\packages\system.net.webheadercollection\4.0.1\lib\netstandard1.3\System.Net.WebHeaderCollection.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.objectmodel\4.3.0\lib\netstandard1.3\System.ObjectModel.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.private.datacontractserialization\4.1.1\lib\netstandard1.3\System.Private.DataContractSerialization.dll;C:\Users\npatel\.nuget\packages\system.private.servicemodel\4.8.0\lib\netstandard2.0\System.Private.ServiceModel.dll;C:\Users\npatel\.nuget\packages\system.reflection.dispatchproxy\4.7.1\lib\netcoreapp2.0\System.Reflection.DispatchProxy.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.numerics\4.0.1\lib\netstandard1.3\System.Runtime.Numerics.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.serialization.primitives\4.1.1\lib\netstandard1.3\System.Runtime.Serialization.Primitives.dll;C:\Users\npatel\.nuget\packages\system.runtime.serialization.xml\4.1.1\lib\netstandard1.3\System.Runtime.Serialization.Xml.dll;C:\Users\npatel\.nuget\packages\system.security.accesscontrol\5.0.0\lib\netstandard2.0\System.Security.AccessControl.dll;C:\Users\npatel\.nuget\packages\system.security.cryptography.cng\4.7.0\lib\netcoreapp3.0\System.Security.Cryptography.Cng.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.cryptography.openssl\4.0.0\lib\netstandard1.6\System.Security.Cryptography.OpenSsl.dll;C:\Users\npatel\.nuget\packages\system.security.cryptography.pkcs\4.7.0\lib\netcoreapp3.0\System.Security.Cryptography.Pkcs.dll;C:\Users\npatel\.nuget\packages\system.security.cryptography.primitives\4.0.0\lib\netstandard1.3\System.Security.Cryptography.Primitives.dll;C:\Users\npatel\.nuget\packages\system.security.cryptography.protecteddata\5.0.0\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll;C:\Users\npatel\.nuget\packages\system.security.cryptography.xml\4.7.0\lib\netstandard2.0\System.Security.Cryptography.Xml.dll;C:\Users\npatel\.nuget\packages\system.security.permissions\5.0.0\lib\netcoreapp3.0\System.Security.Permissions.dll;C:\Users\npatel\.nuget\packages\system.security.principal.windows\5.0.0\lib\netstandard2.0\System.Security.Principal.Windows.dll;C:\Users\npatel\.nuget\packages\system.servicemodel.duplex\4.8.0\lib\netstandard2.0\System.ServiceModel.Duplex.dll;C:\Users\npatel\.nuget\packages\system.servicemodel.http\4.8.0\lib\netstandard2.0\System.ServiceModel.Http.dll;C:\Users\npatel\.nuget\packages\system.servicemodel.nettcp\4.8.0\lib\netstandard2.0\System.ServiceModel.NetTcp.dll;C:\Users\npatel\.nuget\packages\system.servicemodel.primitives\4.8.0\lib\netcoreapp2.1\System.ServiceModel.Primitives.dll;C:\Users\npatel\.nuget\packages\system.servicemodel.primitives\4.8.0\lib\netcoreapp2.1\System.ServiceModel.dll;C:\Users\npatel\.nuget\packages\system.servicemodel.security\4.8.0\lib\netstandard2.0\System.ServiceModel.Security.dll;C:\Users\npatel\.nuget\packages\system.text.encodings.web\5.0.0\lib\netcoreapp3.0\System.Text.Encodings.Web.dll;C:\Users\npatel\.nuget\packages\system.text.json\5.0.0\lib\netcoreapp3.0\System.Text.Json.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.regularexpressions\4.3.0\lib\netstandard1.6\System.Text.RegularExpressions.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll;C:\Users\npatel\.nuget\packages\system.windows.extensions\5.0.0\lib\netcoreapp3.0\System.Windows.Extensions.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.readerwriter\4.3.0\lib\netstandard1.3\System.Xml.ReaderWriter.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.xmldocument\4.3.0\lib\netstandard1.3\System.Xml.XmlDocument.dll;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.xmlserializer\4.0.11\lib\netstandard1.3\System.Xml.XmlSerializer.dll;C:\Users\npatel\.nuget\packages\xunit.abstractions\2.0.1\lib\netstandard1.0\xunit.abstractions.dll;C:\Users\npatel\.nuget\packages\xunit.extensibility.core\2.2.0\lib\netstandard1.1\xunit.core.dll"" exited with code 9.
1>C:\Users\npatel\.nuget\packages\dotnet-svcutil.xmlserializer\1.2.0\build\dotnet-svcutil.xmlserializer.targets(35,5): warning MSB4181: The "Exec" task returned false but did not log an error.
1>C:\Users\npatel\.nuget\packages\dotnet-svcutil.xmlserializer\1.2.0\build\dotnet-svcutil.xmlserializer.targets(36,5): warning : Warning : Fail to generate the serializer for proxy.netcore.corexchange.dll.
1>Done building project "proxy.netcore.corexchange.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by yalin78** [comment]
Can someone please help with this?

**Comment by yalin78** [comment]
Can someone please help with this?

**Comment by yalin78** [comment]
Any updates on this?

**Comment by ferrarimartin** [comment]
I've tried this as a workaround, and it worked (for me) on my Windows machine:
- Go to C:\Users\<your user>\.nuget\packages\dotnet-svcutil.xmlserializer\1.2.0\lib\netcoreapp2.1
- Edit dotnet-svcutil.xmlserializer.runtimeconfig.json
- Change tfm and version to match the .net core version your building for.
- Build.

Got the workaround from this similar issue: https://github.com/dotnet/runtime/issues/1390

**Comment by HongGit** [comment]
@imcarolwang can you please see if you could repro this?

**Comment by HongGit** [comment]
Closing out this issue as net core 3.1 is already out of support, see [doc](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).
