### ISSUE TITLE
Unit testing a WCF service interface that uses TransactionFlowAttribute

### ISSUE THREAD

**Issue by Astronought** [dotnet/wcf#4463]
Hi,

I have a unit test project that targets .Net Core 3.1, I'm using the MOQ framework to create mock instances of remote services, one such service happens to be a WCF service.

The issue I'm having is that several of the methods in the WCF service's interface are decorated with transaction flow attributes, when MOQ attempts to instantiate a mock object using this interface I get an exception because the project is unable to find the System.ServiceModel.TransactionFlowAttribute class inside the System.ServiceModel.dll.

Is this a known issue, if so are there any work arounds or plans to support this class in .Net Core?

Thanks.

**Comment by HongGit** [comment]
WCF can not support TransactionFlowAttribute sue to System.Transactions on .NET Core lacking distributed support at the moment.
