### ISSUE TITLE
Create package for System.Web.Services.Description

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#4464]
Both dotnet-svcutil and CoreWCF (needed to add WSDL support) have a dependency on the types in the System.Web.Services.Description namespace. The types in this namespace are object model classes and serializers for WSDL schema. Rather than have both projects maintain their own internal clone of this implementation (which dotnet-svcutil does today), we should have a public package containing these interchange types.

**Comment by wouterroos** [comment]
We also have a use-case for this, would be great if this could be done.

**Comment by mconnew** [comment]
@wouterroos, I have the start of this available [here](https://github.com/mconnew/wcf/tree/SysWebServices). Can you check that the api's you need are available there?

**Comment by wouterroos** [comment]
@mconnew Thanks for the update. I'll notify our team and will make sure we have a look. Our use-case requires that we are able to generate (partial) WSDL's. We're mostly interested in the part that describes service/operation contracts since that is (as far as I know) the only truly technology agnostic way to describe a service contract. Our product uses ServiceContracts without necessarily relying on WCF as a servicehost/proxy. My ideal API would be something like .GenerateWDSL(ServiceDescription), but I'm willing to write some more code to achieve this goal 😉. Based on this description, Is this something that you think could be done using this library?

**Comment by mconnew** [comment]
You may have some problems still. The operation contracts are largely generated by creating the XML Schema using the serialization classes and those api's are still not available. I'm going to need to get those added, but unfortunately the release timeline for the runtime repo means it's likely not going to happen until .NET 7. This work is in support of CoreWCF as well as dotnet-svcutil (which carries a copy of this internally), so I'm going to need to get creative. As I'm going to try and make it a separate package in CoreWCF, it's likely whatever solution I come up with to work around the missing api's will be consumable without pulling in too much unnecessary components.

**Comment by wouterroos** [comment]
@mconnew Thanks, I'll have a detailed look at both your work and our requirements soon as I'm a little fuzzy on the details of both and will get back to you. If we can assist in any way on making this stuff happen please don't hesitate to ask!

**Comment by wouterroos** [comment]
@mconnew Additional question: what functionality will you support in CoreWcf exactly for which this is needed? Will we be able to expose a metadata endpoint or something?

**Comment by mconnew** [comment]
The intention is to expose the WSDL in CoreWCF. I don't know if the Metadata endpoint needs this as that's a separate SOAP contract whereas a WSDL is just a schema file that you download. As most people use WSDL and not Metadata, that's the first part I'm implementing. I'd like to eventually support IWsdlImportExtension in this repo and IWsdlExportExtension (needed for the WSDL support) in CoreWCF. This will make it easier for dotnet-svcutil to keep in sync with feature updates.

**Comment by mconnew** [comment]
To actually answer your question, I intend to support fetching the Wsdl, SingleWsdl, and the IMetadataExchange SOAP endpoint for fetching the metadata, as well as the help page that WCF generates by default (apparently some people depend on it being there)

**Comment by wouterroos** [comment]
@mconnew Thanks!

**Comment by mtraudt-qontigo** [comment]
@mconnew Can  you give an update on the timeline for supporting IWsdlImportExtension in CoreWCF? Also IServiceContractGenerationExtension and IOperationContractGenerationExtension. We have a service that uses these features that we would like to port to CoreWCF.
