### ISSUE TITLE
Disable running dotnet-svcutil tests at the command-line by default

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#4472]
When trying to run ServiceModel tests by using `build -test -testscope all`, the dotnet-svcutil tests get executed too. These tests take a long time to execute. The dotnet-svcutil-lib tests were running for more than 30 minutes before I stopped the test run. This is making it really difficult to iterate on ServiceModel code.

**Comment by HongGit** [comment]
@imcarolwang can you please take a look?

**Comment by imcarolwang** [comment]
Way to run ServiceModel test without executing dotnet-svcutil tests:
1. Specify -projects parameter in commandline:
_build -configuration Release **-projects System.ServiceModel.sln** -test -testscope all_

2. Update dotnet-svcutil-lib test project name to anything NOT end with .Tests

@mconnew do you think any of the work arounds above is an acceptable solution?
