### ISSUE TITLE
DisposeAsync support

### ISSUE THREAD

**Issue by jumpingjackson** [dotnet/wcf#4484]
**Describe the bug**
jumpingjackson @jumpingjackson Dec 04 2020 14:55
Does Dispose() on the new WCF client clean up properly? The old client you had to this https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/use-close-abort-release-wcf-client-resources

Matt Connew @mconnew Dec 06 2020 12:32
We've kept the same behavior as desktop. This is definitely something worth visiting. I don't think we can change the behavior on Dispose without potential compat issues but we could maybe add support for the new DisposeAsync and have cleaner behavior on that. Feel free to open an issue.

**Comment by mconnew** [comment]
Fixed in #4865

**Comment by petersladek** [comment]
I am using System.ServiceModel.Primitives 4.10.0 (WCF v3.4.0) on .NET 6 and I am confused that I see CloseAsync() in ClientBase<T> available, but corresponding OpenAsync() is missing.. According to [release notes](https://github.com/dotnet/wcf/releases/tag/v3.4.0-rtm) this should already be in 4.10.0 nuget package. But according to this [v.3.4.0 to v6.0.0 tag comparison](https://github.com/dotnet/wcf/compare/v6.0.0...v3.4.0-rtm?diff=split#diff-eaaf9db1364cf04ddffffc3ac3a6afb891fe70aa1940fb25b33a1155cf3e6fc6) both OpenAsync() and CloseAsync() were added in WCF v6.0 and thus neither should be available in 4.10.0 nuget package. I am sure I am missing something, or don't understand the versioning. Could you please explain?
