### ISSUE TITLE
MessageEncoding missing in WSFederationHttpBinding

### ISSUE THREAD

**Issue by Erikvdv** [dotnet/wcf#4487]
I am using System.ServieModel.Federation 4.8.0
It is not possible to define MessageEncoding in WSFederationHttpBinding
I am looking to use WSMessageEncoding.Mtom in a dotnet 5 project

**Comment by mconnew** [comment]
MTOM isn't supported yet. It's currently planned to be added with the release that aligns with .NET 6 (although we won't require .NET 6 to use it).

**Comment by sboboryk** [comment]
@mconnew  any idea of ETA for MTOM support? Thank you.

**Comment by HongGit** [comment]
@imcarolwang  could you please add a test scenario for this?

**Comment by mconnew** [comment]
To fill in a bit of missing context, WSFederationHttpBinding derives from WSHttpBinding which now has the MessageEncoding property and supports MTOM. The only thing missing is specific end to end tests of WSFederationHttpBinding using MTOM.
