### ISSUE TITLE
Error:An unknown error occurred while invoking the service metadata component. - Net core 3.1

### ISSUE THREAD

**Issue by saisworld** [dotnet/wcf#4494]
**Describe the bug**
I'm getting error "_Error:An unknown error occurred while invoking the service metadata component_." when I try to add a Connected Service to a .Net core 3.1 class library project

My Visual studio version details - 
Microsoft Visual Studio Professional 2019
Version 16.7.6

I tried using the dotnet-svcutil via terminal as well and it failed with error - _"Error: Method 'Log' in type 'Microsoft.Tools.ServiceModel.Svcutil.DebugLogger' from assembly 'dotnet-svcutil-lib, Version=2.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.  "_

**Expected behavior**
Should be able to add Connected Service successfully

**Screenshots**
![error-vs](https://user-images.githubusercontent.com/5602414/104434178-d609ad80-5582-11eb-957a-014953f1f66b.png)

**Comment by imcarolwang** [comment]
We couldn't reproduce the error with the given information. 

Could you please try the scenario on  the latest VS release which could be downloaded from https://visualstudio.microsoft.com/vs/preview/ ? For command line tool release you can find the install command from [here](https://www.nuget.org/packages/dotnet-svcutil/2.0.3-preview2.21264.1).

**Comment by saisworld** [comment]
I m using the latest version of VS. VS 2019.

**Comment by imcarolwang** [comment]
> I m using the latest version of VS. VS 2019.

To make sure, are you trying on VS Version 16.11.0 Preview 3.0 ? It's only released quite recently. If you can still reproduce, is it possible for you to provide the wsdl file？

**Comment by HongGit** [comment]
Closing due to no response.

Feel free to re-activate if the issue still persists after trying @imcarolwang's suggestion.
