### ISSUE TITLE
Unsure How to Proceed With Error: The method or operation is not implemented.

### ISSUE THREAD

**Issue by MrTovson** [dotnet/wcf#4498]
I've spent a few days researching why I can't work with a vendor's service in .NET Core 3.1.  The service works fine in .NET 4.5.2.

In the end, only 1 of the 2 bindings are generated: WS binding.  In 4.5.2 we are successfully using Basic, which is not generated.

I suppose my question is two-fold:
1. What isn't supported by this relatively simple SOAP service
2. Are there any known workarounds?

I have tried many, have build endpoint+binding dynamically as many ways as I can and am stuck.  

Detail:

PM> dotnet-svcutil https://servicesv4.qa.provexchnet.com/DSIRating.svc -d C:\Temp
Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
[Microsoft.Tools.ServiceModel.Svcutil, Version 2.0.2]
...
Attempting to download metadata from 'https://servicesv4.qa.provexchnet.com/DSIRating.svc' using WS-Metadata Exchange and HttpGet.
Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='https://www.provexchnet.com/dsi']/wsdl:binding[@name='BasicHttpBinding_IDSIRating']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='https://www.provexchnet.com/dsi']/wsdl:service[@name='DSIRating']/wsdl:port[@name='BasicHttpBinding_IDSIRating']
Generating files...
C:\Temp\Reference.cs

**Comment by MrTovson** [comment]
'No connection could be made because the target machine actively refused it.'

Quite tired of seeing this message, regardless of anything I do.  I'm going back to .NET Framework until this service is supported, the service is upgraded by the vendor, or someone who knows what they're doing can help.

**Comment by imcarolwang** [comment]
We tried to repro the issue with the given service https://servicesv4.qa.provexchnet.com/DSIRating.svc  mentioned in issue, we got accessed denied as we don't have a valid certificate.  @MrTovson could you please provide a simplified repro project for us to investigate this further?

**Comment by MrTovson** [comment]
You've got to be kidding.  There is nothing simpler than this.

Sent via the Samsung Galaxy S21 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MrTovson** [comment]
You have the single command needed to reproduce the issue.  There is no cert issue.

**Comment by mconnew** [comment]
@MrTovson, I have been able to download the WSDL and have emailed it to @imcarolwang offline. At the moment dotnet-svcutil is a little behind on the set of features it recognizes as supported in .NET Core. I had a quick look at the WSDL and I can see you are using WSHttpBinding. This is one of the features that dotnet-svcutil doesn't know about yet which is why you are getting the error. From looking at the WSDL I can't tell if you are using security mode Message or MessageWithTransportCredentials, although I suspect it's the latter as https is required in the WSDL. If this is the case, then this is supported in .NET Core. The easiest way to get it working is to copy your contract interface from .NET Framework and create your binding in code yourself. If you need help, please provide your existing binding config from .NET Framework and I can provide the equivalent code to create the binding in Core.

**Comment by sefi-pchen** [comment]
@mconnew Hi, we are having the same issue. We are using 
`<security mode="TransportWithMessageCredential">`
`  <transport clientCredentialType="None" />`
`  <message clientCredentialType="UserName" />`
`</security> `
in the `<WSHttpBinding>` section. 

Is there any documentation on creating the binding in code that you could point me to please? Thanks!

**Comment by mconnew** [comment]
@sefi-pchen, the code api layout is very similar if not identical to the config in many cases. Thankfully the WSHttpBinding is one of those cases. So you would do this:
```
            binding = new WSHttpBinding(SecurityMode.TransportWithMessageCredential);
            binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
            binding.Security.Message.ClientCredentialType = MessageCredentialType.UserName;
```
I believe the second line isn't strictly needed as TransportWithMessageCredentials implies the client isn't authenticating with client transport credentials but there's no harm in being overly verbose here.

**Comment by HongGit** [comment]
Close this out as this has already been fixed.  Please open a new issue if there are more issues related with TransportWithMessageCredential.
