### ISSUE TITLE
Incorrect timeout specified in TimeoutException message for Http

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#45]
In [`HttpChannelUtilities.CreateRequestTimedOutMessage`](https://github.com/dotnet/wcf/blob/7daf79957a65f42b966710f32d5efc0389241a96/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs#L1656), the timeout value that was used when a request timed out is not available so the value 1000ms is used instead.

**Comment by shmao** [comment]
The method was removed by commit 30eccdae259bfe710b788bb310b26106292aa965.
