### ISSUE TITLE
Issue: When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy

### ISSUE THREAD

**Issue by noelmathew** [dotnet/wcf#4515]
I generated a wcf client in my .net core project. I am targeting 2.1 because that's what my servers have installed. I am also running on windows machines. 

My code looks something like this. 
```
var binding = new BasicHttpsBinding(BasicHttpsSecurityMode.Transport);
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
binding.ProxyAddress = new Uri("proxy.xyz.com:83");

EndpointAddress endpoint = new EndpointAddress("https://service-endpoint.com");
StaffingPortClient client = new StaffingPortClient(binding, endpoint);
```
At first it looked like it was not respecting the proxy that I specified here. From my wireshark logs, it looks like it is going to some other default proxy. 
```
binding.BypassProxyOnLocal = false;
binding.UseDefaultWebProxy = false;
```
and now I get the error in the title. 

> When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy

 I see some mention of this error. A brief mention here: https://github.com/dotnet/wcf/issues/1592#issuecomment-322233954
 But I couldn't find the right solution for this. Basically, what needs to be done to allow my wcf client to go through the proxy I am specifying?

**Comment by HongGit** [comment]
@noelmathew can you please give the newest packages a try and see if the issue you are referring is fixed?

**Comment by noelmathew** [comment]
@HongGit : That worked. I am on System.ServiceModel.Http 4.4.4 and it works. Sorry about the confusion.
