### ISSUE TITLE
dotnet-svcutil  - Process is terminating due to StackOverflowException

### ISSUE THREAD

**Issue by kurilovigor** [dotnet/wcf#4519]
**Describe the bug**
Hello! A am using dotnet-svcutil (version 2.0.2). When I run command 
`dotnet-svcutil --help`
I get error: **Process is terminating due to StackOverflowException**
The same error I get, when trying to create connected service in ASP.NET Core 5.0 application.
[svcutil-error-1](https://user-images.githubusercontent.com/6756724/106466662-af1d0800-64ac-11eb-82c7-6726e3f6692c.png)
A have seen older threads, recomending to check off types reusing. This check is not allowed in 5.0. If I downgrade to Core 3.1, then I get the same error or "unexpecded error" (some times)

**To Reproduce**
1. 
`dotnet-svcutil --help`

2.
Create ASP.NET Core 5.0 Web Api project
Create connected service from VisualStudio using provided WSDL:
[DailyInfo.zip](https://github.com/dotnet/wcf/files/5904233/DailyInfo.zip)

**Comment by imcarolwang** [comment]
I tried the repro steps described in issue:
1. I can run `dotnet-svcutil --help` just fine.
2. The issue for running WCF Connected Service from VisualStudio in .NETCore 5.0 project is currently under investigation. But downgrade to .NETCore 3.1, I can generate the ServiceReference with the given WSDL without problem.

**Comment by kurilovigor** [comment]
Found out, that dotnet-svcutil problem relays on current installed instance of VisualStudio 2019, and is not reproduced on clean installation. Due to complexity of locating error closing the issue
