### ISSUE TITLE
System.ServiceModel.Primitives Not Loadable

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/wcf#4523]
When attempting to run a Xamarin.UWP application on Windows v19941.746 with VS 16.9.0 Preview 3.0, I am encountering the following error:

System.IO.FileLoadException HResult=0x80131040 Message=Could not load file or assembly ‘System.ServiceModel.Primitives, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’. The located assembly’s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

A similar error occurs with an Android simulator or phone:

System.TypeLoadException: ‘Could not load type of field ‘Sentry.ISoapServices:SoapClient’ (0) due to: Could not load file or assembly ‘System.ServiceModel.Primitives, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’ or one of its dependencies.’

The error is not present in debugging an iPhone. The problem was present in v4.8.0.0.

Currently the GAC references the v4.0.0.0 NuGet’s. With the upgrade, the solution and project config files reference the new version, but not the GAC.

Based on the comments in the original problem report, I downgraded to v4.3.0.0 which allows the UWP app to run (not sure why), but not the Androids which reference v4.1.1.0. Downgrading to 4.0.0.0 is not Net.Standard 2.0 compatible. Upgrading to v4.6.0.0 which is NS2.0 compatible results in the current issues. Upgrading to v4.7.0.0 has the same results.

The developers community problem has log files and screen shots of the various builds attached.

**Comment by alaskanrogue** [comment]
Here is the issue in depth and various solutions: [https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts](https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts).

**Comment by alaskanrogue** [comment]
It appears that issue is related to Microsoft.Common.CurrentVersion.targets Line 2181 and the assemblies being resolved against. VS v16.9.0 Preview 3.0 is in use.

**Comment by alaskanrogue** [comment]
As an experiment, removing all "ServiceModel" NuGet's across all five solution projects, cleaning and re-building, I responded to the errors reported by only re-installing the NuGet's necessary to the PCL project. Because of the earlier discovery, I used the v4.1.1.0 versions of the NuGet's. The error is not present in either UWP or Android now. 

The question in my mind is if the GAC and the assemblies list above are being updated during the NuGet's installations?  

I plan to continue the experiment by upgrading the NuGet's by version to see the results.

FYI, VS v16.9.0 Preview 4.0 is now in use.

**Comment by HongGit** [comment]
@alaskanrogue this does not seem to be a problem with WCF Core libraries even though you are using System.ServiceModel.Primitives.  I would suggest you to log an issue with Visual Studio Developer Community https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019.
