### ISSUE TITLE
HttpChannelFactory different behavior under .net Framework and .net Core

### ISSUE THREAD

**Issue by Rerago** [dotnet/wcf#4547]
**Describe the bug**
i have a WCF client in a library (TargetFrameworks: netstandard2.0;netstandard2.1;net5.0). This library is used by different application. Now it turns out that the client does not work under .net 4.7.2. I could break it down to the fact that the DelegatingHandler is not called. To be more precise it looks like the func is not executed because it never arrives at the constructor of the DelegatingHandler.

But if I call the client from a .net Core 2.0, .net Core 3.1 or .net 5 application everything works as expected. So I guess that this code part is handled differently under .net Framework than under .net Core.

**To Reproduce**

And here is some sample code. It is very generic. But exactly on these lines you can break down the problem.

```
public class HttpMessageHandlerBehavior : IEndpointBehavior
{
    public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
    {
        bindingParameters.Add(new Func<HttpClientHandler, HttpMessageHandler>(x => new TestHandler(x)));
    }

    public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime) { }

    public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher) { }

    public void Validate(ServiceEndpoint endpoint) { }
}

public class TestHandler : DelegatingHandler
{
	public TestHandler(HttpMessageHandler innerHandler) : base(innerHandler)
	{ }

	protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		System.Diagnostics.Debug.WriteLine("Do Stuff here!");
	}
}
```

**Expected behavior**
I hoped that the code would work the same under all frameworks.

**Comment by Rerago** [comment]
I have created a simple project to reproduce the problem:

[IEndpointBehaviorTest.zip](https://github.com/dotnet/wcf/files/6054678/IEndpointBehaviorTest.zip)

- _WcfClient_ => Is a library (TargetFrameworks - netstandard2.0;netstandard2.1;net5.0) that embeds the WCF service
- _IEndpointBehaviorTest_ => .net 5 console application that calls WCF service via WcfClient
- _IEndpointBehaviorTest.NF_ => .net Framework 4.7.2 console application that calls WCF service via WcfClient

If you call "_IEndpointBehaviorTest_" you get an error message because the DelegatingHandler is called and it does not return "_SendAsync_".

If you now call "_IEndpointBehaviorTest.NF_" everything runs without problems because the DelegatingHandler is not called.

I would expect the DelegatingHandler to be called in both cases.
(Of course, the latest versions of the packages are used).

**Comment by Rerago** [comment]
Mh ok I think slowly I get behind there. I had a look at the call list. The .net Framework client accesses the following HttpChannelFactory:

https://referencesource.microsoft.com/#system.servicemodel/system/servicemodel/Channels/HttpChannelFactory.cs

where "Func<HttpClientHandler, HttpMessageHandler>" is not supported like here:

https://github.com/dotnet/wcf/blob/main/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

So far ok if that's how it's meant to be, although I have to say it's a bit confusing if you haven't dealt with the topic in depth.

The question is how to proceed now? Can I get the .net framework client to access the same classes as the .net core client (which would probably not be supported)? And if not, how do I get the same functionality (injecting a delegating handler) in the .net framework?

**Comment by mconnew** [comment]
The mechanism of providing a Func to modify the behavior of the HttpClientHandler was originally created because the HttpClientHandler is encapsulated by WCF and on Core there aren't any public methods to modify it's behavior. On .NET Framework, HttpClient isn't used, instead we use HttpWebRequest. On .NET Framework you can modify quite a bit of behavior of HttpWebRequest using ServicePointManager, but as this isn't available on Core, I created the Func binding parameter mechanism.  
Can you give a high level overview of what it is you are doing in your handler? There might be an alternative way to do it on .NET Framework. I can't port the Func mechanism to .NET Framework as it doesn't use HttpClientHandler. Core was a significant rewrite to use HttpClient instead.

**Comment by Rerago** [comment]
Hi, first of all thank you for the answer. Now the whole thing makes sense to me.

In very simple terms I do the following:

- execute base.SendAsync
- evaluate the result (check if a certain header is present)
- if necessary send a GET to the same URL (to get cookie)
- resend initial request

Or a bit more precise:

We want to access a WCF service that is located behind an APM F5 (to which we have no access regarding configuration). This requires to support cookies that it sets itself (i.e. I can't set them initially).

If we send only a POST request (without cookie), it returns an HTML page that requires user interaction, which we can't provide. But if we send a GET before (without cookie) we get a valid cookie. With this cookie POST requests will also work.

As a solution i wrote a DelegatingHandler which sends the initial request and then checks the header in the result. If the APM F5 answers and not the webservice a GET is sent to the same URL to get the cookie. If we got the cookie we send the initial request again (now with cookies).
(I leave the cookie handling here completely to WCF).

Since the cookie lasts for a certain time, the WCF client now works normally until the cookie expires again. This causes only a minimal overhead when determining the cookie again.

**Comment by mconnew** [comment]
The good news is that the way you are trying to solve this is the hard way. There's an easier way which will work on all platforms. You can do code similar to this:
```c#
var factory = new ChannelFactory<IService>(
                     new BasicHttpBinding()
                     {
                         AllowCookies = true
                     },
                     new EndpointAddress(serviceAddress));
IService serviceProxy = factory.CreateChannel();
IHttpCookieContainerManager cookieManager = ((IChannel)serviceProxy).GetProperty<IHttpCookieContainerManager>();
```
The `IHttpCookieContainerManager` has a property `CookieContainer` of type `System.Net.CookieContainer` which allows you to add cookies to the container. This is the same CookieContainer that WCF passes to either HttpWebRequest of HttpClientHandler, depending on the platform. So you can make any initial request you like using an HttpClient instance of your own, extract the cookie and add it to this CookieContainer and WCF will then use that cookie.

**Comment by Rerago** [comment]
Well the way is not really hard^^. Currently I need to add a line of code to the client (which adds the Behavior that adds the DelegatingHandler). I have the DelegatingHandler either way since I also use it for our REST clients that need to work with APM F5.

For the variant you describe I would have to rebuild all our WCF clients to work with the channel (currently this was not necessary). Especially since that would only partially solve my problem. Since I have to check this query on every reqest (since I don't know when it revokes the validity of the cookies, that's decided by the APM F5 on invocation). In addition, I would have to take care of the cookies myself (i.e. copy them from one cookie container to another), which WCF (or the HTTPClient WCF uses) did for me in the other variant. And since this is not a one-time thing, but I need to do this consistently (if I want it to always work) I would have to encapsulate some code around each service request to write a check that resembles the DelegatingHandler in functionality.

Isn't it somehow possible under .net framework that I tell it to please use the .net core variant of the namespaces?

**Comment by mconnew** [comment]
You don't need to copy cookies around. You reuse the CookieContainer:
```c#
var request = (HttpWebRequest)WebRequest.Create("https://myserver/someurl");
request.CookieContainer = cookieManager.CookieContainer;
```
Cookie's have an expiry time on them. If you know the name of the cookie, you can retrieve it from the cookie container and check the expiry time. I don't believe that the F5 load balancer is arbitrary on it's disposing of cookies. It should set the cookie expiry time correctly. If it has a 1 minute expiry time and you haven't made a request within a minute, it will expire. This is very easy to set up as a background task.
```c#
public Task KeepCookieAlive(CookieContainer cookieContainer, CancellationToken token)
{
    while(!token.IsCancellationRequested)
    {
        var cookies = cookieContainer.GetCookies(new Uri("https://myserver/someurl");
        var cookie = cookies["cookieName"];
        if (cookie == null || (cookie.Expires - DateTime.Now) < TimeSpan.FromSeconds(10))
        {
            var request = (HttpWebRequest)WebRequest.Create("https://myserver/someurl");
            request.CookieContainer = cookieContainer;
            // Make request

            // Get updated cookie
            cookies = cookieContainer.GetCookies(new Uri("https://myserver/someurl");
            cookie = cookies["cookieName"];
        }
        // Wait 2 seconds longer than earlier check to ensure next time round will update if needed
        await Task.Delay((cookie.Expires - DateTime.Now) - TimeSpan.FromSeconds(8));
    }
}
```
You just kick off this background method before your first request and it keeps your load balancer state active. This code will work on .NET Core and .NET Framework. There isn't a way to use the .NET Core implementation on .NET Framework. You will need a bit more error checking around my proposed solution, e.g. try/catch around web request, bounds check on the Task.Delay to make sure it doesn't go negative, handle case of cookie still not being there (networking issue making LB not able to be connected to causing HttpWebRequest call to throw for example).  

If you really want to be able to do something equivalent, I do have a really hacky way to do something similar on .NET Framework, but it involves hijacking HttpWebRequest and has no direct involvement with WCF, and the code will be significantly different between .NET Framework and .NET Core. If you insist on going that path, I've been planning on writing a blog post about the technique for a while so I can probably write it up next week.

**Comment by Rerago** [comment]
Sure "KeepCookieAlive" would work. But in an environment with parallel running threads I can imagine that there could be overlaps.

The F5 load balancer works normally with cookies. The problem is that there is a lookout link that invalidates the cookies of the user (regardless of the service he is using). This is only an edge case but would make it harder to work with "Expires". In addition the names of the cookies are random (contain an ID, but the scheme could be intercepted with a regex). Because of this I didn't want to deal with it and chose the way of least resistance via the DelegatingHandler :D

I would be totally happy with a "really hacky way" since I would only use the code under .net framework. Until all our projects are moved to .net Core. And .net Core I would continue to use the DelegatingHandler.

**Comment by maumi** [comment]
hey @mconnew do you already wrote your Blog Post about it? I ran into a similar problem and I would be happy to see a workaround (even hacky)

**Comment by mconnew** [comment]
Sorry I forgot to link to it here when I made my method to hijack HttpWebRequests in .NET Framework available. You can find it here: https://github.com/mconnew/Playground/tree/main/HijackHttpWebRequest  
I will stress this isn't an official supported library and is just something I personally worked out and decided to make available as it's interesting.

I'm going to close the issue as with my code sample that should help solve your problem in a similar way as you do on .NET [Core].
