### ISSUE TITLE
Add ClientRuntime.SyncMethod, BeginMethod, and EndMethod

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/wcf#4549]
**Describe the bug**
ClientRuntime.SyncMethod, BeginMethod, and EndMethod are missing from the .NET Core API but are available in the .NET Framework version. This is making it difficult to instrument WCF in OpenTelemetry .NET.

**Additional context**
Discussion: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/38#discussion_r580657277

/cc @mconnew

**Comment by HongGit** [comment]
@imcarolwang  can you please work on this?
