### ISSUE TITLE
System.AggregateException:“Event ServiceChannelBeginCallStart (with ID 704) has the same task/opcode pair as e)”

### ISSUE THREAD

**Issue by NiKeYiGuN** [dotnet/wcf#4556]
`            var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
            binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
            //binding.Security.Transport.Realm = "SAP Web Application Server [LPQ]";
            var address = new EndpointAddress("https://mipoq.p.mi.com/XISOAPAdapter/MessageServlet?senderParty=&senderService=LINGYI_HZ_QAS&receiverParty=&receiverService=&interface=SI_ZFM_WS_API_OUT&interfaceNamespace=http://xiaomi.com/srm/b2b");
            
            SI_ZFM_WS_API_OUTRequest r = new SI_ZFM_WS_API_OUTRequest(request);                  
            SI_ZFM_WS_API_OUTClient myWebService = new SI_ZFM_WS_API_OUTClient(binding, address);//实例化变量           
            
            myWebService.ClientCredentials.UserName.UserName = "RFCLINGYIHZ";
            myWebService.ClientCredentials.UserName.Password = "1$WruwtP";

            var dd=  myWebService.SI_ZFM_WS_API_OUTAsync(request).Result;`

i use generate tool to build web serviece client, but i got an exception, i find that .net core don't support web serviece?

**Comment by HongGit** [comment]
@NiKeYiGuN can you please make sure that you are using the latest WCF packages?  Could you please also share with us the ,NET Core version you are using?

**Comment by NiKeYiGuN** [comment]
.i uset wcf packges in 4.4,and lasted version 4.8.1 I have a try. .NET core version 3.1,Thank u ,i m glad to recive your reply ,i have resolve this issue ,the reason is that i missing 2 parameters in  request. Thank u.

**Comment by HongGit** [comment]
Thanks for letting us know!  We are glad that your issue has resolved.
