### ISSUE TITLE
EndpointDispatcher Class contains no contents

### ISSUE THREAD

**Issue by pkatterjohn** [dotnet/wcf#4583]
Good Morning,

I am working on implementing a ClientMessageInspector in a .Net 5.0 application. I found documentation on how to implement this here: [IClientMessageInspector](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.dispatcher.iclientmessageinspector?view=dotnet-plat-ext-5.0).  Coupled with that is the EndpointBehavior found here: [IEndpointBehavior](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.dispatcher.endpointdispatcher?view=dotnet-plat-ext-5.0). 

When working on the implementation of the EndpointBehavior I am receiving an error on the following line saying: `'EndpointDispatcher' does not contain a definition for 'DispatchRuntime' and no accessible extension method 'DispatchRuntime' accepting a first argument of type 'EndpointDispatcher' could be found (are you missing a using directive or an assembly reference?)`

Upon inspecting the `EndpointDispatcher` class I noticed it is empty. 
![image](https://user-images.githubusercontent.com/22358291/113730369-73293d80-96bd-11eb-8306-c18ec006cd87.png)
While I was not expecting the full code, I was at least expecting properties and methods to be listed. I found the proper contents of the file here: [EndpointDispatcher-Github](https://github.com/dotnet/wcf/blob/main/src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/EndpointDispatcher.cs)

I did try reverting to an older version of `System.ServiceModel.Primitives` but have found it to be consistently empty. I have been able to confirm my co-workers are seeing the same result and I have been able to replicate in the attached barebones project. 

[ClientDispatcherTest.zip](https://github.com/dotnet/wcf/files/6265552/ClientDispatcherTest.zip)

Project Information:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.1" />
  </ItemGroup>

</Project>
```
Whether this is a problem isolated to me or I am not implementing the class properly I am unsure.
Any help on this issue would be greatly appreciated and please let me know if additional information would be helpful!

**Comment by mconnew** [comment]
The DispatchRuntime class is also empty on the contract. Can you tell me what API you are wanting to access on DispatchRuntime? There might be another way to achieve the same result, or we can expose the required API's in the next major release.

**Comment by pkatterjohn** [comment]
@mconnew, I am trying to add a MessageInspector through DispatchRuntime in order to intercept the received message from a vendor before it goes through our system.

My understanding of the implementation is as follows and allows for the ClientMessageInspector to execute AfterReceiveReply in which I am wanting to add a security header to the message.
```
public void ApplyDispatchBehavior(ServiceEndpoint serviceEndpoint, EndpointDispatcher endpointDispatcher)
{
  endpointDispatcher.DispatchRuntime.MessageInspectors.Add(new EndpointBehaviorMessageInspector());
}
```

If there is a better/easier way to do this I am all ears!

**Comment by mconnew** [comment]
As usual with WCF there's 10 ways to do the exact thing. So far there hasn't been a use case that has actually required EndpointDispatcher and/or DispatchRuntime. If something comes up where they are needed, we'll definitely expose those api's. You can add a message inspector via a different behavior api, the ApplyClientBehavior method. There's an example [here](https://github.com/dotnet/wcf/blob/main/src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractCommon.4.1.0.cs#L139). Basically you do this:
```c#
        public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
        {
            clientRuntime.ClientMessageInspectors.Add(new EndpointBehaviorMessageInspector());
        }
```

**Comment by pkatterjohn** [comment]
@mconnew , thanks for the info!

I am still running into issues getting the `AfterReceiveReply` function to execute. The code is executing the `BeforeSendReply` function so that leads me to believe I have part of the implementation functioning. I have stripped out my additional code to see if I could get just a basic execution figured out and ended up with exactly what is in the example (went ahead and included my code below for redundancy, should be essentially identical).

I create a new MessageInspector and add in to the clients EndpointBehaviors.
 ```
            var cb = new MessageInspectorBehavior();

            client.Endpoint.EndpointBehaviors.Add(cb);
```

**Message Inspector Implementation**
``` 
public class MessageInspectorBehavior : IClientMessageInspector, IEndpointBehavior
    {
        private Message _receivedMessage;

        public Message ReceivedMessage
        {
            get
            {
                return _receivedMessage;
            }
        }

        public void AfterReceiveReply(ref System.ServiceModel.Channels.Message reply, object correlationState)
        {
            MessageBuffer buffer = reply.CreateBufferedCopy(int.MaxValue);
            _receivedMessage = buffer.CreateMessage();

            reply = buffer.CreateMessage();

            //**Add Security Header to Response Here**
        }

        public object BeforeSendRequest(ref System.ServiceModel.Channels.Message request,
            System.ServiceModel.IClientChannel channel)
        {
            return null;
        }

        public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
        { }

        public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
        {
            clientRuntime.ClientMessageInspectors.Add(this);
        }

        public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher)
        { }

        public void Validate(ServiceEndpoint endpoint)
        { }
    }
```

Thanks for your continued help on this!

**Comment by mconnew** [comment]
You won't get the AfterReceiveReply method called if there's something wrong with the message. Basically the AfterReceiveReply method is executed after the message has traversed the entire transport layer, including handling any security headers. The only thing left to do before the application code call returns is deserialization. If you are trying to add a security header that would be required by WCF, you're too late as any security headers have already been processed already.  
Is this code that is already functioning correctly in .NET Framework? If AfterReceiveReply isn't getting hit, then your proxy call should be throwing an exception such as a MessageSecurityException.

**Comment by tapizquent** [comment]
Is there any way to make changes to the Message before sending a reply?

We are currently using `BeforeSendReply` from `IDispatchMessageInspector` but as pointed out here, that class is completely missing from the package.

The vendor providing the service is expecting a reply with an specific naming, therefore we are using the `BeforeSendReply` to perform an xslt transform.

**Comment by mconnew** [comment]
@tapizquent, sorry I missed your message originally. IDispatchMessageInspector is used for callback contracts and services and not by a regular client call. That uses IClientMessageInspector. If you still need help, please open a new issue as this issue was about EndpointDispatcher.
