### ISSUE TITLE
WSTrustChannelSecurityTokenProvider - RequestSecurityToken with ActAs

### ISSUE THREAD

**Issue by SteMcLellan** [dotnet/wcf#4593]
Hello,

We have run into a problem utilizing `WSTrustChannelSecurityTokenProvider` to acquire security tokens in our application. Following examples such as https://github.com/dotnet/wcf/issues/4542#issuecomment-789333798 we have been able to successfully call our STS and issue tokens, however there exist scenarios where our application requires/desires a token that utilizes the 'ActAs' property on the RequestSecurityToken request.

Trying to implement this ourselves using `WSTrustChannelSecurityTokenProvider` has yielded a few issues with the current implementation.

1. There are limited extensibility options for `WSTrustChannelSecurityTokenProvider`. There are several `protected virtual` methods on the object, but using them is difficult due to other properties which are set to `internal`. In our case, in order to submit the `ActAs` request, we need to supply `ClientCrendentials` to the TokenProvider, but we cannot actually do that because `ClientCredentials` are not a constructor parameter and the property is `internal`.  Having some way to access the `ChannelFactory` prior to issuing a request might help but that is also `internal`.
   * Our initial plan was to simply override `GetWsTrustRequest` and add/modify the fields we wanted, but we soon found out that wasn't going to work.
   * Is it not expected for clients to attempt to modify the behavior of the WsTrust token provider?
1. The WsTrust objects here (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/brentsch/wstrust/src/Microsoft.IdentityModel.Protocols.WsTrust) seem to partially support `ActAs`, where `WsTrustMessage` has a field for it, but it is never accessed during any of the serialization methods. I realize this is a different project, but these issues seem a bit intertwined.

My questions:
1. Is there any plan towards creating a port of `WsTrustChannelFactory` and `WsTrustChannel` which are available in full framework? These are the objects we utilize in our full framework applications. My assumption, based off reading other issues, is that these objects won't be brought forward.
2. Do you plan on supporting `ActAs`, or are we on our own to implement this?

**Comment by thuannguy** [comment]
@mconnew I have the same need. Could you please tell us if ActAs will be supported, or if we need to do it on our own, point us to the right direction?

**Comment by HongGit** [comment]
@afifi-ins can you give this a try and see if this is already resolved?

**Comment by afifi-ins** [comment]
Here is a code snippet: 
``` C#
      // ask for token address
      var address = new EndpointAddress("http://federationSTS/username");
      var binding = new WS2007HttpBinding();
      binding.Security.Mode = SecurityMode.TransportWithMessageCredential;
      binding.Security.Message.ClientCredentialType = MessageCredentialType.UserName;
      binding.Security.Message.EstablishSecurityContext = false;
      binding.Security.Message.AlgorithmSuite = SecurityAlgorithmSuite.Default;

      var factory = new WSTrustChannelFactory(binding, address);

      factory.Credentials.UserName.UserName = "user";
      factory.Credentials.UserName.Password = "pass";

      // this need to be populated by some other means
      Microsoft.IdentityModel.Tokens.SecurityToken securityToken = null;

      var rst = new WsTrustRequest(WsTrustActions.Trust13.Issue)
      {
          KeyType = WsTrustKeyTypes.Trust13.Bearer,
          KeySizeInBits = 0,
          WsTrustVersion = WsTrustVersion.Trust13,
          AppliesTo = new Microsoft.IdentityModel.Protocols.WsPolicy.AppliesTo(new Microsoft.IdentityModel.Protocols.WsAddressing.EndpointReference("http://contoso.com/myservice.svc")),
          ActAs = new SecurityTokenElement(securityToken)
      };

      var wsTrustChannel = factory.CreateChannel();
      var token = await wsTrustChannel.IssueAsync(rst);

```
Let us know if you need more info.

**Comment by mconnew** [comment]
Closing the issue. Feel free to reopen if the info provided doesn't work for you.
