### ISSUE TITLE
ProtectionLevel property missing FaultContractAttribute

### ISSUE THREAD

**Issue by selvan-ramki** [dotnet/wcf#4609]
I am trying to convert some WCF project libraries to .Net Standard 2.0. For the ServiceModel, I have included the System.ServiceModel.Primitives package. But noticed that the ProtectionLevel property is missing in the FaultContractAttribute class. We have used this property in our project and thus throws an error. Any suggestion is welcome

Here is the metadata from .Net Standard (the ProtectionLevel & HasProtectionLevel  missing)
```
Namespace System.ServiceModel
    <AttributeUsage(AttributeTargets.Method, AllowMultiple:=True, Inherited:=False)>
    Public NotInheritable Class FaultContractAttribute
        Inherits Attribute
        Public Sub New(detailType As Type)
        Public Property Action As String
        Public ReadOnly Property DetailType As Type
        Public Property Name As String
        Public Property [Namespace] As String
    End Class
End Namespace
```

Here is the meta data from .Net Framework reference:
```
Namespace System.ServiceModel
    <AttributeUsage(AttributeTargets.Method, AllowMultiple:=True, Inherited:=False)>
    Public NotInheritable Class FaultContractAttribute
        Inherits Attribute
        Public Sub New(detailType As Type)
        Public ReadOnly Property DetailType As Type
        Public Property Action As String
        Public Property Name As String
        Public Property [Namespace] As String
        Public Property ProtectionLevel As ProtectionLevel
        Public ReadOnly Property HasProtectionLevel As Boolean
    End Class
End Namespace
```

**Comment by HongGit** [comment]
@selvan-ramki ProtectionLevel  is only used when used for full Message security and is ignored with all other security mode.  We don't support full Message security so there is no supported usage scenario.
