### ISSUE TITLE
Consuming a WCF Duplex service using WSDualHttpBinding

### ISSUE THREAD

**Issue by sdesmarteau** [dotnet/wcf#4614]
@prasadmamidi7, `WSDualHttpBinding` is not yet supported in the .Net Core Framework, refer to [WCF features in .Net Core 2.0](https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v2.0.0.md) for the latest feature set; and the GitHub documentation for the [WCF Web Service Reference](https://github.com/dotnet/wcf/blob/master/Documentation/WCF-Web-Service-Reference-guide.md) for more information.

_Originally posted by @mlacouture in https://github.com/dotnet/wcf/issues/2382#issuecomment-345812973_

Have there been any updates re: adding support for consuming a WCF duplex service using wsDualHttpBinding? The lack of support is the one thing preventing our organization from a full switch to .NET 5.

Thanks!

**Comment by HongGit** [comment]
This implementation should be done on the server side, see tracking issue corewcf/corewcf#361.

**Comment by sdesmarteau** [comment]
Sorry, I should've clarified:

I need to build a client to consume a pre-existing WCF service that was published using wsDualHttpBinding, of which I have no control. Given this situation, wouldn't it be true that wsDualHttpBinding support needs to be added to the client-side library?

Thanks for your time and consideration!
