### ISSUE TITLE
ClientMessageInspector doesn't work properly when generating async methods and using async/await

### ISSUE THREAD

**Issue by Doomblaster** [dotnet/wcf#4618]
As already mentioned here: https://github.com/dotnet/extensions/issues/3412

When creating a loggingscope in a clientmessageinspector, the logging scope is not disposed properly when using async/await due to how AsyncLocal is handled

Sync:
![image](https://user-images.githubusercontent.com/1055547/117280018-79e4d500-ae62-11eb-9f31-6fc055f37816.png)
Async:
![image](https://user-images.githubusercontent.com/1055547/117280041-81a47980-ae62-11eb-93ae-518785731486.png)

**To Reproduce**
[WCFRepro.zip](https://github.com/dotnet/wcf/files/6433591/WCFRepro.zip)

**Expected behavior**
I would expect this to work the same way for both sync and async

**Additional context**
As a sidenote, in addition to the "solution" mentioned here https://github.com/dotnet/extensions/issues/3412#issuecomment-676004005, https://www.nuget.org/packages/Capri/ also fix the issue, but in general I think this should be fixed in the library itself.

**Comment by HongGit** [comment]
Since this is not a feature which was supported in .NET Framework, there is no plan to support this in .NET Core either.  It does seem like you could use Capri as a workaround.
