### ISSUE TITLE
Update System.Runtime.Serialization.Xml dependency to 4.1.0

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#462]
This depends on issue https://github.com/dotnet/corefx/issues/4132 being fixed first.
Currently, WCF depends on 4.0.10.0 because the dependency on 4.1.0 broke the TFS lab builds (due to API's not existing in desktop and TestNet).

**Comment by zhenlan** [comment]
We will wait serialization to finalized its support story for desktop and testnet.

**Comment by zhenlan** [comment]
@roncain Please go ahead and make the change. TEST.NET should not be a problem for this anymore.

**Comment by roncain** [comment]
Fixed by #715 which included this version increase.
