### ISSUE TITLE
SecurityMode.Message is not supported?

### ISSUE THREAD

**Issue by GitAntoinee** [dotnet/wcf#4632]
**Describe the bug**

**To Reproduce**
1. Create a an instance like `var client = new WSHttpBinding(SecurityMode.Message)`
2. Call `client.OpenAsync().Wait()`

**Expected behavior**
No exceptions thrown

**Screenshots**

**Additional context**
I am on Linux

**Comment by GitAntoinee** [comment]
The same code, using .NET framework 4.8 works perfectly (with Wine)

**Comment by HongGit** [comment]
You are correct, this is not implemented yet.  There is no plan to add this due to missing dependencies
