### ISSUE TITLE
How to bypass the proxy in wcf

### ISSUE THREAD

**Issue by anilsg123** [dotnet/wcf#4635]
I have created a sample for wcf client that communicates with the service via proxy server. Client authenticates to proxy server using Basic authentication. Communication is successful with the desired response with the usage of BasicHttpBinding element aloing with CustomBinding properties. However, there is a requirement to bypass the proxy server if the network settings of the system are configured with bypass proxy list. Unable to find the approach for setting the bypass proxy list in BasicHttpBinding or CustomBinding properties.

**Code base**

```c#
var binding = new BasicHttpBinding();

binding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

//Wrap binding custombinding to route request through proxy with credential authentication
var customBinding = new CustomBinding(binding);
var httpElement = customBinding.Elements.Find<HttpTransportBindingElement>();
httpElement.ProxyAddress = new Uri("http://<proxyIP>:<proxyPort>");
httpElement.ProxyAuthenticationScheme = AuthenticationSchemes.Basic;
httpElement.UseDefaultWebProxy = false;

using (var webClient = new TransparencyPlatformClient(customBinding, FinalEndpoint)
{
	webClient.ClientCredentials.ServiceCertificate.SslCertificateAuthentication =
        new X509ServiceCertificateAuthentication()
        {
            CertificateValidationMode = X509CertificateValidationMode.None,
            RevocationMode = System.Security.Cryptography.X509Certificates.X509RevocationMode.NoCheck
        };

	webClient.ClientCredentials.UserName.UserName = <ProxyUserName>;
	webClient.ClientCredentials.UserName.Password = <ProxyPassword>;

	webClient.sendMessage(YourMessage);
}
```

Need help for setting the bypass list

**Comment by mconnew** [comment]
Are you wanting to explicitly set the bypass list or have the system bypass list automatically picked up? By default WCF lets HttpClientHandler deal with this, but we do have the ability to override the proxy using an IWebProxy implementation and you would fill out the IsBypassed implementation. If you are wanting to automatically use the system configured proxy bypass list, this is an issue for the owners of HttpClientHandler in the runtime repo.

**Comment by HongGit** [comment]
We didn't hear back from you for a while, close it now.  Feel free to re-activate this if there are more questions regarding this.
