### ISSUE TITLE
how do i convert this to .net core? I don't see custom binding with mutual certificate?

### ISSUE THREAD

**Issue by sekar79** [dotnet/wcf#4659]
how do i convert this to .net core? I don't see custom binding with mutual certificate?
This is my binding.
```xml
<customBinding>
        <binding name="MutualCertificateSigningNoAuthenticationBinding" sendTimeout="00:01:00">
          <textMessageEncoding messageVersion="Soap11WSAddressing10" />
          <security authenticationMode="MutualCertificate" requireDerivedKeys="false" enableUnsecuredResponse="True" includeTimestamp="true" keyEntropyMode="ClientEntropy" messageProtectionOrder="SignBeforeEncrypt" allowSerializedSigningTokenOnReply="true" requireSecurityContextCancellation="false" messageSecurityVersion="WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10"> </security>
          <httpsTransport />
        </binding>
      </customBinding>
```

behavior is 
```xml
<behavior name="MutualCertificateBehavior">
          <clientCredentials>
            <clientCertificate findValue="dev" storeLocation="LocalMachine" storeName="My" x509FindType="FindBySubjectName" />
            <serviceCertificate>
              <defaultCertificate findValue="edev" storeLocation="LocalMachine" storeName="TrustedPeople" x509FindType="FindBySubjectName" />
              <authentication trustedStoreLocation="LocalMachine" />
            </serviceCertificate>
            <windows allowedImpersonationLevel="None" />
            <httpDigest impersonationLevel="None" />
          </clientCredentials>
        </behavior>
```

**Comment by HongGit** [comment]
@sekar79  what you are asking is full Message security feature, which is not supported.  Is it possible to use a different binding?  There are other binding which support client and server certificate authentication without full Message security.

**Comment by sekar79** [comment]
@HongGit  I am writing client code for above SOAP service created in Java. WCF services are created by different company and we need to call this service to get data. We were using .net framework and now switched to .net core. This is the last piece in the migration. All i need is to create a client to call this service. I am not able to change anything on other end.

**Comment by mconnew** [comment]
@sekar79, unfortunately due to missing dependencies we can't yet support full Message security which is needed for your configuration. As you are unable to modify the binding being used by the service, there isn't anything we can suggest at this time. I'm going to close this issue as there's nothing that we can do.
