### ISSUE TITLE
 cannot find a token authenticatorfor the system.Identitymodel.tokens.X509SecurityTOken token type

### ISSUE THREAD

**Issue by sekar79** [dotnet/wcf#4670]
I am getting an error when calling WCF service from .net core 3.1 client. i used connected services to import the WSDl and generated client code. When calling the service, i am getting below error. Cannot find a token authenticator for the System.Identitymodel.Tokens.X509SecurityToken. Tokens of that type cannot be accepted according to current security settings. 

In .net framework client, i had property under security called allowSerializedSigningTokenOnReply = true. But i don't see this here. 
Any help is greatly appreciated.

**Comment by HongGit** [comment]
@sekar79 is it possible for you to provide a sample reply from .NET framework scenario, and also provide the binding info in your repro?

**Comment by sekar79** [comment]
@HongGit  i have added binding info in my other post. When i use that i am getting this error.

**Comment by HongGit** [comment]
This is a duplicate of #4677.  

Thanks for raising issue with us!
