### ISSUE TITLE
Add WSTrustChannelFactory and WSTrustChannel to Federation package

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#4674]
This issue is to track creation of a new WSTrustChannelFactory and WSTrustChannel client to enable scenarios which require getting a SecurityToken from an STS and using it outside of WCF.

**Comment by mconnew** [comment]
@brentschmaltz, this issue is for tracking the WSTrustChannelFactory work you have started the design for.

**Comment by plombaer** [comment]
Hi,
I'm migrating a .Net48 project to .Net6. It is using WSTrustChannelFactory and RequestSecurityToken to connect to an ADFS server. I updated the reference to the very last version of System.IdentityModel.Tokens.Jwt but it still doesn't find the classes. Any change that those 2 types would be included soon ?
Thanks

**Comment by mikkeljohnsen** [comment]
When will this be released. I have been awaiting for years now. (@HongGit you said a few weeks, several years ago :) ) ?

**Comment by felixpelletier** [comment]
We're also waiting on it for migrating from a .Net48 project to .Net6. ADFS server connection as well.

**Comment by simhi88** [comment]
@mconnew : Are there any updates regarding that issue here? We would also like to migrate from .Net48 to .Net6 and need to use the WSTrustChannelFactory / WSTrustChannel.

**Comment by mnixflow** [comment]
Also interested in this, no updates?

**Comment by HongGit** [comment]
[WCF 6.0 release](https://github.com/dotnet/wcf/releases/tag/v6.0.0-rtm) went out in May this year.
