### ISSUE TITLE
how do we create this binding .net core client?

### ISSUE THREAD

**Issue by sekar79** [dotnet/wcf#4677]
This is old setting in .net framework 4.7.2.

`<binding name="MutualCertificateSigningNoAuthenticationBinding" sendTimeout="00:01:00">
          <textMessageEncoding messageVersion="Soap11WSAddressing10" />
          <security authenticationMode="MutualCertificate" requireDerivedKeys="false" enableUnsecuredResponse="True" includeTimestamp="true" keyEntropyMode="ClientEntropy" messageProtectionOrder="SignBeforeEncrypt" allowSerializedSigningTokenOnReply="true" requireSecurityContextCancellation="false" messageSecurityVersion="WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10"> </security>
          <httpsTransport />
        </binding>`

I need to use .net core WCF client now. I am using  dotnet / wcf library. I have used  below code. 

var _wsbinding = new WSHttpBinding();
                _wsbinding.Security.Message.ClientCredentialType = MessageCredentialType.Certificate;
                _wsbinding.Security.Message.EstablishSecurityContext = false;
                _wsbinding.Security.Mode = SecurityMode.Transport;
                _wsbinding.Security.Message.NegotiateServiceCredential = false;
                _wsbinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

                
                var _binding = new CustomBinding(_wsbinding);
                _binding.Name = "MutualCertificateSigningNoAuthenticationBinding";
                _binding.SendTimeout = new TimeSpan(0, 1, 0);

                var sbe = _binding.Elements.Find<TransportSecurityBindingElement>();
                if (sbe != null)
                {
                    sbe.SecurityHeaderLayout = SecurityHeaderLayout.Lax;
                    sbe.KeyEntropyMode = System.ServiceModel.Security.SecurityKeyEntropyMode.ClientEntropy;
                    sbe.MessageSecurityVersion = MessageSecurityVersion.WSSecurity10WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10;
                    sbe.IncludeTimestamp = true;
                }

                MessageVersion msv = MessageVersion.CreateVersion(EnvelopeVersion.Soap11, AddressingVersion.WSAddressing10);
                var _mv = _binding.Elements.Find<TextMessageEncodingBindingElement>();
                if(_mv == null)
                {
                    var _element = new TextMessageEncodingBindingElement();
                    _element.MessageVersion = msv;
                    _binding.Elements.Add(_element);
                }
                else
                {
                    _mv.MessageVersion = msv;
                }

                EndpointIdentity dnsEndpointIdentity = new DnsEndpointIdentity("XXXXXXXXXXXXXXX");
                Uri uri = new Uri("https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                var _address = new EndpointAddress(uri, dnsEndpointIdentity);

                MemberInquiryClient _client = new MemberInquiryClient(_binding,_address) ;
                _client.ClientCredentials.ClientCertificate.SetCertificate(System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine,
                            System.Security.Cryptography.X509Certificates.StoreName.My,
                            System.Security.Cryptography.X509Certificates.X509FindType.FindBySubjectName, "yyyyyyyyyyyyyy");
                _client.ClientCredentials.ServiceCertificate.SetDefaultCertificate(System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine,
                    System.Security.Cryptography.X509Certificates.StoreName.TrustedPeople, System.Security.Cryptography.X509Certificates.X509FindType.FindBySubjectName,
                    "zzzzzzzzzzzz");
                _client.ClientCredentials.ServiceCertificate.Authentication.TrustedStoreLocation = System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine;
                _client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new System.ServiceModel.Security.X509ServiceCertificateAuthentication()
                {
                    CertificateValidationMode = System.ServiceModel.Security.X509CertificateValidationMode.None,
                    RevocationMode = System.Security.Cryptography.X509Certificates.X509RevocationMode.NoCheck
                };

I am getting below error. 

Cannot find token authenticator for the system.identitymodel.tokens.X509Securitytoken token type. Tokens of that type cannot be accepted according to current security settings.

**Comment by HongGit** [comment]
@sekar79 WCF Core client does not support Message Security.  Is it an option for you to change server side binding to support equivalent security?

**Comment by sekar79** [comment]
@HongGit  We cannot make any changes to server side as it is hosted by another company. They are using mainframe systems and they don't have immediate product plans to change this. We are moving from .net framework to .net core. and we got stuck at this.

**Comment by HongGit** [comment]
Thanks for raising the issue!

We will consider this in future releases.

**Comment by HongGit** [comment]
Close this one as we already have an issue tracking message security work.
