### ISSUE TITLE
Test case WebSocketHttpRequestReplyBinaryStreamed failing.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#468]
System.NotSupportedException : this method should never get called
Stack Trace:
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs(396,0): at System.ServiceModel.Channels.WebSocketTransportDuplexSessionChannel.ThrowOnPendingException(Exception& pendingException)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs(584,0): at System.ServiceModel.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.Receive(TimeSpan timeout)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SynchronizedMessageSource.cs(113,0): at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TransportDuplexSessionChannel.cs(100,0): at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\TransportDuplexSessionChannel.cs(195,0): at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceive(TimeSpan timeout, Message& message)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Dispatcher\DuplexChannelBinder.cs(484,0):at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(765,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(722,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(371,0): at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(139,0): at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
at generatedProxy_1.DownloadStream()
C:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Extensibility\WebSockets\WebSocketTests.cs(36,0): at WebSocketTests.WebSocketHttpRequestReplyBinaryStreamed()

**Comment by StephenBonikowsky** [comment]
Test case WebSocketHttpDuplexBinaryStreamed is also failing with this issue.

**Comment by mconnew** [comment]
Found the cause, TimeoutStream doesn't override ReadByte/WriteByte, which then get delegated to WebSocketStream.Read/Write which shouldn't be called. I'm adding an implementation to TimeoutStream for these two methods to delegate to the right method.
