### ISSUE TITLE
Problem with User-Agent header in SOAP call migrating from net 48 to net5.0

### ISSUE THREAD

**Issue by AndrewZenith** [dotnet/wcf#4680]
A Service requires us to send a specific User-Agent header.

The following works fine in net48, but not net50 (i.e. using this library).  How do I get this to work?

using (OperationContextScope contextScope = new OperationContextScope(SOAP.InnerChannel))
                    {
                        OperationContext.Current.OutgoingMessageProperties[HttpRequestMessageProperty.Name] = new HttpRequestMessageProperty()
                        {
                            Headers =
                            {
                                { HttpRequestHeader.UserAgent, "Vendor=XXX, Application=XXX, Version=7.6.0.208, ClientID=XXX"}
                            }
                        };
                        ProcessResponse = SOAP.processSOAP(new processEDIMessageRequest())?.Response; // error here
                    }

Here is the exception:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

  This exception was originally thrown at this call stack:
    System.Net.Http.Headers.HttpHeaderParser.ParseValue(string, object, ref int)
    System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(System.Net.Http.Headers.HeaderDescriptor, System.Net.Http.Headers.HttpHeaders.HeaderStoreItemInfo, string)
    System.ServiceModel.Channels.HttpChannelFactory<TChannel>.HttpClientRequestChannel.HttpClientChannelAsyncRequest.PrepareMessageHeaders(System.ServiceModel.Channels.Message)
    System.ServiceModel.Channels.HttpChannelFactory<TChannel>.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(System.ServiceModel.Channels.Message, System.Runtime.TimeoutHelper)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    System.ServiceModel.Channels.RequestChannel.RequestAsync(System.ServiceModel.Channels.Message, System.TimeSpan)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]

Inner Exception 1:
FormatException: The format of value 'Vendor=XXX, Application=XXX, Version=7.6.0.208, ClientID=XXX' is invalid.

**Comment by jjakob666** [comment]
I have not had success in generating code from wsdl in .net5.  I get the error "No endpoints compatible with .Net Core apps were found."  Were you able to get past this?

**Comment by AndrewZenith** [comment]
It was generated in .net 4.8.  Works fine except the setting of the User Agent header.

**Comment by HongGit** [comment]
@AndrewZenith the User-Agent you used is not a valid format per [spec](https://httpwg.org/specs/rfc7231.html#header.user-agent).  The reason it could pass on .NET 4.8 framework is because .NET framework just sets the value as a string, and .NET Core is using HttpClient to parse headers in a structured way.  

The correct way would be something like "MyApp/1.0 (Vendor=XXX; Application=XXX; Version=7.6.0.208; ClientID=XXX)".

**Comment by HongGit** [comment]
Feel free to reactivate if there are more concerns.
