### ISSUE TITLE
Force sgen.exe use assembly redirects

### ISSUE THREAD

**Issue by RaptorCZ** [dotnet/wcf#4684]
Not sure where is the right repo for sgen.exe tool, but found some issues here.

I have assembly I need to use SGen with. Assembly is using another assembly for logger, and this assembly is using different version of referenced Microsoft.Extensions.Configuration.Abstractions. Project is new csproj but full framework.

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>


    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
```

Using sgen I got

```
Microsoft (R) Xml Serialization support utility
[Microsoft (R) .NET Framework, Version 4.8.3928.0]
Copyright (C) Microsoft Corporation. All rights reserved.
Error: The type initializer for 'Infrastructure.Logging.CommonLogger' threw an exception.
  - Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

If you would like more help, please type "sgen /?".
```

Main assembly is using version 5 of abstractions library, but SGen ignores it.

Tried to generate assembly binding redirects for this dll, but it still doesn't work.

Why and how to fix it? Application crashes when deployed to RTM server.

**Comment by HongGit** [comment]
@RaptorCZ it seems that you are using sgen.exe which ships with .NET Framework SDK.  For issues related with sgen.exe, please log an issue at Visual Studio Feedback [site](https://developercommunity.visualstudio.com/home).

sgen.exe is a legacy .NET framework tool, it does not support .NET core, and it's currently in maintenance mode.
