### ISSUE TITLE
Cannot use SOAP service that requires HTTP Basic Authentication in .NET 5

### ISSUE THREAD

**Issue by zumbuschms** [dotnet/wcf#4685]
**Describe the bug**
I'm trying to access Exchange Auto Discover SOAP service (https://autodiscover.example.com/autodiscover/autodiscover.svc) that requires authentication. After merging the XSD into the WSDL dotnet svcutil was able to generate the model classes and client, and just skipped generating an endpoint as the WSDL for Exchange Auto Discover does not provide these information. So far so good. But if I try to access the WSDL service I always get this error message:

`The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Negotiate, NTLM, Basic realm="autodiscover.example.com"'.`

I intercepted the POST request and the Authorization header is missing. The service properly responds with 401 and the supported authentication mechanisms in the WWW-Authenticate as you can also conclude from the error message. The library seems to never interpret the 401 response as a challenge and fails.

This is not just an issue with a broken Exchange Server or IIS configuration, you can also reproduce the error with the Exchange Auto Discover service in Exchange Online (https://autodiscover-s.outlook.com/autodiscover/autodiscover.svc).

Is there a way to use a WSDL web service that requires HTTP Basic Authentication?

**To Reproduce**
To test the generated client I set up this NUnit unit test.

```
private async Task Test()
{
    var emailAddress= "<any valid Exchange Online email address>"
    var password = "<correct password>"

    var binding = new BasicHttpsBinding();
    binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;

    var endpoint = new EndpointAddress("https://autodiscover-s.outlook.com/autodiscover/autodiscover.svc");

    var client = new AutodiscoverClient(binding, endpoint);
    client.ChannelFactory.Credentials.UserName.UserName = emailAddress;
    client.ChannelFactory.Credentials.UserName.Password = password;

    var response = await client.GetUserSettingsAsync(emailAddress, "InternalEwsUrl", "ExternalEwsUrl");
    Assert.That(response, Is.Not.Null);
}

```
This is the test output including the stack:

```
Message: 
    System.ServiceModel.Security.MessageSecurityException : The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm=""'.

  Stack Trace: 
    AsyncResult.End[TAsyncResult](IAsyncResult result)
    SendAsyncResult.End(SendAsyncResult result)
    ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
    <>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
    --- End of stack trace from previous location ---
    DummyTests.Test() line 47
    GenericAdapter`1.BlockUntilCompleted()
    NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
    AsyncToSyncAdapter.Await(Func`1 invoke)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    <>c__DisplayClass4_0.<PerformWork>b__0()
    <>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
    ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
    ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    ContextUtils.DoIsolated(ContextCallback callback, Object state)
    ContextUtils.DoIsolated[T](Func`1 func)
    SimpleWorkItem.PerformWork()
```

**Expected behavior**
I would expect the authorization header to be included in any request, especially on HTTPS connections or at least I would expect the library to handle the challenge properly and resend the request with the authorization header.

**Additional context**
The official WSDL is documented at https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxwsadisc/059a7880-3246-42e3-b402-869e208cd143. I've attached my merged WSDL.

[ServicesMerged.wsdl.txt](https://github.com/dotnet/wcf/files/6930476/ServicesMerged.wsdl.txt)

**Comment by mconnew** [comment]
Can you try with HttpClient to just send a POST request with just some dummy data in the body. For the credentials, use an instance of CredentialsCache to limit the authentication to Basic auth only. You use it similar to this:
```
NetworkCredential credential = new NetworkCredential(username, password);
CredentialCache credentialCache = new CredentialCache();
Uri uriPrefix = net Uri("https://autodiscover-s.outlook.com/");
credentialCache .Add(uriPrefix, "Basic", credential);
```

Set the credential cache as the credential on HttpClient. I have a suspicion that HttpClient might have a bug where it will only look for credentials in the credential cache for the first authentication mechanism when presented with multiple, and when it can't find a credential for Negotiate, it fails. Doing this experiment should confirm this,

**Comment by zumbuschms** [comment]
I've tried a console application that directly uses HttpClient to send an empty post request. Although I've set the HttpRequestHandler to PreAuthenticate and assigned the credential cache, the initial request is still sent without credentials but a second request is sent with the correct credentials and the server responds with a SOAP error. The HttpClient itself seems to handle HTTP Basic Authentication properly although I'd expect the setting PreAuthenticate to true would include the Authorization header in the initial request. The sample code looks like this:

```
            var credentials = new NetworkCredential("username", "password");
            var cache = new CredentialCache();
            var urlPrefix = new Uri("https://autodiscover.example.com/");
            cache.Add(urlPrefix, "Basic", credentials);

            using (var handler = new HttpClientHandler())
            {

                handler.ServerCertificateCustomValidationCallback = (_1, _2, _3, _4) => true;
                handler.PreAuthenticate = true;
                handler.Credentials = cache;
                using (var client = new HttpClient(handler))
                {
                    var response = client.PostAsync("https://autodiscover.example.com/autodiscover/autodiscover.svc", new StringContent("")).GetAwaiter().GetResult();
                    response.EnsureSuccessStatusCode();
                }
            }
```

We are using dependency injection to provide a the HttpClient to the WCF library following the steps from https://dev.to/nikolicbojan/make-soap-requests-using-ihttpclientfactory-in-net-core-46hk. Our DI registrations looks like this:

```
            serviceCollection
                .AddHttpClient("external-httpclient")
                .AddTransientHttpErrorPolicy(builder => builder.WaitAndRetryAsync(3, i => TimeSpan.FromSeconds(0.5 * i)))
                .ConfigurePrimaryHttpMessageHandler(provider =>
                {
                    var clientHandler = new HttpClientHandler()
                    {
                        ServerCertificateCustomValidationCallback = CertificateCallbacks.External.ServerCertificateCustomValidationCallback
                    };
                    return clientHandler;
                });
```
The custom certificate validation check just checks if the certificate is fully valid (errors == SslPolicyErrors.None). Do we have to set up the credentials cache via DI, too? That would be hard as multiple threads might need to connect to the same endpoint at the same time using different credentials.

**Comment by mconnew** [comment]
Ah, that makes sense now. In the blog article, it's completely replacing the HttpClientHandler from WCF with your own, which means credentials aren't being populated. You've created a named HttpClient (external-httpclient) and one HttpClient/HttpClientHandler can only use a single set of credentials. Each time you ask for the handler, it's going to return you the same one each time. You need an instance of each handler for every unique set of credentials. On top of that, you can't simply cast the returned MessageHandler from factory.CreateHandler to an HttpClientHandler as you are using AddTransientHttpErrorPolicy which wraps the HttpClientHandler in a PolicyHttpMessageHandler. You have a few options.

### Configure the factory to return a new instance each time
I don't know enough about the HttpClientFactory logic to know how to achieve this, but if you can get it to return you a new instance each time, you should be able to solve this. WCF doesn't call this every time, for each ChannelFactory instance it calls it once for each unique set of credentials and caches it. If you can get it to instantiate a new one every time CreateHandler is called on the factory, then you could do something like this:
```c#
public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
{
    bindingParameters.Add(new Func<HttpClientHandler, HttpMessageHandler>(handler => 
    {
        HttpMessageHandler messageHandler = _httpMessageHandler();
        HttpMessageHandler innerHandler = messageHandler;
        while(innerHandler is DelegatingHandler)
        {
            DelegatngHandler dh = innerHandler as DelegatingHandler;
            innerHandler = dh.InnerHandler;
        }
        // Add some validation that innerHandler is HttpClientHandler and throw if it isn't.
        // There's an unlikely possibility the bottom handler could change type in a future .NET version, e.g. SocketsHttpHandler
        HttpClientHandler hch = innerHandler as HttpClientHandler;
        hch.Credentials = handler.Credentials;
        return messageHandler;
    }));
}
```
This basically traverses the wrapped message handlers and when it gets to the bottom (which should be HttpClientHandler), copies the credentials across.

### Wrap it with your own delegating handler
Because you are using basic authentication, you can actually very easily create your own delegating handler as the Basic auth mechanism is really simple.

```c#
internal class BasicAuthMessageHandler : DelegatingHandler
{
    public BasicAuthMessageHandler(ICredentials credentials, MessageHandler innerHandler) : base(innerHandler)
    {
        _credentials = credentials;
    }
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var creds = credentials.GetCredential(request.RequestUri, "Basic");
        string authHeaderStr = creds.UserName + ":" + creds.Password;
        string authHeaderBase64 = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(authHeaderStr));
        request.Headers.Authorization = new AuthenticationHeaderValue("Basic", authHeaderBase64);
        return base.SendAsync(request, cancellationToken);
    }
}
```

Then in AddBindingParameters you could do this:
```c#
public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
{
    bindingParameters.Add(new Func<HttpClientHandler, HttpMessageHandler>(handler => 
    {
        HttpMessageHandler messageHandler = _httpMessageHandler();
        return new BasicAuthMessageHandler(handler.Credentials, messageHandler);
    }));
}
```

That way you are wrapping the same message handler each time with your own message handler which handles the authentication. You can get away with a single instance for all usages as the credentials aren't being handled by the provided handler. You can only really do this for basic auth as it's so simple with no real edge cases. This will also send the credentials on the first request avoiding the round trip.

## Please note:
The first option is actually the better one as owning your own authentication implementation isn't the best idea, even if simple and trivial. But I don't know enough about HttpClientFactory to know how to make it give you a new instance every time.

**Comment by zumbuschms** [comment]
Thanks for clearing that up. I'd assumed that if I provide credentials to the WCF client, these credentials would be passed on to the HttpClient ignoring the source of the HttpClient. I'll try to check your suggestions but at the moment I had to skip using the WCF client as the Auto Discover WSDL seems to be broken to some extend.
