### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme Negotiate. The authentication header received from the server was Negotiate oX…Q=

### ISSUE THREAD

**Issue by tylerk2018** [dotnet/wcf#4692]
I am using a desktop application on a client pc to communicate with an IIS WCF web service running on a server, using WsHttpBinding to pass over the Windows user credentials. The application has worked well for many years, but now we are trying to have it communicate over HTTPS instead of just HTTP.

On the server side, we add an SSL certificate to the IIS website and change the WCF web.config to use Transport security for the binding definition:

      <wsHttpBinding>
        <binding name="WSHttpBinding_IService1">
          <readerQuotas maxArrayLength="2147483647" />
          <security mode="Transport" />
        </binding>
      </wsHttpBinding>
On the client side, the client object used to connect to the service uses Transport security mode to account for the HTTPS communication mode:

Dim serverURL as String = ReadServerURL()
Dim client As Service1Client
Dim binding As Channels.Binding
Dim dcso As ServiceModel.Description.DataContractSerializerOperationBehavior

binding = New WSHttpBinding("WSHttpBinding_IService1")

If serverURL.ToLower.StartsWith("https://") Then
  CType(binding, WSHttpBinding).Security.Mode = SecurityMode.Transport
Else
  CType(binding, WSHttpBinding).Security.Mode = SecurityMode.Message
End If

CType(binding, WSHttpBinding).Security.Message.ClientCredentialType = MessageCredentialType.Windows
CType(binding, WSHttpBinding).Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows 

binding.ReceiveTimeout = New TimeSpan(0, 10, 0)

client = New Service1Client(binding, New EndpointAddress(serverURL))

client.ClientCredentials.Windows.ClientCredential = CType(CredentialCache.DefaultCredentials, NetworkCredential)
client.ClientCredentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Delegation 
Some customers use Kerberos to pass the Windows credentials to another server, which is why we use Delegation.

Most customers have opted to use self-signed certificates because they are only using internal servers.

In IIS, the WCF site has Windows Authentication enabled, with both Negotiate and NTLM providers enabled.

enter image description here

This approach seems to work fine at most customer sites, but at least one is experiencing this error:

The HTTP request is unauthorized with client authentication scheme 'Negotiate. The authentication header received from the server was 'Negotiate oXlwcKADCgEBomkEZ2....oZSQ='.

I am not sure where this alternate 'Negotiate oXlwcK...' provider is coming from in IIS or how to configure the client to properly communicate with it. Is this an IIS configuration issue, an issue with the WCF service code and/or the client application code, or could it be a network/domain issue? Any help is greatly appreciated.

**Comment by mconnew** [comment]
Negotiate is the authentication scheme when using Kerberos based domain authentication. It's enabled when you turn on Windows authentication. The server on initial request returns a response saying that it needs to authenticate and will offer Negotiate or NTLM. The client is picking Negotiate (which can do Kerberos or NTLM) and attempting to authenticate. Configuring the client to use Transport security and specifying HttpClientCredentialType.Windows will tell the client to use Windows auth which will use the Negotiate scheme.  

I'm going to close this issue as your problem isn't related to the .NET Core WCF client and it a .NET Framework issue. This isn't the correct mechanism to get support for .NET Framework.
