### ISSUE TITLE
[.Net 5]- Nuget package 4.8.1 and 4.9.0-preview dll does n't have Basic256SecurityAlgorithmSuite

### ISSUE THREAD

**Issue by alavudeenb** [dotnet/wcf#4697]
Basic256SecurityAlgorithmSuite is not available in 4.8.1 and 4.9.0-preview dll. can someone throw somelight on how to access this class in .Net 5 Framework ?

**Comment by mconnew** [comment]
Default should be there, and that's basically an alias for Basic256.

**Comment by alavudeenb** [comment]
Please find below screenshot, which is taken from ILSpy tool. both 4.8.1 and 4.9.0-preview doesn't have it

![image](https://user-images.githubusercontent.com/56952115/130562731-00ab1bad-9d5f-4182-afc5-d569975397d6.png)

![image](https://user-images.githubusercontent.com/56952115/130562816-9a9f841d-5066-44ed-97d1-04b1b541c1d1.png)

**Comment by mconnew** [comment]
It's in the latest code base which will be released as part of RC1 in the coming weeks. See here:
https://github.com/dotnet/wcf/blob/main/src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs#L133-L135

But if you don't modify anything, the default value for SecurityBindingElement/TransportSecurityBindingElement is the Default value which is Basic256. Just don't set it explicitly and you will get what you want. In the next release you will be able to set it explicitly.

**Comment by alavudeenb** [comment]
@mconnew  can you please tell me when this will be released ? we are not able to move our solution to PROD.

**Comment by mconnew** [comment]
It's coming in the upcoming RC1 release. But you don't actually need it as the default is Basic256. If you don't explicitly set it, you get Basic256. You should be good to go with 4.8.1 leaving the default value as is.

**Comment by HongGit** [comment]
Feel free to reactivate the issue if this is still an issue.
