### ISSUE TITLE
WSDiscovery - Source code for older .NET Framework assemblies

### ISSUE THREAD

**Issue by InteXX** [dotnet/wcf#4701]
Where can I find the source code for `System.ServiceModel.Discovery` and `System.ServiceModel.Internal`? I need to migrate these to a .NET Standard 2.0 package for my own internal use.

Even better would be a public package that's already migrated, but if the source is all that's available I'll settle for that.

**Comment by mconnew** [comment]
You can find most of the source code at https://github.com/microsoft/referencesource  
If there's something missing please let us know and we can probably make it available. There's also https://referencesource.microsoft.com/ which helps with navigating around the code base. That's not a good place to copy code from as it's licensed under the Microsoft Reference Source license which is a look but don't copy license. The github repository is an MIT license so is fine to copy.  

The only reason I haven't ported that to Core yet is time and resources. If you would be interested in porting the System.ServiceModel.Discovery package to this repo, we would accept it and the code base would then be supported by Microsoft on an ongoing basis. Please don't feel obligated to do so, just looking for a win-win situation. I would be happy to support you in any difficulties or questions with porting if it's done in the open, even if it's in your own public repo.

**Comment by InteXX** [comment]
Thank you, I'll clone this tomorrow and attempt some builds.

I'll let you know how it goes.

**Comment by InteXX** [comment]
With 2,083 build errors between the two of them, I can see I've got my work cut out for me:

> https://github.com/InteXX/System.ServiceModel.Discovery
> https://github.com/InteXX/System.ServiceModel.Internals

...and I'm not even all that handy with C#. I'll give it my best, of course, but it's going to be a while.

**Comment by mconnew** [comment]
Don't worry about internals, that has etw logging and tracing code. There compatible code for most of that in system.private.servicemodel. Anything starting Fx. Should be copyable from there. Anything TD.Xxxxxx is now WcfEventSource.Instance.Xxxxxxx. Just comment that stuff out initially and we can sort out getting the correct events available later.

**Comment by InteXX** [comment]
Well, that knocks us down to 2,010.

I had included `Internals` because of `Discovery`'s dependence on it. Do you mean to say that we'll be eliminating the dependency during this project?

It's been my understanding that a .NET Framework assembly can depend on a .NET Standard assembly, but not the other way 'round. Please correct me if I'm mistaken in this.

**Comment by InteXX** [comment]
@mconnew 

Knowing the answers to these will assist my progress.

**Comment by mconnew** [comment]
Sorry, forgot to answer this sooner. The Internals assembly was shared among many other assemblies for a lot of the common code. There's no public api's in there. We had some assemblies which were server only such as ones related to activation. We also had Workflow, a bridge assembly that runs inside of the MSDTC process to provide WS-AT SOAP endpoint implementation and many others. None of those are relevant to this code base so we basically shoved it all in together. I've already made a common folder for a lot of this stuff when I created the S.SM.Federation package. Have a look at that project and look at the additional common include code sections of the project. That will give you most of what you will need from the Internals assembly. So the short answer is yes, Internals has gone away.  

You can actually go both ways with shims to some degree. You are aware of the simple case of being able to consume a netstandard2.0 targeted assembly from .NET Framework. In addition to that, you can consume some assemblies that target .NET Framework from .NET Core. There are shims shipped for many of the assemblies which are type forwarding facades which look like .NET Framework assemblies. So for example, if you had an assembly targeting .NET Framework called Foo.dll that uses System.ServiceModel.dll, depending on which API's are needed, you might be able to use it on .NET Core. We ship a System.ServiceModel.dll shim in our packages which type forwards all the supported types to System.Private.ServiceModel.dll. So when the CLR loads Foo.dll and there's a reference to ChannelFactory in an assembly called System.ServiceModel.dll, the type loader finds our shim System.ServiceModel.dll. That shim has a type forward for ChannelFactory which says the type now lives in System.Private.ServiceModel.dll, which is where the type loader will load it from. The same has been done for mscorlib and many other .NET Framework assemblies. If something hasn't been implemented in .NET Core, then you will get a runtime exception complaining about a missing type of missing method. But if it's there, this will work. But that's not a good idea to rely on for a library. I could maybe see it helping you as a stopgap solution to help get started porting code, but so far I haven't needed to do anything like that.

**Comment by InteXX** [comment]
Very good, thank you.

**Comment by A-Ovchinnikov-mx** [comment]
Hi @mconnew I've noticed that for .NET 6 some part of System.Web.Services library is being ported.

We currently use `DiscoveryClientProtocol` to discover WSDLs from a URL. Is there currently a recommended way to do so in .NET 6? For example, I found this extension: https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Extensions/HttpClientDiscoveryExtensions.cs

**Comment by HongGit** [comment]
Closing this as these issues will be grouped in @211.

**Comment by InteXX** [comment]
@HongGit 

The 211 link leads to a 404. Is this what you intended?

**Comment by Smartisa** [comment]
> Sorry, forgot to answer this sooner. The Internals assembly was shared among many other assemblies for a lot of the common code. There's no public api's in there. We had some assemblies which were server only such as ones related to activation. We also had Workflow, a bridge assembly that runs inside of the MSDTC process to provide WS-AT SOAP endpoint implementation and many others. None of those are relevant to this code base so we basically shoved it all in together. I've already made a common folder for a lot of this stuff when I created the S.SM.Federation package. Have a look at that project and look at the additional common include code sections of the project. That will give you most of what you will need from the Internals assembly. So the short answer is yes, Internals has gone away.
> 
> You can actually go both ways with shims to some degree. You are aware of the simple case of being able to consume a netstandard2.0 targeted assembly from .NET Framework. In addition to that, you can consume some assemblies that target .NET Framework from .NET Core. There are shims shipped for many of the assemblies which are type forwarding facades which look like .NET Framework assemblies. So for example, if you had an assembly targeting .NET Framework called Foo.dll that uses System.ServiceModel.dll, depending on which API's are needed, you might be able to use it on .NET Core. We ship a System.ServiceModel.dll shim in our packages which type forwards all the supported types to System.Private.ServiceModel.dll. So when the CLR loads Foo.dll and there's a reference to ChannelFactory in an assembly called System.ServiceModel.dll, the type loader finds our shim System.ServiceModel.dll. That shim has a type forward for ChannelFactory which says the type now lives in System.Private.ServiceModel.dll, which is where the type loader will load it from. The same has been done for mscorlib and many other .NET Framework assemblies. If something hasn't been implemented in .NET Core, then you will get a runtime exception complaining about a missing type of missing method. But if it's there, this will work. But that's not a good idea to rely on for a library. I could maybe see it helping you as a stopgap solution to help get started porting code, but so far I haven't needed to do anything like that.

Is there a good way to know which APIs are compatible and which are incompatible when interacting with different platforms?
Thanks!

**Comment by InteXX** [comment]
@HongGit 

We're getting a 404 when clicking the @211 link you've provided. Please advise.

**Comment by mconnew** [comment]
@InteXX, it was a typo, she typed an @ instead of an # so it tries to find a user called 211. I fixed her link to #211

**Comment by InteXX** [comment]
@mconnew 

Very good, thank you.
