### ISSUE TITLE
svcutil - Confusing message related to `--projectFile` option

### ISSUE THREAD

**Issue by savornicesei** [dotnet/wcf#4705]
Hi all!
I think this qualifies as a (funny) bug.

**Describe the bug**
Confusing message related to `--projectFile` option when trying to update a WCF reference in a C# project.

**To Reproduce**
I'm trying to update a WCF reference in a C# SDK-style project targeting .NET 4.8.
```
cd /d D:\Dev
dotnet new tool-manifest
dotnet tool install --local dotnet-svcutil --version 2.0.2
dotnet dotnet-svcutil --update "IfWebService" -pf "d:\Dev\some-other-folders\SomeService.csproj"
```
And the message I get is the following:
```
Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
[Microsoft.Tools.ServiceModel.Svcutil, Version 2.0.2]
Copyright (c) Microsoft Corporation.  All rights reserved.

Warning: The specified --projectFile option is not expected in the current operational context of the tool!
Error: The --update option requires a project to be specified, please use the --projectFile option to specify the project to use.

If you would like more help, type "dotnet-svcutil -h"
```

**Expected behavior**
A clear message about which of the parameters are incorrect or missing.

**Additional context**
It seems it has issues with the project file having a full path because changing the command to:
```
cd /d d:\Dev\some-other-folders
dotnet dotnet-svcutil --update "IfWebService" --projectFile "SomeService.csproj" --nologo --verbosity Verbose
```
returned 
```
Warning: The specified --projectFile option is not expected in the current operational context of the tool!                                                                                                                                                                               
Error: The specified web service reference 'IfWebService' was not found under the project 'd:\Dev\some-other-folders\SomeService.csproj'.  
```
The following command regenerated the WCF proxy class but still complained that "The specified --projectFile option is not expected in the current operational context of the tool"
```
cd /d d:\Dev\some-other-folders
dotnet dotnet-svcutil --update "Connected Services/IfWebService" --projectFile "SomeService.csproj" --nologo --verbosity Verbose
```

**Additional remarks**
The short forms of the parameters/commands are very hard to see. The standard is to display `short form|long form    explanation`, for example `-d | --outputDir <directory>          - Directory to create files in`.  
I would suggest using the [Sytem.CommandLine](https://www.nuget.org/packages/System.CommandLine/2.0.0-beta1.21308.1) package for command line parsing (and nice display of help text).

Thank you.

**Comment by imcarolwang** [comment]
Fix of the confusing `--projectFile option` issue is merged, the upcoming release should contain the fix. 
Regarding the additional remark in this issue description, we'll track in issue #4892.
