### ISSUE TITLE
How to connect to existing WCF service with clientCredentialType=="Windows"

### ISSUE THREAD

**Issue by D0ctorWh0** [dotnet/wcf#4716]
I am trying to connect to existing WCF service with NetTcpBinding and clientCredentialType set to "Windows" in message security. But it throws me error "clientCredentialType='Windows' not supported".

How can I connect to this existing WCF service? I can't change it.

**Comment by HongGit** [comment]
@D0ctorWh0 what security mode are you using, is it TransportWithMessageCredentials, or is it Message?
