### ISSUE TITLE
Cannot use "new" library in .net 4.8

### ISSUE THREAD

**Issue by Danielku15** [dotnet/wcf#4735]
**Describe the bug**
Currently the NuGet libraries provided by this project for .net 4.8 are forwarding the implementation to the System.ServiceModel coming with .net 4.8 itself. This makes migration really hard because there is no good way to already start using dotnet/wcf + CoreWCF already.

**To Reproduce**
1. Setup a .net 4.8 solution with a server and client project inside. 
2. Use CoreWCF for the server and the NuGet System.ServiceModel.* for the client
3. Notice that the NuGet Packages are actually causing a reference to the .net 4.8 built-in System.ServiceModel
4. Struggle migrating your code to the next-gen libraries to upgrade to .net core as a next step. 

**Expected behavior**
We need a way to enforce usage of the new client-side-only libraries through NuGet without pulling the full-framework WCF including the server parts. 

**Screenshots**

**Additional context**
We cannot yet change our project to actually be .net5.0 or .net6.0 due to a bigger scale rework ongoing which we need to do gradually across all our company wide products and libraries. We would like to first migrate to the new CoreWCF for Server and System.ServiceModel NuGets for client but stay on .net4.8.

Even if we make a .netstandard2.0 library project and consume the nugets and then use it in our main .net 4.8 application, the main application still pulls/references the .net 4.8 WCF libs. 

NuGet [does not provide a proper way](https://github.com/dotnet/sdk/issues/1791) to force usage of .netstandard2.0 libs for individual packages. There are only hacks where you need to spoil your whole solution tree with additional custom references. Therefore my hope lies here on the package authors side to provide a way to consume the new packages and provide a migration path away from the full framework WCF.

**Comment by mconnew** [comment]
Could you split the client code into a separate project which targets .NET Standard? It might be possible to run integration tests using it on .NET to validate the features you need are there.  
The only real concern as far as I can see is if there's a different behavior in the .NET Core implementation than in the .NET Framework implementation. These fall into 2 camps. First, a feature being absent and throwing. This can be mitigated with the separate project approach I mentioned earlier. The second is behavior differences which aren't immediately obvious. Being able to run the .NET Core version of the WCF client implementation on .NET Framework wouldn't completely solve this though. For example, we switched to using HttpClient in .NET Core. Running our packages on .NET Framework would mean we're using the .NET Framework version of HttpClient which wraps HttpWebRequest. Some of the bigger issues we've seen people hit are differences in implementation between HttpWebRequest on .NET Framework and SocketsHttpHandler on .NET Core. You still wouldn't be exposed to those differences if you ran the WCF Core client on .NET Framework. There are other subtle differences I've discovered, such as closing a Socket abandons pending writes on .NET Core, but on .NET Framework it waits for those writes before closing the socket. I have done everything I can to work around the behavior differences between the two platforms so generally you won't be exposed to those differences.  

One piece of advice I will give which you might not hit until too late is to go 100% async with WCF. We removed the sync implementation in the WCF Core client internally so the sync api's are all sync over async and can cause you scalability problems with extra threads. This isn't a problem with something like a desktop UI app, but for a middleware scenario, it can have an impact. Also explicitly open your channels before using them, and if using anything other than BasicHttpBinding or NetHttpBinding, open it async.

As you can see, even if we made it so you could use the .NET Core implementation on .NET Framework, you still won't see the same behavior as you would on .NET Core as our dependencies would have different behaviors. It's not an ideal situation, but it's the best of a set of possible solutions each with their own consequences. I try everything I can to get consistent behavior as far as possible though.
