### ISSUE TITLE
svcutil: System.NullReferenceException while generating duplex client

### ISSUE THREAD

**Issue by lipchev** [dotnet/wcf#4736]
**Describe the bug**
I'm receiving a `System.NullReferenceException` ([here](https://github.com/dotnet/wcf/blob/1a291ea424991a184ffafd2ba20928e0e339fb96/src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomHelpers.cs#L29)) while attempting to generate a duplex proxy in a `.net5.0` project.

It seems like the `"referenceKey"` field that is being targeted [here](https://github.com/dotnet/wcf/blob/1a291ea424991a184ffafd2ba20928e0e339fb96/src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomHelpers.cs#L28) is actually named  [s_referenceKey](https://github.com/dotnet/wcf/blob/1a291ea424991a184ffafd2ba20928e0e339fb96/src/dotnet-svcutil/lib/src/FrameworkFork/System.ServiceModel/System/ServiceModel/Description/ServiceContractGenerator.cs#L690).

**To Reproduce**
1. In Visual Studio 2019:  adding a reference to a duplex service (using the connected services wizard) produces no errors/warnings, but the generated proxy contains invalid annotations:     `[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]`
2. Running the command using the same tool version: `dotnet-svcutil -u "Connected Services\ChemTypesService" --verbosity Debug` lead me to:
`[29020.20] Importing metadata ...
Error: Object reference not set to an instance of an object.`
3. Finally, I got the trace from running the generated `SvcutilBootstrapper` project.
`"   at Microsoft.Tools.ServiceModel.Svcutil.CodeDomHelpers.get_ReferenceKey() in /_/src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomHelpers.cs:line 29"`

**Expected behavior**
The generated proxy contains no errors (a little message in visual studio in case of a failure would also be nice- I spent half a day looking for some nuget that I thought was missing- e.g. `System.CodeDom` seemed like a close match- so _there had to be_ something like that..)

**Additional context**
If I remove the callback interface the same process completes as expected.

**Comment by HongGit** [comment]
The change is in, waiting to release soon.

**Comment by imcarolwang** [comment]
The fix has been released to dotnet-svcutil, you can download the latest version of the tool from nuget.org to get the fix.  Closing issue.
