### ISSUE TITLE
CreateMutualCertificateBindingElement throw SecurityBindingElement.CreateMutualCertificateBindingElement is not supported.

### ISSUE THREAD

**Issue by DBA-org** [dotnet/wcf#4758]
not sure why but CreateMutualCertificateBindingElement isn't implmented in security:

   static public SecurityBindingElement CreateMutualCertificateBindingElement(MessageSecurityVersion version, bool allowSerializedSigningTokenOnReply)
        {
            if (version == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(nameof(version));
            }
            throw ExceptionHelper.PlatformNotSupported("SecurityBindingElement.CreateMutualCertificateBindingElement is not supported.");
        }

How can I use this secuirty biniding? what is the reason it's not supported? is there any implementation in older versions?
Pls advice, any idea, this is the only way I can consume this thrid party service.

**Comment by HongGit** [comment]
duplicate of #3424, CreateMutualCertificateBindingElement requires full message security, which is not planned yet in the near future.
