### ISSUE TITLE
Add Soap with Attachments / SwA-Support

### ISSUE THREAD

**Issue by AleMcKee** [dotnet/wcf#4764]
Currently there is no direct support for "Soap with Attachments". The only thing I could currently find was:

https://github.com/microsoftarchive/msdn-code-gallery-community-s-z/tree/master/Send%20Soap%20with%20Attachments%20using%20WCF

The code still works. However, I have to say that I'm not a fan of using code that was once part of an article and no longer receives any maintenance. Therefore I would be very happy if a native support for "Soap with Attachments" could be implemented.

Here are a few refs. to the spec.

https://www.w3.org/TR/SOAP-attachments/
https://www.w3.org/TR/soap12-af/

**Comment by benken-parasoft** [comment]
I am not sure .NET Web Services Enhancements (WSE) for .NET Framework 2.0 supported SwA let alone .NET Windows Communication Foundation (WCF) which was introduced for .NET Framework 3.0.  So, I imagine this would be a feature for supporting interoperability scenarios with early 2000s-era java-based SwA services (Apache Axis 1.x?).  Perhaps this could be done with some type of custom MessageEncodingBindingElement.  Not sure if anyone has attempted to write such a thing.

**Comment by mconnew** [comment]
Sorry for the really slow reply. I did go research this and learnt that SwA was dropped as a SOAP standard in favor of MTOM.  

The code linked to for a sample how to achieve this with WCF is still mostly valid for the WCF Client nuget packages. You would need to strip out the method overrides which are for Service side implementation (anything referencing IChannelListener), but other than that, the code should work the same.  

I'm closing this issue as we're not going to put support for this into the product.
