### ISSUE TITLE
Verbosity of generated code

### ISSUE THREAD

**Issue by Belorus** [dotnet/wcf#4769]
Hi,

I noticed that before dotnet-svcutil we wrote classes by hand, and models contained ~10-15times less lines. All properties were auto-properties. 

Eg, our hand-written model is 62 lines, and generated is 820.

What do you think, is it worth adding such mode that generates nice and human-friendly auto-properties instead of field+full property pairs?

**Comment by imcarolwang** [comment]
Hi @Belorus, thanks for your suggestion! Do you see a difference in lines of code generation between using Svcutil tool in .Net Framework platform and using dotnet-svcutil tool in .Net Core?

**Comment by HongGit** [comment]
Close this issue as no response, feel free to reactivate if this is still an issue.
