### ISSUE TITLE
API needs to be exposed

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#478]
1. For customer to use custom X509CertificateValidator validator, X509CertificateValidator needs to be exposed

**Comment by iamjasonp** [comment]
This should have been exposed already. Can you check that the test/test runtime is pulling the latest S.SM.Primitives? 

https://github.com/dotnet/wcf/blob/master/src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs#L8

**Comment by roncain** [comment]
@hongdai -- are you saying it does not compile in GitHub or TFS?  If TFS, I believe I resolved this yesterday by fixing the contract dependency order in the ToF wrappers.

**Comment by hongdai** [comment]
Verified resolved.
