### ISSUE TITLE
Hot to Get Started

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/wcf#4796]
I can't seem to find any docs regarding how to get started.  Where should I look?
I have a .NET 6.0 app that needs to talk with a WCF service that does not have a WSDL that I can access.  What is the best way for me to send and receive messages?

**Comment by HongGit** [comment]
@TonyValenti do you have a copy of the service interface.  The suggestion is to use the same service interface.

**Comment by HongGit** [comment]
Closing this as no response, feel free to reactivate if help is still needed.
