### ISSUE TITLE
Help - Using manually compiled dll instead of nupkg breaks at compile time

### ISSUE THREAD

**Issue by leocb** [dotnet/wcf#4798]
Hi, due to company policies, I can't use Nuget packages on shipping products and must compile all libraries myself and use the DLLs I generated. **This policy not negotiable**, believe me, I tried.

I was able to compile the all the libs successfully.

The project is targeting .NET6

While developing (And this setup is working flawlessly) I was using the nuget packages, as follows:
```xml
<PackageReference Include="System.ServiceModel.Http" Version="4.9.0" />
<PackageReference Include="System.ServiceModel.NetTcp" Version="4.9.0" />
<PackageReference Include="System.ServiceModel.Security" Version="4.9.0" />
```

Now for the release version I need to replace those nugets with the dll files I manually compiled, and as I discovered, all the dependencies they have too, my setup now looks like this:
```xml
<!-- All dlls are from the net6 folder, except when they don't have a net6 specific version, then i used the netstandard2.1 -->
<Reference Include="System.ServiceModel.Http">
    <HintPath>..\packages\System.ServiceModel.Http.dll</HintPath>
</Reference>
<Reference Include="System.ServiceModel.NetTcp">
    <HintPath>..\packages\System.ServiceModel.NetTcp.dll</HintPath>
</Reference>
<Reference Include="System.ServiceModel.Primitives">
    <HintPath>..\packages\System.ServiceModel.Primitives.dll</HintPath>
</Reference>
<Reference Include="System.ServiceModel.Security">
    <HintPath>..\packages\System.ServiceModel.Security.dll</HintPath>
</Reference>
<Reference Include="Microsoft.Bcl.AsyncInterfaces"><!-- From dotnet/runtime -->
    <HintPath>..\packages\Microsoft.Bcl.AsyncInterfaces.dll</HintPath>
</Reference>
```

With this dll setup I get errors in compile time like these:
![image](https://user-images.githubusercontent.com/8310271/156849732-bda080a8-451a-4edf-9bf5-355165c4a568.png)

But if I navigate to the symbol that issues this error and press F12, Visual studio is able to find the references without any problem.

What am I missing and how could I solve it?

Thank you in advance!

**Comment by mconnew** [comment]
I believe the problem you are hitting is the compile time assets are different than the runtime assets. When compiling, you need to reference the dll's in either ref\net6.0 or ref\netstandard2.0 of the packages. But you don't copy them to your application folder as they are reference assemblies only. What you need to copy is the dll's in lib\net6.0 or lib\netstandard2.0 of the System.ServiceModel.* packages. These are type forwarding facades which point to the implementation assembly. You also need System.Private.ServiceModel.dll (the implementation assembly) from the same named package from the lib\netstandard2.0 folder.  

You could potentially make things easier by doing none of that and just directly referencing the System.Private.ServiceModel.dll, but there is a potential gotcha with that. That assembly has some api's which are public, but aren't in the reference assemblies. If you inadvertently use one of those api's and then have a problem with it, support is going to be tricky as non-public api's aren't technically supported and those api's are considered non-public as they don't appear in any reference assemblies.

**Comment by leocb** [comment]
Using only System.Private.ServiceModel.dll directly solved my issues for now. But I still have to validate if everything is working as expected. Thank you!

**Comment by mconnew** [comment]
I'm closing this issue. If you need any further help, please open a new issue.
