### ISSUE TITLE
NetTcp transport security server certificate X509CertificateValidationMode P1 pivots

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#480]
P0 scenario tests have been covered, add tests that pivot on the following X509CertificateValidationModes...

X509CertificateValidationMode.PeerTrust
X509CertificateValidationMode.ChainTrust
X509CertificateValidationMode.PeerOrChainTrust

**Comment by zhenlan** [comment]
X509CertificateValidationMode.ChainTrust is covered by default already.

**Comment by StephenBonikowsky** [comment]
Tests have already been added for ChainTrust.
PeerTrust is currently not supported, @iamjasonp does it have anything to do with MessageSecurity? As far as I have been able to tell the primary difference is that it will look for the cert in "TrustedPeople" store, so should it not work with SecurityMode.Transport?
For PeerOrChainTrust, I am adding a test that should pass based on ChainTrust.

**Comment by StephenBonikowsky** [comment]
Update...
PeerOrChainTrust is also throwing a PlatformNotSupported, looking into the code it seems like this could be modified so that if this enum is used we check to see if the ChainTrust path will work and then continue not just throw automatically because it isn't explicitly ChainTrust.

**Comment by StephenBonikowsky** [comment]
Final Update...
PeerTrust cannot be supported as it depends on a Windows component that no longer exists on Windows 10 and above.

PeerTrust has been obsoleted on the full framework.
Will open a new Issue for this to be obsoleted in .NetCore.

**Comment by iamjasonp** [comment]
Sorry, earlier when we chat I misheard "PeerTrust" as "PeerChannel" so was basing my answers on that. PeerTrust hasn't been deprecated or removed, and should be supported in Windows too.

**Comment by StephenBonikowsky** [comment]
Ok then.

@zhenlan you mentioned elsewhere manual verifying this, but to be clear we are throwing PlatformNotSupported so it has to be enabled first.

I will use this Issue to get the tests created and open another Issue to enable the feature.

**Comment by zhenlan** [comment]
According to @StephenBonikowsky the feature won't work even with manual setup, so yes, the plan sounds good to me. Thanks!

**Comment by StephenBonikowsky** [comment]
Opened Issue  #1192 to investigate this scenario for http.
