### ISSUE TITLE
RPC Message "MessageName" in operation "OperationName" has an invalid body name "TypeNameResponse". It must be "OperationNameResopnse"

### ISSUE THREAD

**Issue by akghasemi** [dotnet/wcf#4803]
I am working with old soap web service and I am facing this error ,it works fine in .net framework but this error appears in .net core:
"RPC Message writeSettingResponse in operation startInit has an invalid body name writeSettingResponse. It must be startInitResponse
"
I have read some suggestions that to change the contract name to match this but the problem is that I have tones of method that only return on types and when  I change the contract name another method complains about the same problem and it is not possible to set multiple contract name for one class.
is there any generic soultions for this

**Comment by HongGit** [comment]
@akghasemi are you working on WCF client on .NET framework, or SOAP client on .NET framework?

**Comment by akghasemi** [comment]
It is just asp.net core applications and I am using the code that is being generated by WCF util in visual studio,

**Comment by HongGit** [comment]
@akghasemi can you please share the wsdl you are using?

**Comment by HongGit** [comment]
Sorry, we can't investigate this further without the wsdl.  Feel free to re-activate once you could provide the wsdl.

**Comment by jeffreytobin** [comment]
Hello, I'm having the same issue "RPC Message assetOwnerListRequest1 in operation assetOwnerList1 has an invalid body name assetOwnerList. It must be assetOwnerList1". I have attached the .wsdl  

I was able to get code generated by another of their .wsdl files to work by removing 1 of 2 methods, but this one has too many to remove them manually.

Please let me know if you have further questions.

Thanks,
Jeff
[Configurator.zip](https://github.com/dotnet/wcf/files/8786907/Configurator.zip)
