### ISSUE TITLE
WCF reference generated with dotnet-svcutil 2.0.3 uses wrong namespace attributes

### ISSUE THREAD

**Issue by ciceroneves** [dotnet/wcf#4807]
When I attempt to add reference to a WCF service using dotnet-svcutil 2.0.3 it creates classes with the attribute
`[Microsoft.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]`

This is different from the reference to the same service generated using version 2.0.2 of the tool
`[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]`

VisualStudio complains that the Microsfot.CodeDom namespace cannot be found which makes me believe this is some kind of internal namespace not intended to be exposed to consumers

The command I ran to generate the reference in Powershell is
`dotnet-svcutil  'url-of-wcfservice'`

**Comment by imcarolwang** [comment]
@ciceroneves , I ran 2.0.3 version of dotnet-svcutil tool against a simple WCF service url and I couldn't reproduce the issue. Can you provide a sample url or wsdl file that can reproduce the problem?

**Comment by HongGit** [comment]
Feel free to reactivate if the issue still persists and a simple repro is provided.
