### ISSUE TITLE
Question: What happens if a wcf connection/channel is not closed.

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [dotnet/wcf#4810]
There is this recommendation to always close the channel after work is completed. This is understandable.

However, I'm trying to understand what happens if we don't or in certain scenarios the objects are not correctly disposed(and closed eventually),

This is good (per recommendation)
```csharp
var myClient = ChannelFactoryManager.CreateChannel(); // Assume ChannelFactoryManager has an active and reusable instance of ChannelFactory<FooServiceClient> which uses NetTcpBinging
// do work with channel
var data = myClient.GetSomeData();
((IChannel)channel).Close(); // Or a graceful close with try catches to prevent circumvent unintended states
return data;
```

What would happen in the situation below? Is it fair to confirm that consistent calls such as this would then leave TCP connections in a Bound state on the machine and never ever get killed and eventually lead to port exhaustion?

```csharp
var channel = ChannelFactoryManager.CreateChannel(); // Assume ChannelFactoryManager has an active and reusable instance of ChannelFactory<T> which uses NetTcpBinging
// do work with channel
var data = myClient.GetSomeData();
// do not close, just exit this code block. 
return data;
```

Considering that this could lead to significant issues, is it possible for some finalization implementation in the base classes to ensure that when garbage collection happens, we close the connection? 

So, something like,
```csharp
~ServiceChannel()
{
    Close();
}
```

Please pardon me if `ServicChannel` is not a right place to put this. My question is more about the idea of some finalizer implementation or clean up mechanism, if consumer missed closing connections.

**Comment by EmmanuelPonnudurai** [comment]
Thank you for the detailed explanation @mconnew I missed the part about the internal collection which holds the created channels and yes, if that's the case, we can't do a finalizer on the wcf side and must be implemented by the consuming side.

**Comment by mconnew** [comment]
I'm closing this issue as I don't believe there's anything left pending that needs addressing.
