### ISSUE TITLE
Error while trying to add wcf reference in VS 2022

### ISSUE THREAD

**Issue by vvenkataratnam** [dotnet/wcf#4811]
Hi, I am using VS 2022 (17.1.4) with.NET Core 6.0 to add a Service Reference using Manage Connected Services.
I can see the service is running and access the WSDL using browser.

I am getting following error, while trying to add a reference

![image](https://user-images.githubusercontent.com/57880936/163700021-45af3d6a-58dd-45b8-9bed-b6038824fc25.png)

**Comment by imcarolwang** [comment]
@vvenkataratnam  Thank you for filing the issue. Could you provide the repro service wsdl or a simplified one which reproduces this error?

**Comment by vvenkataratnam** [comment]
Hi @imcarolwang,
Initially I was trying add a reference to a class library, which was giving this error. Later, I tried with Console app and it worked fine. Sorry for the confusion.

**Comment by damien-r** [comment]
Hi,
If this can help someone: I had the same issue and found it was because of the name I gave to my Service reference. Maybe it has a size limit.

**Comment by jrpacheco** [comment]
> Hi @imcarolwang, Initially I was trying add a reference to a class library, which was giving this error. Later, I tried with Console app and it worked fine. Sorry for the confusion.

Hi, How do you resolved this problem?
