### ISSUE TITLE
dotnet-svcutil - ability to ignore certficate error when generating code

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/wcf#4818]
Would like the ability to ignore certificate errors when generating c# from the command line tool. I have over a hundred WCF endpoints that I update through a powershell script for every version of a system we use and clicking accept for the certficate warnings would be nice to avoid with a switch to the tool.

**Comment by HongGit** [comment]
@johanskoldekrans  does this behavior repro on .NET framework?  If not, is it possible for you to share a simple repro with us?

**Comment by johanskoldekrans** [comment]
`[CmdletBinding()]
Param(
    [switch]
    $BaseServices,

    [switch]
    $Services,

    [switch]
    $ValidationEngineServices
)

function Write-Bar()
{
    Write-Host
    Write-Host "******************************************************" -ForegroundColor White
    Write-Host
}

function Generate-Services($serviceCategory)
{
    $serviceListFilePath = "$PSScriptRoot/_ServiceLists/"

    Switch ($serviceCategory)
    {
        "BaseServices"
        {
            $serviceListFilePath += "BaseServiceList.txt"
            $baseUrl = "https://198.193.172.57/AbaSecServicesEPB"
        }
        "Services"
        {
            $serviceListFilePath += "ServiceList.txt";
            $baseUrl = "https://198.193.172.57/AbaSecuritiesServicesEPB"
        }
        "ValidationEngineServices"
        {
            $serviceListFilePath += "ValidationEngineServiceList.txt"
            $baseUrl = "https://198.193.172.57/ValidationEngineServicesEPB"
        }
        default
        {
            throw "Invalid service category: '$serviceCategory'"
        }
    }

    $servicesFileContent = Get-Content -Path $serviceListFilePath
    $servicesFolderPath = "$PSScriptRoot/$serviceCategory"
    $stagingFileName = "_CurrentService.cs"

    Write-Bar

    $counter = 0
    $successfulCounter = 0;
    $failedServices = @();

    $services = @()

    # Exclude commented lines or part of lines, '#' is used as a commenting character
    $servicesFileContent | ForEach-Object {
        $serviceName = $_.Split('#')[0].Trim()
        if (($null -ne $serviceName) -and ($serviceName -ne '')) { $services += $serviceName }
    }

    $services | ForEach-Object {
        $counter++

        $serviceName = $_
        $serviceUrl = "$baseUrl/$serviceName`?wsdl"

        if ($serviceName.EndsWith('.svc'))
        {
            $serviceName = $serviceName.Substring(0, $serviceName.Length-4)
        }

        Write-Host "Generating code for service: " -NoNewline
        Write-Host $serviceName -ForegroundColor Cyan -NoNewline
        Write-Host " ($counter/$($services.Length))"
        Write-Host

        if (Test-Path "$servicesFolderPath/$stagingFileName")
        {
            Remove-Item $servicesFolderPath/$stagingFileName -Force
        }

        $cmdLine = "dotnet svcutil $serviceUrl --outputFile $stagingFileName --outputDir $servicesFolderPath --namespace *,AbaSecService.$serviceCategory.$serviceName"

        Write-Host "Executing command: "
        Write-Host $cmdLine -ForegroundColor Cyan
        Write-Host

        Invoke-Expression $cmdLine

        if ($LASTEXITCODE -ne 0)
        {
            Write-Host
            Write-Host "Failed to generate service!" -ForegroundColor Red
            Write-Bar

            $failedServices += $serviceName

            return
        }

        $stagingFilePath = "$servicesFolderPath/$stagingFileName"
        $destinationFilePath = "$servicesFolderPath/$serviceName.cs"

        Write-Host "Renaming " -NoNewline
        Write-Host $stagingFilePath -ForegroundColor Cyan -NoNewline
        Write-Host " to " -NoNewline
        Write-Host $destinationFilePath -ForegroundColor Cyan

        Move-Item -Path $stagingFilePath -Destination $destinationFilePath -Force
        Write-Host
        Write-Host "Successfully generated service!" -ForegroundColor Green
        Write-Bar

        $successfulCounter += 1
    }

    Remove-Item "$servicesFolderPath/dotnet-svcutil.params.json" -Force

    Write-Host "Successfully generated $successfulCounter out of $counter services" -ForegroundColor Green
    Write-Host

    if ($failedServices.Length -gt 0)
    {
        "The following services could not be generated:"
        $failedServices | ForEach-Object {
            Write-Host $_ -ForegroundColor Red
        }
    }

    Write-Host
}

Push-Location $PSScriptRoot

dotnet tool install --global dotnet-svcutil
$startTime = [System.Diagnostics.Stopwatch]::StartNew()

$anyAction = $false

if ($Services)
{
    Generate-Services("Services")
    $anyAction = $true
}
if ($BaseServices)
{
    Generate-Services("BaseServices")
    $anyAction = $true
}
if ($ValidationEngineServices)
{
    Generate-Services("ValidationEngineServices")
    $anyAction = $true
}

if (-not $anyAction)
{
    $scriptName = $MyInvocation.MyCommand.Name
    Write-Host "Please specify which service category to generate.`n"
    Write-Host "Example: $scriptName -BaseServices -Services -ValidationEngineServices`n"
    throw "Error"
}

$elapsedTime = $startTime.Elapsed
Write-Host "Elapsed time: " -NoNewline
Write-Host $([string]::Format("{0:d2}:{1:d2}:{2:d2}",
                        $elapsedTime.hours,
                        $elapsedTime.minutes,
                        $elapsedTime.seconds)) -ForegroundColor Magenta
Write-Host

Pop-Location
`

Above is the powershell we are using. Below is what I am trying to avoid
![image](https://user-images.githubusercontent.com/18699147/175915030-94bea695-a755-42d8-8369-079c5bc3f6d1.png)

**Comment by imcarolwang** [comment]
We have released a fix to address the reported issue, a brief description of the fix usage is showed below as a reference, you can install the latest version of dotnet-svcutil from nuget.org, type "dotnet svcutil -h" for more details and try it out.

```
--acceptCertificate    - Accept remote certificate as trusted when downloading service metadata. (Short
                                            Form: -ac)
```
