### ISSUE TITLE
Expected Release: 2nd Quarter 2020 hey you guys awake? Anyone here? Any plans on fixing the re-use bug.

### ISSUE THREAD

**Issue by brewfreedom** [dotnet/wcf#4829]
Having major issues as a result of the assembly reuse feature not working. How about at least updating your release schedule since you blew that by a year +.

**Comment by HongGit** [comment]
@brewfreedom thanks for your feedback!

Do you have any particular issue you would like to raise with us?

**Comment by brewfreedom** [comment]
Nope. Just looking at the assembly reference reuse bug in svcutil 4829 which I assume is the same as this that has been sitting out there a long time. https://github.com/dotnet/wcf/issues/4277

**Comment by imcarolwang** [comment]
Thanks for the feedback! We are actively working on the next release which will be coming soon. Regarding issue 4277, the behavior is not a regression from svcutil.exe, we will treat it as an enhancement for future consideration.

I am closing this one as it doesn't track a specific issue.
