### ISSUE TITLE
ChannelFactory construct with configuration name throws PlatfromNotSupported exception

### ISSUE THREAD

**Issue by hatzhang** [dotnet/wcf#4840]
I have the following config files on the client side.
```
WCFClients.config
WCFBindings.config
WCFBehaviours.config
```
Under net48, i can use the following code to create ChannelFactory with all the bindings and behaviours, the endpointConfigurationName is specified in WCFClients.config.
```
new ChannelFactory<T>(endpointConfigurationName);
```
But when run under net5, i got this PlatfromNotSupported exception.
So what's the right way to construct ChannelFactory with these configuration files under net5/6.

**Comment by HongGit** [comment]
@hatzhang please check out https://github.com/twsouthwick/ServiceModel.Configuration, which is use your best bet.
