### ISSUE TITLE
BUG: Could not load type System.ServiceModel.Description.IWsdlExportExtension from assembly System.ServiceModel

### ISSUE THREAD

**Issue by ffruylan03** [dotnet/wcf#4842]
I have created a .NET framework 4.8 library class where I access and manipulated the WSDL service. And created a Unit Test for that service with the same .NET framework 4.8 and it work's well. Now, I have an existing .NET 5 framework (ASP.NET CORE) project and I reference this service (.NET framework service), and when I access the method in it I always get an error message: 

`System.TypeLoadException : Could not load type 'System.ServiceModel.Description.IWsdlExportExtension' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

I already added these [5 facade packages](https://github.com/dotnet/wcf#wcf-library-components) and still, the error occurred.

Any help is very much appreciated. Thank you.

**Comment by HongGit** [comment]
@ffruylan03 we don't support IWsdlExportExtension as that is server side capability, this WCF Core repo is a client library.  

Best option is to multi-target your code and use conditional compilation to exclude this functionality when building for .NET 5.0.
