### ISSUE TITLE
.net wcf digest performance problem

### ISSUE THREAD

**Issue by HekunX** [dotnet/wcf#4844]
**Describe the bug**
it is very slow to remote call onvif  in .net6 but fast in .net472.
**To Reproduce**
```
var binding = new BasicHttpBinding();
CustomBinding customBinding = new CustomBinding(binding);
foreach (var el in customBinding.Elements)
{
    if (el is HttpTransportBindingElement httpTransport)
    {
        //httpTransport.AuthenticationScheme = AuthenticationSchemes.Digest;
    }
    else if (el is TextMessageEncodingBindingElement encoding)
    {
        encoding.MessageVersion = MessageVersion.Soap12WSAddressing10;
    }
}

DeviceClient deviceClient = new DeviceClient(customBinding, new EndpointAddress("http://192.168.1.224/onvif/device_service"));
//deviceClient.ClientCredentials.HttpDigest.ClientCredential = new NetworkCredential("admin", "hik111111");
var res1 = await deviceClient.GetNetworkInterfacesAsync();
var rees2 = await deviceClient.GetNetworkInterfacesAsync();

Console.WriteLine("down");
```

**Additional context**
OS:Winodws11
SDK:.Net6

**Comment by HongGit** [comment]
@mconnew could you please comment?

**Comment by mconnew** [comment]
I have a suspicion of what's going on here, but I'll need you to capture the requests using Fiddler to verify. On .NET Framework we set HttpWebRequest.PreAuthenticate to true, and on .NET Core we set HttpClientHandler.PreAuthenticate to true. My understanding is that they have subtly different behaviors. This is from memory of an issue I investigated a few years ago which is why it needs to be validated. I believe on .NET Framework, when you set PreAuthenticate to true it sends the first request with Content-Length header set to 0 to have the server reply with the authentication challenge (needed for Digest). The reason for this is that the entire request body needs to be sent even if the server has already replied with the response header containing the challenge. By setting the content length to 0, it avoids needing to send the entire request body when getting the authentication challenge. Once it has the authentication challenge it can send the actual request body with the authentication header in a new request.  
I know this was an issue with Windows authentication with NTLM, so I believe it would apply to Digest too. On .NET Core I believe it sends the initial unauthenticated request with the actual content length and needs to send the entire request body. This causes an initial delay before the subsequent request can be sent with the correct authentication header.  

The verification I need from you is to use Fiddler and look at the initial unauthenticated request which is sent to the camera from .NET Framework and then from .NET Core and see if this is what's happening. Check to see if there's a request body sent on the initial unauthenticated request. Another useful datapoint is to check to see if the slower performance is only on the first request with a client or also on subsequent requests.

**Comment by HekunX** [comment]
> @mconnew could you please comment?

Sorry,Different time zones.

**Comment by HekunX** [comment]
> I have a suspicion of what's going on here, but I'll need you to capture the requests using Fiddler to verify. On .NET Framework we set HttpWebRequest.PreAuthenticate to true, and on .NET Core we set HttpClientHandler.PreAuthenticate to true. My understanding is that they have subtly different behaviors. This is from memory of an issue I investigated a few years ago which is why it needs to be validated. I believe on .NET Framework, when you set PreAuthenticate to true it sends the first request with Content-Length header set to 0 to have the server reply with the authentication challenge (needed for Digest). The reason for this is that the entire request body needs to be sent even if the server has already replied with the response header containing the challenge. By setting the content length to 0, it avoids needing to send the entire request body when getting the authentication challenge. Once it has the authentication challenge it can send the actual request body with the authentication header in a new request. I know this was an issue with Windows authentication with NTLM, so I believe it would apply to Digest too. On .NET Core I believe it sends the initial unauthenticated request with the actual content length and needs to send the entire request body. This causes an initial delay before the subsequent request can be sent with the correct authentication header.
> 
> The verification I need from you is to use Fiddler and look at the initial unauthenticated request which is sent to the camera from .NET Framework and then from .NET Core and see if this is what's happening. Check to see if there's a request body sent on the initial unauthenticated request. Another useful datapoint is to check to see if the slower performance is only on the first request with a client or also on subsequent requests.

Ok!I will use wireshark to test right now.

**Comment by HekunX** [comment]
### Enable Digest Auth 
#### Net6
![image](https://user-images.githubusercontent.com/52776319/174206501-6ec32887-1a3c-4d5c-98d4-5c01adac1c84.png)
```C#
var binding = new BasicHttpBinding();
CustomBinding customBinding = new(binding);
foreach (var el in customBinding.Elements)
{
    if (el is HttpTransportBindingElement httpTransport)
    {
        httpTransport.AuthenticationScheme = AuthenticationSchemes.Digest;
    }
    else if (el is TextMessageEncodingBindingElement encoding)
    {
        encoding.MessageVersion = MessageVersion.Soap12WSAddressing10;
    }
}

DeviceClient deviceClient = new DeviceClient(customBinding, new EndpointAddress("http://192.168.1.224/onvif/device_service"));
deviceClient.ClientCredentials.HttpDigest.ClientCredential = new NetworkCredential("admin", "hik111111");

for(int i = 0; i < 5; i++)
{
     await deviceClient.GetNetworkInterfacesAsync();
}
```
#### Net472
![image](https://user-images.githubusercontent.com/52776319/174207381-bcf79ccc-fdce-4a9b-a098-e021341e0175.png)
```c#
            var binding = new BasicHttpBinding();
            CustomBinding customBinding = new CustomBinding(binding);
            foreach (var el in customBinding.Elements)
            {
                if (el is HttpTransportBindingElement httpTransport)
                {
                    httpTransport.AuthenticationScheme = AuthenticationSchemes.Digest;
                }
                else if (el is TextMessageEncodingBindingElement encoding)
                {
                    encoding.MessageVersion = MessageVersion.Soap12WSAddressing10;
                }
            }

            DeviceClient deviceClient = new DeviceClient(customBinding, new EndpointAddress("http://192.168.1.224/onvif/device_service"));
            deviceClient.ClientCredentials.HttpDigest.ClientCredential = new NetworkCredential("admin", "hik111111");
            deviceClient.ClientCredentials.HttpDigest.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
            for (int i = 0; i < 5; i++)
            {
                 deviceClient.GetNetworkInterfaces();
            }
```
### Disable Digest Auth
#### Net6
![image](https://user-images.githubusercontent.com/52776319/174207956-6c66c2be-c2e2-40bb-8e3b-d286199e067e.png)
```C#
var binding = new BasicHttpBinding();
CustomBinding customBinding = new(binding);
foreach (var el in customBinding.Elements)
{
    if (el is HttpTransportBindingElement httpTransport)
    {
        //httpTransport.AuthenticationScheme = AuthenticationSchemes.Digest;
    }
    else if (el is TextMessageEncodingBindingElement encoding)
    {
        encoding.MessageVersion = MessageVersion.Soap12WSAddressing10;
    }
}

DeviceClient deviceClient = new DeviceClient(customBinding, new EndpointAddress("http://192.168.1.224/onvif/device_service"));
//deviceClient.ClientCredentials.HttpDigest.ClientCredential = new NetworkCredential("admin", "hik111111");

for(int i = 0; i < 5; i++)
{
    try
    {
        await deviceClient.GetNetworkInterfacesAsync();
    }
    catch 
```
#### Net472
![image](https://user-images.githubusercontent.com/52776319/174208756-8d55b0ac-9408-43bd-92d5-8c0249d152db.png)
```C#
            var binding = new BasicHttpBinding();
            CustomBinding customBinding = new CustomBinding(binding);
            foreach (var el in customBinding.Elements)
            {
                if (el is HttpTransportBindingElement httpTransport)
                {
                    //httpTransport.AuthenticationScheme = AuthenticationSchemes.Digest;
                }
                else if (el is TextMessageEncodingBindingElement encoding)
                {
                    encoding.MessageVersion = MessageVersion.Soap12WSAddressing10;
                }
            }

            DeviceClient deviceClient = new DeviceClient(customBinding, new EndpointAddress("http://192.168.1.224/onvif/device_service"));
            //deviceClient.ClientCredentials.HttpDigest.ClientCredential = new NetworkCredential("admin", "hik111111");
            deviceClient.ClientCredentials.HttpDigest.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
            for (int i = 0; i < 5; i++)
            {
                try
                {
                    deviceClient.GetNetworkInterfaces();
                }
                catch { }
                 
            }
```

**Comment by HekunX** [comment]
I download source code to debug and find this.
### the first request
![image](https://user-images.githubusercontent.com/52776319/174212385-483571c9-8965-4c6e-800c-74c35e43cd4a.png)
![image](https://user-images.githubusercontent.com/52776319/174212872-2f6a5fca-ea8d-4883-9936-aaf3a179d88b.png)
it cost not more than 1.5 seconds in network.
### the next request
![image](https://user-images.githubusercontent.com/52776319/174213492-b083fd8d-c309-434c-aafe-7b599253ebf1.png)

**Comment by HekunX** [comment]
![image](https://user-images.githubusercontent.com/52776319/174215156-84382198-87da-4889-8796-a810ca8c9e95.png)
It will be normal if add this to source code.
```C#
_httpClient.DefaultRequestHeaders.ExpectContinue = false;
```

**Comment by mconnew** [comment]
This means the HTTP server on the camera isn't fully compliant with the HTTP/1.1 spec. When an Expect header is sent the body isn't initially sent. It's supposed to reply with a `100 Continue` response after which the client will send the request body. To account for non-compliant servers, the http client will send the body anyway if it hasn't received the `100 Continue` response within a certain period of time. On .NET Framework I believe this delay was 350ms, and on .NET Core the http client uses a longer time. 1 second I think. When the server doesn't support this feature of HTTP/1.1, you will get a longer delay on .NET Core than you had on .NET Framework.  

Someone has written a great blog post on how to modify the behavior of WCF on ,NET Core to disable the Expect header. You can find it here: https://justsimplycode.com/2019/11/02/disable-header-100-continue-in-net-core-wcf-client/

**Comment by HekunX** [comment]
> This means the HTTP server on the camera isn't fully compliant with the HTTP/1.1 spec. When an Expect header is sent the body isn't initially sent. It's supposed to reply with a `100 Continue` response after which the client will send the request body. To account for non-compliant servers, the http client will send the body anyway if it hasn't received the `100 Continue` response within a certain period of time. On .NET Framework I believe this delay was 350ms, and on .NET Core the http client uses a longer time. 1 second I think. When the server doesn't support this feature of HTTP/1.1, you will get a longer delay on .NET Core than you had on .NET Framework.
> 
> Someone has written a great blog post on how to modify the behavior of WCF on ,NET Core to disable the Expect header. You can find it here: https://justsimplycode.com/2019/11/02/disable-header-100-continue-in-net-core-wcf-client/

It works.Thanks a lot!
