### ISSUE TITLE
X509CertificateValidator Validate method not being called.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#485]
Two scenario tests, one positive and one negative show that the Validate method derived from the X509CertificateValidator class is not getting called by the WCF product code.

Test Cases are:
- Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_CustomValidator_EchoString
- Security.TransportSecurityClient.ExpectedExceptionTests.TcpClientCredentialType_Certifiacte_CustomValidatorFail_EchoString

**Comment by hongdai** [comment]
The failures are test issues to me. The tests set 
Authentication.CertificateValidationMode to None, it needs to be set to Custom to hook up the custom validator.

**Comment by StephenBonikowsky** [comment]
Correct, I managed to lose that setting between desktop and OSS, thanks for catching that Hong.
