### ISSUE TITLE
Getting timeout exception when calling HttpClientCredentialType.Windows from linux against windows hosted WCF.

### ISSUE THREAD

**Issue by dalibor-sanzeru** [dotnet/wcf#4860]
Client calls WCF server which uses BasicHttpBindig:
```
            var binding = new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly);
            binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
            var client = new MyWebServiceClient(binding, new EndpointAddress(this.config.Url));
            client .ClientCredentials.Windows.ClientCredential = new NetworkCredential(this.config.UserName, this.config.Password, this.config.Domain);
```

Calls from WINDOWS->WINDOWS machine pass and data are returned.
Calls from LINUX (DOCKER) -> WINDOWS machine timeouts with following message:

.NET CORE 3.1.4

_The request channel timed out attempting to send after 00:01:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout., The HTTP request to 'http://10.100.169.64:8030/WcfService/MyWebService/' has exceeded the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout._

Server WCF setup follows:
<bindings>

```
      <basicHttpBinding>

        <binding name="webServiceBinding" maxReceivedMessageSize="2147483647">

          <readerQuotas maxDepth="999"

                        maxStringContentLength="2147483647"

                        maxArrayLength="2147483647"

                        maxBytesPerRead="2147483647"

                        maxNameTableCharCount="2147483647" />

          <security mode="TransportCredentialOnly">

            <transport clientCredentialType="Windows" />

          </security>

        </binding>

      </basicHttpBinding>

```

So the question would be if  HttpClientCredentialType.Windows is supported from linux.

Thanks for help,
Dalibor.

**Comment by HongGit** [comment]
@dalibor-sanzeru could you please try to make sure that your linux machine is domain joined and kerberos is setup correctly or use NTLM which does not require kerberos.

**Comment by HongGit** [comment]
Close due to no response, feel free to reactivate if the problem persists after tying above suggestion.
