### ISSUE TITLE
How to achieve Custom Binding with Mutual Certificate

### ISSUE THREAD

**Issue by GauravDivate** [dotnet/wcf#4863]
Hi,

I have been tasked with the upgrade of one of our solution to .NET 6. I did some analysis on this solution and
was able to see that there are different mode of authentication modes being used along with different types of bindings
to consume SOAP Services.

One of the binding that is currently is used CustomBinding with the AuthenticationMode as “MutualCertificates” as shown in
Web.Config below.

`
<customBinding>
	<binding name="BindingName">
		<security allowSerializedSigningTokenOnReply="true" **authenticationMode="MutualCertificate"** messageProtectionOrder="SignBeforeEncrypt" messageSecurityVersion="WSSecurity10WSTrust13WSSecureConversation13WSSecurityPolicy12BasicSecurityProfile10">
			<secureConversationBootstrap />
			<localClientSettings detectReplays="false" />
		</security>
		<textMessageEncoding messageVersion="Soap11WSAddressing10" />
		<httpsTransport />
	</binding>
</customBinding>
`
        
 Is this possible now with corewcf? If yes, can you anyone please with help me some examples/snippet, etc.
 
 Thanks in advance!!!

**Comment by HongGit** [comment]
Please see issue #4220.
