### ISSUE TITLE
Header is not passed with System.ServiceModel.Primitives channel factory

### ISSUE THREAD

**Issue by dineshkvp** [dotnet/wcf#4864]
I have a legacy WCF service with custom binding. I want to invoke this service from a .Net Standard 2.0 client. I have added nuget packages system.servicemodel.primitives, system.servicemodel.security and system.servicemodel.security. Below is my channel factory setup

var binding = new CustomBinding();
        var security = SecurityBindingElement.CreateUserNameOverTransportBindingElement();
        security.IncludeTimestamp = true;
        binding.Elements.Add(security);

        binding.Elements.Add(new TextMessageEncodingBindingElement(MessageVersion.Default, Encoding.UTF8));
        binding.Elements.Add(new HttpsTransportBindingElement { MaxBufferSize = MaxBufferSize, MaxReceivedMessageSize = MaxReceivedMessageSize });
        var headers = new Dictionary<string, string>
        {
            {"Ocp-Apim-Subscription-Key","xxxxxxxxxxxxxxxxxxxxxxx"}
        };
        var behaviour = new AddHttpHeaderMessageEndpointBehavior(headers);
        ChannelFactory<ITaskService> cf = new ChannelFactory<ITaskService>(binding, new EndpointAddress("https://api-xxl.yyy.com/cvg/fg/swer/v1"));
        cf.Endpoint.EndpointBehaviors.Add(behaviour);
        cf.Credentials.UserName.UserName = "username";
        cf.Credentials.UserName.Password = "password";

I get the below error

"HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'AzureApiManagementKey"

When i intercept the message with Fiddler i noticed that header is not getting passed. Please find below the raw request

POST https://api-xxl.yyy.com/cvg/fg/swer/v1 HTTP/1.1
Host: api-xxl.yyy.com
Cache-Control: no-cache, max-age=0
Accept-Encoding: gzip, deflate
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 1525

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" 

Am i missing something or is it a bug in .Net Standard Sysm.ServiceModel.Primitives implementation?

**Comment by HongGit** [comment]
@dineshkvp  could you please share the implementation of AddHttpHeaderMessageEndpointBehavior with us?

**Comment by HongGit** [comment]
Closing because of no response, feel to reactivate if issue persists and there is a repro app.
