### ISSUE TITLE
New Service Reference with .net 6 defined in Directory.Build.props-File not working

### ISSUE THREAD

**Issue by mhoermann** [dotnet/wcf#4867]
Hi,

when I want to add a new "WCF Web Service" reference in a .net 6 solution I get an error when the target framework is defined in the Directory.Build.props-file and not in the project file.
When I define the target framework in the project file, the wizard actually works.

Please, look at the attachments for further details.
![1](https://user-images.githubusercontent.com/18574569/182357290-499d5738-bc05-4b7b-bd76-0027695260be.png)
![2](https://user-images.githubusercontent.com/18574569/182357302-6f04da18-6083-4453-a415-dd7986651bab.png)
![3](https://user-images.githubusercontent.com/18574569/182357308-6d9b8fef-07a4-4f10-a549-cc912c40f386.png)

**Comment by imcarolwang** [comment]
A fix of the issue has been released to both dotnet-svcutil tool and VS 2022 preview. You can get the fix by installing the most recent release of [dotnet-svcutil](https://www.nuget.org/packages/dotnet-svcutil) or [VS2022 Preview](https://visualstudio.microsoft.com/vs/preview/). Closing issue.
