### ISSUE TITLE
dotnet-svcutil ignores most of the settings 

### ISSUE THREAD

**Issue by Montago** [dotnet/wcf#4887]
I've used the Visual Studio 2022 wizard to add a connection to my WCF service. 
I've SPECIFICALLY chosen **ObservableCollection** as collectiontype as well as Dictionary. 
The generated collections are **ARRAY**

I NEED the DataContracts to have the **INotifyPropertyChanged** implementation, so i added the option to the json.
This is IGNORED. 

I've tried using the tool from CLI and add the options but they are still IGNORED. 

I really want to upgrade to .NET6 - but this tool isn't making it easy for me :( 

```
{
    "ExtendedData": {
        "inputs": [
            "very nice url"
        ],
        "collectionTypes": [
            "System.Collections.Generic.Dictionary`2",
            "System.Collections.ObjectModel.ObservableCollection`1"
        ],
        "namespaceMappings": [
            "*, Modelkatalog.Client.CatalogService"
        ],
        "sync": true,
        "enableDataBinding": true,
        "targetFramework": "net6.0",
        "typeReuseMode": "All"
    }
}
```

**Comment by SchRobert** [comment]
Using 2.1.0 but the option
  `--collectionType System.Collections.Generic.List `
 or 
  `--collectionType System.Collections.Generic.List`1`
just throws an error that it cannot find the an assembly of this type.

When using without --collectionType, List<T> are created as T[] (array)

It is not an option to update all clients of List<T> into T[] ;-(

I used the svcutil with:

`dotnet-svcutil http://localhost/my/service.svc --reference "System.ComponentModel.Primitives, {System.ComponentModel.Primitives, 4.3.0}" --reference "System.Drawing.Common, {System.Drawing.Common, 6.0.0.0}" --projectFile myProject.csproj --namespace *,My.Namespace.MyService --serializer DataContractSerializer --collectionType System.Collections.Generic.List --outputDir "Connected Services/MyService" --sync --targetFramework net6.0`

**Comment by imcarolwang** [comment]
@SchRobert Can you try the -ct option with value name System.Collections.Generic.List`1 instead of System.Collections.Generic.List1` ?

**Comment by Montago** [comment]
Comment: Instead of having fully qualified names of types like System.Collections.Generic.List1` 

could we then PLEASE have a shorthand version ? eg: LIST, OBSCOL, ARRAY etc..

**Comment by Ungerfall** [comment]
If you run in from powershell windows terminal you should pass two ``
``` bash
dotnet-svcutil -ct "System.Collections.Generic.Dictionary``2" -ct "System.Collections.Generic.List``1"
```

**Comment by HongGit** [comment]
Close as this seems to be resolved.  Feel free to reactivate if this is still an issue.

**Comment by Montago** [comment]
It's not resolved .. it still doesnt work

**Comment by GranakPavel** [comment]
Hello, this helped me:

dotnet-svcutil 2.1.0

dotnet-svcutil https://XXXXXX/XXX.svc --enableDataBinding --namespace "*, XXXService" --outputDir "{ProjectName}/Connected Services/XXXService" --outputFile Reference.cs --targetFramework "net7.0" -ct "System.Collections.ObjectModel.ObservableCollection``1,System.ObjectModel"

**Comment by Montago** [comment]
The latest versions of Visual Studio 2022 (17.8) has finally fixed the issues with WCF subscription 

- Databinding works now
- ObservableCollection works if you remember to pick System.ObjectModel as dependency
