### ISSUE TITLE
Compiling JScript/CSharp scripts is not supported.

### ISSUE THREAD

**Issue by santo1991** [dotnet/wcf#4911]
Hi, I am using Asp.net core 3.1 and try to consume web-service. The wsdl url generate the code file and required methods. When I call a method bellow error occurred :
"Compiling JScript/CSharp scripts is not supported."

But I am getting proper response in SoapUI.

What can be the reason for this error?Or can i get the exact error?

**Comment by HongGit** [comment]
@santo1991 this is not a great message.  Usually, this happens when generating the sterilizer failed.  Please attach debugger and find out what exception was thrown before this exception, and share it with us.

**Comment by HongGit** [comment]
@santo1991 thanks for raising the issue with us!  We are closing this issue as there is no response for a long time.  Feel free to reactivate if the issue persists and share the detailed exceptions with us as stated above.
