### ISSUE TITLE
How to override ws-addressing <To> header value

### ISSUE THREAD

**Issue by nhontran** [dotnet/wcf#4930]
We consume a SOAP service via API gateway, we got one problem that the address endpoint is set as **URL A** (API Gateway endpoint), but the hosted service endpoint is **URL B**, and it threw exception below:

> The message with To '{URL A}' cannot be processed at the receiver, due to an AddressFilter mismatch at the EndpointDispatcher. Check that the sender and receiver's EndpointAddresses agree.

We are trying to override the WS-Address &#60;To&#62; header by the code below but not successful:

```
WSHttpBinding binding = new WSHttpBinding();
binding.Security.Mode = SecurityMode.Transport;
EndpointAddress endpoint = new EndpointAddress("<URL A>");
ServiceClient client = new ServiceClient(binding, endpoint);
using (new OperationContextScope(client.InnerChannel))  
{  
        OperationContext.Current.OutgoingMessageHeaders.To = new Uri("<URL B>");  
        ....  
}
```
the &#60;To&#62; will be overridden by the address endpoint 
```
	<s:Header>
		...
		<a:To s:mustUnderstand="1">URL A</a:To>
		...
	</s:Header>
```

We found another way to do it by using **ClientViaBehavior** but it is not supported in .NET 6:
https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.description.clientviabehavior?view=netframework-4.8&viewFallbackFrom=net-6.0

Is there any way to get this working?

**Comment by mdraganov** [comment]
Had the same issue because of SSL offloading at the API gateway. Found two different workarounds if you can afford them. One is to use BasicHttpsBinding instead of WSHttpBinding. It does not send this header and again has SecurityMode.Transport by default. The other would be to use the SoapActorAttribute on the service side.

**Comment by mconnew** [comment]
I'm sorry, I thought I had replied but apparently I forgot to hit the comment button and now my reply is lost. The ClientViaBehavior doesn't need access to any internals that aren't exposed so you can just copy the implementation from [here](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/Description/ClientUriBehavior.cs). The only property you need available is ClientRuntime.Via and I checked and that is exposed in the package.

**Comment by HongGit** [comment]
Close since this seems to be resolved.  Feel free to re-open if it's not the case.
