### ISSUE TITLE
Question: Does .Net Framework 4.8 support WCF Message Security?

### ISSUE THREAD

**Issue by epkuiper** [dotnet/wcf#4937]

**Comment by HongGit** [comment]
@epkuiper do you mean the 4.8 .NET Framework or version 4.8 of System.Servicemodel.* packages?

If former, the answer is yes, WCF .NET Framework 4.8 supports Message security.

If later, no, System.ServiceModel.* packages do not support Message Security yet.

**Comment by epkuiper** [comment]
I mean the 4.8 .NET Framework. Thank you for your answer.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
