### ISSUE TITLE
Add support for WebHttpBinding to build clients of RESTful Web Services

### ISSUE THREAD

**Issue by stukselbax** [dotnet/wcf#494]
Currently, there is no support for WebHttpBinding, which is (IMHO) convinient way to build clients of RESTful Web Services via WCF.

**Comment by roncain** [comment]
Thanks for the suggestion, @stukselbax .  Do you currently have existing WCF RESTful services running and want to connect to them from a client or mid-tier?  Or do you make this suggestion to help build new RESTful apps? For building new RESTful apps, I recommend Web API (http://www.dotnetfoundation.org/aspnet-5).  For SOAP-based apps, or those requiring TCP, I'd continue to use WCF.  But Web API is the logical descendent of WCF REST and was designed and created to provide a cleaner and more powerful Http programming model. Some of the WCF REST authors participated in its design and implementation.  We use it ourselves in this GitHub repo (https://github.com/dotnet/wcf/tree/master/src/System.Private.ServiceModel/tools/test/Bridge ) to provide a RESTful model our functional tests can use to launch arbitrary WCF services.

**Comment by stukselbax** [comment]
We have created complicated distributed computer system (cross-platform). Currently, we are using .net Remoting for communication between them (replication, command execution, etc., with custom security). Our customers want to access our services in RESTful manner, using **HTTP** and json/xml inside the body. So, we are planning to migrate our solution to WCF.

Why? We have pointed out, that using WCF we could achive protocol-agnostic solution, because we can either expose our service via **HTTP** (in REST manner, in order to be accessible from anywhere) and **TCP** (netTcp - in order to perform our internal interprocess communication), using the same set of `ServiceContracts`. We have looked into the Web API, and it seems to us that this is very good for writing server side of communication, but what about the client?

In examples all over the web, in order to perform `WebRequest`, you should manually specify URL, Headers & Body of the message. Commonly the Body is the serialized objects, so, you need to call some kind of serialization method to fullfill all required fields. After that, you have to check `WebResponse` - check the **HTTP** Status code, deserialize response body, handle the error, and so on, so on. Now, imagine that the number of such calls per logical method is large (more than 2), and the number of such logical operations is huge. Your code will beacame unreadable immediatly.

My point is that manual handling of such kind of work (serealization, deserealization, error code checking, and so on) must be opaque and configurable.

Currently, we are trying to use MONO stack of WCF Web HTTP model, but it seems that it sligthly buggy, and the community is not so active. So I think that we should migrate to the Microsoft stack of .net implementation, but there is no support either for WebHttpBinding, and for WCF Server.

**Comment by roncain** [comment]
Thanks @stukselbax , I think I understand your requirements better.  We'll update this topic once we decide which additional bindings we should add to the client API's.  We appreciate suggestions like yours and the explanation why you made it.

**Comment by zhenlan** [comment]
> We have looked into the Web API, and it seems to us that this is very good for writing server side of communication, but what about the client?

@stukselbax just for your information, you can use [Swagger](http://swagger.io/) for [client generation](https://github.com/swagger-api/swagger-codegen) and use [Swashbuckle](https://www.nuget.org/packages/Swashbuckle/) to generate Swagger documents for ASP.NET Web API and also for services built using ASP.NET MVC 6.
