### ISSUE TITLE
Not able to Consume WCF Service in .NET Core 

### ISSUE THREAD

**Issue by Shruthi1984** [dotnet/wcf#4940]
Microsoft explains in many ways to consume the WCF services in .net core . But I'm not able to consume it, 
It gives an option to add the service thru the connected services , upon adding the service file, When i try to build it, it simply gives an error saying 
**Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'CodeDom' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	ClassLibrary1	D:\TFS\WCFClientInCore\ClassLibrary1\Connected Services\ServiceReference1\Reference.cs	1403	Active**

and Microsoft also claims that it is solved .Net Standard 2.x and .net 5 above but it is not .
There also i get the same error. Couple of the nuget package like dotnet-svcutil and Microsoft.CodeDom.Providers.DotNetCompilerPlatform are also not supported by .net 6.0 and .net standard 2.X.

Without all this i dont know how we can say, we can consume WCF services in .NET 6.0.

If it really solved pls send me the link with the reference or code example where it is actually working, i'm just curios to see, how it is claimed that it works.

**Comment by imcarolwang** [comment]
@Shruthi1984, thanks for raising the issue with us. The current supported features of WCF Connected Service tool in .NET Core project is not as complete as Add Service Reference tool in classic Full .NETFramework project. For example, generation of WCF Message Security Mode code is not yet supported by the tool in .NET Core platform. I've ever seen WCF Connected Services ran into error during code generation but still generates code, and when this happens, we can see that the "Microsoft.CodeDom.*" attribute be applied in the generated classes which also implies the code generation process ended abnormally. So, I suspect that the service you're generating code for may contain features that the tool doesn't fully support. Could you try generating code for the same service by running Add Service Reference tool in .NET Framework project? If you see no problem, can you provide a service or wsdl file which reproduces the issue in .NETCore? Thank you!

**Comment by Shruthi1984** [comment]
Hi @imcarolwang , the same service works completely fine in .NET Framework, we have not faced any issues there. when it comes to cross platform across .NET Framework and .NET 5(or above) and .NET Standard we are facing this issue.
 And I don't have the WSDL file to share with you, as the service was just exposed with the Endpoints with netTCP configuration and I am sharing the config file Snips with you 
![ConfigSnip1](https://user-images.githubusercontent.com/100934985/198950542-0a039ac7-e4a3-42f6-88c7-3f6a484ba4d7.PNG)
![ConfigSnip2](https://user-images.githubusercontent.com/100934985/198950553-a36f95ff-eaba-4664-b6aa-d4537ccf9fd1.PNG)

Also, Can you give me list of WCF services from .NET Framework which can be consumed in .NET Core and .NET 5(above) . so that we know that , before analyzing more on it and saves lot of time for us.

Thanks in advance!

**Comment by HongGit** [comment]
@Shruthi1984 from the config file you shared, there is nothing obvious which the existing WCF Core or dotnet-svcutil does not support yet.  In order to understand your issue better, any chance you could provide a simple repro app or provide some repro steps?

**Comment by HongGit** [comment]
@Shruthi1984 closing this as no response for long time.  Feel free to reactivate if the issue persist..
