### ISSUE TITLE
I wrote 2 identical programs to use a web service: one in .NET Framework one in .NET Core, only the former works.

### ISSUE THREAD

**Issue by ClintonBast** [dotnet/wcf#4971]
I don't know if this is a bug or if I'm doing something wrong.

I wrote 2 identical programs to use a web service: one in .NET Framework and one in .NET Core, only the former works.

I made a message inspector so I could see what was being sent to the service in each version of the program.
**Both versions seem to be sending the exact same SOAP envelope.**  Except the .NET Core version added `<?xml version="1.0" encoding="utf-16"?>` to the top.   But according to  _mconnew_ in post [](https://github.com/dotnet/wcf/issues/4570), that extra xml tag is just something that the .NET Core _Message.ToString()_ writes out, it isn't actually sent to the service.

I followed _mconnew's_ suggestion to see what is really being sent by doing what this person did on this blog: https://justsimplycode.com/2019/11/02/disable-header-100-continue-in-net-core-wcf-client/.   But it never seemed to call _HttpMessageHandlerBehavior.GetHttpMessageHandler()_ so it could replace it with _InterceptingHttpMessageHandler_.

**Comment by ClintonBast** [comment]
I'm really just having trouble with one web service we use for work.
I was able to use another web service (https://www.dataaccess.com/webservicesserver/TextCasing.wso?WSDL) successfully in .NET Core.

**Comment by mconnew** [comment]
Were you using the intercepting http handler with .NET Framework as it won't work there, only on .NET Core. If you want to do something similar in .NET Core, you need something [like this](https://github.com/mconnew/Playground/tree/main/HijackHttpWebRequest) to intercept the request. You could also use fiddler to MITM the request and take a look.

**Comment by ClintonBast** [comment]
Thanks for the response _mconnew_.

> Were you using the intercepting http handler with .NET Framework as it won't work there, only on .NET Core.

No, I was trying to use it with .NET Core.

> If you want to do something similar in .NET Core, you need something [like this]_(https://github.com/mconnew/Playground/tree/main/HijackHttpWebRequest) to intercept the request.

Did you mean to say .NET Framework in this sentence? 
I'll check out the link.

> You could also use fiddler to MITM the request and take a look.

I'm kind of a newbie with most of this stuff.  So, I don't know what _fiddler_ is or what _MITM_ means.  I'll have to look it up.

**Comment by ClintonBast** [comment]
Hmmm.  I wonder if I'm going crazy.  

The whole point of my post was to show how my .NET Framework test program could use the web service successfully while the .NET Core test program would fail.
But today when I was demonstrating the problem to another programmer,  my **.NET Framework test program was also failing!**  But I swear it worked before.  That's why I wrote this post in the first place!  Now I'm beginning to question if it ever worked.

I know the web service is not down because I can post requests to it using the Insomnia program.

So, I guess I'm just going to close this issue.
