### ISSUE TITLE
WS – Security 1.1 Timestamp and Signature

### ISSUE THREAD

**Issue by avojacek** [dotnet/wcf#4972]
Hi all,
is it possible to use this library to create SOAP client which can use WS – Security 1.1 Timestamp and Signature ? 
SOAP message looks like attached file.
Thank you a lot.
[soap.zip](https://github.com/dotnet/wcf/files/10263744/soap.zip)

**Comment by mconnew** [comment]
The SOAP message was really helpful to work out what you need. Unfortunately, it requires the full Message security feature which we don't currently have planned for .NET.  If you look at the SignedInfo block, it references two items as part of the signature. The first with URI `#Timestamp-445df5c5-e7cc-4fac-89bde2ba0a40161b` includes the Timestamp element, but the second with URI `#Id-acf95827-208c-42eb-afad-87fd72dd116d` is referencing the main SOAP Body element. We don't have the ability to include digests for elements outside of the Security header.

**Comment by avojacek** [comment]
Ok thank you,
I never used this even in WCF times of .NET 4.x fw, so I have to learn more about that. But can I ask you what path I could take? Do it in .NET 4.x using WCF or try to do it somehow in .NET Core? This communication will be part of system which I wanted to do in .NET Core because i was ment to be few services and one web in docker containers. When I found that this communication is neede I already started with other stuff :-( . If it ends up that I have to do it in old .NET I can do it but I t means that one part of solution will use windows server. Sorry for my bad english, hopefully you can understand me :-) 
Thank you again for your response.

**Comment by mconnew** [comment]
To be honest, your current binding doesn't make a lot of sense. You are signing the body of the message but you aren't encrypting it. This means SOAP is protecting you from the body payload being modified without you knowing, but it's not keeping the contents of your request secret. Usually you want to keep your communication secret which means using HTTPS and not HTTP. If you are using HTTPS, you already have protection against the message being modified so you don't need to sign the body.  
The main usage scenario for your setup is if the host which receives the message isn't the final host to process it and you want the final host to be able to validate the client credentials and have confidence the message wasn't modified on its way. If you are doing direct client to server communication, signing the body is likely unnecessary. You also get limited protection from replaying of an old message (presuming you reject messages with an old timestamp).   

Are you able to make changes to the service to use a different configuration as long as it gives you the same security features that you currently have? If so, then I may be able to help you come up with an alternative which works with .NET Core.

**Comment by avojacek** [comment]
The problem is, that i'm client of service which I do not develop. That service is external (electricity market in Czech rep.) And yes it is over HTTPS and you have a good gues why it is signed, the service which I do interact with is not final recipient (not every time atleast). The service is developed using product SAP Netweaver. :-(

**Comment by mconnew** [comment]
I'm sorry, for now .NET Framework is the only solution without a lot of code to do this manually yourself.

**Comment by avojacek** [comment]
Thank you a lot for your time.
Firtstly I will try to do prototype in .NET and when it works May be then write the code in .NET Core will not be to hard.
Thank you a lot.
Ales
