### ISSUE TITLE
Fix extensibility issues with the WSFederation feature

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#4983]
Original issue where this was discovered is #4979.  

On the class `WSTrustTokenParameters` there are two properties intended to allow customization of the `WsTrustRequest` which is sent to get a WSTrust security token, `ClaimTypes` and `AdditionalRequestParameters`. These are currently ignored, and their data isn't copied to the `WsTrustRequest` instance. In the method `WSTrustChannelSecurityTokenProvider.CreateWsTrustRequest()` we need to copy the data from these two properties into the `WsTrustRequest` instance that's returned. Additionally, the `WSTrustChannelSecurityTokenProvider.ClientCredentials` property needs to be made either `public` or `internal protected`. 

## WSTrustTokenParameters.ClaimTypes
There's a mismatch in api's between `WSTrustTokenParameters.ClaimTypes` and `WsTrustRequest.Claims`. The former is defined as `ICollection<Microsoft.IdentityModel.Protocols.WsTrust.Claims> ClaimTypes` and the latter is defined as `Microsoft.IdentityModel.Protocols.WsTrust.Claims Claims`. If there are multiple `Claims` instances in the  `WSTrustTokenParameters.ClaimTypes` collection, we can't blindly combine them. This is because the `Claims` type has a `Dialect` property. There are 4 solutions I can think of.  
1. The simplest solution is to only support a single `Claims` instance in the `WSTrustTokenParameters.ClaimTypes` collection and throw when fetching the claims if there's more than one. This does make the behavior and the api shape contradict, but is a simple solution.   
2. Combine multiple `Claims` instances into a single instance, with validation that the dialect is the same on all of them and throwing if they aren't all the same.  
3. Obsolete the existing `WSTrustTokenParameters.ClaimTypes` property as it currently unused so we won't functionally break someone who was previously working, then add the correctly shaped API `public Claims Claims { get; set; }`. Worst case someone compiling their code fresh will get a warning which alerts them that their existing code adding `Claims` wasn't doing anything, which is a good thing to bring attention to.  
4. Similar to option 3, but instead delete the incorrect property. Our next release is going to have a 6.x version number and will require .NET6.0+ and we're allowed breaking changes between major versions. In this case the worst that can happen is a library could be referencing the bad property (which was doing nothing) and the referencing application could promote the version of WCF being used to 6.0 and cause a runtime error. This is very unlikely as I would expect someone trying to use that property would have discovered it doesn't work as their returned token wouldn't include the claims.  

## WSTrustTokenParameters.AdditionalRequestParameters
For the property `AdditionalRequestParameters` we have another conflict. The class `WSTrustTokenParameters` derives from the class `IssuedSecurityTokenParameters`. On .NET Framework, `IssuedSecurityTokenParameters` has a public property defined as `public Collection<XmlElement> AdditionalRequestParameters { get; }`. While this property exists in the .NET implementation, it was never exposed on the contract. The `WSTrustTokenParameters.AdditionalRequestParameters` property is defined as `public new ICollection<XmlElement> AdditionalRequestParameters { get; }` which is very similar. As this property isn't doing anything, making changes won't functionally break anyone. Reverting to the .NET Framework api doesn't have the option of applying the obsolete property to the `WSTrustTokenParameters` property. We have had requests for adding IssuedToken support so we might be adding more api's to the `IssuedSecurityTokenParameters` class in the future, but that's the app supplying a token to WCF which has already been obtained. I could only find uses of this api in .NET Framework for the Federation scenario (which is a subset of the IssuedToken feature, specifically WCF goes and fetches the issued token for you as compared to passing WCF the issued token) so there's a reasonable argument that we should just leave it on `WSTrustTokenParameters`. The solutions I can think of are:  
1. Leave the new property on `WSTrustTokenParameters` as it's only applicable to the federation scenario which has now been implemented in System.ServiceModel.Federation, external to the core WCF code base in Primitives. The risk here is I missed a scenario on .NET Framework which we might port over in the future requiring the property to be brought back on `IssuedSecurityTokenParameters`. This is unlikely as the purpose of the API is to provide free-form XmlElement's to be added to the end of the security token request. We purposefully named the package and namespace System.ServiceModel.Federation and not WSFederation in case we wanted to expand federated scenarios beyond WSFederation to other federated scenarios. Any other scenarios would most likely be best implemented in this package and not in Primitives where `IssuedSecurityTokenParameters` lives.  
2. Remove the property on `WSTrustTokenParameters` and make the one on `IssuedSecurityTokenParameters` public in the reference assembly. The only benefit here is to match the api's between .NET and .NET Framework. Anyone using this feature will be using the newer System.ServiceModel.Federation package which has classes which don't exist on .NET Framework (different namespace).

Whatever the solution to where the `AdditionalRequestParameters` will live, using the values is simple. It should be a simple matter of copying the values to `WsTrustRequest.AdditionalXmlElements`.

## WSTrustChannelSecurityTokenProvider.ClientCredentials
The problem here is the class was intended to be derived as it has virtual methods to enable changing behaviors, but without the ability to set the `ClientCredentials`, there's no way to authenticate the WS-Trust IssueToken request with the issuing service. If using the class itself without deriving, you would use `WSTrustChannelClientCredentials` to instantiate an instance which would take care of setting the credentials. This suggests that the `ClientCredentials` property should be `internal protected` as code consuming the class has no need to set it, only a derived implementation does.

# Testing
The easiest way to test these fixes is by writing a class derived from `WSTrustChannelSecurityTokenProvider`. A public helper method in the derived class will be able to call the protected `CreateWsTrustRequest` method and return the `WsTrustRequest` instance. Test code can then verify that the various data from `WSTrustTokenParameters` have been copied into the `WsTrustRequest` instance. Writing an end to end test for this would require quite a bit of work and is unnecessary.

**Comment by michalor** [comment]
> ## WSTrustTokenParameters.AdditionalRequestParameters
> (...) 
> Whatever the solution to where the `AdditionalRequestParameters` will live, using the values is simple. It should be a simple matter of copying the values to `WsTrustRequest.AdditionalXmlElements`.

I've just noticed, the `AdditionalRequestParameters` property is defined like this `public IList<XmlElement> AdditionalXmlElements { get; } = new List<XmlElement>();` in the `Microsoft.IdentityModel.Protocols.WsTrust.WsTrustMessage` class.

I'm not sure how to deal with that, since we want to set it during creation of `WsTrustRequest` instance and the class 'WsTrustMessage' is not a part of this package.

**Comment by thuannguy** [comment]
Awesome. I have to use reflection to set that ClientCredentials property for now. Looking forward to having these changes implemented 😁
