### ISSUE TITLE
Update release notes for dotnet-svcutil

### ISSUE THREAD

**Issue by kapsiR** [dotnet/wcf#4986]
The [dotnet-svcutil - Release Notes](https://github.com/dotnet/wcf/blob/main/release-notes/dotnet-svcutil-notes.md) do not mention versions > `2.0.1`

In the meantime [`v2.1.0` has been released](https://www.nuget.org/packages/dotnet-svcutil/2.1.0), what has actually changed? (framework support changed?)

Thanks 🙏

(initially I created this issue [in the wrong repo](https://github.com/CoreWCF/CoreWCF/issues/980#issue-1528790414), cc @HongGit)

**Comment by HongGit** [comment]
Thanks for reporting this issue, @kapsiR!  Please refer to https://github.com/dotnet/wcf/releases/tag/v2.1.0-dotnet-svcutil.

**Comment by kapsiR** [comment]
@HongGit Thanks for the hint! I proposed a PR with incooperates this into the release notes file of dotnet-svcutil 😉
