### ISSUE TITLE
Reorganize the existing scenario tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#50]
PR https://github.com/dotnet/wcf/pull/41 effectively moved our experimental scenario branch into master in preparation for allowing further reorganizing and improving in the open. However the test organization in that branch pre-dated this WCF repo becoming public and therefore was not available for community feedback.

The goal of this current issue is to publically reorganize and rename these existing tests into a more rational structure that is similar to how the long-standing WCF samples are organized. Once this reorganization has been reviewed and completed, we will be able to publish guidance for adding new scenario tests.

**Comment by StephenBonikowsky** [comment]
For reference the WCF Samples on MSDN can be found here...
3.5: https://msdn.microsoft.com/en-us/library/vstudio/ms751532(v=vs.90).aspx
4.0/4.5: https://msdn.microsoft.com/en-us/library/dd483346(v=vs.110).aspx

So based on the previously released WCF Samples below is the new proposed structure with modifications where it felt right.

Notes...
- This only shows the file structure for where existing tests go. As more tests are added the file structure will widen.
- These are Scenario tests not Unit tests.
- The CS files are actual checked-in files, some of them need to be renamed, we should do that as a separate PR after this one is in.
- The test cases in the CS files also need to be revisited for renaming purposes, I also think that should be done as a separate PR.

Feedback would be appreciated, such as whether some directories should go deeper. For instance for Http and Tcp Bindings, Transport Security involves more than just ClientCredentialType so I took the directory one layer deeper to add other transport related scenarios for each Binding.

└───Scenarios
    ├───Binding
    │   ├───Custom
    │   │       CustomBindingWithHttpTransportTests.cs
    │   │
    │   ├───Http
    │   │   │   BasicHttpBindingTests.cs
    │   │   │   NetHttpBindingTests.cs
    │   │   │
    │   │   └───TransportSecurity
    │   │           ClientCredentialTypeTests.cs
    │   │
    │   └───Tcp
    │       └───TransportSecurity
    │               ClientCredentialTypeTests.cs
    │
    ├───Client
    │   ├───ChannelLayer
    │   │       DuplexChannelShapeTests.cs
    │   │       RequestReplyChannelShapeTests.cs
    │   │
    │   ├───ClientBase
    │   │       ClientBaseTests.cs
    │   │
    │   ├───ExpectedExceptions
    │   │       ExpectedExceptionTests.cs
    │   │
    │   └───TypedClient
    │           TypedProxyTests.cs
    │
    ├───Contract
    │   ├───Data
    │   │       DataContractTests.cs
    │   │
    │   ├───Fault
    │   │       ExpectedExceptionTests.cs
    │   │
    │   ├───Message
    │   │       MessageContractTests.cs
    │   │       MessageTests.cs
    │   │
    │   └───XmlSerializer
    │           XmlSerializerTests.cs
    │
    ├───Encoding
    │   ├───Encoders
    │   │       BinaryEncodingTests.cs
    │   │       TextEncodingTests.cs
    │   │
    │   └───MessageVersion
    │           MessageVersionTests.cs
    │
    ├───Extensibility
    │   └───HttpRequestMessageProperty
    │           NotYetInRepo.cs
    │
    ├───Security
        └───Https
                HttpsTests.cs

**Comment by roncain** [comment]
I like this proposal @StephenBonikowsky -- it's close enough to the MSDN Samples hierarchy to be familiar but also improves the organization to make tests more discoverable. 

It is probably worth mentioning all of these Scenario tests are what the CoreFx repo calls [OuterLoop](https://github.com/dotnet/corefx/issues/1477) meaning they are executed currently using 'build /p:WithCategories=OuterLoop'. They are not normally expected to run on the CI machine for every PR, but they will be run on a schedule.  And of course everyone can run them on their own development machines.

 My recommendations (I can wait for the PR to see) are:
* The Https folder seems like it should live somewhere under the Binding folder.  Parallel to Http?
* I think our existing MessageInspector tests will fit under Extensibility (as will our MessageFormatter tests when we add them)
* I would find value in seeing where CSPROJ files live to understand better the intended granularity for running groups of tests. I opened issue https://github.com/dotnet/wcf/issues/53 to use xunit traits to allow filtering across CSPROJ boundaries.

**Comment by StephenBonikowsky** [comment]
Hoping to have a PR early next week for this.

**Comment by SajayAntony** [comment]
@StephenBonikowsky this is really nice. 
Does Client->channel layer mean creating a client using just the channel layer?

The only change i would recommend  
* Https  would go under - TransportSecurity in Binding ( I guess we could think about lighting up the security folder when if and when we light up message security as @roncain suggested)
* ExpectedException Tests under fault should mostly like be FaultContractTests or something on those lines.

**Comment by StephenBonikowsky** [comment]
The PR is ready for review #58 
@SajayAntony 
- Yes, channel layer is for tests calling directly into the channel layer of WCF and skipping what we traditionally call the ServiceModel Layer.
- The current PR keeps the Https tests under 'Security\TransportSecurity' as the Binding itself does not really matter, we would add an additional pivot here if/when Message security gets added.'Security\MessageSecurity'.
- Yes, only Fault related exception tests will be under there, currently called FaultExceptionTests.cs.

**Comment by StephenBonikowsky** [comment]
Did I miss a way for the PR to use this Issue instead of creating a new one?

**Comment by iamjasonp** [comment]
Nope - you didn't miss anything. 
The best you can do is says something like "Fixes #50" in a commit comment, which will automatically close this issue once the PR is accepted.
