### ISSUE TITLE
Address additional comments on Make cert parameters configurable and add TCP negative security tests pull request

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#500]
Jason has made some additional comments after the pull request committed. This issue is to track addressing those comments.

https://github.com/dotnet/wcf/commit/8cdbd5b85631ff0d965479560563fb156f5fb65d#commitcomment-14131881

**Comment by iamjasonp** [comment]
These are all NIT level issues; recommend just dealing with them the next time someone touches the file, no need to address immediately.

**Comment by hongdai** [comment]
Closing the issue per Jason's comments above.
