### ISSUE TITLE
Missing EndpointAddressAugust2004 and EndpointAddress10

### ISSUE THREAD

**Issue by dpomerantz-jci** [dotnet/wcf#5010]
I'm looking at the original WCF implementation of WS-Discovery, and see how it uses both EndpointAddressAugust2004 and EndpointAddress10 in its implementation of Resolve.  WCF Core has ported EndpointAddress, but has not ported these other two classes.  Is there a new way to implement the functionality that was written in the original WCF's WS-Discovery without them?  If so, please point to documentation or example.  If not, could these be added to WCF?  Examples of the the code used for WS-Discovery are below.  They may not mean much out of context, but do show the calls made.  Each of these is duplicated for EndpointAddressAugust2004 and EndpointAddress10, but I am only showing EndpointAddress10 for brevity:

`EndpointAddress10.GetSchema(schemaSet)`

`EndpointAddress10 endpoint = discoveryVersion.Implementation.EprSerializer.ReadObject(reader) as EndpointAddress10;`

`EndpointAddress10 endpoint = EndpointAddress10.FromEndpointAddress(endpointAddress);`

`this.eprSerializer = new DataContractSerializer(typeof(EndpointAddress10));`

TIA,

dmp

**Comment by HongGit** [comment]
@dpomerantz-jci, here is the [referencesource](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/EndpointAddress10.cs), you could copy the source code to your own project.

Feel free to let us know if there are more questions.

**Comment by dpomerantz-jci** [comment]
I'm aware that they are there, and mentioned them in my original comment, referred to as "the original WCF," thus my question is not answered.  Allow me to ask again:

Has the WCF Core team devised a different way to resolve WS-Addressing addresses?  If so, please point me to the documentation.

If there is not another implementation, will the WCF Core team add these two classes to to the product?

I have already included them, and a few others, in my project, but I was hoping to take care of low hanging fruit and getting these added to the core library.  Note, the biggest roadblock to implementing WS-Discovery I've found is the lack of UDP support.  As far as I can tell, WS-Discovery in WCF is dead without it.

**Comment by mconnew** [comment]
We do plan to bring the WS-Discovery feature in the future, but I can't provide a date yet. That will be in its own nuget package. The two EndpointAddressXXX api's are only used with WS-Discovery so it wouldn't be appropriate to add them to the System.ServiceModel.Primitives package. We will add them when we port WS-Discovery.  
For the Udp binding, there's [a sample for it for .NET Framework here](https://github.com/dotnet/samples/tree/main/framework/wcf/Extensibility/Transport/Udp/CS/UdpTransport). You should be able to use that as a basis, remove the service side methods (e.g BuildChannelListener) and compile it for .NET 6.

**Comment by dpomerantz-jci** [comment]
@mconnew, Thank you, this is very helpful information!   (The reason for not including EndpointAddressXXX classes makes sense).

Once UDP is added as a supporting protocol, the next largest issue I found was that a full implementation of WS-Discovery, even for a "client," needs to support both sending UDP packets and hosting UDP listeners to receive Hello, Bye, and responses to Probe and Resolve.  It looked to me like the best approach was to implement UDP in both WCF and CoreWCF and create a standalone assembly to use both.  Can you comment if that is the proposed plan?

**Comment by mconnew** [comment]
The initial WS-Discovery implementation has been intended to support the infrastructure mode of WS-Discovery where you connect to a central server over HTTP to either register or query what servers are available.  
I do have a suggestion for technology to replace WS-Discovery in an infrastructureless mode. I've had this idea for a while to combine m-dns with sd-dns to provide the same functionality in a more lightweight way. M-dns is multicast dns so you can make a dns query using a multicast address and any machine in the broadcast/multicast domain can respond. Basically peer based dns. sd-dns is a convention for using dns records to advertise services. So basically a service which register with the local machines m-dns implementation an sd-dns record, and a client would query for an sd-dns record using m-dns. Windows has support for it via UWP api's which can be used by regular app's and don't require a Windows Store app to call them. They are easily callable from .NET.  
I understand this doesn't help you if you need to fit into an existing infrastructure, just adding possibilities to the conversation.  

You are correct about how you would need to handle things for UDP receiving historically with WCF. You would use a CompositeDuplexBinding to connect an outgoing UDP connection with an incoming UDP connection and make it look like a single thing, and the incoming would usually be an embedded ServiceHost instance. I think we can probably do it all on the client side though. If we model it as an IDuplexChannel, then add code to decode incoming UDP packets, I don't think it would be a lot of work (for someone who knows the channel layer api's really well) to do it all on the client side without needing CoreWCF. I think the WCF implementation was written with the mindset that a client doesn't open listening sockets so it needs to be done with a ServiceHost, and that would be correct for anything using streaming connections (eg TCP based transports) as you need to worry about connection counts and multiple channel instances and their lifetimes etc. None of that overhead is needed with UDP as it's datagram based so I think it can be done purely with the client.

**Comment by dpomerantz-jci** [comment]
I'm sure you've given more thought to this than I have, and I see what you are saying with the CompositeDuplexBinding for Probe and Resolve, but wouldn't you still need UDP listeners for Hello and Bye?  I think it's technically possible to ignore Hello and Bye, never use a cache, and never query a proxy, but it makes the protocol more chatty, which was avoided in the spec.  Honestly, it won't affect my use case, because we won't have proxies, but still....
