### ISSUE TITLE
WCF Web Service Reference Provider Tool - can't refresh service based on an edited ConnectedService.json file

### ISSUE THREAD

**Issue by bati06** [dotnet/wcf#5032]
Previously some hidden features were added to be used from the `ConnectedService.json` file.
For example: [serializer setting](https://github.com/dotnet/wcf/issues/3082#issuecomment-487160143) or [enableDataBinding](https://github.com/dotnet/wcf/issues/2205#issuecomment-490633884)

But currently in `Visual Studio 2022` it is not possible to refresh your connected service (based on your edited `ConnectedServiec.json` file). You can only select "Edit" on the UI that will overwrite your `ConncetedService.json` file. All in all you cannot use those hidden features mentioned above.

I know `dotnet svcutil` can be used as a workaround, but I would like to have those hidden feature either on the UI, or at least be able to edit my `ConnectedService.json` file and refresh the service based on that.

**Comment by bati06** [comment]
As I figured out I can run `dotnet svcutil --update "Connected Services/MyServiceName"` from the project folder to refresh the service based on the edited `Connected Services/MyServiceName/ConnectedService.json` file.

**Comment by Montago** [comment]
Why is this issue closed ??

It's still not working in Visual Studio 2022 v17.6 !!!

Editing the JSON and updating the service doesnt add the features added to the JSON :(
