### ISSUE TITLE
Need scenario test coverage for Client Certificates on http.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#507]
Current tests for Client Certificate are using NetTcp, need to add the http pivot.

**Comment by StephenBonikowsky** [comment]
Needed pivots...
- NetHttpBinding
- BasicHttpBinding

**Comment by mconnew** [comment]
Currently we don't have the relevant API's available to do this. NetHttpBinding and BasicHttpBinding throw an exception on ChannelFactory creation when setting client authentication mode to certificate. HttpsTransportBindingElement doesn't expose the RequireClientCertificate property. This will require a contract change to enable.

**Comment by zhenlan** [comment]
@mconnew with the new API you added recently, is this good to go now?

**Comment by StephenBonikowsky** [comment]
Seems this is still not supported but I think we can use NetHttpsBinding, we have one test using BasicHttpsBinding.

For NetHttpsBinding we don't have any tests at all.

**Comment by StephenBonikowsky** [comment]
Morphing this issue to be for adding test coverage for NetHttpsBinding.
