### ISSUE TITLE
Method missing property missing ProtectionLevel in contractDescription

### ISSUE THREAD

**Issue by kuldeepdshah** [dotnet/wcf#5071]
Hello,

I have just installed latest package but, noticed dll not showing the updated changes.
for example ContractDescription have ProtectionLevel property which is not showing.
Can you please revert and reason why its not there.

Regards,
Kuldeep Shah

**Comment by HongGit** [comment]
@kuldeepdshah ProtectionLevel property only applies to Message security mode, which WCF client does not support yet.
