### ISSUE TITLE
Develop strategy for E2E testing for Windows Linux and UWP

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#508]
This issue is for the discussion and design of E2E tests we can use for sign-off and creating easy repro's for other teams.  Goals:
- Needs to run on CoreCLR and UWP
- Needs to run on Windows and Linux
- Needs to be checked into GitHub and runnable by anyone
- Should leverage as much as possible existing Bridge and BridgeClient
- Should leverage existing WCF services (does not need to use all)
- Should be easy to copy this app to turn it into a repro of an issue to give another team

**Comment by zhenlan** [comment]
related to issue #476

**Comment by roncain** [comment]
@hongdai is working on this now.  The next step is for her to present the proposal or PR. I'm holding this issue to ensure I am in the loop for the design.
