### ISSUE TITLE
WCF Named Pipe synchronous calls deadlock for certain SynchronizationContexts

### ISSUE THREAD

**Issue by smithmw** [dotnet/wcf#5080]
**Describe the bug**
WCF Named Pipe synchronous calls deadlock when called from a thread where the "current" SynchronizationContext is one which sends its work to the same thread (E.g. WindowsFormsSynchronizationContext).

**To Reproduce**
Attached is a sample that runs a WCF Named pipe service. 
[NetNamedPipeNet6.zip](https://github.com/dotnet/wcf/files/11151193/NetNamedPipeNet6.zip)
There is a Console Application that connects to it and works correctly.  There is a Winforms application that connects to it and exhibits the defect.  
1. Open the Solution WCFNetNamedPipe.sln
2. Run the WCF_NewsService project.
3. Run the WinFormsApp1 project.
4. Press the button (this initiates a synchronous call to the service and displays a message box once the call returns).
Issue: this causes a deadlock.  

**Expected behavior**
The expected behavior is that there is no deadlock.
The correct behavior can be observed by checking the "Workaround" checkbox in the WinFormsApp1. This temporarily removes the SynchronizationContext prior to calling the service.
The correct behavior can also be observed by running the ConsoleApp_Net6 project.  

**Additional context**
It appears that the fix is likely to either be adding an `await TaskHelpers.EnsureDefaultTaskScheduler();` somewhere in the flow.
It may be the case that this change addresses or has an affect on this issue:
https://github.com/dotnet/wcf/pull/5044 for https://github.com/dotnet/wcf/issues/4946

Is there a preview package with this change incorporated that can be tested?

**Comment by smithmw** [comment]
> Can you try launching the client call using `Task.Factory.StartNew(() => { /* make call */ }, TaskCreationOptions.PreferFairness)`. If this fixes it, then the pending fixes should fix your issue.

It does. Is there a preview package with the latest changes I can test with and confirm?

**Comment by mconnew** [comment]
We've now released an RC release with the fix. Can you try that to ensure it fixes your problem.

**Comment by smithmw** [comment]
It does.  Thank you!
