### ISSUE TITLE
Client certificate is not sent when using BasicHttpsBinding

### ISSUE THREAD

**Issue by olsh** [dotnet/wcf#5088]
My server uses a client certificate for authentication. And when I send it using HttpClient everything works fine. But when I use the WCF client libraries the client certificate is not sent to the server.
I use IIS 10 as a web server and ASMX (SOAP) services. On the client side .NET 6 is used.

Client creation:
```csharp
            var httpsBinding = new BasicHttpsBinding(BasicHttpsSecurityMode.Transport);
            httpsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
            var client = new DsPayment.Client.Payment.ServiceSoapClient(httpsBinding, new EndpointAddress(endpoint));

            client.ClientCredentials.ClientCertificate.Certificate = clientCertificate;

            client.CallServerMethod();
```

Server-side code in global.asax:
```csharp
        protected void Application_BeginRequest(object sender, EventArgs e)
        {
            Log.Information("Request started");

            var request = ((HttpApplication) sender).Request;

            // Check client certificate
            if (request.ClientCertificate.IsPresent)
           ...
```

HttpClient code that works:
```csharp
var handler = new HttpClientHandler();
handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.ClientCertificates.Add(new X509Certificate2(X509Certificate2.CreateFromEncryptedPemFile(@"cert.crt", "password", @"private.pem").Export(X509ContentType.Pfx)));

using (var httpClient = new HttpClient(handler))
{
	using (var request = new HttpRequestMessage(new HttpMethod("GET"), "https://service.local/Service.asmx"))
	{
		var response = await httpClient.SendAsync(request);
	}
}
```

**Expected behavior**
The client certificate is sent to the server.

**Additional context**
The client certificate acceptance is enabled in the IIS settings
![image](https://user-images.githubusercontent.com/3613592/230715067-b6a1c12f-7bbf-4c2d-af5e-30cb5718bb12.png)
TLS 1.2 is used for the requests. The client certificate is self-signed and added to the `Trusted Root Certificate Authorities` on the server. The client certificate has a private key.

Referenced packages:
```xml
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.*" />
```

**Comment by mconnew** [comment]
How are you determining it's not sent?  

The client only sends the certificate if the server has asked for it as part of the TLS handshake. When you set the SSL settings to Accept, the server doesn't ask for the certificate as part of the initial TLS handshake. Once WCF has received the request headers and identified that the request is for an endpoint that needs the certificate, it asks IIS for the certificate. IIS then initiates a TLS renegotiation and asks the client for the certificate. It's at this point that the client will send it.  

If you set the SSL Settings to Require, IIS will ask the client to provide a certificate as part of the initial TLS handshake.

**Comment by olsh** [comment]
> How are you determining it's not sent?

With the following code on the server side
```csharp
protected void Application_BeginRequest(object sender, EventArgs e)
{
    Log.Information("Request started");

    var request = ((HttpApplication) sender).Request;

    // Check client certificate
    if (request.ClientCertificate.IsPresent)
```

> If you set the SSL Settings to Require, IIS will ask the client to provide a certificate as part of the initial TLS handshake.

When I set the setting to `Require` then the request fails with the following exception.
```
System.ServiceModel.Security.MessageSecurityException : The HTTP request was forbidden with client authentication scheme 'Anonymous'.
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   // My application frames
```

But the `HttpClient` code in the first comments works without any issues.

**Comment by mconnew** [comment]
The only difference between how you create your HttpClientHandler and how WCF creates one is you set `ClientCertificateOptions`, but the default is Manual anyway so that shouldn't make a difference. You are also calling the service with a GET request, but WCF will make a POST call. There is a way to get to the `HttpClientHandler` that WCF creates. You can find details in [this blog post](https://justsimplycode.com/2019/11/02/disable-header-100-continue-in-net-core-wcf-client/). You don't need to create an intercepting handler, you can just return the same `HttpClientHandler` that's passed in. Can you check using a debugger that your certificate is set on the `HttpClientHandler`?
