### ISSUE TITLE
Unable to build an error free ServiceReference from Five9's Web API WSDL

### ISSUE THREAD

**Issue by LouHendricks** [dotnet/wcf#5098]
**Describe the bug**
I am converting my old .Net Framework code to .Net.  I migrated two sets of code that use WCF to .Net last year (one using a customer library and one that calls the Reporting Services SOAP endpoint).  I am not trying to migrate another piece of code that calls a customer server and my generated ServiceReference is filled with errors.  I don't know if it's a limitation of .Net or if I am doing something wrong or missing a step or workaround.

**To Reproduce**
In a brand new .Net 7 project using the add service reference wizard choose WCR and and enter the URI: https://api.five9.com/wsadmin/AdminWebService?wsdl&user=DK

You will see the Service WsAdminService and also see a warning that one or more errors occured.  Create the service and the generated code will contain many errors.

Alternative: 
use dotnet-svcutil to generate the service and add it to your project.  This shows a number of warnings and also generate code that contains many errors.

**Expected behavior**
I'm hoping to get a valid service reference so I can port my code to .Net 7.

**Additional context**
I may be trying to import WSDL that can't work with .Net 7 but I don't know enough to know if that's the case.

**Comment by LouHendricks** [comment]
This can be closed.  Five9 published an updated WSDL under a different URL  that works fine with .Net 7 using Add Service Reference from the GUI.

**Comment by Aplaza-Eddy** [comment]
> This can be closed. Five9 published an updated WSDL under a different URL that works fine with .Net 7 using Add Service Reference from the GUI.

Can you share the Updateed WSDL url ?

**Comment by LouHendricks** [comment]
> 
> Can you share the Updateed WSDL url ?

Looks like this was what I used:

`https://api.five9.com/wsadmin/v11_5/AdminWebService?wsdl&user=DK`

I don't remember why the user parameter is on there.
