### ISSUE TITLE
Confirm correct behaviour in usages of System.Xml.XmlWriter.Dispose()

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#51]
In all cases within WCF where we use an XmlWriter rather than XmlDictionaryWriter, check that:
* `Dispose()` is called on the XmlWriter after use
* All Xml tags/elements/contents are manually closed and doesn't rely on `Dispose()` to do this work

**Background:**
In desktop .NET, [System.Xml.XmlWriter](http://referencesource.microsoft.com/#System.Xml/System/Xml/Core/XmlWriter.cs) has a virtual `Close()` method that is overridden by, say, [System.Xml.XmlTextWriter](http://referencesource.microsoft.com/#System.Xml/System/Xml/Core/XmlTextWriter.cs) that performs actions like closing all outstanding opened elements. 

In .NET Core, [System.Xml.XmlWriter](https://github.com/dotnet/corefx/blob/master/src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriter.cs) does not expose a `Close()` method anymore, and neither does [System.Xml.XmlTextWriter](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Xml/XmlTextWriter.cs). You are expected to call the `Dispose()` method instead. 

We *don't* need to check XmlDictionaryWriter for this issue. `Dispose() == Close()` since [XmlDictionaryWriter](https://github.com/dotnet/corefx/blob/master/src/System.Private.DataContractSerialization/src/System/Xml/XmlDictionaryWriter.cs) (and therefore, derived classes) has a virtual `Close()` method. `XmlDictionaryWriter.Dispose()` will call `XmlDictionaryWriter.Close()`

**Comment by iamjasonp** [comment]
LGTM, subject to @roncain's comments about indents. 

I also did a quick check and I don't see any new exceptions being thrown from the Dispose code, but might be worth double-checking.

**Comment by shmao** [comment]
I confirm that there’s no new exception being thrown from the Dispose code. I will make the change per Ron’s suggestion.
