### ISSUE TITLE
WSMessageEncoding does not exist in SystemModel namespace

### ISSUE THREAD

**Issue by ZhaodongTian** [dotnet/wcf#5101]
Repro steps:

1. Create Console app and target with 7.0
2. Install below WCF package with latest version: 6.0.0-rc.23205.4
      **PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0-rc.23205.4" 
    PackageReference Include="System.ServiceModel.Federation" Version="6.0.0-rc.23205.4" 
    PackageReference Include="System.ServiceModel.Http" Version="6.0.0-rc.23205.4"
    PackageReference Include="System.ServiceModel.NetTcp" Version="6.0.0-rc.23205.4" 
    PackageReference Include="System.ServiceModel.Security" Version="6.0.0-rc.23205.4" **
3.    Create BasicHttpBinding object and set MessageEncoding 
       System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
       **result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Text;**

Actual Result:

WSMessageEncoding cannot be found 

![image](https://user-images.githubusercontent.com/25213046/232403508-c01f7560-4424-4f96-8d36-9c0f248596bf.png)

**Comment by HongGit** [comment]
This has been fixed in WCF Client 6.0.
