### ISSUE TITLE
dotnet-svcutil: The term 'svcutil' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by noblemfd** [dotnet/wcf#5105]
In my ASP.NET Core-6 Application, I installed dotnet-svcutil Version="1.0.4" using **Package Manage**r. Then still with Package Manager, I decided to integrate the wsdl as shown below:

PM> svcutil https://thirdpartyapi.com/MyService?wsdl

But got this error:

    The term 'svcutil' is not recognized as the name of a cmdlet, function, script file, or operable program

I have successfully done the same thing using connected service. But prefer this method.

How do I get this resolved?

**Comment by imcarolwang** [comment]
Svcutil is for .NET Framework projects, dotnet-svcutil is a command-line tool for generating a web service reference compatible with .NET Core and .NET Standard projects.

According to the description, you are working on .NET Core project, I think you have two options to add service reference to the ASP.NET Core app for the given URI:
1. Use the WCF Connect Service tool from Visual Studio IDE by right clicking on the project name and select "Add" -> "Service Reference" ->"WCF Web Service" -> "Next", then enter the URI, click "Go" and the "Next" buttons to finish the wizard.

2. Alternatively, you can install dotnet-svcutil tool on your machine from a Command Prompt window and run commands as shown below to generate the service reference. [This doc](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) has more details about usage of tool.
> dotnet tool install -g dotnet-svcutil
>dotnet-svcutil  https://thirdpartyapi.com/MyService?wsdl

**Comment by HongGit** [comment]
@noblemfd hopefully your issue is resolved.  Feel free to reactivate the issue if there are more questions.
