### ISSUE TITLE
How to resolveConfiguration files are not supported. at System.ServiceModel.ClientBase`1..ctor() in SWDL SOAP Service in ASP.NET Core

### ISSUE THREAD

**Issue by noblemfd** [dotnet/wcf#5114]
I am given a third party WSDL SOAP Service to consume in ASP.NET Core 6 Web API, and then generate JSON response service.  This is the given WSDL SOAP Service:

    http://thirdpartyapi:3209/SchoolService/SchoolService?WSDL

I consumed it using the two methods at different times, but still the same error:

**method 1:** Service Reference using Connected Service

**method 2:** 

    dotnet tool install -g dotnet-svcutil
    dotnet-svcutil http://thirdpartyapi:3209/SchoolService/SchoolService?WSDL

 I called it `SchoolServiceReference`

So here is part of the generated Service Reference

**DTO**

    public class StudentDetailDto
    {
        public string StudentRef { get; set; }
        public string StudentCode { get; set; }
    }

Then I created Service Interface and Implementation

**EmployeeService - interface:**

    Task<QueryStudentResponse> GetStudentDetailAsync(StudentDetailDto model);

**Implementation:**

    public class StudentDetailService : IStudentDetailService
    {
        private readonly SchoolServiceSEIClient _client;
        public StudentDetailService(
            SchoolServiceSEIClient client
            )
        {
            _client = client;
        }
        public async Task<QueryStudentResponse> GetStudentDetailAsync(StudentDetailDto model)
        {
            var request = new QUERYSTUDENT_REQ();
            request.SCH_HEADER = new SCH_HEADERType();
            request.SCH_HEADER.USERNAME = "username1";
            request.SCH_HEADER.PASSWORD = "password1";

            request.SCH_BODY = new QUERYSTUDENT_BODY
            {
                StudentQ = new StudentQueryType
                {
                    REF = model.StudentRef,
                    COD = model.StudentCode
                }
            };

            var response = await _client.QueryStudentAsync(request);
            return response;
        }
    }

**Note:** QueryStudentResponse is from the Generated Service Reference

**DI:**

        public static class DIServiceExtension
        {
            public static void AddDependencyInjection(this IServiceCollection services)
            {
                services.AddScoped<IStudentDetailService, StudentDetailService>();
                services.AddTransient<SchoolServiceSEIClient, SchoolServiceSEIClient>();
            }
        }

Program.cs:

    builder.Services.AddDependencyInjection();

Then, then controller:

**Controller:**

    [Route("api/[controller]")]
    [ApiController]
    public class StudentController : ControllerBase
    {
        private readonly IStudentDetailService _studentDetailService;

        public StudentController(
            IStudentDetailService studentDetailService
            )
        {
            _studentDetailService = studentDetailService;
        }

        [HttpGet("StudentDetail")]
        public async Task<IActionResult> GetStudentDetailAsync([FromQuery] StudentDetailDto model)
        {
            var result = await _studentDetailService.GetStudentDetailAsync(model);
            return Ok(result);
        }
    }

When I submitted the request on Swagger or POSTMAN (with either HtttPost Or HttpGet request), I got this error

    System.PlatformNotSupportedException: Configuration files are not supported. at System.ServiceModel.ClientBase`1..ctor() at SchoolServiceSEIClient..ctor() in C:\SchoolApp.Common\SchoolService.cs:line 149
`at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)`

It highlights:

    var response = await _client.QueryStudentAsync(request)

Also this is line 149 the error refers to in Generated Service Reference

      public SchoolServiceSEIClient()  { }

You can find below the Generated Service Reference:

```
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://SchoolService.types.ws.gw.thirdpartyapi.com", ConfigurationName="SchoolServiceSEI")]

public interface SchoolServiceSEI
{

    [System.ServiceModel.OperationContractAttribute(Action="http://SchoolService.types.ws.gw.thirdpartyapi.com/SchoolServiceSEI/QueryStudent" +
        "IORequest", ReplyAction="http://SchoolService.types.ws.gw.thirdpartyapi.com/SchoolServiceSEI/QueryStudent" +
        "IOResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    QueryStudentResponse QueryStudent(QueryStudentRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://SchoolService.types.ws.gw.thirdpartyapi.com/SchoolServiceSEI/QueryStudent" +
        "IORequest", ReplyAction="http://SchoolService.types.ws.gw.thirdpartyapi.com/SchoolServiceSEI/QueryStudent" +
        "IOResponse")]
    System.Threading.Tasks.Task<QueryStudentResponse> QueryStudentAsync(QueryStudentRequest request);
}
```

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryStudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thirdpartyapi.com/service/SchoolService", Order=0)]
        public QUERYSTUDENT_REQ QUERYSTUDENT_REQ;
        
        public QueryStudentResponse()
        {
        }
        
        public QueryStudentResponse(QUERYSTUDENT_REQ QUERYSTUDENT_REQ)
        {
            this.QUERYSTUDENT_REQ = QUERYSTUDENT_REQ;
        }
    }
       
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thirdpartyapi.com/service/SchoolService")]
    public partial class QUERYSTUDENT_REQ
    {
        
        private SCH_HEADERType sCH_HEADERField;
        
        private QUERYSTUDENT_BODY sCH_BODYField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SCH_HEADERType SCH_HEADER
        {
            get
            {
                return this.sCHHEADERField;
            }
            set
            {
                this.sCH_HEADERField = value;
            }
        }     
    
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QUERYSTUDENT_BODY SCH_BODY
        {
            get
            {
                return this.sCH_BODYField;
            }
            set
            {
                this.sCH_BODYField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thirdpartyapi.com/service/SchoolService")]
    public partial class SCH_HEADERType
    {
        private string uSERNAMEField;
        private string pASSWORDField;
        private SCH_HEADERTypePARAM[] aDDLField;
    
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string USERNAME
        {
            get
            {
                return this.uSERNAMEField;
            }
            set
            {
                this.uSERNAMEField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PASSWORD
        {
            get
            {
                return this.pASSWORDField;
            }
            set
            {
                this.pASSWORDField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://thirdpartyapi.com/service/SchoolService")]
    public partial class QUERYSTUDENT_BODY
    {
        
        private StudentQueryType studentField;
        
        [System.Xml.Serialization.XmlElementAttribute("StudentQ", Order=0)]
        public StudentQueryType StudentQ
        {
            get
            {
                return this.studentField;
            }
            set
            {
                this.studentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CustAcc-Query-IO-Type", Namespace="http://thirdpartyapi.com/service/FCUBSAccService")]
    public partial class StudentQueryType
    {
        
        private string eMPField;
        
        private string dEPField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string REF
        {
            get
            {
                return this.rEFField;
            }
            set
            {
                this.rEFField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COD
        {
            get
            {
                return this.cODField;
            }
            set
            {
                this.cODField = value;
            }
        }
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<QueryStudentResponse> SchoolServiceSEIClient.QueryEmployeeAsync(QueryStudentRequest request)
    {
        return base.Channel.QueryStudentAsync(request);
    }
    
    public System.Threading.Tasks.Task<QueryStudentResponse> QueryStudentAsync(QUERYSTUDENT_REQ)
    {
        QueryStudentRequest inValue = new QueryStudentRequest();
        inValue.QUERYSTUDENT_REQ = QUERYSTUDENT_REQ;
        return ((SchoolServiceSEIClient)(this)).QueryStudentAsync(inValue);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryStudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thirdpartyapi.com/service/SchoolService", Order=0)]
        public QUERYSTUDENT_RES QUERYSTUDENT_RES;
        
        public QueryStudentResponse()
        {
        }
        
        public QueryStudentResponse(QUERYSTUDENT_RES QUERYSTUDENT_RES)
        {
            this.QUERYSTUDENT_RES = QUERYSTUDENT_RES;
        }
    }

    public partial class SchoolServiceSEIClient : System.ServiceModel.ClientBase<SchoolServiceSEI>, SchoolServiceSEI
    {
        
        public SchoolServiceSEIClient()
        {
        }
        
        public SchoolServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SchoolServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SchoolServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SchoolServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
    
       [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QueryStudentResponse SchoolServiceSEI.QueryStudent(QueryStudentRequest request)
        {
            return base.Channel.QueryCustAccIO(request);
        }
        
        public QUERYSTUDENT_RES QueryStudent(QUERYSTUDENT_REQ QUERYSTUDENT_REQ)
        {
            QueryStudentRequest inValue = new QueryStudentRequest();
            inValue.QUERYSTUDENT_REQ = QUERYSTUDENT_REQ;
            QueryStudentResponse retVal = ((SchoolServiceSEI)(this)).QueryStudent(inValue);
            return retVal.QUERYSTUDENT_RES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueryStudentResponse> SchoolServiceSEI.QueryStudentAsync(QueryStudentRequest request)
        {
            return base.Channel.QueryStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueryStudentResponse> QueryStudentAsync(QUERYSTUDENT_REQ QUERYSTUDENT_REQ)
        {
            QueryStudentRequest inValue = new QueryStudentRequest();
            inValue.QUERYSTUDENT_REQ = QUERYSTUDENT_REQ;
            return ((SchoolServiceSEI)(this)).QueryStudentAsync(inValue);
        }
    }

How do I sort this out?

**Comment by mconnew** [comment]
I want to bring your attention to a behavior change in .NET [Core] that is likely to cause you problems once you get your code to production. Generated clients on .NET Framework use configuration which means they can safely cache a single ChannelFactory instance. On .NET we don't have config support so the generated client uses code based configuration. As there's no deterministic way to know if two code based bindings are identical, caching is off by default. This means each client instance creates a new instance of ChannelFactory. The Http connection pooling is in .NET is also different. In .NET Framework the pool is process wide. In .NET, it's scoped to an HttpClientHandler instance. Each ChannelFactory instance creates a new HttpClientHandler instance. As you are using Scoped or Transient lifetime for the client, this means every incoming request will result in a new ChannelFactory instance (which are quite heavy weight), and a new connection pool. You are likely to exhaust your outgoing ports as you are effectively disabling connection pooling.  
There are two things you could do. Either change the scope of the generated client to be Singleton, or at the start of your app before any instances have been created, call `SchoolServiceSEIClient.CacheSetting = CacheSetting.AlwaysOn;`. This will say even though technically an instance could be created with a different binding and/or endpoint, you aren't going to do that so cache a single ChannelFactory across all client instances, which means a single connection pool across all instances.

**Comment by HongGit** [comment]
Close this as there is no more response.  Feel free to reactivate the issue if there are more questions.
