### ISSUE TITLE
`--noStdLib` seems to do nothing

### ISSUE THREAD

**Issue by ThaDaVos** [dotnet/wcf#5126]
**Describe the bug**

When I generate a ServiceReference with `dotnet-svcutil` - it doesn't matter if I use `--noStdLib` or not - the added references are always:
```XML
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.Federation" Version="4.10.*" />
  </ItemGroup>
```

My full command: `dotnet-svcutil https://soap.e-boekhouden.nl/soap.asmx?wsdl -d Externals\EBoekhouden -o EBoekhouden -i --serializer DataContractSerializer --sync -n "*,MyProject.Externals.EBoekhouden"`

**To Reproduce**
1. Ideally a sample project that we can debug.
2. Full call stacks.
3. For issues related to generating client code using dotnet-svcutil please provide the WSDL.

**Expected behavior**
A difference in the references added to the project - based on the option description, it should de something different from `System.ServiceModel.*`

**Screenshots**

**Additional context**
Used Latest DotNet 7

**Comment by imcarolwang** [comment]
@ThaDaVos thanks for raising the issue. 

If option `--noStdLib` is not applied, the tool references standard library assemblies during code generation. Specifically, if the tool finds any types that belong to the standard library, those types will be reused and not get generated.

If option `--noStdLib` is applied, the tool is unaware of any types coming from standard library assemblies, so if detected in use those types will be generated by the tool.

This option does not determine whether the context project would add wcf package references or not. And you will only observe difference when types from standard libraries are used as DataContract/DataMember in the target service.

Hope this clarifies what this option is for.

**Comment by HongGit** [comment]
Close due to no recent response.  Feel free to reactivate if this is still an issue for you.
