### ISSUE TITLE
Could not load type 'System.ServiceModel.Configuration.ConfigurationChannelFactory`1' 

### ISSUE THREAD

**Issue by CarlosPolastro** [dotnet/wcf#5156]
TypeLoadException: Could not load type 'System.ServiceModel.Configuration.ConfigurationChannelFactory`1' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**To Reproduce**
1. Create a blazor project (.Net 7).
2. Add package 'System.ServiceModel.Primitives'
2. Try to Instantiate class 'ConfigurationChannelFactory'

ConfigurationChannelFactory<T> channelFactory = new ConfigurationChannelFactory<T>(configName, PluginConfig, null);

**Expected behavior**
System should be able to instantiate class 'ConfigurationChannelFactory'

**Comment by HongGit** [comment]
@CarlosPolastro ConfigurationChannelFactory is not supported in .NET [Core]. If you are trying use Blazor with WASM, instantiate a WCF client in the browser, issue(#77405) blocks this scenario.
