### ISSUE TITLE
Calling `TypedMessageConverter.Create` throws `NullReferenceException` in v6.0.0

### ISSUE THREAD

**Issue by huaxing-yuan** [dotnet/wcf#5163]
**Describe the bug**
In one of my dotnet core project, I'm using `dotnet-svcutil` to generate proxy classes and use `TypedMessageConverter.ToMessage` to generate SOAP Message from objects. Following method is used to create TypedMesssageConverter, it works with package `System.ServiceModel.Http` 4.10.2 and below.

```Csharp
TypedMessageConverter.Create(objectType, null, new XmlSerializerFormatAttribute
{
    Style = OperationFormatStyle.Document,
    SupportFaults = true
});
```
But after upgrading the package `System.ServiceModel.Http` to 6.0.0, the above code throws `NullReferenceException`.
After analyzing, it seems the exception has been thrown from here:

https://github.com/dotnet/wcf/blob/4516dc40041e866cbfbdc819773929e1edfe236d/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs#L1318

because the variable `messageContractAttribute` is null:
https://github.com/dotnet/wcf/blob/4516dc40041e866cbfbdc819773929e1edfe236d/src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs#L1305

**To Reproduce**
1. Create a typedmessageconverter using above code, given objectType a class name of ServiceContract, generated by dotnet-svcutil.
2. Use nuget package `System.ServiceModel.Http` 4.10.2 => OK
3. update to `System.ServiceModel.Http` 6.0.0 => NullPointerException.

**Expected behavior**
The v6.0.0 package should work as v4.10.2

**Screenshots**
![image](https://github.com/dotnet/wcf/assets/37816968/5024d632-6c7f-47a7-8c02-a57bf9ca1e3f)

**Comment by HongGit** [comment]
@imcarolwang can you please see if you could repro this?

**Comment by huaxing-yuan** [comment]
Hi @imcarolwang : Sorry for the late reponse. I didn't have received the notification. I reinstalled the 6.0.0 package to reproduce the error:

The following code snippet is what I used to serialize Soap Messages from given type. In this case, the type os `GetBookingInfoByIdRequest` which is generated from WSDL. It has `MessageContractAttribute`.

![image](https://github.com/dotnet/wcf/assets/37816968/df8512c0-9d35-4654-a938-540dc7d0f8e8)

If I dig further via reflection, this attribute is defined in: `System.Private.ServiceModel`, because the class GetBookingInfoByIdRequest was generated previously and compiled into an assembly.
I’ll Try to reproduce it in a simple project and let you know.

From the github souce, I'm able to find two `MessageContractAttribute`, one from System.Private.ServiceModel, another from `System.ServiceModel.Primitives`
<img width="345" alt="image" src="https://github.com/dotnet/wcf/assets/37816968/99f325aa-4db8-48ba-aee2-949912176505">

**Comment by huaxing-yuan** [comment]
OK, I made some further research and I confirm the pb is caused by `MessageContractAttribute` defined in different assemblies
## Context:
I use `dotnet-svcutil` to generate C# proxies, then compile it using Roslyn compiler.

In previous versions of ServiceModel, in order to compile generated Proxy Code, I have referenced several assemblies including `System.ServiceModel.Primitives.dll`, `System.Private.ServiceModel.dll` and `System.ServiceModel.dll`

After upgrading `System.ServiceModel.Http` to 6.0.0 this part of code failed to 2 reasons:
- `System.ServiceModel.dll` cannot be found
- Many classes are defined in both `System.ServiceModel.Primitives.dll` and `System.Private.ServiceModel.dll` 

I think the main reason of this bug is that `MessageContractAttribute` is defined in both assemblies, and unfortunately, my compiled code refers the former, but in TypeConverter it refers the latter.

## Workaround
On my side, I can remove the reference to `System.PrivaQe.ServiceModel.dll` and `System.ServiceModel.dll`. The generated code compiles so far (I will try to compile more proxy code generated from different WSDL definitions to confirm) and when loading compiled assembly, Type converter works perfectly.

## Conclusion
I suggest this issue is introduced by this rename:
<img width="949" alt="image" src="https://github.com/dotnet/wcf/assets/37816968/2b563f5c-e41b-42d0-9b53-42916323e219">

If you are compiling new assemblies from generated C# proxy, there will be no issue.
But *any previously compiled assemblies* containing `MessageContractAttribute` won't work anymore.

**Comment by imcarolwang** [comment]
@huaxing-yuan thanks for your update and glad to know that you found a workaround!

`System.ServiceModel.dll` is supposed to be used by full .NET Framework target project only, WCF Client releases previously targeted .NET Standard 2.0 to support both .NET (Core) and .NET Framework, start from 6.0, the WCF client packages moved targets to .NET 6. Your problem is likely a side-effect of this breaking change which could be found recorded at https://learn.microsoft.com/en-us/dotnet/core/compatibility/wcf-client/6.0/net-standard-2-support. 

By the way, you also don't need to directly reference `System.Private.ServiceModel.dll `in your project as it will be restored automatically by the project when you are referencing any WCF feature packages which has a dependency on it.

**Comment by huaxing-yuan** [comment]
Thanks @imcarolwang for the clarification, I know better the history now.
Yes, i removed the reference of these 2 dlls and it works now. There are some assemblies of the software components compiled before upgrading to 6.0.0, but i can manage to re-compile them.   

If you permit we can close the issue.
Thanks again for your detailed explanation !

**Comment by imcarolwang** [comment]
@huaxing-yuan, glad to help. I am closing the issue 😃
