### ISSUE TITLE
Error trying to upgrade System.ServiceModel.Http and System.ServiceModel.Primitives packages from 4.10.2 version to 6.0.0

### ISSUE THREAD

**Issue by vkirienko** [dotnet/wcf#5164]
Hi,

I'm getting error trying to upgrade System.ServiceModel.Http and System.ServiceModel.Primitives packages from 4.10.2 version to 6.0.0 in .NET 4.8 project.

Could not install package 'System.ServiceModel.Http 6.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

Regards,
Vlad Kirienko

**Comment by HongGit** [comment]
@vkirienko please refer [this doc](https://learn.microsoft.com/en-us/dotnet/core/compatibility/wcf-client/6.0/net-standard-2-support#recommended-action) for recommended actions.
