### ISSUE TITLE
Add IMetadataExchange to WCF core

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/wcf#5185]
Consider bring IMetadataExchange to wcf core.

**Note**
In .NET Framework, IMetadataExchange is indirectly used by svcutil.exe which use MetadataExchangeClient to retrieve metadata from WCF service mex endpoint, MetadataExchangeClient uses IMetadataExchange.

**Comment by HongGit** [comment]
Thanks for logging this issue!

After discussion with folks, we could leave IMetadataExchange out of WCF Client as of now.
