### ISSUE TITLE
System.ServiceModel.Primitives has a vulnerable dependency

### ISSUE THREAD

**Issue by ondrokrc** [dotnet/wcf#5190]
**Describe the bug**
The most recent version 6.0.0 System.ServiceModel.Primitives depends on System.Security.Cryptography.Xml >= 6.0.1, which depends on System.Security.Cryptography.Pkcs >= 6.0.1 (for .NET Standard 2.0). This package is vulnerable in this version: https://www.nuget.org/packages/System.Security.Cryptography.Pkcs/6.0.1.

**Expected behavior**
A new version of System.ServiceModel.Primitives without vulnerable dependencies.

Thank you.

**Comment by Ismael-Pep** [comment]
There isn´t a patched stable version of System.Security.Cryptography.Xml that resolves this issue, so System.Security.Cryptography.Pkcs-6.0.3 should be reference directly in the csproj.

**Comment by HongGit** [comment]
Thanks for raisin this issue with use!  Please refer to [this](https://github.com/dotnet/runtime/issues/68931#issuecomment-1125260283) as why WCF packages are not impacted.
