### ISSUE TITLE
Polly policy with generated WCF client

### ISSUE THREAD

**Issue by OleksandrBorovenskyi** [dotnet/wcf#5198]
Hi,

Since WCF Core autogenerated client uses `HttpClient` under the hood.
I am wondering whether there is an opportunity to use resilience policies from Polly library along with that `HttpClient`?

----
Just to add a bit more to the context.
Currently, I do
1) register a retry policy in the DI container:
```
services
            .AddScoped<IAsyncPolicy, AsyncRetryPolicy>(sp =>
            {
                var logger = sp.GetRequiredService<ILogger<AsyncRetryPolicy>>();

                return Policy
                    .Handle<Exception>(ex => ex is not FaultException)
                    .WaitAndRetryAsync(
                        sleepDurations,
                        (ex, _, retryCount, _) =>
                        {
                            var remaining = sleepDurations.Length - retryCount + 1;
                            logger.LogWarning(
                                "Remaining attempts: {RemainingAttempts}. Request to ... failed with error:{ErrorMessage}",
                                remaining, ex.Message);
                        });
            });
```

2) Inject it inside the service that utilizes generated WCF client:
```
var result = await _policy.ExecuteAsync(() => soapClient.CallSomeWcfService(key));
```

And the problem is that inside the unit test, I can not mock call of the policy totally.
I can only specify that the policy with parameter `Func<Task<SoapOperationResult>>` is called.
But can not specify the exact method of generated SOAP client with exact parameters.

That's why I think would be good to encapsulate a resilience policy inside Wcf client if it is possible.
Somewhere along with `HttpClient` that is used under the hood.

Thanks in advance

**Comment by peterkiss1** [comment]
First thing to read: [Realization of the connections pool with WCF for .Net Core with usage of HttpClientFactory](https://medium.com/trueengineering/realization-of-the-connections-pool-with-wcf-for-net-core-with-usage-of-httpclientfactory-c2cb2676423e)
From this it is easy to preconfigure in the DI a named HttpClient for your services and from there you can simple add the Polly things just as for regular services, you only have to make sure you are injecting the right handler into your WCF service call by referring to the right name on creating the request handler.

**Comment by OleksandrBorovenskyi** [comment]
@peterkiss1,
Thanks, it works.

The only minor suggestion.
There is no need for the field of type `Func` in the custom Endpoint Behavior class.
We can keep `HttpMessageHandler`
