### ISSUE TITLE
How to create Custom ServiceHostFactory in CoreWCF

### ISSUE THREAD

**Issue by pascalrebello** [dotnet/wcf#5201]
How to create Custom ServiceHostFactory in CoreWCF

In the case of WCF  we can extend it by using  ServiceHostFactory and SeviceHost.

And finally mentioning the Factory in the .SVC file  like this (<% @ ServiceHost Language="C#" Service="WcfService1.Service1" 
                 **Factory="WcfService1.MyWebServiceHostFactory"** %>

So similar way how we can implement this in CoreWCF? Kindly share your valuable suggestions.

**Comment by mconnew** [comment]
Closing in preference of the CoreWCF issue CoreWCF/CoreWCF#1151
