### ISSUE TITLE
.NET 8 breaks NetTcp with certificate auth

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#5205]
A recent change was made to SslStream which calls Stream.Read on the inner stream with a zero byte buffer. The intention is to cheaply detect when a stream has data available. This is an undocumented expectation and at least some of the WCF Stream implementations throw on argument validation as we explicitly reject a zero byte read. The easy solution is to add this code to the top of every Read (or Read variant like ReadAsync) implementation:
```c#
if (count == 0 return 0;
```
There are a couple of Stream implementations that we shouldn't change. Those are the framing streams in NetFramingBase.

**Comment by mconnew** [comment]
This needs to be back ported to the latest 4.x release too as that can be run on .NET 8 as well.

**Comment by brandonagr** [comment]
Is there an update on the work for this? This issue prevents us from testing out net8 rc1

**Comment by kanchansingh1214** [comment]
I receive the same issue when testing .net8 rc1. 
The logic fails at `ReadAsync` method in `SocketConnection.cs` file where the buffer length is zero and it throws an exception 
This works in .net 7 and below and is an issue starting with .net 8
