### ISSUE TITLE
TimeoutException message implies the logged time is _elapsed time_, but the logged value is actually _remaining time_

### ISSUE THREAD

**Issue by deadalusai** [dotnet/wcf#5220]
**Describe the bug**
See this block of code in `RequestChannel` which handles `TimeoutExceptions` which may be raised.

https://github.com/dotnet/wcf/blob/ff278d72765b420fd3be41904e526395e9d3dd90/src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/RequestChannel.cs#L264-L285

As the routine proceeds it keeps track of a variable `TimeSpan savedTimeout` to which it re-assigns `timeoutHelper.RemainingTime()` periodically. If a `TimeoutException` is raised then this `savedTimeout` value is passed as a format argument to either `SRP.RequestChannelSendTimedOut` or `SRP.RequestChannelWaitForReplyTimedOut` which both interpret the format argument as an _elapsed_ period of time

> "The request channel timed out attempting to send after {0}."
> "The request channel timed out while waiting for a reply after {0}."

Because the value passed in is actually a calculated time remaining until the configured timeout has elapsed, error messages produced by this code often logs confusingly low times, implying that the request timed out very quickly. E.g. for a request that timed out on the server-side just inside 60 seconds, this code logged:

> System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:00.0660043. 

**To Reproduce**
1. Set up a WCF client/server pair using basic HTTP bindings
2. Configure the client to timeout after e.g. 30 seconds
3. Configure the server to respond with a 504 Gateway Timeout status code after e.g. 5 seconds
4. See the logged timeout error message logs an unexpectedly high "elapsed time" of something near 25 seconds

Alternatively:
1. Set up a WCF client/server pair using basic HTTP bindings
2. Configure the client to timeout after e.g. 10 seconds
3. Configure the server to respond after e.g. 15 seconds
4. See the logged timeout error message logs an unexpectedly low "elapsed time" of something near 0 seconds

**Expected behavior**
The exception message should log `ElapsedTime` instead of `RemainingTime`.

**Additional context**
Full WCF stack trace from our application:
```
System.TimeoutException: The request channel timed out while waiting for a reply after 00:00:00.3965133. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
 ---> System.TimeoutException: GatewayTimeout GATEWAY_TIMEOUT
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateResponseStatusCode()
   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location ---
```

And our (approximate) client configuration:
```csharp
var address = new EndpointAddress("https://example.com/example"]);
var binding = new BasicHttpBinding(BasicHttpSecurityMode.None);
binding.MaxBufferSize = int.MaxValue;
binding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
binding.MaxReceivedMessageSize = int.MaxValue;
binding.AllowCookies = true;
binding.SendTimeout = TimeSpan.FromMilliseconds(60000);
binding.OpenTimeout = TimeSpan.FromMilliseconds(30000);
binding.CloseTimeout = TimeSpan.FromMilliseconds(30000);
var channelFactory = new ChannelFactory<IExampleChannel>(binding, address);
var channel = channelFactory.CreateChannel();
```

**Comment by mconnew** [comment]
The exception message includes this at the end:

> The time allotted to this operation may have been a portion of a longer timeout.

This is to indicate the possibility of the behavior you are seeing. WCF is really extensible and there's no way to pass original timeout from the initial code which handles sending a request all the way through to the code at the end of the chain which timed out an IO operation. The best any component can do is report the timeout value that it was passed.  

We don't even have the ability to just repeat the binding timeouts as you can cast the channel to IClientChannel and set OperationTimeout which will modify the send timeout for the specific channel. That's the timeout which is initially used as it's passed through the layers, with the remaining time after each step has done its work passed to the next layer.

If you need to log an accurate time of how long the operation took to timeout, you should use a Stopwatch instance to record the time it took to make the call, catch a TimeoutException and log your own timing.

**Comment by deadalusai** [comment]
Hi @mconnew I think you've misinterpreted my bug report. I'm specifically interested in the first part of the exception messages which include the formatted "time" value in question. Those are:
```
"The request channel timed out attempting to send after {0}."
"The request channel timed out while waiting for a reply after {0}."
```

This means the formatted value should indicate a period of time elapsed, e.g. "The request channel timed out while waiting for a reply after {29.5 seconds elapsed}."

However, the code as written is passing in a "time remaining" value, calculated by subtracting time elapsed from the client's configured timeout value (e.g. 30 seconds). As such the logged exception message is something like "The request channel timeout out while waiting for a reply after {0.5 seconds remaining}" which is a nonsense sentence.

I believe fixing this bug may be as simple as passing `timeoutHelper.ElapsedTime()` instead of `timoutHelper.RemainingTime()` as these messages are calculated entirely using client-side state.
