### ISSUE TITLE
Customer report MessageParameterAttribute for return response not working

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#527]
We expose MessageParameterAttribute in the contract. We need to investigate if this is a bug.

Customer report below does not get deserialized
[System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
[return: System.ServiceModel.MessageParameterAttribute(Name = "result")]
Task<LoginResult> loginAsync(string username, string password);

However if the customer change the response SOAP XML, result node to loginResult, it works.

**Comment by BadriL** [comment]
Any rough idea you have related to when a NuGet package with this fix be available for us to use, please?
