### ISSUE TITLE
ServiceChannelProxy should implement both IAsyncCommunicationObject and IAsyncDisposable

### ISSUE THREAD

**Issue by 0xced** [dotnet/wcf#5270]
It seems to me that the `ServiceChannelProxy` class should implement the `IAsyncCommunicationObject` and `IAsyncDisposable` interfaces. I was surprised to learn that it currently doesn't.

The implementation looks trivial to me since the underlying `ServiceChannel` object already implements both interfaces.

```csharp
async Task IAsyncCommunicationObject.CloseAsync(TimeSpan timeout)
{
    await ((IAsyncCommunicationObject)_serviceChannel).CloseAsync(timeout);
}

async Task IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
{
    await ((IAsyncCommunicationObject)_serviceChannel).OpenAsync(timeout);
}

async ValueTask IAsyncDisposable.DisposeAsync()
{
    await ((IAsyncDisposable)_serviceChannel).DisposeAsync();
}
```

Is there any risk in adding those two interfaces to `ServiceChannelProxy` ?

**Comment by HongGit** [comment]
@0xced thanks for the suggestion!  It's not trivial to support these, we will consider this in future releases.

**Comment by mconnew** [comment]
See [comment here](https://github.com/dotnet/wcf/issues/5269#issuecomment-1701896425) for details of why this is difficult.

**Comment by 0xced** [comment]
Actually, I would already be very happy with just `IAsyncDisposable`.

Ignoring the `IAsyncCommunicationObject` part, is there any risk in making `ServiceChannelProxy` implement `IAsyncDisposable` like this?

```csharp
ValueTask IAsyncDisposable.DisposeAsync()
{
    return ((IAsyncDisposable)_serviceChannel).DisposeAsync();
}
```

So that channels created through a `ChannelFactory<T>` without inheriting from `ClientBase<T>` would also benefit from the asynchronous disposal improvements introduced in https://github.com/dotnet/wcf/pull/4865.
