### ISSUE TITLE
System.ServiceModel.HostNameComparisonMode claims it is defined in System.ServiceModel.Primitives, but it is not found

### ISSUE THREAD

**Issue by rbeurskens** [dotnet/wcf#5292]
Trying to move from .net framework to .net60, a project using the HttpTransportBindingElement.HostnameComparisonMode property, fails to build saying the System.ServiceModel.HostNameComparisonMode enum is not found in System.ServiceModel.Primitives 6.0
(This property was in .NET Framework, but was not defined in <6 versions of this package. It is now, but there seems to be a problem with the property type?)

**Comment by HongGit** [comment]
@rbeurskens thanks for reporting this!  

It's a bug, and it will be fixed in upcoming release.

@imcarolwang  please add this to primitives, and log an issue to remove the property and the enum in .NET 8.0 release.
