### ISSUE TITLE
How do i disable Wrapping ? 

### ISSUE THREAD

**Issue by Montago** [dotnet/wcf#5295]
I have a .NET Framework 4.8 WCF service with tons of methods.

I'm consuming the WCF Service in a new WPF .NET Core 6 project. 

One of them receives and Integer and might return a list of objects. 

Using the dotnet-svcutil (or svcutil or Connected Services in VS2022) I'm getting methods that wrap all messages in Requests and Response objects

eg GetList(int id) turns into 

public CatalogService.GetEngineListResponse GetEngineList(CatalogService.GetEngineListRequest request)
{
    return base.Channel.GetEngineList(request);
}

Even methods that already have a MessageContract wraps the contract into another contract !!!

I've tried using "wrapped = false" but it makes no difference.

**Comment by Montago** [comment]
found this similar issue 
https://github.com/dotnet/wcf/issues/2670

**Comment by Montago** [comment]
so .. instead of 

```
    data = await ClientInstance.Instance.Client.GetBrandsModelsAndTypesAsync();
```
I need to do 

```
    data = (await ClientInstance.Instance.Client.GetBrandsModelsAndTypesAsync(new GetBrandsModelsAndTypesRequest())).GetBrandsModelsAndTypesResult;
```

**Comment by mconnew** [comment]
What does the service side operation look like? Are you using a MessageContract there?

**Comment by Montago** [comment]
Hi @mconnew 

This is a typical method in the SVC: 

```
    // Interface part: 
    [OperationContract]
    List<ModelTillaegsbetegnelser> GetModelTillaegsbetegnelser();

    // Implementation 
    [PrincipalPermission(SecurityAction.Demand, Authenticated = true)]
    public List<ModelTillaegsbetegnelser> GetModelTillaegsbetegnelser()
    {
        using (var db = new BilregisterEntities())
        {
            return db.ModelTillaegsbetegnelser.ToList();
        }
    }
```

**Comment by Montago** [comment]
I just tried adding MessageContract attribute on the response object that i had made. 

after updating the servicereference, the returntype of the method now correctly corrosponds to my DTO response object. 

The method still expect an empty Request object 🙄 

So i guess that the difference between the Framework 4.x SVCUTIL and Core SVCUTIL is that Framework 4x had implicit MessageContract  mapping between and that Core is explicit...

**Comment by Montago** [comment]
Looking at the WSDL (from the Framework 4.8 WCF Service) i can see that WCF has always wrapped Request  / Response objects 

So the conclusion is that SVCUTIL for Framework 4.7 unwraps these messages automatically. 
while SVCUTIL for .NET 6  / Core - does not. 

```
<xs:element name="UpdateKoeretoejModelVariantAargangstabelResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q47="http://schemas.datacontract.org/2004/07/Modelkatalog.ServiceCore.Bilregister" minOccurs="0" name="UpdateKoeretoejModelVariantAargangstabelResult" nillable="true" type="q47:KoeretoejModelVariantAargangstabel"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetEngineVersionSupport">
<xs:complexType>
<xs:sequence/>
</xs:complexType>
</xs:element>
<xs:element name="GetEngineVersionSupportResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q48="http://schemas.datacontract.org/2004/07/Modelkatalog.ServiceCore.Contracts" minOccurs="0" name="GetEngineVersionSupportResult" nillable="true" type="q48:EngineVersionSupportContract"/>
</xs:sequence>
</xs:complexType>
</xs:element>
```

**Comment by Montago** [comment]
I've attached the WSDL .. 

GetEngineVersionSupport method returns the EngineVersionSupportContract DTO which i have decorated with MessageContract. GetEngineVersionSupport has no parameters. 

CarModelSearch returns CarModelSearchContract DTO which have NOT been decorated. 
CarModelSearch  has a parameter of CarModelSearchContract DTO 

I cant seem to notice the difference in the XML that would indicate why one method wraps the DTO and the other doesnt. 

[CatalogService.zip](https://github.com/dotnet/wcf/files/12828000/CatalogService.zip)

**Comment by DenniYue** [comment]
Got the same issue today when adding async WCF client. But I found by checking the generate synchronous code checkbox in VS add WCF service tool generated correct code without wrapped parameters.
Seems the tool itself already supported unwrap but somehow only works for VS when synchronous codes also generated.

https://github.com/dotnet/wcf/tree/main/src/dotnet-svcutil
`"sync": true` in ConnectedService.json

Works in VS2022 professional edition with .Net 8

**Comment by Montago** [comment]
I think what you mean is 

"messageContract": true, -> should be removed or false. 

"sync" : true refers to "create Synchronous methods" instead of only async. 

Ill check it out.

**Comment by GitClickOk** [comment]
@Montago, I am with the same problem, VS2022, but I set "messageContract": false and "sync" : true, and these options are ignored, Visual Studio keeps creating wrapped params... 

I try to use the dotnet svc tool, and I "forced" these params in settings file, including the "wrapped" param to false:
```
{
  "providerId": "Microsoft.Tools.ServiceModel.Svcutil",
  "version": "8.0.0",
  "options": {
    "inputs": [
      "http://mydomain/MyService.svc?wsdl"
    ],
    "outputFile": "Reference.cs",
    "targetFramework": "net9.0",
    "typeReuseMode": "All",
    "sync": true,
    "messageContract": false,
    "wrapped": false,
    "namespace": "*,MyNamespace"
  }
}
```

is there some tip, or something else you did it then it works?
