### ISSUE TITLE
Create new Xunit trait attributes to categorize tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#53]
We will want to be able to run (or exclude) subsets of unit and scenario tests by category independent of their CSPROJ grouping.  I believe the best approach is to define our own xunit trait attributes and attach them to the tests.  This is consistent with what is being proposed in CoreFx Issue https://github.com/dotnet/corefx/issues/1477 and will allow filtering in or out tests by category.

Let's use this current issue to first propose what test categories we need, then we can create the PR to implement and apply them.  Note that the current build tools categorize OuterLoop tests using an xunit trait attribute, but that may change.  If it does change, it is not expected to affect our use of our own traits.

**Comment by zhenlan** [comment]
Close this for now. We may need this when we have much larger test bed and only want to run a subset of targeted tests for particular changes.
