### ISSUE TITLE
Find solutions to deal with the CRL caching to avoid this 2 minute wait

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#533]
Currently we set CRL cache to refresh every 2 minutes. Thus the CRL test need to wait for 2 minutes to ensure it's updated.

This issue is to either find the solution, or work around it by changing the test to make a call to the service in a short period of time in a loop and times out in 2 minutes.

**Comment by hongdai** [comment]
A potential solution is to pre-create this specific revoked Cert in bridge start up and wait for 2 minutes in bridge start up script. It also has the advantage to isolate set up issue from test running time.

**Comment by iamjasonp** [comment]
I think I have a solution to this - it involves mucking with the CRL URI baked into the cert, but I haven't yet had a chance to test this. 

Another possible solution is to create the cert, immediately revoke it, and somehow ensure that this test is the first to run.

**Comment by iamjasonp** [comment]
Commit 9fa49e3 adds support for this - @hongdai, can you please take a look? 
Sorry, I was doing two things at once and didn't end up splitting the change from the #422 test.

**Comment by hongdai** [comment]
The change looks good, other than the test has a 2 minutes delay that needs to be removed before enabling it. I'll take care of it.
