### ISSUE TITLE
WCF self hosting in Service Fabric - The HTTP service located at https://....  is unavailable

### ISSUE THREAD

**Issue by ranjeetkpGit** [dotnet/wcf#5338]
Hi I have a WCF service self hosted in Service Fabric on prem. 
One of my application has following requirements

1. Call Create Endpoint
Wait 2 mins
2. Call Search Endpoint
Wait 1 min
4. Call Update Endpoint
Wait 2 mins
6. Call Search Endpoint 

Sometimes it works fine but most of the time I am getting

The HTTP service located at https://..................................... is unavailable.  This could be because the service is too busy or because no endpoint was found listening at the specified address. Please ensure that the address is correct and try accessing the service again later.

It is very unpredictable and can fail at any step given above

Using 

.NET 4.8
var binding = new CustomBinding();
var security = SecurityBindingElement.CreateUserNameOverTransportBindingElement();

**Comment by imcarolwang** [comment]
This repository contains the client-oriented WCF libraries that enable applications built on **.NET Core** to communicate with WCF services. You are having issues on **.NET Framework**, can you please log the issue at  [https://developercommunity.visualstudio.com/VisualStudio](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2FVisualStudio&data=05%7C01%7Cv-carwan%40microsoft.com%7Ccff759de713242ccac0508dbb973057b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638307675921481524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uQpYPrBSSLcDY1WfT2h2uZviUDlDnK28v8%2BhQoSWZmk%3D&reserved=0) instead? Thanks!
