### ISSUE TITLE
I cannot install dotnet-svcutil 1.1.0-preview with .NET 7.0

### ISSUE THREAD

**Issue by cedriccullingworth** [dotnet/wcf#5339]
I am trying to install dotnet-svcutil with a .NET 7.0 project but failing to, with variations of this error:

NU1202	Package dotnet-svcutil 2.2.0-preview1.23462.5 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package dotnet-svcutil 2.2.0-preview1.23462.5 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net7.0 (.NETCoreApp,Version=v7.0) / any	

I'm trying to install svcutil to solve this problem with trying to add an EF core migration: dotnet : Unable to generate deps.json, it may have been already generated.

**Comment by imcarolwang** [comment]
@cedriccullingworth Thank you for raising the issue.

I tried the latest version of the tool and can't repro the error on my machine with .net7.0 installed.

dotnet-svcutil works as a .NET CLI tool, so you should install it as described at https://www.nuget.org/packages/dotnet-svcutil:
e.g. `dotnet tool installation --global dotnet-svcutil --version 2.2.0-preview1.23462.5`

You can also check the output of "dotnet --info" to make sure the required .net version is installed (in this case .net7.0).
If .net7.0 exists and dotnet-svcutil is installed as a global tool, but the problem persists, can you share the steps to reproduce it for us to look at further? Thanks!

**Comment by cedriccullingworth** [comment]
Good day

 

I resolved my problem by using the dotnet-ef command line commands, so this didn’t bring my development to a complete halt!

 

Thanks for the prompt response.

 

Regards

 

Cedric Cullingworth

**Comment by HongGit** [comment]
Good to see that your issue is resolved.
