### ISSUE TITLE
Do channels created from ChannelFactory experiance any DNS issues?

### ISSUE THREAD

**Issue by bjornen77** [dotnet/wcf#5354]
If you create a channel factory in your ASP.NET core application and keeps the same channel factory for the life time of the application(singleton)

```
BasicHttpBinding myBinding = new BasicHttpBinding();
    
EndpointAddress myEndpoint = new EndpointAddress("http://localhost/MathService/Ep1");

ChannelFactory<IMath> myChannelFactory = new ChannelFactory<IMath>(myBinding, myEndpoint);
```

Will the generated channels from the channel factory have any potential DNS issues(or are the underlying http clients refreshed automatically)? For example if you create a new channel for each request in ASP.NET Core:

```
IMath wcfClient1 = myChannelFactory.CreateChannel();
double s = wcfClient1.Add(3, 39);
Console.WriteLine(s.ToString());
((IClientChannel)wcfClient1).Close();
```
Or do I also need the HttpClientFactory solution stated in (#3230)

**Comment by petersladek** [comment]
My understanding is yes there can be DNS issues, as this is not CoreWCF issue, see https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#recommended-use. CoreWCF does not expose a way to set PooledConnectionLifetime of the underlying SocketsHttpHandler. I ended up recreating SocketsHttpHandler with all values copied from original handler, and just providing a way to customize the http connection options.

`internal class CustomizeHttpHandlerEndpointBehavior : IEndpointBehavior
{
    private readonly HttpConnectionProperties _httpConnectionProperties;

    public CustomizeHttpHandlerEndpointBehavior(HttpConnectionProperties httpConnectionProperties)
    {
        _httpConnectionProperties = httpConnectionProperties;
    }

    public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
    {
        bindingParameters.Add(new Func<HttpClientHandler, HttpMessageHandler>(handler =>
        {
            var newHandler = new SocketsHttpHandler();
            // copy all properties set by WCF on it's handler (so we keep all configuration from wcf), see source
            // https://github.com/dotnet/wcf/blob/main/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L288
            newHandler.AutomaticDecompression = handler.AutomaticDecompression;
            newHandler.Proxy = handler.Proxy;
            newHandler.UseProxy = handler.UseProxy;
            newHandler.UseCookies = handler.UseCookies;
            newHandler.CookieContainer = handler.CookieContainer;
            newHandler.PreAuthenticate = handler.PreAuthenticate;
            newHandler.Credentials = handler.Credentials;
            newHandler.SslOptions.EnabledSslProtocols = handler.SslProtocols;
            newHandler.SslOptions.ClientCertificates = handler.ClientCertificates;

            // override default http connection properties if custom value was provided
            if (_httpConnectionProperties.PooledConnectionLifetime.HasValue)
                newHandler.PooledConnectionLifetime = _httpConnectionProperties.PooledConnectionLifetime.Value;
            if (_httpConnectionProperties.PooledConnectionIdleTimeout.HasValue)
                newHandler.PooledConnectionIdleTimeout = _httpConnectionProperties.PooledConnectionIdleTimeout.Value;
            if (_httpConnectionProperties.MaxConnectionsPerServer.HasValue)
                newHandler.MaxConnectionsPerServer = _httpConnectionProperties.MaxConnectionsPerServer.Value;

            return newHandler;
        }));
    }

    public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime) { }

    public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher) { }

    public void Validate(ServiceEndpoint endpoint) { }
}`

HttpConnectionProperties is just custom settings class.

**Comment by bjornen77** [comment]
Thank you @petersladek for your nice solution to this potential issue.
