### ISSUE TITLE
System.Web.Services.Protocols.SoapHttpClientProtocol is not found

### ISSUE THREAD

**Issue by 01hanybakir10** [dotnet/wcf#5387]
**Describe the bug**
Genesys WFM has provided a 4.8 reference file (WfmAPI700, WfmAPI850) for accessing the WFM API. Both files are generating many errors as shown in the screen shot.

[GenesysWfmAp.zip](https://github.com/dotnet/wcf/files/13692666/GenesysWfmAp.zip)

**To Reproduce**
Just attach the .cs files to a project.

**Screenshots**
![image](https://github.com/dotnet/wcf/assets/22276497/516058c7-92a7-43c8-be5c-769939555329)

![image](https://github.com/dotnet/wcf/assets/22276497/837e465c-0af2-4c0b-989e-b60624aa743b)

**Comment by HongGit** [comment]
@01hanybakir10 what you are asking for is .NET 2.0 SOAP client, which is not supported on .NET.  We suggest you regenerate the client using WCF.
