### ISSUE TITLE
 Nuget: System.ServiceModel.Federation 6.2.0 depends on vulnerable version System.Text.RegularExpressions 4.3.0

### ISSUE THREAD

**Issue by Bykiev** [dotnet/wcf#5399]
Hi, Nuget shows that `System.ServiceModel.Federation 6.2.0` depends on vulnerable version `System.Text.RegularExpressions 4.3.0`. I've checked the code and don't see the direct dependency. What can be done to avoid using of vulnerable version `System.Text.RegularExpressions 4.3.0`, except using it as direct dependency, not transitive (which is not good for us)?

**Comment by HongGit** [comment]
@Bykiev it seems that `System.ServiceModel.Federation 6.2.0` is not directly depending on `System.Text.RegularExpressions 4.3.0`.  
.NET guidelines are not to add a new direct dependency to force pulling in a higher version to resolve these dependency issues, this is something that should be done at the app level.
