### ISSUE TITLE
Enable F5 debugging of scenario tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#54]
Currently the self-hosted WCF service needed to run the scenario (OuterLoop) tests is started and torn down in the main build script.  Attempting to F5 debug one of the scenario test projects in VS fails because the service is not running.

This current issue needs to solve these scenarios
* Allow the current behavior to continue to work so the CI machine can continue to run OuterLoop tests
* Allow a developer to hit F5 on a scenario test project and have them succeed
* Allow a developer to msbuild any scenario test project and have the tests succeed

**Comment by roncain** [comment]
One additional note: it is understood the F5 experience will still require the developer to ask for OuterLoop tests to be run.  I believe it may be necessary to set an environment variable WithCategories to the value OuterLoop before starting VS.  This requirement should go away when the build tools we import are updated to support that.

**Comment by zhenlan** [comment]
Close this for now as we don't have a good solution at this point. The overall debugging story needs improvement.
