### ISSUE TITLE
System.ServiceModel.Duplex and Microsoft.Windows.Compatibility

### ISSUE THREAD

**Issue by Rand-Random** [dotnet/wcf#5421]
I have the following csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.2" />
        <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
        <PackageReference Include="System.ServiceModel.NetTcp" Version="8.0.0" />
        <PackageReference Include="System.ServiceModel.Primitives" Version="8.0.0" />
    </ItemGroup>
</Project>
```

Which has this basic class

```
[CallbackBehavior()]
public class Class1
{
}
```

With that setup I am getting the compile error

> The type 'CallbackBehaviorAttribute' exists in both 'System.ServiceModel.Duplex, Version=4.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.ServiceModel.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

To fix this error, is adding the deprecated package `System.ServiceModel.Duplex, Version=6.0.0.0` the correct procedure?
Asking because of the deprecated flag, seems wrong and I want to make sure, if what I am doing is correct.

**Comment by HongGit** [comment]
@Rand-Random this is the correct thing todo.

**Comment by Rand-Random** [comment]
Thanks, for the fast response.
