### ISSUE TITLE
UWP sceanrios with WCF RC1 packages are broken due to SM references newer version of runtime-backed packages

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#543]
SM is referencing newer versions of runtime-backed packages. We intentionally pinned all the runtime-backed packages because the runtime ships in the toolchain.

For SM to remain serviceable without updating the runtime we need to lower its dependencies down to the stable versions that shipped at UWP RTM for any of these packages.

**Comment by hongdai** [comment]
Matt will fix the bug so that we can do runs against both stable and the latest bits in the lab. The checkin version will be the stable one as possible.

**Comment by mconnew** [comment]
I did this a while ago.
