### ISSUE TITLE
Http only supports client certificates on windows coreclr

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#544]
We have a dependency on dotnet/corefx#4479 and dotnet/corefx#4476. Support on windows coreclr has been implemented using WinHttpHandler.

**Comment by mconnew** [comment]
We now have support for UWP.

**Comment by StephenBonikowsky** [comment]
The following test fails on NetNative due to this.
HttpsTests.ServerCertificateValidation_EchoString

**Comment by StephenBonikowsky** [comment]
More specifically, the issue @mconnew linked above dotnet/corefx#4476 seems to be the task related to the client side work for server SSL validation.

**Comment by StephenBonikowsky** [comment]
Splitting this issue into two separate issues...
#959 and #960
Closing it as part of the PR that updates the ActiveIssues on the affected test cases.
