### ISSUE TITLE
Investigate the huge difference in time to run first 10K WCF client requests

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#559]
While the maximum throughput in K is comparable with the desktop WCF we are significantly slower to run the first several WCF requests in multi-threaded tests. One thing that was immediately obvious is that the K threadpool was much slower to inject threads. There are possibly other reasons (slow to establish connection, etc).

**Comment by zhenlan** [comment]
According to @mconnew this is because there is no IO threadpool in CoreCLR (or we don't use it).

**Comment by KKhurin** [comment]
There are several factors:
* thread pool starvation caused by slow thread pool injection pace and lack of control over MinThreads - there is a workaround and CLI will have a config setting
* relying on worker threads only (with no IO threadpool)
* synchronous Close (vs. async close in desktop) - we already have a fix
* loading lots of smaller coreclr assemblies takes longer than a few large desktop assemblies
* the throughput is slower overall

We'll open separate bugs to get into more details over these issues.

**Comment by KKhurin** [comment]
We identified and fixed are numerous bugs in async close path (#1159 is the latest of them).
There are also numerous perf improvements in throughput (as well as in scalability and thread usage) coming up. Both help with the thread pool starvation and the startup time.

The thread pool injection pace is beyond the scope of this bug. Before we continue more thorough investigation we need to establish a more stable metrics for startup time (which is also beyond the scope of this bug).
