### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [dotnet/wcf#5594]
Hi team,

 Is there a plan to include the PrivacyInfo.xcprivacy manifest as required by Apple? ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Hao

**Comment by mconnew** [comment]
The [documentation found here](https://learn.microsoft.com/en-us/dotnet/maui/ios/privacy-manifest?view=net-maui-8.0) should be sufficient for you. WCF only calls .NET runtime apis, we don't call any apple api's directly so wouldn't have api usage to add to a privacy manifest file beyond what is documented in the maui documentation.
