### ISSUE TITLE
Move wiki content to documentation folder like CoreFx

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#56]
CoreFx and CoreClr are moving their wiki content into the repo itself, under a documentation folder.  The WCF repo should also do this.  It is possible our README.md and Contributing.md's might now point to non-existant locations in CoreFx, so they will need to be fixed at the same time.

For references see CoreFx PR https://github.com/dotnet/corefx/pull/1879

**Comment by zhenlan** [comment]
Assign to @SajayAntony as he is already working on this.

**Comment by SajayAntony** [comment]
Updated wiki to be inline with [corefx wiki](https://github.com/dotnet/corefx/wiki)
