### ISSUE TITLE
Improve legend for what's supported table and update all cells to reflect RC1

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#567]
2 parts to this task:
1. Improve the granularity of the emoji's to distinguish better between "what works completely" to "what works for the paths we've tested"
2. Go through and choose the right emoji's for each table cell

**Comment by zhenlan** [comment]
I think the granularity of current emoji's in the supported feature table are just right. Going into too much details will make it too hard to maintain. However, I do agree there is room for improvement of the definition of each emoji. Here is my proposal of update:

:white_check_mark: -- Works with no known issues
:warning: -- Partially works with known issues or only partially tested
:x: -- Does not work
:question: -- Not yet tested

cc: @hongdai as the change of definition of the emoji's may affect her current PR.

**Comment by hongdai** [comment]
I like the idea green means no major issues. Any different opinion?

:white_check_mark: -- Works with no known major issues

**Comment by roncain** [comment]
It depends -- how do we define what a "major issue" is?  I guess I would be okay with this if we still included a "more..." to describe what issues there are for this feature.  Major to us may be different than major to a customer.

**Comment by zhenlan** [comment]
"Works with no known major issues" really means "Works with no known issues" to us. If we know any issues worth mentioning, we should use :warning: instead. But it is always possible there are corner cases we did not test and we have a bug, so that the word "major" is added is more about setting proper expectations with customers.

**Comment by hongdai** [comment]
Given we have been prioritizing major scenarios(p0 and p1) in our outerloop tests and unit test coverage is not high, it's very possible corner cases are missed.
