### ISSUE TITLE
NtlmAuthentication_RoundTrips_Echo and WindowsAuthentication_RoundTrips_Echo failed in RC1 UWP E2E App

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#568]
We need to repro them on the latest bits.

exception from >	System.Net.Http.dll!System.Net.Http.HttpHandlerToFilter.SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancel) Line 60

Callstack:
System.NotSupportedException occurred
  HResult=-2147467263
  Message=This IRandomAccessStream does not support the GetInputStreamAt method because it requires cloning and this stream does not support cloning.
  Source=System.Runtime.WindowsRuntime
  StackTrace:
       at System.IO.NetFxToWinRtStreamAdapter.ThrowCloningNotSuported(String methodName)
       at System.IO.NetFxToWinRtStreamAdapter.GetInputStreamAt(UInt64 position)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException:

**Comment by roncain** [comment]
This is probably the same cause as #327

**Comment by mconnew** [comment]
This should be fixed when using the latest build of the NetNative HttpClient. Assigning back to @hongdai to verify.

**Comment by hongdai** [comment]
I've verified both tests passed in the latest bit.
