### ISSUE TITLE
Use [ActiveIssue] instead of [Fact(Skip="reason"))] in all tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#57]
All tests that are currently marked with [Fact(Skip="some reason")] need to be marked with [ActiveIssue] and the Skip reason removed.  See CoreFx repo for examples.  Also verify the ActiveIssue attribute exists in our repo and clone from build-tools if not.

**Comment by StephenBonikowsky** [comment]
Looks like we are missing "xunit.netcore.extensions\Attributes" from our repo. I'll figure out how to get it to our repo tomorrow.
