### ISSUE TITLE
Create WCF test service capable of testing Kerberos

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#59]
We need to be able to launch and run tests against a WCF test service that allows us to test Kerberos.  This issue needs to consider how to configure a machine for this service, launch this service, and identify the tests that require this service (probably custom xunit traits like OuterLoop).

Let's use this issue to discuss the approach and open other issues as appropriate.

**Comment by hongdai** [comment]
We have implemented a manual way to test Kerberos. We need to automate it in TOF lab so they get exercised automatically.

**Comment by roncain** [comment]
Agreed.  The first step would be for you to integrate with the Bridge work being done by @dmetzgar to create a resource that will launch the necessary WCF service on demand, and then to add the necessary scenario tests to invoke it.  Then we need to implement #53 to be able to attribute these tests to run optionally.  Feel free to make multiple new issues for the different sub-tasks.

Until we can do all these steps we need to document how to do it manually so that the developer community can follow the steps.  The best place is probably a .md file under the Documentation folder.

**Comment by hongdai** [comment]
Create a separate issue(issue #193 ) to track the first step.

**Comment by hongdai** [comment]
The second step is to document how to run the test manually until issue# 53 resolved. The second step is tracked by issue #195

**Comment by hongdai** [comment]
All work are done. Closing this issue. Once issue #53 is resolved, we can open a new issue to track run this test in a category.
