### ISSUE TITLE
Managed memory leak in http streaming scenarios

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#594]
The leak is per request so it is very fast. A cursory look shows that we don't dispose System.Net.Http.HttpResponseMessage instances. This could be a bug in System.Net.Http though (disposing should not be required to be memleak-free). Need more investigation - assigning to myself.

**Comment by zhenlan** [comment]
This is high-pri as it is blocking perf and stress.

**Comment by KKhurin** [comment]
This is a tracking bug for https://github.com/dotnet/corefx/issues/5927

**Comment by KKhurin** [comment]
Fixed
