### ISSUE TITLE
Turning on client cert for HTTPS in CoreCLR and UWP

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#597]
This will need add new api to CoreCLR.
UWP may not be able to do this because it will require changes in HttpClientHanderler owned by Networking.

**Comment by iamjasonp** [comment]
I might be missing something ... if we "add API to CoreCLR" here, then don't we have to add it to the contract which covers both UWP and CoreCLR and desktop? 

Or will we "add API to CoreCLR" and then PNSE this for UWP in the interim?

**Comment by mconnew** [comment]
The api's needing to be added is BasicHttpsBinding as BasicHttpBinding won't allow ClientCertificate to be specified as client certificate type, and/or HttpsTransportBindingElement.RequireClientCertificate property. Without either of these, there's no way to tell WCF to use a client certificate. The issue with UWP is that there's no way to specify the client certificate to HttpClient. In CoreClr, on windows only, we can use WinHttpHandler which has properties exposed to set the client certificate. This isn't available in UWP.
