### ISSUE TITLE
Exposing selected operation contracts as ReST causing error Operation 'method name' of contract 'IContract' specifies multiple request body

### ISSUE THREAD

**Issue by anuraj** [dotnet/wcf#601]
Here is the scenario. There is an existing service contract with some methods which are getting consumed by a desktop app. Now need to expose some operation contracts via ReST. But it demands to expose all the methods as ReST. Else there is exception with below text which often comes if the params are wrapped.

> Error message -

> Operation 'SaveEntitiy' of contract 'IService' specifies multiple request body parameters to be serialized without any wrapper elements. At most one body parameter can be serialized without wrapper elements. Either remove the extra body parameters or set the BodyStyle property on the WebGetAttribute/WebInvokeAttribute to Wrapped.

Here is the operation contract.
```
[ServiceContract]
public interface IService
{
        [OperationContract] //No need to expose this as ReST
        string SaveEntity(int id,string name);

        [OperationContract]
        [WebInvoke(Method = "GET", ResponseFormat = WebMessageFormat.Json)]
        string GetData(int value);
}
```

If we expose the SaveEntity as ReST everthing works. Means the configs are correct.

**Comment by mconnew** [comment]
We don't support WebHttpBinding in the open source WCF so I'm going to close this issue.  
Having said that, I can give you a couple of suggestions. You could add the WebInvoke attribute to your SaveEntity method specifying the Method = "POST" as this does allow multiple request parameters. You could also use specify UriTemplate in the WebInvoke attribute. For example `[WebInvoke(UriTemplate = "IgnoreThis/{id}/{name}"]`. This mechanisms though still make the method available to clients and if you expose the WSDL, they will be discoverable. Another option is to create a new ServiceContract interface that is used for your REST endpoint only. Only place the methods you want exposed in that contract, so you would only have the GetData method and not the SaveEntity. Your implementation class would implement the original interface and the REST interface. As long as the methods have the same definition (attributes don't matter for this), the one method on the service class would match for both interfaces. Your WebHttpBinding endpoint would be declared as servicing your new interface.
