### ISSUE TITLE
Support WebSockets on Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#625]
WebSockets does not yet work on Linux because the implementation of WebSockets.Client is currently only a stub.  Issue https://github.com/dotnet/corefx/issues/2486 tracks implementing it.  Once fixed, we need to remove [ActiveIssue] from any tests assigned to this current issue.

**Comment by roncain** [comment]
Note: this issue is referenced in several [ActiveIssue] attributes in tests.  Please don't close it without also modifying those [ActiveIssues].

**Comment by mconnew** [comment]
This is blocked by dotnet/corefx#9985. The tests appear to succeed, the issue is with closing the WebSocket.
