### ISSUE TITLE
System.IdentityModel.Claims code coverage analysis.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#639]
Parent Issue #314 

The triage process should categorize as best as possible everything into one of three buckets...
    1.Unsupported product code that needs to be removed.
    2.Unsupported product code that we want to support relatively soon so keep it.
    3.Supported product code that needs test coverage.

Class level details of System.IdentityModel.Claims namespace...

| Namespace | Covered | Uncovered | Coverable | Total | Line Coverage |
| --- | --- | --- | --- | --- | --- |
| **System.IdentityModel.Claims** | 166 | 666 | 832 | 1957 | 19.90% |
| **System.IdentityModel.Claims.Claim** | 30 | 57 | 87 | 203 | 34.40% |
| **System.IdentityModel.Claims.ClaimComparer** | 17 | 146 | 163 | 297 | 10.40% |
| **System.IdentityModel.Claims.ClaimSet** | 28 | 34 | 62 | 119 | 45.10% |
| **System.IdentityModel.Claims.ClaimTypes** | 10 | 21 | 31 | 77 | 32.20% |
| **System.IdentityModel.Claims.DefaultClaimSet** | 10 | 48 | 58 | 106 | 17.20% |
| **System.IdentityModel.Claims.Rights** | 2 | 0 | 2 | 16 | 100% |
| **System.IdentityModel.Claims.WindowsClaimSet** | 0 | 147 | 147 | 253 | 0% |
| **System.IdentityModel.Claims.X509CertificateClaimSet** | 62 | 160 | 222 | 443 | 27.90% |
| **System.IdentityModel.Claims.X509Identity** | 7 | 53 | 60 | 443 | 11.60% |

**Comment by zhenlan** [comment]
Closing this as the data is outdated. We will continue adding test coverage tracked by new issues.
