### ISSUE TITLE
System.ServiceModel.Security code coverage analysis.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#643]
Parent Issue #314 

The triage process should categorize as best as possible everything into one of three buckets...
 1.Unsupported product code that needs to be removed.
 2.Unsupported product code that we want to support relatively soon so keep it.
 3.Supported product code that needs test coverage.

Class level details of System.ServiceModel.Security namespace...

| Namespace | Covered | Uncovered | Coverable | Total | Line Coverage |
| --- | --- | --- | --- | --- | --- |
| **System.ServiceModel.Security** | 532 | 5259 | 5791 | 28503 | 9.10% |
| **System.ServiceModel.Security.Basic128Rsa15SecurityAlgorithmSuite** | 0 | 5 | 5 | 642 | 0% |
| **System.ServiceModel.Security.Basic128SecurityAlgorithmSuite** | 0 | 23 | 23 | 642 | 0% |
| **System.ServiceModel.Security.Basic128Sha256Rsa15SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.Basic128Sha256SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.Basic192Rsa15SecurityAlgorithmSuite** | 0 | 5 | 5 | 642 | 0% |
| **System.ServiceModel.Security.Basic192SecurityAlgorithmSuite** | 0 | 23 | 23 | 642 | 0% |
| **System.ServiceModel.Security.Basic192Sha256Rsa15SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.Basic192Sha256SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.Basic256Rsa15SecurityAlgorithmSuite** | 0 | 5 | 5 | 642 | 0% |
| **System.ServiceModel.Security.Basic256SecurityAlgorithmSuite** | 0 | 23 | 23 | 642 | 0% |
| **System.ServiceModel.Security.Basic256Sha256Rsa15SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.Basic256Sha256SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.BasicSecurityProfileVersion** | 0 | 7 | 7 | 27 | 0% |
| **System.ServiceModel.Security.BinaryNegotiation** | 0 | 53 | 53 | 87 | 0% |
| **System.ServiceModel.Security.ChannelProtectionRequirements** | 0 | 260 | 260 | 373 | 0% |
| **System.ServiceModel.Security.CommunicationObjectSecurityTokenAuthenticator** | 0 | 83 | 83 | 500 | 0% |
| **System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider** | 0 | 90 | 90 | 500 | 0% |
| **System.ServiceModel.Security.EmptyReadOnlyCollection`1** | 1 | 0 | 1 | 1048 | 100% |
| **System.ServiceModel.Security.HttpDigestClientCredential** | 22 | 2 | 24 | 51 | 91.60% |
| **System.ServiceModel.Security.IdentityVerifier** | 102 | 60 | 162 | 283 | 62.90% |
| **System.ServiceModel.Security.InMemoryNonceCache** | 0 | 87 | 87 | 160 | 0% |
| **System.ServiceModel.Security.MessagePartSpecification** | 42 | 102 | 144 | 229 | 29.10% |
| **System.ServiceModel.Security.MessageProtectionOrderHelper** | 0 | 5 | 5 | 22 | 0% |
| **System.ServiceModel.Security.MessageSecurityException** | 4 | 18 | 22 | 53 | 18.10% |
| **System.ServiceModel.Security.MessageSecurityTokenVersion** | 0 | 118 | 118 | 202 | 0% |
| **System.ServiceModel.Security.NonceCache** | 0 | 24 | 24 | 63 | 0% |
| **System.ServiceModel.Security.OperationWithTimeoutAsyncResult** | 0 | 28 | 28 | 1048 | 0% |
| **System.ServiceModel.Security.ProtectionLevelHelper** | 8 | 25 | 33 | 1048 | 24.20% |
| **System.ServiceModel.Security.ReceiveSecurityHeader** | 0 | 7 | 7 | 37 | 0% |
| **System.ServiceModel.Security.RequestSecurityToken** | 0 | 319 | 319 | 559 | 0% |
| **System.ServiceModel.Security.RequestSecurityTokenResponse** | 0 | 310 | 310 | 567 | 0% |
| **System.ServiceModel.Security.RequestSecurityTokenResponseCollection** | 0 | 28 | 28 | 58 | 0% |
| **System.ServiceModel.Security.ScopedMessagePartSpecification** | 0 | 136 | 136 | 205 | 0% |
| **System.ServiceModel.Security.SecureConversationDriver** | 0 | 11 | 11 | 73 | 0% |
| **System.ServiceModel.Security.SecureConversationVersion** | 0 | 28 | 28 | 86 | 0% |
| **System.ServiceModel.Security.SecurityAccessDeniedException** | 0 | 6 | 6 | 18 | 0% |
| **System.ServiceModel.Security.SecurityAlgorithmSuite** | 0 | 188 | 188 | 642 | 0% |
| **System.ServiceModel.Security.SecurityAuditHelper** | 0 | 3 | 3 | 16 | 0% |
| **System.ServiceModel.Security.SecurityChannel`1** | 0 | 60 | 60 | 115 | 0% |
| **System.ServiceModel.Security.SecurityContextKeyIdentifierClause** | 0 | 27 | 27 | 66 | 0% |
| **System.ServiceModel.Security.SecurityCredentialsManager** | 1 | 0 | 1 | 14 | 100% |
| **System.ServiceModel.Security.SecurityHeader** | 0 | 70 | 70 | 163 | 0% |
| **System.ServiceModel.Security.SecurityKeyEntropyModeHelper** | 0 | 11 | 11 | 33 | 0% |
| **System.ServiceModel.Security.SecurityMessageProperty** | 21 | 172 | 193 | 318 | 10.80% |
| **System.ServiceModel.Security.SecurityNegotiationException** | 3 | 6 | 9 | 23 | 33.30% |
| **System.ServiceModel.Security.SecurityPolicyVersion** | 0 | 27 | 27 | 79 | 0% |
| **System.ServiceModel.Security.SecurityProtocol** | 0 | 23 | 23 | 68 | 0% |
| **System.ServiceModel.Security.SecurityProtocolFactory** | 3 | 686 | 689 | 1141 | 0.40% |
| **System.ServiceModel.Security.SecurityStandardsManager** | 0 | 17 | 17 | 68 | 0% |
| **System.ServiceModel.Security.SecurityStateEncoder** | 0 | 1 | 1 | 18 | 0% |
| **System.ServiceModel.Security.SecurityTimestamp** | 0 | 100 | 100 | 193 | 0% |
| **System.ServiceModel.Security.SecurityTokenAttachmentModeHelper** | 0 | 33 | 33 | 67 | 0% |
| **System.ServiceModel.Security.SecurityTokenSpecification** | 6 | 4 | 10 | 35 | 60% |
| **System.ServiceModel.Security.SecurityUniqueId** | 0 | 18 | 18 | 1048 | 0% |
| **System.ServiceModel.Security.SecurityUtils** | 105 | 394 | 499 | 1048 | 21% |
| **System.ServiceModel.Security.SecurityVersion** | 17 | 98 | 115 | 286 | 14.70% |
| **System.ServiceModel.Security.SendSecurityHeader** | 0 | 9 | 9 | 46 | 0% |
| **System.ServiceModel.Security.SignatureConfirmationElement** | 0 | 20 | 20 | 52 | 0% |
| **System.ServiceModel.Security.SignatureTargetIdManager** | 0 | 3 | 3 | 22 | 0% |
| **System.ServiceModel.Security.SslProtocolsHelper** | 11 | 3 | 14 | 1048 | 78.50% |
| **System.ServiceModel.Security.SspiSecurityTokenProvider** | 7 | 4 | 11 | 38 | 63.60% |
| **System.ServiceModel.Security.SupportingTokenAuthenticatorSpecification** | 0 | 24 | 24 | 68 | 0% |
| **System.ServiceModel.Security.SupportingTokenProviderSpecification** | 0 | 16 | 16 | 47 | 0% |
| **System.ServiceModel.Security.SupportingTokenSpecification** | 0 | 10 | 10 | 39 | 0% |
| **System.ServiceModel.Security.TimeBoundedCache** | 0 | 334 | 334 | 513 | 0% |
| **System.ServiceModel.Security.TokenImpersonationLevelHelper** | 5 | 74 | 79 | 1048 | 6.30% |
| **System.ServiceModel.Security.TripleDesRsa15SecurityAlgorithmSuite** | 0 | 5 | 5 | 642 | 0% |
| **System.ServiceModel.Security.TripleDesSecurityAlgorithmSuite** | 0 | 23 | 23 | 642 | 0% |
| **System.ServiceModel.Security.TripleDesSha256Rsa15SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.TripleDesSha256SecurityAlgorithmSuite** | 0 | 7 | 7 | 642 | 0% |
| **System.ServiceModel.Security.TrustDriver** | 0 | 14 | 14 | 141 | 0% |
| **System.ServiceModel.Security.TrustVersion** | 0 | 28 | 28 | 86 | 0% |
| **System.ServiceModel.Security.UserNamePasswordClientCredential** | 29 | 2 | 31 | 63 | 93.50% |
| **System.ServiceModel.Security.WSSecurityOneDotOneReceiveSecurityHeader** | 0 | 3 | 3 | 24 | 0% |
| **System.ServiceModel.Security.WSSecurityOneDotOneSendSecurityHeader** | 0 | 3 | 3 | 31 | 0% |
| **System.ServiceModel.Security.WSSecurityOneDotZeroReceiveSecurityHeader** | 0 | 3 | 3 | 20 | 0% |
| **System.ServiceModel.Security.WSSecurityOneDotZeroSendSecurityHeader** | 0 | 3 | 3 | 19 | 0% |
| **System.ServiceModel.Security.WSSecurityPolicy** | 0 | 3 | 3 | 122 | 0% |
| **System.ServiceModel.Security.WSSecurityTokenSerializer** | 0 | 247 | 247 | 441 | 0% |
| **System.ServiceModel.Security.WSUtilitySpecificationVersion** | 0 | 66 | 66 | 164 | 0% |
| **System.ServiceModel.Security.WindowsClientCredential** | 16 | 32 | 48 | 92 | 33.30% |
| **System.ServiceModel.Security.WrapperSecurityCommunicationObject** | 0 | 76 | 76 | 500 | 0% |
| **System.ServiceModel.Security.X509CertificateInitiatorClientCredential** | 22 | 14 | 36 | 73 | 61.10% |
| **System.ServiceModel.Security.X509CertificateRecipientClientCredential** | 41 | 42 | 83 | 148 | 49.30% |
| **System.ServiceModel.Security.X509CertificateValidationModeHelper** | 10 | 3 | 13 | 59 | 76.90% |
| **System.ServiceModel.Security.X509ClientCertificateAuthentication** | 0 | 10 | 10 | 32 | 0% |
| **System.ServiceModel.Security.X509ServiceCertificateAuthentication** | 56 | 39 | 95 | 160 | 58.90% |
| **System.ServiceModel.Security.XmlHelper** | 0 | 261 | 261 | 397 | 0% |

**Comment by zhenlan** [comment]
Closing this as the data is outdated. We will continue adding test coverage tracked by new issues.
