### ISSUE TITLE
Update FaultException{Object} in rd.xml to rely on new toolchain open generic instantiation

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#664]
The toolchain has been updated to support instantiation of generics using primitive types, meaning FaultException<int> should now work.  To enable this feature, we need to modify the rd.xml under the resources folder to change FaultException{Object} to FaultException`1.

**Comment by Joebeazelman** [comment]
I am getting the following build error on a Windows UWP project see issue #2438
