### ISSUE TITLE
Move WCF project out of TFS using CoreFx guidelines

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#671]
Follow the guidelines at https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md to create a .builds file and allow WCF to build for any framework from a single project file.

**Comment by StephenBonikowsky** [comment]
I just started working on this based on #637 
Is this Issue a dupe?

**Comment by StephenBonikowsky** [comment]
Actually there seems to be two main pieces to this...
1. Implement guidelines in the project-guidelines.md file
2. Port WCF libraries from TFS to GitHub.

We can use this issue for the porting of the libraries if you want, I'll use #637 for the initial guideline changes and will open additional issues for the more difficult/complicated aspects of the guidelines.

**Comment by StephenBonikowsky** [comment]
This work was completed by #694
