### ISSUE TITLE
[Build] Package not laid out as expected

### ISSUE THREAD

**Issue by esdrubal** [dotnet/wcf#691]
`run-test.sh` is exiting with message `Package not laid out as expected`

Something looks off in https://github.com/dotnet/wcf/blob/master/run-test.sh#L105.
Where is `$packageDir` coming from?

**Comment by esdrubal** [comment]
@roncain $packageDir was set in the commit that introduced it https://github.com/dotnet/wcf/commit/c962b41641683362be683c32eb66eae2ecb822bb#diff-b85dc439de2f53c86324409385ec0b5aR89

But is no longer defined since https://github.com/dotnet/wcf/commit/5d8b2ec031e8e0f8a4afe1e7a79d0b7a8da824ce#diff-b85dc439de2f53c86324409385ec0b5aL86

**Comment by roncain** [comment]
@esdrubal -- good question and I will investigate.  We have been running this script manually and on our CI machines for some weeks, so I need to understand how that was working for us. The edits were done to keep WCF's run-test.sh in sync with the version in CoreFx.

We are also now moving to deprecate run-test.sh and use only build.sh.  However there are some dnu restore timeout issues that require it to be run several times before it succeeds.  We are also moving to use the new 'dotnet' for the package restore and hope it resolves the timeout issues.

Sorry for the inconvenience -- we are in a high rate of churn right now as CoreFx and WCF are moving to build.sh and being able to rely on published packages, as well as moving from dnu to 'dotnet' in preparation for the next RC release.

We'll reply on this issue asap as we get this stable.

/cc @mconnew @iamjasonp
