### ISSUE TITLE
XmlDictionaryReader pooling - implementation in System.Private.ServiceModel (Text, Binary)

### ISSUE THREAD

**Issue by shmao** [dotnet/wcf#696]
Implement streamedReaderPool and TakeStreamedReader method.

**Comment by zhenlan** [comment]
@shmao to work with @KKhurin to see how much impact this is going to have on performance

**Comment by roncain** [comment]
@shmao -- I believe this constitutes a new feature, correct?  This will require additional information in shiproom triage to understand what scenarios are currently blocked and need this fix.  Can you provide more details, or should we consider it for post-RTM?

**Comment by shmao** [comment]
The XmlDictionaryReader type in .Net Core is not resuable, i.e. we cannot reset the input of a reader. Therefore we cannot implement this XmlReader pool in .Net Core.

Besides, I verified that the current TakeStreamedReader takes less than 0.1% of the total time of a WCF call. We wouldn't get much perf improvement even if we impelmented such a pool. 

I'm closing this issue for now.
