### ISSUE TITLE
Support automated root certificate installation in *nix, OS X

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#700]
Currently in Linux, we have to do the following manually to test with certificates:

https://github.com/dotnet/wcf/blob/master/Documentation/manualtest-guide.md

This is needed because OpenSSL and therefore cURL uses a "bundle" of SSL root CA certificates to determine whether or not the cert presented is trusted. We need to add the WCF Bridge root cert to the bundle for our tests to pass. 

This needs to be automated, the current experience is not pleasant

The following is the known set of tasks: 

* [x] Automate for Debian/Ubuntu <br/>
  `sudo update-ca-certificates`
* [x] Automate for OS X <br/>
  `sudo /usr/bin/security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain [cert]`<br/>
* [x] Automate for RHEL 
* [x] Automate for CentOS  <br/>
  `sudo update-ca-trust`
* [x] ~~Tie in everything to one script and integrate to build.sh~~
* [x] Wire this into infrastructure in [ConditionalFact]

**Comment by iamjasonp** [comment]
For the moment, use the manual test guide: https://github.com/dotnet/wcf/blob/master/Documentation/manualtest-guide.md, which documents the needed steps

**Comment by iamjasonp** [comment]
Note: these scripts may change once the new testing (server) infrastructure comes online.

**Comment by roncain** [comment]
This work item is necessary to fix issue #1123.

**Comment by iamjasonp** [comment]
Mostly done with #1313. We still need to tie this script into setup

**Comment by iamjasonp** [comment]
Note that we no longer want to integrate this step into build.sh - we're looking at tying this in at runtime instead

**Comment by iamjasonp** [comment]
All done! 

There will probably be some teething pains as some of these platforms are new to us (and we don't test on them often). Closing this bug though as the main body of work for this is done.
