### ISSUE TITLE
Transaction.Current becomes null after awaiting call in service

### ISSUE THREAD

**Issue by ajtowf** [dotnet/wcf#708]
When flowing a transaction from a client to a service Transaction.Current becomes null after awaiting a service to service call, unless you wrap the call in a TransactionScope with the TransactionScopeAsyncFlowOption.Enabled option.

See http://stackoverflow.com/questions/34767978
or https://youtu.be/B-Q3T5KpiYk if you prefer to see instead of read.

**Comment by hongdai** [comment]
This is because Transaction is not currently supported in .Net foundation.

**Comment by ajtowf** [comment]
I mistook this repo for the full-fledged WCF in .NET, sorry, didn't realize it only was the .NET Core version of the Windows Communication Foundation client libraries.

Could you please tag somebody from the WCF team, that perhaps could answer http://stackoverflow.com/questions/34767978/ ?

**Comment by zhenlan** [comment]
I am closing this issue as it is about full .NET Framework.

For future reference, issues with full .NET Framework can be reported through [Microsoft Connect](http://connect.microsoft.com/).
