### ISSUE TITLE
Not possible to create a TransactionScope in a Message Inspector

### ISSUE THREAD

**Issue by ajtowf** [dotnet/wcf#709]
Should it be possible? I don't know, but it would be nice so we don't have to create a transactionscope with TransactionScopeAsyncFlowOption.Enabled set in each service method.

See https://github.com/dotnet/wcf/issues/708
or stackoverflow http://stackoverflow.com/questions/34767978

**Comment by hongdai** [comment]
This is because Transaction is not currently supported in .Net foundation.

**Comment by ajtowf** [comment]
Closing as dup of https://github.com/dotnet/wcf/issues/708
