### ISSUE TITLE
Evaluate NuGet packages generated by build

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#721]
Now that our build generates .nupkg, we need to verify their content and dependencies are correct, including all platforms and target frameworks.  This could be manual or involve app building using a custom NuGet feed folder containing these packages

**Comment by zhenlan** [comment]
Two tasks
* [ ]  Manually unzip the package and verify the payload is as expected
* [ ]  Build a test app to consume the packages

**Comment by StephenBonikowsky** [comment]
I diffed version 4.0.1-rc2-23712 built from my local FxKit against the exact same version from MyGet and they were identical in every way.

**Comment by zhenlan** [comment]
Thanks @StephenBonikowsky. With this so we know the build lab is using the same artifacts from our OSS repo to build our packages, we don't know if they are correct though. Can we compare the new package with some older package (eg. [RC1 package](http://www.nuget.org/packages/System.Private.ServiceModel/4.1.0-beta-23516)) and verify if all the diffs are expected?

**Comment by zhenlan** [comment]
Close this one as package building keeps changing. We will create a RC2 issue to track sign oof of end 2 end experience.
