### ISSUE TITLE
Wcf repo fails to build due to CLI changes

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#724]
Changes made to the CLI cause build errors in the WCF repo.  It appears this happened in CoreFx too but was fixed by PR https://github.com/dotnet/corefx/pull/5539.

I have made PR #723 to bring these same changes into WCF.

Experiments show the 1.0.0-rc2 release branch now fails to build too, so these changes will need to be ported.  Applying 'release-blocking' because this PR will need to be ported back to the release branch.

**Comment by StephenBonikowsky** [comment]
PR #723 is merged and verified to fix the build break.

**Comment by roncain** [comment]
Resolved in the master branch.  Keeping this issue open until conversation with ShipRoom decides whether we will make further modifications and/or backport to 1.0.0-rc2

**Comment by roncain** [comment]
Closing because integrated to RC2, and future of RC2 is not clear
