### ISSUE TITLE
Not Able to find the feature Add Service Reference

### ISSUE THREAD

**Issue by leena-v** [dotnet/wcf#728]
Hi,

I created a new solution on the new Visual Studio 2015 and created a dll Library(Package).
When I try to add a reference to a webservice(wsdl), I am unable to add the service reference the right click on the references only has the following options:
1) Add Reference
2) Add Connected Service
3) ManageNuget Package
4) Restore Packages
Has anyone faced the same issue?
Is there anyway to configure the application to display this feature(add service reference)?
Could you please suggest which is the best way to add a third party WSDL api reference to a .net core dll? is this feature available?

Thanks,

**Comment by roncain** [comment]
This thread originated at https://github.com/dotnet/core/issues/49.  I copied the reply here so we can continue the discussion in this repo.

Hi @leena-v . A blog describing this up-coming feature is at http://blogs.msdn.com/b/webdev/archive/2015/12/15/wcf-connected-service-visual-studio-extension-preview-for-asp-net-5-projects.aspx . Give it a try and let us know how it works for you.

@leena-v replied:
@roncain Appreciate for your quick response. Could you please suggest which is the best way to add a third party wsdl api reference to a .net core dll? is this feature available?

/cc @zhenlan @mlacouture.

**Comment by leena-v** [comment]
The approach suggested using the WCF application as a Connect Reference is not an option. I am trying to build a console application that references a dll that internally calls the wsdl. Could you please suggest how to add a third party WSDL api reference to a .net core dll?

**Comment by zhenlan** [comment]
> I am trying to build a console application that references a dll that internally calls the wsdl.

@leena-v can you please help us to understand what kind of console application you are building? Is it a xproj, csproj or something else? Where is the dll you are referencing from? Did you build it or is it from a 3rd party? If you build it, is it a xproj, csproj or something else:?

**Comment by leena-v** [comment]
Hi Zhenlan,
The console application and the dll are xproj. Basically I am trying to rebuild an existing Visual Studio 2012 application to Visual Studio 2015. The dll references a wsdl. This is referenced using the feature of service reference. I am not able to add the wsdl reference in the new xproj that I created. How can a wsdl reference be added to the project?

**Comment by zhenlan** [comment]
Thanks @leena-v for the clarification.

> I am not able to add the wsdl reference in the new xproj that I created.

Just to make sure I understand... so you have a wsdl reference (eg. http://...?wsdl). When you put this url into the WCF connected service, didn't it generate the client proxy you expected? If so, what errors do you get? Or do I misunderstand what you mean by wsdl reference?

**Comment by leena-v** [comment]
No. I am not sure how to include this as a WCF connected service. When I tried to use the option to the WCF connected service it lists a default set of APIs that can be used for this feature. But no option to add a URL. Could you please advise how can I set this WSDL to be available under the WCF connected service.

**Comment by zhenlan** [comment]
> But no option to add a URL.

A URL can be added in the _Address_ box as shown in this [picture](http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-63-56/2744.WCF.Service.Reference.Dialog.1.PNG). For details of how to get to this dialog, you can find in the [blog post](http://blogs.msdn.com/b/webdev/archive/2015/12/15/wcf-connected-service-visual-studio-extension-preview-for-asp-net-5-projects.aspx) Ron mentioned earlier.

I may still not fully understand your question. I am wondering if you can post a video showing the issue you have.

**Comment by vincentshow** [comment]
How to add net.tcp binding service? I’ve added net.tcp binding service using this tool of .net core rc2. But when I upgraded it to .net core 1.0, I couldn’t add net.tcp binding service with error msg “invalid url”. 

I’ve tried to add http binding service, and it showed progress bar of searching service while no progress bar shown when adding net.tcp binding service. It just gives me invalid url error, and the detail is 

The service Uri is not valid: ‘net.tcp://10.13.0.228:7000/SnailGame.GameManage.CenterService.Console.ExecuteService’.

I've provided this feedback in this [blog](https://blogs.msdn.microsoft.com/webdev/2016/06/26/wcf-connected-service-for-net-core-1-0-0-and-asp-net-core-1-0-0-is-now-available/#comment-128505), but it seems nobody answer me...thanks

**Comment by vincentshow** [comment]
sorry, the tool I mentioned is WCF connected service

**Comment by hongdai** [comment]
Thanks for reporting the issue!
Non-http based URI is not yet supported. We are evaluating adding the support.

**Comment by vincentshow** [comment]
so sad, how can you cut off features in high version? Anyway, could you please give me a url by which I can download the rc2 version? No rc2 version can be searched in https://visualstudiogallery.msdn.microsoft.com. This feature is so critical that I cannot move on without it in my project. Much much much thanks...

**Comment by vincentshow** [comment]
0.1.20119.0, this is the version no of wcf connected service which allow me to add net.tcp binding, please give me a download url, thanks

**Comment by hongdai** [comment]
RC2 is a pre-release version, thus not all features there would be officially released. Unfortunately for the same reason, we do not keep RC2 bits for consumption.

I will help raising the priority to support the feature.

**Comment by vincentshow** [comment]
ah...resolved. I added one more wsdualhttpbinding in my wcf service, and the tool generated valid reference for me with System.ServiceModel.NetTcpBinding. I thought what blocked me was the tool's url filter, and the feature is suported all the way.

**Comment by roncain** [comment]
@hongdai -- can we close this issue now?

**Comment by hongdai** [comment]
Yes. Net.tcp is supported now.
