### ISSUE TITLE
WCF it is based on conventions and not just configuration.

### ISSUE THREAD

**Issue by leolana** [dotnet/wcf#73]
Where these standard conventions will reduce the amount of code generated to configure the service, the bindings, proxy and etc. Where settings will be used in more specific cases to override the conventions adopted by the WCF.

**Comment by roncain** [comment]
Thanks for the suggestion @leolana. Would you mind providing some specific examples of the conventions you would like to see?

**Comment by zhenlan** [comment]
@leolana we are closing this issue for now but please feel free to reopen this when you have more details.
