### ISSUE TITLE
Improve assert messages for unexpected exceptions

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#74]
Many of the scenario tests detect unexpected exceptions but only report their type name, which does not give enough information, especially for CI failures.

We need to report unexpected exceptions in a consistent way.  This includes:
- The expected exception type
- The actual exception type
- (Newline and) exception.ToString() of the actual exception caught

If xunit asserts provide all this, they should be used.  Otherwise we need a test helper.
All unit tests and scenario tests should be updated to use this style.

**Comment by iamjasonp** [comment]
xunit should show exception messages properly. The offending code is this: 

    src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs

        catch (Exception e)
        {
            if (e.GetType() != typeof(EndpointNotFoundException))
            {
                Assert.True(false, string.Format("Expected exception: {0}, actual: {1}", "EndpointNotFoundException", e.GetType()));
            }

            if (!e.Message.Contains(expectExceptionMsg))
            {
                Assert.True(false, string.Format("Expected exception message: {0}, actual: {1}", expectExceptionMsg, e.Message));
            }
            return;
        }

I wonder in this case, we are actually reading into the expected exception message; perhaps we can make our own helper here to deal with the case where we expect an exception message.

**Comment by roncain** [comment]
As long as we get the stacktrace of the unexpected exception, and any inner exception, and can test the message, we'll have what we need. I'd use xunit instead of helpers where possible. The goal should be that we can diagnose intermittent test failure in the lab or submitted as an issue. I actually think testing only exception type is a mistake (think ArgumentNullException thrown from somewhere other than you expect.)

**Comment by iamjasonp** [comment]
I've sometimes found that if you're having to dig into the exception message in test, there's a way to test in a more precise way (e.g., split up a block of code into multiple `Assert` calls), or the product has been designed with exceptions that cover too broad a set of errors :smile: 

That being said, I agree that there are many times we may want to verify the message - the example you gave makes sense, as does the testcase cited earlier. I think though that we need to move away from catching the exception and let xunit do as much of its magic as possible. 

Digging slightly into xunit, one pattern we might be able to use is: 

    Assert.Throws<ArgumentNullException>("paramName", () => { /* action */ }); 
    
... if the Exception.paramName is set. 
To verify an exception message: 

    var exception = Assert.Throws<EndpointNotFoundException>( () => { /* action */ });
    Assert.True(exception.Message.Contains("exception message"), exception); 

I think this takes care of 1) ensuring that the exception type is correct, and then 2) checking that the exception text is right. 

Care needs to be taken should we ever find ourselves needing to key off the *message*, we should try to make sure we don't hard code the natural language messages in unit tests as they might change over time. Do we have access to the string resources used in product in test?

**Comment by StephenBonikowsky** [comment]
@roncain , after looking through our scenario tests I see that the standard we have been using to log errors is by creating a StringBuilder variable that we log errors to. In the typical test we have the 'catch (Exception ex)' section for any unexpected exceptions which is what I think this Issue is primarily about?

It looks like we append our own custom message together with the test name and the Exception .ToString(). And then we call the Xunit.Assert to see if the StringBuilder is empty or not.

What I noticed is that many of the tests do not include the extra code to include the Exception.InnerException.ToString() in the log file, is that what this is primarily about? Updating the tests to include the InnerException details?

I think how we handle the 'ExpectedExceptionTests' is a little different since those are not "unexpected" exceptions, @iamjasonp  has good feedback regarding that.

**Comment by iamjasonp** [comment]
I think the general guidance I use for myself is: 

* Don't use a catch-all `catch (Exception)` - this messes with any xunit `Assert`s you might use inside the try block. If you think you need to use it, in my experience, chances are you really don't need it if you re-jig the test slightly. 
* xunit does a good job of printing out the entire exception message and inner exception if there's an unexpected exception - so we don't really need to use the StringBuilder anymore unless you're trying to log/catch multiple exceptions. 
* You should try to use the more specific helper (e.g., `Assert.Equal<T>`, `Assert.StrictEqual`, `Assert.IsAssignableFrom`, etc.) if possible, but you will notice that many of them do not provide a way to output a nicer message. In that case, I'm using `Assert.True` to provide the message as I haven't yet seen a better way.

**Comment by StephenBonikowsky** [comment]
I see, so if we are talking about updating all the tests to remove StringBuilder this becomes a fairly large PR.

**Comment by iamjasonp** [comment]
I think this can happen slowly do this as tests and scenarios get added. If you notice old-style exception handling, then just fix the rest of the tests in the same file/project? 

The only ones that I would consider urgent are ones that are failing in CI and are not providing enough debug info. 

Eventually (i dunno, a few months?) we should end up in a state where there are a few tests left that haven't been touched in a long time, and we can one-shot change them at that point.

**Comment by StephenBonikowsky** [comment]
Update: We continue to update existing tests with this new cleanup process as we touch test files for whatever reason.

**Comment by StephenBonikowsky** [comment]
Update ExpectedException tests, https://github.com/dotnet/wcf/pull/1677

**Comment by StephenBonikowsky** [comment]
https://github.com/dotnet/wcf/pull/1691
