### ISSUE TITLE
Need to build xplat package for System.Private.ServiceModel

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#749]
The S.P.SM.pkgproj is currently building only a Windows version, and when developers use WCF packages on Linux, they get the Windows version. We need to modify our pkgproj to package the Linux version as well as the Windows version

There are examples of packages that do this already in corefx.  For example System.Private.Uri or System.IO.Filesystem.

**Comment by StephenBonikowsky** [comment]
Fixed by PR #754
