### ISSUE TITLE
Reorganize unit tests

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#75]
The unit tests need to be organized slightly.  At a high level I recommend we adopt these conventions:
 * (Like today) keep unique folders corresponding to each contract (e.g. src\S.SM.Http\tests)
 * (Like today) the tests in these contract-specific folders will test only types that belong to that contract.
 * (New) these contract-specific tests will test *all* public members of the types in the contract, even if those members themselves are not part of the contract.
 * (Like today) keep a single folder under S.Private.SM/tests for all tests for types not in any contract
 * (Like today) folders under the unit tests will follow the normal namespace/folder naming conventions, and each test class will test exactly one type (by appending the word "Test" to the name of the type).

Changes needed to get there:
 * System.ServiceModel.Tests.Common should move from root down into tests/common folder
 * Any existing tests under S.Private.SM for types belonging to a contract should move to their respective contract-specific folder
 * We should create a new folder called "unit" parallel to "Scenarios" and move all (not in contract) unit tests currently under S.Private.SM\tests to be under "unit" instead

When this refactor is complete, "src\System.Private.ServiceModel\tests" will contain these 3 folders:
 * unit
 * scenarios
 * common

And "src" will contain these folders:
 * System.Private.ServiceModel\tests
 * System.ServiceModel.Primitives\tests
 * System.ServiceModel.Http\tests
 * System.ServiceModel.NetTcp\tests
 * System.ServiceModel.Security\tests
 * System.ServiceModel.Duplex\tests

**Comment by StephenBonikowsky** [comment]
Issue completed with PR #141, closing.
