### ISSUE TITLE
Please add support for System.ServiceModel.Syndication

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/wcf#76]
Please create a NuGet package for System.ServiceModel.Syndication. A lot of ASP.NET MVC users use SyndicationFeed to create Atom/RSS feeds.

I myself want to use it in <a href="https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d">ASP.NET MVC Boilerplate</a>.

Thank You!

**Comment by arc95** [comment]
I've experienced this issue and had to find other ways to parse the Atom/Rss feed, as detailed in this StackOverflow post: http://stackoverflow.com/questions/30262874/install-asp-net-5-0-version-of-system-servicemodel-syndication

Even following the instructions provided by some helpful people there, I ran into additional obstacles and decided to abandon the effort. Please bring the System.ServiceModel.Syndication back in ASP.NET MVC. Thanks.

**Comment by iamjasonp** [comment]
Thanks, @RehanSaeed, @arc95! 

Seems like a discussion is needed on how this library is used out in the wild, whether or not this is the correct place for System.ServiceModel.Syndication, and how to prioritize such work.

Example: we took out all the DataContractSerializers from the WCF main project as it was used by far more than just WCF - it currently lives in the dotnet/corefx repo. 

You've both mentioned that you want to use this in ASP.NET MVC. Is this a common case?

**Comment by RehanSaeed** [comment]
I believe it would make more sense to put this under System.Web.Syndication as this code is generally used to parse or generate Atom or RSS feeds. I personally don't know any other use cases.

If you search for SyndicationFeed on StackOverflow, you will find a lot of people using it in their MVC or Web Forms projects, specifically to parse or generate Atom or RSS feeds.

**Comment by mconnew** [comment]
@RehanSaeed, the question of what namespace for the functionality to live under will affect how the library is pulled into your code when referenced against various versions of .Net. It will be easiest to explain by example. If you create a portable library and want to use HttpClient, you add a reference to your project for System.Net.Http. If your portable library is being used in a universal windows application, your reference to System.Net.Http will cause an implementation of HttpClient from .Net native to be used which builds on top of the Win RT HttpClient. If your portable library is used in a asp.net v5 (using core clr) website, it will pull in a core clr implementation which builds on top of the win32 WinHTTP api. If your portable library is used in a desktop application, then the version of System.Net.Http that ships with the desktop version of .Net which uses HttpWebRequest will be used. This can be done because the same namespace and class types are used on all these platforms.
If the syndication code is moved to System.Web.Syndication, on platforms which already have the implementation already available such as mono, Silverlight or the desktop clr, the existing implementation can't be used and new code will need to be distributed with the app. This increases memory usage in some use cases.

**Comment by mconnew** [comment]
@RehanSaeed , @arc95, the first step is to clearly scope your requirements. Can you please let us know the api's you need. This would include which classes you use, which properties and methods you need, and which constructor overloads you use.

**Comment by RehanSaeed** [comment]
I have created a full list of types and members I use below for the <a href="https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate">ASP.NET MVC Boilerplate</a> project. You can see the usages of the code on GitHub <a href="https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC5/Boilerplate.Web.Mvc5/SyndicationFeedExtensions.cs">here</a> and <a href="https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC5/Boilerplate.Web.Mvc5.Sample/Services/Feed/FeedService.cs">here</a>.

I realize the concern about extra memory used if it was split into a separate assembly. However, it's rightful place is as a web component. All new web components seem to be placed under System.Net, so perhaps that's where it should go. It really has very little to do with WCF.

<h2>SyndicationFeed</h2>
<ul>
<li>Id</li>
<li>Title</li>
<li>Items</li>
<li>Description</li>
<li>LastUpdatedTime</li>
<li>ImageUrl</li>
<li>Copyright</li>
<li>Language</li>
<li>Generator</li>
<li>Links</li>
<li>Authors</li>
<li>Categories</li>
<li>Contributors</li>
<li>Please add an Icon property as per the <a href="https://tools.ietf.org/html/rfc4287">Atom 1.0 spec</a></li>
<li>AttributeExtensions</li>
</ul>

<h2>SyndicationContent</h2>
<ul>
<li>SyndicationContent.CreatePlaintextContent(string content)</li>
</ul>

<h2>TextSyndicationContent</h2>
<ul>
<li>TextSyndicationContent(string text) constructor</li>
</ul>

<h2>SyndicationItem</h2>
<ul>
<li>Id</li>
<li>Title</li>
<li>Summary</li>
<li>LastUpdatedTime</li>
<li>PublishDate</li>
<li>Copyright</li>
<li>Links</li>
<li>Authors</li>
<li>Contributors</li>
<li>Categories</li>
</ul>

<h2>SyndicationElementExtension</h2>
<ul>
<li>GetObject<T>()</li>
<li>SyndicationElementExtension(string outerName, string outerNamespace, object dataContractExtension)</li>
<li>SyndicationElementExtension(object dataContractExtension)</li>
</ul>

<h2>SyndicationLink</h2>
<ul>
<li>SyndicationLink.CreateSelfLink(Uri uri, string mediaType)</li>
<li>SyndicationLink.CreateAlternateLink(Uri uri, string mediaType)</li>
<li>SyndicationLink(Uri uri, string relationshipType, string title, string mediaTypem long length)</li>
</ul>

<h2>SyndicationCategory</h2>
<ul>
<li>SyndicationCategory(string name)</li>
</ul>

<h2>SyndicationPerson</h2>
<ul>
<li>Name</li>
<li>Uri</li>
<li>Email</li>
</ul>

**Comment by kobynet** [comment]
+1

**Comment by horsdal** [comment]
:+1: from me. I too could use the `Syndication` types to create feeds in a DNX solution. For my scenario though I do not have `MVC`, just ASP.NET 5.

**Comment by roncain** [comment]
Thanks for the additional feedback @horsdal . We'll factor it into our planning and update this issue when we've got something concrete to say.

**Comment by leus** [comment]
Is `System.ServiceModel` considered here? I need to use SOAP services in an MVC application and it's proving difficult.

**Comment by dansiegel** [comment]
Would have to say that Syndication needs to be baked in for sure. Given that the most common use case for this would be with and ASP.NET 5 project and given the modularized design the best thing would be to set add this as it's own package similar to Identity with it's own middleware.

**Comment by lviana1** [comment]
+1 for this. A lot of ASP.NET MVC users use the Syndication classes to consume and create Atom/RSS feeds, so we need this back in ASP.NET v5. Any ideas as to which milestone this is being considered under?

**Comment by tparnell8** [comment]
:+1:  creating rss feeds is a key for websites that have any kind of subscriptions

**Comment by lviana1** [comment]
What I think needs to happen here is that all the code under the System.ServiceModel.Syndication namespace needs to be moved to .NET Core (dotnet/corefx repo). You mention that something similar was already done with the DataContractSerializers code. The System.ServiceModel.Syndication functionality is used extensively by both, ASP.NET server-side web apps, as well as client-side apps, so I believe a similar move is needed. If this component is moved to .NET core, and a NuGet package is created for it, then cross-platform ASP.NET 5 web apps, as well as client apps, will be able to continue using it.

**Comment by tparnell8** [comment]
I would like to see this moved into its own nuget package that can target the core runtime. Generating RSS feeds, and reading rss feeds are done in a multitude of applications (web, client, etc), and not being able to use this library is a blocking factor in using the core runtime.

**Comment by daveaglick** [comment]
I agree with @tparnell8, this should not be tied up with a web-specific library. I write a static site generator and so I have a need to create and consume RSS/Atom feeds outside the context of any specific web framework.

**Comment by RehanSaeed** [comment]
Is this completed? I noticed a "System.ServiceModel.Web" package but it doesn't seem to work with ASP.NET Core RC2.

**Comment by roncain** [comment]
Hi @RehanSaeed -- sorry, but no new announcements on Syndication. We're still working full out to solidify the current feature set and discussing how to handle packages like Syndication. We understand the need and appreciate your detailed list of required API's in the comments above, but we can't yet promise when or how it might be delivered.  As we make decisions about it, we'll do what we can to keep this current issue updated.  For our future planning, we're ranking requested features by relative importance, and so as always we appreciate knowing how you yourself rank Syndication with respect to other features you need.

**Comment by RehanSaeed** [comment]
@roncain Totally understand and appreciate your efforts.

Right now, `SyndicationFeed` and `SmtpClient` is the only thing stopping me from using and recommending .Net Core over the full .Net framework. Based on the GitHub and StackOverflow comments I have seen, there are many others in the same boat. My understanding is that one of the Azure clients (Was it DocumentDB?) is also held up due to this issue.

**Comment by madmunsterdaddy** [comment]
This should really be in its own library anyways and not tied to WCF. As was mentioned earlier, it's such a common requirement and one can assume many ASP.NET MVC users are going to be using this.

**Comment by SyntonicStudios** [comment]
I'm about to port a web application to .net core and it is currently using SyndicationFeed and would greatly appreciate this namespace in .net core. I'd really hate to reinvent the wheel just to do clean RSS parsing - though if anyone has some good ideas to hold me over until this gets ported I'd love to hear them. Thanks.

**Comment by zrhyvr** [comment]
I am also using SyndicationFeed. SyndicationFeed has a unified interface for both Atom and Rss, but sometimes it can be confusing and tricky to use. It is better to create two different types for Atom and Rss.

**Comment by MissyMelissa** [comment]
Any updates?

**Comment by zhenlan** [comment]
@MissyMelissa thanks for querying. This is still in our backlog.

**Comment by RehanSaeed** [comment]
Still not available in .NET Core 2.0 Preview 1 which probably means 2.0 RTM will not have it either, am I right?

**Comment by zhenlan** [comment]
Syndication will not be part of .NET Core 2.0. We are in planning phase.

Looks like it's consensus here Syndication should be in its own package. At this point, it probably also makes sense for Syndication to be built on Net Standard (if possible) so it can run on different frameworks. We are also thinking about improvement over the version in full framework, for example, more flexibility of parsing date-time formats. If anyone has any pain points of using the version of Syndication in full framework, we would love to hear and will appreciate your feedback.

**Comment by dodyg** [comment]
Another useful thing is to add a way to deal with the feed extensions. RSS/ATOM allows extensions through namespaces and I think there was no easy way to deal with them through SyndicationFeed.

For example:

https://en.wikipedia.org/wiki/Media_RSS

**Comment by zhenlan** [comment]
@dodyg thanks for the feedback. We will look into this.

cc: @eljerry

**Comment by dodyg** [comment]
> We are also thinking about improvement over the version in full framework, for example, more flexibility of parsing date-time formats.

This is a critical feature. The web is full of broken RSS dates.

**Comment by zhenlan** [comment]
Hi everyone, I just posted our roadmap for SyndicationFeed at #2098. Any feedback is welcome!

**Comment by BryanWilhite** [comment]
I extracted a simple, single-concern version of `SyndicationFeed` directly from `System.ServiceModel.Syndication.SyndicationFeed` [[my source](https://github.com/BryanWilhite/Songhay.Feeds/blob/master/Songhay.Syndication/SyndicationFeed.cs)]. Now I would like to add content-negotiation support which means I will need `Rss20FeedFormatter` and `Atom10FeedFormatter`, right? Do these formatters not support `async` correctly? Is that why @zhenlan is blocked from proceeding? @RehanSaeed?

**Comment by Lxiamail** [comment]
Since we have released  System.ServiceModel.Syndication on .NET Core, close this issue. Please let us know if your issue is still not addressed.
Source: https://github.com/dotnet/corefx/tree/master/src/System.ServiceModel.Syndication
NuGet package: https://www.nuget.org/packages/System.ServiceModel.Syndication/
