### ISSUE TITLE
Investigate NetTcp HelloWorld throughput regression in RC2 comparing to RC1

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#764]
The NetTcp helloworld perf tests consistently show 8% sync and 15% async throughput regression in RC2 comparing to RC1. We'll need profiles to figure out why.

**Comment by zhenlan** [comment]
We should measure again to see if this is because of ETW tracing.

**Comment by zhenlan** [comment]
@mconnew has a PR for this now #974

**Comment by zhenlan** [comment]
Extra ETW fix is going to be tracked by #1217.
