### ISSUE TITLE
ChannelFactory.Open takes more than a minute

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#775]
Calling Open on a channel factory takes more than a minute.
I am using XmlSerializer for my WCF client. This is caused by the presence of a lot of known-type attributes and xml-include attributes. 
System.Xml.Serialization.XmlIncludeAttribute
System.ServiceModel.ServiceKnownTypeAttribute

For the desktop version of .Net I address this by generating static serializers using svcutil and stripping the attributes. The speed up is like 100x.
I can't strip the attributes without a proper serializer as some of those attributes are significant for the deserialization process.

Are there any plans to introduce a similar workaround for .Net Core or improve the way dynamic serializer are created?
This might also be an issue with how those attributes are interpreted by the XmlSerializer behavior in WCF, though I am not sure I could comprehend the whole algorithm just by looking at the code and debug.

**Comment by zhenlan** [comment]
Thank you for the feedback @atanasa. We are looking into potential solutions for pre-generated serializers for .NET Core. This work is tracked by dotnet/corefx#4561.

cc: @shmao, FYI

**Comment by shmao** [comment]
@atanasa, Thanks for reporting the issue. Would you mind sharing your ServiceReference.cs file with me? I can do some investigation and see what caused the long starting time. Thanks.

**Comment by atanasa** [comment]
@shmao, this is code that reproduces the perf issue:
[WcfPerfTest.zip](https://github.com/dotnet/wcf/files/132539/WcfPerfTest.zip)

The delay is split between Factory.Open and the first call to the web service (the serialization part).
The output from the perf test for me is:

Factory.Open: Time elapsed: 55618 ms
Dummy service call (serialization incl.): Time elapsed: 31538 ms
Total time elapsed: 102508 ms

**Comment by shmao** [comment]
Thanks for providing the repro app, @atanasa . I will give it a try.
