### ISSUE TITLE
Move Jenkins CI to use build.sh on Linux from run-tests.sh

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#784]
The current process for running tests on Linux in CI is quite complicated, involving lifting binaries from another CI job, copying over, and running. 

We should investigate moving to use ./build.sh in Linux for building and running. See #782 for some of the discussion we've already had about whether to (or not) move to using build.sh in Linux build + test.

**Comment by zhenlan** [comment]
As part of this clean up, we should have our documentation cleaned up as well.

**Comment by iamjasonp** [comment]
@mmitche, we want to move away from ./run-tests.sh to using build.sh to build and test on a Linux box directly. 

build.sh will restore packages, then build, then test. 

Is it okay for us to do this, or are there considerations that prevent us from moving to build.sh... for example, are there considerations and limitations on the amount of time we should take on the Linux boxes?

**Comment by mmitche** [comment]
Nope, that's totally fine.  When you move to that, can you affinitize the new runs with setMachineAffinity(newJob, 'Ubuntu14.04', 'latest-or-auto') ?

**Comment by iamjasonp** [comment]
Gotcha. Thanks @mmitche!

**Comment by iamjasonp** [comment]
Fixed by #801
