### ISSUE TITLE
Scenario Test Needed: ChannelLayer tests

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#80]
Need to add "OneWayChannelShapeTests.cs" under System.Private.ServiceModel\tests\Scenarios\Client\ChannelLayer and add tests using IOutputChannel and IInputChannel. (Session variation as well)
Need to add some coverage for IRequestSessionChannel.
Need to add an IRequestChannel test using the NetHttpBinding.
Need to add test coverage for IChannelFactory(IDuplexChannel>.

**Comment by StephenBonikowsky** [comment]
IRequestSessionChannel requires System.ServiceModel.Channels.SymmetricSecurityBindingElement which is not yet supported in K, it comes with WSHttpBinding.

**Comment by SajayAntony** [comment]
@iamjasonp might make sense to close this for now and park it for when IRequestSessionChannel really becomes useful.

**Comment by iamjasonp** [comment]
All - any suggestions on how best to "park" an issue in the way @SajayAntony mentions and not lose track of the knowledge that @StephenBonikowsky has put in here already? 

Might be good just to leave this issue around or rename it to make it track "Implement `x, y, z` + tests" or something. Once closed, it's probably easier to lose track of the issue?

**Comment by StephenBonikowsky** [comment]
Well this particular issue cover more than just IRequestSessionChannel. Maybe I should have opened several separate issues but I am now working on the one-way channel shape tests and would likely reference this issue in the PR.

**Comment by zhenlan** [comment]
@StephenBonikowsky Do you have any update for this?

**Comment by StephenBonikowsky** [comment]
Had dropped this due to other higher priority tasks, will pick it back up now and finish it before the holidays.

**Comment by StephenBonikowsky** [comment]
Based on code coverage analysis...
   - IOutputChannel and IInputChannel are well covered as they are used by other channels within WCF.
   - IDuplexChannel is nothing more than IOutputChannel and IInputChannel together.
   - IRequestChannel on various bindings doesn't gain any additional coverage.
   - Session variations of various channels can be tested when they are added as new features.
