### ISSUE TITLE
Support SecurityMode.Transport for NetTcpBinding

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#81]
Currently throws: System.PlatformNotSupportedException: SecureConnectionDuplexSession is not supported.

**Comment by iamjasonp** [comment]
We will still need the NegotiateStream implementation (dotnet/corefx#1844) in order for us to fully implement this.

**Comment by iamjasonp** [comment]
Note: not in scope for this: dotnet/corefx#1844 (NegotiateStream) for the time being; we will focus on bringing this scenario up using SslStream for the time being until NegotiateStream is implemented.

**Comment by iamjasonp** [comment]
Fixed by #311 - closing
