### ISSUE TITLE
System.Net.Http.WinHttpException: A security error occurred while invoking WCF service in .Net core

### ISSUE THREAD

**Issue by venknar** [dotnet/wcf#828]
Hi

Invoking a WCF service with basichttpbinding from a console application. Getting an error saying "Security error has occurred".

Not able to figure out what is happening. This is the same code that works fine with the full .Net framework.

Here is the sample source code:

```
        this.channelFactory = new ChannelFactory<T>(
                this.helper.Binding,
                new EndpointAddress(this.endpoint));

        this.channelFactory.Credentials.ServiceCertificate.Authentication.CertificateValidationMode = 
            X509CertificateValidationMode.Custom;
        this.channelFactory.Credentials.ServiceCertificate.Authentication.CustomCertificateValidator = 
            helper;
        this.channelFactory.Credentials.ServiceCertificate.SslCertificateAuthentication =
            this.channelFactory.Credentials.ServiceCertificate.Authentication;

        this.openTimeoutSec = this.channelFactory.Endpoint.Binding.OpenTimeout;
        this.clientChannel = this.channelFactory.CreateChannel();

        this.clientChannel.Opening += new EventHandler(HandleOpeningEvent);
        this.clientChannel.Opened += new EventHandler(HandleOpenedEvent);
        this.clientChannel.Faulted += new EventHandler(HandleFaultedEvent);
        this.clientChannel.Closing += new EventHandler(HandleClosingEvent);
        this.clientChannel.Closed += new EventHandler(HandleClosedEvent);

        object requestMessagePropertyObject = null; 
        if (!OperationContext.Current.OutgoingMessageProperties.TryGetValue(HttpRequestMessageProperty.Name, out requestMessagePropertyObject))
        {
            throw new InvalidOperationException();
        }

        HttpRequestMessageProperty requestMessageProperties = (HttpRequestMessageProperty)requestMessagePropertyObject;

        // Get the ACS token and set the authorization header
        string acsToken = GetAcsToken(operationEta);
        if (acsToken != null)
        {               
            requestMessageProperties.Headers[HttpRequestHeader.Authorization] = acsToken;
        }
        this.clientChannel.Register();
```

Stack trace of the exception is:

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
**System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---

> System.Net.Http.WinHttpException: A security error occurred
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at **System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__11.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReaso
> n)
>    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__33.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
>    at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
>    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
>    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
>    at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)

**Comment by venknar** [comment]
Hi, 

If you could please guide me on how to enable tracing and figure out the root cause, it would be great. I tried gathering the ETW traces using the instruction given here - https://github.com/dotnet/wcf/blob/master/Documentation/HowToUseETW.md

For .Net core I do not see any trace collected when I hit the above issue.

Thanks
Venknar

**Comment by iamjasonp** [comment]
Hi @venknar,

Previously, I've seen a similar issue manifest itself when the certificates I was presenting were invalid (e.g., expired certs, self signed cert but not trusted, self signed cert but not for the same hostname). 

Can you confirm: 
* That You are using https / transport security
* If you are using transport security, your certificates are okay (inspect using certmgr.msc)
* when comparing against desktop, what version are you using? 

You may also get a hint on what's happening by enabling tracing / ETW on the server side if the client side tracing isn't working. @mconnew, any thoughts on the tracing issue here?

**Comment by iamjasonp** [comment]
FYI, this was the change in 4.6.1+ in cert validation: 
http://stackoverflow.com/questions/34910373/wcf-sslstreamsecurity-dns-identity-check-failing-for-just-4-6-framework

This shouldn't be an issue in WCF Core though, but we're still handling things a bit differently.
