### ISSUE TITLE
System.ServiceModel.NetTcp specify dependency on System.Runtime on .NetCore

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#841]
In VS update 2 + projectK RC1 testing, there is a warning that system.runtime has downgraded because System.ServiceModel.NetTcp and S.P.SM specify different versions. The warning should go away for future projectK release as we now use stable version of system.runtime in S.P.SM.

However, System.ServiceModel.NetTcp specifies dependency on system.runtime ONLY for .NetCore(not DNXCore). We should investigate why it's needed in .NetCore, and remove the dependency if it turns out not needed.

**Comment by StephenBonikowsky** [comment]
The nuspec content for our Contracts has seen a lot of churn recently.
Where before we saw a dependency on "dnxcore50" we now see ".NETStandard1.?", the listed dependency on System.Runtime seems to be correct at this point for the various target frameworks.
