### ISSUE TITLE
Determine how to test NegotiateStream with explicit credentials specified

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#851]
I would like a test case that allows us to test NegotiateStream + Kerberos with explicit credentials, for example, specified like this: 

``` csharp
factory = new ChannelFactory<IWcfService>(
    binding,
    new EndpointAddress(new Uri(Endpoints.Tcp_DefaultBinding_Address))
);


factory.Credentials.Windows.ClientCredential.Domain = "someDomain";
factory.Credentials.Windows.ClientCredential.UserName = "someUser";
factory.Credentials.Windows.ClientCredential.Password = "somePassword";
```

We need to 
1. figure out if there's any way to do testing without a domain joined server machine
2. figure out how to share secrets among machines so that they can be tested
3. set it all up automagically for automated testing

**Comment by zhenlan** [comment]
Automation of this might not be simple. For now, we will add this to be part of our manual test guidance https://github.com/dotnet/wcf/blob/master/Documentation/manualtest-guide.md.

**Comment by mconnew** [comment]
There's a new Azure service in preview which might help. [Azure Active Directory Domain Services](https://azure.microsoft.com/en-us/services/active-directory-ds/)

**Comment by iamjasonp** [comment]
Tried this. This works! But it's not nicely automatable since it's still in preview. I suppose that when this is released for real, we might be able to provision this via API or something. 

In the meantime, I think we will have to make do with manually testing this.

**Comment by StephenBonikowsky** [comment]
I am removing this Issue as the ActiveIssue used to skip these tests and instead adding the ConditionaFact 'Domain_Joined', if/when this is solved the tests will start running.

**Comment by hongdai** [comment]
We now have a once per week manual run to cover it.
