### ISSUE TITLE
Cookies do not work on dnxcore50

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#853]
When I invoke operations on a channel that has AllowCookies = true, on dnxcore50 it fails with:

Unhandled Exception: System.InvalidOperationException: **When using CookieUsePolicy.UseSpecifiedCookieContainer, the CookieContainer property must not be null.**

On net451 it looks ok.

The bindings that I tried:

```
var factory = new ChannelFactory<T>(
             new BasicHttpBinding() {
                 AllowCookies = true
             }, 
             new EndpointAddress(new Uri(serviceUrl)));
```
```

var factory = new ChannelFactory<T>(
             new CustomBinding(
                    new TextMessageEncodingBindingElement(MessageVersion.Soap11, System.Text.Encoding.UTF8), 
                    new HttpTransportBindingElement() {
                        AllowCookies = true
                    }), 
             new EndpointAddress(new Uri(serviceUrl)));
```

I've also checked if there is a cookie container at IHttpCookieContainerManager, and there is one there prior to invoking an operation.

The full code sample that I use to reproduce:
[WcfCookieTest.zip](https://github.com/dotnet/wcf/files/146443/WcfCookieTest.zip)

I couldn't find where the cookie container from IHttpCookieContainerManager is passed to the HttpHandler on .Net Core so that might be the issue.

**Comment by shmao** [comment]
Thanks for submitting the issue, @atanasa . I will investigate the issue.
