### ISSUE TITLE
Investigate regressions in HelloWorld over Http throughput

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#861]
We see about 10% regression on rc3 23822 running on dnx build 16551 comparing to rc3 23811 running on dnx build16496. More investigations needed to determine if this is due to CLR / corefx / or WCF itself.

**Comment by zhenlan** [comment]
Action items:
- validate to see if this regression is because of DNX
- Profile two builds that have the regression to see if there any difference

**Comment by zhenlan** [comment]
@KKhurin will measure again with rc2 packages.

**Comment by KKhurin** [comment]
We got the official numbers for RC2 (comparing to RC1) for 24 core servers. RC2 did not regress comparing to RC1 in HelloWorld over HTTP so we're closing this one.
