### ISSUE TITLE
Investigate RC1 - RC2 regressions in HelloWorld (NetTcp) and Duplex (NetTcp) throughput

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#862]
We see about 8% regression on rc3 23822 running on dnx build 16551 comparing to rc3 23811 running on dnx build16496. More investigations needed to determine if this is due to CLR / corefx / or WCF itself.

**Comment by zhenlan** [comment]
@KKhurin will measure again with rc2 packages.

**Comment by KKhurin** [comment]
We got the numbers for RC1 and RC2 on 24 core client (running against a 24 core server).
Will update as soon as we have the profiles.

**Comment by KKhurin** [comment]
Got the profiles for Desktop, RC1 and RC3

**Comment by zhenlan** [comment]
This is fixed as part of #1217.
