### ISSUE TITLE
EndpointNotFoundException scenario test fails periodically on CI machine

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#87]
Every 2nd day or so, this test fails.  It is the only failure.

MESSAGE:
Expected exception: EndpointNotFoundException, actual: System.IO.IOException
+++++++++++++++++++
STACK TRACE:
at ExpectedExceptionTests.UnknownUrl_Throws_EndpointNotFoundException() in d:\j\workspace\dotnet_wcf_outerloop\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 315

**Comment by iamjasonp** [comment]
Looks like this is a high priority test to fix when fixing #74.

**Comment by shmao** [comment]
This is an NCL issue. I've come up with a repro which involves with System.Net APIs only. Opened a issue for NCL team.

**Comment by roncain** [comment]
Tracking https://github.com/dotnet/corefx/issues/4934

**Comment by shmao** [comment]
The NCL team confirmed that this was caused by a bug in HttpClient and they would investigate a fix. Marked this issue as 'tracking'.

**Comment by shmao** [comment]
According to @davidsh 's comment in https://github.com/dotnet/corefx/issues/4934 ,

> It has been determined by the WinHTTP team that the IOException is being caused by a bug/race condition in native WinHTTP. There is no current workaround. Even ignoring the error from WinHttpWriteData() will not allow a subsequent WinHttpReceiveResponse() to work, despite the response headers actually being transmitted on the wire from the server to the client.

>So, the fix for this will require a Windows OS fix in a future Windows 10 update

**Comment by zhenlan** [comment]
dotnet/corefx#4934 has been fixed. This can be closed. @StephenBonikowsky can you check if we have any test cases disabled by this issue? Thanks.

**Comment by StephenBonikowsky** [comment]
Test case is active and passing.
