### ISSUE TITLE
Sync WCF and Corefx versions of netci.groovy

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#874]
We have made significant WCF specific changes to this file and just recently Corefx completely overhauled the file.

How do we handle this? Some changes Jason made to it in our repo may now also be part of the latest version in Corefx while other changes we have made probably need to remain unique to our version.

**Comment by iamjasonp** [comment]
The changes don't look super significant to what we care about. Most of the changes seem to do with the use of build flows / packing and unpacking assets. We don't use either.

**Comment by zhenlan** [comment]
The consensus of triage is to not update this until this become a problem or we have specific needs to update this. This way we don't have to deal with too much potential churns.

**Comment by iamjasonp** [comment]
I'm thinking that this will be harder going forward, as we start putting our own extensions into the netci.groovy file. Let's do this as needed.

**Comment by iamjasonp** [comment]
Fixed by #932
