### ISSUE TITLE
Update project.json files to latest rc version

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#875]
Update all the project.json files to depend either on stable package versions if they exist, otherwise to the latest RC versions.

**Comment by zhenlan** [comment]
- [ ] Update the normal project.json to take dependency on rc3 version of packages sync'ed with corefx
- [ ] Fix build breakage when we try to build against the latest dependencies (floating)

**Comment by roncain** [comment]
Observation: when upgrading LatestDependencies/project.json it looks like some have also changed either their minor or patch numbers as well, including:

- System.Runtime.Serialization.Xml
- System,Security.Cryptography.X509Certificates

**Comment by ericstj** [comment]
Serialization bumped the version because of the stable release for UWP.  Crypto bumped *minor* version due to API refactoring to support net46 & net461 (instead of just net461).

**Comment by StephenBonikowsky** [comment]
Latest dependencies project should also be fixed now. Assigning to Hong for verification.
