### ISSUE TITLE
Re-enable use of new CoreCLR MsBuild in Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#889]
Once PR #888 has been merged, we should be able to revert the changes we made in PR #879. #888 removes the dependency on CodeTaskFactory, which was breaking the Linux build.

**Comment by roncain** [comment]
Please buddy-build under Linux to verify after the fix.  The CoreCLR MsBuild does not support certain string operations (i.e. MsBuild property functions), and we need to make sure we aren't using any of those.

**Comment by StephenBonikowsky** [comment]
Verified fixed.
