### ISSUE TITLE
Build.cmd gives error message attempting to build  native components

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#891]
The build.cmd we inherited from CoreFx attempts to build native components (which don't exist in WCF) and issues an error message.  It does not fail the build but should be silenced.  The build sequence looks like this:

c:\OSS\wcf>build /p:SkipTests=true
Tools are already initialized.
[13:32:30.22] Building Native Libraries...
The system cannot find the path specified.
Native component build failed see nativebuild.log for more details.

Verify the experience with build.sh is also free of errors or warnings about native components.

**Comment by StephenBonikowsky** [comment]
It would be ideal to get this fixed in corefx, have opened https://github.com/dotnet/corefx/issues/7001

**Comment by StephenBonikowsky** [comment]
The issue was fixed and our version of build.cmd has been updated.
