### ISSUE TITLE
Implement DuplexClientBase

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#90]
As per issue https://github.com/dotnet/wcf/issues/1, implement DuplexClientBase

**Comment by SajayAntony** [comment]
Won't #111 be blocked by this?

**Comment by iamjasonp** [comment]
@SajayAntony Yes, it's kind of a circular reference. Basically we are using work done in #111 to validate anything we do here.

**Comment by iamjasonp** [comment]
Tests written.
