### ISSUE TITLE
Decide how SpnEndpointIdentity.SpnLookupTime property setter should behave

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#902]
PR #901 added back the SpnLookupTime to SpnEndpointIdentity because it was part of the public contract.  But it was added only as an auto-property to un-break a TFS build.  We need to decide whether it is preferable for the setter to (a) be a NOP, (b) behave like the desktop, or (c) throw PNSE

**Comment by iamjasonp** [comment]
After looking I'm thinking we might as well implement this in CoreFx like we have on Desktop. It's a very lightweight implementation, so I see no harm in implementing it. 

The only internal usage I can find is http://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/SpnEndpointIdentity.cs,110 

... it's in a method which we are unable to support in CoreFx, as it attempts to map a given SPN to a Windows SID.

**Comment by roncain** [comment]
@iamjasonp -- I agree that the replicating the behavior of the property setter from the full framework seems best, even though we have no code to consume that property now.
