### ISSUE TITLE
[UserVoice] Get Active Directory user information

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#909]
Taken from 

http://email.feedback-poweredby.uservoice.com/c/eJxVj0GOwyAMRU_T7KiAQCgLFrOZa1TEdlLUFCIgieb2A7MbyYsv-z_bH53kQvshOD0hWUUPY4XiTy2sGJeFzGxn8BNoIYW1N8WPQvlMAegO6TO8HBrR5rPRM9cGpKARuhJWeeCIOGzuVetebuPXTX63unak8_5vTesuKR-f0oQQ3HDNjhhOysVv7AoR01XYvvnaXN1cjnWlUkOKf4TUejLGspUq81AbyDBkgpryD-uHWIid9J0YavbwDnF9QkJyBpRtmTmaBRQHwwUqC_bhFy-VnaYhO9hCrC15Purbl_7vL6PJZGg 

As a developer I need access to the current logged in active directory user to check if the user has a specific role.

Normally I do this with:

WindowsIdentity currentUser = WindowsIdentity.GetCurrent(); 
var groups = currentUser.Groups; 
or 
groups.Claims

So I can get the SID or the groups of the user. 

Most companies want to control the access of the user by the active directory. The enterprise application uses this information whether a user got access or not.

If there is no api to access this information, enterprise application development with uwp becomes uninteresting. Please help us out!

**Comment by zhenlan** [comment]
The user voice is an ask about WindowsIdentity support on UWP and I have routed it to the attention of proper owner team. Closing out this issue since it not an ask to WCF.

**Comment by mfe-** [comment]
@zhenlan Is it possible to get in touch with the proper owner team on github? I want to stay updated on the topic, otherwise I would create an issue on [corefx](https://github.com/dotnet/corefx)?.

**Comment by zhenlan** [comment]
@mfe- yes, creating an issue on corefx repo will be the best approach to get visibility of the discussion on this topic.
