### ISSUE TITLE
WCF build fail on Linux

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#922]
Most WCF tests failed on Linux. This was originally caused by dotnet/corefx#6883 that system.private.uri package is not built properly. To pick up the fix of this issue, WCF has to move dependencies forward to build 23819, which uncovered more issues with dependent packages. Below is latest error @StephenBonikowsky has found.

================
EXEC : error : System.Linq.Expressions 4.0.0 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [C:\OSS\wcf\build.proj]

The packages with these failures are…

-	System.Linq.Expressions
-	System.ObjectModel
-	System.Threading
-	System.Xml.ReaderWriter
-	System.Collections.Concurrent
-	System.Xml.XmlSerializer
-	System.Runtime.WindowsRuntime
-	System.Threading.Overlapped

**Comment by zhenlan** [comment]
@ericstj is currently working on PR #925 to address this issue.

**Comment by roncain** [comment]
This was fixed in master with #925 and ported to RC2 with #928
