### ISSUE TITLE
Could not load file or assembly 'System.Net.Security'

### ISSUE THREAD

**Issue by Lcng** [dotnet/wcf#927]
When using ChannelFactory.CreateChannel() to create a channel, I got the following Exception:
// ASP.NET 5, on Windows 10
Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

**Comment by roncain** [comment]
Thanks for contacting us @Lcng.  Could I ask you to describe what version of Visual Studio you are using and what package versions you are using in the project.json file in your project?  Thanks.

**Comment by zhenlan** [comment]
@Lcng if you are using ASP.NET 5/.NET Core 5 RC1, do you mind to try to update your project.json as suggested in Known Issues section of the [release notes](https://github.com/dotnet/wcf/releases)?

**Comment by Lcng** [comment]
Thank you @roncain and @zhenlan .
I am using ASP.NET 5/.NET Core 5. I added the required packages and the problem is solved. Thank you.

**Comment by zhenlan** [comment]
Great. Glad it helped. Thanks for trying out Core!
