### ISSUE TITLE
Support duplex channel in ServiceChannelFactory/ServiceChannel

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#93]
As per issue https://github.com/dotnet/wcf/issues/1

**Comment by zhenlan** [comment]
Use this issue to track adding unit tests for the subject.

**Comment by roncain** [comment]
Closing because the e2e scenarios worked when issue #1 was resolved.  This issue was a placeholder for my share of the work, but @mconnew did it all for us.  The types mentioned here are internal and cannot be unit tested.  The scenario tests do test these code paths.
