### ISSUE TITLE
Increase randomness of stress test settings

### ISSUE THREAD

**Issue by KKhurin** [dotnet/wcf#934]
Our stress tests would likely benefit from more random patterns as we converge with the number of issues we can find with the current static stress load.
- vary by number of tasks driving execution of tests
- vary by various test knobs themselves (timeouts, number of pooled communication objects, including scalability limits)
- vary by server settings (throttling, timeouts)

**Comment by Lxiamail** [comment]
Close it for now. Reactivate it if we see the need.
