### ISSUE TITLE
Wire up the callback instance context to the ServiceChannel when creating a DuplexChannelFactory

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#94]
As per issue https://github.com/dotnet/wcf/issues/1

**Comment by SajayAntony** [comment]
I would assign this to @mconnew since he has taken over lighting up duplex. Basically the dispatch should be another issue since it involves bringing over the invokers and the immutable dispatch runtime  but this one should be closed by - sajayantony/wcf@7fc19f0fb292f7095dbab76a88f4013775b37af4

**Comment by iamjasonp** [comment]
Agreed, and reassigning @mconnew.
