### ISSUE TITLE
The type or namespace web could not be found?DNX 5.0 Error code CS0234. The application is based on ASP.NET MVC 5. I tried adding references multiple times but failed.

### ISSUE THREAD

**Issue by mshahnawaz9935** [dotnet/wcf#940]

**Comment by zhenlan** [comment]
@mshahnawaz9935 this does not look like directly related to WCF. Do you want to open an issue in [aspnet repo](https://github.com/aspnet/home/)? If it is related to WCF, could you please clarify a bit?

**Comment by zhenlan** [comment]
@mshahnawaz9935 please let me know if you have other questions. I am closing out this issue for now.
