### ISSUE TITLE
Helix runs ignoring ActiveIssue when part of #if/#else/#endif logic.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#944]
Example test case: FunctionalTest.Client.ExpectedExceptions.Tests#ExpectedExceptionTests.TCP_ServiceCertRevoked_Throw_MessageSecurityException

The test case is attributed like this...
```
    [Fact]
#if FEATURE_NETNATIVE
    [ActiveIssue(833)] // Not supported in NET Native
#else
    [ActiveIssue(578)]
#endif
    [OuterLoop]
```
In this case when not running where FEATURE_NETNATIVE is true we should still be skipping the test for ActiveIssue 578, but the test case is running anyway on both OS X and Windows. (why it actually passed is another issue...)

**Comment by zhenlan** [comment]
According to @StephenBonikowsky, this test was ran and passed in Helix. @StephenBonikowsky will take another look to confirm if this is still the case.

**Comment by StephenBonikowsky** [comment]
This behavior is no longer reproducing. Closing.
