### ISSUE TITLE
Automate kinit step and kdestroy step for ambient credential NegotiateStream/security tests

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#945]
The following tests fail when Kerberos is not initialized, but passes when `kinit` is run and server is running as LOCAL SYSTEM 

```
   StreamingTests.NetTcp_TransportSecurity_StreamedRequest_RoundTrips_String [FAIL]
   StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String_WithSingleThreadedSyncContext [FAIL]
   StreamingTests.NetTcp_TransportSecurity_Streamed_RoundTrips_String [FAIL]
   StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String [FAIL]
   StreamingTests.NetTcp_TransportSecurity_StreamedRequest_Async_RoundTrips_String [FAIL]
   StreamingTests.NetTcp_TransportSecurity_StreamedResponse_Async_RoundTrips_String [FAIL]
   StreamingTests.NetTcp_TransportSecurity_StreamedResponse_RoundTrips_String [FAIL]
   StreamingTests.NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation [FAIL]
   StreamingTests.NetTcp_TransportSecurity_Streamed_Async_RoundTrips_String_WithSingleThreadedSyncContext [FAIL]
   Tcp_ClientCredentialTypeTests.SameBinding_DefaultSettings_EchoString [FAIL]
   Tcp_ClientCredentialTypeTests.SameBinding_SecurityModeTransport_EchoString [FAIL]
   NegotiateStream_Http_Tests.NegotiateStream_Http_AmbientCredentials [FAIL]
```

We need to be able to: 
- Run the Bridge/test host as LOCAL SYSTEM or another credential with access to the HOST/hostname SPN 
- Automate the `kinit user@dc.domain.com` step to specify the ambient Kerberos credential 
- Automate the `kdestroy -A` step to destroy the Kerberos credential

**Comment by iamjasonp** [comment]
For the moment, use manual test guide: https://github.com/dotnet/wcf/blob/master/Documentation/manualtest-guide.md

**Comment by zhenlan** [comment]
@iamjasonp let's consider a solution with the new test infrastructure, for example, host relevant service separately ran with LOCAL SYSTEM account.

**Comment by Lxiamail** [comment]
Since we have the manual coverage, the infrastructure work is not low cost. closing it for now.
