### ISSUE TITLE
Scenarios attempting to use S.Security.Principal.WindowsIdentity.GetCurrent fail

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#946]
We need to spend some time investigating the following security tests on Linux

Fails always: 

```
   HttpsTests.ClientCertificate_EchoString [FAIL]
   HttpsTests.ServerCertificateValidation_EchoString [FAIL]
   Https_ClientCredentialTypeTests.NtlmAuthentication_RoundTrips_Echo [FAIL]
   Https_ClientCredentialTypeTests.WindowsAuthentication_RoundTrips_Echo [FAIL]
   NegotiateStream_Http_Tests.NegotiateStream_Http_AmbientCredentials [FAIL]
```

These seem to stem from the following callstack: 

```
      Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
         at System.Security.Principal.WindowsIdentity.GetCurrent()
```

Investigate why using an ambient credential for Windows auth can work in tcp but not for http.

**Comment by iamjasonp** [comment]
Manual test guide updated: https://github.com/dotnet/wcf/blob/master/Documentation/manualtest-guide.md

**Comment by iamjasonp** [comment]
System.Security.Principal.WindowsIdentity.GetCurrent() is currently not an API supported in CoreFx, so are expected to fail on all platforms except Desktop. dotnet/corefx#7325 is an issue tracking a solution to the issue. 

(Note: no matter what, we will need to look at the manual test guide for this - #946

**Comment by zhenlan** [comment]
This issue has been worked around by #1569. However, the scenario still does not work E2E and it is tracked by #1589.
