### ISSUE TITLE
The NegotiateStream_Http_AmbientCredentials test fails on Windows (CoreCLR only)

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#949]
This test failed in Helix for the reason below.  Like #948, it is hard to diagnose cause for failure due to the Assert.True(bool) in the finally block.  Recommend catching unexpected exception and reporting it.  This same test passes in normal OSS runs as well as ToF N-from-K runs.
```
Path  FunctionalTest.Security.TransportSecurity.Tests#NegotiateStream_Http_Tests.NegotiateStream_Http_AmbientCredentials  
Run On  Tuesday, March 29, 2016 5:03 PM  
Architecture  AnyCpu  
Configuration  CHK  
OperatingSystem  Windows.10  

Test Output

Test Failed 
 Unhandled exception of type 'Xunit.Sdk.TrueException': Credentials passed:\r\n NegotiateTestRealm : 'DOMAIN.CONTOSO.COM'\r\n NegotiateTestDomain : 'DOMAIN'\r\n NegotiateTestUserName : 'testuser'\r\n NegotiateTestPassword : 'hunter2'\r\n NegotiateTestSpn : 'testhost.domain.contoso.com'\r\n NegotiateTestUpn : 'testuser@DOMAIN.CONTOSO.COM'\r\n\r\nExpected: True\r\nActual: False 
 at NegotiateStream_Http_Tests.NegotiateStream_Http_AmbientCredentials() in C:\wcftest\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Negotiate\NegotiateStream_Http_Tests.cs:line 94 

```

**Comment by iamjasonp** [comment]
The Assert.True() should not have prevented the exception message from bubbling up. I'll take a further look. My guess is that the Helix machines are not domain-joined and hence will fail here.

**Comment by zhenlan** [comment]
@iamjasonp please go ahead and update the test when you get a chance. We need to consider how to enable domain-joined server in our new test infrastructure.

**Comment by iamjasonp** [comment]
This test was fixed so we can see the exception messages.

**Comment by iamjasonp** [comment]
Passes on manual test run in Windows. On OS X and UWP, we require Kerberos creds to have already been set with `kinit user@REALM.DOMAIN.COM`
