### ISSUE TITLE
System.Net.Http.CurlException on OS X runs.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#952]
**SUMMARY**
This failure is happening on tests using BasicHttpSecurityMode.Transport (Https)

**Failing Tests**
-	Security.TransportSecurity.Tests#HttpsTests.CrossBinding_Soap11_EchoString
-	Security.TransportSecurity.Tests#HttpsTests.SameBinding_DefaultSettings_EchoString
-	Security.TransportSecurity.Tests#HttpsTests.SameBinding_Soap11_EchoString
-	Security.TransportSecurity.Tests#HttpsTests.SameBinding_Soap12_EchoString
-	Security.TransportSecurity.Tests#Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo
-	Security.TransportSecurity.Tests#Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException

**Call Stack**
System.ServiceModel.CommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates\n 
 at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)\n 
 at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, CURLcode messageResult)\n --- End of inner exception stack trace ---\n 
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n 
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n 
 at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()\n
  --- End of inner exception stack trace ---\n 
  at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(HttpRequestException requestException, HttpRequestMessage request, HttpAbortReason abortReason)\n 
  at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()\n
  --- End of stack trace from previous location where exception was thrown ---\n 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n 
  at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__34.MoveNext()\n

**Comment by StephenBonikowsky** [comment]
This may be related to #954 
According to @mconnew 
"Our certificate setup isn’t working correctly on OSX. Once that issue is resolved, I expect this failure to go away."

**Comment by iamjasonp** [comment]
How were certs set up? Was it done using the BridgeCertificateInstaller.sh script?

**Comment by iamjasonp** [comment]
Confirmed related to #954. For now we will have to manually test these scenarios.

**Comment by iamjasonp** [comment]
So this looks like a likely issue between how we use cURL and how it's handled on OS X. I'm still investigating this and will know the results shortly

**Comment by iamjasonp** [comment]
The difference is the default cURL version that is installed on the system. On Ubuntu, the cURL version installed relies on the OpenSSL root certificate bundle; on OS X, the default installed version relies on SecureTransport, which gets its root certificates from the OS keychain. 

We currently don't have setup/teardown that supports writing to the OSX system keychain yet, but we do know how to in Ubuntu. So this is a setup issue by and large. 

---

On Ubuntu: 

07:06 $ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 **OpenSSL/1.0.1f** zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

On OS X 

wcfmini:wcf wcfcore$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) IibcurI/7.43.0 **SecureTransport** zlib/1.2.5 
Protocols: dict file ftp ftps gopher http https imap imaps Idap Idaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

**Comment by raminescence** [comment]
Do we have any workaround for this issue.  Currently I am facing the same CA issue on my Mac however my colleague is not having this issue with exact similar spec/setup.  Not sure if there was a setting we could disable?

curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

**Comment by iamjasonp** [comment]
@raminescence - it depends what the issue is...

If you are trying to establish a HTTP connection, make sure your root certificate is installed in the OS X keychain. However, note that with libcurl+SecureTransport, features such as custom certificate validation won't work. If you want that, the only workaround we have right now is to install a copy of libcurl that supports OpenSSL and reference it (see https://github.com/dotnet/wcf/issues/1368#issuecomment-234695592) 

If you're using Net.Tcp, it should be possible to install the root cert into ~/.dotnet/corefx/cryptography/x509certificates/root and have the validation work.

**Comment by raminescence** [comment]
Thank you @iamjasonp   Adding it to the keychain and making sure that the "always trust" flag is marked, helped me to bypass the certificate issue.  Cheers.

**Comment by dilunika** [comment]
Thanks @iamjasonp I was able to overcome this issue by adding the untrusted certificate to OS X Key Chain (System).

NOTE: OSX Users .. once you add the cerficate to keychain, please make sure to select 'Trust Always' for that certificate. [Add Self Sign Cert to Mac](http://www.andrewconnell.com/blog/setup-self-signed-certificates-trusting-them-on-os-x)

**Comment by iamjasonp** [comment]
I found a command that can help here :smile: 

`sudo security -v add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/tmp/untrusted-root-cert.crt`

This will install the certificate to the keychain and trust it

**Comment by dilunika** [comment]
Thanks. That is cool.

**Comment by iamjasonp** [comment]
* Security.TransportSecurity.Tests#HttpsTests.CrossBinding_Soap11_EchoString
* Security.TransportSecurity.Tests#HttpsTests.SameBinding_DefaultSettings_EchoString
* Security.TransportSecurity.Tests#HttpsTests.SameBinding_Soap11_EchoString
* Security.TransportSecurity.Tests#HttpsTests.SameBinding_Soap12_EchoString
* Security.TransportSecurity.Tests#Https_ClientCredentialTypeTests.BasicAuthentication_RoundTrips_Echo
* Security.TransportSecurity.Tests#Https_ClientCredentialTypeTests.BasicAuthenticationInvalidPwd_throw_MessageSecurityException

Are passing on this CI run: http://ci.dot.net/job/dotnet_wcf/job/master/job/outerloop_osx_debug_prtest/322

I think this is safe to close this issue. If there are any further problems encountered, please reopen this bug

**Comment by iamjasonp** [comment]
Also passing in Helix [20160912.04](https://mc.dot.net/#/product/netcore/master/source/official~2Fwcf~2Fmaster/type/test~2Fscenario~2Fiishosted~2F/build/20160912.04). Due to a quirk in how this is reported the results don't appear explicitly as passed (i.e., the way to verify this is to note that they haven't been skipped...)
