### ISSUE TITLE
S.SM.Security.SecurityNegotiationException on OS X runs.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#956]
**SUMMARY**
We don’t expect ‘Client Certificates’ to work on any Linux platform, should these tests have ActiveIssues conditional on “PlatformID.AnyUnix”?

**Failing Tests**
FunctionalTest.Binding.Custom.Tests#CustomBindingTests.DefaultSettings_Tcp_Binary_Echo_RoundTrips_String
FunctionalTest.Security.TransportSecurity.Tests#IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException
FunctionalTest.Security.TransportSecurity.Tests#IdentityTests.VerifyServiceIdentityMatchDnsEndpointIdentity
FunctionalTest.Security.TransportSecurity.Tests#Tcp_ClientCredentialTypeCertificateCanonicalNameTests.TcpClientCredentialType_Certificate_With_Only_CanonicalName_EchoString
FunctionalTest.Security.TransportSecurity.Tests#Tcp_ClientCredentialTypeCertificateCanonicalNameTests.TcpClientCredentialType_Certificate_With_Only_CanonicalName_EchoString
FunctionalTest.Security.TransportSecurity.Tests#Tcp_ClientCredentialTypeCertificateCanonicalNameTests.TcpClientCredentialType_Certificate_With_Only_CanonicalName_EchoString
FunctionalTest.Security.TransportSecurity.Tests#Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_With_ServerAltName_EchoString 

**Call Stack**
Unhandled exception of type System.ServiceModel.Security.SecurityNegotiationException : The X.509 certificate CN=WCFCORESRV4, O=DO_NOT_TRUST, OU=Created by https://github.com/dotnet/wcf; F435753A4EB99DFE3FC69646BF781B76F58B0B13 chain building failed. The certificate that was used has a trust chain that cannot be verified. Replace the certificate or change the certificateValidationMode. CRL has expired \n---- System.IdentityModel.Tokens.SecurityTokenValidationException : The X.509 certificate CN=WCFCORESRV4, O=DO_NOT_TRUST, OU=Created by https://github.com/dotnet/wcf; F435753A4EB99DFE3FC69646BF781B76F58B0B13 chain building failed. The certificate that was used has a trust chain that cannot be verified. Replace the certificate or change the certificateValidationMode. CRL has expired 
 at System.ServiceModel.Channels.SslStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__19.MoveNext()

**Comment by StephenBonikowsky** [comment]
This may be related to #954 
 According to @mconnew 
"Client certificates only don’t work for https, this is NetTcp where they should work. The chain likely can’t be built because it can’t use the certificates we attempted to install."

**Comment by StephenBonikowsky** [comment]
Updated initial comment with the latest list of failing tests due to this issue. I can confirm that these tests all fail in Helix on the *nix platforms except Debian runs which currently has worse problems.

**Comment by roncain** [comment]
It is possible we are failing to install the certs on *nix (a likely scenario until we resolve our setup issues on *nix) and may be attempting to use stale certs still on the machines found by name only.  If we could get Console output for Helix, we would know whether we installed, matched by thumbprint, or matched by name.

**Comment by iamjasonp** [comment]
These tests pass when manually run on OS X and certificates installed. This is not a bug, but a test issue, which is manifesting itself when certs aren't properly installed on the target machine. 

```
PASS	FunctionalTest.Binding.Custom.Tests#CustomBindingTests.DefaultSettings_Tcp_Binary_Echo_RoundTrips_String 
PASS FunctionalTest.Security.TransportSecurity.Tests#IdentityTests.ServiceIdentityNotMatch_Throw_MessageSecurityException
PASS FunctionalTest.Security.TransportSecurity.Tests#IdentityTests.VerifyServiceIdentityMatchDnsEndpointIdentity
PASS FunctionalTest.Security.TransportSecurity.Tests#Tcp_ClientCredentialTypeCertificateCanonicalNameTests.TcpClientCredentialType_Certificate_With_Only_CanonicalName_EchoString
PASS FunctionalTest.Security.TransportSecurity.Tests#Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_With_ServerAltName_EchoString
```

Once we fix #1102, this issue should be dealt with. Because they're still likely going to be failing in Helix, I will move this issue out to the next milestone and mark this a test bug (rather than a product bug)

**Comment by roncain** [comment]
Thanks @iamjasonp . Question: how did you install the certs on OS X?  Did you use BridgeCertificateInstaller?  It is my understanding @mconnew updated this exe, so except for renaming the .exe and .sh, I think #1102 is done.  It would be good to know whether this exe was sufficient to make these tests pass on OS X.

Incidentally, these same tests are failing for all *nix platforms on Helix as well as on my own Ubuntu VM.  I'm trying to understand whether BridgeCertificateInstaller is sufficient for all the Helix machines (as well as to understand why it still doesn't allow these tests to pass on my Ubuntu box).

**Comment by iamjasonp** [comment]
On OS X, I had to install the certs into the keychain manually. The reason we have to manually install this is because the default installation of cURL is different - as explained in [in this thread](https://github.com/dotnet/wcf/issues/952#issuecomment-225070292).

I will work on automating this for different OSes. Unfortunately for now, this script only is known to work well for Ubuntu - other distributions haven't yet been tested against this.

**Comment by iamjasonp** [comment]
#1313 should help with this issue

**Comment by iamjasonp** [comment]
Confirmed - when running OS X tests with #1313 installed, we are seeing these tests pass
