### ISSUE TITLE
Create [ConditonalFact] conditions for tests with special requirements

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#958]
We have certain classes of tests that need xunit traits defined for them. Consider this a living list of traits that we need to create:

Tests requiring:
* [x] Client certificate installation - Windows / \*nix **[Client_Certificate_Installed]**
Such tests require that the test (client) machine is provided with a certificate generated by a Certificate Authority trusted by the server. The test (client) machine must install this certificate to its user store, and then use the certificate with this thumbprint to access the WCF test service. Upon finishing the test, the cert MUST be removed from the machine. 

* [x] Client machine (Windows) domain joined **[Domain_Joined]**
For testing ambient Kerberos/NTLM credentials. Such tests require the test (client) machine is joined to an Active Directory domain or Azure Active Directory Domain Services domain. Note that this does not mean MDM joined via Azure Active Directory - that is not sufficient. If using AAD DS, there need not be an additional server machine as AAD DS provisions a domain controller capable of acting as a TGT

* [x] Client (\*nix, OS X): Kerberos ambient credential setup/destroy **[Client_Linux_Domain_Joined]** **
For testing ambient Kerberos credentials. Such tests require that the test (client) machine to have a gssapi package installed, and the tests must be able to run kinit and kdestroy under a user context. Prior to testing, kdestroy must be run, then kinit must be run and provided with valid user credentials for the target Kerberos Realm. After the test, kdestroy must be run. 

* [x] Client (\*nix, OS X): Kerberos explicit credential setup/destroy
For testing explicit Kerberos credentials. Such tests require that the test (client) machine to have a gssapi package installed, and the tests must be able to run kinit and kdestroy under a user context. Prior to testing, kdestroy must be run. The test must be supplied with valid Kerberos credentials for the target Kerberos Realm, and the test (via .NET Core) is to obtain the Kerberos ticket from the TGT. After the test, kdestroy must be run. 

* [x] Service: server machine is domain joined **[Server_Domain_Joined]**
In conjunction with clients that require Kerberos, the server must be run on a machine joined either to an Active Directory domain or an Azure AD Directory Services domain. The server/domain must provide a set of valid user credentials with which to log onto the domain and to acquire Kerberos tickets from it. 
~~We can probably always set this condition to be true in CI/Helix~~ I think we need to set up the CI server box such that it is domain joined. It will avoid many of the issues around testing that we have today where these tests are disabled. 

* [x] Service: server machine SPN specified (server required to run as LOCAL SERVICE) 
From our current testing, in order for us to do sufficient testing where the test (client) machine can hit a WCF service machine with an SPN, the server must be capable of registering itself to the machine SPN (e.g., host/TESTSERVER.TESTDOMAIN.COM)

* [x] Root certificate installation **[Root_Certificate_Installed]**
For all tests involving secure transports (e.g., HTTPS), we must either install a generated trusted root certificate authority certificate to the client machine, or ensure that the server machine has a certificate signed by a universally recognized certificate authority. Generally we prefer to use a generated trusted root CA as it allows us to perform other testing such as certificate revocation or certificate expiry scenarios whereas other public CAs will not allow us to do such things. 
_Note: implies access to the certificate revocation list as well._

* [x] UserName_And_Password_Available This condition would be true only when TestProperties have been provided with a username and password (defaults would be blank). This is needed for domain tests such as Digest auth.

**Comment by roncain** [comment]
Consider use of [ConditionalFact] for these too.  Right now trait-based alternatives silently don't run the tests, but @StephenBonikowsky has mentioned it is better for reporting to see which tests were explicitly skipped and why.  I believe [ConditionalFact] will help with the latter part.  I'm thinking we might invent a new TestProperty that we can use for all of these categories so users could say
```
build /p:IncludeWcfTests="Cert;Domain"
```
When not specified like this, these tests should show as "skipped because XYZ".

**Comment by iamjasonp** [comment]
Sure - I think we should consider this workitem a "let's find a good way to skip certain classes of tests" item, rather than prescribe the use of traits

**Comment by roncain** [comment]
PR #978 is a proposed approach to this issue.  Comments welcome there or here.

**Comment by roncain** [comment]
@iamjasonp -- could I ask you to help enumerate which conditions we need to wire up now and which can wait?  Also, when would we specify that the server needs to be domain joined without also specifying the same for the client?

**Comment by roncain** [comment]
PR #978 is merged, and build tools have been updated to allow multiple conditions.  I'm leaving this issue open until the newer xunit.netcore.extensions package appears on the dotnet-core feed.  At that point, we really do need some concrete choices about what these conditions are and how they are named.

/cc @iamjasonp @zhenlan

**Comment by zhenlan** [comment]
Agree with @roncain. @iamjasonp, why don't you go ahead and make proposals of necessary condition strings that we can use in ConditionalFactAttribute?

**Comment by zhenlan** [comment]
@iamjasonp this is assigned back to you and moved to current milestone. Please do make proposals of conditions that we need to get discussion going.

**Comment by iamjasonp** [comment]
I think the ones that will end up wiring later are the server side scenarios, e.g., those requiring Kerberos and domain join. I crossed out one of those above that I don't think is necessary.

**Comment by roncain** [comment]
Thanks @iamjasonp for the good explanations. I have a few questions to help me understand how to proceed:
- When does a test need to distinguish between Client_Windows_Domain_Joined and Client_Linux_Domain_Joined?  Would the test itself  be written differently for each?  Can these be combined into a single Client_Domain_Joined and make the condition detector implementation fork based on current platform ID?

- When does a test need to distinguish (or specify both) client vs server domain-joined?  Is it adequate to say only that it needs to be domain-joined and let the condition detector validate both are true?   For example, what kind of test would operate in a situation where only the client was domain-joined or only the server?

- We currently have a couple placeholder conditions, SPN_Available and Kerberos_Available.  Do you see a need to retain these? 

- When wiring up our current conditions, it was often unclear to me when to assert a test needed Root_Certificate_Installed and/or Client_Certificate_Installed.  I think you have concluded that any test that actively requires a client certificate should assert Client_Certificate_Installed.  Does it also need to assert Root_Certificate_Installed, or can one imply the other? 

- Do you see a need to create conditions for platform ID?  [ConditionalFact] effectively eliminates the ability to use [PlatformSpecific], but we could trivially add conditions for ID (Is_Windows, Is_AnyUnix, Is_OSX, Is_NET_Native).

I guess in a nutshell it comes down to distinguishing between what the individual tests say they need to run, versus how the condition detector is implemented. I view the conditions names as being only "I run only when X is true" and I view the detectors as being "Well, is X true or can I make it true?".

**Comment by roncain** [comment]
I'd like to add to the list:
* [ ] UserName_And_Password_Available
This condition would be true only when TestProperties have been provided with a username and password (defaults would be blank).  This is needed for domain tests such as Digest auth.

**Comment by iamjasonp** [comment]
Added to the list, @roncain :)

**Comment by iamjasonp** [comment]
Closing this issue. We've dealt with all the ConditionalFacts listed in this issue.
