### ISSUE TITLE
Custom validation of server SSL Certificate not working.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#959]
Support for this needs to be added to HttpClient API.
Issue opened in corefx repo: dotnet/corefx#4476

Failing test case...
-   Security.TransportSecurity.Tests#HttpsTests.ServerCertificateValidation_EchoString

**Comment by mconnew** [comment]
I've removed the Linux and OSX tags as this now works on those platforms. Keeping the bug open as we still can't do custom validation of the server certificate because of lack of support in the UWP HttpClient api.

**Comment by zhenlan** [comment]
Thanks @mconnew.

> we still can't do custom validation of the server certificate because of lack of support in the UWP HttpClient api.

Is there an issue in corefx tracking this?

**Comment by roncain** [comment]
Tests that fail for me include:
* ServerCertificateValidation_EchoString
* Https_SecModeTrans_CertValMode_PeerTrust_Fails_Not_In_TrustedPeople
* Https_SecModeTrans_CertValMode_ChainTrust_Succeeds_ChainTrusted
* Https_SecModeTrans_CertValMode_PeerOrChainTrust_Succeeds_ChainTrusted

**Comment by roncain** [comment]
It looks like CoreFx has issue https://github.com/dotnet/corefx/issues/7623 open for 1.2.0 to update their contracts, and deal with this issue there.

**Comment by zhenlan** [comment]
This is pending to pick up updated Windows MD.
