### ISSUE TITLE
Verify client cert scenarios work on Mac OS X

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#962]
We don't have automated test coverage for client cert scenarios on *nix due to #700 today, but we should verify it on Mac one way or anther before RTM.

**Comment by iamjasonp** [comment]
#700 talks about automating this, but agree that we should be manually verifying this. We may need to do this on a periodic basis because neither our nightlies or CI are covering this scenario at the moment.

**Comment by iamjasonp** [comment]
I've been able to verify this works by manually testing this on an OS X box.

**Comment by zhenlan** [comment]
Great. Thanks @iamjasonp. We can use #700 to track automated testing and close this one now.

**Comment by iamjasonp** [comment]
Closing per @zhenlan's comment, we'll use #700 to track this issue
