### ISSUE TITLE
Custom certificate validation for HTTPS transport is ignored

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#997]
I am setting a X509CertificateValidator on a factory using the HttpsTransportBindingElement as the transport. Also setting the CertificateValidationMode to X509CertificateValidationMode.Custom.

When I make calls on the channel, the X509CertificateValidator.Validate is not called.

Setting the handler:
```
         var factory = new ChannelFactory<T>(
             new CustomBinding(
                    new TextMessageEncodingBindingElement(
                        MessageVersion.Soap11, System.Text.Encoding.UTF8), 
                    new HttpsTransportBindingElement() {
                        AllowCookies = true
                    }), 
             new EndpointAddress(new Uri(serviceUrl)));

         factory
            .Credentials
            .ServiceCertificate
            .Authentication
            .CertificateValidationMode = 
                X509CertificateValidationMode.Custom;

         factory
            .Credentials
            .ServiceCertificate
            .Authentication
            .CustomCertificateValidator = 
                new CustomX509CertificateValidator();
```

Dependencies:
```
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002347"
    },
    "System.ServiceModel.Primitives": "4.1.0-rc3-24012-00",
    "System.ServiceModel.Http" : "4.1.0-rc3-24012-00"
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
```

The full repro code sample: 
[ReproCustomSslValidation.zip](https://github.com/dotnet/wcf/files/215413/ReproCustomSslValidation.zip)

Testing on Win10 x64, CLI : 1.0.0-rc2-002347

**Comment by mconnew** [comment]
There are two different places to set certificate authentication. One is the one that you used, and the other is factory.Credentials.ServiceCertificate.Authentication.SslCertificateAuthentication. This second one defaults to null and needs a new instance of X509ServiceCertificateAuthentication() to be created and set. Unfortunately, it looks like we haven't included the public constructor in our contracts. I'll make a fix for this, but for now, there's a simple workaround you can do.
```csharp
    factory.Credentials.ServiceCertificate.SslCertificateAuthentication = 
        factory.Credentials.ServiceCertificate.Authentication;
```

**Comment by atanasa** [comment]
Thanks, the workaround seems to work for me. Once you complete the fix, what should be the proper way to do this - set the configuration on the SslCertificateAuthentication or Authentication property?

**Comment by mconnew** [comment]
SslCertificateAuthentication is used to specify properties to validate the server's certificate. Authentication is used to specify a client certificate to pass to the server.

**Comment by atanasa** [comment]
There is one more issue - this does not run on Ubuntu - when I run it, I get the exception:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler..ctor()
   at System.ServiceModel.Channels.HttpsChannelFactory`1.GetHttpMessageHandler(EndpointAddress to, SecurityTokenContainer clientCertificateToken)
   at System.ServiceModel.Channels.HttpChannelFactory`1.GetHttpClient(EndpointAddress to, NetworkCredential credential, TokenImpersonationLevel impersonationLevel, AuthenticationLevel authenticationLevel, SecurityTokenContainer clientCertificateToken)
   at System.ServiceModel.Channels.HttpChannelFactory`1.<GetHttpClientAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.<GetHttpClientAsync>d__25.MoveNext()
....

**Comment by mconnew** [comment]
This looks like a bug in the build of System.Net.Http that you are using. We have end-to-end tests which verify this scenario. One thing to know is that client certificates aren't supported on Linux yet. The bug to track progress on this is dotnet/corefx#7623. Once that is complete, we will make changes to WCF to use these changes and client certificates should then be supported on all platforms.

**Comment by atanasa** [comment]
Can you provide a matching build for WCF and Microsoft.NETCore.App? The matching builds that I somehow uncovered give me this error:

**"Server certificate validation not supported yet"**

The stack trace:
```
at System.ServiceModel.Channels.HttpsChannelFactory`1.AddServerCertMappingOrSetRemoteCertificateValidationCallback(ServiceModelHttpMessageHandler messageHandler, EndpointAddress to)
at System.ServiceModel.Channels.HttpsChannelFactory`1.GetHttpMessageHandler(EndpointAddress to, SecurityTokenContainer clientCertificateToken)
...
```

Looking at the code of `AddServerCertMappingOrSetRemoteCertificateValidationCallback` there is indeed such an exception.

The builds that I managed to restore are:

```
  "dependencies": {
    "Microsoft.NETCore.App": "1.0.0-rc2-3002700",
    "System.ServiceModel.Http" : "4.1.0-rc2-24027"
  },
```

**Comment by mconnew** [comment]
@atanasa, this should be supported in our RTM release. Are you still having this issue?

**Comment by atanasa** [comment]
It is ok now

**Comment by brunobertechini** [comment]
Hi there I ran in the same issue. But my case is i cant get rid of the error System.ServiceModel.Security.SecurityNegotiationException : Could not establish trust relationship for the SSL/TLS secure channel with authority  even settings those options:

```c#
credentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication();
credentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = X509CertificateValidationMode.None;
credentials.ServiceCertificate.SslCertificateAuthentication.RevocationMode = X509RevocationMode.NoCheck;
credentials.ServiceCertificate.Authentication.CertificateValidationMode = X509CertificateValidationMode.None;
credentials.ServiceCertificate.Authentication.RevocationMode = X509RevocationMode.NoCheck;
```

**Comment by brunobertechini** [comment]
If I specify a custom validator, its never called:

```c#
public class IgnoreServerCertificatesValidator : X509CertificateValidator
    {
        public override void Validate(X509Certificate2 certificate)
        {
             // Empty
        }
    }
```

```c#
credentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = X509CertificateValidationMode.Custom;
credentials.ServiceCertificate.SslCertificateAuthentication.CustomCertificateValidator = certValidator;
```

```c#
credentials.ServiceCertificate.Authentication.CertificateValidationMode = X509CertificateValidationMode.Custom;
credentials.ServiceCertificate.Authentication.CustomCertificateValidator = certValidator;
```

**Comment by brunobertechini** [comment]
After several tries, i've found out i need to set this at Binding level in order to the custom validator be called:

```c#
binding.Security.Mode = BasicHttpsSecurityMode.Transport;
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
```

Then with an empty validator the error is gone :)

**Comment by iyrwis** [comment]
Hi, @brunobertechini 

Do you mean you cannot get rid of errors (Could not establish trust relationship for the SSL/TLS secure channel) even you set settings below with NoneMode?

credentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication();
credentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = X509CertificateValidationMode.None;
credentials.ServiceCertificate.SslCertificateAuthentication.RevocationMode = X509RevocationMode.NoCheck;
credentials.ServiceCertificate.Authentication.CertificateValidationMode = X509CertificateValidationMode.None;
credentials.ServiceCertificate.Authentication.RevocationMode = X509RevocationMode.NoCheck;

**Comment by iyrwis** [comment]
Hi, @brunobertechini 

Your final solution is here and I have question: You use Custom binding not BasicHttpBinding, right? So why can you use the below setting? 


After several tries, i've found out i need to set this at Binding level in order to the custom validator be called:

binding.Security.Mode = BasicHttpsSecurityMode.Transport;
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
Then with an empty validator the error is gone :)
